### ISSUE TITLE
PropTypes error in RN 0.50.x

### ISSUE THREAD

**Issue by moonjava2005** [react-native-community/react-native-camera#1001]
Dear all,
I try using react-native-camera version 1.0.. alpha
I found incompatible error with RN 0.50.x
Should change
import React, {Component} from 'react';
to
import PropTypes from 'prop-types';
Best regards,

**Comment by thatjuan** [comment]
Are you sure you're pulling the right package? Current version of this package is 0.12.0 and it has no PropType errors on RN 0.50

**Comment by moonjava2005** [comment]
Dear you guys,
I'm using 'react-native-camera' version 1.0.0-alpha1

**Comment by hawkup** [comment]
@moonjava2005 the latest version is 0.12.0 on **Master** branch
1.0.0-alpha1 is the version on [**Next** branch](https://github.com/lwansbrough/react-native-camera/blob/ddd9ba7c9fa5e6146312b172bd3d97e3539da028/package.json#L7) but it has not updated since Jan 2017

**Comment by ospfranco** [comment]
rn ~0.50.0 support should be on master, read the README and update accordingly
