### ISSUE TITLE
Tap to Focus doesn't work on android?

### ISSUE THREAD

**Issue by bvv218** [react-native-community/react-native-camera#1003]
I am trying to implement Tap to Focus, and when I put ```touchToFocus``` in Camera, it doesn't seem to work on Android (haven't tested on iOS). Can someone please explain if this is the right way to do it or if it just doesn't work on android?

**Comment by GauravBuche** [comment]
From README.md - 
"Android: This callback is not yet implemented. However, Android will automatically do tap-to-focus if the device supports auto-focus; there is currently no way to manage this from javascript."

**Comment by jim-binea** [comment]
How about this question? There is any way to do "Tap to Focus" on android?
