### ISSUE TITLE
SIGABRT when recording video on iOS

### ISSUE THREAD

**Issue by thatjuan** [react-native-community/react-native-camera#1006]
**Env:**
React Native: 0.49.3
Yarn: 1.3.2
RCTCamera: 0.12.0
Xcode 9.1
Device: iOS 11.1.2 (on an iPhone 6S+)

**Issue:**
My Camera declaration:

```
            <Camera
              ref={(cam) => {
                  this.camera = cam;
              }}
              style={{flex:1}}
              aspect={Camera.constants.Aspect.fill}
              captureMode={Camera.constants.CaptureMode.still}
              captureTarget={Camera.constants.CaptureTarget.disk}
              captureQuality={Camera.constants.CaptureQuality.photo}
              type={this.state.cameraType}
              flashMode={this.state.flashMode}
              keepAwake={true}
              onZoomChanged={() => {}}
              onFocusChanged={() => {}}
            />
```

When I call:

```
            this.camera.capture({mode: Camera.constants.CaptureMode.video})
                .then((data) => { ...
```

I get a `SIGABRT` (NSException) crash right on [this line](https://github.com/lwansbrough/react-native-camera/blob/59a0b44c71c7b13601dfd34b43714bf8cbb198eb/ios/RCTCameraManager.m#L786).

I've been trying to debug it, but there's a lot of context to go through. It doesn't seem to be a generic issue that many people run into with AVCaptureMovieFileOutput. There aren't any obvious nils that I can see before the line is reached.

Any clues? Thanks in advance.

**Comment by thatjuan** [comment]
I found the crash is caused by specifying `Camera.constants.CaptureQuality.photo` as the captureQuality.

It'd probably make sense to add guards against that.

**Comment by haofeng123** [comment]
I think I also had a problem How do you solve that ,thank you

**Comment by georgewwindsor** [comment]
I am additionally experiencing this, but only randomly.

**Comment by sibelius** [comment]
Upgrade to RNCamera
