### ISSUE TITLE
capture not working in android 6.0.1 (OnePlus)

### ISSUE THREAD

**Issue by svenvanlierde** [react-native-community/react-native-camera#1008]
Camera.capture is not working on a OnePlus One android 6.0.1. 
It does not log anything in then or catch...
But in the logcat output i have multiple time (before capture)
af_process_parse_stats: Invalid FV data!
af_process: Error processing AF stats!

react-native: 0.48.3
react-native-camera: 0.12.0

Any suggestions? thanks :)

**Comment by karltaylor** [comment]
Also have this problem

**Comment by karltaylor** [comment]
@svenvanlierde can you show me your component? I had a problem where I was underendering the camera before it could complete.

**Comment by svenvanlierde** [comment]
Hi, 

Changing captureTarget={"temp"} to captureTarget={"disk"} solved my problem on OnePlus...

**Comment by sibelius** [comment]
try the experimental RNCamera https://github.com/react-native-community/react-native-camera#experimental
