### ISSUE TITLE
How to add brightness and focus controls?

### ISSUE THREAD

**Issue by THPubs** [react-native-community/react-native-camera#1010]
How can I add brightness and focus controls as shown here:

![brightness](https://user-images.githubusercontent.com/1212023/33366361-0e4873f2-d511-11e7-8548-b86b1b50494b.jpg)

Could not find any way to adjust the brightness and focus.

**Comment by THPubs** [comment]
Any updates?

**Comment by vnmone** [comment]
Is there any way to control exposure (brightness) now?
