### ISSUE TITLE
App crashes in Android white start video recording 

### ISSUE THREAD

**Issue by rahulnakate** [react-native-community/react-native-camera#1011]
I facing issue in android side,  it gives some error  like  
**

> _"Attempt to invoke virtual method 'int com.lwansbrough.RCTCamera.RCTCamera.getOrientation()' on a null object reference"_
![device-2017-11-30-151153](https://user-images.githubusercontent.com/7077797/33424140-e3536636-d5e0-11e7-9278-2e242388151a.png)

**

"react": "16.0.0",
"react-native": "0.50.1",
"react-native-camera": "^0.12.0",

**Comment by SimonErm** [comment]
RCTCamera is deprecated, use RNCamera instead.
