### ISSUE TITLE
how to detect cameras

### ISSUE THREAD

**Issue by DevNamedZed** [react-native-community/react-native-camera#1032]
what is the recommended way to detect if a device has a front camera?

**Comment by Traviskn** [comment]
I'm also curious to know how to detect if a camera is available at all, for example in an app that may be running on an android device with no camera

**Comment by rohitgoyal** [comment]
Anything on this? 
I also need to check if the client has the front camera  available on her device. 
What does the library do if I have type='front' and the front camera is unavailable?
