### ISSUE TITLE
Error While installing react-native-camera plugin

### ISSUE THREAD

**Issue by deepupathak** [react-native-community/react-native-camera#1035]
Hi,
I found an error while install this plugin in my project. I am attaching screen shot of error.

```
React native version - 0.47.1
react-native-camera - 0.6.0
windows 10 64 bit
```

I have tried following commands but nothing happened - 

```
cd android
gradlew clean
```

![camera_error](https://user-images.githubusercontent.com/17025296/33838313-2b5fbf7e-deb5-11e7-8ee8-f9090aa16b7e.PNG)

**Comment by deepupathak** [comment]
@lwansbrough Are you able to look this issue. I need this plugin urgently in my app.

**Comment by sibelius** [comment]
this is a problem with your android build

search for multidex on stackoverflow
