### ISSUE TITLE
Detect If Camera Roll Storage Is Full

### ISSUE THREAD

**Issue by zachrnolan** [react-native-community/react-native-camera#1049]
Is there a specific error thrown when the camera roll storage is full?

We had a user that was trying to record a video and it would just stop recording and not throw any errors. They figured out they had no storage space left on their phone. Once they cleared some photos/videos, they were able to record successfully. 

Any ideas how we can capture this scenario and tell the user they have low storage space?

**Comment by sibelius** [comment]
I think this is responsible of CameraRoll module of react native core https://facebook.github.io/react-native/docs/cameraroll.html instead
