### ISSUE TITLE
Multiple Camera Preview Stream

### ISSUE THREAD

**Issue by rubencg195** [react-native-community/react-native-camera#1050]
I am currently wanting to implement a View where I can show two instances of the <Camera> component. One as the original camera preview and the second one as a secondary component to show filters and object recognition implementation for which I need to have access to the camera stream in real time for image-processing. 

Using a unique component there is no problem, but when trying to add the second one, one of the views shows as a black screen. Also, I haven't find a way to have access to the camera stream for image-processing. 

Note: Both using a dummy camera on an emulator. and the same issue on a real device.

1) Using an unique camera component:

![image](https://user-images.githubusercontent.com/25628940/34071981-3b9055d2-e277-11e7-9eed-699fa7decf47.png)

2) Using two camera components:

![image](https://user-images.githubusercontent.com/25628940/34071994-769bfed8-e277-11e7-8a9d-b4431f362b3e.png)

3) Two camera components, one of them hidden as a comment since it doesn't work two at the same time.
![image](https://user-images.githubusercontent.com/25628940/34072422-34508da2-e27f-11e7-875f-55f47d27d885.png)

**Comment by mateusz-** [comment]
This can also happen when having more than one camera component across scenes when using a router (in my example, react-native-router-flux).

**Comment by sibelius** [comment]
fixed on master with RNCamera

**Comment by rubencg195** [comment]
How can I do to show my camera in two diferentes components, I want to do an app compatible with Google cardboard for augmented reality.

**Comment by mateusz-** [comment]
Thanks @sibelius.

For anyone slightly confused by the update (like me), update your Camera component to [RNCamera](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md) and all should be good.

**Comment by MrPluto** [comment]
Hi @rubencg195 
how do you do **real time image-processing** or **image filter** by using this library?
 can you give me some tips
