### ISSUE TITLE
Android - camera using onBarCodeRead crashes app on second instance

### ISSUE THREAD

**Issue by eltanno** [react-native-community/react-native-camera#1054]
We are using the camera in one screen of a multi screen app on Android. If you add a onBarCodeRead handler to the camera instance the first time you load the camrea screen it is fine. The second time you load the screen the app crashes. This is a bug in the Java code. In RTCCameraViewFinder this code results in a crash as the camera.getParameters() is unpopulated. I think the previous instance of the camera isnt released properly. If you move these lines inside the try / catch block everything works fine.  

RTCCameraViewFinder.java line 309
```
                Camera.Size size = camera.getParameters().getPreviewSize();
                int x = 0;
                int y = 0;
                int width = size.width;
                int height = size.height;
```
I will submit a PR with the code change.

**Comment by eltanno** [comment]
Looks like the master branch has this fix in already, but not the NPM released version

**Comment by charleycesar** [comment]
when it will be publish??? It's happen with me too

**Comment by sibelius** [comment]
Fixed on latest release
