### ISSUE TITLE
Sensor orientation checker overtakes motion in entire app

### ISSUE THREAD

**Issue by card-b** [react-native-community/react-native-camera#1058]
According to the Apple docs:

> Important
An app should create only a single instance of the CMMotionManager class. Multiple instances of this class can affect the rate at which data is received from the accelerometer and gyroscope.

I'm having difficulty writing another package that relies on the CMMotionManager class while this package is included in my project. Is there any chance that the sensorOrientationChecker might be conditionally created when it's needed rather than when the package is initialized? (or perhaps, is there a workaround that I'm not seeing?) It seems heavy handed to need to use the gyroscope and accelerometer to determine orientation for an image.

**Comment by SimonErm** [comment]
Is this still an Issue?
