### ISSUE TITLE
Native system UI with success/cancel callback? (Android)

### ISSUE THREAD

**Issue by Noitidart** [react-native-community/react-native-camera#1059]
On iOS to launch native camera UI to take photo/video recording we use `ImageRecorderIOS.openCameraDialog` - https://facebook.github.io/react-native/docs/imagepickerios.html#opencameradialog - which has a success and error callback. This launches native camera UI and gets back photo/camera/cancel in the callback.

I need the equivalent for Android, can we do this with this module? Launching native system camera photo/video taking UI?

**Comment by sibelius** [comment]
not sure, ask on stackoverflow and let us know
