### ISSUE TITLE
camera preview not start again and first taken image shows on screen (only with samsung mobile and tabs)

### ISSUE THREAD

**Issue by ahmad-hassan-arbisoft** [react-native-community/react-native-camera#1063]
when i capture first image the image taken stay on screen and camera not starts again

**Comment by hardcodet** [comment]
Same here using Master. Samsung S6, no tabs though.

**Comment by wbroek** [comment]
Same here on the S6

**Comment by OatsAndSquats25** [comment]
Same thing for me on S6 and S7

**Comment by sibelius** [comment]
RNCamera or RCTCamera?

**Comment by OatsAndSquats25** [comment]
RCTCamera

**Comment by OatsAndSquats25** [comment]
This bug is solved using RNCamera. Thank you :)
