### ISSUE TITLE
Сapture promise never resolves on Android.

### ISSUE THREAD

**Issue by VTSingle** [react-native-community/react-native-camera#1067]
Body: 
using the example from github 

takePicture() {
    const options = {};
    this.camera.capture({metadata: options})
      .then((data) => console.log(data))
      .catch(err => console.error(err));
  }

Invoking takePicture function on some Android devices triggers neither 'then' nor 'catch' callbeck. 
The problem is faced on xiaomi and Meizu phones. Permissions for camera use were added to AndroisManifest. 
Interestingly, but in debug mode this problem doesn't happen. 

On Samsung S8, after some times of using camera capture the application is crashed.

**Comment by kumarvish** [comment]
Are you making any changes to local state in this component? I experienced this behavior if there was re-rendering due to change in local state.

**Comment by PanRada** [comment]
Have issues on similar problem with promise.

**Comment by ranjitnadar** [comment]
any solution for this promises issue on android

**Comment by dann1609** [comment]
I has this problem to, but only on android. On IOS it works very well!

I tried changing etccamera to RNCamera but issue still present (Problem is bigger in RN)
