### ISSUE TITLE
Aspect ratio on Android. Help!

### ISSUE THREAD

**Issue by VTSingle** [react-native-community/react-native-camera#1073]
Guys, I need to get a photo as a result with a 4: 3 aspect ratio.

I'm using the camera property
Camera.constants.CaptureQuality ["480p"]

on Samsung all is well, I get a photo 4: 3 and 480: 640.
But on Meizu and Xiaomi, I get a photo with a 480: 800 aspect ratio. But I need to get  also 480: 640.

How can I achieve this?

**Comment by sibelius** [comment]
check this PR https://github.com/react-native-community/react-native-camera/pull/1071
