### ISSUE TITLE
[Android] Need more quality than 'high' when capture image.

### ISSUE THREAD

**Issue by ducpt2** [react-native-community/react-native-camera#1075]
[Android] Need more quality than 'high' when capture image.
Quality is  lower than default camera image (4608x3456 and size image is 3-4M # 1,3M when capture with react-native-camera).

**Comment by miguelcanobbio** [comment]
Same here but in my case is whit iOS, when i capture an image with react-native-camera the size is 573KB while that when i use default camera, the size's image is 1.5M

**Comment by sibelius** [comment]
On Android you can try the experimental RNCamera
