### ISSUE TITLE
RNCameraExample does not run on device

### ISSUE THREAD

**Issue by ospfranco** [react-native-community/react-native-camera#1081]
Tried to run RNCameraExample on a moto g4 with android 7.

Ran into:

![screenshot_20180109-114700](https://user-images.githubusercontent.com/1634213/34717526-b33ec018-f533-11e7-9f40-0a1e9ea2dbd9.png)

**Comment by sibelius** [comment]
add a null check here https://github.com/react-native-community/react-native-camera/blob/14af35aca3e4a73a2a5999031a924deadb026e79/android/src/main/java/org/reactnative/camera/events/FaceDetectionErrorEvent.java#L50

**Comment by ospfranco** [comment]
should be fixed with #1082
