### ISSUE TITLE
add RNCamera ios implementation

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#1084]
Based on expo camera module

- [x] Camera component (https://github.com/expo/expo/tree/master/ios/Exponent/Versioned/Core/Api/Components/Camera)
- [x] FaceDetector (https://github.com/expo/expo/tree/master/ios/Exponent/Versioned/Optional/FaceDetector)

**Comment by sibelius** [comment]
https://github.com/react-native-community/react-native-camera/pull/1128

only missing FaceDetector part

**Comment by tirrorex** [comment]
Any chance to get a changelog with the differences between the two components?
