### ISSUE TITLE
Upgraded android build-tools and compile conflicts

### ISSUE THREAD

**Issue by afilp** [react-native-community/react-native-camera#1088]
@sibelius I see that you already added the solution in README. I mentioned the problem in slack and you immediately solved it!. Thank you!

Solution here:
https://github.com/react-native-community/react-native-camera/blob/master/README.md#meta-data-android-26

In addition, Oscar in slack requested that I create a ticket with the following suggestion for the upgraded android build-tools issue:

_I think you upgraded android build-tools, would this be solved by updating the root project build tools version as well?_

Would that work?

**Comment by ospfranco** [comment]
Not necessary if sibelius solution already works
