### ISSUE TITLE
Android cropToPreview only cropping left/right sides

### ISSUE THREAD

**Issue by sunweiyang** [react-native-community/react-native-camera#1089]
This is related to #1057.

I am running RN 0.51.0 and react-native-camera master as of bc975b4bac49a31b8ff885efddd36c456da7c262.

On iOS it works great, but on Android I'm seeing that it only crops the left/right sides off. In other words, I've defined my preview to be a square, but what I get instead is a tall skinny rectangular captured image.

I have the following constant defined:
```
const windowWidth = Dimensions.get('window').width;
```

A button is defined that runs this function when pressed (very similar to README example):
```
  takePicture() {
    var component = this;
    const options = {};
    //options.location = ...
    this.camera.capture({metadata: options})
      .then((data) => {
        console.log(data);
      })
      .catch(err => console.error(err));
  }
```

My render method contains:
```
        <Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          style={{width: windowWidth*0.8, height: windowWidth*0.8}}
          type={'front'}
          orientation={'portrait'}
          cropToPreview={true}
        />
```

**Comment by mckn** [comment]
@sunweiyang awesome feedback! Thanks! I will try to setup your example and fix the issue.

**Comment by mckn** [comment]
@sunweiyang Some more questions so I can debug.

1. What orientation settings do you have on your app? 
2. What orientation do you have when taking the photo?

Thanks in advance!

**Comment by sunweiyang** [comment]
Thanks @mckn for looking into this.

I am forcing portrait mode on my app. Specifically, I have the following in my AndroidManifest.xml:
```
        <activity android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:windowSoftInputMode="adjustPan"
            android:exported="true"
            android:screenOrientation="portrait" />
```

**Comment by claudiumatei** [comment]
Hi, I also confirm the issue on Android (no matter the orientation of the device).

**Comment by eoy** [comment]
I can also confirm this issue on Android.

**Comment by t407289575** [comment]
Why the 'cropToPreview={true}'  is invalid for me ,both Android or IOS.

    "react-native": "0.48.4",
    "react-native-camera": "^0.13.0",

my code:
<Camera
                    ref={(cam) => {
                        this.camera = cam;
                    }}
                    style={{
                        width:SCREEN_WIDTH * 0.8,
                        height: SCREEN_WIDTH * 0.5,
                    }}
                    captureTarget={Camera.constants.CaptureTarget.cameraRoll}
                    aspect={Camera.constants.Aspect.fill}
                    captureQuality={'high'}
                    cropToPreview={true}
                    playSoundOnCapture={false}>


Hope to help

**Comment by Jinran** [comment]
does this issue fixed？

**Comment by eqyiel** [comment]
Ref: https://github.com/react-native-community/react-native-camera/pull/1636
