### ISSUE TITLE
RNCamera takePictureAsync only returns base64 

### ISSUE THREAD

**Issue by ywongweb** [react-native-community/react-native-camera#1099]
### Steps to reproduce
1. Run the RNCameraExample included in the project

### Expected behaviour
```
takePicture = async function() {
    if (this.camera) {
      this.camera.takePictureAsync().then(data => {
        console.log('data: ', data);
      });
    }
  };
```
According to the expo camera doc, takePictureAsync should return an object: 
```
{ uri, width, height, exif, base64 }
```
https://docs.expo.io/versions/latest/sdk/camera.html

### Actual behaviour
The `data` object only contains base64 data

### Environment
Android

**Comment by Fconstant** [comment]
Fixed by #1144
