### ISSUE TITLE
Get camera FOV

### ISSUE THREAD

**Issue by WellDone2094** [react-native-community/react-native-camera#110]
hi, i was wandering if it's possible to get the FOV of the camera, i have seed that in objective-c is possible get it easily doing this 

```
float FOV = camera.activeFormat.videoFieldOfView;
```

where camera is the AVCaptureDevice, but i don't know objective-c so i'm not able to add this feature by my-self

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
