### ISSUE TITLE
The master branch compiled failed on Android.

### ISSUE THREAD

**Issue by jaggerwang** [react-native-community/react-native-camera#1109]
### Steps to reproduce
1. Change the version in package.json from '0.10.0' to 'git+https://git@github.com/react-native-community/react-native-camera'
2. Gradle sync in Android Studio

### Expected behaviour
Gradle sync success.

### Actual behaviour
Gradle sync failed. I'm already using v0.10.0 for a few months, but the qrcode detecting is not good enough, so I want to try the Expo one.
![image](https://user-images.githubusercontent.com/1255011/35036619-dd761c8c-fbaf-11e7-9c0a-90f262b440a1.png)

### Environment
- **Node.js version**: v6.11.3
- **React Native version**: 0.44.3
- **React Native platform + platform version**: Android Studio 3.0

### react-native-camera
**Version**: master

**Comment by sibelius** [comment]
Check Q & A section on README

**Comment by lynkxyz** [comment]
@sibelius si  I was doing but it not working
