### ISSUE TITLE
Cannot compile: `Argument list too long` on another package (`react-native-intercom`) due to `react-native-camera` pod

### ISSUE THREAD

**Issue by afilp** [react-native-community/react-native-camera#1114]
### react-native-camera
**Version**: "master"

When using the `pod`, I get `Argument list too long` on `Intercom`. I am assuming that this is related to ``React`` included in the pod? I do not need this, as React is already included in the XCODE project.

Please check here (another user also mentions `react-native-camera` there:
https://github.com/tinycreative/react-native-intercom/issues/40

Can something be changed on the `podfile` so that all works OK with other packages?
Or, should I do something else?

Thanks a lot!

**Comment by hegelstad** [comment]
Did you figure this out?

**Comment by sibelius** [comment]
check this https://github.com/react-native-community/react-native-camera/issues/1407
