### ISSUE TITLE
Error when archiving on MASTER: .../node_modules/react-native-camera/ios/RCTCameraManager.m:706:54: Use of undeclared identifier 'viewportSize'

### ISSUE THREAD

**Issue by ryd0rz** [react-native-community/react-native-camera#1122]
### Steps to reproduce
1. use master latest
2. archive ios project

### Expected behaviour
shoud not throw error

### Actual behaviour
throws error. please test your pull request before merge.
Here is my PR comment (however, the PR is already merged, and needs fixed):
https://github.com/react-native-community/react-native-camera/commit/0c4161ab1749e236f9773a6ef5ba95dbc0c519e7#diff-67aecadd1220a0eebd27fd0e61cd2b91R706

I had to use master cause of other issues related to not working in latest version of RN.

### Environment
"react": "16.0.0-alpha.12",
"react-native": "0.51.0",
"react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera.git",

### react-native-camera
**Version**: master

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by ryd0rz** [comment]
PR: https://github.com/react-native-community/react-native-camera/pull/1123

**Comment by jgcmarins** [comment]
thanks @ryd0rz
