### ISSUE TITLE
Execution failed for task ':react-native-camera:processDebugAndroidTestManifest'.

### ISSUE THREAD

**Issue by evansherry** [react-native-community/react-native-camera#1129]
### Steps to reproduce
1. Start marke project , but build fail
2. Follow Readme , add tools:node="replace" to AndroidManifest.xml, add this to build.gradle(app)
```
 compile (project(':react-native-camera')) {
        exclude group: "com.android.support"
}
 compile ('com.android.support:exifinterface:26.0.1') {
        force = true;
    }

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            details.useVersion "${rootProject.supportLibraryVersion}"
        }
    }
}
```
3. versions:
```
    gradle : 3.0.1
    compileSdkVersion = 26
    minSdkVersion = 16
    targetSdkVersion = 26
    supportLibraryVersion = '26.1.0'
```

### Expected behaviour
build successful

### Actual behaviour
FAILURE: Build failed with an exception.

* What went wrong:
build fail !
Execution failed for task ':react-native-camera:processDebugAndroidTestManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:exifinterface:26.0.2] AndroidManifest.xml:25:13-35
  	is also present at [com.android.support:support-v4:26.0.1] AndroidManifest.xml:28:13-35 value=(26.0.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at manifestMerger2304450501655821264.xml:23:9-25:38 to override.

### Environment
- **OS**: Mac OS Sieera
- **Node.js version**:   v7.7.4
- **React Native version**:  0.46.1
- **React Native platform + platform version**:  Android 6.0.1 

### react-native-camera
**Version**: npm version  4.1.2

**When I set up add  'tools:replace="android:value" to AndroidManifest.xml, build fail, remove  continue 'tools:replace="android:value" to build success, but I do not want to always be the case**

**Comment by Samykills** [comment]
Stuck with same issue? :(
Do u have any other dependencies in your project...i have react-native-google-places which i suspect might be causing some problems!

**Comment by Samykills** [comment]
build.gradle for react-native-camera has 
dependencies {
  ...
  compile "com.android.support:exifinterface:26.0.2"
}

this is leads to ..
Error:Execution failed for task ':react-native-camera:processDebugAndroidTestManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:exifinterface:26.0.2] AndroidManifest.xml:25:13-35
  	is also present at [com.android.support:support-v4:26.0.1] AndroidManifest.xml:28:13-35 value=(26.0.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at manifestMerger4058125526788706578.xml:23:9-25:38 to override.

**Comment by evansherry** [comment]
Sorry, I'm late, and finally I did not use studio run, I'm in WebStorm run android and ./gradlew + other commands.

**Comment by sibelius** [comment]
follow this https://github.com/react-native-community/react-native-camera#meta-data-android-26

**Comment by ThomLaGreca** [comment]
I followed the above steps and still i get the same error. Every post i find regarding this issue just points to the above meta-data-android-26 link and stops... Help. 

> Error:Execution failed for task ':react-native-camera:processDebugAndroidTestManifest'.
> > Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:exifinterface:26.0.2] AndroidManifest.xml:25:13-35
>   	is also present at [com.android.support:support-v4:26.0.1] AndroidManifest.xml:28:13-35 value=(26.0.1).
>   	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at manifestMerger1679199706524611983.xml:23:9-25:38 to override.


```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile (project(':react-native-camera')) {
        exclude group: "com.android.support"

        // uncomment this if also com.google.android.gms:play-services-vision versions are conflicting
        // this can happen if you use react-native-firebase
        // exclude group: "com.google.android.gms"
    }

    compile ('com.android.support:exifinterface:26.0.1') {
        force = true;
    }

    // uncomment this if you uncommented the previous line
    // compile ('com.google.android.gms:play-services-vision:11.6.0') {
    //    force = true;
    // }
}
```

**Comment by thevishnupradeep** [comment]
@ThomLaGreca meta-data-android-26 link actually helps. add
`exclude group: "com.google.android.gms"`
and add
`maven {
     url "https://jitpack.io"
}`
to your project level build.gradle

**Comment by pielambr** [comment]
@ThomLaGreca Did you ever fix this in the end? I have the same problem as you have

**Comment by Taym95** [comment]
Same issue here!

**Comment by prjmax** [comment]
Same problem, I'm not sure if this is related, I can run the App in Dev mode but when I try to execute assembleRelease I get a "Failed to execute aapt" error

**Comment by sibelius** [comment]
You should disable appt now

In the next React native version 54, it will solve the issue with appt2

**Comment by prjmax** [comment]
you are right @sibelius, adding android.enableAapt2=false in gradle.properties solved the issue, Thanks!

**Comment by sibelius** [comment]
@prjmax could you send a PR to https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md

adding this note about `aapt2`?

**Comment by afilp** [comment]
@sibelius Whatever I do I always have the problem that all others mentioned. The Q&A solutions do not fix the problem. Can you please let us know what else to do?

**Comment by h-sakano** [comment]
In my case, when I change the version specification of "com.android.support:exifinterface", the build will now succeed.

```
dependencies {
    ...
    // compile "com.android.support:exifinterface:26.0.2"
    compile "com.android.support:exifinterface:26.0.1"
}
```

**Comment by satish754ss** [comment]
Error:Execution failed for task ':react-native-camera:processDebugAndroidTestManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:exifinterface:26.0.2] AndroidManifest.xml:25:13-35
	is also present at [com.android.support:support-v4:26.0.1] AndroidManifest.xml:28:13-35 value=(26.0.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at manifestMerger1412991257447853314.xml:23:9-25:38 to override. 
please help to solve this problem

**Comment by arapocket** [comment]
Adding `android.enableAapt2=false` didn't fix anything for me.

**Comment by cvvspb** [comment]
Looks like following the Q/A section https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md **and updating from 1.0.0 to 1.0.1** fixed the issue for me.

**Comment by GarryLaly** [comment]
Following this step https://medium.com/react-native-zone/error-react-native-camera-com-android-support-exifinterface-26-0-2-7e779366c828 I tested is work.
