### ISSUE TITLE
Camera Permission popup

### ISSUE THREAD

**Issue by JJMoon** [react-native-community/react-native-camera#1132]
### Steps to reproduce
1. Get the Camera permission on startup.
2. Turn off camera permission in device setting
3. Return to the app and go to camera screen.

### Expected behaviour
Show permission popup

### Actual behaviour
Show blank screen with 'camera not authorized'
(It crashed at v 0.12.0)

### Environment
- **Node.js version**:  9.3.0
- **React Native version**: 0.50
- **React Native platform + platform version**: iOS 9.0
I didn't test on Android device.

### react-native-camera
**Version**: npm version or "master"

It is not critical, but (I hope) should be fixed.

**Comment by sibelius** [comment]
You can only show permission popup once, if user denied, he needs to go to settings and reenable
