### ISSUE TITLE
capture panorama on Android 

### ISSUE THREAD

**Issue by VTSingle** [react-native-community/react-native-camera#1136]
Guys. Can I use this module to shoot a panorama?
if possible, how?

**Comment by jacob-cross99** [comment]
Plus this for iOS~

**Comment by ducpt2** [comment]
+1 Can we shoot a panorama?

**Comment by awnumar** [comment]
Pinging to reopen this issue. What are the requirements for implementing this?

**Comment by MateusAndrade** [comment]
@awnumar maybe you can give a look at: https://developer.android.com/training/camerax
