### ISSUE TITLE
iOS build failure due to framework search path on master

### ISSUE THREAD

**Issue by tirrorex** [react-native-community/react-native-camera#1152]
### Which implementation are you using

RCTCamera master with react-native 0.51

### Steps to reproduce
Create a project with react-native init (react will be added in libraries
Added react-native-camera to libraries
pod install
Try to build

### Expected behaviour
Project should compile normally

### Actual behaviour
Not compiling.

Problem comes from https://github.com/react-native-community/react-native-camera/commit/8ebeb530c55b6e7559ace7cec3447713e458c235#diff-c35a6eca356820416e0423eb03754a34

Path were added for FRAMEWORK_SEARCH_PATHS, HEADER_SEARCH_PATHS and LIBRARY_SEARCH_PATHS making the compilation fail with error : 
"Argument list too long: recursive header expansion failed at /Users/thibautnoah/Mvpstars/frimousse/node_modules/react-native-camera/ios/../../../ios/Pods/React/node_modules/fsevents/node_modules/tar-pack/test."

Trying to debug this, problem with submitting a PR will be to test that there is no regression for other users.

**Comment by tirrorex** [comment]
I changed the title, it wasn't clear that the issue was related to master only

**Comment by sibelius** [comment]
@tirrorex check this PR https://github.com/react-native-community/react-native-camera/pull/1153

**Comment by tirrorex** [comment]
Yup thanks, i ended up removing RN and Detector also because i didn't want to add more unecessary frameworks to the project (since pod installing google vision is mandatory atm)

**Comment by nikolas7892** [comment]
I keep getting the same error.... Argument list too long: recursive header expansion failed at /Users/*USER*/*APP*/node_modules/react-native-camera/ios/../../../ios/build/Index/DataStore/v5/records/1G.

**Comment by MaheshNandam** [comment]
I have added Pods at frame relative paths and also [replace master repo at package.json](https://github.com/react-native-community/react-native-camera#how-to-use-master-branch)

but still:
Argument list too long: recursive header expansion failed at ../node_modules/react-native-camera/ios/../../../ios/Pods/React/node_modules/fsevents/node_modules/path-is-absolute.

**Comment by futurechallenger** [comment]
@nikolas7892 Hi have u fixed this problem?

**Comment by arapocket** [comment]
I'm getting this error as well.

**Comment by sibelius** [comment]
check this https://github.com/react-native-community/react-native-camera/issues/1407
