### ISSUE TITLE
Customize Barcode scanner view - Android

### ISSUE THREAD

**Issue by ahetawal-p** [react-native-community/react-native-camera#1156]
### Which implementation are you using
RCTCamera 

Is there a way to add a surrounding box around the scanner view. I am looking at the `zxing` examples and see you can achieve something like this 

![3524e374-e8f7-11e4-83a1-6d2f75b6a50e](https://user-images.githubusercontent.com/8919529/35349461-d50f19f0-00ef-11e8-90d2-bafd364c5875.png)

Is there a way to get a similar view in this module. Barcode reader without bounds certainly doesnt tell users as where they should focus there camera on.

Thank you,

**Comment by ludalex** [comment]
There is #874 that addresses this and more, even though it was recently closed by the author due to the lack of involvement from the repo maintainers to merge his code.

**Comment by jqn** [comment]
@ahetawal-p if you need a quick solution you could use this https://github.com/jqn/AC-QRCode-RN with npm or just extract https://github.com/jqn/AC-QRCode-RN/blob/master/lib/QRScanner.js from this library and create your own component.

**Comment by ahetawal-p** [comment]
@jqn thanks will take look !

**Comment by csumrell** [comment]
I struggled with this for awhile but its actually very simple, just create a visual border and nest it within the RNCamera component

```
import React, { Component } from "react";
import { StyleSheet, View } from "react-native";

export class BarcodeFinder extends Component {
  constructor(props) {
    super(props);
  }

  getSizeStyles() {
    return {
      width: this.props.width,
      height: this.props.height
    };
  }

  render() {
    return (
      <View style={[styles.container]}>
        <View style={[styles.finder, this.getSizeStyles()]}>
          <View
            style={[
              { borderColor: this.props.borderColor },
              styles.topLeftEdge,
              {
                borderLeftWidth: this.props.borderWidth,
                borderTopWidth: this.props.borderWidth
              }
            ]}
          />
          <View
            style={[
              { borderColor: this.props.borderColor },
              styles.topRightEdge,
              {
                borderRightWidth: this.props.borderWidth,
                borderTopWidth: this.props.borderWidth
              }
            ]}
          />
          <View
            style={[
              { borderColor: this.props.borderColor },
              styles.bottomLeftEdge,
              {
                borderLeftWidth: this.props.borderWidth,
                borderBottomWidth: this.props.borderWidth
              }
            ]}
          />
          <View
            style={[
              { borderColor: this.props.borderColor },
              styles.bottomRightEdge,
              {
                borderRightWidth: this.props.borderWidth,
                borderBottomWidth: this.props.borderWidth
              }
            ]}
          />
        </View>
      </View>
    );
  }
}


var styles = StyleSheet.create({
  container: {
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0
  },
  finder: {
    alignItems: "center",
    justifyContent: "center"
  },
  topLeftEdge: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 40,
    height: 20
  },
  topRightEdge: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 40,
    height: 20
  },
  bottomLeftEdge: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: 40,
    height: 20
  },
  bottomRightEdge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 40,
    height: 20
  }
});

```

```
<RNCamera
        ref={cam => {
          this.camera = cam;
        }}
        style={styles.preview}
        onBarCodeRead={data => this.scannedBarcode(data)}
      >
        <BarcodeFinder width={280} height={220} borderColor="red" borderWidth={2} />
      </RNCamera>
```

**Comment by sibelius** [comment]
follow this https://github.com/react-native-community/react-native-camera/issues/1156#issuecomment-370035072

**Comment by ahetawal-p** [comment]
The above solution will just show the borders, but will not restrict the scanning to the areas which are not under the border. So the experience would be confusing as to where exactly a user needs to focus the rectangle at. Not sure why this was closed @sibelius

**Comment by csumrell** [comment]
That is correct in that it won't limit the scanning areas, but in what case is that going to be issue? 

From my experience users think that the barcode scanner doesn't work if there aren't scan lines...so just give them the fake lines

**Comment by Spisaczek** [comment]
Yeah, but limiting scan area should also improve performance.

**Comment by lucasleelz** [comment]
Yes,I also think that this is not very good and requires a real scan code area. @sibelius

**Comment by twxia** [comment]
Boundary seems need to use below method to get the actual corner coordinates: https://github.com/zxing/zxing/blob/7a64f483fd62afb13f651af655200a6bbfefd1db/core/src/main/java/com/google/zxing/aztec/detector/Detector.java#L235 

So `bounds` parameter in `onBarCodeRead` is same behavior in both iOS (`bounds.origin`) and Android.

**Comment by sibelius** [comment]
@twxia can u open another issue and send a pr fixing this?

**Comment by icxcat** [comment]
```
		const x = Number(e.bounds.origin.x);
		const y = Number(e.bounds.origin.y);
                 // IOS
		// const width = Number(e.bounds.size.width);
		// const height = Number(e.bounds.size.height);
                // Android
		const width = Number(e.bounds.width);
		const height = Number(e.bounds.height);
		const viewMinX = (winWidth - 267) / 2;
		const viewMinY = 144;
		const viewWidth = 267;
		const viewHeight = 267;
```

**Comment by wahyuutomoputra** [comment]
u can try this one https://github.com/shahnawaz/react-native-barcode-mask

**Comment by VSV6** [comment]
Thank you so much @wahyuutomoputra ! You saved me from writing the code from scratch! Thanks a lot :)
