### ISSUE TITLE
Need help on how to enable the camera face detector feature

### ISSUE THREAD

**Issue by yh6782** [react-native-community/react-native-camera#1158]
Is there any step by step guide on how to enable the face detection feature in react-native-camera? 

I've change my package.json and imported RNCamera and FaceDetector at my camera screen but I'm still not getting face detection on my camera 

Need a guide and help if anyone out here knows. Thank you!

**Comment by sibelius** [comment]
android or ios?

**Comment by yh6782** [comment]
android

**Comment by sibelius** [comment]
it should just work on master using RNCamera

ping us on expo slack on react-native-camera and we can help

**Comment by harris666** [comment]
how to solve it?

**Comment by sibelius** [comment]
tks
