### ISSUE TITLE
react-native-camera/ios/FaceDetector/RNFaceDetectorUtils.h:12:9:  'GoogleMVDataOutput/GoogleMVDataOutput.h' file not found

### ISSUE THREAD

**Issue by suijunqiang** [react-native-community/react-native-camera#1159]
RCTCamera 

### Steps to reproduce
1. rm -rf node_modules/
2.npm install
3.rnpm link
4,Use Xcode clean/build

### Expected behaviour
Xcode throw out errors:

Showing All Errors Only

Build target RCTCamera of project RCTCamera with configuration Debug
...

Showing All Errors Only
.../node_modules/react-native-camera/ios/FaceDetector/RNFaceDetectorUtils.h:12:9: 'GoogleMVDataOutput/GoogleMVDataOutput.h' file not found

.../node_modules/react-native-camera/ios/FaceDetector/RNFaceEncoder.h:9:9: 'GoogleMobileVision/GoogleMobileVision.h' file not found

...

### Actual behaviour
It can't be fix, I have try a lot times

### Environment
- **Node.js version**: v8.4.0
- **React Native version**:react-native ^0.46.0
- **React Native platform + platform version**: Xcode 9.2;

### react-native-camera
**Version**: I try it base on last & ^0.12.0

It's run well today before I rm -rf node_modules/

**Comment by greatdg** [comment]
try to this link. it works for me. https://github.com/react-native-community/react-native-camera/issues/1151

**Comment by suijunqiang** [comment]
@greatdg 
Thanks for your answer,  it is same issue of mine.
But in the post of #1151 I still can not fix my issue,  so would you please give me a hand  if have some experience .

Thanks & Best Regards
Sui
2018-01-26

**Comment by suijunqiang** [comment]
There is a work around way of back react-native-camera to 0.12.0, and it able to fix my issue.
so Would you please closed it.

Thanks & Best Regards
Sui

**Comment by pohsiu** [comment]
**No Face Detection steps**
If you do not need it and do not want to install the GMV frameworks, open your app xcode project, on the Project Navigator, expand the RNCamera project, right click on the FaceDetector folder and delete it (move to trash, if you want). If you keep that folder and do not follow the GMV installation setps, your project will not compile.

**Comment by hungdev** [comment]
thank @paiou .
as you @pohsiu  say.  after that, clean project by using: comand+ option+shift+k and command + shift + k
