### ISSUE TITLE
iOS: Retake option with simply hiding and showing the camera

### ISSUE THREAD

**Issue by LoganArnett** [react-native-community/react-native-camera#1168]
### Which implementation are you using

RCTCamera or RNCamera?
react-native-camera

### Steps to reproduce
1. Create Camera Instance
2. Take Photo and Display Photo in an Image tag, hide the Camera Component
3. Press Retake button and hide the Photo and Display the Camera again

### Expected behaviour
Able to redisplay the camera component and take another photo

### Actual behaviour
In debug version this works as expected in a release build it freezes the app on press of retake button and eventually crashes

### Environment
- **Node.js version**: 7.9.0
- **React Native version**: 0.50.3
- **React Native platform + platform version**: iOS 11.0

### react-native-camera
**Version**:  "^0.12.0"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

```js
{photoTaken ?
      <View style={styles.circle}>
            <Image source={{ uri: image }} style={styles.photo} />
       </View> :
       <View style={styles.circle}>
             <Camera
                  ref={(cam) => {
                     setCamera(cam);
                   }}
                   style={styles.preview}
                   orientation="landscapeRight"
                   flashMode="auto"
                   captureQuality="720p"
                   mirrorImage={false}
              >
              </Camera>
       </View>
}
```

**Comment by wbyoung** [comment]
I just came across this while looking for something else. I'm using `RNCamera` and having no trouble with this. You may want to include a crash report from the device (the iOS crash report) in order for the project contributors to track this down, though. Without that, this report may not contain the level of information where it'll be easy for them to find where the problem is.

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
