### ISSUE TITLE
react-native-camera crashes on ios and android

### ISSUE THREAD

**Issue by evansherry** [react-native-community/react-native-camera#1173]
### Which implementation are you using

RCTCamera or RNCamera?
RCTCamera (version 0.12.0)

### Steps to reproduce
android 
1.Enter the QR code scanning interface
2. No runtime permissions box, and then click on the surfaceView,
3.throw NullPointerException,Camera.getParamaters () on a null object reference at RCTCameraViewFinder.onTouchEvent (RCTCaneraViewFinder.java:363)

iOS:
1.After entering the QR code scanning interface for the first time.
2.after I refuse the camera permission.
3.I will crash into the QR code scanning interface.

### Expected behaviour
not crash , android should determine whether the current object is null.

### Actual behaviour
crash

### Environment
- **Node.js version**: v7.7.4
- **React Native version**: 0.46.1
- **React Native platform + platform version**: iOS 10.3.3, Android 6.0.1 (mi 4), etc

### react-native-camera
**Version**: npm version or "master"
npm version 4.1.2   
react-native-camera 0.12.0

crash information && unambiguous evidence：
![image](https://user-images.githubusercontent.com/11881751/35515045-1db7d820-0543-11e8-8777-b0c9cd18aa1a.png)
![image](https://user-images.githubusercontent.com/11881751/35515111-3e97f98a-0543-11e8-9e85-ca8e7b057385.png)

Please kill the crash！

**Comment by sibelius** [comment]
try RNCamera
