### ISSUE TITLE
Footprint of Google Mobile Vision on iOS

### ISSUE THREAD

**Issue by ma-pe** [react-native-community/react-native-camera#1178]
Embedding the Frameworks for Google Mobile Vision adds a footprint of around 25 mb to my .ipa-file. 

Is there any chance this will be considerably less in the (near) future?

**Comment by sibelius** [comment]
this is only needed if u want face detection

you should ask google about it

**Comment by ma-pe** [comment]
I do want face detection, but the footprint is immense. 

Following the setup-instructions I added 8 frameworks in order to achieve the face detection. I was just questioning myself, if all are necessary (e.g. the address book framework). :-)

**Comment by sibelius** [comment]
https://developers.google.com/vision/ios/getting-started

**Comment by jgfidelis** [comment]
Unfortunately, there is nothing we can do about it. Google Mobile Vision uses other Google frameworks and at least one of them uses AddressBook (Google utilities I believe). I tried to remove as much as possible, but these are the minimum requirements for the project to compile correctly.

A solution would be to find a face detection framework other than Google's that is lighter and provides the same functionality.

**Comment by ma-pe** [comment]
@jgcmarins Thanks for clarifying.
