### ISSUE TITLE
Image load and show not working right after App install and get permission

### ISSUE THREAD

**Issue by JJMoon** [react-native-community/react-native-camera#1181]
### Which implementation are you using
RNCamera

### Steps to reproduce
1. App install (iOS)
2. Get Camera permission 
3. Take photo
4. Get Save permission
5. Save photo
6. Get file access permission
7. Try to read and show the taken photo >>. only white image is shown.

8. Retake photo
9. Read and show the taken photo >> It's ok.

### Expected behaviour
Should work at the first time.

### Environment
- **Node.js version**: 9.3.0
- **React Native version**: 0.50.3
- **React Native platform + platform version**: iOS 9.0

### react-native-camera
**Version**: 0.13.0

I print the file name in render function, it's fine at the first time. Just cannot show the image.
(uri: "assets-library://asset/asset.J .....)
I tried forceUpdate() with button, it doesn't work.

Thank you for your great work.!!

**Comment by VrajSolanki** [comment]
I believe this is happening as the component you are using to display the image from url (for eg: <Image source={{uri: 'pathToImage'}} ) is mounted before the permissions are given.
To solve this try: 

1. set in state permissionsAvailable variable
2. Ask for permissions and update state accordingly.
3. render component if permissions else <Text>No permissions Available</Text>

I believe this should solve your issue.
