### ISSUE TITLE
When can we expect RNCamera to be part of the release?

### ISSUE THREAD

**Issue by kneza23** [react-native-community/react-native-camera#1185]
Is there some timetable or just some ballpark date? 
It has a lot better perfomance on android then Camera component.

**Comment by jgfidelis** [comment]
We are planning to integrate in some bigger projects and see its performace. If it is stable, we will release a 1.0 version and deprecate RCTCamera. As a schedule, we do not have anything formal, but it should not take too long

**Comment by kneza23** [comment]
Ok cool gl. It would be good to put that into the readme file :)

**Comment by jgfidelis** [comment]
Thanks for the performance comment btw, that was the plan.
