### ISSUE TITLE
App crashes when recording videos on virtual device

### ISSUE THREAD

**Issue by Tsiniloiv** [react-native-community/react-native-camera#1187]
### Which implementation are you using

RCTCamera

### Steps to reproduce
1. Using Android Studio's emulator and the example app's startRecording/stopRecording pattern, record a video.
2. Attempt to record a second video.

### Expected behaviour
You'd expect the camera to start recording a video, and then when you stop recording a video, you have a video file containing the video you recorded, and then you can record another video.

And it does work that way on a real phone, but not on a virtual device!

### Actual behaviour
When tested on a virtual Nexus 5X, API 27, the app hangs for like a second, then saves a video file that's 0 seconds long. Attempting to record a second video then crashes the app. I'm wondering if this is known behavior for virtual devices, or if I'm screwing something up somewhere.

### Environment
- **Node.js version**: 9.3.0
- **React Native version**: 0.52
- **React Native platform + platform version**: Android API 27

### react-native-camera
**Version**: 0.12

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
