### ISSUE TITLE
[RNCamera][ios] Preview freezes when switching camera type with torch mode on

### ISSUE THREAD

**Issue by jgfidelis** [react-native-community/react-native-camera#1189]
### Which implementation are you using

RNCamera

### Steps to reproduce
1. Open RNCameraExample on iOS
2. Switch to front camera
3. Switch flash mode to torch
4. Press FLIP to switch back to back camera

### Expected behaviour
RNCamera should switch to back camera as normal

### Actual behaviour
preview freezes. If you change the flash mode or the camera type, it returns to normal

### Environment
Node: 9.4.0
RN version: "react-native": "0.51.0"
Platform: iPhone 6 & iOS 11.1.2

### react-native-camera
master

**Comment by KurtMakesWeb** [comment]
Has this been fixed yet, its also happening to me. Testing on an iPhone SE if that helps any
