### ISSUE TITLE
Add Support for R.N. 0.49 ++ PropTypes deprecated

### ISSUE THREAD

**Issue by caudaganesh** [react-native-community/react-native-camera#1211]
### Which implementation are you using

RCTCamera or RNCamera? RNCamera

### Steps to reproduce
1. Use RN version 0.49 ++

### Actual behaviour
PropTypes package deprecated

### Environment
- **Node.js version**: 9.4.0
- **React Native version**: 0.51.0
- **React Native platform + platform version**: Android 5.0

### react-native-camera
**Version**: npm version

I am able to fix this, gonna fork and make a PR soon

**Comment by Fconstant** [comment]
This is already fixed, isn't it?

**Comment by sibelius** [comment]
yep
