### ISSUE TITLE
 Could not find com.github.react-native-community:cameraview:d5d9b0d925494ef451ce3eef3fdf14cc874d9baa.

### ISSUE THREAD

**Issue by Fadi-Ghattas** [react-native-community/react-native-camera#1214]
On android Bullied this what i get any help ? 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.react-native-community:cameraview:d5d9b0d925494ef451ce3eef3fdf14cc874d9baa.
     Required by:
         Kuppl:app:unspecified > Kuppl:react-native-camera:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by sibelius** [comment]
follow https://github.com/react-native-community/react-native-camera#q--a

**Comment by SteveDuqPro** [comment]
Is a bug of react-native-camera. You can't link it. So don't make a react-native link react-native-camera.

**Comment by petrleocompel** [comment]
Updated link https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md

**Comment by formigone** [comment]
What solved this for me was to follow [step #6 for Android](https://github.com/react-native-community/react-native-camera#getting-started):

    6) Add jitpack to android/build.gradle
    
    allprojects {
        repositories {
            maven { url "https://jitpack.io" }
        }
    }

**Comment by ducpt2** [comment]
@formigone doest this lib work with RN version 0.53+? I try but it not work.

**Comment by eroosenmaallen** [comment]
The QA docs linked above do not address this issue at all; there is no mention of this error.

**Comment by akamahesh** [comment]
make sure you crosscheck with manual android instruction too. for installing automically

6) Add jitpack to android/build.gradle

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}

did the trick for me!
