### ISSUE TITLE
Unable to capture video

### ISSUE THREAD

**Issue by newlifepop** [react-native-community/react-native-camera#1217]
### Which implementation are you using

RCTCamera

### Steps to reproduce
This is the code:

    import Camera from 'react-native-camera';

    const { CaptureMode, CaptureTarget } = Camera.constants;
    const { video: captureModeVideo, still: captureModePhoto } = CaptureMode;

    class CameraScreen extends Component {
        constructor(props) {
            super(props);
            this.state = {
                captureMode: captureModePhoto,
                isRecording: false
            };

            this.onCapture = this.onCapture.bind(this);
            this.onSwitchCaptureMode = this.onSwitchCameraMode.bind(this);
        }

        onCapture() {
            const { captureMode, isRecording } = this.state;

            if (isRecording) {
                this._camera.stopCapture();
                this.setState({ isRecording: false });
                return;
            }

            if (captureMode === captureModeVideo) {
                this.setState({ isRecording: true });
            }

            this._camera.capture({ mode: captureMode })
                .then((result) => console.log(result))
                .catch((error) => console.log(error));
        }

        onSwitchCaptureMode() {
            if (this.state.captureMode === captureModeVideo) {
                this.setState({ captureMode: captureModePhoto });
            } else {
                this.setState({ captureMode: captureModeVideo });
            }
        }

        render() {
            const { captureMode } = this.state;

            return (
                <Camera
                    ref={(ref) => this._camera = ref}
                    style={{ flex: 1 }}
                    captureMode={captureMode}
                    captureTarget={CaptureTarget.disk}
                >
                    <TouchableOpacity onPress={this.onCapture}>
                        <Icon
                            name='camera-alt'
                            ...
                            ...
                        />
                    </TouchableOpacity>
                    <TouchableOpacity onPress={this.onSwitchCaptureMode}>
                        <Icon
                            name='...'
                            ...
                            ...
                        />
                    </TouchableOpacity>
                </Camera>
            );
        }
    }

    export default CameraScreen;

### Expected behaviour
When `captureMode === captureModeVideo`, return data such as `path`, `duration` should be logged

### Actual behaviour
No data is logged when `captureMode === captureModeVideo`, but everything works fine when taking a photo

### Environment
- **Node.js version**: v8.9.4
- **React Native version**: 0.52.2
- **React Native platform + platform version**: iOS 8.0

### react-native-camera
**Version**: 0.13.0
**npm**: 5.6.0

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by jgfidelis** [comment]
Can you try master branch?

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
