### ISSUE TITLE
Can't change video quality 

### ISSUE THREAD

**Issue by alameddince** [react-native-community/react-native-camera#1224]
I recorded 15 seconds videos with iPhone 5s.
first video CaptureQuality={1} 
second video CaptureQuality={Camera.constants.CaptureQuality["480p"]} 
and last video CaptureQuality={Camera.constants.CaptureQuality.low}

but all videos size 19mb between 21 mb. 

I don't understand I recorded videos 1 month ago and this video size only 500-600kb

**Comment by jordangrant** [comment]
Hi @alameddince,
for me the solution was to set the quality in the component, i.e.
```
<Camera
          ref={(cam) => { this.camera = cam; }}
          style={styles.preview}
...
          captureQuality={'480p'}
/>
```

When I set it elsewhere it didn't take effect.

Hope that helps.

**Comment by jgfidelis** [comment]
Use template

**Comment by emilemoureau** [comment]
I'm on iPhone X!

2.5 mb for a video with captureQuality={'480p'} and defaultVideoQuality={Camera.Constants.VideoQuality["720p"]} !

Is there a way to have a lower video size? Without using the 480p that distorts the video.
