### ISSUE TITLE
Error in importing org.reactnative.RNCameraPackage (incorrect docs) V1.0.0

### ISSUE THREAD

**Issue by TitanKing** [react-native-community/react-native-camera#1226]
For those running into an issue where they get an error when importing the new 1.0.0, the documentation is wrong and it should be this instead:

`import org.reactnative.camera.RNCameraPackage`

Hope it helps anyone running into the same issue.

**Comment by sibelius** [comment]
@TitanKing can you send a PR fixing this?

**Comment by TitanKing** [comment]
Sure give me a sec.

**Comment by TitanKing** [comment]
As requested: https://github.com/react-native-community/react-native-camera/pull/1227

**Comment by sibelius** [comment]
tks
