### ISSUE TITLE
Removed props in new RNCamera

### ISSUE THREAD

**Issue by Deevent** [react-native-community/react-native-camera#1229]
Hello,

I just successfully switched to RNCamera on my project but it appears that some features have disappeared in the new version (1.0.0).

aspect={RNCamera.Constants.Aspect.fill}
captureTarget={RNCamera.Constants.CaptureTarget.disk}

I was using those two properties on the Camera component but I can't anymore. I want my camera to be fullscreen and for that, I need to set the aspect. I went through the code and it doesn't exist anymore.

**Comment by jgfidelis** [comment]
You can keep using RCTCamera if RNCamera still does not satisfy your needs.

I did not fill any need of the aspect prop in RNCamera.

RNCamera is a whole new implementation of the camera in relation to RCTCamera, so some rctcamera feature are still not present. But RNCamera is way faster.

**Comment by piuccio** [comment]
I just had the same issue, it works fine without `aspect` but I really miss the `captureTarget`. I'm using `react-native-fetch-blob` to upload recorded videos to my server but I don't get access to a physical file anymore.

I don't want to use `fetch` because it doesn't have progress information

**Comment by n1ru4l** [comment]
@Deevent Feel free to open a pull request that reimplements those properties.


@piuccio wrote
> I just had the same issue, it works fine without `aspect` but I really miss the `captureTarget`. I'm using `react-native-fetch-blob` to upload recorded videos to my server but I don't get access to a physical file anymore.
> 
> I don't want to use `fetch` because it doesn't have progress information

recordAsync returns the uri of the file, so you are still able to get physical access to the file.

**Comment by bcalik** [comment]
@n1ru4l ok we can access the file from cache, but when you make an application that has offline capabilities, then cache directory is not reliable because I have to keep the recordings for later use.

**Comment by n1ru4l** [comment]
@bcalik feel free to copy it to another place or send a pull request that allows specifying the output path of the file

**Comment by rodrigoreis22** [comment]
Does anyone have an alternative for the missing `captureTarget` using `react-native-fetch-blob` ? I'm also using it to upload to my server with a progress bar.

**Comment by piuccio** [comment]
@rodrigoreis22 I'm using it without `captureTarget` and with `react-native-fetch-blob` and it works like this:

```js
import fetchBlob from 'rn-fetch-blob';

const stripFilePathPrefix = (pathStr) => {
  if (pathStr.startsWith('file://')) return pathStr.replace(/^file:\/\//, '');
  return pathStr;
};

class MyCamera extends React.Component() {
  onTouchStartRecording() {
    this.camera.recordAsync().then((data) => {
      const videoPath = data.uri;
      const header = {}; // maybe you need authentication here
      fetchBlob.fetch('PUT', 'your-url', headers, fetchBlob.wrap(stripFilePathPrefix(payload))).then(() => {});
    });
  }
  render () {}
}
```

Keep in mind that `react-native-fetch-blob` is not maintained anymore, `rn-fetch-blob` is a fork with a few bug fixes, but it's not well maintained either, there might be better ways now...

**Comment by rodrigoreis22** [comment]
Thanks @piuccio . I'll try this implementation.
