### ISSUE TITLE
RNCamera not working on android emulator (black screen)

### ISSUE THREAD

**Issue by cvvspb** [react-native-community/react-native-camera#1234]
### Which implementation are you using

*RNCamera*

### Steps to reproduce
`<RNCamera`
`ref={(cam) => { this.camera = cam; }}`
`type={RNCamera.Constants.Type.back}`
`// onBarCodeRead={this.barcodeRead}`
`barCodeTypes={[RNCamera.Constants.BarCodeType.qr]}`
`style={styles.preview}`
`>`
`<Text style={styles.capture} onPress={this.emulateScan}>[id: 4 code: 5K0C3H]</Text>`
`<TouchableOpacity onPress={() => Alert.alert('Alert', 'Keyboard pressed')}>`
`	<Image source={imgKeyboard} style={[styles.icon]} />`
`</TouchableOpacity>`
`</RNCamera>`

### Expected behaviour
Should display a preview screen

### Actual behaviour
This code does work on a device in debug mode as expected, but on an emulator displays a black screen.
Tested on Android (4.1, 6.0, 7.1.1) ABI x86 with Google API

### Environment
- **Node.js version**: 8.9.0
- **React Native version**: 0.50.0
- **React Native platform + platform version**: Android (4.1, 6.0, 7.1.1) ABI x86 with Google API

### react-native-camera
**Version**: "^1.0.0"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by jgfidelis** [comment]
We have to take a look into it but emulators were not a priority to 1.0.0

**Comment by rasom** [comment]
This happens on real devices as well, at least on Android 5.0.1, 6.0.1

**Comment by rasom** [comment]
It actually works on real device in debug mode, but can be reproduced in release mode.

**Comment by sibelius** [comment]
This could be a bug with android 6 permissions

**Comment by asemiankevich** [comment]
I can see this on Android 7

**Comment by ejswenson15** [comment]
+1

**Comment by araujobarret** [comment]
+1

**Comment by tobob** [comment]
on all my emulators I have same issue, however I did check it on 3 real devices and it works ok, however when I install expo camera app using expo on one of emulators it making images correctly

**Comment by tobob** [comment]
```
new ResolveTakenPictureAsyncTask(byteBuffer.array(), promise, options).execute();
```

this line fails, it on only called on Emulators

**Comment by Tsiniloiv** [comment]
I'm also getting this error on my emulator, and also on one of my test devices, though we've so far been unable to reproduce the error intentionally on a physical device.

**Comment by tutts** [comment]
We're finding this issue on Android 7 and 8 on a release build too. Most notably when we use React Navigation and already have a camera (scanning enabled) on one view and then attempt to load another camera on top later on in the navigation stack, wondering if there's a reference issue somewhere as both will be mounted until popped off the stack...

**Comment by rasom** [comment]
as @tutts mentioned, it can be reproduced in release build in real device

**Comment by CPCherrington** [comment]
Im getting this issue also

**Comment by waitopiggu** [comment]
I've tracked it down to [here](https://github.com/react-native-community/react-native-camera/blob/a64d31eb4591c60f89d1ce444f1944232c057faa/android/src/main/java/org/reactnative/camera/RNCameraView.java#L439).

If you remove the fingerprint check, the webcam does indeed start, at least, on my machine.

```
//if (!Build.FINGERPRINT.contains("generic")) {
  start();
//}
```

I'm sure this check was put there for a reason. It's been there since the first history entry `RNCameraView.java`.

**Comment by avshenuk** [comment]
As I know this check actually means “if this is emulator” because their
fingerprints contain “generic” in the fingerprint... so this is definitely
for a reason there :)

**Comment by waitopiggu** [comment]
@avshenuk Well, I set my emulator webcam to "none" and the app didn't crash, but there was a logcat error.

`W/CameraBase: An error occurred while connecting to camera -1: Status(-8): '4: validateConnectLocked:899: No camera device with ID "-1" available'`

My remote debugger isn't working for emulated devices, so I can't check if React exceptions are being handled well.

**Comment by sibelius** [comment]
@aalices do u know why there is this check?

**Comment by aalices** [comment]
Yeah I put it by design to not render any preview when using an emulator cause iirc this was often crashing

**Comment by adipascu** [comment]
It whould be nice to show something like `<Text>The camera is currently unavailable on emulators</Text>`instead of a blank screen to avoid confusion.

**Comment by waitopiggu** [comment]
@aalices I'll create some AVDs with different Android versions and architectures when I get a chance. I've only been on testing on "P" x86 so far.

**Comment by ChristineTzeng** [comment]
I got the same black screen on Android 7(API 25/x86) emulator.

**Comment by mirceanis** [comment]
do you think we can get a release with this small fix in?
