### ISSUE TITLE
Lag while using RNCamera to record videos.

### ISSUE THREAD

**Issue by karankapoor229** [react-native-community/react-native-camera#1236]
I am facing a lag while starting and stopping the video recording using RNCamera , while with RCTCamera it is working fine.

### Steps to reproduce
**In Render Method**
`            <RNCamera
                ref={(cam) => {
                    this.camera = cam;
                }}
                type={RNCamera.Constants.Type.front}
                style={styles.preview}
                permissionDialogTitle={'Permission to use camera'}
                permissionDialogMessage={'We need your permission to use your camera phone'}
                captureAudio= {true}
                ratio = "16:9"
            >`
**On Button Click**
`takeVideo() {
        this.state.isRecording ?
            this.camera.stopRecording()
            : this.saveVideo()
        this.state.isRecording ?   this.setState({isRecording: false}) : this.setState({isRecording: true})
    }`
**Function to start and save video recording**
`saveVideo = async function() {
        if (this.camera) {
            const options = { maxDuration: 10 }
            const data = await this.camera.recordAsync(options)
            this.setState({ path: data.uri })
            this.setState({recorded: true})
        }};`

### Expected behaviour
The video recording should start instantly on button click.

### Actual behaviour
There is a significant lag after pressing the button to start recording video and same while stopping the recording.

### Environment
- **Node.js version**: 8.9.4
- **React Native version**: 0.52.0
- **React Native platform + platform version**: Android 8.0

### react-native-camera
**Version**:  "master"

**Comment by jgfidelis** [comment]
Thanks for the input.

RCTCamera uses MediaRecorder to record while RNCamera uses Google's CameraView, from what I see there is nothing stopping the CameraView from starting to record on RNCamera so I think it is a problem on that class, a slow setup, I do not know. If anyone knows Android better than me and has a better opinion, it would be great.

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera

**Comment by asarasua** [comment]
I'm facing the same issue, and also not using RCTCamera but RNCamera (latest version), as @karankapoor229.

**Comment by baughmann** [comment]
This is still an issue. It exists on iOS but is even worse on Android. The issue remains unchanged when using a release build.

**Comment by eqlion** [comment]
Still have this issue with react-native-camera 3.38.0, RN 0.62.2 and Android 10

**Comment by baughmann** [comment]
@eqlion The best solution for me was to get down and dirty and make native components for the Camera. Most of your camera UI can use your normal RN components, but it's better to implement the actual camera yourself in Swift/Kotlin

**Comment by eqlion** [comment]
@baughmann Could you share your solution, if it is generic? All we need is recording videos and taking pictures, and I'm proficient enough neither in Kotlin, nor in Swift :(

**Comment by baughmann** [comment]
@eqlion I've been thinking about trying to re-create it at some point. Thing is, even if you're good in Swift/Objective-C and Kotlin/Java, using Native Modules and Native components is notoriously poorly documented and confusing. To my knowledge, this issue has never been addressed.

I can try to find my code and make some gists for it, but that project has been lost to time for the most part. If you want a smooth and fast camera, it is your best bet.

If a camera is not a core part of your application, I would suggest that you search for another plugin. You could also fork and modify this package to try to eliminate some of the features you do not need to make it simpler and maybe faster.
