### ISSUE TITLE
[Android] Manifest merger failed

### ISSUE THREAD

**Issue by mistenkt** [react-native-community/react-native-camera#1239]
So i have spent a day trying all suggestions for similar issues and without any luck. This also fails on a completely fresh RN project.

:react-native-camera:processDebugAndroidTestManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-camera:processDebugAndroidTestManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:exifinterface:26.0.2] AndroidManifest.xml:25:13-35
  	is also present at [com.android.support:support-v4:26.0.1] AndroidManifest.xml:28:13-35 value=(26.0.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at manifestMerger196235135338020733.xml:23:9-25:38 to override.

**Comment by sibelius** [comment]
Check Q & A docs

**Comment by mistenkt** [comment]
Closing this doesnt fix the issue, none of the solutions in the Q&A helps

**Comment by jgfidelis** [comment]
In your app/build.gradle, change the react-native-camera compile to:
```
compile (project(':react-native-camera')) {
        exclude group: "com.android.support"
    }
compile "com.android.support:exifinterface:26.1.0"
```

**Comment by mistenkt** [comment]
adding exclude to react-native-camera doesnt help. Error still shows every time on gradle sync.

**Comment by jgfidelis** [comment]
```
compile (project(':react-native-camera')) {
exclude group: "com.android.support"
}
compile ("com.android.support:exifinterface:26.0.2") {
force = true;
}
```

Could you try this instead?

**Comment by mistenkt** [comment]
`Error:Execution failed for task ':react-native-camera:processDebugAndroidTestManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:exifinterface:26.0.2] AndroidManifest.xml:25:13-35
  	is also present at [com.android.support:support-v4:26.0.1] AndroidManifest.xml:28:13-35 value=(26.0.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at manifestMerger1115803340332880803.xml:23:9-25:38 to override.`

`dependencies {
    compile project(':react-native-image-picker')
    compile project(':react-native-fs')
    compile project(':react-native-fcm')
    compile 'com.google.firebase:firebase-core:11.8.0' //this decides your firebase SDK version
    compile project(':react-native-facebook-login')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.0.2"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
    }
    compile ("com.android.support:exifinterface:26.0.2") {
        force = true;
    }
    compile ("com.google.android.gms:play-services-vision:11.8.0") {
        force = true;
    }
}`

**Comment by jgfidelis** [comment]
@mistenkt 

Please, look at your build.gradle:
```
compile (project(':react-native-camera')) { 
exclude group: "com.google.android.gms" 
}
```
It should be:
```
compile (project(':react-native-camera')) { 
exclude group: "com.google.android.gms" 
exclude group: "com.android.support"
}
```

**Comment by mistenkt** [comment]
tried them all. updated now to be both and same error

**Comment by mistenkt** [comment]
it is now:

dependencies {
    compile project(':react-native-image-picker')
    compile project(':react-native-fs')
    compile project(':react-native-fcm')
    compile 'com.google.firebase:firebase-core:11.8.0' //this decides your firebase SDK version
    compile project(':react-native-facebook-login')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.0.2"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile (project(':react-native-camera')) {
        exclude group: "com.android.support"
        exclude group: "com.google.android.gms"
    }
    compile ("com.android.support:exifinterface:26.0.2") {
        force = true;
    }
    compile ("com.google.android.gms:play-services-vision:11.8.0") {
        force = true;
    }
}

and it gives them same error for Manifest merger

**Comment by sibelius** [comment]
follow this https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md#meta-data-android-26

**Comment by mistenkt** [comment]
i have

**Comment by sibelius** [comment]
can u create a repo to reproduce this error?

try to run this one https://github.com/react-native-community/rncamera-example

**Comment by jgfidelis** [comment]
Ok that is pretty weird.

remove 
```
compile ("com.android.support:exifinterface:26.0.2") {
force = true;
}
```

It should build, try to take a photo and see if everything goes ok.

**Comment by matheus-lima** [comment]
this worked for me.
adding a meta-data to your manifest

```xml
<meta-data
        tools:replace="android:value"
        android:name="android.support.VERSION"
        android:value="26.0.2" />
```

**Comment by afilp** [comment]
@matheus-lima @sibelius Does this mean that a new version could be released that will fix all these problems?
