### ISSUE TITLE
Camera does not respond to touch after reset on stack navigator

### ISSUE THREAD

**Issue by NhatAnh** [react-native-community/react-native-camera#1247]
### Which implementation are you using

RCTCamera

### Steps to reproduce
1. Use stack navigator from react navigation, first screen has <Camera> component with a button inside and one button outside. Add onPress function for both buttons
2. navigate to several screen on the stack. On last screen, reset the stack with
```
const resetAction = NavigationActions.reset({
      index: 0,
      key: null,
      actions: [NavigationActions.navigate({ routeName: 'HomeScreen' })],
    });
    this.props.navigation.dispatch(resetAction);
```

### Expected behaviour
both buttons should still work

### Actual behaviour
the button inside Camera component does not respond, while the button outside still works.

### Environment
- **Node.js version**: v8.1.2
- **React Native version**:
react-native-cli: 2.0.1
react-native: 0.51.0
- **React Native platform + platform version**: iOS 9.0

**Comment by n1ru4l** [comment]
RCTCamera is deprecated, please try the latest release of RNCamera. If you still experience these problems, please open a new issue!
