### ISSUE TITLE
Flash not working

### ISSUE THREAD

**Issue by rf1804** [react-native-community/react-native-camera#1253]
import Camera from 'react-native-camera';

whenever i click on flash icon it gets changed but it never triggers flash of mobile, i am recording video by using this module

**Comment by sibelius** [comment]
try RNCamera

`import { RNCamera } from 'react-native-camera`

**Comment by rf1804** [comment]
@sibelius i've tried using RNCamera but it is giving more problems, video freezing and all, is there any solution for RCTCamera as everything is working absolutely fine except flash in video recording
