### ISSUE TITLE
Image not saved to Camera Roll with new RNCamera?

### ISSUE THREAD

**Issue by donni106** [react-native-community/react-native-camera#1254]
### Which implementation are you using

*RNCamera*

I updated my application to master with RNCamera. The app is running in an iOS Simulator.

### Steps to reproduce
Take picture with new `takePictureAsync()`.

### Behaviour
With old version RCTCamera the image was stored in the devices Camera Roll right after capturing.
Now i capture and get the data. I can output it with `console.log` and see it in the desktop browser when clicking the link.
How can i achieve this with the new version RNCamera?

### Environment
- **Node.js version**: v9.5.0
- **React Native version**: 0.51.0
- **React version**: 16.0.0

### react-native-camera
**Version**: "master" 1.0.1

### Something else
With checking the new docs, i saw
```
toggleView() {
    this.setState({
      showGallery: !this.state.showGallery,
    });
  }
```

and implemented it on another button next to my takePicture. But nothing happens. What should this action actually do?

**Comment by sibelius** [comment]
I think this is a feature in fact, it saves all images to a cache folder

then you can use `react-native-fs` to move to somewhere else

**Comment by jgfidelis** [comment]
It saves the picture in your device's cache folder and the promise will return its URI. You can then move that file to anywhere you'd like with other libs like `react-native-fs`, like @sibelius mentioned.

Save directly to camera roll would be a nice feature to have that can be implemented in the future, but in RNCamera it is not available yet, only on RCTCamera.

**Comment by jgfidelis** [comment]
About the `Something else`, it is a code snippet from the example app and it doesn't do anything, the variable showGallery in the state is not used for anything if I recall correctly

**Comment by sibelius** [comment]
maybe we should add this do `docs`

**Comment by CescCesc** [comment]
I'm try CameraRoll.saveToCameraRoll(data.uri, "photo") and success. 
data = await this.camera.takePictureAsync(options) in RN Camera

**Comment by sundariragavan** [comment]
return await CameraRoll.saveToCameraRoll(uri, "photo");
In android, app is save the image into camera gallery. How to create a custom folder and save the image into gallery.

**Comment by ozankonur** [comment]
@Friendly-Robot  Thanks it helped me.

**Comment by TheAlgo** [comment]
@ozankonur what did you do to save the image in the gallery?

**Comment by ozankonur** [comment]
@TheAlgo I use above my codes & I removed 'base64: true' from options.

**Comment by TheAlgo** [comment]
@ozankaur did this save the image to gallery ?

**Comment by ozankonur** [comment]
@TheAlgo yes

**Comment by TheAlgo** [comment]
![whatsapp image 2019-02-07 at 2 18 46 pm](https://user-images.githubusercontent.com/26045331/52399821-63b10880-2ae3-11e9-8569-b55e7698daa7.jpeg)
@ozankonur  I am getting this and my image is not getting saved

**Comment by TheAlgo** [comment]
undefined is not an object data.uri , it is showing @ozankonur
