### ISSUE TITLE
Updating the Child Elements of RNCamera results in Black Preview Screen

### ISSUE THREAD

**Issue by K-Leon** [react-native-community/react-native-camera#1259]
### Which implementation are you using

*RNCamera*

### Steps to reproduce
You need a code construct like this. As soon as you update this.props.children and the inner UI changes the Camera Preview goes black.
```
<RNCamera>
        {this.props.children}
</RNCamera>
```
### Expected behaviour
It should keep working like in RCTCamera

### Actual behaviour
It goes black

### Environment
- **Node.js version**: latest
- **React Native version**: latest
- **React Native platform + platform version**: Android 7

### react-native-camera
**Version**: master

**Comment by jgfidelis** [comment]
I think we need a startPreview and stopPreview methods like RCTCamera

**Comment by K-Leon** [comment]
I‘m not sure this is the reason - i didn’t used them on rctcamera too. (But maybe it is used internally - i need to look this up)

**Comment by jgfidelis** [comment]
Yes, I believe they usem them internally but I have to take a look into the code later.

**Comment by kosintop** [comment]
@jgfidelis, may I ask how's the progress on this? I'm having trouble with this issue and would like to know whether it will be possible to render children inside <RNCamera> or not

**Comment by sibelius** [comment]
Can somebody debug and try to fix this? I think this only happens when there is a setState

**Comment by Concert0** [comment]
It works fine on iOS but not on android(using master branch)

**Comment by carloscuesta** [comment]
Having the same problem, @sibelius I'm not using `setState` just a conditional render based on props

**Comment by markidm** [comment]
@sibelius I have a conditional render based on state, I'm getting the same issue.

**Comment by n1ru4l** [comment]
@markidm Could you please provide a reproduction repository? Or fork this repository in order to implement a reproduction in `examples/basic`?

**Comment by sibelius** [comment]
Just do a setState while trying to do a capture

**Comment by sibelius** [comment]
fixed here https://github.com/react-native-community/react-native-camera/releases/tag/v1.7.0
