### ISSUE TITLE
Can't find variable takePicture

### ISSUE THREAD

**Issue by jarnail1004** [react-native-community/react-native-camera#1261]
### Intgerated RNCamera but function **takePicture** is having below error:

Can't find variable **takePicture**

I am developing on windows 10 system with android studio installed and testing outoput in simulator. 

### Environment
- **Node.js version**: 8.9.3
- **React Native version**: 0.53.0
- **React Native CLI version**: 2.0.1
- **Android Studio**: 3.0.1
- **Android version**: 5.x, 6.x, 7.x
- **Editor**: Visual Studio Code (VS Code)
- **System OS**: Windows 10 pro
- **Browser for debug**: Google Chrome

### Expected behaviour
I should be able to use camera to scan barcodes

### Actual behaviour
Error: Can't find variable **takePicture**

**Comment by jgfidelis** [comment]
RNCamera uses the `takePictureAsync`.
