### ISSUE TITLE
error while building android project

### ISSUE THREAD

**Issue by yubo725** [react-native-community/react-native-camera#1264]
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.react-native-community:cameraview:d5d9b0d925494ef451ce3eef3fdf14cc874d9baa.
     Required by:
         TestReactNavigation:app:unspecified > TestReactNavigation:react-native-camera:unspecified

**Comment by sibelius** [comment]
Missing jitpack, check Q & A
