### ISSUE TITLE
Camera preview is distorted

### ISSUE THREAD

**Issue by sandropoluan** [react-native-community/react-native-camera#1267]
### Expected behaviour
Camera preview should not distorted

### Actual behaviour
Camera preview is distorted

### Environment
- **Node.js version**: v8.9.3
- **React Native version**: "0.53.0"
- **React Native platform + platform version**: Tested on Android 5.0, Android 7.1 etc

### react-native-camera
**Version**: 1.0.1 (NPM)

### My Code
```
          return (<View style={{flex:1}}>
                       <RNCamera ref={ref => {
                          this.camera = ref;
                        }}
                        style={{flex: 1,justifyContent: 'flex-end',alignItems: 'center'}}
                        type={RNCamera.Constants.Type.back}
                        permissionDialogTitle={'Permission to use camera'}
                        permissionDialogMessage={'We need your permission to use your camera phone'}                    
                        
                        />
                     </View>);
```

**Object is tall and slim** (not normal condition)
![screenshot_2018-02-20-14-12-12-269_com eabsen](https://user-images.githubusercontent.com/11922251/36410076-eff9c19c-1649-11e8-9d44-7018cd2eb25f.png)

**When I rotate it become short and wide.** (not normal condition)
![screenshot_2018-02-20-14-12-02-299_com eabsen](https://user-images.githubusercontent.com/11922251/36410103-05cfbdf0-164a-11e8-98bc-3deaae9687f9.png)

**Normal condition (taken by Android Native Camera)**
![img_20180220_143305](https://user-images.githubusercontent.com/11922251/36410311-36f7992e-164b-11e8-83dc-08738c08bdd6.jpg)

**Comment by alizahid** [comment]
I have a square-sized camera preview, and I have this issue, too. I had a hacky fix, which involved calculating the layout height and width and setting on the camera preview, and then setting the ratio to `3:4`, and it worked. On some devices, at least

Today, I upgraded to `1.0.1` and it crashes when trying to render camera preview. A similar stack trace here https://github.com/google/cameraview/issues/206

Using `RNCamera`

**Comment by jgfidelis** [comment]
Some of this errors are likely due to CameraView, but we use Expo's version, so I do not know the best place to open issues about it, if it is in Expo's repo or Google's repo.

**Comment by jgfidelis** [comment]
@alizahid did you use `getSupportedRatiosAsync` before setting the ratio that crashed the device?

**Comment by alizahid** [comment]
It was indeed an unsupported ratio that caused the crash.

**Comment by waitopiggu** [comment]
On my Android development phone, setting the aspect to '16:9' removed the distortion.

Without some way of getting the dimensions from the camera itself, there's no way to work out the correct aspect ratio to use.

Allowing the user to choose from a list of supported aspect ratios would work, but not a very good solution from a UX perspective.

**Comment by alizahid** [comment]
@waitopiggu `3:4` worked for me. But it's not available on most devices.

**Comment by Sangrene** [comment]
Hi guys, just a quick workaround ONLY if you render it on all the screen with position absolute: 
In your render camera function write this at the beginning
```
const {height, width} = Dimensions.get('window');
const newWidth = height*(3/4);
const widthOffset = -((newWidth-width)/2);
```

Then in your RNCamera component, add the follow style
`{left: widthOffset, right:widthOffset}`

Just for you to know, my base RNCamera style is
```
preview: {
    position: "absolute",
    top: 0,
    bottom: 0,
    right: 0,
    left: 0,
    zIndex: 2
  }
```

Hope it helps you :)

**Comment by jgfidelis** [comment]
please try on master branch

**Comment by gigby** [comment]
It is not a bug. Please, check here https://github.com/react-native-community/react-native-camera/issues/1280
