### ISSUE TITLE
EAN-13 barcode doesn't scan vertically

### ISSUE THREAD

**Issue by karpie28** [react-native-community/react-native-camera#1272]
### Steps to reproduce
1. Try to scan barcode EAN13 format
2. Present barcode vertically (does not scan)
3. Present barcode horizontally (Scans quickly)

### Expected behaviour
Should scan both horizontally and vertically

### Actual behaviour
Present barcode horizontally (does not scan)
Present barcode vertically (Scans quickly)

When book is vertically:

![untitled](https://user-images.githubusercontent.com/16509861/36494250-d36f87da-1731-11e8-9c8c-9fe3132f7612.png)

When book is horizontally:

![untitled2](https://user-images.githubusercontent.com/16509861/36494252-d4f5662e-1731-11e8-8961-8807058ee6d7.jpg)

### Environment
- **Node.js version**: 8.4.0
- **React Native version**: 0.50.4
- **React Native platform + platform version**:  Android 6.0.1

### react-native-camera
**Version**: master

**Comment by CodeAddictSebastianGolinski** [comment]
Same problem here 😕

**Comment by OzoTek** [comment]
Same, since I upgraded from RCTCamera to RNCamera last version, was working fine before

**Comment by K-Leon** [comment]
Probably related to aspect ratio like discussed in #1258

**Comment by JorgeCeja** [comment]
What aspect ratio are you using? @karpie28

**Comment by csumrell** [comment]
I am getting this same error on Android only, and only when my phone is positioned in Vertical/Portrait mode. It just stares at the barcode without doing anything, however if i stop the camera, turn the phone sideways (Landscape) and scan it, it processes it very quickly.

**Comment by movie4** [comment]
Get seems issues on RNCamera 1.0.1 - EAN13 — barcode

**Comment by SimonAmpleman** [comment]
Also have the same problem. Application is in portrait mode. I've tried every aspect ratio possible. If I turn the phone in landscape, it works fine.

Also, when I save a picture, it appears in landscape mode (it's rotated 90 degrees).

Thank you for your help!

**Comment by SimonAmpleman** [comment]
I'll contribute a 50$ USD if this can be fixed : Camera in portrait mode. Taking picture in portrait mode. And detecting UPC in both portrait or orientation at the same time.

Thanks !

**Comment by ChangeSomeCode** [comment]
same problem

**Comment by joselazarosiqueira** [comment]
Same problem!

**Comment by jslok** [comment]
+1

**Comment by uikolas** [comment]
Same on android

**Comment by krystianpach** [comment]
Same issue on all Android Devices, there is no problem with iOS

**Comment by DanielLeberle** [comment]
I have the same problem, does anyone have not this problem?

**Comment by E-P1983** [comment]
Same problem!

**Comment by Hoolii** [comment]
Same here, since I migrated from RCTCamera to RNCamera.

**Comment by DanielLeberle** [comment]
Does anyone have a solution to make scanning possible in portrait mode but not in landscape mode? this would help me a lot.

I had a look into the java code and tried to rotate the image but without success.

**Comment by jpudysz** [comment]
@DanielLeberle yes. Downgrade to `RCTCamera`

**Comment by DanielLeberle** [comment]
well I guess there is no other option. Although RCTCamera has not the same performance as RNCamera in my opinion. On iOS RNCamera is a lot better, thats why we switched.

**Comment by jpudysz** [comment]
I agree, but we end up using 2 cameras. One for barcode scanner and second for photos. Still it's better to have app than crashes :)

I guess we need to wait ;)

**Comment by MWalid** [comment]
same here.... +1

**Comment by jgfidelis** [comment]
Please try on master branch

**Comment by Ilario17** [comment]
Now it works in portrait but on my Wiko Rainbow the performances are terrible

**Comment by platonish** [comment]
Still doesn't work. Tested on Android Nougat, react-native-camera v1.1.4

**Comment by prateekgoel** [comment]
@sibelius This is still the issue for me. I have tried it with the latest version of react-native-camera and with RNCamera and RCTCamera also. Not working in any case.

**Comment by Eriwyr** [comment]
Same problem for me, anyone has found a way to fix this problem ?

**Comment by JohnTree** [comment]
Same problem for me, anyone has found a way to fix this problem ?

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera

**Comment by wolkingdead** [comment]
same problem how to fix it

**Comment by luizaprata** [comment]
same problem how to fix it
