### ISSUE TITLE
Example doesn't build

### ISSUE THREAD

**Issue by roruva** [react-native-community/react-native-camera#1274]
### Steps to reproduce
1. Download the repository.
2. go to react-native-example/Example
3. npm i
4. react-native run-android

![Image of Yaktocat](https://image.ibb.co/ksNTDH/error_Compiling.png)

### Expected behaviour
The project should build and run.

### Actual behaviour
The project doesn't build.

### Environment
- **Node.js version**: 7.10.0
- **OS **: Windows 10

**Comment by sibelius** [comment]
use the new example https://github.com/react-native-community/rncamera-example using RNCamera
