### ISSUE TITLE
Unsupported Modules Detected: Compilation is not supported for following modules: react-native-camera. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

### ISSUE THREAD

**Issue by afilp** [react-native-community/react-native-camera#1277]
"react-native-camera": "^0.12.0",

I get the following error message in Android Studio 3.0.1:

Unsupported Modules Detected: Compilation is not supported for following modules: react-native-camera. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

**Comment by sibelius** [comment]
use master or >=1.0.0

**Comment by afilp** [comment]
Thanks, this is what I had but I had to go to 0.12 because react-native-firebase had conflicts (as suggested here: https://github.com/react-native-community/react-native-camera/issues/1086#issuecomment-359454837)

Is this also solved if I go to v1.0?
