### ISSUE TITLE
Is there a way to turn off capture sound?

### ISSUE THREAD

**Issue by bvv218** [react-native-community/react-native-camera#1281]

**Comment by sibelius** [comment]
there is a `mute` option on RNCamera

**Comment by bvv218** [comment]
@sibelius It doesn't seem to work when you take pictures. Doesn't it mute sound of videos only?

**Comment by ajaxmac** [comment]
Not on iOS, this is enforced by the operating system. I saw some notes on turning off the shutter sound for Android somewhere. Apparently it's law in Japan that phone cameras must make a sound so that people can't surreptitiously take photos.

**Comment by jgfidelis** [comment]
ios has the prop `captureAudio` as `false` as default. If you want to capture audio, pass `true`
 read the doc https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md

**Comment by SBright** [comment]
Is it possible to disable capture sound on RNCamera in iOS?
