### ISSUE TITLE
RNCameraManager crash issues after QRCODE read

### ISSUE THREAD

**Issue by itrcz** [react-native-community/react-native-camera#1292]
### Steps to reproduce
1. scanning QRCode with weird encoding on something like that
2. - (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputMetadataObjects:(NSArray *)metadataObjects fromConnection:(AVCaptureConnection *)connection  calls
3. metadata.stringValue is NULL that causes application crash.

### Expected behaviour
metadata.stringValue should be not be NULL

### Actual behaviour
metadata.stringValue is NULL

### Environment
- **Node.js version**: 8.9.1
- **React Native version**: 0.51.0
- **React Native platform + platform version**: iOS 11.2

### react-native-camera
**Version**: npm version 1.0.1

### QRCODE that causes issue
![image 2018-02-26 19 23 25](https://user-images.githubusercontent.com/2022624/36681781-9fad29d2-1b2a-11e8-83cb-31d1be71fbba.jpg)

**Comment by gre** [comment]
can reproduce with this QRCode:

![qrcode](https://user-images.githubusercontent.com/211411/37468218-a06c6604-2862-11e8-88b3-a269867b79b3.png)


(generated on https://smealum.github.io/ninjhax2/ )

**Comment by gre** [comment]
@itrcz were you able to still reproduce?
