### ISSUE TITLE
When can we expect the `forceUpOrientation`-feature to be part of a release?

### ISSUE THREAD

**Issue by klaasman** [react-native-community/react-native-camera#1298]
This feature has been committed on 22 february:

https://github.com/react-native-community/react-native-camera/commit/c20fb94150de1517fac126c61c73c4338de433a9 - Add ability to force up orientation on iOS

**Comment by sibelius** [comment]
use master for now

@jgfidelis u release a new version this week

**Comment by klaasman** [comment]
I am indeed, thanks for planning the release!
