### ISSUE TITLE
async function 'getSupportedRatios' is not defined

### ISSUE THREAD

**Issue by Nauzer** [react-native-community/react-native-camera#1300]
### Which implementation are you using
RNCamera

### Steps to reproduce
Implement following code snippet
```
getRatios = async function() {
  const ratios = await this.camera.getSupportedRatios();
  // not sure how ratios returns for assuming it is an Array, take the first element
  return ratios[0];
};

constructor() {
  this.super();
  // use wrong ratio to check update is done correctly
  this.state = {
    ratio: '16:9',
  }
}

componentDidMount() {
    const self = this;
    this.getRatios().then((result) => { self.setState({
      ratio: result
    })});
 }

render() {
    return (
      <View style={styles.container}>
        <RNCamera
          ref={(cam) => {
                this.camera = cam;
              }}
          onBarCodeRead={this.onBarCodeRead}
          style={styles.preview}
          ratio={this.state.ratio}
        >
          {this.renderOverlay()}
        </RNCamera>
      </View>
    );
  }

```

### Expected behaviour
Result of this.camera.getSupportRatios async can be used to set state to a supported ratio.

### Actual behaviour
Follow error it thrown:

> Possible Unhandled Promise Rejection (id: 0):
> TypeError: this.camera.getSupportedRatios is not a function

It seems that getSupportedRatios is not defined.

### Environment
- **Node.js version**: v6.10.2
- **React Native version**: v0.53.0
- **React Native platform + platform version**: Android 7.1.1

### react-native-camera
**Version**: npm version v1.0.1

**Comment by Fconstant** [comment]
You should only use `getSupportedRatios` when the camera is ready.
See #1280 for a simple example

This is a android only feature, so don't forget to add a `if (Platform.OS === 'android') { ... }` statement
