### ISSUE TITLE
[RNCamera] - Focus stops working

### ISSUE THREAD

**Issue by stoffern** [react-native-community/react-native-camera#1301]
### Steps to reproduce
1. switch from front to back
2.switch from back to front
3.focus lost..

### Environment
- **Node.js version**: 8.9.4
- **React Native version**: 0.53.3
- **React Native platform + platform version**: Android

### react-native-camera
**Version**: 1.0.1

**Comment by jgfidelis** [comment]
Could you test if it happens on the expo version as well?
Use this app: https://github.com/expo/camerja

**Comment by stoffern** [comment]
@jgcmarins same problem.
But if i toggle AutoFocus off-on then it will start to focus again.

**Comment by sibelius** [comment]
@stoffern could u send a PR to fix this?

**Comment by stoffern** [comment]
@sibelius i can always provide a js fix for it.
But Java is not my thing, and it is probably better so solve it natively?

**Comment by guilhermebruzzi** [comment]
Same problem with RN 0.43.4 and react-native-camera 1.0.1
