### ISSUE TITLE
Can't find the API to light the light

### ISSUE THREAD

**Issue by hrh94** [react-native-community/react-native-camera#1303]
When the environment is a bit dark, when I sweep the code, the cell phone needs to turn on the light
For example：
![u 3270856376 1533712612 fm 11 gp 0](https://user-images.githubusercontent.com/16442574/36821352-9e55b702-1d2d-11e8-91a7-862475d13445.jpg)

**Comment by huangguozhen** [comment]
get same problem

**Comment by hrh94** [comment]
https://github.com/react-native-community/react-native-camera/issues/832

**Comment by jgfidelis** [comment]
RNCamera, set flashMode to `RNCamera.Constants.FlashMode.torch`
read documentation please.
