### ISSUE TITLE
App crashes: RNCameraManager.takePicture was called with 2 arguments but expects 1 arguments.

### ISSUE THREAD

**Issue by bvv218** [react-native-community/react-native-camera#1304]
I have updated to RNCamera, and when I take a picture the app crashes with the following error (both android and ios):

```
RNCameraManager.takePicture was called with 2 arguments but expects 1 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
```

**Comment by sibelius** [comment]
Are u using the latest react native version?

**Comment by bvv218** [comment]
@sibelius I am using version 0.51.0 of react native

**Comment by jgfidelis** [comment]
How is your code?

**Comment by sibelius** [comment]
it is getting the wrong react native android version, check your android configs based on https://github.com/react-native-community/rncamera-example
