### ISSUE TITLE
[RNCamera] - Android crash on init (FaceDetector$Builder)

### ISSUE THREAD

**Issue by jpudysz** [react-native-community/react-native-camera#1310]
### Which implementation are you using

*RNCamera*

### Steps to reproduce
1. Use simulator or phone with Android
2. Use RNCamera
3. Navigate to camera page

### Expected behaviour
Should work as on iOS or like deprecated RCTCamera

### Actual behaviour
Exception

### Environment
- **Node.js 8.5**:
- **React Native 0.53.3**:
- **Android 7.0**: 

### react-native-camera
**Version**: 1.0.1

![face-detector](https://user-images.githubusercontent.com/9088288/36891410-d87183f6-1e01-11e8-9227-96fd44f9f9ab.jpg)

**Comment by sibelius** [comment]
U need to include google Visio dep on ur gradle config

**Comment by jpudysz** [comment]
Ah thanks! I missed it 👍 

For future reference, take a look at:
```
compile ("com.google.android.gms:play-services-vision:10.2.0") {
  force = true;
}
```

In my case I had a lot of other conditions like `play-services-base` , `play-services-maps` etc. and I missed that in docs we have `play-services-vision` :)
