### ISSUE TITLE
Access the camera stream, so I can render the same image in two different textures?

### ISSUE THREAD

**Issue by rubencg195** [react-native-community/react-native-camera#1315]
### Which implementation are you using
*RNCamera*

### Expected behaviour
I want to create two instances of RNCamera to make it compatible with Google Cardboard for an Augmented Reality App. The problem is that when creating both, one appears on black. I understand that maybe you **cannot access the back camera twice.** So my question is, 

# how can I access the camera stream, so I can render the same image in two different textures or gl-textures?

![image](https://user-images.githubusercontent.com/25628940/36954074-154ae580-1fe5-11e8-906b-9309a1328f86.png)

### Actual behaviour
When creating two camera instances, one is black.

![image](https://user-images.githubusercontent.com/25628940/36954057-ee4035c6-1fe4-11e8-86e1-23a555f247b5.png)

![image](https://user-images.githubusercontent.com/25628940/36954509-287a48aa-1fe8-11e8-95c6-ccdfb6ca0c35.png)

### Environment
- **Node.js version**: v8.9.4
- **React Native version**: 0.52.0
- **React Native platform + platform version**: 'Android SAMSUNG-SM-N900A - 5.0' 

### react-native-camera
**Version**:   "master" 
"git+https://git@github.com/react-native-community/react-native-camera"

**Comment by loic-lopez** [comment]
I have the same problem does any one know how to access to the camera stream?

Thanks for reply.
