### ISSUE TITLE
RNCamera android front record error

### ISSUE THREAD

**Issue by teilala** [react-native-community/react-native-camera#1319]
I use RNcamera,because it has whiteBalance .
and when i record on android front camera, got warning . but IOS was work .

in org.reactnative.camera.CameraModule.java line:228
                  if (cameraView.isCameraOpened()) {  //here get null 
                      cameraView.record(options, promise, cacheDirectory);
                  } else {
                      promise.reject("E_CAMERA_UNAVAILABLE", "Camera is not running");// in the case ,output this warning...so it can't record.
                  }

**Comment by jgfidelis** [comment]
try on master branch

**Comment by sibelius** [comment]
this was a bug on Camera2
