### ISSUE TITLE
Cant take multiple photos with flash on (Android, Pixel 2 XL)

### ISSUE THREAD

**Issue by rknell** [react-native-community/react-native-camera#1323]
Not sure if this is an existing issue, and if so sorry, but I couldn't find any evidence / solutions anywhere

**THIS ONLY HAPPENS WHEN flashMode={RNCamera.Constants.FlashMode.on} IS SPECIFIED**
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

RNCamera

### Steps to reproduce
1. Take a photo using the example code (including flash)
2. Take another photo using the example code (dont recreate the RNCamera control)
3. Camera freezes shortly after
4. Take another photo, warning, "camera not running"

### Expected behaviour
It should continue to take photos, not shut down the camera

### Actual behaviour
The camera freezes and can only take one photo without the control being recreated. This is not a problem when flashMode is not specified.

### Environment
- **Node.js version**: v8.9.4
- **React Native version**: 0.53.3
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
Android 8.1, Google Pixel 2 XL

### react-native-camera
**Version**: npm version or "master"
My fork: https://github.com/rknell/react-native-camera.git (only changes are to remove additional items required after install)
Updated to master 

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by petrleocompel** [comment]
I have same problem with S6 edge. If I set `flashMode` to `off` everythings work fine. But that is not a solution. :disappointed:
