### ISSUE TITLE
Replacement for Capture Target

### ISSUE THREAD

**Issue by arapocket** [react-native-community/react-native-camera#1324]
If we need to upload the file somewhere (ie an S3 bucket) what do we do now without the CaptureTarget prop?

**Comment by sibelius** [comment]
Upload where?

**Comment by arapocket** [comment]
What I am asking is if it's still possible to retrieve the file without using CaptureTarget.disk, because I remember trying to get the file from the cache was an issue when I had tried it before.

**Comment by arapocket** [comment]
Nevermind it still works fine.
