### ISSUE TITLE
RNCamera doesn't support cropToPreview

### ISSUE THREAD

**Issue by sunweiyang** [react-native-community/react-native-camera#1327]
The legacy RCTCamera implementation supported cropToPreview as a prop. Can RNCamera get this functionality as well?

**Comment by jgfidelis** [comment]
Would be a nice feature to have if you implement it, send a PR

**Comment by 404sand808s** [comment]
This feature would be very useful (and is a basic must-have IMO). I've had users complain that they image captured is not the same as the viewfinder showed.

**Comment by jkdf2** [comment]
References #1057 where `cropToPreview` was implemented for `RCTCamera`

**Comment by n1ru4l** [comment]
Ongoing Pull Request: https://github.com/react-native-community/react-native-camera/pull/1636

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera

**Comment by jkdf2** [comment]
@sibelius, I am not sure this issue was resolved. This issue is in relation to RNCamera, not the deprecated RCTCamera.

**Comment by gdoudeng** [comment]
we need `cropToPreview`

**Comment by blakito** [comment]
> we need `cropToPreview`

We do need it too

**Comment by Luminous13** [comment]
Any update on this one?

**Comment by D4nt4lion** [comment]
Feature is truly needed. Is this library dead?

**Comment by dipeshkoirala21** [comment]
Has anyone solved this issue?
