### ISSUE TITLE
Flash not Working

### ISSUE THREAD

**Issue by rf1804** [react-native-community/react-native-camera#1328]
I am using RCTCamera

react-native : 0.51.0
react-native-camera : 0.13.0
i've tried using RNCamera but it is giving more problems, video freezing and all, is there any solution for RCTCamera as everything is working absolutely fine except flash in video recording.
Please help me.

**Comment by rf1804** [comment]
Any Updates?

**Comment by bthuan** [comment]
I ran to the same issue. After i upgrade to version 1.0.3 then it works. I know upgrading from 0.13 -> 1.0.3 is not easy but it's worth trying

**Comment by n1ru4l** [comment]
RCTCamera is deprecated. Please use RNCamera instead. If there are any problems with RNCamera please open a separate issue that addresses the problem.
