### ISSUE TITLE
takePicture method is not invoked somehow

### ISSUE THREAD

**Issue by suhailjain** [react-native-community/react-native-camera#1332]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
code i used : 

  takePicture = async function() {
      if (this.camera) {
        const options = { quality: 0.5, base64: true };
        const data = await this.camera.takePictureAsync(options)
       console.log(data.uri);
    }
   };

  render() {
    return (
      <View style={styles.container}>
        <RNCamera
          ref={(cam) => {
            this.camera = cam;
          }}
          onBarCodeRead={this.onBarCodeRead.bind(this)}
          style={styles.preview}
          type={this.props.type}
          captureAudio={false}
        >
        <View style={styles.innerContainer}>

        <Icon
        raised
        iconStyle={{ backgroundColor: 'transparent' }}
        name='chevron-left'
        color='#003366'
        onPress={() => Actions.pop()}
        />

        <Icon
        raised
        name='camera'
        color='#003366'
        onPress={() => this.takePicture}
        />
        <Icon
        raised
        name='close'
        color='#003366'
        onPress={() => Actions.pop()}
        />

        </View>
        </RNCamera>
      </View>
  

### Expected behaviour
log statement should print to console 

### Actual behaviour
log is never printed thus takePicture is never invoked.
instead i get this in my dev tools console on chrome : 

[RNCamera initializeCaptureSessionInput]_block_invoke: Error Domain=AVFoundationErrorDomain Code=-11814 "Cannot Record" UserInfo={NSLocalizedDescription=Cannot Record, NSLocalizedRecoverySuggestion=Try recording again.}

### Environment
- **Node.js version**:8.9.3
- **React Native version**:0.51
- **React Native platform + platform version**: iOS 11.2
### react-native-camera
**Version**: v1.0.0

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by jgfidelis** [comment]
https://stackoverflow.com/questions/24176738/error-domain-avfoundationerrordomain-code-11814-cannot-record

Use a device

**Comment by suhailjain** [comment]
not working on a real android device.

**Comment by suhailjain** [comment]
**Attempted to transition from state `RESPONDER_INACTIVE_PRESS_IN` to `RESPONDER_ACTIVE_LONG_PRESS_IN`, which is not supported. This is most likely due to `Touchable.longPressDelayTimeout` not being cancelled**

above is printed to console when running on android real device and performing repetitive calls to takePicture method.

Please help.

**Comment by jgfidelis** [comment]
This is probably a problem not related to RNCamera, I cannot help you.

**Comment by suhailjain** [comment]
aint there issues on RNCamera not working for real devices ?

**Comment by suhailjain** [comment]
working fine now, JS code was the culprit

**Comment by dann1609** [comment]
@suhailjain what did you did? I have this problem but only on android, in iOs it works great!.

**Comment by suhailjain** [comment]
i changed the way i am declaring and calling the method 'takePicture'.

code changed that worked for me : 

instead of:
takePicture = async function() 

do this:
  async takePicture() {

and instead of:
 onPress={() => this.takePicture

do this:
onPress={() => this.takePicture()

@dann1609  do tell me if it works.

**Comment by dann1609** [comment]
@suhailjain my problem was I set state while app is takin picture. so I changed my code to call a set state with the promised returned from camera. No it works great. Also I found I have some premises issues that explain why it work in some androids and not in another.

**Comment by gshoanganh** [comment]
Seem you using an emulator, i think you need use 

> an device

.
Hope it helps you
