### ISSUE TITLE
onBarCodeRead works excellently on qrcodes but not not on code-128 or code-39

### ISSUE THREAD

**Issue by SaiKDot** [react-native-community/react-native-camera#1334]
```
         <RNCamera
            ref={ref => {
              this.camera = ref;
            }}
            style = {styles.preview}
            type={RNCamera.Constants.Type.back}
            flashMode={RNCamera.Constants.FlashMode.on}             
            permissionDialogTitle={'Permission to use camera'}
            permissionDialogMessage={'We need your permission to use your camera phone'}
             barCodeTypes={[RNCamera.Constants.BarCodeType.code39]}
             onBarCodeRead={this._bacr.bind(this)}

        />

   _bacr(e){
         Alert.alert(e.data);
       }
```
Nothing really happens. But when I remove the barCodeTypes props it scans qr codes,but not barcodes.
### Environment
- **Node.js version**: 5.5.1
- **React Native version**:  0.54.0
 

### react-native-camera
**Version**: npm version

**Comment by movie4** [comment]
ean13 barcode also not working

**Comment by movie4** [comment]
Seems like this issue https://github.com/react-native-community/react-native-camera/issues/1334

**Comment by SaiKDot** [comment]
I have solved this issue by using <Camera /> instead of <RNCamera />
Anyone reading this, don't forget to add 
`import Camera from 'react-native-camera';`  instead of `import { RNCamera } from 'react-native-camera';`
