### ISSUE TITLE
Crash on taking picture

### ISSUE THREAD

**Issue by emretekince** [react-native-community/react-native-camera#1340]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

RNCamera

### Steps to reproduce
1. open camera
2. takePictureAsync()
3. crash

### Expected behaviour
Tell us what should happen

### Actual behaviour
app crashes when calling takePictureAsync function

### Environment
- **Node.js version**:
- **React Native version**: 0.54.1
- **React Native platform + platform version**: Android 4-8

### react-native-camera
**Version**: 1.0.2

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by brunolemos** [comment]
I had a `java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/media/ExifInterface;` crash, this is fixed by adding this on `app/build.gradle`:

```diff
 compile (project(':react-native-camera')) {
         exclude group: "com.android.support"
         exclude group: "com.google.android.gms"
+        compile 'com.android.support:exifinterface:27.+'
     }
     compile ("com.google.android.gms:play-services-vision:11.8.0") {
         force = true;
     }
```

But after this I have this crash: `java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference`

Because for some reason `mBitmap = BitmapFactory.decodeByteArray(mImageData, 0, mImageData.length);` is returning null. I don't have a fix.

**Comment by brunolemos** [comment]
@emretekince do you have this on simulator only or also on a real device?

**Comment by brunolemos** [comment]
@emretekince @ratkus91 do you have this on Emulator only or also on a real device?

**Comment by emretekince** [comment]
@brunolemos Both

**Comment by gla5001** [comment]
i'm having same issue

**Comment by Traviskn** [comment]
I'm having problems with crashing only when trying to use face detection features on Android.  This is the error message I get:

```
03-12 18:52:53.155 9726-9775/com.universal E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
...
java.lang.RuntimeException: An error occured while executing doInBackground()
...
Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.internal.zzbjt
```

**Comment by brunolemos** [comment]
Update: The crash I was facing only happens on emulator, worked fine on device.

**Comment by jgfidelis** [comment]
@Traviskn probably related to your build/gradle. How is it? compile('reacti-native-camera') {...} ?

**Comment by Traviskn** [comment]
Here are my dependencies in my gradle file:
```
dependencies {
    compile project(':react-native-device-info')
    compile project(':react-native-wheel-picker-android')
    compile project(':react-native-fetch-blob')
    compile (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
    }
    compile ("com.google.android.gms:play-services-vision:10.2.0") {
        force = true;
    }
    compile project(':react-native-vector-icons')
    compile project(':react-native-sensitive-info')
    compile project(':react-native-i18n')
    compile project(':react-native-threads')
    compile project(':react-native-sqlite-storage')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:26.0.2'
    compile 'com.facebook.react:react-native:+'
}
```
I have quite a few dependencies already, after some googling I'm afraid I might be running into the Android 64K method limit, I may need to enable multi-dexing

**Comment by sibelius** [comment]
Check RNCamera example to see if the deps are correct

**Comment by emretekince** [comment]
@brunolemos it's fixed when I add **compile 'com.android.support:exifinterface:27.+'**. also working in emulator (Genymotion)

**Comment by victorpiccoli** [comment]
@Traviskn I had a similar error, fixed by removing 

 {
    	exclude group: "com.google.android.gms"
	compile 'com.android.support:exifinterface:27.+'
	}
    compile ("com.google.android.gms:play-services-vision:10.2.0") {
    	force = true;
	}
in app module of build.gradle

**Comment by Traviskn** [comment]
@victorpiccoli Thanks for the tip!

**Comment by filipencus** [comment]
Still crashing without any information to debug. Both emulator and real device crash when take picture.
RNCamera: 1.1.2
React Native: 0.55
