### ISSUE TITLE
[RNCamera] Image is stretched instead of cropped on Android

### ISSUE THREAD

**Issue by brunolemos** [react-native-community/react-native-camera#1343]
### Which implementation are you using

RNCamera

### Steps to reproduce
1. Create a **square** RNCamera component

### Expected behaviour
The square should be filled by cropping the camera (it does this on iOS), not by distorting/stretching the image.

Maybe it should also accept an `aspect` prop like the old camera implementation does (with `Camera.constants.Aspect.fill` as default).

### Actual behaviour
Image is distorted, the same way it would be if we used `Camera.constants.Aspect.stretch` on RCTCamera.

### Environment
- **Node.js version**: 8.9.0
- **React Native version**: 0.54.0
- **React Native platform + platform version**: Android 7

### react-native-camera
**Version**: 1.0.2

**Comment by chenkang2208** [comment]
I'm getting the same issue after updated from RTCCamera to RNCamera.

![actual](https://user-images.githubusercontent.com/7448127/37379168-4c408be6-276d-11e8-9a41-d542f308a63b.jpg)

![in_scan_window](https://user-images.githubusercontent.com/7448127/37379177-54a1334e-276d-11e8-981d-9d6dc0085d69.png)

**Comment by mjaffa-figure** [comment]
Yeah This would be nice to get fixed, as I am getting this issue too. Works great on iOS, and getting ready to pass on this component and either build our own or look for something else out there. But this is by far the best I have found out there.

**Comment by jgfidelis** [comment]
please try on master branch

**Comment by waitopiggu** [comment]
This is still a problem as of the master branch be3e0ebfb8ff42a48211b55054325548cd304694
![screenshot_20180409-155212](https://user-images.githubusercontent.com/26673366/38505275-b061b87e-3c0e-11e8-9ae0-730d615522c8.png)

**Comment by waitopiggu** [comment]
@aalices That's one way of looking at it, but it's not a good solution as it leads to unnecessary complexity. It would be better to just get the Android implementation to work correctly.

The logic [here](https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/org/reactnative/camera/RNCameraView.java#L172) needs a little more work. I will have a look at it when I get the chance or when I start testing on Android proper.

**Comment by nberktumer** [comment]
@jgfidelis I tried using RCTCamera and it was working fine with aspect prop.

**Comment by nberktumer** [comment]
@waitopiggu I had a look at the part that you said and changed the content of the if statement there. It's working fine on me now. I didn't tested the else statement but if statement is working fine.

```
if (height / width < ratio) {
    correctHeight = (int) height;
    correctWidth = (int) (height / ratio);
} else {
    correctHeight = (int) (width * ratio);
    correctWidth = (int) width;
}
```

**Comment by waitopiggu** [comment]
@nberktumer I'll try it out tomorrow and with a few different preview sizes to see what happens.

**Comment by waitopiggu** [comment]
I spent a couple of hours this afternoon working on this and it's working pretty well.

If someone else wants to test it out on another phone before I make a PR, that would be great.

https://github.com/waitopiggu/react-native-camera

---

![uniquekeenbarasinga-max-1mb](https://user-images.githubusercontent.com/26673366/38771099-ac42d016-4014-11e8-8ddb-55a43124d6e4.gif)

**Comment by avshenuk** [comment]
Nice, thanks, man. I’ll test it out in a while!

**Comment by sibelius** [comment]
it looks like a good approach, tks for the work

send a PR so more people could easily test it

can u also share this example app?

**Comment by waitopiggu** [comment]
@sibelius Done and https://github.com/waitopiggu/rn-camera-android-cropping-test

**Comment by brunolemos** [comment]
@sibelius can you make a new npm release?

**Comment by pkyeck** [comment]
@waitopiggu your example isn't working for me - it's resizing ok, but the preview always has a 4:3 ratio. Is this because my device doesn't support 1:1? Is this even a valid ratio?
