### ISSUE TITLE
Demo can't run!

### ISSUE THREAD

**Issue by AncientMing** [react-native-community/react-native-camera#1344]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-camera
**Version**: npm version or "master"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by n1ru4l** [comment]
I also noticed that. I will try to fix it this week

**Comment by jgfidelis** [comment]
https://github.com/react-native-community/rncamera-example

Is the oficial RNCamera example app

**Comment by n1ru4l** [comment]
@jgfidelis You should remove the Example folder in this repository and link the demo project

**Comment by sibelius** [comment]
@n1ru4l feel free to send a pr removing this demo from this repo

**Comment by jdeanwaite** [comment]
@sibelius I created PR #1396
