### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by AncientMing** [react-native-community/react-native-camera#1347]
#import <GoogleMobileVision/GoogleMobileVision.h>

File not found!!

### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-camera
**Version**: npm version or "master"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by jgfidelis** [comment]
Are you using face detection?

**Comment by sibelius** [comment]
follow docs to integrate properly

**Comment by jiaoxuebing2014** [comment]
![image](https://user-images.githubusercontent.com/8436801/37521320-3fbd6584-295b-11e8-863f-09a98e7e9eb5.png)


#import <GoogleMobileVision/GoogleMobileVision.h>
File not found!!

**Comment by pohsiu** [comment]
+1 same as @jiaoxuebing2014
