### ISSUE TITLE
Samsung picture rotated when picture is taken

### ISSUE THREAD

**Issue by ejkkan** [react-native-community/react-native-camera#1348]
### Which implementation are you using
*RNCamera*

### Steps to reproduce
1. take picture on a samsung phone

### Expected behaviour
When a picture is taken the picture should be faced the same way as the preview has taken it, the default behavior of any other android or ios phone. Tested on sony and honor phone, which works properly.

### Actual behaviour
When picture is taken on an samsung, the picture is rotated x amount of degrees rightward.

![img_1022](https://user-images.githubusercontent.com/32518962/37394305-b40a6138-2773-11e8-8055-84d19440b311.JPG)

![img_1023](https://user-images.githubusercontent.com/32518962/37394278-a32b9f4e-2773-11e8-8b7a-542c0db70ce8.JPG)

### Environment
- **React Native version**: 0.51.0
- **React Native platform + platform version**: Android version *any*, Only samsung phones. Tested on S8 and Galaxy J5

### react-native-camera
**Version**:  git+https://git@github.com/react-native-community/react-native-camera and 1.0.2 tested

**Comment by jgfidelis** [comment]
can you test with the fixOrientation option?
like:
```
options = { fixOrientation: true };
const data = await this.camera.takePictureAsync(options);
...
```

**Comment by eliaahadi** [comment]
@jgfidelis I tried that and it still rotates incorrectly. Any other suggestions?

**Comment by zthornto** [comment]
Not sure why this has been marked as closed. Am experiencing the same issue on an S7 edge. Has anyone discovered a fix yet? Thanks.

**Comment by byunghyunpark** [comment]
@ziks21 How did you solve the above issue?

**Comment by fozzarelo** [comment]
Has this issue been addressed?

**Comment by hielfx** [comment]
This issue is still happening today, has anybody found a solution yet? I'm experiencing this issue with a Samsung Galaxy S8 device and Xiaomi Mi A1

**Comment by skizzo** [comment]
Anybody managed to fix this?

**Comment by vinnyboySherb** [comment]
To skip pre-process from your device, you can do that :
`await this.camera.takePictureAsync({skipProcessing: true})`
That way the picture will be save has it will be taken by the user.
Find here : https://docs.expo.io/versions/latest/sdk/camera/
