### ISSUE TITLE
Complie Error 

### ISSUE THREAD

**Issue by nazmul-it** [react-native-community/react-native-camera#1351]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
npm install react-native-camera --save
react-native link react-native-camera

### Expected behaviour
Compiled and Build 

### Actual behaviour
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.react-native-community:cameraview:cc47bb28ed2fc54a8c56a4ce9ce53edd1f0af3a5.
     Required by:
         InstaForex:app:unspecified > InstaForex:react-native-camera:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

### Environment
- **Node.js version**: 5.6.0
- **React Native version**: 0.54.2
- **React Native platform + platform version**: iOS 9.0, Android 6.0, etc

### react-native-camera
**Version**: npm version or "master"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by sibelius** [comment]
Follow docs

Missing jitpack
