### ISSUE TITLE
Android build fails with 'missing return value' error

### ISSUE THREAD

**Issue by gla5001** [react-native-community/react-native-camera#1352]
### Which implementation are you using

*RNCamera*

### Steps to reproduce
1. Build android
2.
3.

### Expected behaviour
The android build should be successful

### Actual behaviour
The android build fails

```
> Task :app:processDebugGoogleServices
Parsing json file: /Users/gregalexander/Dev/fooder/android/app/google-services.json

> Task :react-native-camera:compileDebugJavaWithJavac
/Users/gregalexander/Dev/fooder/node_modules/react-native-camera/android/src/main/java/com/lwansbrough/RCTCamera/MutableImage.java:222: error: incompatible types: missing return value
          return;
          ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error


FAILURE: Build failed with an exception.
```

Maybe `convertExposureTimeToDoubleFormat` should return empty string when `!exposureTime.contains("/")` is true?

### Environment
- **Node.js version**: 8.9.1
- **React Native version**: 0.54.2
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-camera
**Version**:  master

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by gla5001** [comment]
if the fix for this is to just return an empty string in that case, i can open up a PR. Just let me know

**Comment by sibelius** [comment]
please do it

**Comment by gla5001** [comment]
👍

**Comment by ivansnek** [comment]
I'm facing the same error, is there a fix for this?

**Comment by almasaeed2010** [comment]
Tested #1353 and it works 👍

**Comment by sibelius** [comment]
fixed, tks
