### ISSUE TITLE
react-native-camera Unable to install and run

### ISSUE THREAD

**Issue by wabgy** [react-native-community/react-native-camera#1359]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

*RNCamera

### Steps to reproduce
1.
2.
3.

### Expected behaviour
RN version 0.48.2, before using RCTCamera to do a demo, react-native-camera can run. Now, RNCamera is used in the project, executed according to the steps on the GIT, and can not run at the end.

### Actual behaviour
Tell us what happens instead

### Environment
- **Node.js version**:
- **React Native version**:0.48.2
- **React Native platform + platform version**: Android 6.0

### react-native-camera
**Version**: npm version

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by sibelius** [comment]
Provide more info
