### ISSUE TITLE
Error. No camera found.

### ISSUE THREAD

**Issue by dann1609** [react-native-community/react-native-camera#1364]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
1. Use RCTCamera Or RNCamera.
2. Use the next code:
```
this.camera.capture()
                .then((data) => {
                  console.log('image captured: '+JSON.stringify(data));
                })
                .catch(err =>console.error(err));
```
3. Try on android 5.0.0
4. See console error.

`Error: No camera found.
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:347)
    at MessageQueue.js:137
    at MessageQueue.__guard (MessageQueue.js:265)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:72`

### Expected behaviour
Take a photo

### Actual behaviour
No photo is taken in android 5.0.0 and up.
lower version of android and iOS work well.

### Environment:
  OS: macOS Sierra 10.12.6
  Node: 7.8.0
  Yarn: Not Found
  npm: 4.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### react-native-camera
**Version**: 0.12 and 1.0.2

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by jgfidelis** [comment]
simulator or real device?

**Comment by zachrnolan** [comment]
Seeing this for a few users on real devices.

react: 16.3.0-alpha.1
react-native: 0.53.3
react-native-camera: 0.13.0

**Comment by jgcmarins** [comment]
@zachrnolan try version 1.1.5

**Comment by n1ru4l** [comment]
Closed due to missing feedback. If you still experience this issue with the newest version open a new issue
