### ISSUE TITLE
What is the correct syntax for using the quality property? (video)

### ISSUE THREAD

**Issue by arapocket** [react-native-community/react-native-camera#1365]
`const options = { maxFileSize: 5242880, quality: RNCamera.Constants.VideoQuality.480p };`
results in a syntax error at the `.480p`

`quality: 'RNCamera.Constants.VideoQuality.480p'` has no effect

**Comment by jgfidelis** [comment]
iOS code is:
```
@"VideoQuality": @{
                     @"2160p": @(RNCameraVideo2160p),
                     @"1080p": @(RNCameraVideo1080p),
                     @"720p": @(RNCameraVideo720p),
                     @"480p": @(RNCameraVideo4x3),
                     @"4:3": @(RNCameraVideo4x3),
                     },
```

So `RNCamera.Constants.VideoQuality.480p` should work.

Try to `console.log(RNCamera.Constants);` and see the object.

Your code looks correct.

**Comment by astutetechnp** [comment]
Try this for Android
`const options = {maxDuration:5, quality:RNCamera.Constants.VideoQuality['480p']}`
