### ISSUE TITLE
Incompatible block pointer types

### ISSUE THREAD

**Issue by chixpc123** [react-native-community/react-native-camera#1366]
hello @sibelius please checkout my issue. 

### Expected behaviour
it should work fine in real device

### Actual behaviour
I can't run on device, it showing error "Incompatible block pointer types...." as you can show in attached snapshot

### Environment
- **Node.js version**: v8.7.0
- **React Native version**: 0.54.2
- **React Native platform + platform version**: iOS 9.2

### react-native-camera
**Version**: git+https://git@github.com/react-native-community/react-native-camera

![screen shot 2018-03-20 at 1 08 35 pm](https://user-images.githubusercontent.com/23215308/37641958-8b9f4ba0-2c41-11e8-93ce-7a4e2e3e5078.png)
![screen shot 2018-03-20 at 1 08 12 pm](https://user-images.githubusercontent.com/23215308/37641978-9efb83bc-2c41-11e8-86cf-47a268ad1814.png)
![screen shot 2018-03-20 at 1 09 06 pm](https://user-images.githubusercontent.com/23215308/37641998-a6ed927c-2c41-11e8-8bc7-1655d01b94a3.png)

Thanks.

**Comment by jgfidelis** [comment]
Hmmm, maybe a problem with RN 0.54.2... they may have changed their method's signatures in the bridge library.

**Comment by jgfidelis** [comment]
Looks like they changed view registry from a NSDictionary to a RCTSparseArray type from your print screens...

**Comment by JeffreyHyer** [comment]
Any update on this? Running into the same issue on `react-native@0.54.4`
