### ISSUE TITLE
How to avoid multiple scans in one second

### ISSUE THREAD

**Issue by hrh94** [react-native-community/react-native-camera#1368]
When I scan the bar code, I want it to take only one scan in two seconds, in fact it's going to keep scanning.

**Comment by chen2584** [comment]
My current solution is
```javascript
onBarCodeRead = (scanResult) => {
    if(!this.barcodeList.includes(scanResult.data)) {
        this.barcodeList.push(scanResult.data);
    }
}
```

**Comment by krystianpach** [comment]
You can use component state:

`
export class BarcodeScanner extends React.Component {
    state = {
        isBarcodeScannerEnabled: true
    }
    
    constructor(props) {
        super(props)
        
        this.onBarCodeRead = this.onBarCodeRead.bind(this)
    }
    
    onBarCodeRead(event) {
        if (this.state.isBarcodeScannerEnabled) {
            // code //
            alert(event.data)
            this.setState({
                isBarcodeScannerEnabled: false
            })
        }
    }
    
    render() {
        return (
            <RNCamera
                style={styles.preview}
                onBarcodeRead={this.onBarCodeRead}
            />
        )
    }
}
`

**Comment by Bitenca** [comment]
Thanks @krystianpach! Like a charm!

**Comment by prateekgoel** [comment]
Using component state doesn't help. As setState is asynchronous, there are many times when multiple scans are triggered before the state changes.
@sibelius Please reopen this issue. I think react-native-camera should provide a better solution.

**Comment by KaoPengHsiang** [comment]
I have same problem when after setting isBarcodeScannerEnabled state, it take lots of scans in very short times that state didn't change in time. Is there any other solution can help?   > < "

**Comment by chen2584** [comment]
@KaoPengHsiang This was my ugly solution. I never test it without `stopPreview` variable. If you do, please let me know the result.

```javascript
constructor() {
    this.stopPreview = false; // I don't save this in state, because setState() is asynchronous
}

onBarCodeRead = async(scanResult) => {
    if(!this.stopPreview) {
        this.stopPreview = true;
        this.refs.camera.stopPreview(); // force camera to stop preview (also stop detect barcode)
        
        // your logic goes here

        this.stopPreview = false;
        this.refs.camera.stopPreview(); // force camera to start preview again
    }
}

render() {
    return (
        <Camera ref="camera" onBarCodeRead={this.onBarCodeRead} />
    );
}
```

**Comment by Jonnakutivijaykumar** [comment]
> I have same problem when after setting isBarcodeScannerEnabled state, it take lots of scans in very short times that state didn't change in time. Is there any other solution can help? > < "

Hello did u find any solution for this.

**Comment by KaoPengHsiang** [comment]
@Jonnakutivijaykumar I finally use a ugly solution, too. You can try it, it works for me.
```js
i = 0;
onBarCodeRead = result => {
    this.i++;
    if (this.i++ == 1) {
//your logic here
    if (
        this.state.isBarcodeScannerEnabled &&
        Actions.currentScene !== "SecondPage"
      ) {        
        // code //
        this.setState({
          isBarcodeScannerEnabled: false
        });
     Actions.currentScene !== "SecondPage"   ? Actions.push("SecondPage", { url: data }) : {} ;
}
````

**Comment by chengsam** [comment]
> Using component state doesn't help. As setState is asynchronous, there are many times when multiple scans are triggered before the state changes.
> @sibelius Please reopen this issue. I think react-native-camera should provide a better solution.

Just use a variable instead of state
