### ISSUE TITLE
Delete taken photo

### ISSUE THREAD

**Issue by skeie** [react-native-community/react-native-camera#137]
Hi,

Based on [this](https://github.com/johanneslumpe/react-native-fs/issues/34), is it possible that delete photo will be implemented into react-native-camera?

**Comment by lwansbrough** [comment]
Hey there, I have no plans to implement any fs operations in the camera module.

**Comment by skeie** [comment]
Hi @lwansbrough, thanks for answering. Is it possible to save the images to a async storage instead of the disk? I would love to be able to not save each images to the disk.

**Comment by lwansbrough** [comment]
AsyncStorage saves to disk in the background, so I'm not using it solves whatever problem you're trying to solve.

You also don't want to pass the image over the bridge in all likelihood, as it will lock the UI. Your best bet is to use the file system. If you really want to use JS APIs you can use the memory option as the target. This feature will come out of deprecation in 1.0.0.

**Comment by sibelius** [comment]
CameraRoll can delete photos on react-native 52
