### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by pohsiu** [react-native-community/react-native-camera#1371]
I want to use faceDetection function, so I follow the instruction from readme 
But got this error
![image](https://user-images.githubusercontent.com/3203630/37692566-88280a30-2cf4-11e8-943e-6fc9c647eaac.png)

I had pod install to link & add frameworks myself(by...)

> Podfile

`target 'camera' do`
`pod 'react-native-camera', subspecs: ['RCT', 'RN', 'FaceDetector'], path: '../node_modules/react-native-camera'`
`end`

> Add to framework(by 2 way, both failed and get same error) 

1.
![image](https://user-images.githubusercontent.com/3203630/37692494-05101214-2cf4-11e8-9ed7-b7a88240248e.png)
2. (this way will add Link Binary With Libraries auto)
![image](https://user-images.githubusercontent.com/3203630/37692543-5ba75452-2cf4-11e8-8624-e2a9f5c2c30c.png)

pod install warning (no idea how to fix this, either)
![image](https://user-images.githubusercontent.com/3203630/37692592-9ecc873e-2cf4-11e8-88ef-7dad0a378dff.png)

### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Expected behaviour
Works with faceDetection function

### Actual behaviour
GoogleMVDataOutput/GoogleMVDataOutput.h' file not found

### Environment
- **Node.js version**: v8.9.1
- **React Native version**: "0.53.3"
- **React Native platform + platform version**: iOS 11.2

### react-native-camera
**Version**: npm version or "master" latest version(2018/03/19 installed) from git+https://git@github.com/react-native-community/react-native-camera

**Comment by zhaiyjgithub** [comment]
same issue.

**Comment by jgfidelis** [comment]
can you try master branch?

**Comment by jgfidelis** [comment]
Is the bug still happening?

**Comment by n1ru4l** [comment]
Closed due missing feedback. Please feel free to reopen the issue if the issue does still occur.
