### ISSUE TITLE
Unable to take a photo on Samsung Galaxy Grand Prime

### ISSUE THREAD

**Issue by jpudysz** [react-native-community/react-native-camera#1379]
### Which implementation are you using
*RCTCamera*, cannot take a photo on *RNCamera* because of #1369 

### Steps to reproduce
1. Use older Android like Samsung Galaxy Grand Prime
2. Use RCTCamera
3. Take a photo

### Expected behaviour
Should return a photo

### Actual behaviour
Crash in native code occured

### Environment
- **Node.js version**: 7.6.0
- **React Native version**: 0.53.3
- **Android**: 5.1.1

### react-native-camera
**Version**: 1.0.1

### Stack trace
![error](https://user-images.githubusercontent.com/9088288/37708670-dcd71806-2d07-11e8-8685-e77a5c72cfaf.png)

### Additional info
I'm mounting/unmounting camera multiple times because of specific use case (full screen photo preview). I was trying to preserve camera ref and use `stopPreview` with `startPreview` but with no luck (I don't know if it's even related).

**Comment by deehuey** [comment]
Any resolution on this one?

**Comment by jpudysz** [comment]
I was able to resolve this issue on my own.
- refactor build.gradle (clean dependencies)
- use `RNCamera` because aspect ratio issue was resolved
- lower quality and resolution
