### ISSUE TITLE
GoogleMobileVision/GoogleMobileVision.h file not found

### ISSUE THREAD

**Issue by NijaahnandhRV** [react-native-community/react-native-camera#1383]
'GoogleMobileVision/GoogleMobileVision.h' file not found, I have installed the pod file and added the frameworks as given in the instruction even though i get the error
![screen shot 2018-03-22 at 11 15 18 am](https://user-images.githubusercontent.com/37614736/37753352-7c035240-2dc2-11e8-8f3a-4bfdbc09a4f8.png)
![screen shot 2018-03-22 at 11 16 07 am](https://user-images.githubusercontent.com/37614736/37753366-8679c88a-2dc2-11e8-893a-4e6888c0e4ab.png)
![screen shot 2018-03-22 at 11 17 17 am](https://user-images.githubusercontent.com/37614736/37753395-a1d5af22-2dc2-11e8-9889-90dfd047ae76.png)

My header search path

![screen shot 2018-03-22 at 11 18 10 am](https://user-images.githubusercontent.com/37614736/37753527-6935e10e-2dc3-11e8-8a66-9476dc43ce96.png)

Can you please help me!!!!

**Comment by jgfidelis** [comment]
The header search path is wrong. Change the first line to `$(SRCROOT)/../../../ios`

**Comment by jgfidelis** [comment]
Or try master branch, I fixed it there.

**Comment by danna88** [comment]
Change the first line to $(SRCROOT)/../../../ios?    is project targets or RNCamera targets?
