### ISSUE TITLE
':openCVLibrary340' could not be found

### ISSUE THREAD

**Issue by carlos03** [react-native-community/react-native-camera#1386]
### FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred evaluating project ':react-native-camera'.
> Project with path ':openCVLibrary340' could not be found in project ':react-native-camera'.

**Comment by sibelius** [comment]
@ma-pe check this please

**Comment by ma-pe** [comment]
Sorry - I (really) messed this up.

it's already resolved at master, please update.

**Comment by carlos03** [comment]
ok, Thanks
