### ISSUE TITLE
Shutter fired twice

### ISSUE THREAD

**Issue by sandropoluan** [react-native-community/react-native-camera#1390]
### Which implementation are you using
RCTCamera

### Expected behaviour
Shutter only fired one time

### Actual behaviour
Shutter fired twice almost every time I run the `capture()` method

### Environment
- **React Native version**: 0.53.3
-Android all vesion

### react-native-camera
**Version**: 1.0.1
```
takePhoto=()=>{
    const data = await this.camera.capture().then(data=>{
      console.log(data)
    }).catch(error=>{
      toast(error);
    });
}


render(){
    return(
    <View style={{flex:1}}>
        <Camera
        ref={(cam) => {
        this.camera = cam;
        }}
        style={{flex: 1,justifyContent: 'center',alignItems: 'center',flexDirection:'column'}}
        aspect={Camera.constants.Aspect.fill}                                                                                                                                
        type={this.state.type}
        >
            <TouchableOpacity onPress={this.takePhoto} style={{width:70,height:70,borderRadius:35,backgroundColor:'#1ab394',justifyContent:'center',alignItems:'center'}}>
                <MaterialIcons name='camera' style={{color:'#FFF',fontSize:40}}/>
                </TouchableOpacity>
        </Camera>
    </View>);
    }
```

This happen 80% of the cases.  

I don't use RNCamera due to [this](https://github.com/react-native-community/react-native-camera/issues/1267) problem

**Comment by jpudysz** [comment]
I encountered same issue on GoClever Quantum 2

**Comment by sibelius** [comment]
is this happening on RNCamera?

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
