### ISSUE TITLE
RNCamera does not export checkDeviceAuthorizationStatus anymore

### ISSUE THREAD

**Issue by piuccio** [react-native-community/react-native-camera#1398]
Hello, sorry for not using the issue template, I wasn't sure how to fill it.

Anyway in RNCamera the `checkDeviceAuthorizationStatus` method seems to have disappeared.
Or actually it's simply not exported anymore.

### Expected behaviour

According to the migration guide, I'm supposed to change

```js
import Camera from 'react-native-camera';
```

to

```js
import { RNCamera } from 'react-native-camera';
```

However, when I do that I get `RNCamera.checkDeviceAuthorizationStatus` is undefined

I ended up writing

```js
import Camera, { RNCamera } from 'react-native-camera';

await Camera.checkDeviceAuthorizationStatus();

render () {
  <RNCamera />
}
```

Which seems rather wrong.

Another approach would be

```js
import { NativeModules } from 'react-native';
import { RNCamera } from 'react-native-camera';
import { requestPermissions } from 'react-native-camera/src/handlePermissions';

await requestPermissions(true, NativeModules.RNCameraManager || NativeModules.RNCameraModule, '', '');
```

Which doesn't look much better.

I like the method `requestPermissions` because it nicely handles the different platforms, but would it be possible to expose a nicer API around it?

Something like the following would be amazing

```js
import { requestPermissions } from 'react-native-camera';

requestPermission(hasVideoAndAudio, permissionDialogTitle, permissionDialogMessage);
```

### react-native-camera
**Version**: 1.0.3

**Comment by Fconstant** [comment]
In the new `RNCamera` component permissions are requested automatically. If you want some customization there are specific props that you can pass to `RNCamera`:
- `permissionDialogTitle` (android only)
- `permissionDialogMessage` (android only)
- `notAuthorizedView`
- `pendingAuthorizationView`

[Check out the docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#android-permissiondialogtitle) for more info.
