### ISSUE TITLE
How to enable the camera face detector feature

### ISSUE THREAD

**Issue by harris666** [react-native-community/react-native-camera#1399]
version:
"react": "16.2.0"
"react-native": "0.51.0"
"react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera.git"

platform: android

I've written 'onFacesDetected' on RNCamera , but still not calling the callback.  What should i do?

**Comment by jgfidelis** [comment]
Check our example app
https://github.com/react-native-community/rncamera-example

**Comment by harris666** [comment]
The example still not work.

**Comment by piercefreeman** [comment]
Anyone have additional information about this?

**Comment by FrikkieSnyman** [comment]
I am experiencing the same problem.

On my Google Pixel 2, the `onFacesDetected` callback works perfectly. But executing the exact same code on a Samsung Galaxy Tab A6, the callback is just not being called at all. What is strange, is that the faceDetectionError callback is also not being called.

Would love to get a solution to this?

**Comment by stewartduffy** [comment]
Any updates on this??

**Comment by webmasterdragon** [comment]
Same issue here.

**Comment by drhenault** [comment]
Same here. Works with a Samsung Galaxy S6, but not with a Pixel C tablet.

**Comment by idrissbellil** [comment]
are testing on Android 8.0.0 and up?

**Comment by ManigandanRaamanathan** [comment]
Any update on this issue?

**Comment by liguanhan** [comment]
OnFacesDetected no callback. Are there any updates?
