### ISSUE TITLE
onframepreview not working

### ISSUE THREAD

**Issue by eviansplash** [react-native-community/react-native-camera#1406]
Placed a log inside onFramePreview (in the RNCameraView.java) and it's not working.. Tried creating a new project and installing it from scratch, still not working. Anybody else experiencing the same problem?

**Comment by eviansplash** [comment]
BUMP - no comments on this yet? I can't get barcode reader to work! and I'm following example

**Comment by liyanhuadev** [comment]
+1

**Comment by eviansplash** [comment]
no need for +1, i got it to work.. wasnt a gradle issue or anything like that, just needed to change js stuff hehe.. no need for panic
