### ISSUE TITLE
recordAsync: Expected a Camera component  

### ISSUE THREAD

**Issue by sivaranjansahu** [react-native-community/react-native-camera#1408]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using
RNCamera

### Steps to reproduce

Trying to record video with recordAsync, using the below code : 

1. <RNCamera
            ref	  = { (cam) => { this.camera = cam; } }
    				style = { styles.preview }
    				type  = { RNCamera.Constants.Type.back }
    				onCameraReady  = { () => { 
    				   this.setState( { message : 'Camera Ready !'})
    				}} />
2.   startVideo = async () => {
    if ( !this.camera ) return;
    try {
		  const data = await this.camera.recordAsync({ });
			console.log( data);
			this.setState( { message: 'Good' });
		} catch ( error) {
		  this.setState( { message: 'bad' });
      throw error;
		}
  }
   
3.stopVideo = () => {
		if ( !this.camera ) return;
		this.camera.stopRecording();
  }
4. react-native run-android
### Does it work with Expo Camera?
Did not try

### Expected behaviour
Video should be recorded and URI should be shown on console

### Actual behaviour
Error in console, app crashes

Console error ::
Possible Unhandled Promise Rejection (id: 0):
Error: recordAsync: Expected a Camera component
Error: recordAsync: Expected a Camera component
    at createErrorFromErrorData (blob:http://localhost:8081/ea79261d-48ec-42ef-b126-fbc7cc730629:2023:17)
    at blob:http://localhost:8081/ea79261d-48ec-42ef-b126-fbc7cc730629:1975:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/ea79261d-48ec-42ef-b126-fbc7cc730629:2417:18)
    at blob:http://localhost:8081/ea79261d-48ec-42ef-b126-fbc7cc730629:2162:18
    at MessageQueue.__guardSafe (blob:http://localhost:8081/ea79261d-48ec-42ef-b126-fbc7cc730629:2330:11)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/ea79261d-48ec-42ef-b126-fbc7cc730629:2161:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:72:58
console.warn @ D:\Learn\ReactNative\camera2\node_modules\react-native\Libraries\ReactNative\YellowBox.js:82
onUnhandled @ D:\Learn\ReactNative\camera2\node_modules\react-native\Libraries\Promise.js:44
onUnhandled @ D:\Learn\ReactNative\camera2\node_modules\promise\setimmediate\rejection-tracking.js:71
(anonymous) @ D:\Learn\ReactNative\camera2\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:258
_callTimer @ D:\Learn\ReactNative\camera2\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:154
callTimers @ D:\Learn\ReactNative\camera2\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:407
__callFunction @ D:\Learn\ReactNative\camera2\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:353
(anonymous) @ D:\Learn\ReactNative\camera2\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:118
__guardSafe @ D:\Learn\ReactNative\camera2\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:316
callFunctionReturnFlushedQueue @ D:\Learn\ReactNative\camera2\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:117
(anonymous) @ debuggerWorker.js:72

### Environment
- **Node.js version**: 6.11.4
- **React Native version**: 0.54.3
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
Android  7.1.1
### react-native-camera
**Version**: 1.0.3  and Masterbuild
 

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by jing-wu** [comment]
I got this error too. But I solved this by adding the following permissions in AndroidManifest.xml

`
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.RECORD_VIDEO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
`

**Comment by sivaranjansahu** [comment]
@jing-wu  I have that already in my manifest. 

I am stuck in this problem for last 2 days and its breaking my head! I am sure there is some small thing which I am missing, may be a combination of builds or something. Can any one please help!

 Here is the file : 

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.camera2">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
      <uses-permission android:name="android.permission.CAMERA" />

<uses-permission android:name="android.permission.RECORD_AUDIO"/>
<uses-permission android:name="android.permission.RECORD_VIDEO"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />


    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

**Comment by jgfidelis** [comment]
Your camera is not being mounted probably, is onMountError being called?

**Comment by internet5** [comment]
I have the same problem
How to resovle it?

**Comment by internet5** [comment]
I found the reason of error
the options before: quality: RNCamera.Constants.VideoQuality["2160p"] 
I changed quality to RNCamera.Constants.VideoQuality["460p"]
It worked!!

**Comment by alzoubiMohammed** [comment]
I have the same problem
How to sovle it?

**Comment by jgfidelis** [comment]
@alzoubiMohammed as @internet5 said, he changed the VideoQuality

**Comment by internet5** [comment]
@jgfidelis @alzoubiMohammed @sivaranjansahu 
I  was wrong, that problem doesn't matter with the VideoQuality, it's record-audio permission that is not opend automatically.
It worked when I open the record-audio permission manually.
i have this permissions:
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
Why i didn't get it opened? 
You sovled it?

**Comment by stevanus1997** [comment]
i have same problem, you already fix it?
if u fix it please the way

**Comment by alzoubiMohammed** [comment]
@stevanus1997  @internet5  
I found the solution only by adding the  Mute option in recordAsync()
like
const options = { mute:false };
 It will work

**Comment by stevanus1997** [comment]
const data = await this.camera.recordAsync({
      quality: RNCamera.Constants.VideoQuality['480p'],
      mute: false
    });

its still not working, always return video will 0 sec duration

**Comment by sosospicy** [comment]
@arapocket  use `await` in an `async` function like:
`checkPermission = async () => {
  let hasAudioPermission = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.RECORD_AUDIO)
}`

async/await are new syntax in ES7. [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)

**Comment by stevanus1997** [comment]
@sosospicy i already have permission for recording audio, but the result form recording always become 0 sec, please any one can help? 3 days more my thesis will be collected

**Comment by stevanus1997** [comment]
magic after i leave my code 3 weeks, and now its work

**Comment by blogdaren** [comment]
it's indeed that PermissionsAndroid.PERMISSIONS.RECORD_AUDIO not granted by user causing this issue.
