### ISSUE TITLE
Can't stop scanning after onBarCodeRead?

### ISSUE THREAD

**Issue by lucasleelz** [react-native-community/react-native-camera#1413]
### Expected behaviour
I use `RNCamera`，Can't stop scanning after `onBarCodeRead`?
When I call `stopRecording` method, `onBarCodeRead` method will still be called

### Actual behaviour
I hope to increase the method for starting and stopping scanning.
### Environment
- **Node.js version**: 5.7.1
- **React Native version**:0.54.3
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
- **react-native-camera**: 1.0.3

**Comment by Fconstant** [comment]
Create a flag on your component:
```js
onBarCodeRead = (...someArgs) => {
    if (!this.isBarcodeRead) {
         this.isBarcodeRead = true;
         // Do your work
    }
}
