### ISSUE TITLE
Application is Crash on Android version Marshmallow and above.

### ISSUE THREAD

**Issue by Ashi90** [react-native-community/react-native-camera#1419]
### Which implementation are you using

Version: React-native-camera:1.0.2

### Steps to reproduce
1.when click on video recorder icon app is crashed on Android Marshmallow.

### Environment
- **Node.js version**:0.0.1
- **React Native version**: 0.50.3
- **React Native platform + platform version**: iOS 9.0, Android 4.4, etc

**Comment by jgfidelis** [comment]
If you want any chance of help, you need to post more information, like what is the error.
