### ISSUE TITLE
[Enhancement] More stark brightness adjustment

### ISSUE THREAD

**Issue by rpastorelle** [react-native-community/react-native-camera#142]
Doing a quick search thru the issues it seems the brightness adjustment is automated based on tap-to-focus ([reference](https://github.com/lwansbrough/react-native-camera/issues/107#issuecomment-157232835)) ... However, I have this component in a production app with tap-to-focus and the brightness adjustment is minimal and hardly noticeable in low light conditions. Is there a way/a plan/a hint on how to make this adjustment more dramatic?

**Comment by RGBz** [comment]
:+1:

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
