### ISSUE TITLE
Request for Barcode scan area support

### ISSUE THREAD

**Issue by kosintop** [react-native-community/react-native-camera#1435]
I have been looking for ways to limit barcode scan area and have notice that RNCamera already have the  needed structure to support this feature on android (not sure about iOS)

In the [BarCodeScannerAsyncTask.java line#62](https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/org/reactnative/camera/tasks/BarCodeScannerAsyncTask.java#L62), the PlanarYUVLuminanceSource contructor which take in the previewed frame can take parameter top,left,width,and height which in effect will cropped the frame and will only scan for barcode in that specified area

I have tried roughly edit the code, set the mentioned params, and create a rectangle scan area in react side to see the result. It seems to be working but the area seems to be a little bit off which might be because the frame can get skewed depends on aspect ratio

this features has been request a few time #962, #815, and there is also a pull request #874 (but for RCT camera and does not get merged)

I'm not sure how the whole thing work so I would like to request this feature to be implemented

**Comment by tidydee** [comment]
Been looking at this myself. Would love to see this feature come to light.

**Comment by winadiw** [comment]
Any follow up on this? Really need this feature..

**Comment by n1ru4l** [comment]
@winadiw Feel free to send a pull request that addresses this issue.

**Comment by sibelius** [comment]
check this https://github.com/react-native-community/react-native-camera/pull/1852
