### ISSUE TITLE
RNCamera request: still/freeze frame during takePhotoAsync

### ISSUE THREAD

**Issue by wbyoung** [react-native-community/react-native-camera#1438]
I'd like to be able to capture a photo and have the experience be similar to the built in camera. Currently, the video preview continues beyond pressing the shutter & then a preview will show a prior frame from the video. This feels very odd when using the camera vs. the native experience.

### Steps to reproduce

1. With a mounted `RNCamera` component, call `takePhotoAsync`
2. Replace component w/ `<Image source={ ... } />` with the `uri` from the capture

### Does it work with Expo Camera?

It probably works the same way. I've opened a duplicate issue there, https://github.com/expo/expo/issues/1613.

### Expected behaviour

The (video) preview should be able to be frozen during the capture of the still image to mimic what happens when using the built in camera. (At least on iOS, that's how it works. I presume Android is the same, but don't have a device.)

### Actual behaviour

The component continues to show the video preview beyond what will be the actual captured image leading to an inconsistent user experience vs. the built in camera.

### Environment
- **Node.js version**: 9.5.0
- **React Native version**: 0.54.2
- **React Native platform + platform version**: iOS 11.2.5

### react-native-camera
**Version**: 1.0.2

**Comment by jgfidelis** [comment]
I think we have this implemented on RCTCamera, or at least I saw a pr for this feature, don't know if it got merged. If you want to implement it, take a look at rctcamera or at the old PRs at the repo! It is a nice feature.
