### ISSUE TITLE
Scan barcode in album orientation not works on RNCamera

### ISSUE THREAD

**Issue by 6pm** [react-native-community/react-native-camera#1439]
### Expected behaviour
Barcode scanning must work on album and portrait orientation.

### Actual behaviour
Scan barcode in album orientation not works. But on old version it worked fine.

### Environment
- **Node.js version**: 8.8.1
- **React Native version**: 0.50
- **React Native platform + platform version**: Android 6.0

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by SimonErm** [comment]
Have you tried using master?

**Comment by 6pm** [comment]
Yes, I tried on master.

**Comment by SimonErm** [comment]
But on portrait mode it works?

**Comment by 6pm** [comment]
Yes, on portrait works fine. Only on album mode not works.

**Comment by SimonErm** [comment]
#1667
