### ISSUE TITLE
Text Recognition for iOS

### ISSUE THREAD

**Issue by DavidRajPaul** [react-native-community/react-native-camera#1446]
Will there be text Recognition support for iOS?

**Comment by sibelius** [comment]
We gonna accept a Pr for this

**Comment by AlexandreLage** [comment]
Yeeey! I have been trying to develop it on my own (bridging RNCamera + Google Mobile Vision) but it has not been easy.

**Comment by AlexandreLage** [comment]
I know so far Google has released their "Google Mobile Vision" library supporting iOS Text Detection.

Is there anybody who could help us here?

**Comment by sibelius** [comment]
fixed https://github.com/react-native-community/react-native-camera/pull/1775

test on master

**Comment by almazpdf** [comment]
RNCamera onTextRecognized only returns empty [] ... for some reason. What am I doing wrong?

**Comment by MateusAndrade** [comment]
@almazpdf did you follow the link instructions related to Mlkit? Also, you can try the example with Mlkit to see If It works for you?
