### ISSUE TITLE
react native camera captured picture not save in app cache

### ISSUE THREAD

**Issue by Aashir1** [react-native-community/react-native-camera#1449]
I am using react-native-camera in my react-native app and everything works well, however when I take a photo the picture should be saved on my device, I addressed the mention location where my picture saves but there is no any image. How can I access capture image? I m using takePictureAsync.

**Comment by yz-xlame** [comment]
recordAsync([options]): Promise
The promise will be fulfilled with an object with some of the following properties:

uri: returns the path to the video saved on your app's cache directory.

iOS codec: the codec of the recorded video. One of RNCamera.Constants.VideoCodec

They say so

**Comment by jgfidelis** [comment]
It is saved on your cache directory. Do you have all correct permissions? If you want to save it somewhere else, like the Camera roll, you should use other libraries.

**Comment by jgfidelis** [comment]
Are you using RNCamera, RCTCamera...? Which version?

Please explain your problem better with a code snippet if possible.

**Comment by Aashir1** [comment]
"react": "16.3.0-alpha.1",
"react-native": "0.54.2",
"react-native-camera": "^1.0.3".

I am using RNCamera and with all permissions that mentioned in the react-native-camera documentation.

Thank you, @jgfidelis Camera roll works fine for my use case.

**Comment by josuesossou** [comment]
@AndrewHenderson  I want to do the same and even if it's possible not to save it in chache

**Comment by AndrewHenderson** [comment]
@josuesossou I'm ended up using [React Native FS](https://github.com/itinance/react-native-fs) to remove the file once I was done with it. 
```jsx
import { RNCamera } from 'react-native-camera';
import RNFS from 'react-native-fs';

takePhoto = async () => {
  const data = await this.camera.takePictureAsync();
  // Do what you need with the image and then…
  RNFS.unlink(data.uri); // Remove image from cache
}
```

**Comment by josuesossou** [comment]
@AndrewHenderson thank you so much, that was a great help!

**Comment by ramipaleo** [comment]
Hi @Aashir1 , How did you use Camera roll? I have all permissions that mentioned in the react-native-camera, but It show me error of access denied

**Comment by akbarmaulan4** [comment]
same issue, I'm using RNCamera, when get data uri I try to save to my local storage with react-native-fs,
