### ISSUE TITLE
How to increase the scan area of the react-native-camera?

### ISSUE THREAD

**Issue by nis24jit** [react-native-community/react-native-camera#145]
While scanning barcodes and qr codes,the scanning area is limited to the middle portion of the camera.Is it possible to increase the scanning area.I am able to scan the barcodes and qrcodes that fall in the middle portion of the camera but not above or below it.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
