### ISSUE TITLE
App alway crash when use RNCamera

### ISSUE THREAD

**Issue by vanhungoz** [react-native-community/react-native-camera#1451]
i using RNCamera in my app with some information 
react-native :0.52.0
"react-native-camera": "^1.0.3",
when i use " import Camera from 'react-native-camera';". it take a error "Permission denied".
<img width="236" alt="screen shot 2018-04-09 at 18 30 31" src="https://user-images.githubusercontent.com/35133417/38495562-3f6fbaa6-3c24-11e8-98ed-a85140f5fdb4.png">
-when i use "import { RNCamera } from 'react-native-camera';" . it make my app crash whenever i navigate to this screen.
anyone saw this error before.

**Comment by sibelius** [comment]
You need a permission to storage the image when taking photo

only after getting this permission that you can show the camera

**Comment by vanhungoz** [comment]
what information do you want? maybe i can show it for you ?

**Comment by vanhungoz** [comment]
"react-native-camera": "^1.0.3",
    "react-native": "0.52.0",
import {RNCamera} from 'react-native-camera';

**Comment by vanhungoz** [comment]
it make crash when i use import {RNCamera} from 'react-native-camera';
i can't log anything before it crash

**Comment by sibelius** [comment]
Try to use adb logcat

**Comment by vanhungoz** [comment]
adb logcat show me error is :"ErrorProcessor: Caused by: com.google.android.apps.gsa.shared.exception"

**Comment by sibelius** [comment]
we need the full stacktrace

**Comment by vanhungoz** [comment]
yes. i'll send to you soon

**Comment by vanhungoz** [comment]
can i set `compile (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
        compile 'com.android.support:exifinterface:27.+'
//        compile ("com.google.android.gms:play-services-vision:12.0.1")
    }`

**Comment by vanhungoz** [comment]
without 'com.google.android.gms:play-services-vision:12.0.1'

**Comment by vanhungoz** [comment]
in android . error is "Didn't find class "com.google.android.gms.vision.face.FaceDetector"

**Comment by vanhungoz** [comment]
may i use this lib without FaceDetector in android ?

**Comment by jgcmarins** [comment]
yes, @vanhungoz 
try to follow docs, please

**Comment by vanhungoz** [comment]
hi @jgcmarins  ,in android it work perfectly when i install lib with GVM. but whenever i install with  'com.google.android.gms:play-services-vision:12.0.1'.  it make app crash with logcat "Didn't find class "com.google.android.gms.vision.face.FaceDetector". 
i try to read README but according to README i just saw how to remove GVM in IOS, i can't see anything about ANDROID .

**Comment by jgcmarins** [comment]
I guess all `play-services` must be on same version

**Comment by vanhungoz** [comment]
now, i am installing GVM with no ideal to use it in my app.lol

**Comment by sibelius** [comment]
gvm is not required on ios

**Comment by jgfidelis** [comment]
1 - GVM is required on Android at all times.
2 - It is optional on iOS.

Are you still having any problem?

**Comment by vanhungoz** [comment]
thanks @jgfidelis . now it work for me.
