### ISSUE TITLE
Conflicts when using pod Firebase/Database (react-native-firebase) on iOS

### ISSUE THREAD

**Issue by leonchabbey** [react-native-community/react-native-camera#1460]
### Which implementation are you using

RNCamera

### Steps to reproduce
1. npm install react-native-firebase
2. Edit Podfile and add ```pod Firebase/Database``` and then ```pod update```
3. Try to build the app

### Expected behaviour
Should build without conflicting. It only happens with the specific ```pod Firebase/Database```.

### Actual behaviour
For reasons that I don't know, when I add Firebase/Database to my Podfile (I'm also using Firebase/Core and Firebase/Auth but they don't conflicts) it breaks RNCamera.
#PodFile:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # FCM
  pod 'Firebase/Messaging'
  
  # RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database' # Causes the issue
end
```
<img width="269" alt="screen shot 2018-04-12 at 12 48 59" src="https://user-images.githubusercontent.com/12344434/38673015-31be62ee-3e50-11e8-8765-351e353dc457.png">

<img width="269" alt="screen shot 2018-04-12 at 12 49 05" src="https://user-images.githubusercontent.com/12344434/38673017-332f12d6-3e50-11e8-9a17-6d6e2fdb85e5.png">
<img width="268" alt="screen shot 2018-04-12 at 12 49 11" src="https://user-images.githubusercontent.com/12344434/38673021-351d91bc-3e50-11e8-8da9-86cf0eea266b.png">
<img width="269" alt="screen shot 2018-04-12 at 12 49 19" src="https://user-images.githubusercontent.com/12344434/38673022-36e3a1da-3e50-11e8-991b-025fd9db5a3c.png">
<img width="269" alt="screen shot 2018-04-12 at 12 49 22" src="https://user-images.githubusercontent.com/12344434/38673045-472dcc82-3e50-11e8-9c33-861f5cfeeb4d.png">

### Environment
- **Node.js version**: v9.7.1
- **React Native version**: 55.1
- **React Native platform + platform version**: iOS 11.3 (not tested on Android) and Xcode 9.3

### react-native-camera
**Version**: 1.0.3

**Comment by leonchabbey** [comment]
Yep, I've found a way to make them work together.

My solution has been to not use Cocoapods for react-native-firebase and add the frameworks manually into my project.
1) Downloading all of them at: https://firebase.google.com/download/ios
2) Create a folder in my project under: ios/Firebase
3) Put all the frameworks I need in the folder and drag and drop them in xcode

(Note: I had to **not use the frameworks "GoogleToolboxForMac.framework" and "nanopb.framework"** because of duplication (Apple Match-O Linker dupication error...))

**Comment by jgfidelis** [comment]
Cool... at our projects we avoid cocoapods at all, because it usually gives us too much problem with RN. Happy you found a solution and explained it for others, well done.
