### ISSUE TITLE
Android error with googleVisionBarcodeType defaultProp

### ISSUE THREAD

**Issue by waitopiggu** [react-native-community/react-native-camera#1461]
### Which implementation are you using

RNCamera

### Steps to reproduce
1. Initialize component without supplying prop `googleVisionBarcodeType`
2. Run on Android device
3. The component throws an error

### Expected behaviour
The component should mount using its default parameters

### Actual behaviour
RNCamera fails to initialize unless googleVisionBarcodeType prop is supplied as a number.

### Environment
- Node v9.11.1
- React Native v0.55.2
- Android 6.0

### react-native-camera
master

---

Supplying `googleVisionBarcodeType={0}` allows the component to initialize, but it should not be necessary when  not using the barcode scanner functionality.

---

>ExceptionsManager.js:71 Warning: Failed prop type: Invalid prop `googleVisionBarcodeType` of type `object` supplied to `Camera`, expected `number`.
>    in Camera (at Camera.js:7)
>    in Camera (at App.js:8)
>    in App (at renderApplication.js:33)
>    in RCTView (at View.js:60)
>    in View (at AppContainer.js:102)
>    in RCTView (at View.js:60)
>    in View (at AppContainer.js:122)
>    in AppContainer (at renderApplication.js:32)

![screenshot_20180413-101840](https://user-images.githubusercontent.com/26673366/38729272-59066206-3f0a-11e8-91b5-477598a46e4a.png)

**Comment by sibelius** [comment]
The proptypes is wrong, can u send a pr to fix it?

**Comment by waitopiggu** [comment]
@sibelius is `0` a safe value to set it as? The default prop is currently `{}`.

**Comment by sibelius** [comment]
You should use exported constants instead of direct numbers

**Comment by jgfidelis** [comment]
I think that 0 not woking is wrong...

Looking at the code in BarcodeDetectorUtils:
```
public class BarcodeFormatUtils {

  public static final SparseArray<String> FORMATS;
  public static final Map<String, Integer> REVERSE_FORMATS;

  private static final String UNKNOWN_FORMAT_STRING = "UNKNOWN_FORMAT";
  private static final int UNKNOWN_FORMAT_INT = -1;

  static {
    // Initialize integer to string map
    SparseArray<String> map = new SparseArray<>();
    map.put(Barcode.CODE_128, "CODE_128");
    map.put(Barcode.CODE_39, "CODE_39");
    map.put(Barcode.CODE_93, "CODE_93");
    map.put(Barcode.CODABAR, "CODABAR");
    map.put(Barcode.DATA_MATRIX, "DATA_MATRIX");
    map.put(Barcode.EAN_13, "EAN_13");
    map.put(Barcode.EAN_8, "EAN_8");
    map.put(Barcode.ITF, "ITF");
    map.put(Barcode.QR_CODE, "QR_CODE");
    map.put(Barcode.UPC_A, "UPC_A");
    map.put(Barcode.UPC_E, "UPC_E");
    map.put(Barcode.PDF417, "PDF417");
    map.put(Barcode.AZTEC, "AZTEC");
    FORMATS = map;


    // Initialize string to integer map
    Map<String, Integer> rmap = new HashMap<>();
    for (int i = 0; i < map.size(); i++) {
      rmap.put(map.valueAt(i), map.keyAt(i));
    }

    rmap.put("ALL", 0);
    REVERSE_FORMATS = Collections.unmodifiableMap(rmap);
  }

  public static String get(int format) {
    return FORMATS.get(format, UNKNOWN_FORMAT_STRING);
  }

  public static int get(String format) {
    if (REVERSE_FORMATS.containsKey(format)) {
      return REVERSE_FORMATS.get(format);
    }

    return UNKNOWN_FORMAT_INT;
  }
}
```
`rmap.put("ALL", 0);` so 0 should be read all?
A good fix would be to create a `none` value in the constants and make:
`googleVisionBarcodeType: (CameraManager.GoogleVisionBarcodeDetection || {}).BarcodeType.None`
in defaultProps. If no one fix this, I will try during the weekend.
