### ISSUE TITLE
Error while updating property 'barcodeScannerEnabled' of view managed by : RNCamera

### ISSUE THREAD

**Issue by Moussawi7** [react-native-community/react-native-camera#1467]
### Which implementation are you using
RNCamera

### Steps to reproduce
1.install the plugin : npm install --save https://github.com/react-native-community/react-native-camera
2.link it :react-native-link react-native-camera
3.add the js code

```
<RNCamera
          ref={(cam) => {
            this.camera = cam;
          }}
          ratio="1:1"
          permissionDialogTitle={'Permission to use camera'}
          permissionDialogMessage={'We need your permission to use your camera phone'}
          onBarCodeRead={(e)=>this.onBarCodeRead(e)}
          style={Styles.camera}/>
```

### Expected behaviour
Scan QR code

### Actual behaviour
throw an error saying "Error while updating property 'barcodeScannerEnabled' of view managed by : RNCamera"
![screenshot_2018-04-14-17-57-25_1024](https://user-images.githubusercontent.com/5157060/38769610-4f344dc4-400e-11e8-9081-ef09d6e91e43.png)

### Environment
- **Node.js version**:8.0.0
- **React Native version**:0.53.3
- **React Native platform + platform version**: Android 6.0.1

### react-native-camera
**Version**: "master"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by wassgha** [comment]
Having this bug too

**Comment by sibelius** [comment]
it could be related to this commit https://github.com/react-native-community/react-native-camera/pull/1464

can u try with a commit before that one?

**Comment by jgfidelis** [comment]
Does it happen as soon as the app starts?

It doesn't happen on my emulator, it happens only on when you point it to a barcode?

**Comment by jgfidelis** [comment]
Can you guys tell me if #1469 fixes the bug?

**Comment by ajaykumar97** [comment]
Following configuration worked for me: 
`implementation (project(':react-native-camera')) {
        implementation ("com.google.android.gms:play-services-vision:10.0.1") {
            force = true
        }

        exclude group: "com.google.android.gms"
        implementation 'com.android.support:exifinterface:27.+'
    }
implementation 'com.google.android.gms:play-services-base:10.0.1'
`

Make sure that all google-play-services implementations have same version(10.0.1 in my case).

**Comment by AndreyPatseiko** [comment]
Please update the documentation as the starting example uses **onGoogleVisionBarcodesDetected** function for read code. (in BadInstagramCloneApp)

**Comment by n1ru4l** [comment]
@AndreyPatseiko Feel free to send a pull request that improves the documentation if there are any misunderstandings.
