### ISSUE TITLE
Incompatible block pointer types sending 'void (^)(RCTUIManager *__strong, NSDictionary<NSNumber *,RNCamera *> *__strong)' to parameter of type 'RCTViewManagerUIBlock' (aka 'void (^)(RCTUIManager *__strong, RCTSparseArray *__strong)')

### ISSUE THREAD

**Issue by blaZ3** [react-native-community/react-native-camera#1471]
I am getting this following error when trying to build in iOS,

`Incompatible block pointer types sending 'void (^)(RCTUIManager *__strong, NSDictionary<NSNumber *,RNCamera *> *__strong)' to parameter of type 'RCTViewManagerUIBlock' (aka 'void (^)(RCTUIManager *__strong, RCTSparseArray *__strong)')`

My react native version is - 0.50.4 which version is the library depending on. It works fine in Android.

**Comment by jgfidelis** [comment]
https://github.com/airbnb/lottie-react-native/issues/113

Please try this
