### ISSUE TITLE
Children components (visually) persist between umount and re-mount

### ISSUE THREAD

**Issue by monyxie** [react-native-community/react-native-camera#149]
When a `<Camera />` component is unmounted and mounted again, its children components will persist. 
[Demo](https://gist.github.com/monyxie/dd0552a72262fe508891):
![rn-camera mov](https://cloud.githubusercontent.com/assets/703164/12225476/3fde110e-b846-11e5-8d7e-c0b8919dc1a5.gif)
In the demo, everytime `<Camera />` mounts, it renders a randomly positioned line as its child. You can see the previous lines persist when `<Camera />` umounts and mounts again.

**Comment by MatthewRDodds** [comment]
I'm experiencing this same issue with iOS when trying to show a slightly different camera view (scanning barcode vs taking a picture):

![screen shot 2016-03-10 at 2 27 09 pm](https://cloud.githubusercontent.com/assets/1717864/13681659/492a27f2-e6cc-11e5-8399-a43d038f84e1.png)

The previous view is visually persistent, as if it's just been chilling in the background until I render my next camera view on top of it.

@monyxie were you able to find a workaround?

**Comment by monyxie** [comment]
@MatthewRDodds We took our child component and put it under the same parent as `<Camera/>`, then we styled it so that it appears on top of `<Camera/>`.

**Comment by MatthewRDodds** [comment]
That solution seems to have worked for me as a work-around.

**Comment by rt2zz** [comment]
If I recall correctly, react-native-maps had a similar issue that they resolved. unfortunately I cannot find a reference in the commits. If anyway has any ideas help would be appreciated.

**Comment by bz123** [comment]
I found a workaround, hacky but well I'll leave it here in case anyone else wants to hack around it.

The trick is to wrap your condition under a view within the camera itself e.g:

`<Camera><View> {this.state.isTrue && <Text> Hi </Text>} </View> </Camera>`

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
