### ISSUE TITLE
Unable to access camera permissions on android

### ISSUE THREAD

**Issue by cukiy** [react-native-community/react-native-camera#1492]
## A warning will pop up when you jump to the camera interface, and the interface is always waiting.

![image](https://user-images.githubusercontent.com/22424504/38907819-1dd810c8-42f0-11e8-8a8e-9e4d0f238264.png)

<RNCamera
                    ref={ref => { this.camera = ref; }}
                    style = {styles.preview}
                    type={RNCamera.Constants.Type.back}
                    flashMode={RNCamera.Constants.FlashMode.on}
                    permissionDialogTitle={'请求权限'}
                    permissionDialogMessage={'需要访问您的相机'}
                />

## These permissions have been added:
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

## Environment
node.js version : 8.9.1
react-native version : 0.36.0 

Thank you for your help

**Comment by sibelius** [comment]
english please

it looks like u have an old react native version

**Comment by cukiy** [comment]
The RCTCamera can access the camera.  What's the minimum version of react native for RNCamera?

**Comment by xenu256** [comment]
See [this working example](https://github.com/react-native-community/react-native-camera/issues/1708#issuecomment-429547891)

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
