### ISSUE TITLE
A problem occurred evaluating project ':react-native-camera'.

### ISSUE THREAD

**Issue by xichaoliu** [react-native-community/react-native-camera#1496]
### Error
Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by sibelius** [comment]
Upgrade to gradle 3

**Comment by jsina** [comment]
@sibelius I've see your workaround as many as I'm searching for this problem. could you please explain your workaround much better for me. I've stuck with this problem and I could not resolve it yet.
