### ISSUE TITLE
Image from camera is rotate image

### ISSUE THREAD

**Issue by top24056** [react-native-community/react-native-camera#1498]
I use react-native-camera (RNCamera)  but image from camera is rotate

this my function take picture
`takePicture = async function(){
        if(this.camera){
            const options = {
                quality : 1,
                width : 500,
                height : 500
            };
            const data = await this.camera.takePictureAsync(options);
        }
    }`

**Comment by jgfidelis** [comment]
ios or Android?

Have you tried the `forceUpOrientation` (ios) and `fixOrientation` flags on options?

**Comment by top24056** [comment]
Thank you for your suggestion. It's work
