### ISSUE TITLE
How to use it scan barcode.

### ISSUE THREAD

**Issue by liukepeng** [react-native-community/react-native-camera#150]
run it I can saw camera open,but how to use it implement scan barcode? Or look like scanning something?

**Comment by lwansbrough** [comment]
You can use the `onBarCodeRead` property on `Camera` to capture bar code reads. A bounding box is returned which can be used to draw the location of the barcode.

**Comment by Talkwondo** [comment]
Hello,
Can you elaborate? maybe copy a text code here?

Thanks,

**Comment by marxsk** [comment]
Look at an example on:
https://github.com/lazaronixon/react-native-qrcode-reader

**Comment by sahir** [comment]
scan barcode example have a look : https://github.com/sahir/react-native-barcode-reader

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
