### ISSUE TITLE
Build fails with manual link IOS

### ISSUE THREAD

**Issue by connercms** [react-native-community/react-native-camera#1500]
### Which implementation are you using
RNCamera

### Steps to reproduce
Follow manual link instructions exactly on readme
1. npm install react-native-camera --save
2. Right click libraries in Xcode project, add RNCamera.xcodeproj
3. Add libRNCamera.a to Build Phases - Link Binaries With Libraries
<img width="273" alt="screen shot 2018-04-19 at 12 55 32 pm" src="https://user-images.githubusercontent.com/12799522/39010016-ef308ab4-43d2-11e8-9311-1467f4e2dbfd.png">
4. Ensured RNCamera project Header Search Paths contain both $(SRCROOT)/../../react-native/React and $(SRCROOT)/../../../React 
<img width="515" alt="screen shot 2018-04-19 at 1 00 30 pm" src="https://user-images.githubusercontent.com/12799522/39010028-fa3f381a-43d2-11e8-8087-e3d6bb3062da.png">
5. Clean and rebuild project 
<img width="270" alt="screen shot 2018-04-19 at 12 55 19 pm" src="https://user-images.githubusercontent.com/12799522/39010052-0870a95a-43d3-11e8-9f62-c29a00db3bef.png">

### Expected behaviour
Project to build?

### Actual behaviour
Project does not build

### Environment
- **Node.js version**: 5.0.3
- **React Native version**: 0.51.0

### react-native-camera
**Version**: ^1.1.1

**Comment by brenwell** [comment]
I have the identical issue, did you solve your issue?

**Comment by connercms** [comment]
@brenwell No, I am still stuck on this problem

**Comment by brenwell** [comment]
![screen shot 2018-04-20 at 15 14 37](https://user-images.githubusercontent.com/802618/39052850-a2fe902e-44ad-11e8-9cd0-00b1a73667b0.png)

This fixed it for me Enable Modules -> **NO**

**Comment by connercms** [comment]
I tried disabling this option for my project, RNCamera project, and both projects and build still failed every time.

**Comment by connercms** [comment]
Right clicking on libRNCamera.a and clicking Show In Finder does not show anything, and libRNCamera.a text is red. I think it may have something to do with this but not very familiar with Xcode

**Comment by brenwell** [comment]
Well that sucks, I also rolled back , perhaps that helps

```json
"react-native-camera": "1.0.3",
```

**Comment by jgfidelis** [comment]
Is it working on 1.0.3?

**Comment by jgfidelis** [comment]
Please try on 1.1.0 as well.

Maybe some dependency we introduced when adding CircleCI to the project caused this

**Comment by connercms** [comment]
No. Have tried rolling back version, disabling modules as suggested above, removing library and reinstalling and trying react-native link, upgrading react-native version to latest and trying above combinations, but nothing works.

**Comment by connercms** [comment]
Will try 1.1.0

**Comment by connercms** [comment]
No luck. Disabled modules for RNCamera project removes the Parse Issue errors from the screenshot above, but can't get rid of the Lexical or Preprocessor Issue, 'string' file not found issue no matter what I try.

**Comment by brenwell** [comment]
Problem returned for me and I couldn't shake it. Sadly I had to swap to an alternative lib. It appears the 1.0.3 didn't make any difference

**Comment by connercms** [comment]
Closed with no solution? Looks like I'll find an alternative library also

**Comment by FacuAcosta** [comment]
Having the same issue on v1.1.1, why is this even closed?

```
"react": "^16.3.2",
"react-native": "^0.55.3",
```

**Comment by MrPistoul** [comment]
Same problem here
Someone have a solution ?
"react-native-camera": "^1.1.1"
"react": "^16.3.2",
"react-native": "^0.54.4",

**Comment by himanshusoni** [comment]
Any updates on this issue ?

we recently moved from `react-native-barcode-universal` (which used rn-camera 1.0 internally ) to `react-native-camera: 1.4.3` 
The interesting fact is that we are facing the above issue on xcode 10. But its working fine on xcode 9.3.1 !!

```
    "react": "16.3.1",
    "react-native": "0.55.4",
```

**Comment by FlavioNascimento10** [comment]
Same problem here. Someone have a solution?
