### ISSUE TITLE
Limit barcode scan area?

### ISSUE THREAD

**Issue by remisaado** [react-native-community/react-native-camera#1503]
I am using the barcode scanner from react-native-camera and currently if I use it and there are multiple QR-codes closely on top of each other, I point my camera at one and it reads the code above it which is outside of the display on screen but within the cameras view. If however there is no QR-code above the one I want to scan, then it scans the correct one, so it seems like it always scans the top QR-code within the cameras view.

**Here's my question:** Is there a way to limit the "scan area" to be the same size and area as my camera view on my display?

```
<View style={styles.container}>
  <Camera
    style={styles.preview}
    onBarCodeRead={this.onBarCodeRead}
    ref={cam => this.camera = cam}
    aspect={Camera.constants.Aspect.fill}>
  </Camera>
  <Button
    style={styles.buttonStyle}
    <Text>{this.state.qrcode}</Text>
  </Button>
</View>

const styles = {
  container: {
    height: 300,
    flex: 1
  },
  preview: {
    flex: 1
  },
  buttonStyle: {
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 20,
    alignSelf: 'center'
  }
}
```

Versions, if needed:
```
"react-native": "0.42.3",
"react-native-camera": "0.6.0",
```

[My question on Stackoverflow](https://stackoverflow.com/questions/49880395/react-native-camera-limit-barcode-scan-area)

**Comment by YLeaves** [comment]
I also use this library to implement the QR code scanning function. The callback method of barcodeReceived is always called, so I set a recognition area based on the callback parameters. The callback parameter contains the frame you scanned. You can use a range of coordinate points as the recognition area, and then use a variable to mark the read information.

Here's my treatment. I hope I can help you

Ps: My QR code scan area is the size of 200x200 in the middle of the screen. The 2D code origin identification area is a range in the upper left corner

var width = Dimensions.get('window').width
var height = Dimensions.get('window').height

let viewMinX = (width - 200)/2;
let viewMinY = (height - 200)/2;

let isShowCode = false;

barcodeReceived(e) {
        //console.log(e)
        let x = Number(e.bounds.origin.x)
        let y = Number(e.bounds.origin.y)

        //识别二维码左上角坐标点位置
        if ((x > viewMinX && y > viewMinY )&&( x < (viewMinX + 60) && (y < viewMinY + 60))){
            if (!isShowCode){
                isShowCode = true;
                alert('Type: ' + e.type + '\nData: ' + e.data);
            }
        }
    }

**Comment by twxia** [comment]
For iOS, I do something like @YLeaves says.

In Android, now always return finder pattern's coordinates. Also, I try to modify `RCTCameraViewFinder.java` and use `WhiteRectangleDetector` from https://github.com/zxing/zxing to get the boundary. I can't get the actual boundary of the qr code, but only finder pattern's coordinates. So it's hard to restrict the scanner area. Not sure I'm using the right method from `zxing`.

If we need to achieve this restriction area, seems we need to export some parameters(left, top, width, height) from `PlanarYUVLuminanceSource` to let developers to setup the scanning area.

**Comment by HarshitMadhav** [comment]
Facing the same issue I am unable to set the custom width and height to the scan area.

**Comment by anniewey** [comment]
@remisaado Did you manage to find any solution?

**Comment by gaodeng** [comment]
any news

**Comment by anniewey** [comment]
@gaodeng you can apply the `rectOfInterest` PR for iOS. But for Android I couldn't get it work with this library, hence using other [library](https://github.com/react-native-component/react-native-smart-barcode).

**Comment by ntk0104** [comment]
any news guys?

**Comment by jsastriques** [comment]
help here plz, i face the same doubt

**Comment by mjm918** [comment]
Any update on this?

**Comment by adimshev** [comment]
+1

**Comment by ceessay** [comment]
Having a similar use case. I am using text detection with ML Kit. Detection is made on electric meters which can have multiple text blocs on them. Would be useful to have a mask specifying the area to consider when performing detection, every piece of text outside that area would be ignored.

**Comment by kaduelinho** [comment]
I'm having the same issue

**Comment by lededje** [comment]
Can you use the bounding coords in the callback and use those to discard anything that is outside of the bounds you want?

**Comment by MakhouT** [comment]
I also need this...

**Comment by lededje** [comment]
I too had to do this recently. I've managed to achieve something I'm happy with so I thought I'd share it here. I believe the correct solution is a fully native one so I'm inclined not to make a pr to add this into the plugin but I'll share my workaround:

First I specified the height and width of the viewport I wanted to check against:

```js
const viewfinderHeight = 200;
const viewfinderWidth = 300;
```

You will need an aabbCollision function. These are pretty simple:

```js
const aabb = (obj1, obj2) => obj1.x < obj2.x + obj2.width
    && obj1.x + obj1.width > obj2.x
    && obj1.y < obj2.y + obj2.height
    && obj1.y + obj1.height > obj2.y;
```

All this does is check the height, width, x position and y position of two objects and see if they collide. This can be tweaked to ensure that one is entirely within another or maybe a prebuilt rotation-aware n-body continuous collision detection function but this wasn't needed for my project.

Next I needed to know which area of the screen was the area that is deemed safe.

```js
  const { height: windowHeight, width: windowWidth } = Dimensions.get('window');
  const viewFinderBounds = {
    height: viewfinderHeight,
    width: viewfinderWidth,
    x: (windowWidth - viewfinderWidth) / 2,
    y: (windowHeight - viewfinderHeight) / 2,
  };
```

Using the `onGoogleVisionBarcodesDetected` to get the the full bounding box, I checked each matched barcode against the viewfinder bounds.

```js
onGoogleVisionBarcodesDetected={({ barcodes: detectedBarcodes = [] }) => {
  const collidingBarcodes = barcodes.filter((barcode) => aabb(viewFinderBounds, {
    height: barcode.bounds.size.height,
    width: barcode.bounds.size.width,
    x: barcode.bounds.origin.x,
    y: barcode.bounds.origin.y,
  });

  setBarcodes(collidingBarcodes)
}
```
The last thing I needed was something visual so the user can see what area is designated for scanning. I used the react-native-barcode-mask and passed in the viewport sizes like so:

```jsx
<BarcodeMask width={viewfinderWidth} height={viewfinderHeight} showAnimatedLine={false} transparency={0.8} />
```

Below is an example of what I ended up with. The red barcode is not colliding with the viewport and is ignored.

<img src="https://user-images.githubusercontent.com/1545098/72205381-1b7c3200-347a-11ea-8094-9af33938e31c.jpeg" alt="Barcode collision demonstration" width="200" />

**Comment by amirulasrof** [comment]
+1

**Comment by kaduelinho** [comment]
Please don't close this issue, should be great if has this feature!!!

**Comment by amirulasrof** [comment]
> Please don't close this issue, should be great if has this feature!!!

Now you can use rectOfInterest for both Android and iOS to limit scan area

**Comment by skyrippa** [comment]
> > Please don't close this issue, should be great if has this feature!!!
> 
> Now you can use rectOfInterest for both Android and iOS to limit scan area

can you help me on how to implement it on Android? I can't find out what are the cameraViewDimensions or how to implement the percentages in rectOfInterest

**Comment by shupingchu** [comment]
Is possible you could provide example for how to use `rectOfInterest` for both iOS and Android by chance? it seems like not working somehow..

**Comment by amirulasrof** [comment]
Sorry for the late reply. Here is my sample code https://gist.github.com/amirulasrof/c6b64165f63baecea2fa53061eb2b80f @shupingchu @skyrippa

**Comment by manuel3265** [comment]
How do I use it with the phone horizontally? this way it works for me with the device vertically

**Comment by manuel3265** [comment]
@amirulasrof  How do I use it with the phone horizontally? this way it works for me with the device vertically

**Comment by amirulasrof** [comment]
> @amirulasrof  How do I use it with the phone horizontally(landscape)? this way it works for me with the device vertically(portrait)

https://stackoverflow.com/questions/62472029/react-native-detect-screen-rotation-change-using-portrait-mode

You can refer solution above then update the scanArea accordingly

**Comment by manuel3265** [comment]
@amirulasrof I have tried detecting the orientation change, but it does not scan

**Comment by saadmoneylion** [comment]
@amirulasrof have you tried this

> Sorry for the late reply. Here is my sample code https://gist.github.com/amirulasrof/c6b64165f63baecea2fa53061eb2b80f @shupingchu @skyrippa

@amirulasrof have you tried this solution on Android? Is it working and limiting the scan Area? Because I am trying and it's not limiting the scanArea, I can still scan outside of my centered scan box.

**Comment by LongVT8** [comment]
@amirulasrof 
 https://gist.github.com/amirulasrof/c6b64165f63baecea2fa53061eb2b80f

 I tried this solution on Android, but it not working and limiting the scan Area. Please check code .
