### ISSUE TITLE
App crash when using tack picture on Samsung Galaxy A7 device

### ISSUE THREAD

**Issue by Fox-3394** [react-native-community/react-native-camera#1504]
Hi every one, I has issue. 

### Description: 
When I using device Samsung Galaxy A7 tack picture, then app crash. I call logcat. and this result:

  
![screen shot 2018-04-20 at 5 16 15 pm](https://user-images.githubusercontent.com/25562336/39046453-75587da2-44c0-11e8-8993-f1f28eaa82a6.png)
And file full log: 
[log-cat.txt](https://github.com/react-native-community/react-native-camera/files/1931749/log-cat.txt)

### Expected behaviour
Get uri image

### Actual behaviour
App crash

### Environment
- **React Native platform + platform version**: Android 7.0 - Samsung Galaxy A7 - Version 8.1

### react-native-camera
**Version**: v1.10

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by krystianpach** [comment]
Same on Samsung Galaxy s5 neo

**Comment by mykelaballe** [comment]
is this fixed? i'm also experiencing it in samsung 4.2.2
