### ISSUE TITLE
takePictureAsync not work properly on ios and crashed on Android due to Out of Memory

### ISSUE THREAD

**Issue by Deno028** [react-native-community/react-native-camera#1507]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?
=> RNCamera

### Steps to reproduce
```
var options = 	{ width: 1920, fixOrientation: true,quality:0.5 ,base64: true}
const data = await this.camera.takePictureAsync(options);
console.log(data);

```
1. run takePictureAsync({ width: 1920, fixOrientation: true,quality:0.5 ,base64: true}) => get raw image from iPhone camera.
2. run takePictureAsync(options) function on android => crashed 
3.

### Does it work with Expo Camera?
I dont use expo

### Expected behaviour
Tell us what should happen
Should return object with the input options 

### Actual behaviour
Tell us what happens instead
- ios: return raw images not compressed
- android: crashed 

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 7.3.0
  Yarn: 1.3.2
  npm: 5.7.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.2 AI-145.3360264

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

ios: iphone 6s - ios 11.3
android: Asus zenphone - android 4.4.2

### react-native-camera
**Version**: npm version or "master"
1.0.1

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Logcat:**

E/dalvikvm-heap(19948): Out of memory on a 50331664-byte allocation.
E/AndroidRuntime(19948): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(19948): Process: come.example.debug, PID: 19948
E/AndroidRuntime(19948): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(19948): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(19948): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(19948): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(19948): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(19948): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(19948): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(19948): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(19948): 	at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime(19948): Caused by: java.lang.OutOfMemoryError
E/AndroidRuntime(19948): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime(19948): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
E/AndroidRuntime(19948): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
E/AndroidRuntime(19948): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
E/AndroidRuntime(19948): 	at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.rotateBitmap(ResolveTakenPictureAsyncTask.java:137)
E/AndroidRuntime(19948): 	at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:73)
E/AndroidRuntime(19948): 	at org.reactnative.camera.tasks.ResolveTakenPictureAsyncTask.doInBackground(ResolveTakenPictureAsyncTask.java:26)
E/AndroidRuntime(19948): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(19948): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(19948): 	... 4 more
E/IMGSRV  (  187): :0: PVRDRMOpen: TP3, ret = 77
E/IMGSRV  (  187): :0: PVRDRMOpen: TP3, ret = 36
E/GooglePlayServicesUtil(  763): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
E/IMGSRV  (  187): :0: PVRDRMOpen: TP3, ret = 51
E/IMGSRV  (  187): :0: PVRDRMOpen: TP3, ret = 49
E/IMGSRV  (  187): :0: PVRDRMOpen: TP3, ret = 55
E/IMGSRV  (  187): :0: PVRDRMOpen: TP3, ret = 53
E/Sensors (  535): HAL:write fd 270 returned 'Invalid argument' (22)
E/Sensors (  535): HAL:ACCEL update delay error
E/dalvikvm-heap(19948): Out of memory on a 50331664-byte allocation.
E/AndroidRuntime(19948): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(19948): Process: come.example.debug, PID: 19948
E/AndroidRuntime(19948): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(19948): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(19948): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(19948): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(19948): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(19948): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(19948): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(19948): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(19948): 	at java.lang.TE/GooglePlayServicesUtil(18593): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

**Comment by jgfidelis** [comment]
Probably a problem with old android phones with less RAM, you could try a smaller width for android?

**Comment by jpudysz** [comment]
Try smaller width and quality also clean (refactor) your build.gradle file. With all that settings we were able to take pictures on every Android.

**Comment by Deno028** [comment]
Problem solved after update to 1.1.0

**Comment by YouCii** [comment]
I lowered the width and solved the problem.

**Comment by mschmuckler** [comment]
@YouCii Did you manage to find the maximum width that works on all androids? Or quality? Or combination of width/quality?

**Comment by YouCii** [comment]
@mschmuckler I think it's basically impossible to find a stable configuration that works for all android. Maybe we can determine the current device's memory size to dynamically initialize these configurations.

**Comment by Samykills** [comment]
ok so i think i found a solution, you gotta mention exif here like this : 
this.camera.takePictureAsync({ quality: 0.2, exif: false, base64: false })

**Comment by mschmuckler** [comment]
@Samykills { exif: false, base64: false } are the defaults according to [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md).

Is quality: 0.2 good enough? That sounds incredibly low, as if the picture would be fuzzy. Also, if you don't specify a width, it seems you'd still be taking large pics (1200x + or something) with low quality.

**Comment by Samykills** [comment]
@mschmuckler  yeah true these are defaults, but if i do not specify explicitly then this method is failing, not sure on the cause though.

And m keeping the quality low for my usecase as i need the same image blurred so it does'nt matter, hence a low sized file, have to provide a specific width here. thanks for the tip :D

**Comment by csae0** [comment]
Add this to your manifest in the application tag:
android:hardwareAccelerated="true"
android:largeHeap="true"

worked for me

**Comment by felansu** [comment]
@csae0 i go to test your solution

**Comment by felansu** [comment]
work for my :D
