### ISSUE TITLE
Stop preview in RNCamera

### ISSUE THREAD

**Issue by Shauneoo** [react-native-community/react-native-camera#1509]
### Which implementation are you using
RNCamera

### Expected behaviour
this.camera.stopPreview() to stop preview screen

### Actual behaviour
this.camera.stopPreview() not a function in the latest RNCamera. Is there a work around of this? I have several instances of RNCamera in my app and trying to reduce app impact on performance.

### Environment
- **Node.js version**: v8.5.0
- **React Native version**:  "0.52.0",
- **React Native platform + platform version**: iOS 11.3

### react-native-camera
**Version**: "master"

**Comment by jgfidelis** [comment]
You can test this pr: #1442

**Comment by Shauneoo** [comment]
@jgfidelis thanks for the, will do. Forgive me but how do I get the specific link to that pull request? 'https://github.com/react-native-community/react-native-camera/pull/1442' doesn't seem to work.

**Comment by mstange22** [comment]
Not sure if this is the same issue, but I'm looking at implementing a camera (front-facing) in our app to record facial emotions, but I don't want to display the preview.  Is there a way to disable the display to save real estate and resources (working in Android)?

**Comment by YouCii** [comment]
My android app runs very slowly while navigating back from a camera screen.
So i need to stop preview before navigation.

**Comment by AnurajDev** [comment]
Are there any specific reasons why "stopPreview()" is not implemented in RNCamera? I have the same problem @YouCii  has.

**Comment by n1ru4l** [comment]
Despite the fact that you can simple unmount the camera component when you navigate away from a screen (e.g. react-navigation https://reactnavigation.org/docs/en/with-navigation-focus.html), there is a `pausePreview` method: https://github.com/react-native-community/react-native-camera/blob/808fbb1be06b4f19f7653246ebb6ffdc35e9315e/src/RNCamera.js#L454

@AnurajDev Is there anything not working with that method?

**Comment by n1ru4l** [comment]
Do a conditional render and return null instead of the RNCamera in case the property injected by WithNavigationFocus is false

**Comment by AnurajDev** [comment]
@n1ru4l  Thanks a lot for the replies. 

My problem was my device time and computer time were out of sync. After they were synced, navigation is happening much faster. 

Thanks again. :)
