### ISSUE TITLE
Use Google Mobile Vision to scan barcode to improve.

### ISSUE THREAD

**Issue by ducpt2** [react-native-community/react-native-camera#1512]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
 Use RNCamera scan barcode (blur or not enough sharpen image barcode) slower than use Google Barcode Vision (i test on both android and ios).

### Expected behaviour
 Faster detect barcode.

### Actual behaviour
Slower (or CAN'T detect withblur or not enough sharpen image barcode )

### Environment
- **React Native version**: 0.53.3
- **React Native platform + platform version**: iOS 10.0, Android 6.0, etc

### react-native-camera
git+https://git@github.com/react-native-community/react-native-camera

**Comment by jgfidelis** [comment]
So, are you saying that using GMV somewhere else it detects barcodes faster than the GMV in the RNCamera?

**Comment by ducpt2** [comment]
@jgfidelis you mean RNCamera current using GMV to detects barcodes? 
i'm using => https://github.com/ekreutz/react-native-barcode-scanner-google for android 
 and => https://github.com/googlesamples/ios-vision for test ios.
Both of them detect faster (or RNCamera can not detect blur barcode) than using RNCamera example => https://github.com/react-native-community/rncamera-example.
@jgfidelis Maybe i miss the new version of RNCamera? Please help. Thanks.

**Comment by jgfidelis** [comment]
I get what you mean now.

How much faster, do you have any time comparison just from looking?

**Comment by ducpt2** [comment]
@jgfidelis if you notice, i have said CAN NOT detect blur barcode (barcode image has a poor quality). If you want, i can send you my image of barcode for testing?

**Comment by danielsantiago** [comment]
I also had notice that GMV is much faster detecting barcodes also I'm able to scan all these bar codes with GMV: https://github.com/bees4honey/mobile_vin_scanner/tree/master/VIN%20Examples. But have problem scanning these two with RNCamera:

https://github.com/bees4honey/mobile_vin_scanner/blob/master/VIN%20Examples/7.JPG
https://github.com/bees4honey/mobile_vin_scanner/blob/master/VIN%20Examples/5.JPG

**Comment by sibelius** [comment]
We have GMV for barcode scanning as well on RNCamera

check the code here https://github.com/react-native-community/react-native-camera/blob/master/src/RNCamera.js#L82

reopen if it is not working well

**Comment by danielsantiago** [comment]
@sibelius but RNCamera already support GMV barcode in iOS too?

**Comment by sibelius** [comment]
we gonna accept a pr to implement this on iOS side

**Comment by sibelius** [comment]
@dov11 made a PR to use MLKit for this https://github.com/react-native-community/react-native-camera/pull/2209
