### ISSUE TITLE
RNCamera takePictureAsync not trigger when reload

### ISSUE THREAD

**Issue by top24056** [react-native-community/react-native-camera#1515]
### Which implementation are you using

*RNCamera*

Here's my code
```
takePicture = async function(){
        if(this.camera){
            const options = {
                quality : 1,
                width : 1000,
                height : 1000,
                fixOrientation : true,
                base64 : true
            };
            console.log('ready')
            const data = await this.camera.takePictureAsync(options);
            this.props.ImageAction(data);

            
            this.props.navigation.navigate("Modal");
            
            // console.log("store image = ",this.props.image.image_food)
        }
    }
```
### Steps to reproduce
1. When I edited code react native hot reload will reload app
2. takePicture will not trigger 
3. I have to rebuilt my app 

What happened?? I don't want to rebuilt my app every time I edited my code in takePicture() 
What can I do??

### Environment
- **Node.js version**: v8.9.4
- **React Native version**: react-native-cli: 2.0.1
- **React Native platform + platform version**: Android 8.0, etc

**Comment by jgfidelis** [comment]
I think this is more of React-Native bug than RNCamera's...

**Comment by jgfidelis** [comment]
Is the method not being called or `this.camera` is being set to null and when the `takePicture` is called it does not enter the if?

**Comment by leandro-a-silva** [comment]
I also have the same problem here.

**Comment by ayushmankd** [comment]
Same issue with me!

**Comment by amitkumarsingh1991** [comment]
Hey @ayushmankd , what permissions u added in manifest file , please get back to me

**Comment by ayushmankd** [comment]
Camera Permissions, Read and Write Permissions
