### ISSUE TITLE
#react-native camera in windows UWP

### ISSUE THREAD

**Issue by hoangtuandinh77** [react-native-community/react-native-camera#1520]
hello, I see your commit about R-N windows camera, can u show me the example for use it, tks so much!!

**Comment by sibelius** [comment]
the pr is here https://github.com/react-native-community/react-native-camera/pull/862

it is staled, we need somebody to update it and improve docs

**Comment by surajGoverdhanam** [comment]
I tried and getting Undefined at 'Aspect' property. Can you give me a soultion on this?
This is working for iOS and Android.
