### ISSUE TITLE
Error when attempting to import the camera

### ISSUE THREAD

**Issue by TravJav** [react-native-community/react-native-camera#1525]
### Which implementation are you using

react-native-camera: "^1.1.2"

### Steps to reproduce
1. create react native app using cli on Mac 
2. install the react-native-camera through npm
3. launch expo 
4. error will be outputted ( see error message below )

### Does it work with Expo Camera?
App crashes and never has the opportunity to show a frame, greeted immediately with the red screen with the defined error below.

### Expected behaviour
To launch the application and be able to take the photo or use as per intended.

### Actual behaviour
To confirm; when creating or using another app there are no issues. The issues are apparent as soon as the react-native-camera is installed via. npm which leads to this error present on the phone while using the Expo app:
 

The development server returned response 500 URL: MY_IP node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=%2FUsers/user%2FnodeProject%2/myProjectName%2node_modules%2Fexpo%2Ftools%2FhashAssetFiles

Body{'originModulePath":"/Users/users/Project/myProject/node_modules/react-native-scripts/build/bin/crna-entry.js 

***** >> This is the bulk of the error, repeats after this on the physical device screen when using Expo as mentioned. I'm a little stumped why this is occurring although I expected the task to be tricky since we're using the camera it's not giving me much to go on other than the  " crna-entry.js" 

### Environment
-  node: v9.2.1
-  r.n: v 0.54.4
- npm: v 6.0.0
- Android 6.0 ( n/a have tested with ios, same result)

### react-native-camera
react-native-camera: "^1.1.2"

**Comment by jgfidelis** [comment]
If you are using Expo, you need to use their SDK's camera
