### ISSUE TITLE
I am getting error while compiling on ios in #import "RNCameraUtils.h"

### ISSUE THREAD

**Issue by kishanj918** [react-native-community/react-native-camera#1531]
versions are as below  
 "react": "16.3.1",
    "react-native": "0.53.3",
    "react-native-camera": "^1.0.2",

![screen shot 2018-05-01 at 5 47 16 pm](https://user-images.githubusercontent.com/3994657/39475005-142da45a-4d74-11e8-939b-5034dc59c4a7.png)

**Comment by jgfidelis** [comment]
What is your XCode version? We had an issue about this. Use Xcode 9 or greater.

**Comment by jgfidelis** [comment]
https://github.com/react-native-community/react-native-camera/issues/1231
