### ISSUE TITLE
How to use 'onGoogleVisionBarcodesDetected' on iOS

### ISSUE THREAD

**Issue by phuhk** [react-native-community/react-native-camera#1534]
Hi there, I'm face on problems about scan QR code on iOS.
I'm using default props for RNCamera to scan QR code (not define specific barcodeTypes, just implement 'onBarCodeRead' function to scan all barcodeTypes).

In Android is work well, but on iOS I have crash on this function:
`- (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputMetadataObjects:(NSArray *)metadataObjects
       fromConnection:(AVCaptureConnection *)connection`

metadataObjects stringValue is null.
I know Android is using Google Mobile Vision (GMV) to scan QR code, i see props 'onGoogleVisionBarcodesDetected', I want to ask how can I use GMV to scan QR code? 

Addition information: I tested normal QR code is work already, but my project is require for scan some encode Qr code string

**Comment by sibelius** [comment]
this was only implemented on Android side, we would accept a PR to add this feature on iOS

**Comment by phuhk** [comment]
I must code native iOS using `ZXing` lib to resolve this case. Any one need help can pm me.

**Comment by brayanL** [comment]
Really the BarCode functionality is not available for IOS..? you have any alternative..? :(

**Comment by brayanL** [comment]
Really the BarCode functionality is not available for IOS..? you have any alternative..? :(

**Comment by sibelius** [comment]
try using `onBarCodeRead` instead

**Comment by brayanL** [comment]
Thank you very much @sibelius your last answer was a few confusion, but i understand that Google Vision for BarCode is only available for android, but IOS BarCode Scan works but without him.

**Comment by sibelius** [comment]
can we close this?

**Comment by brayanL** [comment]
onGoogleVisionBarcodesDetected is not available for IOS yet?

**Comment by minhdang-idev** [comment]
This feature is really important. And why is it only implemented on android?

**Comment by sibelius** [comment]
check latest version

**Comment by erkutr-prog** [comment]
Is this feature still available only for android?
