### ISSUE TITLE
The captured image is wrong orientation and take a long time for capturing

### ISSUE THREAD

**Issue by ducgao** [react-native-community/react-native-camera#1540]
I'm using react-native-camera to implement snap feature. The screen I developed is fixed orientation so when I capture a image, the output is not rotate follow the right direction and the capturing process is take a long time.

I think react-native-camera need to use sensor manager to get the right orientation of device when capture instead of listen to orientation changed event.

The skipProcessing option didn't help a lot. The capture process still take a time to be done.
:(

**Comment by jgfidelis** [comment]
Android still needs a lot of work. We need people to send PRs with these improvements.

**Comment by Asalem1** [comment]
Have there been any developments on this @ducgao ?

**Comment by ducgao** [comment]
I folked the repo and did it myself. if you feel interest, please visit my repo
