### ISSUE TITLE
A problem occurred evaluating project ':react-native-camera'.

### ISSUE THREAD

**Issue by 841660202** [react-native-community/react-native-camera#1543]
Build file '/Users/work/logistics_app/node_modules/_react-native-camera@1.1.2@react-native-camera/android/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-camera'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by yezidd** [comment]
solve problem now?

**Comment by yezidd** [comment]
+1

**Comment by jgfidelis** [comment]
Try fixes suggested in this thread:
https://github.com/react-native-community/react-native-svg/issues/584

**Comment by gvaladao** [comment]
I have the same problem:

A problem occurred evaluating project ':react-native-camera'.
> Could not find method google() for arguments [] on repository container.


Can you give-me a hint please?

Thank you

**Comment by sibelius** [comment]
here is the hint react-native-community/react-native-svg#584

**Comment by gvaladao** [comment]
Thank you
