### ISSUE TITLE
Error: recordAsync: Expected a Camera component

### ISSUE THREAD

**Issue by alexvaltin97** [react-native-community/react-native-camera#1544]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Gradle 3
This package required Gradle 3, follow this migration guide https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration

### Which implementation are you using

RNCamera

### Steps to reproduce
1. Implement RNCamera.recordAsync on the RNCameraExample
2. Set a maxDuration
3. Run the example and try recording a video

### Does it work with Expo Camera?
Not using Expo Camera

### Expected behaviour
Recording a Video

### Actual behaviour
Error:

Possible Unhandled Promise Rejection (id: 0):
Error: recordAsync: Expected a Camera component
Error: recordAsync: Expected a Camera component
    at createErrorFromErrorData (blob:http://localhost:8081/3205bd02-f1b9-4e27-80fc-04c327a17673:2039:17)
    at blob:http://localhost:8081/3205bd02-f1b9-4e27-80fc-04c327a17673:1991:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/3205bd02-f1b9-4e27-80fc-04c327a17673:2433:18)
    at blob:http://localhost:8081/3205bd02-f1b9-4e27-80fc-04c327a17673:2178:18
    at MessageQueue.__guardSafe (blob:http://localhost:8081/3205bd02-f1b9-4e27-80fc-04c327a17673:2346:11)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/3205bd02-f1b9-4e27-80fc-04c327a17673:2177:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:70:58

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by jgfidelis** [comment]
Device or emulator?

**Comment by alexvaltin97** [comment]
Both. The issue is only using the maxDuration. Otherwise it works fine

**Comment by tuomohopia** [comment]
I'm running into the same issue regardless of whether the maxDuration is set or not.
