### ISSUE TITLE
undefinde is not an object error after it's been linked

### ISSUE THREAD

**Issue by Voyager-One** [react-native-community/react-native-camera#1545]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our migration guide here https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md

### Gradle 3
This package required Gradle 3, follow this migration guide https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration

### Which implementation are you using
**RNCamera**
### Steps to reproduce
1. `yarn add react-native-camera`, `react-native link react-native-camera`
![snip20180507_1](https://user-images.githubusercontent.com/23122353/39694718-dbf2e87e-521a-11e8-9a90-786342d73b4f.png)
2. just import the RNCamera 
`import { RNCamera } from 'react-native-camera'`
![snip20180507_2](https://user-images.githubusercontent.com/23122353/39694752-f3e057e6-521a-11e8-8318-4a1aaad0b427.png)
So I think it is not actually linked
3. in xcode
![snip20180507_3](https://user-images.githubusercontent.com/23122353/39694771-fe6bb8e0-521a-11e8-9bc6-a2c3cb8fd12d.png)
![snip20180507_5](https://user-images.githubusercontent.com/23122353/39694783-06545026-521b-11e8-8b8e-edfff386a993.png)
### Does it work with Expo Camera?
expo camera works fine
### Expected behavior
successfully imported
### Actual behaviour
it looks like that it is not actually linked with the project. but the `react-native link` did give success message.
### Environment
- **Node.js version**: 10.0.0
- **React Native version**: 0.55.2
- **React Native platform + platform version**: iOS 11.3
### react-native-camera
**Version**: 1.1.2
> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by jgfidelis** [comment]
I don't know what went wrong but that is a classical wrong link error...

**Comment by jgfidelis** [comment]
Try doing the manual link

**Comment by alopes** [comment]
I'm getting the same exact issue on a new project.

**Comment by Voyager-One** [comment]
hey guys, I think I finally figure it out. if you are using expo (`create-react-native-app`) and want to use rn libs that needs to run `react-native link`, you must eject the expo project........

**Comment by Mickamwamba** [comment]
Same issue here.. I am using 
react-native-cli: 2.0.1
react-native: 0.55.3
macOS Sierra v 10.12.6

**Comment by JindiHu** [comment]
@Mickamwamba i thought this error happens in IOS. I dont think it related to android gradle. 
by the way, i also have the same problem with ios linking.

**Comment by sibelius** [comment]
the link is wrong
