### ISSUE TITLE
FaCC Feature breaks backwards compatibility

### ISSUE THREAD

**Issue by delta98** [react-native-community/react-native-camera#1553]
### Which implementation are you using

*RNCamera*

Given an example of the child implementation before FaCC
```
<RNCamera><View><Text>Child View</Text></View></RNCamera>
```

### Expected behaviour
The latest version of React Native Camera should be backwards compatible 

### Actual behaviour

`renderChildren` returns null if `hasFaCC` isn't provided, breaking backwards compatibility which was the original intention on the issue and PR for the feature.

Instead of returning `null` I believe it would be better to return `this.props.children` if a function isn't provided.

**Comment by delta98** [comment]
@AndreiCalazans PR here #1554

**Comment by AndreiCalazans** [comment]
Awesome @delta98  thank you very much!
