### ISSUE TITLE
taking photos in landscape mode is rotating the photo 90º (turning to portrait)

### ISSUE THREAD

**Issue by imspikey** [react-native-community/react-native-camera#1570]
### Which implementation are you using
*RNCamera* 

### Steps to reproduce
1. Take a picture in landscape mode

3.

### Expected behaviour
Image should  look like its in landscape 
![whatsapp image 2018-05-18 at 16 22 27](https://user-images.githubusercontent.com/1473944/40237138-35521750-5ab8-11e8-857c-dde946159e8a.jpeg)

### Actual behaviour
image looks cropped and in portrait 
![whatsapp image 2018-05-18 at 16 22 28](https://user-images.githubusercontent.com/1473944/40237190-5d6ba850-5ab8-11e8-8446-2cbaf9c0033e.jpeg)

### Environment
- **Node.js version:9.7.1
- **React Native version:0.53.3
- **React Native platform + platform version**: iOS 11.3.1

### react-native-camera
**Version**: 1.1.2

**Comment by jgfidelis** [comment]
can you try `forceUpOrientation: true` option?

**Comment by imspikey** [comment]
I have tried with no success

**Comment by JoseVf** [comment]
In my case it happens when rotation mode is enabled on phone's configuration, but when it's disabled image will keep it's orientation.

**Comment by imspikey** [comment]
But rotation is disabled in my case. Also video recording dose not have this problem only image capture

**Comment by aditya-rumbleon** [comment]
I have the same issue.

**Comment by aditya-rumbleon** [comment]
forceUpOrientation: true does not work for me. Any suggestions?

**Comment by almost** [comment]
I added an "orientation" option to takePhotoAsync, the PR just got merged. So you can pass in the orientation you want.

For me the problem was that the orientation lock was turned on on the phone which made it think it was always portrait even when a modal that forced to landscape (as I use for the photo view finder screen) was in view.

**Comment by imspikey** [comment]
@almost   Thank you my issue has bean solved after setting orientation to portrait 👍

**Comment by sibelius** [comment]
@imspikey can you send a PR to add this to the docs

**Comment by mun3** [comment]
Can I ask how the `orientation` option should be used? I've tried setting it to `3`, but my `CameraManager.Orientation` is undefined. My `CameraManager` is `NativeModules.RNCameraModule`. Does another manager need to be used instead?

**Comment by imspikey** [comment]
sibelius ok 👍

**Comment by imspikey** [comment]
mun3 her is my code

takePicture = async function() {
        if (this.camera) {

            const options = {orientation:'portrait',forceUpOrientation: true, mirrorImage:(fix this part as appropriatef)this.type == RNCamera.Constants.Type.front ,  quality: 0.20, base64: true };
            const data = await this.camera.takePictureAsync(options)
            return data
        }
    };

**Comment by mun3** [comment]
@imspikey Thanks

I believe that's the fix for iOS, but the same issue arises in Android.

**Comment by almost** [comment]
My patch adding the orientation prop was ios only. I intend to do the same
for android when i have time. Unless someone else beats me to it :)

I would also be good to fix the auto orientation to match the orientation
used by the preview.

**Comment by anztrax** [comment]
in index.ts, there're  options that support the orientation :
```
  /** Android only */
    skipProcessing?: boolean;
    fixOrientation?: boolean;

    /** iOS only */
    forceUpOrientation?: boolean; 
```

you can use when using them for example (in android) : 
```
 const takeCameraOptions = {
        quality : 0.5,  //just in case want to reduce the quality too
        skipProcessing: false,
        fixOrientation: true
      };
      this.camera.takePictureAsync(takeCameraOptions).then(data => .... ).catch(err => ...)
```

**Comment by meiqi1992** [comment]
> Can I ask how the `orientation` option should be used? I've tried setting it to `3`, but my `CameraManager.Orientation` is undefined. My `CameraManager` is `NativeModules.RNCameraModule`. Does another manager need to be used instead? I'm having this same problem on Android.

same problem! how to resovle?

**Comment by sibelius** [comment]
recheck on 1.6.3

**Comment by HauLuu** [comment]
I have the same issue. Any fix so far?

`      const options = {
        base64: true,
        fixOrientation: true,
        pauseAfterCapture: true,
      };

      const data = await this.camera.takePictureAsync(options);`

**Comment by sergchernata** [comment]
Experiencing this issue on iOS. App and camera are both set to `landscapeLeft`. Works as it should on Android, but on iOS the image taken is flipped 180 degrees.

iOS works as it should only if set to the opposite - `landscapeRight`.

```
"react-native": "^0.60.3",
"react-native-camera": "^3.9.0",
```

**Comment by amcm23** [comment]
> I have the same issue with Samsung Galaxy S9. Any fix so far?
> 
> ```
> const options = {
>         base64: true,
>         fixOrientation: true,
>         pauseAfterCapture: true,
>       };
> 
> const data = await this.camera.takePictureAsync(options);
> ```

I fixed it with ` const options = { quality: 1, base64: true, pauseAfterCapture: true, orientation:'auto',fixOrientation: true};`

**Comment by fabriciosautner** [comment]
Thank you @sergchernata ,

Incredibly, the orientation problem in landscape mode is solved by inverting the "orientation" option in takePictureAsync.

That is, where landscapeRight is to place landscapeLeft and vice versa.
