### ISSUE TITLE
Does the component have no control over the onBarCodeRead callback interval attribute?

### ISSUE THREAD

**Issue by giantss** [react-native-community/react-native-camera#1575]
## status quo
When I use this component to scan the QR code, the `onBarCodeRead` callback frequency is very high, basically every one millisecond.
I try to use the following code to control the program not to repeat the second pass, but performed two or three times at the same time (milliseconds).
```
...
  constructor(props){
        super(props);
        this.isBarCodeRead = false; //here
}
...

    _barcodeReceived = (e) => {
        if(e.data){
            if(!this.isBarCodeRead){
                console.log('this.isBarCodeRead',this.isBarCodeRead);
                this.isBarCodeRead = true;
                //Need to execute code
                setTimeout(()=>{
                    this.isBarCodeRead = false;
                }, 5000);
            }


        }
    };


```
![image](https://user-images.githubusercontent.com/13778798/40305709-3d199530-5d2e-11e8-9813-76808ffe596c.png)

![image](https://user-images.githubusercontent.com/13778798/40306028-a46dc8ea-5d2f-11e8-8e16-24b26bc2b67e.png)
![image](https://user-images.githubusercontent.com/13778798/40306048-bc4ed5c6-5d2f-11e8-88d7-ea56292eb862.png)
![image](https://user-images.githubusercontent.com/13778798/40306126-fe3ae182-5d2f-11e8-8a40-b8c91bc74f0b.png)

Isn't this a bug?
[#419](https://github.com/react-native-community/react-native-camera/issues/419)

**Comment by bachlongkocanh** [comment]
`  i = 0;
    onBarCodeRead = (scanResult) => {
        this.i++
        if (this.i == 0) {
            if (scanResult.data != null) {
                this.setState({ ResultScan: scanResult.data })
                this.props.navigation.state.params.onSelect({ result: scanResult.data });
                this.props.navigation.goBack();
            }
        }
        return;
    }`
resolve for me.

**Comment by n1ru4l** [comment]
We should definitely have some way to disable `onBarCodeRead` calls. This could block the react-router bridge and could result in bad performance

**Comment by panda6412** [comment]
any resolution here ?
