### ISSUE TITLE
Gradle DSL method not found: 'google()'

### ISSUE THREAD

**Issue by danchokobo** [react-native-community/react-native-camera#1577]
Hi,
I can not update build gradle version, cause it should be lower than 2.7
But android require update, beacuse it needs buildToolVersion 25+, whereas  my buildToolsVersion is 23, in order to update buildverions android asks me update gradle, that's a big trouble.
Can you provide another version of module ?

`Gradle DSL method not found: 'google()'
Possible causes:<ul><li>The project 'android' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
Upgrade plugin to version 3.1.0 and sync project</li><li>The project 'android' may be using a version of Gradle that does not contain the method.
Open Gradle wrapper file</li><li>The build file may be missing a Gradle plugin.
Apply Gradle plugin</li>
`

**Comment by sibelius** [comment]
upgrade to gradle 3

read issue template as well

https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md

**Comment by danchokobo** [comment]
@sibelius can I just install older version of react-native-camera?

**Comment by danchokobo** [comment]
@sibelius can I just install older version of module?

**Comment by sibelius** [comment]
you can, but it is up to you

**Comment by wynch** [comment]
This is not Gradle 3 but Gradle 4.4, with plugin 3.1.0.... 

One thing to have in mind : ReactNative - today in version 0.56.0 - is still not compatible with Gradle 4+. They just bumped their version from gradle 2 to 3

 It might work with your lib, react-native-camera, but it will fail with others (like react-navigation).
So enforcing Gradle 4 is a real deal-breaker for me...
