### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSString

### ISSUE THREAD

**Issue by edisonlao** [react-native-community/react-native-camera#1582]
"react": "16.3.1",
"react-native": "0.55.1",
"react-native-camera": "^1.1.2",

when I use import RNCamera from 'react-native-camera';

## **Android**  
normal operation

## **IOS**  
collapse with error:  

**JSON value '<'null'>' of type NSNull cannot be converted to NSString**

**+[RCTConvert NSString:]**
**RCTConvert.m:56**

**Comment by n1ru4l** [comment]
@edisonlao Could you please explain under which circumstances this error occurs?

Could you please also try if this issue occurs with the newest version published to npm and/or the master branch?
