### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by vitensun** [react-native-community/react-native-camera#1583]
Build file 'C:\Users\Catme\Desktop\test\node_modules\react-native-camera\android\build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-camera'.
> Could not find method google() for arguments [] on repository container.

**Comment by grsmvg** [comment]
https://github.com/react-native-community/react-native-camera/issues/1577

**Comment by vitensun** [comment]
Thx. I already updated to gradle 3. All issues are fixed.
