### ISSUE TITLE
Modify exif of picture taken

### ISSUE THREAD

**Issue by Dror-Bar** [react-native-community/react-native-camera#1587]
I know it is possible to read the exif of the picture taken, however, is it also possible to modify the exif with this library? Can I add metadata such as datetime, author, etc?

**Comment by sibelius** [comment]
@Dror-Bar not possible yet

not sure if this should be in this library

**Comment by Dror-Bar** [comment]
I see, thank you for the quick answer. This would definitely be nice to have, I suppose I shall look for this functionality elsewhere in the meantime.
Regardless, I appreciate all the work you guys did with this library, it's very useful.

**Comment by sibelius** [comment]
let's us know if you implement it 

we can add to this library or to the docs

**Comment by Dror-Bar** [comment]
If anyone is curious, I ended up editing the exif using [piexifjs](https://github.com/hMatoba/piexifjs) library.
