### ISSUE TITLE
Build error -  Could not find repository.jar, protos.jar and builder-test-api.jar

### ISSUE THREAD

**Issue by Fsarmento** [react-native-community/react-native-camera#1589]
### Which implementation are you using

*RNCamera*

### Steps to reproduce
1. Install react-native-camera as described in [react-native-camera](https://github.com/react-native-community/react-native-camera)
2. On android/app/build.gradle, instead of compile `('com.google.android.gms:play-services-vision:12.0.1'`, update to  `implementation ('com.google.android.gms:play-services-vision:15.0.2')` to make it compatible with RNFirebase (otherwise gradle will throw an error "All firebase libraries must be either above or below 14.0.0")

### Does it work with Expo Camera?
N/A

### Expected behaviour
Project should compile without errors

### Actual behaviour
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-camera'.
> Could not resolve all files for configuration ':react-native-camera:classpath'.
   > Could not find repository.jar (com.android.tools:repository:26.0.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/repository/26.0.0/repository-26.0.0.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:26.0.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/analytics-library/protos/26.0.0/protos-26.0.0.jar
   > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:3.0.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/builder-test-api/3.0.0/builder-test-api-3.0.0.jar
```

### Environment
- **Node.js version**: v8.11.1 
- **React Native version**: v0.55.3 
- **React Native platform + platform version**: Android 8.10

### react-native-camera
**Version**: 1.1.4

**Comment by enieber** [comment]
@freshlybakedcode  any solution?
