### ISSUE TITLE
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.

### ISSUE THREAD

**Issue by fauzzi** [react-native-community/react-native-camera#1597]
### Failure
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't write 
[C:\Users\projectname\android\app\build\intermediates\multi-dex\debug\componentClasses.jar] 
(Can't read [C:\Users\projectname\node_modules\react-native-camera\android\build\intermediates\intermediate-jars\debug\classes.jar(;;;;;;**.class)] 
(Duplicate zip entry [classes.jar:com/google/android/cameraview/CameraView$Facing.class]))

### Gradle 3
    classpath 'com.android.tools.build:gradle:3.0.0'
    
   compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {   
        multiDexEnabled true
    }dependencies {
    compile 'com.android.support:multidex:1.0.3'
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.0.2"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile project(':react-native-navigation')
    compile project(':react-native-spinkit')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-config')
    compile project(':react-native-image-picker')
    compile project(':react-native-geocoder')
    implementation(project(':react-native-camera')) {
        exclude group: "com.android.support"
    }
    implementation "com.android.support:exifinterface:+"
    implementation "com.android.support:support-annotations:+"
    compile("com.android.support:support-v4:26.0.1") {
        force = true
    }
}

**Comment by sturmenta** [comment]
@fauzzi  Did you try to execute `sudo react-native run-android` ?

**Comment by wladimir1982** [comment]
I had same problem, after I have connected react-native-camera library. How did you fix that?

**Comment by shrivastavaanurag** [comment]
how did you fix this. i am also having same issue

**Comment by AFMW** [comment]
How did you fixed this?
