### ISSUE TITLE
Taking full resolution photos

### ISSUE THREAD

**Issue by tume** [react-native-community/react-native-camera#160]
When taking photos iPhone 6 the photo resolution seems to be 1080x1920 which is fine but not close to resolution it could (2448x3264). 

I was going through the source code to see if there is some kind of switch for quality but only thing I could find was this line:
https://github.com/lwansbrough/react-native-camera/blob/master/ios/RCTCameraManager.m#L126

Which uses AVCaptureSessionPresetHigh preset which if I understood correctly sets highest quality for video and not for stills. Switching this to AVCaptureSessionPresetPhoto allows me to capture full resolution photos.

I was wondering whether there was some specific reason to use PresetHigh instead of PresetPhoto? and is it possible to change it somehow from js side?

**Comment by lwansbrough** [comment]
This was probably because we used to transfer data over the bridge and the full resolution would have been too slow. Would accept a PR to make this functionality possible (or perhaps even change the default)

**Comment by viscasillas** [comment]
Stupid question problably but Can I use my existing iOS code on Android?? Do I need to use android studio? 

Thanks

**Comment by pyrabbit** [comment]
I am interested in this type of enhancement and would consider working on a PR. I haven't done much with Objective-C or Swift or mobile for that matter. Is this a relatively straight forward fix or would it require a significant rehaul.

**Comment by rpopovici** [comment]
It's done just needs to be merged https://github.com/lwansbrough/react-native-camera/pull/211

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
