### ISSUE TITLE
[Android] - onBarCodeRead 

### ISSUE THREAD

**Issue by bdouram** [react-native-community/react-native-camera#1601]
Hi! 
The RN-Camera good works when **onBarCodeRead**  isn't set.

**The speed of camera is good when:**
`<RNCamera
            ref={ref => {
              this.camera = ref;
            }}
            style = {styles.preview}
            type={RNCamera.Constants.Type.back}
            flashMode={RNCamera.Constants.FlashMode.off}
            permissionDialogTitle={'Permission to use camera'}
            permissionDialogMessage={'We need your permission to use your camera phone'}
        />
`

**But this make my Android Camera slow frame:**

`<RNCamera
            ref={ref => {
              this.camera = ref;
            }}
            style = {styles.preview}
            type={RNCamera.Constants.Type.back}
            flashMode={RNCamera.Constants.FlashMode.off}
            permissionDialogTitle={'Permission to use camera'}
            permissionDialogMessage={'We need your permission to use your camera phone'}
            onBarCodeRead = {(e)=> alert(e.data)} // my camera slowing image now.....
        />`

**My package.json have this configurations:**

Android 6.1

`"dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-camera": "^1.1.4"
  }`

This is my code: https://github.com/bdouram/camera-react-native-test
Could you help me?
Thanks.

**Comment by bdouram** [comment]
I think if this issue is because of the scan area: It is the total screen size of my smartphone. Am i correct?

If yes:
How can I continue with the full size of my smartphone screen and limit only the scan area?

**Comment by zhenizhui** [comment]
@bdouram i think you can try this repository https://github.com/shifeng1993/react-native-qr-scanner.

It may help you although it still has some bug that I found.

**Comment by bdouram** [comment]
@zhenizhui you solve my problem!

Thanks!

**Comment by bdouram** [comment]
Closing the issue.
