### ISSUE TITLE
Preview image rotated by 90 degrees after 4 rotations

### ISSUE THREAD

**Issue by mun3** [react-native-community/react-native-camera#1607]
### Which implementation are you using

RNCamera

### Steps to reproduce
1. Rotate clockwise (or counter clockwise) 4 times on Android (API 25 & 26) emulator

### Expected behaviour
Preview image restores to the original orientation.

### Actual behaviour
Preview image is rotated by 90 degrees:

Original orientation:
![screen shot 2018-06-04 at 11 06 11 pm](https://user-images.githubusercontent.com/1611736/40919322-879ae23e-684c-11e8-8a9d-51d628557676.png)

Final orientation (after 4 rotations):
![screen shot 2018-06-04 at 11 06 25 pm](https://user-images.githubusercontent.com/1611736/40919293-713b650e-684c-11e8-9a99-7e7f4b7bf53d.png)

### Environment
- **React Native version**: 0.51.0
- **React Native platform + platform version**: Android 7.1.1, 8.0

### react-native-camera
**Version**: "master"

**Comment by 6pm** [comment]
It is well known behavior for nexus 5x. try to add `fixOrientation: true`.

**Comment by sibelius** [comment]
recheck on 1.6.3
