### ISSUE TITLE
Is there anybody working on RNCamera for iOS and GMV Text Recognition?

### ISSUE THREAD

**Issue by AlexandreLage** [react-native-community/react-native-camera#1610]
### Is there anybody working on RNCamera for iOS who would like to develop this bridge just like Face Recognition (which has already been developed for iOS)?
Google Mobile Vision has released their 1.3 version with Text Recognition for iOS. I was trying to bridge and wrap everything up, but I had to give up due to my due dates haha

Could some project maintainer set iOS and Wanted Help labels to this issue? There one similar question, but it's labeled as Android :'/ so maybe no iOS developer has seen it.
  
Thank you all guys for everything you are doing!

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by sibelius** [comment]
fixed here https://github.com/react-native-community/react-native-camera/pull/1775

test on master
