### ISSUE TITLE
RNCamera - QR Code Not Scanning on Samsung S7-S9

### ISSUE THREAD

**Issue by avinashwigroup** [react-native-community/react-native-camera#1611]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our [Migration guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md)

### Which implementation are you using
*RNCamera* 

### Steps to reproduce
1. Generate a QR code and print it on a paper.
2. Scan it using Samsung S7-S8-S9

### Does it work with Expo Camera?
No.  The project was created using react-native cli.

### Expected behaviour
The QR code should be scanned without delay ...like immediately.

### Actual behaviour
The camera is forcing itself to focus and  scan the QR code.  It works on the other brands of Android mobile phones but not always on samsung ones.

### Environment
- **React Native version**:   "0.48.4"
- **React Native platform + platform version**:  Android 5.0 to latest

### react-native-camera
**Version**: "^1.1.4"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by avinashwigroup** [comment]
@joelbarbosa  thanks .  what is the behaviour on other android devices if we use your fix ?

**Comment by joelbarbosa** [comment]
@avinashwigroup the camera always focuses and never lose it, so on Samsung, we always have the focus and never cancel what resolve the problem.
The application manages the focus overall.

**Comment by avinashwigroup** [comment]
Thanks @joelbarbosa .  I implemented the solution and the client is happy.  Hopefully we will get a fix soon for this issue.

**Comment by sibelius** [comment]
try on latest version

it uses MLKit
