### ISSUE TITLE
Cannot add output <AVCaptureMetadataOutput: 0x11ef05410> to capture session <AVCaptureSession: 0x122649600 [AVCaptureSessionPresetHigh]> because more than one output of the same type is unsupported

### ISSUE THREAD

**Issue by xwartz** [react-native-community/react-native-camera#1616]
### Which implementation are you using

*RNCamera*

### Crash Stacktrace
```
Fatal Exception: NSInvalidArgumentException
*** -[AVCaptureSession addOutput:] Cannot add output <AVCaptureMetadataOutput: 0x11ef05410> to capture session <AVCaptureSession: 0x122649600 [AVCaptureSessionPresetHigh]> because more than one output of the same type is unsupported
```

![image](https://user-images.githubusercontent.com/4149827/41086630-2f8d9226-6a6d-11e8-8d8b-eecc0a3c1b52.png)

### Environment
- **React Native version**:  0.51.0
- **React Native platform + platform version**: Android 5/6/7/8

### react-native-camera
**Version**: 1.1.1

**Comment by eric-fl** [comment]
+1

**Comment by rajivshah3** [comment]
+1 but slightly different stacktrace:

```
NSInvalidArgumentException *** -[AVCaptureSession addOutput:] Cannot add output <AVCaptureMetadataOutput: 0x1c4637940> to capture session <AVCaptureSession: 0x1c0201bb0 [AVCaptureSessionPresetHigh]> because more than one output of the same type is unsupported 
    Frameworks/CoreFoundation.framework/CoreFoundation ___exceptionPreprocess
    /usr/lib/libobjc.A.dylib _objc_exception_throw
    Frameworks/AVFoundation.framework/AVFoundation -[AVCaptureSession addOutput:]
    /Users/vagrant/git/src/mobile/node_modules/react-native-camera/ios/RN/RNCamera.m:669:13 -[RNCamera _setupOrDisableMetadataOutput]
    /Users/vagrant/git/src/mobile/node_modules/react-native-camera/ios/RN/RNCamera.m:659:5 -[RNCamera setupOrDisableBarcodeScanner]
    /Users/vagrant/git/src/mobile/node_modules/react-native-camera/ios/RN/RNCameraManager.m:182:5 -[RNCameraManager set_barCodeScannerEnabled:forView:withDefaultView:]
    /Users/vagrant/git/src/mobile/node_modules/react-native/React/Views/RCTComponentData.m:108:5 -[RCTComponentData callCustomSetter:onView:withProp:isShadowView:]
    /Users/vagrant/git/src/mobile/node_modules/react-native/React/Views/RCTComponentData.m:229:7 __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2
    /Users/vagrant/git/src/mobile/node_modules/react-native/React/Views/RCTComponentData.m:356:5 __37-[RCTComponentData setProps:forView:]_block_invoke
    Frameworks/CoreFoundation.framework/CoreFoundation -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
    /Users/vagrant/git/src/mobile/node_modules/react-native/React/Views/RCTComponentData.m:355:3 -[RCTComponentData setProps:forView:]
    /Users/vagrant/git/src/mobile/node_modules/react-native/React/Modules/RCTUIManager.m:971:7 __50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke
    /usr/lib/system/libdispatch.dylib __dispatch_call_block_and_release
    /usr/lib/system/libdispatch.dylib __dispatch_client_callout
    /usr/lib/system/libdispatch.dylib __dispatch_main_queue_callback_4CF$VARIANT$mp
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
    Frameworks/CoreFoundation.framework/CoreFoundation ___CFRunLoopRun
    Frameworks/CoreFoundation.framework/CoreFoundation _CFRunLoopRunSpecific
    PrivateFrameworks/GraphicsServices.framework/GraphicsServices _GSEventRunModal
    Frameworks/UIKit.framework/UIKit _UIApplicationMain
    appName/main.m:16:12 main
    /usr/lib/system/libdyld.dylib _start
```

`react-native-camera`: v1.1.4
`react-native`: v0.51.0
`react`: v16.0.0

**Comment by reganperkins** [comment]
im getting this as well but can't yet tell what is causing it

**Comment by rajivshah3** [comment]
>React Native platform + platform version: Android 5/6/7/8

@xwartz I think this is an iOS issue, `NSInvalidArgumentException` sounds like an iOS class. What iOS versions are you seeing it on?

**Comment by xwartz** [comment]
@rajivshah3  Yes, it's iOS issue, it occur on 11.1.0 - 11.3.1

**Comment by ZionChang** [comment]
+1

**Comment by MannyFM** [comment]
+1.
```
"react": "16.3.1",
"react-native": "~0.55.2",
"react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera",
```
```
2018-07-08 21:29:32.096059+0600 ReactiveMuseum[249:12251] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureSession addOutput:] Cannot add output <AVCaptureMetadataOutput: 0x1c4429920> to capture session <AVCaptureSession: 0x1c020ad80 [AVCaptureSessionPresetPhoto]> because more than one output of the same type is unsupported'
*** First throw call stack:
(0x1861ff164 0x185448528 0x18bb6fcf0 0x1051619a0 0x105161718 0x10515ef28 0x105a912cc 0x105a9128c 0x105a9ff80 0x105a947ec 0x105aa0f6c 0x105aa8020 0x185e26f1c 0x185e26b6c)
libc++abi.dylib: terminating with uncaught exception of type NSException
2018-07-08 21:40:14.830417+0600 ReactiveMuseum[249:15129] XPC connection interrupted
```

**Comment by svetoslav0625** [comment]
+1
I got this error on iOS
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-camera": "^1.1.4",

**Comment by SimonErm** [comment]
Can you test if this fix this? https://github.com/SimonErm/react-native-camera/tree/fix/multipleOutputOfSameType

**Comment by eamonwhiter73** [comment]
@SimonErm I'm just curious...im newbish with github...how would i go about testing ur fork? just uninstall react-native-camera, and then install your version branch normally with `npm install`?

**Comment by eamonwhiter73** [comment]
@SimonErm I'm just curious...im newbish with github...how would i go about testing this? just uninstall react-native-camera, and then install your fork?

**Comment by eamonwhiter73** [comment]
@dmitryn hod does the reference issue relate?

**Comment by SimonErm** [comment]
@eamonwhiter73 use "react-native-camera": "git+https://git@github.com/SimonErm/react-native-camera#multipleOutputOfSameType" instead of a version and run npm install

**Comment by eamonwhiter73** [comment]
@SimonErm thanks ill try

**Comment by eamonwhiter73** [comment]
@SimonErm I am getting `error: pathspec 'multipleOutputOfSameType' did not match any file(s) known to git.` when trying to run `npm install` and in your repo on git it says `Cannot retrieve the latest commit at this time.` Are there any commits I can retrieve?

**Comment by SimonErm** [comment]
@eamonwhiter73 oh sorry, it has to be: `"react-native-camera": "git+https://git@github.com/SimonErm/react-native-camera#fix/multipleOutputOfSameType"`

**Comment by yurnery** [comment]
@SimonErm hi, can you tell me which commit you fix this issue, I got no information from your commit list

**Comment by theohdv** [comment]
@SimonErm could you explain your fix please ? I'll try it but i'd like to know what went wrong

**Comment by AshokICreate** [comment]
```
iPhone 7 (D101AP)
Name | iOS
-- | --
Version | 11.4 (15F79)
```

```
NSInvalidArgumentException: Application threw exception NSInvalidArgumentException: *** -[AVCaptureSession addOutput:] Cannot add output <AVCaptureMetadataOutput: 0x1c042f880> to capture session <AVCaptureSession: 0x1c02078b0 [AVCaptureSessionPresetPhoto]> because more than one output of the same type is unsupported Originated at or in a subcall of GMSx_AbslInternalSpinLockWake
--
```

**Comment by n1ru4l** [comment]
@AshokICreate Can you please provide a step by step guide to reproduce this issue with the example app in this repository?

**Comment by AshokICreate** [comment]
```
- (void)_setupOrDisableMetadataOutput
{
    if ([self isReadingBarCodes] && (_metadataOutput == nil || ![self.session.outputs containsObject:_metadataOutput])) {
        AVCaptureMetadataOutput *metadataOutput = [[AVCaptureMetadataOutput alloc] init];
        if ([self.session canAddOutput:metadataOutput]) {
            NSLog(@"Stack trace : %@",[NSThread callStackSymbols]);
            [metadataOutput setMetadataObjectsDelegate:self queue:self.sessionQueue];
            @try {
                [self.session addOutput:metadataOutput];
            }
            @catch (NSException *exception) {
                NSLog(@"ashok the exception is %@", exception);
                NSLog( @"ashok Name: %@", exception.name);
                NSLog( @"ashok Reason: %@", exception.reason);
            }
            @finally {
                NSLog(@"Finally condition");
            }
            [self.session addOutput:metadataOutput];
            self.metadataOutput = metadataOutput;
        }
    } else if (_metadataOutput != nil && ![self isReadingBarCodes]) {
        [self.session removeOutput:_metadataOutput];
        _metadataOutput = nil;
    }
}
```

**Comment by AshokICreate** [comment]
I changed to below code.

`- (void)_setupOrDisableMetadataOutput
{
    if ([self isReadingBarCodes] && (_metadataOutput == nil || ![self.session.outputs containsObject:_metadataOutput])) {
        AVCaptureMetadataOutput *metadataOutput = [[AVCaptureMetadataOutput alloc] init];
        if ([self.session canAddOutput:metadataOutput]) {
            @try {
                if(![self.session.outputs containsObject:metadataOutput]) {
                    if(_metadataOutput != nil && [self.session.outputs containsObject:_metadataOutput]) {
                        [self.session removeOutput:metadataOutput];
                    } else {
                        [metadataOutput setMetadataObjectsDelegate:self queue:self.sessionQueue];
                        [self.session addOutput:metadataOutput];
                        self.metadataOutput = metadataOutput;
                    }
                    
                }
            }
            @catch (NSException *exception) {
                NSLog(@"exception is %@", exception);
            }
        }
    } else if (_metadataOutput != nil && ![self isReadingBarCodes]) {
        [self.session removeOutput:_metadataOutput];
        _metadataOutput = nil;
    }
}`

but below code is getting executed twice by some thread
```
 [metadataOutput setMetadataObjectsDelegate:self queue:self.sessionQueue];
                        [self.session addOutput:metadataOutput];
                        self.metadataOutput = metadataOutput;
```

is this because of 
```
dispatch_async(self.sessionQueue, ^{
//some code
})
```

**Comment by AshokICreate** [comment]
https://github.com/n1ru4l anything u can help?

**Comment by AshokICreate** [comment]
> @AshokICreate Can you please provide a step by step guide to reproduce this issue with the example app in this repository?

@n1ru4l please find above comments

**Comment by 7772** [comment]
Is there any update here?
