### ISSUE TITLE
Add timestamp to image captures in simulator

### ISSUE THREAD

**Issue by sharathprabhal** [react-native-community/react-native-camera#162]
Currently, image capture in the simulator is a plain white image. It will be helpful if the images had a timestamp to figure out if new captures were successful.

**Comment by lwansbrough** [comment]
Do you think you could do something similar for Android?

**Comment by sharathprabhal** [comment]
@lwansbrough Absolutely! I'll work on a PR soon.

**Comment by lwansbrough** [comment]
Awesome!

**Comment by adamkdean** [comment]
@sharathprabhal did you ever get round to this?

**Comment by sharathprabhal** [comment]
@adamkdean Unfortunately, I did not get around to adding it for android.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
