### ISSUE TITLE
Module ''react-native'' has no exported member 'ViewProperties'

### ISSUE THREAD

**Issue by pimuzzo** [react-native-community/react-native-camera#1624]
Using react-native-camera > `1.0.2` I have this issue when launching yarn build on my project:

```
No valid rules have been specified
node_modules/react-native-camera/types/index.d.ts(13,10): error TS2305: Module ''react-native'' has no exported member 'ViewProperties'.
error Command failed with exit code 2.
```

**Comment by jgfidelis** [comment]
please try newer versions

**Comment by pimuzzo** [comment]
As previously written I tried the new versions, but the only one that works correctly is 1.0.1 (or less).
At the moment I'm trying to debug the problem, I'll update the ticket if I find out something.
If you have any advice I'll try it

**Comment by pimuzzo** [comment]
Fixed, I write two lines in case it happens to someone else.
I'm writing an extension for reactxp and I noticed that it included a custom version of react-native types. removing it and installing the types from npm now everything works perfectly, sorry.
