### ISSUE TITLE
Error: camera is not running

### ISSUE THREAD

**Issue by taomanwai** [react-native-community/react-native-camera#1626]
Hi all,

I am using RNCamera takePictureAsync(), it works in iOS but failed in Android, any ideas?

### Steps to reproduce
1. Add RNCamera in page
2. Run const data = await this.camera.takePictureAsync({ quality: 0.5, base64: true });
3. "Error: camera is not running" exception occurred 

### Expected behaviour
Capture camera image as data variable

### Actual behaviour
"Error: camera is not running" exception occurred 

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: Android 7.1.0

### react-native-camera
**Version**: "master" (RNCamera is using)

**Comment by taomanwai** [comment]
To n1ru4l, what more information u want?

**Comment by massimopibiri** [comment]
The same problem here. The camera sometimes works when the application is rebuilt. But he stops working suddenly for no reason, even when nothing has changed in the code.

**Comment by massimopibiri** [comment]
Found the solution :
I read in stackoverflow that the problem comes from the router (I use react-native-router-flux). I don't know if this is true or not. I didn't understand it. In my case, everything started to work as soon as I removed the following code from inside the RNCamera:

```
          {({ camera, status }) => {
            if (status !== 'READY') return <PendingView />;
            return (
              <View style={{ flex: 0, flexDirection: 'row', justifyContent: 'center' }}>
                <TouchableOpacity onPress={() => this.takePicture(camera)} style={styles.capture}>
                  <Text style={{ fontSize: 14 }}> SNAP </Text>
                </TouchableOpacity>
              </View>
            );
          }}
```
And I simply put the button without verifying if the camera is 'ready':

```
              <View style={{ flex: 0, flexDirection: 'row', justifyContent: 'center' }}>
                <TouchableOpacity onPress={() => this.takePicture(camera)} style={styles.capture}>
                  <Text style={{ fontSize: 14 }}> SNAP </Text>
                </TouchableOpacity>
              </View>
```
and it works perfectly.

**Comment by massimopibiri** [comment]
Sorry... without the "camera" inside this.takePicture()

**Comment by geisterfurz007** [comment]
Appears my issue is a duplicate of this https://github.com/react-native-community/react-native-camera/issues/1426#issuecomment-381566152

**Comment by telmen** [comment]
This is happening on Android 4.4.2

**Comment by shaksi** [comment]
had similar issue where the camera is loading on iOS and not on android. 
following @massimopibiri advice adapted the code as follows

`{({ camera, status }) => {
//check if camera is ready and platform is not android
//if android assume its ready
            if (status !== 'READY' && Platform.OS === "android") return <PendingView />;
            return (
              <View style={{ flex: 0, flexDirection: 'row', justifyContent: 'center' }}>
                <TouchableOpacity onPress={() => this.takePicture(camera)} style={styles2.capture}>
                  <Text style={{ fontSize: 14 }}> SNAP </Text>
                </TouchableOpacity>
              </View>
            );
          }}`

**Comment by zvs001** [comment]
I had this issue with `react-navigation` router.
Camera stops working after I changing page
This code solved it for me:
``` 
import { withNavigationFocus } from 'react-navigation' 
```

```
render() {
    const { isFocused } = this.props
    return (
       <View>
         { isFocused && <RNCamera  ... />  }
       </View
     )
}
```
``` 
export default withNavigationFocus(Camera) 
```

**Comment by brsaylor2** [comment]
I'm using `react-native-navigation` and was seeing this bug after displaying a modal over the camera. I solved it by passing the [`modalPresentationStyle: 'overCurrentContext'`](https://wix.github.io/react-native-navigation/#/docs/styling?id=common-options) option to `showModal`.

**Comment by blackstalk** [comment]
I was getting the "Camera not running" error when i changed screens. So for functional components instead of `withNavigationFocus(Camera)` use this method:
```

import { useIsFocused } from '@react-navigation/native';

function MyComponent() {
  const isFocused = useIsFocused()
  
  return (
    <View>
      { isFocused && <RNCamera />  }
    </View>
  )
}
```
