### ISSUE TITLE
How to pause camera preview?

### ISSUE THREAD

**Issue by deathnopool** [react-native-community/react-native-camera#1628]
how to pause camera preview while using RNCamera ?
i use it to scan barcode and don't know how to pause it after getting result.

**Comment by sibelius** [comment]
use master for now

https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#pausepreview-void

**Comment by deathnopool** [comment]
@sibelius thanks!  but by using 1.1.5, an error  `undefined is not a function (evaluating 'CameraManager.pausePreview(this._cameraHandle)')` ocurrs.

**Comment by deathnopool** [comment]
@sibelius thanks!
