### ISSUE TITLE
undefined is not an object (evaluating 'CameraManager.aspect') during running app

### ISSUE THREAD

**Issue by sarikabhimre18** [react-native-community/react-native-camera#1631]

**Comment by sibelius** [comment]
your linking is wrong

check docs, link right and rebuild

**Comment by OPY-bbt** [comment]
+1

**Comment by connercms** [comment]
+1.  I think most of us are following the docs exactly and experiencing this issue, so it would be nice to get a better explanation than "your link is wrong" that is posted in every thread involving this issue. What do you mean "your linking is wrong"?

**Comment by GreatAuk** [comment]
+1

**Comment by ShahoG** [comment]
Have the exact same issue,  installed and linked according to docs but get this instead:

> rnpm-install ERR! Something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "<" found.
Please file an issue here: https://github.com/facebook/react-native/issues

**Comment by imspikey** [comment]
I solved this issue buy cleaning and rebuilding with android studio 👍

**Comment by anniewey** [comment]
Run `react-native-link` didn't link the library completely.
Manually add `libRNCamera.a` to **Linked Frameworks and Libraries** solve the problem for me

**Comment by n1ru4l** [comment]
@riyadshauk You can either do that or correctly link the library 😇
