### ISSUE TITLE
flashMode.torch not turning on light RNCamera

### ISSUE THREAD

**Issue by mcoder14** [react-native-community/react-native-camera#1634]
Using *RNCamera* 

### Steps to reproduce
<RNCamera
					ref={cam => {
						this.camera = cam;
					}}
					style={this.getStyle().preview}
					type={RNCamera.Constants.Type.back}
					flashMode={RNCamera.Constants.FlashMode.torch}
					onFocusChanged={() => { }}
					onZoomChanged={() => { }}
					defaultTouchToFocus
					mirrorImage={false}
					barCodeTypes={[
						RNCamera.Constants.BarCodeType.aztec,
						RNCamera.Constants.BarCodeType.code39,
						RNCamera.Constants.BarCodeType.code39mod43,
						RNCamera.Constants.BarCodeType.code93,
						RNCamera.Constants.BarCodeType.code128,
						RNCamera.Constants.BarCodeType.datamatrix,
						RNCamera.Constants.BarCodeType.ean13,
						RNCamera.Constants.BarCodeType.ean8,
						RNCamera.Constants.BarCodeType.interleaved2of5,
						RNCamera.Constants.BarCodeType.itf14,
						RNCamera.Constants.BarCodeType.pdf417,
						RNCamera.Constants.BarCodeType.qr,
						RNCamera.Constants.BarCodeType.upce,
					]}
					onBarCodeRead={barcodeReadFunction}
				>

### Expected behaviour
The torch mode should turn on the flashlight and it should stay on

### Actual behaviour
The flash flickers twice and then does not turn on

### Environment
-  "react-native": "0.55.3",
-  iOS 11.3

### react-native-camera
      "react-native-camera": "^1.1.2",

**Comment by jlemm45** [comment]
Torch mode needs to be set after the camera has already loaded so essentially try using a state variable tied to a button toggle of some sort to control which flashMode is on. 

Example:
`flashMode={torchOn ? Camera.Constants.FlashMode.torch : Camera.Constants.FlashMode.off}`

**Comment by n1ru4l** [comment]
We should improve this!

**Comment by zhangxinagjunHJH** [comment]
Have you solved the problem already？

**Comment by zhangxinagjunHJH** [comment]
I rebuild project from xcode, it worked!

**Comment by joaaomanooel** [comment]
I also have this problem on Android and tried these solutions, but it did not work

**Comment by GotiMehta** [comment]
@jordanmkoncz  I tried your solution however it is only working in Android and not in iOS. Bit strange but could not successful. Torch just blinks once and goes off.

I followed below reference for it:
[https://github.com/react-native-community/react-native-camera/issues/1626#issuecomment-402609694](url)

Does any body have idea what causes the issue?

**Comment by smeevil** [comment]
I have the exact same thing as @GotiMehta on iOS.

**Comment by GotiMehta** [comment]
@smeevil 

Use [react-native-torch](https://www.npmjs.com/package/react-native-torch). It works in both platforms.
