### ISSUE TITLE
About the usage of recordAsync to record video with RNCamera

### ISSUE THREAD

**Issue by goldenhuang** [react-native-community/react-native-camera#1638]
Hello,
     I am using RNCamera (the latest release 1.1.5) to record the video from Camera on iPhone. 
     I got the one issue by duplicating it as below.
     (1) Use <RNCamera> with whatever props required for video recording.
     (2) Use recordAsync with its options to start record the video.
     (3) For the first recording right after calling stopRecording, I can read back the recorded video file without any issues.
     (4) But if my code calls recordAsync again for the second call, the code will fail at the internal API call, startRecordingToOutputFileURL in the code portion of RNCamera.m!! 
     It can be reproduced and consistent. Right now I don't have any clue to solve it.
     The same code can work very well on Android platform but fail on iOS iPhone 6 device.
     The caught error is as below:

     exception	NSException *	name: @"NSInvalidArgumentException" - reason: @"*** -[AVCaptureMovieFileOutput startRecordingToOutputFileURL:recordingDelegate:] No active/enabled connections"	0x000000010e9628b0

     Let me know if you need more information from me. Thanks!

**Comment by willysama** [comment]
Hello @goldenhuang,
I have the same issue!
I saw you closed the thread. Were you able to solve your problem? If so, what did you do?

**Comment by goldenhuang** [comment]
Hello,
    Please comment out the following code section right located at the end of 'didFinishRecordingToOutputFileAtURL' of RNCamera.m in react-native-camera/ios/RN:
    if (self.session.sessionPreset != AVCaptureSessionPresetPhoto) {
         [self updateSessionPreset:AVCaptureSessionPresetPhoto];
    }
    After commenting this out clean and rebuild the project, then you can continuously complete each video recording.
    The default value for sessionPreset is high.

**Comment by willysama** [comment]
@goldenhuang thank you!
