### ISSUE TITLE
Argument list too long: recursive header expansion failed

### ISSUE THREAD

**Issue by JindiHu** [react-native-community/react-native-camera#1648]
React native camera 1.1.4
i followed the instruction and manually link for ios  no face detection setup. 
but when i build the project, i got this error 

Argument list too long: recursive header expansion failed

can someone share the solution?

**Comment by VicFrolov** [comment]
I opened a ticket about this a few months ago, and it was closed stating it was fixed, but this was not fixed for me.

You need to go to Xcode -> Libraries -> RNCamera.xcodeproj -> Framework Search Paths

this works for me: `$(SRCROOT)/../../ios` and I need to change it from `$(SRCROOT)/../../../ios`

**Comment by vgeorge** [comment]
@JindiHu Did you look into issue #1407? I managed to install without face detection by installing via CocoaPods, as explained [here](https://github.com/react-native-community/react-native-camera/issues/1407#issuecomment-397683592).

**Comment by sibelius** [comment]
check this https://github.com/react-native-community/react-native-camera/issues/1407
