### ISSUE TITLE
Preview distorted when its size is set to  fullscreen. 

### ISSUE THREAD

**Issue by Mnjaro** [react-native-community/react-native-camera#1650]
### Steps to reproduce
1. Use the RNCamera exemple from documentation
2. Delete the TouchableOpacity to set Preview to fullscreen
3. Open the app to the Camera screen

### Expected behaviour

Camera should be of correct ratio. Or of a fixed ratio

### Actual behaviour

Image get shrinked or streched depending on screen orientation.

**Comment by SimonErm** [comment]
Android or iOS or both?

**Comment by ntelkedzhiev** [comment]
Same here... Simulated on Android.
