### ISSUE TITLE
[Android] when orientation is locked programmatically, recorded video is sometimes rotated

### ISSUE THREAD

**Issue by manask88** [react-native-community/react-native-camera#1652]
### Which implementation are you using

RNCamera

### Steps to reproduce
1.  Lock the screen orientation to portrait mode programatically
2. Mount the camera component
3. start recording

### Expected behaviour
If the video has been recorded with the physical orientation of the phone in landscape or portrait mode, those videos should have the correct orientation when they are played.

### Actual behaviour
- When the orientation is locked to portrait programmatically and the phone is placed in landscape physical orientation, the recorded video comes rotated.
- When the orientation is locked to portrait programmatically and the phone is placed in portrait physical orientation, the recorded video orientation comes out okay.

### Environment
- **React Native version**:  0.55.4
- **React Native platform + platform version**:  Android 5.0

### react-native-camera
**Version**: npm version or "master": master

In order to make this work some changes in https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/google/android/cameraview/DisplayOrientationDetector.java#L59 would need to be made. The current limitation is that Display.getRotation gets the screen rotation based on the natural state of the device. When the orientation is locked programmatically, this value never changes.  

A potential solution is to use the orientation from the listener in order to set the output video orientation and use Display.getRotation to set the video preview orientation

I'd love to send a PR with this solution. However, I want to understand if you guys would be willing to accept my changes.

**Comment by manask88** [comment]
@sibelius , please let me know your thoughts about this so I can start working on a potential solution

**Comment by n1ru4l** [comment]
Possible related to #1725
