### ISSUE TITLE
[Android] Could not find method implementation() for arguments [com.google.zxing:core:3.2.1] 

### ISSUE THREAD

**Issue by longpq18** [react-native-community/react-native-camera#1655]
Could not find method implementation() for arguments [com.google.zxing:core:3.2.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

My react-native: 
react-native-cli: 2.0.1
react-native: 0.53.3

**Comment by sibelius** [comment]
can u post the full stacktrace?

**Comment by longpq18** [comment]
myproject/node_modules/react-native-camera/android/build.gradle' line: 56

* What went wrong:
A problem occurred evaluating project ':react-native-camera'.
> Could not find method implementation() for arguments [com.google.zxing:core:3.2.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by punksta** [comment]
upgrade your gradle and android-gradle-plugin to resolve issue: https://stackoverflow.com/a/46619296/2795206
