### ISSUE TITLE
feature request: allow not to save to disk

### ISSUE THREAD

**Issue by mvayngrib** [react-native-community/react-native-camera#1659]
### Which implementation are you using

RNCamera

### Why?

security reasons. I only want the base64, i don't want the image saved anywhere at all. I realize I could use some other lib to delete the image after, but it would cool to have an option not to save in the first place

**Comment by jgfidelis** [comment]
this would be a fairly simple thing, just create an option like `doNotSave` and if it is true, skip the save on cache.

**Comment by mvayngrib** [comment]
@jgfidelis yep, happy to submit a PR when i have some time (probably in a few weeks), or if someone else wants to do it, by all means

**Comment by n1ru4l** [comment]
closed in #1770
