### ISSUE TITLE
[documentation][need help] not clear how to setup camera on android throw guide

### ISSUE THREAD

**Issue by djleonskennedy** [react-native-community/react-native-camera#1660]
### Which implementation are you using
*RNCamera*

### Steps to reproduce
N/A

### Expected behaviour
No propblem to setup for ios and android.

### Actual behaviour
No propblem to setup for ios, but a lot of aspects not clear for android.

### Motivation
Hello you've got amazing plugin for camera, i'm new in RN however i've set camera for ios and it's work as well

**However i've can't build and run android application**
Sorry that i use issue tracker as clarification area, but i'm fighting with android for 4 days :)

Might you've got some example with lates plugin and RN version on android.

P.S. latest result are i've build app, but it's crashed during launch with Java error:
**MainApplication** could not be created, can find symbol **BuildConfig**

### Environment
- **React Native version**:
 "dependencies": 
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-camera": "^1.1.4"
 
  "devDependencies": 
    "babel-jest": "23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.1.0",
    "react-test-renderer": "16.3.1"
  
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
react-native-cli@2.0.1

### react-native-camera
**Version**: ^1.1.4

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by rghorbani** [comment]
@djleonskennedy Is this what you are looking for?
[https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md](https://github.com/react-native-community/react-native-camera/blob/master/docs/GradleUpgradeGuide.md)
