### ISSUE TITLE
I get Cannot initialize a variable of type 'CFDictionaryRef' when building RNCamera in Xcode

### ISSUE THREAD

**Issue by ingviso** [react-native-community/react-native-camera#1665]
### Which implementation are you using

RNCamera

### Steps to reproduce
1. yarn add react-native-camera
2. build app wich import RNCamera

### Expected behaviour
I should be able to build the app with RNCamera imported inside Xcode using iPhone 6s with iOS 11,4 and run the app.

### Actual behaviour
When building RNCamera in Xcode an error occurs inside:
Project > Libraries > RNCamera.xcodeproj > RN > RNImageUtils.m > +updatePhotoMetadata:withAdditionalData:inResponse

On line 98 this error comes up
Cannot initialize a variable of type 'CFDictionaryRef' (aka 'const __CFDictionary *') with an rvalue of type 'CFTypeRef _Nullable' (aka 'const void *')

Code in line 98: 
`CFDictionaryRef exifAttachments = CMGetAttachment(imageSampleBuffer, kCGImagePropertyExifDictionary, NULL);`

### Environment
Platform:  iOs 11,4
"react-native": "^0.55.2",
"react-native-camera": "^1.1.4"

**Comment by jgfidelis** [comment]
what xcode version are you using?

**Comment by uriklar** [comment]
Hi @ingviso i'm getting this too. Any chance you remember the solution?
