### ISSUE TITLE
Publish react-native-camera@1.1.5

### ISSUE THREAD

**Issue by cailenmusselman** [react-native-community/react-native-camera#1670]
I see the package.json was updated to version 1.1.5 a couple weeks ago - will it be published to NPM soon? It still lists 1.1.4 as the newest version.

Sorry in advance if this isn't the correct medium to ask such questions.

**Comment by DavidBabel** [comment]
Seems like there is nothing in yet.

**Comment by chad187** [comment]
@cailenmusselman if you can't wait try this
Inside your package.json, use this "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera" instead of "react-native-camera": "^1.0.0".
