### ISSUE TITLE
Camera shows BLACK SCREEN

### ISSUE THREAD

**Issue by Albert0405** [react-native-community/react-native-camera#1671]
### Problem
Im using react-native-camera for scanning QR Codes and react-navigation for TabNavigation. I wanted to put the Camera in one of the Tabs i created in react-navigation unfortunately when i try to navigate on other tabs and then go back to camera tab, the camera became black

1. Camera is working fine
2. I press on Home Tab which contains nothing but text "Home"
3. I press back to QrScanner Tab to see if the camera still working but unfortunately it became black and cannot scan QR Code anymore

![untitled-1](https://user-images.githubusercontent.com/38030623/42125576-aece7122-7c2e-11e8-91ed-6483676014f5.png)

### Which implementation are you using
QR Code Scanner

### Does it work with Expo Camera?
Yes, Check it here and run in your device
https://snack.expo.io/rkPEdeSzX

### Expected behaviour
I just want the camera to be still working after i press on the Tabs on my TabNavigator

**Comment by SimonErm** [comment]
Take a look at #1051 and #999. If the answers don't work for you, you can reopen the issue.

**Comment by Albert0405** [comment]
I fixed using react navigation isFocused and withNavigationFocus

**Comment by Albert0405** [comment]
By the way im having a performance issue when using withNavigationFocus. Was there any other way to fix this?

**Comment by dileepbolisetti** [comment]
@Albert0405 pls provide sample code i am unable to achieve it thanks in advance

**Comment by Albert0405** [comment]
@dileepbolisetti  Here

```
import { withNavigationFocus } from "react-navigation";
import QRCodeScanner from "react-native-qrcode-scanner";
```

```
class QrCodeCamera extends Component {

      renderCamera() {
         const isFocused = this.props.navigation.isFocused();
         
         if (!isFocused) {
             return null;
         } else if (isFocused) {
             return (
                <QRCodeScanner />
             )
         }

      render() {
         return (
           <View style={{ flex: 1 }}>
              {this.renderCamera()}
           </View>
     }
}

export default withNavigationFocus(QrCodeCamera);
```

**Comment by raphaelhovsepyan** [comment]
Don't Wrap `RNCamera` with other components, it should be on the top

**Comment by munonn430** [comment]
can i have the custom marker source code?

**Comment by Hirurgo** [comment]
> Don't Wrap `RNCamera` with other components, it should be on the top

Где ваши доказательства. RNCamera wrapped in View in official doc.

https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md

**Comment by n1ru4l** [comment]
@raphaelho wrote
> Don't Wrap RNCamera with other components, it should be on the top

That is not true, you can wrap `RNCamera` into any component. (as @Hirurgo said).
