### ISSUE TITLE
Ask:  want to save image or not

### ISSUE THREAD

**Issue by burhanahmed92** [react-native-community/react-native-camera#1679]
I am using RNCamera. Is there option in RNCamera to show a captured image with option to retake or save. 

### Expected behaviour
I want RNCamera to show dialog with current capture image with option save or retake

### Actual behaviour
Just save the captured image

### Environment
- **React Native version*0.55.3*:
- **React Native platform + platform version**: iOS 9.0 to 11, Android 5.0 to 8.0

### react-native-camera
**Version**: npm version 1.1.1

**Comment by jgcmarins** [comment]
This feature does not apply for this lib. It's up to developer to take control of this kind of dialog.
