### ISSUE TITLE
onBarCodeRead still be called after cameraInstance.pausePreview()

### ISSUE THREAD

**Issue by deathnopool** [react-native-community/react-native-camera#1680]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our [Migration guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md)

### Which implementation are you using
RNCamera
*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
1. set a RNCamera View
2. give the onBarCodeRead a callback func
3. cameraInstance.pausePreview() when onBarCodeRead 
4. onBarCodeRead still be called
### Does it work with Expo Camera?
Check usage with Expo - https://github.com/react-native-community/react-native-camera/blob/master/docs/Expo_Usage.md
You should open an issue there as well, so we can cooperate in a solution.

### Expected behaviour
Tell us what should happen
barcode recognizing paused after pausePreview
### Actual behaviour
Tell us what happens instead
barcode recognizing don't paused after pausePreview

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
android 8.0
### react-native-camera
**Version**: npm version or "master"
master

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by deathnopool** [comment]
@Concert0 thanks! that may be an option.

**Comment by sibelius** [comment]
try on latest version

**Comment by roshangm1** [comment]
This issue still exists in latest version as well. I have camera in the bottomsheet. I do pausePreview initially and resume preview when bottomsheet is opened. But still, qr code is scanned even if the state is paused. Any other workarounds for this ? @sibelius
