### ISSUE TITLE
Camera is not initialize after updating React-Native to 0.56 on Android 5.1

### ISSUE THREAD

**Issue by anton-loktev** [react-native-community/react-native-camera#1681]
Camera is not initialize after updating React-Native to 0.56 on Android 5.1. 
The same project is working fine on RN 0.55 + Android 5.1 (api 22) or with RN 0.56 + Android 6 or higher.

### Environment
- **React Native version**: 0.56
- **Android 5.1**

### react-native-camera
**Version**: 1.1.4

**Comment by s-o-r-o-u-s-h** [comment]
Does it says Camera is not Authorized?

**Comment by anton-loktev** [comment]
Yes. Your PR fix this issue.

**Comment by ivosabev** [comment]
Is the PR going to be merged and released soon?

**Comment by sibelius** [comment]
fixed https://github.com/react-native-community/react-native-camera/pull/1684
