### ISSUE TITLE
<ios 11.4  RNCamera 1.1.4>when i record a video , then I cancel this operation and record a new video will crash on startRecordOutputFileUrl withDelegate

### ISSUE THREAD

**Issue by chriszhou666666** [react-native-community/react-native-camera#1683]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our [Migration guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md)

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
1.
2.
3.

### Does it work with Expo Camera?
Check usage with Expo - https://github.com/react-native-community/react-native-camera/blob/master/docs/Expo_Usage.md
You should open an issue there as well, so we can cooperate in a solution.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-camera
**Version**: npm version or "master"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by yagneshmodh** [comment]
i am facing the same issue . 
following is my code

**Comment by sibelius** [comment]
it is happening on latest version?
