### ISSUE TITLE
Camera freezes and black screen

### ISSUE THREAD

**Issue by nadzic** [react-native-community/react-native-camera#1686]
### Which implementation are you using

*RNCamera*

### Steps to reproduce
1. Come to one of screens where we initialize react-native camera
2. Scan the barcode with react-native camera
3. Camera freezes and we have to go next screen and back that we can scan again

### Does it work with Expo Camera?
Not using expo camera.

### Expected behaviour
React native camera should scan barcode normally and not freeze.

### Actual behaviour
I am using react native camera with the combination of the react-navigation 1.4.0, it works fine on iOS and newer version of Android phones, but on Android version 7.0 always I scan product barcode the camera freezes. If I want to scan, I have to go to next screen with react-navigation and then back to scan the product. 

I am having also another one issue, which happens sometimes - not every time. For example if I scan product or many products and go to next screen and then return back to this one screen I get black screen here where is initialised. It does not happen every time, just sometimes. I am using the following code for the scanning: 

```jsx
const view = (
  <RNCamera
    ref={ref => {
      this.camera = ref;
    }}
    style={styles.cameraPreview}
    onBarCodeRead={isEmpty(currentProduct) ? this.onBarCodeRead : null}
    permissionDialogTitle={"Permission to use camera"}
    permissionDialogMessage={"We need your permission to use your camera phone"}
  />
);

```

As you can see is am enabling/disabling onBarCodeRead with null or . Maybe that should be the problem? isEmpty(currentProduct) works fine, in cases when I need it is true, otherwise it is false.

### Environment
- **React Native version**: 0.52.0
- **React Native platform + platform version**: Android 7.0

### react-native-camera
**Version**: ^1.1.4

> Love react-native-camera? Please consider

**Comment by Albert0405** [comment]
[react-native-qrcode-scanner](https://github.com/moaazsidat/react-native-qrcode-scanner) use this instead. It uses react-native-camera too (RNCamera)

**Comment by nadzic** [comment]
Why should I use react-native-qrcode-scanner if I am scanning barcodes? What is actually the difference between react-native-camera and react-native-qrcode-scanner?

**Comment by nadzic** [comment]
Is there any solution already?

**Comment by jamalx31** [comment]
+1

**Comment by Bartlebyy** [comment]
I had a similar problem. Looks like you're not unmounting the camera component when you switch between tabs. 
I recommend you take advantage of `componentDidMount` and added two listeners `willFocus` and `willBlur`.

Here is an example:
``` 
 componentDidMount() {
    const { navigation } = this.props;
    navigation.addListener('willFocus', () =>
      this.setState({ focusedScreen: true })
    );
    navigation.addListener('willBlur', () =>
      this.setState({ focusedScreen: false })
    );
  }

  render() {
    const { hasCameraPermission, focusedScreen } = this.state;
    if (hasCameraPermission === null) {
      return <View />;
    } else if (hasCameraPermission === false) {
      return <Text>No access to camera</Text>;
    } else if (focusedScreen){
      return (this.cameraView());
    } else {
      return <View />;
    }
  }
```

**Comment by choo737** [comment]
for my case, these only works on second round of navigation. 
`navigation.addListener('willFocus', () =>
      this.setState({ focusedScreen: true })
    );
    navigation.addListener('willBlur', () =>
      this.setState({ focusedScreen: false })
    );`

"react-native-camera": "^1.4.3",
"react-native-qrcode-scanner": "^1.1.0",
"react-navigation": "2.18.3",
"react-navigation-redux-helpers": "^2.0.6",

**Comment by n1ru4l** [comment]
@choo737 Could you please provide a minimal reproduction repository?

**Comment by GaneshSaiKumar** [comment]
> [react-native-qrcode-scanner](https://github.com/moaazsidat/react-native-qrcode-scanner) use this instead. It uses react-native-camera too (RNCamera). If you're not using QRcode then you need to add barCodeTypes in the index.js of the plugin

i'm using react-native-qrcode-scanner still facing the same issue

**Comment by paakcmd** [comment]
If you want to reuse the camera make sure it rerenders before the 2nd use.

**Comment by superp** [comment]
> I had a similar problem. Looks like you're not unmounting the camera component when you switch between tabs.
> I recommend you take advantage of `componentDidMount` and added two listeners `willFocus` and `willBlur`.
> 
> Here is an example:
> 
> ```js
>  componentDidMount() {
>     const { navigation } = this.props;
>     navigation.addListener('willFocus', () =>
>       this.setState({ focusedScreen: true })
>     );
>     navigation.addListener('willBlur', () =>
>       this.setState({ focusedScreen: false })
>     );
>   }
> 
>   render() {
>     const { hasCameraPermission, focusedScreen } = this.state;
>     if (hasCameraPermission === null) {
>       return <View />;
>     } else if (hasCameraPermission === false) {
>       return <Text>No access to camera</Text>;
>     } else if (focusedScreen){
>       return (this.cameraView());
>     } else {
>       return <View />;
>     }
>   }
> ```

If you use Ignite and 'willFocus' doesn't fires try this https://github.com/react-navigation/redux-helpers/issues/53

**Comment by n1ru4l** [comment]
@choo737 Do you have a reproduction?

**Comment by wellington-cunha** [comment]
I solved my problem using  "react-native-camera": "1.2.0",

**Comment by ntk0104** [comment]
> I had a similar problem. Looks like you're not unmounting the camera component when you switch between tabs.
> I recommend you take advantage of `componentDidMount` and added two listeners `willFocus` and `willBlur`.
> 
> Here is an example:
> 
> ```js
>  componentDidMount() {
>     const { navigation } = this.props;
>     navigation.addListener('willFocus', () =>
>       this.setState({ focusedScreen: true })
>     );
>     navigation.addListener('willBlur', () =>
>       this.setState({ focusedScreen: false })
>     );
>   }
> 
>   render() {
>     const { hasCameraPermission, focusedScreen } = this.state;
>     if (hasCameraPermission === null) {
>       return <View />;
>     } else if (hasCameraPermission === false) {
>       return <Text>No access to camera</Text>;
>     } else if (focusedScreen){
>       return (this.cameraView());
>     } else {
>       return <View />;
>     }
>   }
> ```

sorry but I have tried your solution and also tried with navigation.isFocused but none of them work? any solution?

**Comment by JeevaS0722** [comment]
To make this work you need to:
```javascript
import { NavigationEvents } from 'react-navigation';
state = { loaded: true }
render() {
    const { loaded } = this.state;
    return (
      <View style={styles.container}>
        <NavigationEvents
          onWillFocus={payload => this.setState({loaded: true})}
          onDidBlur={payload => this.setState({loaded: false})}/>
      <View style={styles.cameraArea}>
        {loaded && (
          <Camera
            type={Camera.Constants.Type.back}
            ref={ref => {
              this.camera = ref;
            }}
          />
          )}

        </View>
```
The idea is to hide this camera view (onDidBlur-> loaded: false), then when you come back (onWillFocus is triggered and change loaded to true). When render() function is called it will show the <Camera /> again

https://stackoverflow.com/a/54308457/12029536

**Comment by JayM96** [comment]
@JeevaS0722 thanks for the solution.

**Comment by JeevaS0722** [comment]
Thanks...!
