### ISSUE TITLE
Argument list too long: recursive header expansion failed at

### ISSUE THREAD

**Issue by zhangxinagjunHJH** [react-native-community/react-native-camera#1687]
### 
Argument list too long: recursive header expansion failed at /Users/zxj/tfs2018/Huawei.GIS.Application/node_modules/react-native-camera/ios/../../../ios/HuaweiGIS/assets/web/bim-models/svf/cb214ab4-7bf0-41bd-a81c-2c81cd1d3f89.nwc/output.

### 

RNCamera

### Steps to reproduce
1.Follow the "Manual install" guide for iOS in the readme.md file
2.Build the app

### Actual behaviour
Throws an error when building:
`Argument list too long: recursive header expansion failed at /Users/zxj/tfs2018/Huawei.GIS.Application/node_modules/react-native-camera/ios/../../../ios/HuaweiGIS/assets/web/bim-models/svf/cb214ab4-7bf0-41bd-a81c-2c81cd1d3f89.nwc/output.`

### Environment
 "react": "16.0.0-alpha.12",
 "react-native": "^0.55.4",

### react-native-camera
"react-native-camera": "^1.1.4",

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by Gys** [comment]
You could have searched the open and closed issues first. Because this same issue is opened 4 or 5 times already...

The solution is to modify the react-native-camera package every time that you run npm install. Because this problem is caused by a xcode project setting in the package. An explanation and workaround is here: https://github.com/react-native-community/react-native-camera/issues/1407#issuecomment-392881900

**Comment by jgcmarins** [comment]
@Gys is this workaround the only solution or is there a final solution?

**Comment by Gys** [comment]
The final solution is probably someone making a pull request with the updated xcode project ;-)

**Comment by jgcmarins** [comment]
@Gys do you know how to do that?

**Comment by Gys** [comment]
Have a look at this !
https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR

**Comment by jgcmarins** [comment]
Hey @Gys,
I am very happy to know that you have good practices for submitting Pull Requests.
Could you help us on this one?
Since I've already done mine contributions: https://github.com/react-native-community/react-native-camera/commits?author=jgcmarins :wink:

**Comment by dave-irvine** [comment]
@Gys @jgcmarins While we are discussing the issue, I noticed https://github.com/react-native-community/react-native-camera/issues/1454#issuecomment-406257449 that removing all entries from `FRAMEWORK_SEARCH_PATHS` also seems to resolve the issue. Does anyone know if this field needs to be filled at all?

**Comment by sibelius** [comment]
check this https://github.com/react-native-community/react-native-camera/issues/1407
