### ISSUE TITLE
Android dependency 'com.android.support:exifinterface' has different version for the compile (26.1.0) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution

### ISSUE THREAD

**Issue by piyushdesuvit** [react-native-community/react-native-camera#1689]
I am trying to install the library when i build the project shows error ->
Android dependency 'com.android.support:exifinterface' has different version for the compile (26.1.0) and runtime (27.1.0) classpath. You should manually set the same version via DependencyResolution 

Working fine for react native fresh installed project ...

![image](https://user-images.githubusercontent.com/33368907/42558972-5c072052-8510-11e8-87b4-d19a723b013e.png)

**Comment by NielsLindberg** [comment]
Had similar issue mby the following will help:

In android/build.gradle:
```
ext {
    buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
    googlePlayServices = "15.+"
}

```
In Android/App/build.gradle:
```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'com.android.support:multidex:1.0.0'
    implementation(project(':react-native-firebase')) {
        transitive = false
    }
    implementation "com.google.firebase:firebase-core:${rootProject.ext.googlePlayServices}"
    implementation "com.google.firebase:firebase-auth:${rootProject.ext.googlePlayServices}"
    implementation "com.google.firebase:firebase-firestore:16.0.0"
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation "com.google.android.gms:play-services-base:${rootProject.ext.googlePlayServices}"
    implementation "com.google.android.gms:play-services-maps:${rootProject.ext.googlePlayServices}"
    implementation project(':react-native-vector-icons')
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation project(':react-native-linear-gradient')
    implementation (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
        implementation 'com.android.support:exifinterface:27.+'
        implementation ("com.google.android.gms:play-services-vision:${rootProject.ext.googlePlayServices}") {
            force = true
    }
}

```

**Comment by jbonino** [comment]
hey @NielsLindberg 
You approach worked for me but i have to change one thing.

In android/build.gradle, 

I changed googlePlayServices = "15.+"
to googlePlayServicesVersion = "15.+"

And everything worked correctly

**Comment by piyushdesuvit** [comment]
HI @NielsLindberg 
I did all that you mentioned..
 every thing build successfully but apps keeps stopping
![keeppingstop](https://user-images.githubusercontent.com/33368907/42804690-5791a810-89c7-11e8-96b8-353a61972452.gif)

**Comment by reilem** [comment]
I had this issue aswell, and what fixed it for me was changing:
`implementation 'com.android.support:exifinterface:25.+'` to `implementation 'com.android.support:exifinterface:27.+'` and adding `supportLibVersion = "26.1.0"` under `ext`.

**Comment by sibelius** [comment]
make sure all support libs matches
