### ISSUE TITLE
iOS cannot identify QR code when its size is less than 55x55px 

### ISSUE THREAD

**Issue by NickWarrior** [react-native-community/react-native-camera#1693]
### Which implementation are you using
RNCamera

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
1.Scanning QR code which size is less than 55x55px by react-native-camera
2.Cannot  identify QR code and onBarCodeRead not called.
3.This is my code 
```
<RNCamera
     ref={cam => this.camera = cam}
     style={styles.cameraStyle}
     barCodeTypes={[RNCamera.constants.BarCodeType.qr]}
     onBarCodeRead={
         this.barcodeReceived
     }
     torchMode={openFlash ? 'on' : 'off'}>
     </RNCamera>
```

### Expected behaviour
Be able to identify QR code and onBarCodeRead can be called

### Actual behaviour
Cannot identify QR code and onBarCodeRead can not be called

### Environment
react-native:0.47.0
React Native platform:iOS10.2.1

### react-native-camera
react-native-camera:1.1.4

**Comment by sibelius** [comment]
try on latest version

it uses MLKit
