### ISSUE TITLE
IOS record have a flash when start recording

### ISSUE THREAD

**Issue by meiqi1992** [react-native-community/react-native-camera#1700]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our [Migration guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md)

### Which implementation are you using

*RNCamera* or RCTCamera (RCTCamera will be removed on v2.0.0)?

### Steps to reproduce
1.
2.
3.

### Does it work with Expo Camera?
Check usage with Expo - https://github.com/react-native-community/react-native-camera/blob/master/docs/Expo_Usage.md
You should open an issue there as well, so we can cooperate in a solution.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version 0.55.4:
- **React Native platform + platform version**: iOS 9.0, 

### react-native-camera
**Version**: npm version or "master"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

when I start recording use 'RNCamera.recordAsync()'，and then the camera view appear a flash(from dark to shallow)  ,only IOS have the problem android work well.

**Comment by pqminh** [comment]
Did you fix it?
