### ISSUE TITLE
App crash on Android < 5.0

### ISSUE THREAD

**Issue by ntelkedzhiev** [react-native-community/react-native-camera#1701]
### Which implementation are you using

RNCamera

### Steps to reproduce
1. Run app on a device with API Level < 21

### Actual behaviour
App crashes with the following error: 

NoClassDefFoundError
org.reactnative.camera.CameraViewManager
org.reactnative.camera.RNCameraPackage.createViewManagers

### Environment
- **React Native version**: 0.56
- **React Native platform + platform version**: Android < 5.0

### react-native-camera
**Version**: 1.1.4

**Comment by lyseiha** [comment]
+1

**Comment by n1ru4l** [comment]
Please open a new issue if you still experience this issue with the latest `RNCamera` version.
