### ISSUE TITLE
onTextRecognized/onFacesDetected at init position not working on Android 

### ISSUE THREAD

**Issue by yli18** [react-native-community/react-native-camera#1710]
### Which implementation are you using
RNCamera
### Steps to reproduce
    <RNCamera
      ref={(ref) => {
        this.camera = ref;
      }}
      style={{
        flex: 1,
      }}
      type={this.state.type}
      flashMode={this.state.flash}
      autoFocus={this.state.autoFocus}
      whiteBalance={this.state.whiteBalance}
      ratio={this.state.ratio}
      focusDepth={this.state.depth}
      permissionDialogTitle="Permission to use camera"
      permissionDialogMessage="We need your permission to use your camera phone"
      exif
      onFacesDetected={(face) => {
        console.log('face', face);
      }}
      onTextRecognized={(d) => {
         console.log('onTextRecognized', d.textBlocks.map(e => e.value));
      }}
    >
1. onTextRecognized and onFacesDetected(both front back cam) not getting any response when screen not rotate. (depending on front cam hardware position, rotation angle might not be 0) 
2. what strange is when rotate 90, 180, 270 it working fine, and 360 not working again
3. barcode works fine, it is probably because the codes are symmetric
        
I target the code at RNCameraView.java (128-132)

      @Override
      public void onFramePreview(CameraView cameraView, byte[] data, int width, int height, int rotation) {
        int correctRotation = RNCameraViewHelper.getCorrectCameraRotation(rotation, getFacing());
        int correctWidth = width;
        int correctHeight = height;
        byte[] correctData = data;
//        if (correctRotation == 90) {
//          correctWidth = height;
//          correctHeight = width;
//          correctData = rotateImage(data, correctHeight, correctWidth);
//        }

it works fine now, but since this code block must be there for some reason, so please look at it

### Expected behaviour
Tell us what should happen
text/ face should get recognized
### Actual behaviour
text/face not recognized at 0 degree position
### Environment
- **React Native version**:0.54.2
- **React Native platform + platform version**: Android 8.0.0, Android 8.1,0 etc

### react-native-camera
**Version**: 1.1.4

**Comment by Siarhei-Zharnasek** [comment]
I'm facing the same problem for Android, iOS works well.
Is it possible to fix this?
