### ISSUE TITLE
React native camera captured picture not save in app cache

### ISSUE THREAD

**Issue by tadeumx1** [react-native-community/react-native-camera#1718]
I am using react-native-camera in my react-native app and everything works well, however when I take a photo the picture should be saved on my device, I addressed the mention location that is app/cache where my picture saves but there is no any image. How can I access capture image? I m using takePictureAsync.

Code

` takePicture = async () => {

        const {goBack} = this.props.navigation;

        if (this.camera) {

          const options = { quality: 0.5, base64: true };
          const data = await this.camera.takePictureAsync(options);

          alert(data.uri);

        }

      };

<View style={styles.container}>

            <RNCamera
              ref={camera => {
                this.camera = camera;
              }}
              style={styles.preview}
              type={RNCamera.Constants.Type.back}
              autoFocus={RNCamera.Constants.AutoFocus.on}
              flashMode={RNCamera.Constants.FlashMode.off}
              permissionDialogTitle={"Permissão para usar a câmera"}
              permissionDialogMessage={
                "Precisamos da sua permissão para usar a câmera do celular"
              }
            />

            <View style={styles.buttonContainer}>

              <TouchableOpacity onPress={this.takePicture} style={styles.capture}>

                <Text style={styles.buttonText}> Tirar Foto </Text>

              </TouchableOpacity>

            </View>

          </View>`

"react": "16.4.1",
"react-native": "^0.56.0",
"react-native-camera": "^1.1.4",

I am using RNCamera and with all permissions that mentioned in the react-native-camera documentation. And I was copy the basic working code from the RNCamera Docs.

Thanks for attention !

**Comment by sibelius** [comment]
You should use react-native-fs to transfer the image from cache folder to an user accessible folder

check this recipe https://github.com/react-native-community/react-native-camera/blob/master/docs/Recipes.md#sending-the-image-to-a-server

feel free to improve it
