### ISSUE TITLE
Android recordAsync() crashes

### ISSUE THREAD

**Issue by vamvoukas** [react-native-community/react-native-camera#1724]
we use RCTCamera and version 1.1.5 @latest version from git.
In some android devices when we start to record a video with recordAsync(), app crashes.
And we receive this message:
{"framesToPop":1,"code":"E_CAPTURE_FAILED","line":17711,"column":29}

**Comment by jgcmarins** [comment]
RCTCamera is deprecated, use RNCamera instead

**Comment by devapro** [comment]
maybe this related to permissions. Try manual set permissions for camera and microphone to app. after this try call recordAsync
