### ISSUE TITLE
Module RCTCameraManager requires main queue setup since it overrides `constantsToExport` but doesnt implement `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by isaaclem** [react-native-community/react-native-camera#1732]
### Which implementation are you using
I've migrated from RCTCamera to RNCamera

Under `node_modules/react-native-camera`, I can see below file structures
![screen shot 2018-08-07 at 1 14 45 pm](https://user-images.githubusercontent.com/32945572/43755730-ee664692-9a43-11e8-914a-5bb719872b63.png)

I've tried to added below code to `RCTCameraManager.m` but warning still showing

    + (BOOL)requiresMainQueueSetup
    {
        return YES;
    }

I'm wondering if I can just delete the entire RCT folder?

### Expected behaviour
Warning should not be showing 

### Actual behaviour
Warning is showing. 

### Environment
"react": "^16.4.1",
    "react-native": "^0.56.0",
- iOS

### react-native-camera
"react-native-camera": "^1.1.4",

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by byronicone** [comment]
I am also seeing this issue on RN - 0.57.4.

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
