### ISSUE TITLE
undefined is not an object (evaluating 'CameraManager.Aspect')

### ISSUE THREAD

**Issue by cartesv** [react-native-community/react-native-camera#1736]
I'm getting the message: "undefined is not an object (evaluating 'CameraManager.Aspect')" while trying to render the demo code in iOS through Expo. 

react-native-cli: 2.0.1
react-native: 0.55.4

![img_1fdf22529a28-1](https://user-images.githubusercontent.com/23144526/43787524-302934b4-9a39-11e8-94c4-4e40426decc9.jpeg)

Any idea?

**Comment by cartesv** [comment]
In Camera.js, classes NativeModules.CameraManager || NativeModules.CameraModule are not defined.

**Comment by keske** [comment]
@cartesv Look this: https://github.com/react-native-community/react-native-camera/issues/1407#issuecomment-392881900

I had the same issue and that script helps me.

**Comment by fantasyStyle** [comment]
make sure you have linked xcode's linked frameworks and librales with libRNCamera.a And project finder existed the rncamera.xcodeproj

**Comment by ashavit** [comment]
It didn't for me either. I think the 5 steps of installation are not enough.
I've noticed that RCTCameraManager.m (for iOS) has "Aspect" returned as part of it's constants (constantsToExport method).
But the same method in RNCameraManager,m does not have it. it is missing other constants as well.
is it on purpose? or could this be the reason?

**Comment by albullington** [comment]
I'm stuck on the same error. I tried both react-native link for automatic installation, and I tried the 5 manual steps of installation. Haven't found a solution.

**Comment by pawanacharya** [comment]
Stuck with the same error. The manual linking doesn't solve my issue either.

**Comment by gmaci005** [comment]
I'm stuck on the same error.

**Comment by GerardoLucero** [comment]
I'm stuck on the same error X2

**Comment by albullington** [comment]
I ended up solving by shutting down my simulators and devices, then re-running npm start and react-native run-ios/run-android. Maybe linking the camera library requires a rebuild?

**Comment by xcytek** [comment]
Also, in Xcode under project navigation in the Info.plist file, you have to specify the Privacy - Camera Usage Description with a string Value. Otherwise, you will get an error.

**Comment by farkhanda44zeb** [comment]
same issue:(

**Comment by sibelius** [comment]
link is wrong

relink

**Comment by prakhar-goel** [comment]
Try `react-native link`
