### ISSUE TITLE
When I switch to the settings, and then switch camare permissions, my app always crash

### ISSUE THREAD

**Issue by linshaolie** [react-native-community/react-native-camera#174]
![image](https://cloud.githubusercontent.com/assets/6261591/12742432/a5601de8-c9c0-11e5-9108-dc17fb12a906.png)

**Comment by mikollo** [comment]
https://github.com/lwansbrough/react-native-camera/issues/134

You cant render <Camera /> if You detect that user disabled acces for camera 😉

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
