### ISSUE TITLE
Camera Not Authorize issue

### ISSUE THREAD

**Issue by isaaclem** [react-native-community/react-native-camera#1740]
### Which implementation are you using
RNCamera

### Expected behaviour
Camera should be popping up

### Actual behaviour
Instead showing "Camera Not Authorize"

### Environment
"react": "^16.4.1",
"react-native": "^0.56.0"

Android 4.1

### react-native-camera
**Version**: 1.1.4

**Comment by cagataycali** [comment]
Please give more information about your issue

**Comment by younessiysa** [comment]
Set the RNcamera props  captureAudio={false}

**Comment by n1ru4l** [comment]
If you still experience this issue with the newest version of `react-native-camera` please open a new issue.
