### ISSUE TITLE
Cant compile 

### ISSUE THREAD

**Issue by nes123** [react-native-community/react-native-camera#1746]
error: package com.google.android.gms.vision does not exist

my relevant build.gradle section looks like that:
```
implementation(project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
        implementation 'com.android.support:exifinterface:27.+'
        implementation('com.google.android.gms:play-services-vision:15.0.1') {
            force = true;
        }
    }
```

**Comment by n1ru4l** [comment]
Please checkout the documentation https://github.com/react-native-community/react-native-camera#android

Feel free to open a new issue if it is not clear enough.
