### ISSUE TITLE
Meet some issues running in android

### ISSUE THREAD

**Issue by soliury** [react-native-community/react-native-camera#175]
I have meet some issues running in android, I use Samsung Galaxy s6 API 23 in Genymotion:

```
Warning: Native component for "RCTCamera" does not exist
```

And it can run, but , the camera view is empty, I mean it have nothing, just white.

**Comment by lwansbrough** [comment]
Thanks for reporting. This is an issue that's being tracked in multiple places. I'll try and have a fix tonight (8+ hours away from now.)

**Comment by Phoenix1708** [comment]
You are very likely used npm to installed the out of date version i.e not what's on the master branch @soliury see #177 it will probably give you an idea.

@lwansbrough I guess the the README needs to be updated now otherwise there will be more such issue raised.

**Comment by soliury** [comment]
@lwansbrough @Phoenix1708 I have install the latest master code, but failed.  I mean, when I meet the issue, I have installed the latest code from master, and then show:

```
Warning: Native component for "RCTCamera" does not exist
```

And today, I reinstall the package from the new master, but failed. 

![image](https://cloud.githubusercontent.com/assets/5032079/12805022/340c9972-cb33-11e5-8cd6-0c2625b06619.png)

**Comment by Phoenix1708** [comment]
Hi @soliury , do you mind to show me how did you installed the library ?

**Comment by soliury** [comment]
Just like this:

```
npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save
rnpm link react-native-camera
```

And then, I check the code, it have linked.

**Comment by Phoenix1708** [comment]
If you put ```"react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git"``` in your package.json as one of the dependencies and run ``` npm install ``` you should be able to get the correct version and the required file.

**Comment by lwansbrough** [comment]
I've had problems with rnpm setting the include path of the native modules in settings.gradle. Make sure these paths are set correctly.

**Comment by kwngo** [comment]
Does react-native-camera only work with devices running API 23?

**Comment by benjamin-wss** [comment]
Heya, had a similar issue today when using it. Apparently, the react-native link command did not update the gradle file here : `./android/app/build.gradle`

I had to add the `compile project(':react-native-camera')` myself inside, then it worked.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
