### ISSUE TITLE
How to hide the another permissionDialog in android?

### ISSUE THREAD

**Issue by YouCii** [react-native-community/react-native-camera#1750]
### Which implementation are you using
*RNCamera*

### Steps to reproduce
1. npm i --s react-native-camera
2. react-native link react-native-camera
3. other build.gradle modifications

### Does it work with Expo Camera?
I don't know.

### Expected behaviour
Only show the dialog which actually contains agree and disagree buttons.

### Actual behaviour
It show a dialog(contains the 'permissionDialogTitle/Message') before showing the dialog which actually contains agree and disagree buttons.

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: Android 7.1.1

### react-native-camera
**Version**:     "react-native-camera": "^1.1.4"

**Comment by darekg11** [comment]
Bumping, I would also like to know that.

**Comment by n1ru4l** [comment]
This is currently not possible. However this seems like a reasonable feature and we are happy to accept pull requests for it.

A possible implementation could be a new property (`shouldAskForPermissions`) which is a function that returns a `Promise` which resolves to either `true` or `false`. Depending on the result we could then decide whether the dialog with the `agree` and `disagree` buttons should be showed or not.

The function should be called before this line:

https://github.com/react-native-community/react-native-camera/blob/e79cd566ab61e31105dddef0193d7dd351a14d59/src/RNCamera.js#L413

If anyone is interested in implementing this I would encourage you to also add documentation to `RNCamera.md`.

**Comment by darekg11** [comment]
I think what @YouCii meant and what I meant is to disable showing the `Alert` that happens before actual dialog happens. On my Huawei P8Lite running Android 6.0, things are happening in following order:  
1. Alert showing just `permissionDialogTitle` and `permissionDialogMessage` pops up
2. Actual native dialog showing required permission and `Agree`/`Disagree` pops up.

Is there possibility to remove 1) and only show 2)? I am taking a looking through source code now and I can't anything that would show that additional alert in 1) so I guess this must be default behavior of Android?
