### ISSUE TITLE
Expected camera component error when pausePreview is called before takePictureAsync on android

### ISSUE THREAD

**Issue by mshibl** [react-native-community/react-native-camera#1753]
### Which implementation are you using
RNCamera - **android** (works on iOS)

### Steps to reproduce
1. Call camera.pausePreview()
2. Call camera.takePictureAsync()
3. catch and log error: `Expected camera component`

```    
takePicture = async () => {
        try {
            if (this.camera) {
                this.camera.pausePreview();

                const data = await this.camera.takePictureAsync();

                // ... use picture data
            }
        } catch (err) {
            console.error(err);
        }
    };
```

### Expected behaviour
The camera should pause the preview, and then take the picture 

### Actual behaviour
Throws an error: `Error: takePictureAsync: Expected a Camera component`

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: Android 6.0

### react-native-camera
**Version**: 1.2.0

**Comment by staafl** [comment]
Same scenario, same error - Android 8, react-native-camera 1.2.0

**Comment by inventsys** [comment]
Same problem here. Any solution?

**Comment by niv-breez** [comment]
happen to me also, does anyone found a fix ?

**Comment by winadiw** [comment]
happened to me.. Any fix?

**Comment by FilippoArgenti** [comment]
Can confirm this is still happening on v3.3.0
When I call .takePictureAsync without .pausePreview first it works.

**Comment by Nervado** [comment]
Same here:

RNCamera: 3.9.0
RN: 0.61.4

Plattaform: Android

` async function takePicture() {
    try {
      if (camera) {
        // Pause the camera preview

        // Update the state to indicate loading
        setLoading(true);

        // Set the options for the camera
        const options = {
          base64: true,
        };

        // Get the base64 version of the image
        camera.pausePreview();
        const data = await camera.takePictureAsync(options);

        // Call the identify function
        identifyImage(data.base64);
      }
    } catch (error) {
      Alert.alert('Something whent wrong! =(');
    }
}`

**Comment by Nervado** [comment]
Same here:

RN: 0.61.4
RNCamera: 3.9.0
Plattaform: Android 

`` async function takePicture() {
    try {
      if (camera) {
        // Pause the camera preview

        // Update the state to indicate loading
        setLoading(true);

        // Set the options for the camera
        const options = {
          base64: true,
        };

        // Get the base64 version of the image
        camera.pausePreview();
        const data = await camera.takePictureAsync(options);

        // Call the identify function
        identifyImage(data.base64);
      }
    } catch (error) {
      Alert.alert('Something whent wrong! =(');
    }
  }
``

**Comment by TnRc** [comment]
Has this been resolved?
