### ISSUE TITLE
can't read "UTF-8"

### ISSUE THREAD

**Issue by dekemega** [react-native-community/react-native-camera#1771]
i have some official documentation that has qr code but it's not using English character .. so i need to decode them using uft-8

this is the qr

![2018](https://user-images.githubusercontent.com/23610404/44944529-5760ab00-ade1-11e8-8574-52131e862221.jpg)

the result

![screenshot_2018-09-01-12-13-59](https://user-images.githubusercontent.com/23610404/44944532-66dff400-ade1-11e8-847f-3e7ab7506ccd.png)

**Comment by n1ru4l** [comment]
@dekemega Please feel free to send a pull request that implements the feature.

**Comment by SimonErm** [comment]
I think that's releated to ZXing(take a look here https://github.com/zxing/zxing/issues/708 and here https://stackoverflow.com/questions/2489048/qr-code-encoding-and-decoding-using-zxing). Have you tried using [Google Vision](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md) for scanning?
