### ISSUE TITLE
android vivoY67 can't read code-39 or code-128

### ISSUE THREAD

**Issue by sybil052** [react-native-community/react-native-camera#1774]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our [Migration guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md)

### Which implementation are you using
<RNCamera
                                ref={(cam) => {
                                    this.camera = cam;
                                }}
                                style={styles.cameraStyle}
                                barcodeScannerEnabled={true}
                                onBarCodeRead={
                                    this.barcodeReceived
                                }
                                flashMode={openFlash ? RNCamera.Constants.FlashMode.on : RNCamera.Constants.FlashMode.off}
                                // torchMode={openFlash ? 'on' : 'off'}
                            >

### Steps to reproduce
1.
2.
3.

### Expected behaviour
 function onBarCodeRead can return barcode.

### Actual behaviour
 when vivoY67 read code-39 or code-128, function onBarCodeRead doesn't work.

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: vivo Y67 Android 6.0

### react-native-camera
**Version**: "react-native-camera": "git+https://github.com/react-native-community/react-native-camera.git"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by nadzic** [comment]
Did you get black screen or simply did not read the code?

**Comment by sibelius** [comment]
try latest version

it uses MLKit

**Comment by abhi-nahi** [comment]
Do I need to integrate the firebase ML toolkit to use this feature ???
