### ISSUE TITLE
Tap To Focus question

### ISSUE THREAD

**Issue by rt2zz** [react-native-community/react-native-camera#178]
Does `defaultOnFocusComponent` just disable visual feedback, but preserve the tap to focus functionality?

I am looking into potential android implementation, but am not sure what controls to expose via props, and what the default behavior should be.

**Comment by lwansbrough** [comment]
I really dislike this API - I'm going to remove it for `1.0.0` - I would like to have a property `renderFocusArea` which accepts a function that accepts coordinates points, and leaves the user to return an instantiated component which will be shown at those coordinates. Like so:

```javascript
<Camera renderFocusArea={(coords) => <MyFocusBox style={{top: coords.x - 50, left: coords.y - 50, height: 100, width: 100}}/>}/>
```

Coords would be relative to the size of the camera preview, so there wouldn't be any translation required for the user.

**Comment by lwansbrough** [comment]
I think then that there wouldn't need to be a native API for the focus area, just an event that is triggered when the focus area is changed, with coordinates attached. Then we can handle that event inside the Camera component.

**Comment by rt2zz** [comment]
I like that. I would propose we should also:
- default to a reasonable tap to focus region
- allow disabling tap to focus either by setting renderFocusArea={false} or exposing a separate prop

**Comment by lwansbrough** [comment]
I think tap to focus enabled by default makes sense, so in that case `renderFocusArea={false}` would make sense, yeah.

The same could be done for face detection where a bounding box and coordinates are sent back to a `renderFaceDetectionArea(coords, size)` where coords are now the top left edge of the region, and size is the size of the region.

**Comment by lschmierer** [comment]
Tap To Focus is not implemented in Android at all, right? And on iOS?

**Comment by lazarte** [comment]
Below code work on IOS but not on android?

```
<Camera
    onFocusChanged={this.onFocusChanged.bind(this)}
    defaultOnFocusComponent={true}
    ref = {(cam) => {this.camera = cam}}
    style = {styles.preview}
    captureAudio = {false}
    type = {Camera.constants.Type.back}>
</Camera>
```

**Comment by ivosabev** [comment]
Version 0.6.0 the default tap-to-focus doesn't work in Android.

**Comment by LEEY19** [comment]
@lazarte hi, do you know if the code you posted already works on android?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

**Comment by ahsan-storm** [comment]
Please reopen this issue

**Comment by ahsan-storm** [comment]
Tap to focus still not working in android
