### ISSUE TITLE
Captured image is getting cropped in samsung j7

### ISSUE THREAD

**Issue by ThabrezAhmed** [react-native-community/react-native-camera#1782]
### Which implementation are you using
RCTCamera

### Steps to reproduce
1. Try the sample RN camera in j7

### Expected behaviour
Captured image should have the viewport aspect ratio

### Actual behaviour
Image got cropped in the top and bottom part

### Environment
- **React Native version**: 0.44
- **React Native platform + platform version**: Android 6.0.1

### react-native-camera
**Version**: npm version : 4.6.1

**Comment by djleonskennedy** [comment]
@ThabrezAhmed **RNCamera** should be used, **RCTCamera** is deprecated

**Comment by ThabrezAhmed** [comment]
@djleonskennedy I even tried RNCamera issue still exists

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
