### ISSUE TITLE
Async error java takePictureAsync()

### ISSUE THREAD

**Issue by rusliabdulgani** [react-native-community/react-native-camera#1785]
### Warning
RCTCamera is **DEPRECATED** on v1.0.0 follow our [Migration guide](https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md)

### Which implementation are you using

RNCamera

### Steps to reproduce
1. Open Camera
2. camera.takePictureAsync()
3. force closed (sometimes OK)

### Does it work with Expo Camera?
Check usage with Expo - https://github.com/react-native-community/react-native-camera/blob/master/docs/Expo_Usage.md
You should open an issue there as well, so we can cooperate in a solution.

### Expected behaviour
After execute promise takePictureAsync() it should be take picture

### Actual behaviour
After execute promise/await takePictureAsync() app force closed.
if i used crashlytics it found error like this.

`Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:325)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)`

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: Android version 7.1.1 & 5.1.1

### react-native-camera
**Version**: "master"

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by rusliabdulgani** [comment]
hi all, 

anybody know this issue?

**Comment by SimonErm** [comment]
do you use fixOrientation option?

**Comment by benhartouz** [comment]
+1

**Comment by n1ru4l** [comment]
Closing due to missing feedback.
