### ISSUE TITLE
Black screen after first scanning on Android 7.0, 8.1

### ISSUE THREAD

**Issue by nadzic** [react-native-community/react-native-camera#1797]
### Which implementation are you using

*RNCamera* 

### Steps to reproduce
1. Coming to scanning screen (We are using react-navigation)
2. Scan product bacode
3. After scanning black screen

### Does it work with Expo Camera?
We did not try yet expo camera.

### Expected behaviour
On iOS it works normally, after scanning we can scan normally next product. 

### Actual behaviour
On Android after I scan one product it show black screen and I cannot scan next product. If I go to next screen and return back (to reset navigation state) then I can scan next product again, but after this scanning getting again black screen. So, all the time after one scan we get black screen.

### Environment
- **React Native version**: 0.55
- **React Native platform + platform version**: Android 7.0, Android 8.1

### react-native-camera
**Version**: 1.2.0 (tried also 1.1.2)

### Example of our component

https://pastebin.com/gaSpfRLi

- We already tried to remove SideMenu and other View that RNCamera was top wrapper, did not help,

- We also tried without variables (disable/enable camera): `onBarCodeRead={(!currentKitchenVisible && rnCameraEnable) ? this.onBarCodeRead : null}`,

- We also tried downgrade camera, upgrade react-native from 0.52 to 0.55, did not help.

- We are also using the exact version of sdk build tools as specificed in instructions for installing

What else should we try?

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by SimonErm** [comment]
Can you tell me what your this.onBarCodeRead does? Should pop up a modal or do you just save scanned data?

**Comment by GaneshSaiKumar** [comment]
Duplicate of #1686
