### ISSUE TITLE
react-native link destroys xcodeproj file

### ISSUE THREAD

**Issue by JslinSir** [react-native-community/react-native-camera#1799]
when  i use  react-native link react-native-camera  

the project hangs    and  this file project.pbxproj No conflict
![image](https://user-images.githubusercontent.com/30678791/45686584-62586100-bb7f-11e8-930f-6514e0f398e3.png)

**Comment by SimonErm** [comment]
related https://github.com/react-native-community/react-native-camera/pull/1762 ?

**Comment by sibelius** [comment]
use autolinking with v3
