### ISSUE TITLE
Request: ability to create animated .webp or .gif files with react-native-camera

### ISSUE THREAD

**Issue by sunweiyang** [react-native-community/react-native-camera#1803]
### Which implementation are you using
*RNCamera*

### Description
This will allow developers to use react-native-camera for features such as moving profile pictures, something similar to [iOS Live Photos](https://support.apple.com/en-us/HT207310), etc. Duration and/or number of frames would probably be specified as options.

**Comment by n1ru4l** [comment]
This seems to be out of scope of this package. Feel free to create a react-native library that converts mp4/m4v to gif/webp
