### ISSUE TITLE
> version 1.1.4 don't support <= iOS 8.0

### ISSUE THREAD

**Issue by flybluewolf** [react-native-community/react-native-camera#1806]
AVCaptureSessionPreset3840x2160 only is available on  iOS 9.0+，so please update react-native-camera.podspec and change to s.platform  = :ios, '9.0'.

**Comment by flybluewolf** [comment]
update title

**Comment by n1ru4l** [comment]
@flybluewolf @jgfidelis @sibelius Should be either bump the version or make the code backwards compatible?
