### ISSUE TITLE
doNotSave missing in TypeScript definition

### ISSUE THREAD

**Issue by tvand7093** [react-native-community/react-native-camera#1810]
### Which implementation are you using

*RNCamera*

### Steps to reproduce
1. Install package
2. Attempt to call `takePictureAsync` with specifying `doNotSave` in options

### Does it work with Expo Camera?
Typing issue, so not really applicable.

### Expected behaviour
It should exist in the definition

### Actual behaviour
It does not exist in the definition

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: Cross-Platform

### react-native-camera
**Version**: 1.2.0 (`npm`)

**Comment by jgcmarins** [comment]
hi @tvand7093 thanks for this issue.
Could you please try `master` branch? Thanks.
