### ISSUE TITLE
ios when record use 720p but the video being 1440x1080

### ISSUE THREAD

**Issue by meiqi1992** [react-native-community/react-native-camera#1817]
# Bug Report
**To Do First**
- [ ] Did you try latest release?
- [ ] Did you try master?
- [ ] Did you look for existing matching issues?

**Related Modules**

**Platforms**

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:

**Description/Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by n1ru4l** [comment]
Could you please provide the required information the form provides? I am going to close this issue. Feel free to reopen it once you can provide more information.
