### ISSUE TITLE
Error: An error occurred while recording a video.

### ISSUE THREAD

**Issue by watadarkstar** [react-native-community/react-native-camera#1823]
**Description**

Some of our users (iPhone X iOS 12.0) get this error sometimes where the camera cannot record the video, the error says: `Error: An error occurred while recording a video.] framesToPop: 1, code: 'E_RECORDING_FAILED'`. 

I'm just wondering what might cause this error? Is the camera locked up or something? I saw the code that throws this error and I'm wondering why it might throw such an error. For the effected users it probably only happens less than 20% of the time.

**Relevant line of code:** 

https://github.com/react-native-community/react-native-camera/blob/e2c49e04eb4c3e1bb897828cad575b068b5e5183/ios/RN/RNCamera.m#L921

**Version**

"react-native-camera": "^1.1.4", 
AND
"react-native-camera": "^1.3.0",

**Full log:**

`Instabug - REACT LOG: 2018-09-27 12:49:33.384 [error][tid:com.facebook.react.JavaScript] { [Error: An error occurred while recording a video.] framesToPop: 1, code: 'E_RECORDING_FAILED', nativeStackIOS: [ '0 flyreel 0x00000001023a74a0 RCTFBQuickPerformanceLoggerConfigureHooks + 699744', '1 flyreel 0x0000000102350654 RCTFBQuickPerformanceLoggerConfigureHooks + 343828', '2 flyreel 0x0000000102402ec8 RCTFBQuickPerformanceLoggerConfigureHooks + 1075080', '3 AVFoundation 0x000000020b38771c <redacted> + 88', '4 AVFoundation 0x000000020b3877b0 <redacted> + 36', '5 libdispatch.dylib 0x0000000204cd36c8 <redacted> + 24', '6 libdispatch.dylib 0x0000000204cd4484 <redacted> + 16', '7 libdispatch.dylib 0x0000000204cb3b44 <redacted> + 1012', '8 CoreFoundation 0x000000020522a1bc <redacted> + 12', '9 CoreFoundation 0x0000000205225084 <redacted> + 1964', '10 CoreFoundation 0x00000002052245b8 CFRunLoopRunSpecific + 436', '11 GraphicsServices 0x0000000207498584 GSEventRunModal + 100', '12 UIKitCore 0x0000000231b4f558 UIApplicationMain + 212', '13 flyreel 0x0000000102058b98 flyreel + 19352', '14 libdyld.dylib 0x0000000204ce4b94 <redacted> + 4' ], userInfo: { NSUnderlyingError: { code: '-16418', nativeStackIOS: [ '0 flyreel 0x00000001023a74a0 RCTFBQuickPerformanceLoggerConfigureHooks + 699744', '1 flyreel 0x00000001023a768c RCTFBQuickPerformanceLoggerConfigureHooks + 700236', '2 flyreel 0x0000000102350654 RCTFBQuickPerformanceLoggerConfigureHooks + 343828', '3 flyreel 0x0000000102402ec8 RCTFBQuickPerformanceLoggerConfigureHooks + 1075080', '4 AVFoundation 0x000000020b38771c <redacted> + 88', '5 AVFoundation 0x000000020b3877b0 <redacted> + 36', '6 libdispatch.dylib 0x0000000204cd36c8 <redacted> + 24', '7 libdispatch.dylib 0x0000000204cd4484 <redacted> + 16', '8 libdispatch.dylib 0x0000000204cb3b44 <redacted> + 1012', '9 CoreFoundation 0x000000020522a1bc <redacted> + 12', '10 CoreFoundation 0x0000000205225084 <redacted> + 1964', '11 CoreFoundation 0x00000002052245b8 CFRunLoopRunSpecific + 436', '12 GraphicsServices 0x0000000207498584 GSEventRunModal + 100', '13 UIKitCore 0x0000000231b4f558 UIApplicationMain + 212', '14 flyreel 0x0000000102058b98 flyreel + 19352', '15 libdyld.dylib 0x0000000204ce4b94 <redacted> + 4' ], userInfo: {}, message: 'underlying error', domain: 'NSOSStatusErrorDomain' }, NSLocalizedRecoverySuggestion: 'Try recording again.', AVErrorRecordingSuccessfullyFinishedKey: false, NSLocalizedDescription: 'Cannot Record' }, domain: 'AVFoundationErrorDomain', line: 18, column: 1599, sourceURL: 'https://d1wp6m56sqw74a.cloudfront.net/%40flyreel%2Fflyreel%2F0.1.0%2Fe71783c7d8e43d9320fcbdb91e9d4620-26.0.0-ios.js' }`

**Comment by SimonErm** [comment]
Maybe related: https://github.com/react-native-community/react-native-camera/issues/1778

**Comment by watadarkstar** [comment]
This bug happened again on the latest version of rn-camera:

```
Instabug - REACT LOG: 2018-10-08 20:23:22.930 [error][tid:com.facebook.react.JavaScript] { [Error: An error occurred while recording a video.] framesToPop: 1, code: 'E_RECORDING_FAILED', nativeStackIOS: [ '0 flyreel 0x0000000100ae307c GMSx_AbslInternalSpinLockWake + 1001404', '1 flyreel 0x0000000100abdd80 GMSx_AbslInternalSpinLockWake + 849088', '2 flyreel 0x0000000100be5de8 _ZN5folly6detail15str_to_integralIxEENS_8ExpectedIT_NS_14ConversionCodeEEEPNS_5RangeIPKcEE + 796296', '3 AVFoundation 0x000000018960dd74 <redacted> + 88', '4 AVFoundation 0x000000018960de08 <redacted> + 36', '5 libdispatch.dylib 0x00000001833e4b24 <redacted> + 24', '6 libdispatch.dylib 0x00000001833e4ae4 <redacted> + 16', '7 libdispatch.dylib 0x00000001833f16e0 <redacted> + 1012', '8 CoreFoundation 0x0000000183a9b070 <redacted> + 12', '9 CoreFoundation 0x0000000183a98bc8 <redacted> + 2272', '10 CoreFoundation 0x00000001839b8da8 CFRunLoopRunSpecific + 552', '11 GraphicsServices 0x000000018599b020 GSEventRunModal + 100', '12 UIKit 0x000000018d99978c UIApplicationMain + 236', '13 flyreel 0x0000000100734274 flyreel + 33396', '14 libdyld.dylib 0x0000000183449fc0 <redacted> + 4' ], userInfo: { NSUnderlyingError: { code: '-16418', nativeStackIOS: [ '0 flyreel 0x0000000100ae307c GMSx_AbslInternalSpinLockWake + 1001404', '1 flyreel 0x0000000100ae3268 GMSx_AbslInternalSpinLockWake + 1001896', '2 flyreel 0x0000000100abdd80 GMSx_AbslInternalSpinLockWake + 849088', '3 flyreel 0x0000000100be5de8 _ZN5folly6detail15str_to_integralIxEENS_8ExpectedIT_NS_14ConversionCodeEEEPNS_5RangeIPKcEE + 796296', '4 AVFoundation 0x000000018960dd74 <redacted> + 88', '5 AVFoundation 0x000000018960de08 <redacted> + 36', '6 libdispatch.dylib 0x00000001833e4b24 <redacted> + 24', '7 libdispatch.dylib 0x00000001833e4ae4 <redacted> + 16', '8 libdispatch.dylib 0x00000001833f16e0 <redacted> + 1012', '9 CoreFoundation 0x0000000183a9b070 <redacted> + 12', '10 CoreFoundation 0x0000000183a98bc8 <redacted> + 2272', '11 CoreFoundation 0x00000001839b8da8 CFRunLoopRunSpecific + 552', '12 GraphicsServices 0x000000018599b020 GSEventRunModal + 100', '13 UIKit 0x000000018d99978c UIApplicationMain + 236', '14 flyreel 0x0000000100734274 flyreel + 33396', '15 libdyld.dylib 0x0000000183449fc0 <redacted> + 4' ], userInfo: {}, message: 'underlying error', domain: 'NSOSStatusErrorDomain' }, NSLocalizedRecoverySuggestion: 'Try recording again.', AVErrorRecordingSuccessfullyFinishedKey: false, NSLocalizedDescription: 'Cannot Record' }, domain: 'AVFoundationErrorDomain', line: 16, column: 1614, sourceURL: '/var/containers/Bundle/Application/9DA2436E-1B91-4E3B-9248-41772CF96481/flyreel.app/main.jsbundle' }
```

**Comment by watadarkstar** [comment]
Can anyone help with why this might be happening @n1ru4l @SimonErm @jgfidelis ? Just got the error again:

```
iOS 11.3
iPhone 6
react-native-camera: "^1.3.0"
```

Log is above ^

**Comment by SimonErm** [comment]
Maybe related: https://stackoverflow.com/questions/3495879/error-when-capturing-camera-and-audio-input#3498981 . Do you youse GoogleVision features?

**Comment by SimonErm** [comment]
Can you test if this fix it? https://github.com/SimonErm/react-native-camera/tree/fix/iOSCrashCannotRecord

**Comment by watadarkstar** [comment]
@SimonErm Thank you for responding! We do not use GoogleVision. We do upload the image to a server which uses computer vision to analyze the image.

**Comment by watadarkstar** [comment]
@SimonErm Sure I can give that a try.
