### ISSUE TITLE
Android: Error while updating property 'pictureSize'

### ISSUE THREAD

**Issue by toeyanuntachai** [react-native-community/react-native-camera#1826]
# Bug Report

**Versions**

"react-native-camera": "^1.3.0",
"react-native": "0.56.0"
"react-native-navigation": "^2.0.2510",

**Description/Current Behaviour**

I found this error when I'm navigated to the screen that makes for using the RNCamera, then i found this Error while updating property 'pictureSize' of a view managed by: RNCamera

![23442](https://user-images.githubusercontent.com/7608232/46276153-5f02a380-c589-11e8-83e4-866d56132e94.jpg)
Here is my code
![image](https://user-images.githubusercontent.com/7608232/46276557-a9385480-c58a-11e8-8379-12811fe399e9.png)

**Comment by toeyanuntachai** [comment]
@Ratnesh-Kumar Yes, I have resolved this issue, because I have installed some package that using the same dependency "com.google.android.cameraview", so looks like it's will confuse to resolve the correct package.

P.S. Sorry for English, I'm trying to practice it.

**Comment by Ratnesh-Kumar** [comment]
I am trying firebase with RNCamera getting this error, trying to resolve.

**Comment by n1ru4l** [comment]
@Ratnesh-Kumar We cannot help you with clashing dependencies. It seems like you  have to force a specific version for all resolved `com.google.android.cameraview` dependencies in your `build.gradle`.

**Comment by sibelius** [comment]
we need more docs about this topic

**Comment by n1ru4l** [comment]
@Ratnesh-Kumar Can you please provide a reproduction repository so I can figure out a solution that can be documented?
