### ISSUE TITLE
 QR code inverted color doesn't reading, how to read it?

### ISSUE THREAD

**Issue by jorgeluisrezende** [react-native-community/react-native-camera#1827]
# Question
**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

I have a qr code with the colors inverted, and i need to read it, theres anyway to do that?
i found issues here that get this point, but there's no solution in it.
**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by Sjiep** [comment]
@jorgeluisrezende I added this feature and it got merged into master (#1896). Because it uses the google vision API it is currently Android only.

[See docs.](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#android-googlevisionbarcodemode)
