### ISSUE TITLE
RNCamera video quality option Error: Error retrieving camcorder profile params

### ISSUE THREAD

**Issue by AsocialCoder** [react-native-community/react-native-camera#1833]
I am using RNCamera and If i use quality option return to me this error;

> Possible Unhandled Promise Rejection (id: 0):
> Error: Error retrieving camcorder profile params
> Error: Error retrieving camcorder profile params
> 

```
 const options = {quality:RNCamera.Constants.VideoQuality["480p"]}
        const { uri, codec = "mp4"  } = await this.camera.recordAsync(options);
        this.setState({ recording: false, processing: true });
        const type = `video/${codec}`;
        const data = new FormData();
        data.append("video", {
          name: "mobile-video-upload",
          type,
          uri
        });
        console.log(type);
}
```

**Comment by AsocialCoder** [comment]
what kind of information do you want?

**Comment by AsocialCoder** [comment]
> I am using RNCamera and If i use quality option return to me this error;
> 
> > Possible Unhandled Promise Rejection (id: 0):
> > Error: Error retrieving camcorder profile params
> > Error: Error retrieving camcorder profile params
> 
> ```
>  const options = {quality:RNCamera.Constants.VideoQuality["480p"]}
>         const { uri, codec = "mp4"  } = await this.camera.recordAsync(options);
>         this.setState({ recording: false, processing: true });
>         const type = `video/${codec}`;
>         const data = new FormData();
>         data.append("video", {
>           name: "mobile-video-upload",
>           type,
>           uri
>         });
>         console.log(type);
> }
> ```

**Comment by reime005** [comment]
The more you can provide, the easier to reproduce. Infos about the device mainly

**Comment by sibelius** [comment]
fixed here https://github.com/react-native-community/react-native-camera/pull/1835

try master
