### ISSUE TITLE
Quick Preview Capture Mode to Beat Slow onPictureTaken on Android

### ISSUE THREAD

**Issue by FullstackJack** [react-native-community/react-native-camera#1836]
# Feature-Request

**Describe the Feature**
Despite recent modifications to improve image capture on Android, camera capture is still slow. For applications needing very fast capture before launching a new screen (i.e. Snapchat, Instagram), we should consider offering a capture mode to enable the use of PreviewCallback.

**Possible Implementations**
There is already an implementation of this for CameraKit-Android. Since this library is now included with Expo, we should consider porting that code over to this package instead of splitting the community over this issue.
https://github.com/CameraKit/camerakit-android/blob/master/camerakit-core/src/main/api16/com/wonderkiln/camerakit/Camera1.java#L450

**Related Issues**
There are lots of closed issues surrounding this, but none of them really fixed the problem. Let's hope this solves it.
https://github.com/react-native-community/react-native-camera/issues/942
https://github.com/react-native-community/react-native-camera/issues/1000
https://github.com/react-native-community/react-native-camera/issues/768

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by n1ru4l** [comment]
@FullstackJack Are you interested in implementing this feature?

**Comment by bcalik** [comment]
Its still so slow on Android despite messing with all RNCamera options. I hope someone will fix it.

**Comment by n1ru4l** [comment]
@bcalik Are you interested in fixing it?

**Comment by cesartotvs** [comment]
@n1ru4 Got it, I'm interested in fixing this issue.

**Comment by cesartotvs** [comment]
@n1ru4l  Got it, I'm interested in fixing this issue.

**Comment by FullstackJack** [comment]
I'm currently building a prototype with video player and focusing on that at the moment, but I'm interested in helping out when I have the time (unless others have already pitched in what I'm suggesting.

**Comment by cesartotvs** [comment]
Just a quick note I will not be adding any new features, but only fixing the performance issues.

**Comment by n1ru4l** [comment]
How would this be implemented?

You pass an option to `takePicture` and the first value of uri will be the "preview". Then afterwards we will fire a event that includes the url to the actual picture?

**Comment by sibelius** [comment]
Having an event could make sense, we can have more events

**Comment by n1ru4l** [comment]
Is it even possible get a preview frame and take photo at once? camerakit-android only supports the one or the other.

**Comment by sibelius** [comment]
Not sure, we should try

**Comment by n1ru4l** [comment]
A big issue is also that until the `onPictureTaken`/`onPreviewFrame` callback is called almost 2 seconds pass. I quickly updated the code to use `onPreviewFrame`, but still it does not feel more performant 😕. Seems like it takes a long time until the communication over the bridge actually reaches the java code...

**Comment by sibelius** [comment]
are you sending event before any image processing?

**Comment by n1ru4l** [comment]
@sibelius check this out: https://github.com/react-native-community/react-native-camera/compare/master...n1ru4l:test-fast-mode

**Comment by sibelius** [comment]
I think the problem is the imagem processing part

**Comment by n1ru4l** [comment]
Nah I do not think so.

Takes a long time until this is actually logged: https://github.com/react-native-community/react-native-camera/compare/master...n1ru4l:test-fast-mode#diff-12e8b1a707fb43be92dea959a0b95215R474 (after pressing the capture button)

**Comment by stoffern** [comment]
I think this is related to a problem in RN core, i made a custom module to send string data of 3-4 mb and the write / read times are high. 
1mb write = approx 500ms
1mb read = approx 500ms

problem with slow speeds are also reported in react-native-fs and other modules that require "big" data sendt as string.

**Comment by mcgloneleviROOT** [comment]
From what I can tell, it looks like the Google's CameraView library is used under-the-hood on Android.  There is an issue on the CameraView GitHub repo from 2 years ago saying that the library takes 1-3 seconds to save the image:

https://github.com/google/cameraview/issues/86

My guess is that is the root cause of the slow saves on Android.

**Comment by bbeckk** [comment]
I have the same issue. Very slow in android. Has anybody solved it?

**Comment by AntonIvarsson** [comment]
We hade this problem even though we run our app on ios(staff tool). We tried switching to react native camera kit from wix, which worked like a charm. For everyone who is struggling with this: 
https://github.com/wix/react-native-camera-kit

**Comment by sibelius** [comment]
can you try this pull request https://github.com/react-native-community/react-native-camera/pull/2505

**Comment by cristianoccazinsp** [comment]
The secret is to use `skipProcessing: true` and `fixOrientation: false`. The camera is still a bit slow to open, but the capture speed on flagship devices stays below 1 second with those two options. The later is required because fixOrientation actually breaks it if skip processing is true.

Also as said above, using the preview itself can be even faster, but be ready to lose some camera features on powerful cameras (lightning and post processing).

**Comment by lucasluca** [comment]
i was using this config:
const options = { quality: 0.1, base64: false, forceUpOrientation: true, fixOrientation: true, skipProcessing: true };

and then i removed {forceUpOrientation: true, fixOrientation: true}, from this object and got it working really fast

**Comment by hui05** [comment]
@lucasluca  this can't solve this problem

**Comment by hui05** [comment]
@stale  the problem is not solve, why you close this problem

**Comment by fabriziobertoglio1987** [comment]
in an effort to bump up this thread I propose an alternative of using directly the camera api.
You can write a [Native UIComponent][2] and implement the following solution from [The Busy Coder's Guide to Android][1] chapter `Using the Camera via 3rd-Party Apps`

>The easiest way to take a picture is to not take the picture yourself, but let somebody else do it. The most common implementation of this approach is to use an ACTION_IMAGE_CAPTURE Intent to bring up the user’s default camera application, and let it take a picture on your behalf. In theory, this is fairly simple:

* You call `startActivityForResult()` on an `ACTION_IMAGE_CAPTURE` Intent 
* You either get a thumbnail photo back or — if you provided `EXTRA_OUTPUT` as an extra on the `ACTION_IMAGE_CAPTURE` Intent — a full-sized photo should be written to where you designated in `EXTRA_OUTPUT`

>Setting the Theme
```xml
<activity android:name= ".MainActivity" android:label= "@string/app_name" android:theme= "@android:style/Theme.Translucent.NoTitleBar" > 
   <intent-filter> 
      <action android:name= "android.intent.action.MAIN" /> 
       <category android:name= "android.intent.category.LAUNCHER" /> 
    </intent-filter>
<activity/>
```

as I believe most of the react-native apps do not need access to the camera api and for those type of application you may want to consider writing native solution in android or ios.

There is a [pull request][https://github.com/react-native-community/react-native-camera/pull/2505] and may be a good idea moving the discussion there.

Additionally the camera has many other weaknesses, for example it is not possible to have a smooth zoom functionality so it may take more time to build a camera app with ReactNative then a native Android App. 

On this basis it would be really useful having a 100% functioning package (as from the above specs), easy to install and stable to use the camera via third party applications

[1]: https://commonsware.com/Android/
[2]: https://facebook.github.io/react-native/docs/native-components-android

**Comment by hui05** [comment]
it means  i don't use the react-native-camera, I'll do it by myself

**Comment by fabriziobertoglio1987** [comment]
I personally never experienced this issue, as my understanding skipping the preview can help making the camera work faster, but also using third party camera should not be too much of an hussle. 

an example app is [synced](https://www.synced.to/). They use the third party camera application and it just works perfectly.

It is hard to build a perfect camera app. Their third party camera app has very smooth zoom and fast picture taking

**Comment by pradeep-orbi** [comment]
> I personally never experienced this issue, as my understanding skipping the preview can help making the camera work faster, but also using third party camera should not be too much of an hussle.
> 
> an example app is [synced](https://www.synced.to/). They use the third party camera application and it just works perfectly.
> 
> It is hard to build a perfect camera app. Their third party camera app has very smooth zoom and fast picture taking

How to skip the preview ?
