### ISSUE TITLE
Incompatibilities with Camera2Api. New smartphones uses old Camera API

### ISSUE THREAD

**Issue by fxcosta** [react-native-community/react-native-camera#1837]
# Bug Report
**To Do First**
- [x ] Did you try latest release?
- [x ] Did you try master?
- [x ] Did you look for existing matching issues?

**Related Modules**

**Platforms**

**Versions**
- Android: 8.1
- react-native-camera: ^1.2.0
- react-native: 0.57.0
- react: 16.5.0

**Description/Current Behaviour**
I'm implementing an app that uses a lot of camera features like exposure, manual focus, white balance, etc.

I saw that there is an API for setting depth of focus (this would be equivalent to manual focus?) And I tried to use it. Then I saw that this is only available for phones that have Camera2Api. The real problem is that my phone is a Moto G5S Android 8.1 SDK 27 and it still uses the old camera API.

The library decides whether or not I can use the Camera2Api features based on the SDK and, as I have 27, the library allows me to try to use the features and break when I use the react-native-camera prop useCamera2Api.

Has anyone else had this problem? I'm finding very strange new cellphones with an old api. How can I check now whether or not cell phones actually have access to Camera2Api?

The weirdest? According to the Camera2 Probe app, I would like to set up manual focus. However, debugging the app, I realized that at no time does it use the Camera2 class, but Camera1 instead. If I put the prop useCamera2Api, like I said, the app breaks because my Hardware Level Support Category is Legacy.

**Comment by SimonErm** [comment]
Which targetSDK are you using? I think this could cause the fallback. I am facing the crash on useCamera2Api prop too and going to fix it this week.
