### ISSUE TITLE
[Android] Failed to save image file

### ISSUE THREAD

**Issue by pavermakov** [react-native-community/react-native-camera#1845]
# Bug Report
**To Do First**
- [ ] Did you try latest release?
- [ ] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**
- RCTCamera(deprecated)

**Platforms**
- Android

**Versions**

- Android: 6.0.1
- iOS:
- react-native-camera: 0.10.0
- react-native: 0.51.0
- react: 16.0.0

**Description**

Recently I've switched targetSdkVersion from 22 to 23 and the camera stopped working. I've added a check for permissions, which partially brought camera back to life, however, I am no longer able to take pictures. I get warnings like the one on the screenshot, `failed to save image file`. I know that RCTCamera is already deprecated, but at this point, upgrading the package is not an option (I am terrified of breaking something). Does anyone have any suggestions how to solve this issue?

![screenshot_20181010-140822](https://user-images.githubusercontent.com/10779996/46733039-de822800-cc97-11e8-89ff-17ed6b53b5a4.png)

**Comment by SimonErm** [comment]
Because you're RCTCamera i am not sure if this will be fixed. Can you post Logcat-Logs? Which permissions do you check?

**Comment by pavermakov** [comment]
@SimonErm I've just solved my issue. I had to ask permissions for camera and storage. I used [react-native-permissions](https://github.com/yonahforst/react-native-permissions) for that.
