### ISSUE TITLE
Orientation not working in video 

### ISSUE THREAD

**Issue by DanthonyPabon** [react-native-community/react-native-camera#1846]
>  "react-native": "0.56.0",
>  "react-native-camera": "^1.3.0",
>   node: v10.11.0

# Question
I'm using this to take a video, but the orientation is not working, the video doesn't take the orientation

```
async startRecording() {
    this.setState({ recording: true });
    const data = await this.camera.recordAsync({
      quality: RNCamera.Constants.VideoQuality["480p"],
      orientation:"landscape"
    });
  }
```

**Comment by SimonErm** [comment]
On Android or iOS? The orientation option is just implemented for iOS right now.

**Comment by DanthonyPabon** [comment]
Android

**Comment by SimonErm** [comment]
Like i said, orientation option is just available for iOS right now. Feel free to make a PR.
