### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by juggleru** [react-native-community/react-native-camera#185]
I'm using sample from readme and see just red bordered white screen with small area with text [CAPTURE].

Android 5.0
React-native 0.19

**Comment by ananogal** [comment]
I get exactly the same.

**Comment by agrass** [comment]
I'm with the same problem

**Comment by agrass** [comment]
Hey guys, check this issue #167. It's there a pull request of @rpopovici that solve it

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
