### ISSUE TITLE
Android-> take takePicture:  E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1     Process: com.eazytec.zqtong.gov.baseapp, PID: 4117     java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by pheromone** [react-native-community/react-native-camera#1850]
# Question
**Ask your Question**

Android-> take takePicture:  E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1     Process: com.eazytec.zqtong.gov.baseapp, PID: 4117     java.lang.RuntimeException: An error occurred while executing doInBackground()
**Tags**

 takePicture = async function() {
    if (this.camera) {
      const options = { quality: 0.5, base64: true };
      const response = await this.camera.takePictureAsync(options)
      if(response.base64){
        this.props.dispatch({
          type: 'addressList/cameraScan',
          payload: {
            base64:response.base64
          },
          callback: (response) => {
            if (response.status === 200) {
              var data = response.data
              this.props.dispatch(NavigationActions.navigate({ routeName: 'WriteAdd',params:data }))
            }
          },
        })
      }
    }
  };
---------->>>>>
implementation(project(':react-native-camera')) {
        exclude group: "com.android.support"
    }

**Comment by n1ru4l** [comment]
Please use the template and provide a full stacktrace.
