### ISSUE TITLE
Not Working In Android, can not compile.......

### ISSUE THREAD

**Issue by jiangbophd** [react-native-community/react-native-camera#1854]
# Bug Report
**To Do First**
- [ ] Did you try latest release?
- [ ] Did you try master?
- [ ] Did you look for existing matching issues?

**Related Modules**

**Platforms**

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:

**Description/Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by wbyoung** [comment]
@jiangbophd I'm not a team member here, but I can venture to guess that you'll need to provide more details here if anything is to be resolved.

**Comment by ptomasroos** [comment]
Feel free to open a issue with information in it.
