### ISSUE TITLE
[Video Record] has no sound

### ISSUE THREAD

**Issue by fokoz** [react-native-community/react-native-camera#1864]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**
RNCamera

**Platforms**
iOS

**Versions**

- Android:
- iOS: 11
- react-native-camera: 1.3.0
- react-native: 0.56.1
- react: 16.4.1

**Description/Current Behaviour**
Record video with no sound even set `captureAudio=true`, have tested with VLC player in the PC and also with `react-native-video `no sound at all.

**Expected Behaviour**
The sound should be recorded.

**Steps to Reproduce**
1. Record video with `captureAudio=true` and allow the permission.
2. Video has only image with no sound.

**Comment by fokoz** [comment]
Here's file example:
[qlZTYpiaQbcdOZPzAHhWYD7nNZRRmDSCFUHFlxbg.mov.zip](https://github.com/react-native-community/react-native-camera/files/2496683/qlZTYpiaQbcdOZPzAHhWYD7nNZRRmDSCFUHFlxbg.mov.zip)

**Comment by ryekerjh** [comment]
@fokoz Did you ever find a solution for this?

**Comment by fokoz** [comment]
@ryekerjh don’t set mute in record options. Even if you set muted=false it will be muted anyway.

**Comment by ryekerjh** [comment]
@fokoz My coworker found that shortly after I tagged you. Thanks so much for responding!
