### ISSUE TITLE
Facedetector is not detecting any faces (iOS)

### ISSUE THREAD

**Issue by olegwn** [react-native-community/react-native-camera#1870]
# Bug Report
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**
RNCamera
FaceDetector

**Platforms**
iOS

**Versions**
- iOS: 11.x, 12.x (tried on two different devices)
- react-native-camera: master (fc3f7bd)
- react-native: 0.57.3
- react: 16.6

**Description/Current Behaviour**

When I open a frontal camera I get initial callback on onFacesDetected with:
`{type: "face", faces: Array(0), target: 347}`

After that, when I direct camera to face or faces the callback is never called again.

**Expected Behaviour**
Should detect faces and call onFacesDetected callback

**Steps to Reproduce**
Installed Facedetector using CocoaPods with:
` pod 'react-native-camera', subspecs: ['FaceDetector'], path: '../node_modules/react-native-camera'`

My RNCamera settings:

```            type={RNCamera.Constants.Type.front}
            autoFocus
            flashMode={RNCamera.Constants.FlashMode.auto}
            faceDetectionLandmarks={RNCamera.Constants.FaceDetection.Landmarks.all}
            onFacesDetected={this.onFacesDetected}
            onFaceDetectionError={this.onFaceDetectionError}
            faceDetectionMode={RNCamera.Constants.FaceDetection.Mode.accurate}
```

Tried with RNCamera.Constants.FaceDetection.Mode.fast as well and RNCamera.Constants.FaceDetection.Landmarks.none
makes no difference

**Comment by olegwn** [comment]
strange thing, but after recompiling project in XCode 10 with legacy build system the face detection now works!

**Comment by jgcmarins** [comment]
can we close?

**Comment by brunotalhate** [comment]
I've recompiled using legacy build but I'm still facing the `{type: "face", faces: Array(0), target: 347}` object.

Using cocoapods, iPhone 6 with iOS 12, xCode 10.1 and couldn't find any solution yet

**Comment by UberMC** [comment]
Is face detection broken on iOS?

**Comment by brunotalhate** [comment]
I've been unable to make it work on iOS using both cocoapods and non-cocoa.
Spent 2 days trying a lot of specs without success. 😞

The closest I've achieved was the empty face on mount

Did your tried it lately?

Em sáb, 8 de dez de 2018 3:12 AM, Trent <notifications@github.com> escreveu:

**Comment by olegwn** [comment]
I noticed that face detection works on iPhone X device but doesn't work on iPhone 6 device!

**Comment by brunotalhate** [comment]
Tried with manual linking and I was able to build without errors using the package version `"react-native-camera": "git+https://github.com/react-native-community/react-native-camera.git#7d172af864e963fde3d732fbfd2b8d124ab2b582"` and `Legacy Build System`

**Comment by sibelius** [comment]
@brunotalhate can we do a git bisect to check where the bug was introduced?

**Comment by syadykin** [comment]
Commenting out https://github.com/syadykin/react-native-camera/blob/master/ios/RN/RNCamera.m#L622 reverts face detection back, not sure what it is for though.

**Comment by n1ru4l** [comment]
@syadykin It is for setting the `defaultVideoQuality` property on the `RNCamera` instance in order to prevent flickering. The flickering cannot be avoided when using `recordAsync`

**Comment by telmen** [comment]
Any update on this? using cocoapods

**Comment by telmen** [comment]
Hi @brunotalhate, any luck with it?

**Comment by tiendn** [comment]
Hope !

**Comment by srGritsuk** [comment]
**It broke right here:**
(Older devices cannot shoot video with photo quality)
Its work fine from iPhone 6s and earlier with:
self.session.sessionPreset = AVCaptureSessionPresetHigh (not AVCaptureSessionPresetPhoto)

https://github.com/react-native-community/react-native-camera/blob/master/ios/RN/RNCamera.m#L623

You can manually set a weak preset, for iPhone 6s works fine preset:
defaultVideoQuality={ RNCamera.Constants.VideoQuality.720p }

https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#ios-defaultvideoquality

**Comment by telmen** [comment]
Yeah, it seems solving the problem.

**Comment by sibelius** [comment]
can more people test these 2 PR

https://github.com/react-native-community/react-native-camera/pull/2044
https://github.com/react-native-community/react-native-camera/pull/2036

which one makes more sense?

**Comment by Thomazella** [comment]
@sibelius idk, I tried both and neither work. Also text and barcode don't work for me. It's not calling the `onFacesDetected` callback. iPhone 6s. Maybe I did something wrong? should I expect to see some points render on the screen if my face is detected?

**Comment by Thomazella** [comment]
also tried commenting out the line https://github.com/react-native-community/react-native-camera/blob/master/ios/RN/RNCamera.m#L623
and tried setting it to `AVCaptureSessionPresetMedium`

**Comment by sibelius** [comment]
Have you setup face detection on iOS? Are you using manual link or pods?

**Comment by Thomazella** [comment]
Gonna try again, apparently had a setup issue. Using manual link.

**Comment by luvnish19** [comment]
I am using Xcode 11.3.1 and testing on iPhone 7 with OS 13.3.1. Both onFacesDetected & onFaceDetectionError methods are not called. Can someone have any solution.
I will be very thankful.

**Comment by locliem08** [comment]
I am using the latest current version: "react-native-camera": "^ 3.32.0". Face recognition doesn't work on the rear camera on some older iOS devices. I test on iPhone 11 Pro works, iPhone 7 does not work.
- My fix is ​​to update the code in the library: RNCamera.m change AVCaptureSessionPresetPhoto = AVCaptureSessionPresetHigh

```
-(AVCaptureSessionPreset)getDefaultPreset
{
    AVCaptureSessionPreset preset =
    ([self pictureSize] && [[self pictureSize] integerValue] >= 0) ? [self pictureSize] : **AVCaptureSessionPresetHigh**;

    return preset;
}
```

Everything works normally. I am not sure if there is any impact on react-native-camera functionality?

**Comment by sibelius** [comment]
can you send a pull request?
