### ISSUE TITLE
Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).

### ISSUE THREAD

**Issue by AsocialCoder** [react-native-community/react-native-camera#1871]
```
compile (project(':react-native-camera')) {
    exclude group: "com.google.android.gms"
    compile 'com.android.support:exifinterface:27.+'
    compile ("com.google.android.gms:play-services-vision:12.+")
}
```

Error: 

```
 Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar
```

**Comment by iremlopsum** [comment]
Having the same problem and can't seem to find a solution. Updated `react-native-camera` from `1.1.0` to `1.3.0` and issue still exists

**Comment by iremlopsum** [comment]
After Googling the hell out of this I found a solution based on this answer: https://stackoverflow.com/a/51213879/3840147

I changed my `build.gradle` files so that `jcenter()` would always be at the bottom of the list. I actually made this change for `react-native-camera` in `node_modules` as well and all works fine now :)

Seems that the library is down from maven's side, and needs to use a mirror instead

**Comment by jiasongs** [comment]
same problem, +1

**Comment by netdesk** [comment]
It was enough for me to move `jcenter()` below `google()` within `allprojects.repositories` in `android/build.gradle`. I don't know if this has side effects in other apps or configurations. At least using just this as a temporary solution you don't have to mess around in node_modules.

**Comment by andikaerwansyah** [comment]
same problem, +1

**Comment by xenu256** [comment]
Yeah, jcenter() after google() fixed the problem for me too.

**Comment by sibelius** [comment]
fixed on master

**Comment by SiSa68** [comment]
I'm using `react-native-firebase` and I had same problem, but non of the above answers works for me.
Updated `react-native-firebase`  and everything works fine now

**Comment by imansalhi** [comment]
I'v same problem and the interesting thing is that i'v this problem only in macintosh ...
every thing is working when i build it on windows
