### ISSUE TITLE
Text recognition for iOS without Cocoapods

### ISSUE THREAD

**Issue by ioanamirela** [react-native-community/react-native-camera#1877]
# Feature-Request

**Describe the Feature**
Would love to use text recognition on iOS without the cocoapods constraint.

**Comment by sibelius** [comment]
you can use postinstall strategy

**Comment by ioanamirela** [comment]
Do you mind clarifying?

**Comment by jgcmarins** [comment]
@ioanamirela, check this: https://github.com/react-native-community/react-native-camera#face-detection-or-text-recognition-steps
you will find few instructions and a script to install text recognition without Cocoapods

**Comment by ioanamirela** [comment]
Oh hey, there's a new "Non-CocoaPods Path" section. Thanks @sibelius, will try it out!
