### ISSUE TITLE
Error:Could not resolve all files for configuration ':app:debugRuntimeClasspath'. > Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).   Searched in the following locations:       https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

### ISSUE THREAD

**Issue by Qggld** [react-native-community/react-native-camera#1878]
# Question

**To Do First**
- [ ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by rainbowvs** [comment]
I have the same problem.

FAILURE: Build failed with an exception.

What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
  Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
    Searched in the following locations:  https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

**Comment by ptomasroos** [comment]
jcenter seems to have wiped a lot of dependencies lately

make sure to move down
jcenter() to the bottom of the repositories for the build.gradle + app/build.gradle

this solved our build and documented on many other places. this has nothing todo with react-native-camera it self

**Comment by rainbowvs** [comment]
> jcenter seems to have wiped a lot of dependencies lately
> 
> make sure to move down
> jcenter() to the bottom of the repositories for the build.gradle + app/build.gradle
> 
> this solved our build and documented on many other places. this has nothing todo with react-native-camera it self

I solved this problem. Thank you for your help.   @ptomasroos 👍

**Comment by NadeemShakya** [comment]
Moving down the jcenter() in the repositories in the android/build.gradle helped me solve my problem. Thankyou @ptomasroos 👍

**Comment by JB-CHAUVIN** [comment]
> jcenter seems to have wiped a lot of dependencies lately
> 
> make sure to move down
> jcenter() to the bottom of the repositories for the build.gradle + app/build.gradle
> 
> this solved our build and documented on many other places. this has nothing todo with react-native-camera it self

Thanks you very much, it solved the issue.

**Comment by Weapon-X6** [comment]
And now that jcenter() is no longer receiving updates what is the recommended action?
