### ISSUE TITLE
[Enhancement] Returning video/picture metadata

### ISSUE THREAD

**Issue by corbt** [react-native-community/react-native-camera#188]
It's often useful to get metadata about a picture/video you've captured. It's especially useful to know a video's duration. This can be estimated by manually timing the user's button presses, but it would be easier and more accurate if the framework did this automatically.

I'd like to propose a change to the `capture` method's resolved return value. Currently, it just returns the file's path. This could be improved by returning a `status` object, with the following properties:

Photos: `path`, `width`, `height`, `file_size`
Videos: All of the above, plus `duration`.

This change would also make the library more future-proof, because it would be easy to add more properties if necessary.

Happy to put together a PR if this looks good. Thoughts?

**Comment by aforty** [comment]
I would find this useful. 👍

**Comment by corbt** [comment]
@lwansbrough have you had a chance to think about this?

**Comment by jadnco** [comment]
Adding a `location` object that includes latitude and longitude would also be awesome.

**Comment by sscaff1** [comment]
This is exactly what I need. I need the metadata on the callback as @corbt mentioned above. Has any work been done on this?

**Comment by corbt** [comment]
No, I don't think anyone is working on this. I'm happy to implement this in a PR though if @lwansbrough agrees it's a good idea. It's a breaking change so consensus/approval is important.

**Comment by rt2zz** [comment]
This would be great to have, and since we are looking at a putting together 1.0 release, breaking api changes are very much fair game. 

Also with the promise based api, we do not have a lot of alternative options to support metadata.

:+1:

**Comment by yodacom** [comment]
👍

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
