### ISSUE TITLE
Display corners around detected bar code

### ISSUE THREAD

**Issue by zedtux** [react-native-community/react-native-camera#1880]
# Feature-Request

**Describe the Feature**
Show corners, around the detected bar code, while scanning it, like is doing iOS in this screenshot :

![file](https://user-images.githubusercontent.com/478564/47430434-9f74cc00-d799-11e8-8ca2-b18027b649c5.png)

**Comment by SimonErm** [comment]
the barcode read event already includes the barcode bounds

**Comment by n1ru4l** [comment]
An example/recipe for this could be provided in the documentation.

**Comment by zedtux** [comment]
Could anyone add an example before this stupid bot wrongly close this issue?

**Comment by MateusAndrade** [comment]
You can try: https://github.com/shahnawaz/react-native-barcode-mask

**Comment by MateusAndrade** [comment]
#1503

**Comment by zedtux** [comment]
I'm working on a big project right now stupid bot so go away, there are plenty of issues where you can bore people.

We have to upgrade RN in our app anyways due to the 64bits stuff so I'll give it a try at that moment.

**Comment by zedtux** [comment]
🤫

**Comment by zedtux** [comment]
😤

**Comment by zedtux** [comment]
...

**Comment by zedtux** [comment]
......

**Comment by ceefour** [comment]
Related to: #874, #2786

**Comment by ceefour** [comment]
Are the bounds accurate?

Example of how erratic the returned bounds are: (#2791)

https://www.youtube.com/watch?v=EGX49nYzqoQ

**Comment by renatobenks** [comment]
@sibelius can we close that? it seems that this feature was introduced already, is that right?
