### ISSUE TITLE
Unable to scan some barcodes on iOS

### ISSUE THREAD

**Issue by Cherrionella** [react-native-community/react-native-camera#1887]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**
RNCamera

**Platforms**
iOS

**Versions**
- iOS: 11.4.1
- react-native-camera: 1.3.0
- react-native: 0.57.0
- react: 16.5

**Description/Current Behaviour**
If you are trying to scan some barcodes on iOS the react-native-camera does not recognize them. We tried other scanning apps, they work normal. Also Android works well and reads the same barcode

**Expected Behaviour**
It should scan barcode successfully.

**Steps to Reproduce**
Try to scan barcodes on iOS

**Additionals**
We use very simple installation of react-native-camera.

```
<RNCamera
    onBarCodeRead={this.handleScan}
    notAuthorizedView={<NotAuthorizedView onPress={this.handleCancel} />}
/>
```

Sample of barcode unable to scan in attachments
![img_0070](https://user-images.githubusercontent.com/2771308/47479388-72cabe00-d846-11e8-98a6-c9da1018bc61.JPG)

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by n1ru4l** [comment]
If someone has ideas on how to improve the barcode scanning capabilities please feel free to share your thoughts!
