### ISSUE TITLE
Remove RCTCamera

### ISSUE THREAD

**Issue by n1ru4l** [react-native-community/react-native-camera#1890]
**Describe the Feature**
There are many issues about users using RCTCamera which is deprecated. If they still want to use it they could stick with an older version of react-native-camera. I think it would be best to remove RCTCamera from further react-native-camera versions and furthermore close all remaining RCTCamera related issues, since most of the time maintainers only respond with "Please use RNCamera".

**Possible Implementations**
Remove RCTCamera and push a new major release

**Related Issues**
*Insert every Issue about RCTCamera here*

CC @sibelius @jgcmarins

**Comment by sibelius** [comment]
Let’s remove it and do a major bump

**Comment by n1ru4l** [comment]
What is your opinion on replacing Camera1 with Camera2 in this major bump?

**Comment by sibelius** [comment]
what is the minimum android level for react-native? is it higher than camera1 requirements? I feel that camera2 is still buggy

I'd rather keep camera1 and camera2 for now, and we can deprecate camera1 api in another major release

**Comment by n1ru4l** [comment]
Alright.

Any features in RCTCamera that are currently not in RNCamera?

**Comment by vikmis007** [comment]
@n1ru4l The installation guide says, "To use react-native-camera in UWP, use RCTCamera instead of RNCamera". Is there a workaround to use RNCamera for a UWP in the latest release of react-native-camera.

**Comment by sibelius** [comment]
Try to go back to commit to understand how can you fix this
