### ISSUE TITLE
Record video + run speech to text

### ISSUE THREAD

**Issue by sivaranjansahu** [react-native-community/react-native-camera#1892]
# Question

**To Do First**
- [Done ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [done ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [done ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
I have a unique requirement.
I want to be able to record the video as well as run speech to text while the video is being recorded.
Is it possible to do that ?
The idea is, I want to generate the video transcript while the video is getting recorded.
Any pointers would be appreciated.

**Tags**
extract audio,speech to text, nlp

**Comment by sibelius** [comment]
Try to use react native voice
