### ISSUE TITLE
Incompatible AVCAptureSessionPreset causes crash on iPad Mini 4

### ISSUE THREAD

**Issue by kjartanvest** [react-native-community/react-native-camera#1900]
**Versions**
react-native-qrcode-scanner: 1.1.0
react-native-camera: 1.3.1
react-native: 0.44
react: 16.0.0-alpha.6
Platform: iOS 11/iOS 12

**Description/Current Behaviour**
In my project I am implementing a camera view for scanning QR codes, using the react-native-qrcode-scanner library. This lib is dependent on react-native-camera.
Using the latest release of react-native-camera on master (1.3.1), opening the camera causes the app to crash when using an iPad Mini 4. I am not specifying any camera resolution or format, so the default value is used. 
This error gets printed in Xcode:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureSession setSessionPreset:] AVCaptureSessionPreset3840x2160 is not a supported preset'

Seems like this happens because RNCamera is trying to use the highest resolution video preset (4K video), but the camera in the iPad Mini does not support 4K video. 

**Expected Behaviour**
The camera should start without crashing.

**Additionals**
In my package.json: "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera",
I am using RNCamera without the FaceDetector folder.

**Comment by cozmo** [comment]
I'm also experiencing this on both an iPhone XS with iOS 12 and a 5th generation iPad with iOS 11. Oddly for both of these devices this issue has started without any changes to the underlying package (version locked on commit 537f4bedf0f8172b4f96cd0dd997286ba5b497e2). Unclear what triggered this.
