### ISSUE TITLE
How make RNCamera to fit to container on Android?

### ISSUE THREAD

**Issue by seraphmate** [react-native-community/react-native-camera#1902]
# Question

**To Do First**
- [O] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [O] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [O] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

Firstly, I really thank for all developers who keep this useful library. :)
And, I'm sorry about I can't explain enough cause my english is too short.
I upgraded RNCamera(RCTCamera) from 0.12.0 to master, and I just use camera preview for barcode scanning.
When I use RCTCamera, RCTCamera was fit to it's container, but after upgrade library, RNCamera is not to fit container on Android.
RNCamera show over it's container. How can I make RNCamera to fit container?
I want to make my code like iOS Screenshot.

** Screenshot on Android **
![screenshot_1541406156](https://user-images.githubusercontent.com/1323480/47986938-7c470680-e121-11e8-9ac0-afedf1015ae2.png)

** Screenshot on iOS **
![simulator screen shot - iphone xs max - 2018-11-05 at 17 22 19](https://user-images.githubusercontent.com/1323480/47986939-7c470680-e121-11e8-8fc3-f7001fa95e79.png)

```javascript
<View style={{
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        marginBottom: Styles.Constant.CARD_BASE_MARGIN
      }}>
   <RNCamera
        style={{flex: 1}}
        onBarCodeRead={(code) => {
          if (this.state.barcode === '') this._onBarcodeRead(code)
        }}
        flashMode={this.props.flashOn ? RNCamera.Constants.FlashMode.torch : RNCamera.Constants.FlashMode.off}
        captureAudio={false}
        showViewFinder={false}>
        {scanArea}
      </RNCamera>
</View>
```

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by NSShentu** [comment]
and how can we hide the navigation bar in android？
i hide bar in mainActivity but it comes out when i go into camera page

**Comment by maxmijn** [comment]
+1. After upgrading my buildToolsVersion to "27.0.3" and the compileSdkVersion to 27, the camera does not fit to the view anymore. Setting a fixed height, width or ratio does not work.

**Comment by maxmijn** [comment]
@sibelius This works! Not sure what this helper actually does, but I got a square camera view again. Thanks.

**Comment by seraphmate** [comment]
@sibelius Thank you for your guide. :)

**Comment by ReneDH** [comment]
Thank you so much - it's works perfectly

**Comment by jaredramirez** [comment]
If anyone needs this in reason react native, i converted it:
```
module FillToAspectRatio = {
  open ReactNative;

  let styles =
    Style.(
      StyleSheet.create({
        "container":
          style(~flex=1., ~overflow=`hidden, ~position=`relative, ()),
      })
    );

  type layoutInfo = {
    width: float,
    height: float,
  };

  [@react.component]
  let make = (~ratio: (float, float)=(4., 3.), ~children: React.element=?) => {
    let (layoutInfo, setLayoutInfo) = React.useState(() => Js.Nullable.null);

    let handleLayout = layoutEvent => {
      let nativeEvent = layoutEvent##nativeEvent;
      setLayoutInfo(_ =>
        Js.Nullable.return({
          width: nativeEvent##layout##width,
          height: nativeEvent##layout##height,
        })
      );
    };

    let getRatio = () => {
      let (ratioWidth, ratioHeight) = ratio;
      ratioHeight /. ratioWidth;
    };

    switch (layoutInfo->Js.Nullable.toOption) {
    | None =>
      <View key="pre-info" onLayout=handleLayout style=styles##container />
    | Some({width, height}) =>
      let ratio = getRatio();
      let (wrapperWidth, wrapperHeight) =
        if (ratio *. height < width) {
          (width, width /. ratio);
        } else {
          (ratio *. height, height);
        };
      <View onLayout=handleLayout style=styles##container>
        <View
          style=Style.(
            style(
              ~width=wrapperWidth->dp,
              ~height=wrapperHeight->dp,
              ~marginLeft=((width -. wrapperWidth) /. 2.)->dp,
              ~marginTop=((height -. wrapperHeight) /. 2.)->dp,
              (),
            )
          )>
          children
        </View>
      </View>;
    };
  };
};
```

**Comment by Sargnec** [comment]
Used this but after taken pictures becomes bigger. I think overflow: hidden solves nothing

**Comment by johhansantana** [comment]
not sure if this helps but setting the container style `overflow: 'hidden'` on android fixes the overlay of the camera ratio.
