### ISSUE TITLE
Freeze image while  takePictureAsync is not resolved

### ISSUE THREAD

**Issue by Fsarmento** [react-native-community/react-native-camera#1903]
# Feature-Request

**Describe the Feature**
On Android, takePictureAsync takes up to 3 seconds to resolve (there are already a lot of issues opened regarding this). During this period, the camera is still active. If the user points the camera to a different location, the image seen on the screen is updated. The gif below shows better what I am trying to explain. 

![ezgif com-optimize](https://user-images.githubusercontent.com/18128610/47994918-b1386680-e0eb-11e8-8e07-3a931ab62c88.gif)

It would be great if there was an option to freeze the captured image. The user could still wait for the image to be processed, but he would see a print screen of the picture taken by the camera.

**Possible Implementations**
It could be a boolean flag in RNCamera or an option in takePictureAsync.

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by Fsarmento** [comment]
I guess this is related to https://github.com/react-native-community/react-native-camera/issues/1836

**Comment by FullstackJack** [comment]
@Fsarmento I'd say it's moreso related to https://github.com/react-native-community/react-native-camera/issues/1838

**Comment by Fsarmento** [comment]
Just to add that I tested the pull request https://github.com/react-native-community/react-native-camera/pull/1641 and it seems to work fine. It does pause de camera on takePictureAsync call and the promise is resolved.

`yarn add react-native-camera@react-native-community/react-native-camera#pull/1641/head`
