### ISSUE TITLE
Android Text Recognize Error.

### ISSUE THREAD

**Issue by dileepbolisetti** [react-native-community/react-native-camera#1909]
# Question

**To Do First**
- [ ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
I Was Trying To implement text Recognition Normal Camera is working fine When i Am adding this

           **onTextRecognized={({ textBlocks }) =>
              this.setState({ detectedTexts: textBlocks.map(b => b.value) })
            }**
I Am Having this Error... Apk build is Sucessfull
![picsart_11-07-04 33 19](https://user-images.githubusercontent.com/8918698/48128099-79781d00-e2ab-11e8-8042-4952106a4135.png)

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by SimonErm** [comment]
did you modify your gradle files like discribed here:https://github.com/react-native-community/react-native-camera/blob/master/README.md ?

**Comment by dileepbolisetti** [comment]
@SimonErm  thanks after adding few dependencies the error gone...

**implementation "com.google.zxing:core:3.2.1"
implementation "com.drewnoakes:metadata-extractor:2.9.1"**

How ever android Documentation is not as clear as ios.

**Comment by n1ru4l** [comment]
@dileepbolisetti Feel free to improve the documentation for android!

**Comment by g4laura** [comment]
I'm having the same error, would you mind sharing more about how you fixed it?

**Comment by dileepbolisetti** [comment]
@g4laura 
[](https://github.com/react-native-community/react-native-camera/issues/1909#issuecomment-437650544)

**Comment by sibelius** [comment]
we need more docs

**Comment by guhyeon** [comment]
In my case, I have solved by
Adding jitpack to android/build.gradle
and gradle cache clean cd android && ./gradlew clean


//Adding jitpack to android/build.gradle
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
    }
}
