### ISSUE TITLE
External Camera USB

### ISSUE THREAD

**Issue by pedrofelipest** [react-native-community/react-native-camera#1912]
Hello, do you support the use of external USB cameras?

**Comment by SimonErm** [comment]
Related to this posts:
https://stackoverflow.com/questions/8963897/use-usb-camera-on-android-application/8986688#8986688
https://stackoverflow.com/questions/37877329/using-an-external-usb-camera-in-android#37892200
i think it won't be possible. If i am wrong feel free to correct me.

**Comment by thecodecafe** [comment]
Hey, @pedrofelipest were you able to find a library that supports that?

**Comment by jessicanevesmachado** [comment]
hello do you find a library that supports that?
