### ISSUE TITLE
Update CircleCI Docker Image Node Version to 8.12.x

### ISSUE THREAD

**Issue by n1ru4l** [react-native-community/react-native-camera#1915]
@sibelius Build is currently failing due to semantic-release requiring node version `>= 8.3`.
https://circleci.com/gh/react-native-community/react-native-camera/341

Could not find the source for the Dockerfile (https://hub.docker.com/r/entria/react-native-android/)

Also tried checking if the newest image hast a newer node version without success.

```
| => docker run entria/react-native-android:latest node -v
/entrypoint.sh: line 7: sudo: command not found
/entrypoint.sh: line 8: sudo: command not found
/entrypoint.sh: line 9: sudo: command not found
```

Would be beneficial to open source the source of the  `entria/react-native-android` image.

**Comment by sibelius** [comment]
we upgrade it to latest node LTS (10) and also yarn version

check the code here https://github.com/entria/docker-react-native-android

maybe we can have a community docker version based on that one
