### ISSUE TITLE
Incorrect value reading 47 digit barcode 'interleaved 2 of 5' (Brazilian type)

### ISSUE THREAD

**Issue by douglashptiago** [react-native-community/react-native-camera#1919]
When reading bar code in 'interleaved 2 of 5' format, a code with 43 digits is being returned, 4 less than expected.
Code that I need: 00190000090050201018400016324188122550000015000
Code that is returned to me: 0019122550000150000000000502010180001632418
Any way to set the desired barcode length?

![captura de tela 2018-11-12 as 15 53 34](https://user-images.githubusercontent.com/14179399/48365857-3fd05900-e693-11e8-88d9-a6807aa82509.png)
![captura de tela 2018-11-12 as 15 53 44](https://user-images.githubusercontent.com/14179399/48365859-4068ef80-e693-11e8-880e-d7c956347a05.png)

**Comment by n1ru4l** [comment]
Does this occur on both android and ios devices?

**Comment by grsabreu** [comment]
As of this, the reading is indeed correct.
https://stackoverflow.com/questions/22234424/zxing-not-reading-brazilian-barcode-bills-interleaved-2-of-5-correctly-how-ca

**Comment by sibelius** [comment]
Welcome to Brazil

**Comment by grsabreu** [comment]
🙃

**Comment by n1ru4l** [comment]
@grsabreu Does this mean we can close this issue?

**Comment by fakenickels** [comment]
For anyone looking this in the future, the barcode reading is correct. You gotta convert the read line to a the the `linha digitável` format
https://github.com/Bruno-Louvem/boleto-barcode-parser

**Comment by r-guimaraes** [comment]
Great, thanks @fakenickels . Really helpful reference
