### ISSUE TITLE
How to apply iOS filters like CIImage.applyingFilter to preview stream?

### ISSUE THREAD

**Issue by solohin** [react-native-community/react-native-camera#1920]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Hi guys! 
I have a question related to camera preview on iOS. 
How to apply iOS filters like [CIImage.applyingFilter](https://developer.apple.com/documentation/coreimage/ciimage/1437589-applyingfilter) to preview stream?

I would do something like this on native code:
```
let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer)
let image = CIImage(cvPixelBuffer: pixelBuffer!)
let previewImage = image.applyingFilter("CIColorInvert")
    .applyingFilter("CIPhotoEffectMono")
    .applyingFilter("CIFalseColor", parameters: [
        "inputColor0": CIColor.blue,
        "inputColor1": CIColor.red,
      ])
```
**Tags**
cvPixelBuffer, applyingFilter, CIImage, preview, iOS

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by n1ru4l** [comment]
@sibelius This might be something that should be done in userland I think. It is for images in general so I do not think this should belong into react-native-camera.

**Comment by n1ru4l** [comment]
I do not know your exact use case but maybe https://github.com/iyegoroff/react-native-color-matrix-image-filters could solve it?

**Comment by sibelius** [comment]
it makes sense
