### ISSUE TITLE
why make offline bundle cound not preview just loading

### ISSUE THREAD

**Issue by chenxin0916** [react-native-community/react-native-camera#1921]
# Question

**To Do First**
- [ ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate

**Comment by n1ru4l** [comment]
I cannot understand what you want. Please provide more information

**Comment by chenxin0916** [comment]
thank you！i solve it
