### ISSUE TITLE
Barcode Scanning (Aztec Code)

### ISSUE THREAD

**Issue by mateuszmatyszkowicz** [react-native-community/react-native-camera#1924]
It's possible to improve barcode scanner for aztec code?  I couldn't scan any aztec code (ex. https://dscu.pl/wp-content/uploads/2016/12/zdjecie-probne.jpg) using Camera with `onGoogleVisionBarcodesDetected` and also `onBarCodeRead`, both function was testing independent.
Has anyone had simmilar problem and managed to workaround it? Or maybe there are more suitable libraries to aztec codes which I could link with react native instead of react-native-camera?

**Comment by n1ru4l** [comment]
@mateuszmatyszkowicz Mobile Vision should support aztec barcodes: https://developers.google.com/vision/android/barcodes-overview

Is it possible you have overwritten `barcodetypes` https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#barcodetypes?

Also Mobile Vision is now part of ml-kit. Maybe we should upgrade (https://firebase.google.com/docs/ml-kit/read-barcodes). Maybe the "new" version can provide more accurate results.

**Comment by mateuszmatyszkowicz** [comment]
@n1ru4l I tried it with barCodeTypes and without, but It didn't help. How long it would take to upgrade it for the new version? Did you recommend any other implementation barcode scanner for android? Because  for iOS it works well,. Anyway, thanks for your reply.

**Comment by n1ru4l** [comment]
I have no requirements for qr codes in my application (yet) and I never worked on a project with barcode scanning so sadly I cannot give you an advice. 😕

Maybe someone else could provide more information or could do some research!

**Comment by mateuszmatyszkowicz** [comment]
I have done some research and I encountered https://github.com/dex4er/barcodescanner-lib-aar this library It's looks promising under other project like Ionic (cordova), but I didn't manage to implement it under react-native because JAVA is not my strong suit.

**Comment by n1ru4l** [comment]
@mateuszmatyszkowicz Can you scan the code by using the following app? https://github.com/ravi8x/Barcode-Reader

**Comment by juwo123** [comment]
@mateuszmatyszkowicz did you find any solution? I'm struggling with the same problem with reading aztec codes from polish car documents
