### ISSUE TITLE
undefined is not an object (evaluating 'Z.Aspect')

### ISSUE THREAD

**Issue by SirhanDada** [react-native-community/react-native-camera#1929]
I'm getting the message: "undefined is not an object (evaluating'z.Aspect') render the demo code in Android. Can someone help me?

![bd5cf52a-bc7c-4fb5-890e-201d59875659](https://user-images.githubusercontent.com/45172643/48712038-ecf72400-ebf3-11e8-8ecc-1bd54b6aee58.jpg)

**Comment by sibelius** [comment]
your react-native link is wrong

do it again and rebuild

**Comment by SirhanDada** [comment]
Thanks for the answer, I followed the procedures and now the error path is in Camera.js, how to proceed?

![7481a05a-6c30-47b6-94d9-fc40b56abf61](https://user-images.githubusercontent.com/45172643/48846125-6b370000-ed85-11e8-84f0-4a49ed20eb94.jpg)
