### ISSUE TITLE
pauseAfterCapture option not working

### ISSUE THREAD

**Issue by equesteo** [react-native-community/react-native-camera#1930]
# Bug Report
**To Do First**
- [X] Did you try latest release?
- [ ] Did you try master?
- [X] Did you look for existing matching issues?

**Related Modules**
RNCamera

**Platforms**
Android

**Versions**

- Android: 7.1.2
- iOS:
- react-native-camera: 1.4.1
- react-native: 0.55.4
- react: 16.2.0

- react-native-navigation: 2.0.2556

**Description/Current Behaviour**
When taking a picture using RNCamera.takePictureAsync, I pass the option `pauseAfterCapture` and expect the viewfinder to pause after the photo is captured. It never pauses, even though the photo is captured.

**Expected Behaviour**
The viewfinder should pause upon capture, then be unpaused when I call `resumePreview`.

**Steps to Reproduce**
My camera looks like this: 
```
        <View style={{width, height: width}}>
          { this.props.showCam ? <RNCamera
            ref={ref => { this.camera = ref }}
            style = {styles.preview}
            type={this.state.backCamera ? RNCamera.Constants.Type.back : RNCamera.Constants.Type.front}
            flashMode={RNCamera.Constants.FlashMode.off}
          /> : null}
        </View>
```

And taking a picture looks like this:
```
takePicture () {
    if (this.camera) {
      this.camera.takePictureAsync({pauseAfterCapture: true}).then((data) => {
        const cropData = {
          offset: {
            x: 0,
            y: 0,
          },
          size: {
            width: data.width,
            height: data.width,
          },
        };
        ImageEditor.cropImage(
          data.uri,
          cropData,
          (successURI) => {
            ImagePicker.cleanSingle(data.uri).catch(e => logError(e))
            this.camera.resumePreview() // not working?
            this.props.stashNewRidePhoto(successURI)
          },
          (error) => {
            console.log(error.message);
          },
        );

      }).catch((e) => { logError(e) })
    }
  }
```

**Comment by galcivar** [comment]
I am experiencing this issue using the docs example from the [Docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md). Just changed options:
`const options = { quality: 1, base64: true, pauseAfterCapture: true }`

Packages:
"react-native": "^0.57.5",
"react-native-camera": "^1.4.3"

**Comment by ilibilibom** [comment]
This is still happening to me with version ^3.11.0
error: 
```
Error: Preview is paused - resume it before taking a picture.
```
My function: 
```
takePicture = async() => {
    if (this.camera) {
      const options = { quality: 0.5, base64: true, pauseAfterCapture: true };
      const data = await this.camera.takePictureAsync(options);
    }
  };
```

**Comment by matheuszenker** [comment]
Mine too, using the same example.

**Comment by matheuszenker** [comment]
I'm getting the same error. 

"react-native": "0.61.5",
 "react-native-camera": "^3.15.0",

**Comment by VictorMion** [comment]
I'm having the same error.

`"react-native": "0.61.5",
    "react-native-camera": "^3.15.1",`

I'm following the documentation tutorial.

**Comment by kevintbradbury** [comment]
i have the opposite issue, even if pauseAfterCapture = false (which is set to false by default) set as an option, camera freezes each time it takes a photo. 

react: 16.9.0
react-native: 0.61.5
react-native-camera: git+https://git@github.com/react-native-community/react-native-camera.git

**Comment by felansu** [comment]
its happening in:

"react": "17.0.1"
"react-dom": "17.0.2"
"react-native": "0.64.1"
"react-native-camera": "3.44.0"
