### ISSUE TITLE
add tests using react-native-testing-library

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#1935]
# Feature-Request

https://github.com/callstack/react-native-testing-library

**Comment by n1ru4l** [comment]
What exactly should be tested?

**Comment by sibelius** [comment]
- [ ] it should render with correct props
- [ ] it should render correctly with render props

maybe more

**Comment by SimonErm** [comment]
Maybe we could add a test app and use https://github.com/wix/detox. Furthermore the test app could be used for static analysis like https://sonarcloud.io/about/sq

**Comment by sibelius** [comment]
related to https://github.com/react-native-community/react-native-camera/issues/1620

Detox would really test end to end this component

**Comment by n1ru4l** [comment]
Can Detox test hardware? Most issues with this project can unfortunately only be tested manual 😢

**Comment by sibelius** [comment]
it can run on devices

like this AWS Device Farm

**Comment by n1ru4l** [comment]
That is pretty rad but we would need a sponsor first!

**Comment by teggno** [comment]
> Can Detox test hardware? Most issues with this project can unfortunately only be tested manually😢

It would be possible to use Microsoft's Azure Pipelines for running detox tests on the **Android emulator** an on **iOS simulator**. Azure Pipelines is Microsoft's CI/CD offering and it's free for open source projects (including parallel build jobs). We've successfully set up such tests in a project where we are using react native.
