### ISSUE TITLE
Check camera exists or not

### ISSUE THREAD

**Issue by raghavendramogeraya** [react-native-community/react-native-camera#1938]
I have installed and using this module and working fine for me. But, need to check whether front or back camera is available in the device. I need to show switch 'front' or 'back' to change the camera front or backside. 
Please help me how we can check this?

**Comment by n1ru4l** [comment]
This can be checked with https://developer.android.com/reference/android/content/pm/PackageManager

Maybe we should export an array that includes the supported camera types?

I am pretty sure on iOS there is always a front and face camera, so we can make it static.
On android we will have to write some native code
