### ISSUE TITLE
undefined is not an object (evaluating 'Z.Aspect')

### ISSUE THREAD

**Issue by SirhanDada** [react-native-community/react-native-camera#1940]
Guys i'm getting the message: "undefined is not an object (evaluating'z.Aspect') render the demo code in Android, 

![7481a05a-6c30-47b6-94d9-fc40b56abf61](https://user-images.githubusercontent.com/45172643/48907175-d6e4a000-ee4d-11e8-8d3f-7162a3f1a08b.jpg)

it's not link's problem...

following the path of error we got here:

![image](https://user-images.githubusercontent.com/45172643/48907304-2c20b180-ee4e-11e8-8a6d-72dc2a7db26a.png)

I decided to take out the Aspect and BarCodeType props but he made the error in the following props...
after taking out the props it points error to the bottom lines:

![image](https://user-images.githubusercontent.com/45172643/48907587-0811a000-ee4f-11e8-8afa-b1bf563c41b3.png)

![image](https://user-images.githubusercontent.com/45172643/48907601-18c21600-ee4f-11e8-8f9d-98a44038f210.png)

after deleting the codes above, I can access the camera but it stays on a black screen and give error when giving snap, can anybody help me?

**Comment by n1ru4l** [comment]
Related #1929

Please provide a reproduction repository.
