### ISSUE TITLE
2d Matrix code scanning

### ISSUE THREAD

**Issue by prateekgoel** [react-native-community/react-native-camera#1944]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**
RNCamera
RCTCamera(deprecated)

**Platforms**
Android

**Versions**

- Android: Tested on Oreo and Pie
- react-native-camera: 1.5.1
- react-native: 0.57.7
- react: 16.4.1
- react-navigation: 2.17.0

**Description/Current Behaviour**
I am using react-native-camera RNCamera to scan barcodes, QR codes and 2d codes. Barcodes and QR code scanning works fine but 2d code scanning is not working most of the time. I have tried going through many issues, blogs, etc, but couldn't find a solution.

I have tried all possible aspect ratios.

> This works with the older RCTCamera.

**Expected Behaviour**
Data matrix scan should work with RNCamera.

**Steps to Reproduce**
Try scanning any 2d data matrix code using RNCamera.

**Does it work with Expo Camera?**

I am not using Expo. Though it works fantastic with expo BarcodeScanner. I tested it on another expo project.

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by prateekgoel** [comment]
Any update here?

**Comment by prateekgoel** [comment]
@n1ru4l I updated the Issue using the template. I hope this gets fixed soon.

**Comment by plus24-library** [comment]
the problem is still there, Data Matrix scanning works horribly
