### ISSUE TITLE
pauseAfterCapture not fully functional on 1.4.3

### ISSUE THREAD

**Issue by ntelkedzhiev** [react-native-community/react-native-camera#1949]
**Platforms**
Android

**Versions**
- Android: 7.1.2
- react-native-camera: 1.4.3
- react-native: 0.57.5
- react: 16.6.3

**Description/Current Behaviour**
There is a 2-3 seconds delay before the image "freezes".

**Expected Behaviour**
Image should "freeze" on capture.

**Steps to Reproduce**
Set `pauseAfterCapture: true`

**Comment by ivosabev** [comment]
Any progress on this?

**Comment by n1ru4l** [comment]
@ivosabev You could start by using git bisect in order to find out when this issue was introduced (https://git-scm.com/docs/git-bisect). It would help fixing this issue a lot.

Otherwise once somebody is working on this he will probably notify in this thread. No need to ask for progress.

**Comment by ntelkedzhiev** [comment]
@n1ru4l This issue has existed ever since `pauseAfterCapture` was introduced (https://github.com/react-native-community/react-native-camera/commit/f6f9f29). https://github.com/react-native-community/react-native-camera/commit/71b10c1 made it better but there is still a significant delay.
