### ISSUE TITLE
iOS: [UIApplication statusBarOrientation] must be used from main thread only

### ISSUE THREAD

**Issue by n1ru4l** [react-native-community/react-native-camera#1950]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**
RNCamera

**Platforms**
iOS

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:

**Description/Current Behaviour**

Runtime Warning:

```- (UIInterfaceOrientation)getOrientationBy:(CMAcceleration)acceleration``` in `RNSensorOrientationChecker.m`

-[UIApplication statusBarOrientation] must be used from main thread only

**Expected Behaviour**
No runtime warning

**Steps to Reproduce**
Use rn-camera.

**Additionals**

<img width="1659" alt="bildschirmfoto 2018-11-26 um 11 57 36" src="https://user-images.githubusercontent.com/14338007/49010111-95683380-f172-11e8-9b06-4f9dcb88f5ca.png">

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by justinkiang** [comment]
I believe this issue is causing barcode recognition to not work when I turn the device landscape in an app that is locked to portrait

**Comment by n1ru4l** [comment]
@justinkiang Wanna contribute a fix?

**Comment by justinkiang** [comment]
That should do it
