### ISSUE TITLE
Add image to video when recording is in progress

### ISSUE THREAD

**Issue by AlexSeoven** [react-native-community/react-native-camera#1955]
# Question

**To Do First**
- [*] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [*] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [*] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Is it possible to add image to video when recording is in progress?

if I use ffmpeg on the saved video, it takes a long time (time of processing ~= time of video)

I just need to add overlayed image on first video frame, and i think i need to add image on video stream while recording is in progress

Can you help me with suggestions\workarounds?

**Tags**
video recording, add image to video

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by n1ru4l** [comment]
You can generate thumbnails for your video by using https://github.com/phuochau/react-native-thumbnail#readme
