### ISSUE TITLE
Android crashes while taking a photo

### ISSUE THREAD

**Issue by Nocturne-FFG** [react-native-community/react-native-camera#1960]
# Bug Report
**To Do First**
- [ ] Did you try latest release?
- [ ] Did you try master?
- [ ] Did you look for existing matching issues?

**Related Modules**

**Platforms**

**Versions**

- Android: 6.0
- iOS:
- react-native-camera:1.4.3
- react-native:0.52.2
- react:16.2

**Description/Current Behaviour**
Android crashes while taking a photo. (Android physical machine . version:6.0)

**Expected Behaviour**

normal operation

**Steps to Reproduce**
Use the version of react native 0.52.2 and the version of react-native-camera 1.4.3, then take a photo on Android

**Additionals**
After taking the photo, the program crashes directly and quits. I have not received any errors. So far I have not succeeded. Below is my code.

![image](https://user-images.githubusercontent.com/45280212/49329263-dd45eb00-f5b6-11e8-99e4-051255d15ab6.png)

![image](https://user-images.githubusercontent.com/45280212/49329260-d6b77380-f5b6-11e8-8e72-03ef6a9780d0.png)

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by Nocturne-FFG** [comment]
manifest.xml:
![image](https://user-images.githubusercontent.com/45280212/49329284-20a05980-f5b7-11e8-8455-bde011923130.png)

**Comment by n1ru4l** [comment]
Could you please provide some logs? You can use `adb logcat` (https://developer.android.com/studio/command-line/logcat)

**Comment by Nocturne-FFG** [comment]
@n1ru4l Thank you, I found the answer, add "compile 'com.android.support:exifinterface:27.+'"
