### ISSUE TITLE
Onfaces detected is getting called when faces comes infront of camera but doesnt fire event when the faces go out of camera?

### ISSUE THREAD

**Issue by shohailahm** [react-native-community/react-native-camera#1963]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**

**Platforms**

**Versions**

- Android:26.03
- iOS:
- react-native-camera:1.3.0
- react-native:0.57.3
- react:16.6

**Description/Current Behaviour**

onfacesDetected gets called when faces come in front of camera. Is there any way to know when the face goes out of camera?
here is  my code
```js
  onFacesDetected = ({ faces }) => {
    if (faces.length >= 1) {
      this.setState(
        { origin: faces[0].bounds.origin, size: faces[0].bounds.size },
        () => {
          this.setState({ faceDetected: true });
        }
      );
    } else {
      this.setState({ faceDetected: false });
    }
  };
```
is there a way to call onFacesdetected manually?

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by n1ru4l** [comment]
Please fill out the template.

**Comment by shohailahm** [comment]
someone found anything guys?
