### ISSUE TITLE
How to know if camera is started recording

### ISSUE THREAD

**Issue by svipben** [react-native-community/react-native-camera#1965]
There's no such var like `isRecording` or something like that which returns boolean if the recording is started or no.

**Comment by sibelius** [comment]
can't you handle this on javascript side?

**Comment by svipben** [comment]
I'm doing it but my problem is I get `Video is not recording.` by trying to use `stopRecording()`. This happens if I click too often on start/stop recording. Even if I use var by checking if the recording is in progress I get the same issue. Since I can't be sure 100% if it's started because I'm setting it only before `recordAsync`, I believe boolean from the native module will be way better.

**Comment by sibelius** [comment]
can you avoid using state in this case

you can have `this.isRecording` that will be faster than `setState`, so you won't have any problem I guess

**Comment by svipben** [comment]
Okay, the issue is when I start recording there's some sort of glitch seems like it initializes the camera and if I press stop that moment I get `Video is not recording.`, but second time everything seems okay.

**Comment by svipben** [comment]
I'm currently working on iOS implementation and seems everything is good, I can't test the Android because currently I don't have it, but I can make a PR for iOS if needed.

**Comment by svipben** [comment]
Sounds good!

**Comment by svipben** [comment]
Already opened a PR here: https://github.com/react-native-community/react-native-camera/pull/1969

**Comment by nachumFreedman** [comment]
Hey guys can we do our best to make vitally useful APIs work for both IOS and Android...

**Comment by n1ru4l** [comment]
@nachumFreedman Yes definitely! Please send a pull request. Please also notice that this project is based upon user contributions. Do not assume just opening an issue will solve the problem (in the near future).

I am going to lock this issue. In case there is anything further to discuss, please open a new issue or even better: Let's continue the discussion in a pull request that brings this feature to the android platform.
