### ISSUE TITLE
taking picture with takePictureAsync immediately after changing camera type doesn't work

### ISSUE THREAD

**Issue by Luke-Tan** [react-native-community/react-native-camera#1967]
# Bug Report
**To Do First**
- [Y] Did you try latest release?
- [Y] Did you try master?
- [Y] Did you look for existing matching issues?

**Related Modules**

RNCamera

**Platforms**

iOS

**Versions**

- Android: - 
- iOS: 11.4
- react-native-camera: 1.5.0
- react-native: 0.57.7
- react: 16.6.3

**Description/Current Behaviour**

Calling `takePictureAsync` immediately after calling `setState` to change the direction of the camera does not take the picture with the correct direction.

**Expected Behaviour**

By putting `takePictureAsync` in the `setState` callback, the picture should be taken immediately after `setState` has finished, and thus the camera direction should be changed and a photo should be taken with the other direction. However, the photo taken is always the first direction.

**Steps to Reproduce**

I am trying to take a photo using react native camera immediately after changing from back to front camera. To give you an idea, the code looks kind of like this:

```
state = {
    type: Camera.Constants.Type.back
}

takePicture = () => {
    const options = {quality:0.5}
    this.setState({type:Camera.Constants.Type.front}, () => {
        this.camera.takePictureAsync(options).then(data => {
            console.log(data)
        });
    })
};
```
I presumed that the photo I would have taken would be the one with the front facing camera. However, the photo i get is always the one with the back facing camera. Is there something im missing?

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by n1ru4l** [comment]
Please use the issue template.

There is a certain delay because the communication between the js thread and native thread is asynchronous. In the future this might be solvable with react-native fabric (read more here: https://github.com/react-native-community/discussions-and-proposals/issues/4 keyword JSI Bindings).

**Comment by Luke-Tan** [comment]
So is the only way to fix this to add a setTimeout to takePicture after calling setState?
