### ISSUE TITLE
takePicture Failed Error

### ISSUE THREAD

**Issue by rameshvishnoi90904** [react-native-community/react-native-camera#197]
After modifying the below line i get takePicture failed error
Camera camera = RCTCamera.getInstance().acquireCameraInstance(2);

**Comment by rt2zz** [comment]
Is this in android? try installing the latest from master `npm install lwansbrough/react-native-camera`

**Comment by GauravBuche** [comment]
Check if your app has permissions to access device camera. This applies to new android versions that support setting permissions per app (since Marshmallow, 6.0). The permission for camera could be disabled and should be enabled from the app settings. Settings -> Apps -> [Your App] -> Permissions

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
