### ISSUE TITLE
iOS: onTextDetected returning empty textBlocks

### ISSUE THREAD

**Issue by yis4yimmy** [react-native-community/react-native-camera#1971]
# Bug Report
**To Do First**
- [X] Did you try latest release?
- [X] Did you try master?
- [X] Did you look for existing matching issues?

**Related Modules**

RNCamera

**Platforms**

iOS

**Versions**

- Android: n/a
- iOS: 12.1
- react-native-camera: master
- react-native: 0.57.1
- react: 16.5.0

**Description/Current Behaviour**
Currently I have this code:
```
import React from "react";
import {
  StyleSheet,
  View,
} from "react-native";
import { RNCamera } from "react-native-camera";

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
});

export default class Camera extends React.Component {
  handleTextRecognized = (text) => {
    console.log("Text", text);
  }

  setRef = ref => {
    this.camera = ref;
  }

  render() {
    return (
      <View style={ styles.root }>
        <RNCamera
          ref={ this.setRef }
          style={ styles.camera }
          onTextRecognized={ this.handleTextRecognized }
        />
      </View>
    );
  }
}
```
And the console statement returns `Text {type: "TextBlock", target: 43, textBlocks: Array(0)}` every time.

**Expected Behaviour**
Based on the example https://github.com/dov11/rncamerademo referenced in [#1856](https://github.com/react-native-community/react-native-camera/issues/1856) I expected the text blocks to return the "MacBook Pro" logo and the keyboard letters as objects in the textBlocks array.

**Steps to Reproduce**
Run the app on the device and hold the camera over the keyboard of laptop.

**Additionals**

**Comment by almazpdf** [comment]
I am running into the same issue.
