### ISSUE TITLE
revamp documentation

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#1973]
# Feature-Request

**Describe the Feature**
Improve docs

**Possible Implementations**
- [x] docusaurus - https://docusaurus.io/docs/en/installation

- [ ] Add API.md
- [ ] Revision on outdated methods

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by ronal2do** [comment]
We need to publish the documentation

**Comment by raajnadar** [comment]
Can you split the issue into small tasks I will try to work on this issue. We really need good docs.

**Comment by sibelius** [comment]
Feel free to create a checklist and tackle one item per pull request

**Comment by fabriziobertoglio1987** [comment]
@raajnadar @sibelius 

This was my first experience implementing the Camera functionalities with `react-native-camera`.

1) I visited the [react-native-camera](https://github.com/react-native-community/react-native-camera#react-native-camera----) github repository and experienced this issues:
      * Missing [Video Preview of the Functionalities](https://github.com/wix/react-native-camera-kit#react-native-camera-kit) section from the Library
      * Missing [installation istructions](https://github.com/wix/react-native-camera-kit#installation) section on top of the [`README`](https://github.com/react-native-community/react-native-camera#docs). 
     * Missing [running the example project](https://github.com/wix/react-native-camera-kit#running-the-example-project) section
     * Missing [APIs](https://github.com/wix/react-native-camera-kit#apis) section on top of the README
     * Missing [Example Implementation](https://github.com/wix/react-native-camera-kit#camerakitgalleryview---gallery-grid-component) sections (for ex. simple implementation, QR Code, Pinch to Zoom ...etc..) 
     * Missing [Wiki Section](https://github.com/mperham/sidekiq/wiki) with more example on how to implement `react-native-camera` functionalities

I totally support tidelift, issue hunt, but `wix/react-native-camera-kit` reached 950 stars and the additional traffic may help get additional tidelift subscriptions. For Example we can find other more appropriate places to remind users of our Tidelift/Issuehunt subscription .. Users that experience bugs or need support should be NOTIFIED of the PAYD SUBSCRIPTION option. 

2) The [github page documentation Api docs](https://react-native-community.github.io/react-native-camera/docs/api) are work in progress

3) I am not familiar with Github pages and maybe other Github users too. I prefer to display the documentation from the and the [README](https://github.com/react-native-community/react-native-camera)

4) No [Contributions Guidelines](https://github.com/react-native-community/react-native-camera#contributing)

5) The examples are too complicated. The Basic example is one single file (App.js) of 564 lines. It would be easier having guides in our [wiki section](https://github.com/react-native-community/react-native-camera/wiki) and [recipes](https://react-native-community.github.io/react-native-camera/docs/recipes) section that link to examples hosted on github for each functionality 20 lines long. The example could give an excuse for forking `react-native-camera` and then contributing.

- [ ]  Improve [`README`](https://github.com/react-native-community/react-native-camera#docs)
- [ ]  Improve  [github page documentation Api docs](https://react-native-community.github.io/react-native-camera/docs/api)
- [ ]  Add articles in [wiki section](https://github.com/react-native-community/react-native-camera/wiki) 
- [ ]  [Contributions Guidelines](https://github.com/react-native-community/react-native-camera#contributing)

**Comment by ronal2do** [comment]
### **Documentation - Road Map (Suggestion)**
- [ ] Remove unused methods
- [ ] API documentation
       - Split instalation guide on iOS and Android.
- [ ] Troubleshooting Issues
       - Google Play services conflicts.
- [ ] Update android version
- [ ] Typescript examples
- [ ] More recipes
       - Migrate to MLKit
       - Remove MLKit
       - Hooks examples
       - Working functionality explanation.
       - reacOfInterest
       
Related issues 
- https://github.com/react-native-community/react-native-camera/issues/2845
- https://github.com/react-native-community/react-native-camera/issues/2862
- https://github.com/react-native-community/react-native-camera/issues/2836
- https://github.com/react-native-community/react-native-camera/issues/2870

We still open to suggestions and PRs. 
@sibelius maybe we should create this in a roadmap with the community and move to a new issue
