### ISSUE TITLE
add react-native-camera-cli that makes common tasks easier

### ISSUE THREAD

**Issue by n1ru4l** [react-native-community/react-native-camera#1980]
# Feature-Request

**Describe the Feature**
Add a react-native-camera-cli that can automate certain install steps.

**Possible Implementations**
First command:

- `react-native-camera download-ios-vision-frameworks`

A script that downloads all necessary `*.frameworks` and adds them to the `*.pbxproj`.
This could e.g. be executed as a `postInstall` script.

I already started experimenting here: https://github.com/react-native-community/react-native-camera/commit/719cb44fecb477823c38a4b8b4f2d0f934a4e511

**Related Issues**
<Insert all issues about people having trouble with setting up react-native-camera and face recognition here>

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
check this https://github.com/facebook/react-native-fbsdk/blob/master/bin/ios_setup.js

**Comment by n1ru4l** [comment]
Dope thank you!
