### ISSUE TITLE
Example RN camera is crashing on IOS and android

### ISSUE THREAD

**Issue by radjivF** [react-native-community/react-native-camera#1982]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**
RNCamera

**Platforms**
Android
iOS

**Versions**

- Android: last one 
- iOS: last one
- react-native-camera: 1.5.1
- react-native:0.55.4
- react:16.3.1

**Description/Current Behaviour**

Im using the tutorial for RNCamera and when I render its just crashes without error message

**Expected Behaviour**
Not crash
**Steps to Reproduce**
Just using the example on this repo

Please help

**Comment by n1ru4l** [comment]
Do you mean https://github.com/react-native-community/rncamera-example ?

**Comment by jetonk** [comment]
I have the same problem

**Comment by n1ru4l** [comment]
I am currently working on porting the rncamera-example to this repository, it seems like the face detection stuff is broken.

**Comment by n1ru4l** [comment]
@radjivF Have you tried the example app that is in this repository?

**Comment by radjivF** [comment]
@n1ru4l yes I have tried the example, it works on ios but still crash on android.

**Comment by n1ru4l** [comment]
I have no problems with https://github.com/react-native-community/react-native-camera/tree/master/examples/basic

Can you please provide more information about your hardware?

**Comment by emilemoureau** [comment]
I have the same problem..

**Comment by n1ru4l** [comment]
@emilemoureau Crash logs?

**Comment by emilemoureau** [comment]
Solved, sorry, I didn't have the right config in info.plist !

**Comment by muhammadridho** [comment]
i have same problem. working device Xiaomi Mi5. when i first running i get crash screen

![Screenshot_2019-04-25-13-29-56-917_com rncameraexample](https://user-images.githubusercontent.com/16620050/56714395-e189c500-675e-11e9-8b15-cce529ebedb1.png)

**Comment by mMarcos208** [comment]
I have the same problem in IOS `13.3`
