### ISSUE TITLE
include deviceOrientation and orientation in RecordResponse

### ISSUE THREAD

**Issue by n1ru4l** [react-native-community/react-native-camera#1983]
# Feature-Request

**Describe the Feature**

I am developing an app that records videos in the portrait mode. Therefore I force the orientation Portrait mode with the following code:

```js
const options = {
  ...remainingOptions,
  orientation: 1
};

const result = await camera.recordAsync(options);
```

However I need to know the actual deviceOrientation when the video recording started on the JS Thread.

**Possible Implementations**
Expose a new property `deviceOrientation` on the result returned by `camera.recordAsync(options)`.
This property includes the actual orientation of the device. Furthermore for integrity we can also add the `videoOrientation` property to the result.

@sibelius Are you okay with me implementing this feature?

```js
const options = {
  ...remainingOptions,
  orientation: 1
};

const result = await camera.recordAsync(options);
console.log(result.videoOrientation, result.deviceOrientation);
```

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
I think we can provide this
