### ISSUE TITLE
Review of pauseAfterCapture doesn't contain flash image, only image without the flash

### ISSUE THREAD

**Issue by dangkhoa2708** [react-native-community/react-native-camera#1986]
# Question
Hello guys, I used pauseAfterCapture with flash on, but it turns out the review showing image without flash, however, the returned uri displays  correctly. Do you have any idea to get it work for displaying it correctly in the review ?

**Comment by n1ru4l** [comment]
This seems like a bug. Could you please use the issue template for reporting a bug?
