### ISSUE TITLE
remove lodash dependency

### ISSUE THREAD

**Issue by n1ru4l** [react-native-community/react-native-camera#1993]
# Feature-Request

**Describe the Feature**
Remove `lodash` as a dependency. No need to pull in the whole library.

**Possible Implementations**
We can use `Object.entries(props).map()` instead. 

**Related Issues**
NONE

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by prateekgoel** [comment]
@n1ru4l Can I work on this?

**Comment by n1ru4l** [comment]
@prateekgoel already submitted #1996, but we have plenty of other issues that need help 😊
