### ISSUE TITLE
Package is overweighted

### ISSUE THREAD

**Issue by Nabellaleen** [react-native-community/react-native-camera#2000]
Hi,

After a npm install of your package, the directory size is 16M, mostly due to android build directory, embedding stuff which should not be commited

You should clean that, it's totally useless and horrible for users :)

```
du node_modules/react-native-camera/android/ -h -d 1
68K	node_modules/react-native-camera/android/gradle
4,2M	node_modules/react-native-camera/android/.gradle
596K	node_modules/react-native-camera/android/src
9,5M	node_modules/react-native-camera/android/build
15M	node_modules/react-native-camera/android/
```

**Comment by sibelius** [comment]
android/build is generated by android

**Comment by n1ru4l** [comment]
I think he is right run 

```
npm pack react-native-camera | grep android/build

```

**Comment by sibelius** [comment]
we can ignore more stuff on .npmignore

like examples

**Comment by sibelius** [comment]
https://stackoverflow.com/questions/40642008/how-do-i-view-the-size-of-npm-packages

> react-native-camera@1.6.3: 5.05 MiB

**Comment by MiracleWhy** [comment]
i remove the build directory ,but when i run app,it show like this .
 
![_20181214213802](https://user-images.githubusercontent.com/38320434/50006512-eab49980-ffe8-11e8-8b06-aec6b7db9a1a.jpg)

**Comment by n1ru4l** [comment]
@MiracleWhy please check https://github.com/react-native-community/react-native-camera/issues/1844

**Comment by MiracleWhy** [comment]
> @MiracleWhy please check #1844

tks,it might be my com.google.xxx is not the right version
