### ISSUE TITLE
Face detect bounding box and Blur Face

### ISSUE THREAD

**Issue by jasan-s** [react-native-community/react-native-camera#2004]
# Question

## My use case:
 I want to blur faces in taken photos(save the blurred face image as a copy + original). Thus I need to detect the face and its position and size of the bounding box. 

## Other options I have expolored: 
One way I thought about doing this was using [face-api.js](https://github.com/justadudewhohacks/face-api.js) and then using something like [Sharp.js](https://github.com/lovell/sharp). 

## Using RNCamera
- Does the recent google [deprecation](https://developers.google.com/vision/) of mobile vision API for ML Kit effect this library?  
- If not, how can get the bouding box and blur effect using this library?

**Comment by mrousavy** [comment]
@jasan-s have you solved this issue? I can detect faces, but how do you paint on an image/blur a face using React Native?
