### ISSUE TITLE
discussion about license

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#2013]
@tidelift / @tieguy says this package is not only MIT

the correct label for this package is

`MIT AND Apache-2.0 AND BSD-3-Clause`

as we have THIRD-PARTY-LICENSES as well

what do you guys think?

**Comment by tieguy** [comment]
👋 Happy to answer any questions, but the very short version is: users receive and have to comply with all of THIRD-PARTY-LICENSES, so the package.json license field should reflect everything in there.

**Comment by n1ru4l** [comment]
included in https://github.com/react-native-community/react-native-camera/releases/tag/v1.6.4
