### ISSUE TITLE
Github Bot that adds install command to pull requests

### ISSUE THREAD

**Issue by n1ru4l** [react-native-community/react-native-camera#2017]
# Feature-Request

**Describe the Feature**
It would be helpful if we could have a bot that automatically posts the `yarn` or `npm` install command to a new pull request, so that bug reporters that get pointed to a pull request have no additional obstacle of testing the pull request (Many people do not know you can install a git npm package etc.).

@sibelius What do you think?

**Possible Implementations**
I have seen projects that do this. However at the moment I cannot remember the name of any 😅

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
great, we can try to use github actions or hubot for this

**Comment by n1ru4l** [comment]
@sibelius Do we have access to github actions?

**Comment by sibelius** [comment]
not yet, https://twitter.com/sseraphini/status/1075362702233624577
