### ISSUE TITLE
no audio

### ISSUE THREAD

**Issue by yernandus** [react-native-community/react-native-camera#2029]
# Bug Report
**To Do First**
- [x] Did you try latest release? 
- [ ] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**

RNCamera

**Platforms**

iOS

**Versions**

- iOS:latest
- react-native-camera:1.6.4
- react-native:0.57.5
- react:16.6.1

**Description/Current Behaviour**

video is recorded without audio

**Expected Behaviour**

recorded videos should have audio
**Steps to Reproduce**

record an video on ios. 

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by yernandus** [comment]
solved by passing { muted: false } to recordAsync. The documentation is misleading

**Comment by n1ru4l** [comment]
@yernandus Can you please test if https://github.com/react-native-community/react-native-camera/pull/2024 fixes your issue?
