### ISSUE TITLE
react-native-view-shot compability

### ISSUE THREAD

**Issue by jasan-s** [react-native-community/react-native-camera#2035]
# Question
How can i overlay a view on top of image and save that as a new image. 
I tried using https://github.com/gre/react-native-view-shot/ while using `pauseAfterCapture` but it didn't work see below:

RNCamera Preview Image: 
<img width="323" alt="screen shot 2019-01-07 at 3 06 59 pm" src="https://user-images.githubusercontent.com/13863953/50798671-09c3e580-128e-11e9-83ee-3cd578d1e060.png">

Captured Snapshot with https://github.com/gre/react-native-view-shot/  (Notice Only shows the added Views):
<img width="312" alt="screen shot 2019-01-07 at 3 07 08 pm" src="https://user-images.githubusercontent.com/13863953/50798704-1ea07900-128e-11e9-8578-87d527f9c951.png">

Desired Image want to save(minus the buttons)
<img width="338" alt="screen shot 2019-01-07 at 6 10 51 pm" src="https://user-images.githubusercontent.com/13863953/50805526-af378300-12a7-11e9-915b-c62e82a01c18.png">

**Tags**
image-manipulation,  overlay, composition, image-editing

**Comment by nubwang** [comment]
为啥不能用哇，刚init一个项目，加了这个插件，安装了link了，Could not resolve all files for configuration ':react-native-camera:releaseCompileClasspath'.
> Could not resolve com.facebook.react:react-native:+.
  Required by:
      project :react-native-camera
   > Could not resolve com.facebook.react:react-native:+.
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml'.
                  > Read timed out

**Comment by n1ru4l** [comment]
Duplicate of https://github.com/gre/react-native-view-shot/issues/85

I do not know how `react-native-view-shot` works, so I cannot help you with that. If you have time to investigate further (and this issue can be resolved by adding changes to `react-native-camera`) I encourage you to provide a pull request.

As a **workaround** you could show the taken picture with an `ImageBackground` component and use `react-native-view-shot` on the `ImageBackground` component.

**Comment by Angelk90** [comment]
@n1ru4l : In reference to the issues #2092, that have been closed without being able to reply to the message.

I do not understand the answer that has been given.
Which means: This is out of scope of this library ...

I posted the code with an example, and I asked how I could do something, saving by applying a filter for example, I did not ask things that have nothing to do with the module.

**Comment by Angelk90** [comment]
@n1ru4l : In reference to the issues #2092, that have been closed without being able to reply to the message.

I do not understand the answer that has been given.
Which means: This is out of scope of this library ...

I posted the code with an example, and I asked how I could do something, saving by applying a filter for example, I did not ask things that have nothing to do with the module.

**Comment by n1ru4l** [comment]
@Angelk90 It simply means this is not an issue related to the functionality of react-native-camera. Issues are intended for requesting new features or reporting bugs.

Questions should be asked on StackOverflow.

I do not have time to provide examples for things not covered by the core features. Therefore I closed your issue.

Also the example you provided is for the expo-sdk which is not react-native-camera.

**Comment by Angelk90** [comment]
@n1ru4l : Are you telling me that the request to add a `SurfaceView `function on the camera, for example, in order to do what I asked, for example to apply a filter through a kernel, is beyond the requests that can be made here?

![](https://i.imgur.com/blp1TyO.jpg)

**Comment by n1ru4l** [comment]
@Angelk90 Nope, I never said that. Feel free. It would even be better if you could implement it.

**Comment by fera765** [comment]
has anyone managed to solve this problem?

**Comment by emrahc** [comment]
@Angelk90 were you able to do it?Saving picture with facial square?
