### ISSUE TITLE
"camera not authorized" in version 1.8.0 (Android)

### ISSUE THREAD

**Issue by matheusmonte** [react-native-community/react-native-camera#2041]
# Bug Report
**To Do First**
- [X ] Did you try latest release?
- [ X] Did you try master?
- [ X] Did you look for existing matching issues?

**Related Modules**
RNCamera

**Platforms**
Android (Not tested in iOs)

**Versions**

- Android: 8.1
- iOS: not tested
- react-native-camera: 1.8.0
- react-native: "0.57.5"
- react: 16.6.1

**Description/Current Behaviour**
npm install in react-native-camera and try to use. The app will request camera permission, you tap "OK", the components show "camera not authorized"

**Expected Behaviour**
Show camera frame after get permission

**Steps to Reproduce**
Use RNCamera,
first app time, try to get permissions
try to use after this

**Additionals**
On system settings, show my app as permited
> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by renalpraba** [comment]
![photo_2019-01-09_11-53-00](https://user-images.githubusercontent.com/39117076/50877606-29314e80-1405-11e9-892c-fe0eacb87fc6.jpg)

Found this using v1.8.0 , v1.7.0 & 1.6.6
No problem in v1.6.5

**Comment by syadykin** [comment]
Same issue, 1.6.1 works fine.

**Comment by adimshev** [comment]
Same issue

**Comment by renalpraba** [comment]
@n1ru4l I'm using [react-native-qrcode-scanner](https://github.com/moaazsidat/react-native-qrcode-scanner) (require react-native-camera) with its sample setup getting this error when using react-native-camera 1.6.6 or later, no problem on 1.6.5

**Comment by adimshev** [comment]
```js
<RNCamera
	style={styles.camera}
	onCameraReady={this.onCameraReady}
	onMountError={this.onMountError}
	onBarCodeRead={
		waiter /*|| alert*/ ? undefined : this.onBarCodeRead
	}
	pendingAuthorizationView={null}
/>
```

**Comment by adimshev** [comment]
Permissions are automatically requested when first rendering the RNCamera.

**Comment by n1ru4l** [comment]
@adimshev Are both `Camera` and `Audio` recording permissions permitted?

**Comment by adimshev** [comment]
I add into Manifest only Camera permissions (for barcode scanner).

**Comment by n1ru4l** [comment]
@adimshev Try to set the `captureAudio` property on the `RNCamera` component to `false` if you do not want audio being recorded/permissions for audio recording being asked.

**Comment by adimshev** [comment]
Thank you, now I will install the latest version again and try. 5 minutes.

**Comment by matheusmonte** [comment]
Hi @n1ru4l 

We are using as documentation.

`<RNCamera
                                style={styles.camera}
                                 ref={ref => {
                                    this.camera = ref;
                                }}>
                            </RNCamera>`


When app show screen in the first time, it ask for permissions, you allow, after this, if you check app permissions on android settings, my app have permission to use camera, but it show "camera not authorized" in the render space.

Sorry I can't show all the class code, but I think this is not a code issue, because I downgrade to 1.4.3  version and running well. If you need more information, please, let me know

**Comment by santanapaulo** [comment]
I am getting the same issue as @matheusmonte described. I just updated the version and the camera permission seems not working.

**Comment by n1ru4l** [comment]
@santanapaulo Does Does #2041 (comment) resolve your issue?

**Comment by santanapaulo** [comment]
@n1ru4l the #2041 (comment) worked!!! Thank you for solving it and letting us know. 

PS: I am not sure, but maybe if we set the permissions allowed for sound will it worked. I didn't try it.

**Comment by n1ru4l** [comment]
@santanapaulo Yeah it should work. Going to close this since it seems resolved.

**Comment by cmejet** [comment]
The capture audio = false does seem to solve this, HOWEVER it does NOT match the documentation of how to implement.  Unless you stumble upon this you would have no idea. I too upgraded from and suddenly it told me unauthorized when it worked perfectly fine before.

**Comment by mrudulakb** [comment]
Hi @n1ru4l,
The comment to set captureAudio to false worked. thanks.
<RNCamera ref={ref => { this.camera = ref }} captureAudio={false}>

**Comment by matheusmonte** [comment]
Hi @n1ru4l .

captureAudio={false} solve this issue, thanks.

I try to update documentation in this PR (#2052 ) to avoid more people to have this problem

If need something more, please, let me know

**Comment by HighSoftWare96** [comment]
I had the same problem passing from the 1.5.0 to the 1.8.0 release version. On simulator it crashes, on real device the "camera not authorized" text appears. Solved with captureAudio={false}.

Do I need to open a new issue on this?

**Comment by n1ru4l** [comment]
@HighSoftWare96 You can help by testign this PR: #2048

**Comment by alexisbronchart** [comment]
@renalpraba and others using react-native-qrcode-scanner you can add the prop `cameraProps={{ captureAudio: false }}` on your `QRCodeScanner`.
