### ISSUE TITLE
What version of play services should I use? (with react-native-firebase)

### ISSUE THREAD

**Issue by arapocket** [react-native-community/react-native-camera#2043]
## What is the latest version of play services that includes play-services-vision?

I am trying to build my project with play-services 16.0.1 for react-native-firebase but I can see that there is no play-services-vision:16.0.1

**Comment by lFaustus** [comment]
i used the play-services-vision:16.2.0
```
implementation 'com.google.android.gms:play-services-vision:16.2.0'
implementation (project(':react-native-camera')){
        exclude group: 'com.google.android.gms', module: 'play-services-vision'
}
```

**Comment by MarkRunWu** [comment]
I found there're a property `googlePlayServicesVersion` to specify which version it would load.
But since the version would be missing in other 'com.google.android.gms:' module. 
May renaming the property name into `playServicesVersion` ?

**Comment by arapocket** [comment]
@lFaustus Thanks for the reply. Unfortunately I am also using location and now that's complaining about a non-existent version.

@MarkRunWu I didn't know googlePlayServicesVersion starts from 16.x.x. Good to know. Unfortunately I was already using playServicesVersion.
