### ISSUE TITLE
[Android] `useCamera2API` and barcode scanning isn't working 

### ISSUE THREAD

**Issue by vinayan3** [react-native-community/react-native-camera#2046]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**

**Platforms**
Android

**Versions**
- Android:
  * Nexus 5X @ Android 8.1.0
  * Samsung S6 Edge(SMG-925A)  @ Android 7.0
- react-native-camera: 1.8.0
- react-native: 16.6.3
- react:  0.57.8

**Description/Current Behavior**
Camera is setup as
```
      <RNCamera
        ref={ref => {
          this.camera = ref;
        }}
        style={{
          flex: 1,

        }}
        useCamera2Api={true}
        permissionDialogTitle={'Permission to use camera'}
        permissionDialogMessage={'We need your permission to use your camera phone'}
        onBarCodeRead={this.onBarcode}
     / >
```

**
When pointing the camera at the barcode with the `Camera2API`  enabled there are no detected barcodes.

**Expected Behaviour**
The barcodes should be detected.

**Steps to Reproduce**
1. Set a `onBarCodeRead` to a function
2. Set `useCamera2Api={true}

**Additionals**
I have spun out  the example camera app  into a new example repo with a project created by  `react-native init`. 

https://github.com/vinayan3/CameraTest

For ease of reproducing this bug I've added in buttons which let you toggle which `CameraApi` is used. When you toggle the API or the barcode detection the camera will be unmounted, 5 second wait, and remounted.  Here is a screenshot of the toggles I put in:

![screenshot_20190110-115742](https://user-images.githubusercontent.com/1034900/50993954-c5278c80-14cf-11e9-8af7-b38688fe70a4.png)

**Comment by matt-oakes** [comment]
This is likely caused by the same issue as #1714

**Comment by AgingChan** [comment]
I have encountered a similar issue. The only difference is that the set `useCamera2Api` to `true` will result in the `Face Detection` not working.

**Comment by sraka1** [comment]
@n1ru4l Barcode scanning still does not work with useCamera2Api. Please re-open this issue.

**Comment by agrass** [comment]
Yes, I tested in 2.3.0 and useCamera2Api, and still does not working the barcode scanning.

**Comment by MateusAndrade** [comment]
> Yes, I tested in 2.3.0 and useCamera2Api, and still does not working the barcode scanning.

I Will give a look at this as soon as possible, but you can try the latest version of rn-camera?

**Comment by agrass** [comment]
It worked with last version of rn-camera. Not sure, but it seems that it take more time in read the code compared with Camera1.

**Comment by sibelius** [comment]
can you measure time of the operation?

where is the most time going?

**Comment by JessePreiner** [comment]
Hi, Mr. Bot. Definitely don't close, as the only reason it is stale is because it has not been addressed. The problem didn't fix itself.

**Comment by zelardiel** [comment]
Still a problem mr bot. See referenced issue.
