### ISSUE TITLE
Black screen at first render and null object reference  on android

### ISSUE THREAD

**Issue by shaktalles** [react-native-community/react-native-camera#2047]
# Bug Report
**To Do First**
- [ x ] Did you try latest release?
- [ x ] Did you try master?
- [ x ] Did you look for existing matching issues?

**Related Modules**

RNCamera

**Platforms**

Android

**Versions**

- Android: 6.0.1
- iOS:
- react-native-camera: 1.8.0
- react-native: 0.57.8
- react: 16.6.3

**Description/Current Behaviour**

After creating a new app: react-native init appexample,
In the app folder, install the package: npm install react-native-camera --save,
And do automatic link: react-native link,
Add permission requirement to AndroidManifest.xml.

However, when running the app on device, I get a black screen instead of the camera preview.
Upon clicking on SNAP, I get:

"Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference"
     getDouble
     ReadableNativeArray.java:114

**Expected Behaviour**

Be able to see camera preview and take picture.

**Steps to Reproduce**

As above.

**Additionals**

Environment (at work):
Linux Mint 19.1 - Tara
Node 11.3

Got same issue on other app, I have been reading and trying every possible solution and iteration for the last two days. One thing that kindda worked was using react-native-camera@1.2.0.

Just reproduced the issue at home, using:
Linux Mint 18.2 Cinnamon
Node 10.14.1

Downgrading to react-native-camera@1.2.0 solved the issue.

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by GaneshSaiKumar** [comment]
@n1ru4l  same issue here

**Comment by syntony** [comment]
same issue, thanks  @shaktalles for advice, downgrading solved this problem

**Comment by n1ru4l** [comment]
Sorry for the inconveniences. Could you please try if https://github.com/react-native-community/react-native-camera/pull/2048 resolves your issue?

**Comment by shaktalles** [comment]
hi @n1ru4l, I tried #2048 PR, now it gives a black screen, but with the loading spinner spinning forever. 
I will make more tests next week.

**Comment by n1ru4l** [comment]
@shaktalles Do you only grant `CAMERA` permissions or also `RECORD_AUDIO` permissions?

**Comment by n1ru4l** [comment]
@shaktalles Could you please provide a reproduction repository?

**Comment by luissmg** [comment]
@n1ru4l I think this is because `react-native-camera` is always showing up the `notAuthorizedView` and not checking properly for the permission?
In my case this is happening, even after giving permission. I am only using the camera to take photos, no video.

**Comment by luissmg** [comment]
Soooooooooo I was looking into the lib's code... This is what I found.
In [this](https://github.com/react-native-community/react-native-camera/pull/2037) PR the `captureAudio` is set to `true` by default. Yes, this fixes a lot of stuff for some people, but also ruins for others like me that are not using audio.

Why did this break?
In [this](https://github.com/react-native-community/react-native-camera/blob/master/src/RNCamera.js#L418) line, we take the props value. Before it was `false`, now is `true`. Then, in [here](https://github.com/react-native-community/react-native-camera/blob/master/src/handlePermissions.js#L20), before, when the value was `false`, it entered in the condition and returned whatever. Now, it does not enter in that condition.

Therefore, we, people used to have `captureAudio` has `false` by default, must set it to `false` by hand.

This fixed it for me using the most recent version (`1.8.0`). Please try this @shaktalles @GaneshSaiKumar @syntony 
@n1ru4l Please correct me if I am wrong!

**Comment by asanz8** [comment]
@luissmg Setting ```captureAudio={false}``` did the job, using version 1.8.0

**Comment by n1ru4l** [comment]
@asanz8 You could help by checking if #2048 solves this issue without having to set the `captureAudio` property to `false`.

**Comment by luissmg** [comment]
@n1ru4l I will install your fork from `feature-audio-permissions` branch today and will let you know how it ended up

**Comment by luissmg** [comment]
Already tested by @asanz8!

**Comment by kent2508** [comment]
> Soooooooooo I was looking into the lib's code... This is what I found.
> In [this](https://github.com/react-native-community/react-native-camera/pull/2037) PR the `captureAudio` is set to `true` by default. Yes, this fixes a lot of stuff for some people, but also ruins for others like me that are not using audio.
> 
> Why did this break?
> In [this](https://github.com/react-native-community/react-native-camera/blob/master/src/RNCamera.js#L418) line, we take the props value. Before it was `false`, now is `true`. Then, in [here](https://github.com/react-native-community/react-native-camera/blob/master/src/handlePermissions.js#L20), before, when the value was `false`, it entered in the condition and returned whatever. Now, it does not enter in that condition.
> 
> Therefore, we, people used to have `captureAudio` has `false` by default, must set it to `false` by hand.
> 
> This fixed it for me using the most recent version (`1.8.0`). Please try this @shaktalles @GaneshSaiKumar @syntony
> @n1ru4l Please correct me if I am wrong!

you saved my day bro :D
