### ISSUE TITLE
RNCamera **will** crash on iOS if all three Privacy keys are not included in Info.plist

### ISSUE THREAD

**Issue by dubert** [react-native-community/react-native-camera#2051]
# RNCamera crashes on iOS if all three Privacy keys are not included in Info.plist

Upon reading the README I came across:

```
<key>NSCameraUsageDescription</key>
<string>Your message to user when the camera is accessed for the first time</string>

<!-- Include this only if you are planning to use the camera roll -->
<key>NSPhotoLibraryUsageDescription</key>
<string>Your message to user when the photo library is accessed for the first time</string>

<!-- Include this only if you are planning to use the microphone for video recording -->
<key>NSMicrophoneUsageDescription</key>
<string>Your message to user when the microphone is accessed for the first time</string>
```

Naive me, I wasn't planning on doing any recording, so I didn't include `NSMicrophoneUsageDescription`. My app kept crashing on render and I went digging down a number of rabbit holes. Frustrated and I went back to square one and added all three, and boom, it works. 

I would **highly** recommend removing the comments that suggest the last two keys are optional. In my experience they most certainly were not optional.

**Comment by dubert** [comment]
Update: I am somewhat to blame. This only happens if `captureAudio` is not set to `false` which I did not set. Part of what stumped me was that `Camera` was working, but `RNCamera` was not. But this is because `Camera` defaults `captureAudio` to `false`, but `RNCamera` defaults it to `true`.

**Comment by micchyboy237** [comment]
But how do we set it to false? I use this library because of react-native-qr-scanner, and it crashes when there is no microphone permission

**Comment by n1ru4l** [comment]
@dubert I am working on making microphone permissions optional. Currently my time is limited so if someone could test #2048 and review it would help me massively.

**Comment by Fsarmento** [comment]
I update yesterday react-native-camera for the latest version and my app started crashing. [This](https://github.com/react-native-community/react-native-camera/commit/2940faf8710d321f790419c3458a7eaf9127b93e#diff-6ee136227b7a6fdd96b7a213d5648f4eR261) commit from 8 days ago changed the default `captureAudio` from false to true.

**Comment by n1ru4l** [comment]
@Fsarmento Could you please check if #2048 resolves that crash issue when `captureAudio` is not set?

**Comment by chj-damon** [comment]
> I update yesterday react-native-camera for the latest version and my app started crashing. [This](https://github.com/react-native-community/react-native-camera/commit/2940faf8710d321f790419c3458a7eaf9127b93e#diff-6ee136227b7a6fdd96b7a213d5648f4eR261) commit from 8 days ago changed the default `captureAudio` from false to true.
> To avoid the error (if you only use the camera w/o audio), set `captureAudio={false}`
> 
> Error on Xcode:
> `019-01-16 09:59:13.613561+0000 peeqDaycare[1965:797218] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.`

Thanks a lot!
