### ISSUE TITLE
RNCamera View Doesn't Rotate

### ISSUE THREAD

**Issue by t-hughes** [react-native-community/react-native-camera#2053]
# Bug Report
**To Do First**
- [Y] Did you try latest release?
- [Y] Did you try master?
- [Y] Did you look for existing matching issues?

**Related Modules**

RNCamera

**Platforms**

iOS

**Versions**

- Android:
- iOS: 11.4.1
- react-native-camera: 1.8.0
- react-native: 0.55.4
- react: 16.3.2

**Description/Current Behaviour**

The bug that was reported in #1459 is what I am experiencing. The video provided in that ticket is exactly what is happening. "I found that when the device is rotated the view is initially wrong, but if I start to tilt the device down like I was going to lay it on a table it corrects itself."

**Expected Behaviour**

When the device is rotated the view should rotate along with it.

**Steps to Reproduce**

Open up the camera and turn the device to landscape mode. The view does not change.

**Additionals**

It works correctly on iOS versions 8.5 and 9.3.5 no matter the device. It does not work on iOS version 11.4.1

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by n1ru4l** [comment]
@SimonErm can you take look into this?

**Comment by SimonErm** [comment]
Yes, i will do.

**Comment by SimonErm** [comment]
@t-hughes Can you provide the props you are using?

**Comment by t-hughes** [comment]
@SimonErm - type, ref, style, and onBarCodeRead

**Comment by t-hughes** [comment]
Update on this, I have used both imports as well. So, both Camera and RNCamera and they both give the same result.
