### ISSUE TITLE
RCTCameraModule.stopCapture got 2 arguments, expected 3

### ISSUE THREAD

**Issue by bdeezz** [react-native-community/react-native-camera#206]
React Native version 0.20.0, Android 5.0, Node.js version 5.0.0, react-native-camera (master)

**Comment by Phoenix1708** [comment]
Same Issue here React Native Version 0.21.0. Android 6.0.1, Node version 4.3.2, react-native-camera (master)

**Comment by appbeijing** [comment]
same with upers

**Comment by Frosty92** [comment]
Same issue here, React Native 0.22.2, Android 5.0.1, Node v 4.4.1

**Comment by cubbuk** [comment]
Same issue here, React Native 0.26.1, Android 6.0.1. Any idea how to solve it?

**Comment by zachrnolan** [comment]
Same issue! 

React Native 0.29.2, Android 4.4.4, Node 5.3.0

**Comment by Fuco1** [comment]
Same here

react-native-cli: 1.0.0
react-native: 0.31.0
android 4.4.2
node 5.8.0
on master

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
