### ISSUE TITLE
Could not resolve project :react-native-camera

### ISSUE THREAD

**Issue by aiibe** [react-native-community/react-native-camera#2063]
**Platforms**
Android

**Versions**

- Android: 7.0
- react-native-camera: (master)
- react-native: 0.57.8
- react: 16.6.3

**Description/Current Behaviour**

Build Error
```
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-camera.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-camera: None of the consumable configurations have attributes.
```

Every time a new module is added via ``npm install``, react-native-camera directory will be missing\removed from node_modules.
I have to re-install react-native-camera to solve the problem. Found the solution [here](https://stackoverflow.com/questions/51306490/could-not-resolve-project-react-native-camera)

**Steps to Reproduce**
react-native-camera must already be installed and linked first.
Try ``npm install --save redux redux-thunk`` for instance

**Comment by n1ru4l** [comment]
What version of `npm` are you using? You can run `npm --version` to display it.

Do you install `react-native-camera` with `npm install --save react-native-camera`?

**Comment by aiibe** [comment]
Yes I used ``npm install --save react-native-camera``
``npm`` version 6.6.0

**Comment by n1ru4l** [comment]
I might be wrong but I do not think that this issue is related to `react-native-camera`. Have you tried downgrading your `npm` version? I am using `yarn` and have not used `npm` in a while, but `npm install` should actually work fine.

**Comment by n1ru4l** [comment]
You should be able to install the package with `npm install --save react-native-camera@git+https://git@github.com/react-native-community/react-native-camera.git`

You should actually never edit the package.json dependencies and devDependencies manually since the changes will not be reflected in your lock files. Furthermore I think you forgot the `.git` extension in your url.

**Comment by n1ru4l** [comment]
@aiibe the documentation needs some improvements then 😊Using the master branch is only recommended when you can live with things breaking.

@aiibe Just out of curiosity: Have you any specific reason for installing from master?

**Comment by minicase** [comment]
I have the same issue. RN5.9.3

**Comment by wesleyguirra** [comment]
Same issue

**Comment by MoizYousuf** [comment]
Same Issue

**Comment by ehorodyski** [comment]
Same issue...used the docs to install. I tried installing it through yarn.

**Comment by Tino-F** [comment]
https://github.com/react-native-community/react-native-camera/issues/2210#issuecomment-483677300 fixed it for me

**Comment by fadlykayo** [comment]
In android/app build.gradle:

```
android {
  ...
   defaultConfig {
     ...
     missingDimensionStrategy 'react-native-camera', 'general' <-- insert this line
   }
}
```

**Comment by petarprok** [comment]
@fadlykayo Thank you this solution worked for me. :)

**Comment by andrewhartwig** [comment]
Hmm, @fadlykayo this solution did not fix it for me, on a fresh install of react-native `v0.59.5`

**Comment by andrewhartwig** [comment]
hmm, bizarrely, moving it to the top of the `defaultConfig` key fixed it, or i dunno, maybe the file wasn't saved, but builds are passing now :/

**Comment by johnstew** [comment]
@fadlykayo just for my own knowledge. what exactly is this doing?

also this work for me so thank you!

**Comment by moustaphadiakhate** [comment]
insered like this :
i created in project directory after configured all;
./libs/node_modules/react-native-camera
And in my App.js file
./App.js import Camera from './libs/node_modules/react-native-camera';
Camera bla bla bla ..... working  !

**Comment by superzhy** [comment]
Same issue , react-native v0.59.5

**Comment by superzhy** [comment]
@fadlykayo  Thank you, This method solves my problem

**Comment by rwoloszyn** [comment]
@fadlykayo Thanks, same for me.

**Comment by VyankeshH** [comment]
@andreaskeller I also could not resolve the issue,Did you solve this??

**Comment by ilibilibom** [comment]
> In android/app build.gradle:
> 
> ```
> android {
>   ...
>    defaultConfig {
>      ...
>      missingDimensionStrategy 'react-native-camera', 'general' <-- insert this line
>    }
> }
> ```

@fadlykayo - why is this not in the installation RNcamera guide?
