### ISSUE TITLE
specify picture save path (similar to record video)

### ISSUE THREAD

**Issue by Dror-Bar** [react-native-community/react-native-camera#2065]
# Question

How to change the path where image is saved using takePictureAsync()?
In the docs I only see the option to change path for video.
Is it possible?

**Comment by n1ru4l** [comment]
It seems like this is not possible yet. However we could accept a pull request for this. Shouldn't be to hard to implement. Feel free to send a pull request!

**Comment by Dror-Bar** [comment]
Thanks for the answer.
I'm not sure how to do this myself. But for the meantime I might try to use the solution suggested [here](https://stackoverflow.com/questions/48151242/how-to-save-a-picture-to-a-specific-folder-from-react-native-camera-roll/50081434#50081434).

**Comment by Harsh2402** [comment]
@Dror-Bar @n1ru4l 
Did you get any solution for the same?

**Comment by Dror-Bar** [comment]
@Harsh2402 Yes I was able to save images to a specific path using the File System Access API of the library I linked to (react-native-fetch-blob). There might be other libraries that have access to the FS as well but this one worked well for me.

**Comment by Harsh2402** [comment]
@Dror-Bar 
Thanks
