### ISSUE TITLE
Invalid bounds and dimensions returned by RNCamera onBarCodeRead on Android

### ISSUE THREAD

**Issue by rasmuslelumees** [react-native-community/react-native-camera#2077]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues? - [This bounds units one](https://github.com/react-native-community/react-native-camera/issues/2023) seems to be related.

**Related Modules**
RNCamera

**Platforms**
Android

**Versions**
- Android: 8.0
- iOS:
- react-native-camera: 1.9.2
- react-native: 0.57.2
- react: 16.5.1

**Description/Current Behaviour**

The `RNCamera` component `onBarCodeRead` method returns bounds with a structure different than specified in [the documentation](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#onbarcoderead) and with incorrect width/height values:
- Width and height correspond to the device screen width and height (not the scanned QR code)
- The bounds object does not seem to fit the object description in the docs

This is what I get when I log out the bounds on Android:
```
{
    width: 1440,
    height: 1080,
    origin: 
        [
            { y: '651.5', x: '824.0' },
            { y: '644.0', x: '633.5' },
            { y: '449.5', x: '644.0' },
            { y: '486.0', x: '810.5' }
        ]
}
```

**Expected Behaviour**
- Correct width and height for the bounds (or just remove them to avoid confusion)
- Similar bounds structure like iOS has or just update the documentation to match the reality - based on the results I got the bounds origin array has points in the following order: [ bottomRight, bottomLeft, topLeft, topRight ] which means it's something like this:
```
2 3
1 0
```
Also, as @KlemenS189 [pointed out](https://github.com/react-native-community/react-native-camera/issues/2023), the bounds seem to be incorrect.

**Steps to Reproduce**
1. Launch RNCamera on Android
2. Scan a QR code
3. Observe the bounds returned from `onBarCodeRead`

**UPDATE:** I've realised that the bound coordinates do not make sense because the app is in fixed portrait mode, but the coordinates provided by the RNCamera are expecting the device to be in landscape mode. Didn't find a way to lock the camera orientation in the docs though so keeping this issue open...

**Comment by ajaymore** [comment]
I am getting below output on Android and I can't understand what it means.

```
{"width":2048,"height":1536,"origin":[{"y":"960.0","x":"507.5"},{"y":"960.0","x":"1019.5"}]}
```

My device width X height is shown as 360 X 672.

**Comment by LouiseBC** [comment]
In case anyone is still struggling with this:
For the X and Y coords you can divide them by PixelRatio to get the correct values. This doesn't work for me with width and height (the values are still too large / incorrect), but you can calculate the width from the X-coords, which is good enough for my use case.

```typescript
import { PixelRatio } from 'react-native';

// ...
const pixelRatio = PixelRatio.get()
const leftX = parseFloat(bounds.origin[0].x) / pixelRatio;
const rightX = parseFloat(bounds.origin[1].x) / pixelRatio;
const y = parseFloat(bounds.origin[0].y) / pixelRatio;
const width = rightX - leftX;
```

This is something I would expect the library to fix, though. For iOS I have no such problems
