### ISSUE TITLE
use another variable name for googlePlayServicesVersion

### ISSUE THREAD

**Issue by wadehuang36** [react-native-community/react-native-camera#2079]
# Feature-Request

com.google.android.gms:play-services-vision have different version than other com.google.android.gms modules.  

I tried 15.0.2, but it caused problem with latest com.google.firebase modules
I tried 16.0.0, but here is no play-services-vision:16.0.0
and many versions.  I cannot find a version fit with all dependencies. and end up fork the project and changed gradle.build to read another variable like googlePlayServicesVisionVersion

**Comment by hariDasu** [comment]
@wadehuang36 would you mind linking to your fork? I have the same issue integrating with react-native-firebase in order to set up push notifications on android

**Comment by n1ru4l** [comment]
@ariDasu check out https://github.com/react-native-community/react-native-camera/pull/2112
