### ISSUE TITLE
tried to register two views with the same name GestureHandlerRootView

### ISSUE THREAD

**Issue by hackthemachin3** [react-native-community/react-native-camera#2080]
As you can see in the screenshot, I get the issue after i install react-navigation and react-gesture-handler
![screenshot_20190130-014721](https://user-images.githubusercontent.com/46753886/51952992-74ea7d00-2432-11e9-9b93-7397b64dd652.png)

**Comment by Marti0808** [comment]
What should I do

**Comment by SimonErm** [comment]
I think you ejected an Expo-App. If its true, you don't need to use react-native-gesture-handler since expo already use it and that causes the red screen. If you unlink react-native-gesture-handler it should work. Since this is not a react-native-camera issue, i will close it.
