### ISSUE TITLE
library not found for -lRCTCamera

### ISSUE THREAD

**Issue by masrc** [react-native-community/react-native-camera#2084]
Hey, guys! So, this week I'm making the RCTCamera to RNCamera migration.
I've followed [this doc](https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md) and on Android its working fine, however, on IOS I got this error: 

![screen shot 2019-01-31 at 15 17 00](https://user-images.githubusercontent.com/26003571/52072028-56d46800-256b-11e9-9b32-3a20a3047fd0.png)

Reinstall pod depencencies and running ```react-native link``` again doesn't show any effects. Any idea about to solve it?

**Version**
IOS: 11.3

"react": "16.0.0-alpha.12",
"react-native": "0.48.4",
"react-native-camera": "^1.9.0"

**Comment by n1ru4l** [comment]
@masrc Might be possible that `lRCTCamera.a` is still referenced in the `Link Binary With Libraries` section in the `Build Phases` tab on xcode and cannot be located.

**Comment by masrc** [comment]
Yep, its solved!! Thank u

**Comment by pabloimmediate** [comment]
Thanks, really useful!
