### ISSUE TITLE
RNCamera.Constants.BarCodeType.upce returns undefined

### ISSUE THREAD

**Issue by michalkow** [react-native-community/react-native-camera#2086]
# Bug Report
**To Do First**
- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Related Modules**
RNCamera

**Platforms**
Android
iOS

**Versions**
- Android: 26
- iOS: 12.1
- react-native-camera: 1.10.0
- react-native: 0.57.8
- react: 16.6.3

**Description/Current Behaviour**
RNCamera.Constants.BarCodeType.upce returns undefined

**Expected Behaviour**
RNCamera.Constants.BarCodeType.upce returns 'UPC_E'

**Steps to Reproduce**
console.log(RNCamera.Constants.BarCodeType.upce)

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by SimonErm** [comment]
Just a typo, should be upc_e instead. I am going to do a PR this weekend.
