### ISSUE TITLE
Support for camera shutter speed?

### ISSUE THREAD

**Issue by Xeoncross** [react-native-community/react-native-camera#2093]
# Feature-Request

**Describe the Feature**

Both Android and iPhone lenses support specifying shutter speed. By default they calculate the speed for you along with ISO and Aperture. It would be great to have access to camera shutter speed as an option. This would allow slow speeds for action blur, nicer water in landscape photos, high shutters for freezing fast-moving objects, etc...

On Android this seems to be be handled by reading and writing `Camera.Parameters`. I'm not sure how iOS handles this.

**Possible Implementations**

Android: it looks like different android phones [have different options](https://stackoverflow.com/a/37567225/99923) so you have to parse the camera parameters to see what options should be shown on the UI. (Example Android Code)

            Camera mCamera = Camera.open();
            Camera.Parameters params = mCamera.getParameters();

            String flatten = params.flatten();
            String[] paramsSeparated = flatten.split(";");
            for(String cur : paramsSeparated) {
                if(cur.contains("iso") && cur.contains("values")) {
                    ...
                }
            }

**Comment by sejas** [comment]
I think it's a great idea.
In my case, I need to increase the shutter speed to get less burry images.

**Comment by cinder92** [comment]
any update on this issue?
