### ISSUE TITLE
How use data URI

### ISSUE THREAD

**Issue by tomtomgo92** [react-native-community/react-native-camera#2094]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Hello I would like see my photo on <Image> Alert
but I have `undefined is not an object this.takePicture().data.uri` 

can use `this.takePicture().data.uri`  ?

```
 alertMessage() {
        // Works on both iOS and Android
        Alert.alert(
            'Alert Title',
            <Image source={{ uri: this.takeVideo().data.uri }} style={{ width: 40, height: 40 }} />,
            [
                {
                    text: 'Par Email',
                    onPress: () => this.handleEmail()
                },
                {
                    text: 'Annuler',
                    onPress: () => console.log('Cancel Pressed'),
                    style: 'cancel',
                },
                {
                    text: 'Par SMS',
                    onPress: () => this.smsFunction()
                },
            ],
            { cancelable: false },
        );
    }

```
**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by n1ru4l** [comment]
Please check the example app or the documentation: https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#rncamera

It seems like you do not understand the fundamentals of this library.

Also it is not possible to show images with https://facebook.github.io/react-native/docs/alert.

**Comment by tomtomgo92** [comment]
thank you :)
