### ISSUE TITLE
Image size of IOS is cropped even if the view is in full screen

### ISSUE THREAD

**Issue by moribaleta** [react-native-community/react-native-camera#2097]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by moribaleta** [comment]
the image resolution in Android is the same with the Android Camera App
but in IOS if the image is taken the output image resolution has lower height than the native IOS camera app

//'use strict';
import React from 'react';
import { Dimensions, StyleSheet, TouchableOpacity, TouchableHighlight, View, Image, ActivityIndicator } from 'react-native';
import SnackBar from 'rn-snackbar'
import { RNCamera } from 'react-native-camera';
import { HeaderButtonIconTemplate } from '../components/button_template'
import { ADD_IMAGE, GO_BACK, VIEW_GALLERY } from '../../store/image_store/image_action';
import { connect } from 'react-redux';
import { screen_size } from '../components/screen_size';

class PatientProfileCamera extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            path: null,
            images: null,
            isTaking: false
        };
        this.view_image = false
    }

    onLayout = (e) => {
        const { width, height } = Dimensions.get('window')
        console.log(width, height)
        this.forceUpdate()
    }

    static navigationOptions = ({
        navigation
    }) => {
        return {
            header: () => null
        }
    }

    componentWillReceiveProps(props) {
        this.setState({ path: props.curr_image })
    }

    _takePicture = () => {
        if (!this.state.isTaking) {
            try {
                if (this.camera) {
                    this.setState({ isTaking: true })
                    this.camera.takePictureAsync().then(data => {
                        console.log("image taken %o", data)
                        this.props.add_image(data.uri)
                        this.setState({ isTaking: false })
                        Image.getSize(data.uri, (width, height) => {
                            console.log("width: %o -- height: %o", width, height)
                        })
                    }).catch(err => {
                        this.setState({ isTaking: false })
                        throw err
                    })
                } else {
                    throw 'camera not available'
                }
            } catch (err) {
                console.log('err: ', err);
                SnackBar.show('error ' + err, {
                    confirmText: 'Close',
                    onConfirm: () => {
                        SnackBar.dismiss()
                    },
                    style: { opacity: 0.95 },
                    backgroundColor: '#33A0AF',
                    buttonColor: 'white',
                    textColor: 'white',
                    duration: 5000
                })
            }
        }
    }

    _renderCamera = () => {
        console.log(RNCamera)
        return (
            <RNCamera
                ref={(cam) => {
                    this.camera = cam;
                }}
                style={styles.preview}
                type={RNCamera.Constants.Type.back}
                forceUpOrientation={true}
                flashMode={RNCamera.Constants.FlashMode.off}
                permissionDialogTitle={'Permission to use camera'}
                permissionDialogMessage={'We need your permission to use your camera phone'}
            >
                <TouchableHighlight
                    style={styles.capture}
                    onPress={() => this._takePicture()}
                    underlayColor="rgba(255, 255, 255, 0.5)"
                >{
                        this.state.isTaking ?
                            <ActivityIndicator size="large"></ActivityIndicator> :
                            <View />
                    }</TouchableHighlight>
                <TouchableOpacity
                    style={styles.image_view}
                    onPress={() => { this._viewImage() }}
                >{this.state.isTaking ?
                    <ActivityIndicator size="large"></ActivityIndicator> :
                    (this.state.path != null) ?
                        <Image
                            source={{ uri: this.state.path }}
                            style={styles.image_preview}
                            resizeMode={'cover'}
                        /> : null
                    }</TouchableOpacity>
            </RNCamera>
        );
    }

    _viewImage = () => {
        this.props.view_gallery()
    }

    _onBackPress = () => {
        this.props.goBack()
    }

    render() {
        return (
            <View style={styles.container}>

                {this._renderCamera()}
                <View style={styles.header}>
                    <HeaderButtonIconTemplate
                        style={styles.back_view}
                        icon_style={styles.back_icon}
                        icon_name={'Arrow-L'}
                        onPress={this._onBackPress.bind(this)}
                    />
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#000',
    },
    back_view: {
        marginTop: 20,
    },
    back_icon: {
        color: 'white'
    },
    header: {
        minHeight: 50,
        width: '100%',
        paddingHorizontal: 5,
        paddingBottom: 10,
        position: 'absolute',
        top: 0,

    },
    preview: {
        flex: 1,
        justifyContent: 'flex-end',
        alignItems: 'center',
        height: screen_size.getDeviceSize().height,
        width: screen_size.getDeviceSize().width
    },
    capture: {
        width: 70,
        height: 70,
        borderRadius: 35,
        borderWidth: 5,
        borderColor: '#FFF',
        marginBottom: 15,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center'
    },
    cancel: {
        position: 'absolute',
        right: 20,
        top: 20,
        backgroundColor: 'transparent',
        color: '#FFF',
        fontWeight: '600',
        fontSize: 17,
    },
    image_view: {
        position: 'absolute',
        right: 10,
        bottom: 10,
        borderColor: 'gray',
        borderWidth: 1,
        backgroundColor: 'black',
        height: 80,
        width: 80,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center'
    },
    image_preview: {
        height: '100%',
        width: '100%',
    }
});

const mapStateToProps = (state, ownProps) => {
    return {
        curr_image: state.images[state.images.length - 1]
    }
}

const mapDispatchToProps = dispatch => {
    return {
        add_image: (image) => {
            dispatch(ADD_IMAGE(image))
        },
        view_gallery: () => {
            dispatch(VIEW_GALLERY)
        },
        goBack: () => {
            dispatch(GO_BACK)
        }
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(PatientProfileCamera)

**Comment by moribaleta** [comment]
![screen shot 2019-02-08 at 12 10 25 pm](https://user-images.githubusercontent.com/13190143/52458486-8eaa6380-2b9a-11e9-89e3-998a3d375e36.png)

the right side is the output from the Native IOS Camera app on the right was the result from the RNCamera

**Comment by moribaleta** [comment]
<img width="271" alt="screen shot 2019-02-08 at 12 12 39 pm" src="https://user-images.githubusercontent.com/13190143/52458524-de892a80-2b9a-11e9-9103-e14cc3920f4c.png">

**Comment by GaspardC** [comment]
@moribaleta I have the same issue, did you find a solution ?

**Comment by moribaleta** [comment]
> @moribaleta I have the same issue, did you find a solution ?

i made my own

**Comment by GaspardC** [comment]
@moribaleta awesome,  could you share with me how you did it?

**Comment by moribaleta** [comment]
> @moribaleta awesome, could you share with me how you did it?
@GaspardC 
https://github.com/moribaleta/ReactNative-NativeCameraIOS-Template
