### ISSUE TITLE
onTextRecognized with face detector

### ISSUE THREAD

**Issue by AlanSaracho** [react-native-community/react-native-camera#2098]
# Bug Report

Hi! I can use Face detector and text detector split, but when i try to active together only show a black screen without any preview.
Some ideas?

PD: This feature works very well on andorid.

**To Do First**
- [yes] Did you try latest release?
- [yes] Did you try master?
- [yes] Did you look for existing matching issues?

**Related Modules**
RNCamera

**Platforms**
iOS

**Versions**
- iOS: 12.1.3
- react-native-camera: 1.10.1
- react-native: 0.56.0
- react: 16.4.1

**Steps to Reproduce**

```
<RNCamera
    ref={ref => this.camera = ref}
    type={RNCamera.Constants.Type.back}
    onBarCodeRead={data => this.onBarCodeRead(data)}
    barCodeTypes={[RNCamera.Constants.BarCodeType.pdf417]}
    focusDepth={0.1}
    style={{height: capturedHeight, width: capturedWidth}}
    onFacesDetected={faces => this.onFaceDetected(faces)}
    onFaceDetectionError={() => this.setState({faceBlock: undefined})}
    defaultVideoQuality={RNCamera.Constants.VideoQuality["4:3"]}
    forceUpOrientation={RNCamera.Constants.Orientation.landscapeLeft}
/>
```

**Comment by St7-07** [comment]
Same happen to me, no results found on internet, and I can't achieve manual installation to prove that way, however in RNCamera docs remark that TextDetector can only be installed through CocoaPods
