### ISSUE TITLE
Front facing camera not detecting face

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [react-native-community/react-native-camera#2100]
# Bug Report
**To Do First**
- [Yes] Did you try latest release?
- [No] Did you try master?
- [No] Did you look for existing matching issues?

**Related Modules**
RNCamera
FaceDetector

**Platforms**
Android

**Description/Current Behaviour**
Front facing camera is not detecting face

**Expected Behaviour**
Front facing camera should detect face

**Steps to Reproduce**
Used example code provided for face detection

**Comment by ManigandanRaamanathan** [comment]
@n1ru4l guys any update on this issue? Can you please fix these 2 bugs on yaw angle value and front camera face detection?

**Comment by n1ru4l** [comment]
Please feel free to send a pull request to fix those issues. I have neither the time or the requirements to fix this behaviour. If you or your company rely on react-native-camera you might consider allocating time for working/improving on this library.

**Comment by prodoxx** [comment]
Hey @ManigandanRaamanathan , try installing React-Native Camera version 1.2.0 (or a lower version that is not latest). I got the latest version a yesterday and the face detection was not working properly. It was not detecting faces properly or it looked like it was too slow. I downgraded to 1.2.0 and it works fine now.

**Comment by ManigandanRaamanathan** [comment]
@prodoxx thanks for the info. Will try the older version and update here

**Comment by ManigandanRaamanathan** [comment]
@prodoxx is the front / selfie camera detects face on the version that you're using?

**Comment by prodoxx** [comment]
Yeah, I'm using version 1.2.0 right now and it detects it.

**Comment by ManigandanRaamanathan** [comment]
@prodoxx thanks for the update.

**Comment by darknblack** [comment]
Not working to me as well. It used to work but after updating react native from version .57.4 to 58.5 it stopped working. tried downgrading but still no good.

**Comment by darknblack** [comment]
Downgraded to 1.3.1 solves this problem.

**Comment by sibelius** [comment]
anybody can do a git bisect and check when there was this regression?

**Comment by darknblack** [comment]
> anybody can do a git bisect and check when there was this regression?

I checked my package-json.lock before and after I update the packages and here's what i found out.

1.12.0 = facial recognition working but back camera only
1.3.1 = facial recognition working both back and front camera

**Comment by williamgurzoni** [comment]
Same problem. I downgrade to 1.3.1 and it works, but yawAngle don't.

**Comment by sibelius** [comment]
@williamgurzoni can you try v2 using MLKit

**Comment by HorusGoul** [comment]
@sibelius 

v2 seems to have this issue as the face detector doesn't detect my face properly with the front camera

**Comment by Avdhutk** [comment]
> @sibelius
> 
> v2 seems to have this issue as the face detector doesn't detect my face properly with the front camera

Any updates on this? Facing same issue with V2.3.0.

**Comment by sibelius** [comment]
@Avdhutk can you debug on native code?

**Comment by Avdhutk** [comment]
> @Avdhutk can you debug on native code?

Yes

**Comment by Avdhutk** [comment]
I need to use MLKit but facing problem in face detecting by front camera with latest version. 
Front camera not returning correct bounds and eye positions. Stucked due to this.

**Comment by o-alexandrov** [comment]
Please forgive the comment that might seem as a 👍 alternative.
Just wanted to ask the maintainers for the preferable reproduction example for you to see that the front facing camera is not capable of doing face detection.

Personally, I didn't try the MLKit, but precisely followed every single step for the default face detection.
