### ISSUE TITLE
cocopods

### ISSUE THREAD

**Issue by ZHkkk** [react-native-community/react-native-camera#2107]
# Bug Report

[!] CocoaPods could not find compatible versions for pod "react-native-camera":
  In Podfile:
    react-native-camera (from `./React/node_modules/react-native-camera`)

cocopods  platform  8.0

**Comment by n1ru4l** [comment]
We cannot help you without more information.

**Comment by n1ru4l** [comment]
You are resolving the `react-native-camera` podfile from the wrong directory. Please check the readme/cocoapods setup guide.
