### ISSUE TITLE
Deprecate `permissionDialogTitle` and `permissionDialogMessage` in favor of `androidCameraPermissionOptions` and `androidRecordAudioPermissionOptions`

### ISSUE THREAD

**Issue by n1ru4l** [react-native-community/react-native-camera#2110]
# Feature-Request

**Describe the Feature**
Instead of having different properties like:

- `permissionDialogTitle`
- `permissionDialogMessage`
- `permissionButtonPositive` (not implemented yet)
- `permissionButtonNegative` (not implemented yet)
- `permissionsButtonNeutral` (not implemented yet)

We should have a better approach:

- `androidCameraPermissionOptions`
- `androidRecordAudioPermissionOptions`

This would solve the following issues:

- Show different text/dialogues for requesting camera permissions and requesting audio record permissions
- We reduce the amount of properties on `RNCamera` and do not need to add new properties in case there are new options added for [`PermissionsAndroid.request`](https://facebook.github.io/react-native/docs/permissionsandroid#request)

**Possible Implementations**
- Deprecate `permissionDialogTitle` and `permissionDialogMessage` aka show warning
- Use `permissionDialogTitle` and `permissionDialogMessage` if `androidCameraPermissionOptions` or `androidRecordAudioPermissionOptions` is not set

**Related Issues**

#1849
https://github.com/facebook/react-native/pull/23510

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by kulak-at** [comment]
Hey, I'm working on PR for this issue.

**Comment by kulak-at** [comment]
This task is now resolved in 2.4.0 after #2206 has been merged.
