### ISSUE TITLE
[RCTCamera] scaling down images

### ISSUE THREAD

**Issue by pavermakov** [react-native-community/react-native-camera#2122]
# Question

**To Do First**
- [+] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [+] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [+] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Due to the legacy state of the project I am working on, I am forced to use the old RCTCamera module. On iphoneX emulator images come out really big (2160 by 3840). Is there a way to scale images down?

**Comment by Kielan** [comment]
This is also an issue with RNCamera module and I think should be discussed openly on a main issue thread :)

**Comment by SimonErm** [comment]
I think on RCTCamera you can use the captureQuality Prop:
 https://github.com/react-native-community/react-native-camera/blob/master/docs/RCTCamera.md#capturequality 
On RNCamera you can do the same with the width option:
 https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#takepictureasyncoptions-promise

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
