### ISSUE TITLE
barcode can not be recognized 

### ISSUE THREAD

**Issue by ChenChuanzhen** [react-native-community/react-native-camera#2127]
In my project, some barcode are not be recognized, such as
![img_0946](https://user-images.githubusercontent.com/29937685/53547015-d5bbc100-3b68-11e9-9e7f-dd15664efa45.JPG).How I can improve it?

**Comment by ChenChuanzhen** [comment]
Does someone can tell me how I can improve it?

**Comment by kunalkp** [comment]
We need negative case prevention like this. Even in my project, I am looking for something to handle when the barcode is not readable. Camera should response with error after a given time to read the barcode.

**Comment by sibelius** [comment]
please share some code or some repro

**Comment by Thomazella** [comment]
> I am looking for something to handle when the barcode is not readable. The camera should respond with an error after a given time to read the barcode.

@sibelius you think this is something worth implementing as a feature? Looking for some projects with native ios code to contribute to

**Comment by sibelius** [comment]
I'm not sure if this is android or ios related

**Comment by kunalkp** [comment]
This is not OS specific. In general we don't get any error when Barcode is not readable if it's blur or any other reason.  It should be a must feature to implement.

**Comment by andresmtz98** [comment]
Is there a way to improve the barcode reading in cameras with low resolution (old devices)?
