### ISSUE TITLE
investigate unimodules approach

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#2130]
https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331
https://blog.expo.io/flutter-unimodules-bb66b9bf21de

Unimodules looks like a great idea for this project

we could let user provide some native code behavior like custom object detection logic, and also make it more maintanable

like having more modular modules (barcode scanner, face recognition, core camera)

**Comment by araujobarret** [comment]
I like the idea.

Do we have a profiling data from the current lib status? The idea is to have a stable current performance consumption to do a simple comparison with unimodules to check if the performance will be increased as well.
