### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): Error: Permission denied (while saving the image via "CameraRoll.saveToCameraRoll()")

### ISSUE THREAD

**Issue by aujisti-ador** [react-native-community/react-native-camera#2131]
![screenshot 2019-03-04 at 12 48 35 pm](https://user-images.githubusercontent.com/25290075/53715761-0491aa00-3e7d-11e9-86f7-b528886cdd88.png)
I am getting Permission denied when trying to save the image to the gallery via "CameraRoll.saveToCameraRoll()" from react native. my code is below==>

`takePicture = async function() {`
    `if (this.camera) {`
      `  const data = await this.camera.takePictureAsync();`
      `  let saveResult = CameraRoll.saveToCameraRoll(data.uri);`
     `   console.warn('takePicture ', saveResult);`
      `  console.warn('picture url ', data.uri);`
   ` }`
 ` };`

i have taken permissions from android manifest and ios by adding required codes.
(On Android)
![screenshot 2019-03-04 at 12 50 27 pm](https://user-images.githubusercontent.com/25290075/53716077-e4aeb600-3e7d-11e9-84a9-218d778c2136.png)

even in ios i am getting the same permission denied error. what should i do to work it. i don't wanna try RN File system.

**Comment by n1ru4l** [comment]
I am going to close this as it is unrelated to `react-native-camera`. Please check the `react-native` documentation and follow the instructions. You will need to link the library as well as performing the actions described in the `Permissions` section.
