### ISSUE TITLE
Migration guide to v2

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#2139]
docs/migrationV2.md would be really helpful to make it easy to migrate to v2

based on this pull request https://github.com/react-native-community/react-native-camera/pull/2075

@dov11 can you help us writing this migration guide?

**Comment by dov11** [comment]
Yes, this is indeed needed, I will give it a try

**Comment by sibelius** [comment]
fixed here https://github.com/react-native-community/react-native-camera/blob/master/docs/migrationV2.md

tks
