### ISSUE TITLE
Is it possible to render camera in a circle / shape?

### ISSUE THREAD

**Issue by williamgurzoni** [react-native-community/react-native-camera#2146]
I've tried all this options, with no success:

- RNCamera inside a circular SVG
- RNCamera with radius border
- RNCamera inside circular View

**Comment by madhumatip** [comment]
yes ,
you can apply style to RNCamera 
for eg. camera: {
        height: hp('40%'),
        width: hp('40%'),
        borderRadius: hp('20%'), 
    }

**Comment by sibelius** [comment]
please add this to the docs

**Comment by williamgurzoni** [comment]
Hey @madhumatip, I tried this, but no success. Am I doing something wrong?

`<RNCamera
          style={{ height: hp('40%'), width: hp('40%'), borderRadius: hp('20%'), }}
...`

**Comment by madhumatip** [comment]
can please share your code because it works for me

**Comment by darekg11** [comment]
We are also doing this in `circle` shape with following styles (working on both IOS and Android):
```
            <View style={ styles.preview }>
              <RNCamera
                ref={ cam => {
                  this.camera = cam
                } }
                style={ styles.camera }
                type={ RNCamera.Constants.Type.front }
                flashMode={ RNCamera.Constants.FlashMode.on }
                ratio={ '16:9' }
              />
            </View>
```

```
  preview: {
    height: 240,
    width: 240,
    borderRadius: 120,
    overflow: 'hidden'
  },
  camera: {
    height: 240,
    width: 240
}
```
`React-Native-Camera`: `1.1.2`

Let me know if this would give you results closer to what you want to achieve, I can also fork the repo and do it on the demo app.

**Comment by liangguohun** [comment]
i want to know if use RNCamera.Constants.Type.front the photo result will yours' like the camera show or change direct

**Comment by MateusAndrade** [comment]
> i want to know if use RNCamera.Constants.Type.front the photo result will yours' like the camera show or change direct

If you are asking about the picture orientation, i think this will change the direction. You can found more about this on the instructions provided on the DOCS.
