### ISSUE TITLE
App Does not run on iOS Device

### ISSUE THREAD

**Issue by edgarberlinck** [react-native-community/react-native-camera#2160]
# Question

**To Do First**
- [ x ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ x ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ x ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
My app does not run on iOS Device. If I try to run using xcode I got the following error:

```
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I got no Errors using React-scripts, but nothing happens:

```
installing and launching your app on iPhone de dev1...
** INSTALLATION SUCCEEDED **
```

**Tags**
IOS

**Comment by darekg11** [comment]
This is most probably not related to `react-native-camera`  but to invalid config of your environment. 
Try cloning the repo and try to run example app: https://github.com/react-native-community/react-native-camera/tree/master/examples/basic
