### ISSUE TITLE
Avoid including mlkit face model

### ISSUE THREAD

**Issue by mllrmat** [react-native-community/react-native-camera#2165]
# Question

**Ask your Question**
How can I avoid that the mlkit face detection model is included in the APK? I am just using barcode scanning capabilities, and the face model grows my APK by 9MB. 

**Tags**
Android, mlkit, apk size

**Comment by sibelius** [comment]
try this

https://github.com/react-native-community/react-native-camera/blob/master/examples/basic/android/app/build.gradle#L106

`missingDimensionStrategy 'react-native-camera', 'general'`

this will avoid adding `MLKit` to your android app

**Comment by mllrmat** [comment]
Ok. I thought that mlkit will greatly improve the barcode detection capabilities. Shouldn't the face detection model only be added if face detection is enabled? 

eg. This line in the modules build.gradle removed in all other cases: 
mlkitImplementation "com.google.firebase:firebase-ml-vision-face-model:17.0.2"

**Comment by sibelius** [comment]
I don't think we can detect this on build time

user needs to explicit opt in or opt out of this feature

**Comment by mllrmat** [comment]
Couldn't you add a gradle buildType/flavor similar to the ios subspecs?

**Comment by sibelius** [comment]
isn't `missingDimensionStrategy` the same?

**Comment by mllrmat** [comment]
As far as I understand it this way you opt-out of mlkit completely, what I am asking for is to use mlkit for barcode recognition without importing the face model (I do not use face recognition). This way I can use the upside of mlkit without increasing the APK size dramatically. 
One possible solution could be to import react-native-camera with exclude of the face model: 
```
implementation (project(':react-native-camera')){
    exclude group: 'com.google.firebase', module: 'firebase-ml-vision-face-model'
}
```

**Comment by sibelius** [comment]
feel free to send a pull request if you find a nice solution for your problem

**Comment by mllrmat** [comment]
For me the above works. But I guess the better solution would be to have a productFlavor for mlkit text + barcode and another for face recognition. But I am not an gradle expert.

**Comment by mllrmat** [comment]
Thank you for your quick support!
