### ISSUE TITLE
Flash not working with Video

### ISSUE THREAD

**Issue by cristianocca** [react-native-community/react-native-camera#2171]
# Bug Report

**Related Modules**

RNCamera

**Platforms**
Android

**Versions**
- Android: 7 (Motorola G5) / Android 8 (Mi mix 2) / Android 9 (Pixel 2)
- react-native-camera: 2.0.2
- react-native: 0.59.2
- react: 16.8.5

Using `<RNCamera flashMode={'on'} ...others/>` and even loading flashMode from a state variable that is changed on demand, the flash is always off when recording a video with `camera.recordAsync({quality: '480p'})`

Funny thing is, even if flash is set to torch, it gets immediately turned off when recording starts, and turned on again when recording stops. Should a flash option be set when calling recordAsync?

**Comment by cristianocca** [comment]
Any updates on this? Is it a library restriction instead?

**Comment by cristianoccazinsp** [comment]
https://github.com/react-native-community/react-native-camera/pull/2543 fixes torch while recording on both Android and iOS
