### ISSUE TITLE
Android Studio new version error

### ISSUE THREAD

**Issue by Niroj11** [react-native-community/react-native-camera#2175]
I have encountered this error after I upgraded to new version of android studio

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-camera.
Open File
Show Details

Gradle not able to sync

**Comment by sibelius** [comment]
Post full stack trace

**Comment by lessp** [comment]
Running in to the same error with React Native 0.59, any ideas?

**Comment by Niroj11** [comment]
I setup a fresh react native project with all the latest version of the packages that I was using. It still showed me some errors in version 0.59 so I downgraded to 0.58 and it is working fine now. I could not solve the issue so I copied all my project into a new fresh project
