### ISSUE TITLE
mirrorVideo doens't work for Videos - rn 0.59.1 & Android 9

### ISSUE THREAD

**Issue by emilemoureau** [react-native-community/react-native-camera#2176]
**- startRecording**

```javascript
this.camera.recordAsync({ mirrorVideo: true });
```

"react-native-video": "^4.4.0",

**- renderVideo**

```javascript
<Video 
  source={{ uri: this.state.uri}}
  ref={(ref) => {
   this.player = ref
   }}
  fullscreen={false}
  repeat={true}
  volume={1.0}
/>
```

Everything works perfectly on iOS!

**Comment by susanapons89** [comment]
Having the same issue. Did you find a solution?

**Comment by emilemoureau** [comment]
Not really..

Try to work around the problem with "transform" :

> https://facebook.github.io/react-native/docs/transforms

```javascript
<Video
  source={{ uri: uri }}
  style={{
    transform: [{ rotate: '270deg'}, { scaleX: -1.8 }, { scaleY: 1.8}]
  }}
/>
```

**Comment by victorwpbastos** [comment]
same problem here.

**Comment by asarasua** [comment]
Same issue here, adding `mirrorVideo: true` in the options has no effect.
