### ISSUE TITLE
example not working - android

### ISSUE THREAD

**Issue by ggunti** [react-native-community/react-native-camera#2177]
I just tried to run the mlkit example for android following the documentation: https://github.com/react-native-community/react-native-camera/tree/master/examples/mlkit

But this is what I get:
<img width="1680" alt="Captură de ecran din 2019-03-31 la 13 53 16" src="https://user-images.githubusercontent.com/26307699/55288213-d1c7cc80-53bc-11e9-9498-a4aee19c4093.png">

```
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.1"
}
```

I also tried to `npm install --save react-native-camera` but nothing changed

**Comment by sibelius** [comment]
Have you ran yarn on both root and examples projects?

**Comment by ggunti** [comment]
@sibelius you are right. You solved the problem. But now just appeared a new one:
Inside `./mlkit/android/app/build.gradle` I just changed the applicationId from "com.mlkit" into "com.gothasoft.react_native_camera_example" which is my app id provided by firebase - seems that it is required to change it (see screenshot 1)

Screenshot 1:
<img width="637" alt="Captură de ecran din 2019-03-31 la 18 58 25" src="https://user-images.githubusercontent.com/26307699/55291444-46176580-53e7-11e9-88fb-d4e4dabf3e39.png">

Now, the problem is the following:
<img width="570" alt="Captură de ecran din 2019-03-31 la 19 01 34" src="https://user-images.githubusercontent.com/26307699/55291473-7eb73f00-53e7-11e9-9526-d7a9ce02094e.png">


It says that MainActivity does not exist.

**Comment by dov11** [comment]
You need to change `package com.mlkit;` to `package com.gothasoft.react_native_camera_example;`
In MainActivity.java and MainApplication.java. Change the folder structure of these files to
```
com
|
 __gothasoft
  |
   __react_native_camera_example
```
You will need to rename package in your android manifest 
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.mlkit">
```
