### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by shtengel** [react-native-community/react-native-camera#2179]
Build is failing when adding react-native-camera as a dependency in build.gradle (app),
saw it happen to someone else here but no one replied... anyone know how to fix it ?
i tried to exclude com.facebook from react-native-camera but it does nothing 

# Bug Report
**To Do First**
- [ V] Did you try latest release?
- [ V] Did you try master?
- [V ] Did you look for existing matching issues?

**Related Modules**

**Platforms**

**Versions**
- Android: 28
- react-native-camera: 2.1.1
- react-native: 0.51.1
- react: 16.0.0

**Description/Current Behaviour**
AGPBI: {"kind":"error","text":"Program type already present: com.facebook.infer.annotation.Mutable","sources":[{}],"tool":"D8"}

Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForX86Debug'.
  Program type already present: com.facebook.infer.annotation.Mutable

**Steps to Reproduce**
Add react-native-camera as a dependency to gradle

**Comment by shtengel** [comment]
commenting out `implementation 'com.facebook.infer.annotation:infer-annotation:+'` makes it to build succesfully

**Comment by sibelius** [comment]
Where?

**Comment by shtengel** [comment]
works if i change it to `implementation com.facebook.infer.annotation:infer-annotation:10.0.0`
in `react-native-camera->build.gradle`

**Comment by Strate** [comment]
Can confirm that issue exists, and confirm that commenting out `implementation 'com.facebook.infer.annotation:infer-annotation:+'` fixes issue

**Comment by sibelius** [comment]
can somebody send a pull request that solve this?

**Comment by Strate** [comment]
@sibelius just with commenting line? I am not sure that exactly happens, for example I don't use mlkit, maybe this is related.

**Comment by tadeumx1** [comment]
@sibelius I can work on this

**Comment by shtengel** [comment]
If you comment out then you can build but then runtime exception is thrown ( in my case)
