### ISSUE TITLE
timer set for camera

### ISSUE THREAD

**Issue by pankajmonga12** [react-native-community/react-native-camera#219]
can you tell is there any property to set timer for camera capture image automatically ?

**Comment by rt2zz** [comment]
you can just use a `setTimeout(() => { this.refs.camera.capture()})`

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
