### ISSUE TITLE
RNCamera preview freezes and closes the app if there are multiple instances being rendered

### ISSUE THREAD

**Issue by LautaroMir93** [react-native-community/react-native-camera#2192]
# Bug Report
**To Do First**
- [ + ] Did you try latest release?
- [ + ] Did you try master?
- [ + ] Did you look for existing matching issues?

**Related Modules**
RNCamera

**Platforms**
Android

**Versions**
react-native-camera: 2.2.1
react-native: 0.59.3

**Description/Current Behaviour**
Hi! I'm trying to build a horizontal swiper that renders multiple RNCamera previews. However, when I try to do this, the previews freezes and the app closes. This could be solved by rendering just one instance of the RNCamera component at a time. But I would really like to show the two previews simultaneously during the transition of the swipe. 

**Expected Behaviour**
To be able to show multiple RNCamera previews simultaneously 

**Steps to Reproduce**
Just render two instances of the RNCamera component.

**Comment by azhaubassar** [comment]
same problem :(
