### ISSUE TITLE
Does this Component support QR Scanning in android ???

### ISSUE THREAD

**Issue by rameshvishnoi90904** [react-native-community/react-native-camera#221]

**Comment by drakmail** [comment]
There are PR: https://github.com/lwansbrough/react-native-camera/pull/229

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
