### ISSUE TITLE
provide a real-life use case example

### ISSUE THREAD

**Issue by ppaul** [react-native-community/react-native-camera#2212]
# Question
Could you please provide a detached example, in which you just use the library as anyone would use it in their project? I tried for 2 days but could not manage to get it working along with a firebase auth starter project. The existing basic example use the library from upper folder, which is not the case for all real life projects where it's used. So I think it's more reasonable to do examples for real use cases, than to avoid it to be copied again into node_modules - that's really insignificant benefit, IMHO.
Thank you

**Comment by sibelius** [comment]
feel free to create one and link to the docs

the only difference is how we manage our metro.config.js so we don't have duplicated package on node_modules

**Comment by MateusAndrade** [comment]
I used this project on my daily job. I think i got a private repo, using this library. i can send url to attach this on the docs.

**Comment by ppaul** [comment]
it's OK now. I was struggling a lot mainly because some libs get updated and I had errors which people didn't got on stackoverflow at the moment code was released
