### ISSUE TITLE
[self.previewLayer removeFromSuperlayer] is called on sub thread

### ISSUE THREAD

**Issue by VividLiu** [react-native-community/react-native-camera#2213]
# Bug Report
**To Do First**
- [ ] Did you try latest release?
- [ ] Did you try master?
- [ yes ] Did you look for existing matching issues?

**Related Modules**

RCTCamera

**Platforms**

iOS platform

**Versions**

- Android:
- iOS: iPhone 10
- react-native-camera: 0.3.8
- react-native: rn 55.4
- react:

**Description/Current Behaviour**

We got a crash in RCTCamera as follows: 
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <CALayerArray: 0x2812e8ab0> was mutated while being enumerated.'

3                             -[UIView(Hierarchy) _makeSubtreePerformSelector:withObject:withObject:copySublayers:] + 344
4                             __UIViewWasRemovedFromSuperview + 136
5                             -[UIView(Hierarchy) removeFromSuperview] + 464
6                             -[RCTCamera removeFromSuperview] (RCTCamera.m:108)
7                             -[UIView dealloc] + 464

After diving in, we found one of the UIKit method  removeFromSuperlayer is called in a sub thread instead of main thread which is a very bad idea. 
https://github.com/react-native-community/react-native-camera/blob/master/ios/RCT/RCTCameraManager.m#L526

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
RTCamera is deprecated

can you try with RNCamera?

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
