### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by Jeijie** [react-native-community/react-native-camera#2216]
React Native Environment Info:
  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 8.64 GB / 15.88 GB
  Binaries:
    Node: 8.12.0 - F:\install\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Users\GDYT\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - F:\install\nodejs\npm.CMD

  "react": "16.8.3",
   "react-native": "0.59.5",
    "react-native-camera": "^2.6.0",

     buildToolsVersion = "28.0.3"
     minSdkVersion = 16
     compileSdkVersion = 28
     targetSdkVersion = 28
     supportLibVersion = "28.0.0"

  

**Description/Current Behaviour**

FAILURE: Build failed with an exception.

*
 What went wrong:
Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
> Could not resolve com.google.zxing:core:3.3.3.
  Required by:
      project :app > project :react-native-camera
   > Could not resolve com.google.zxing:core:3.3.3.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/goog
le/zxing/core/3.3.3/core-3.3.3.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/google/zxi
ng/core/3.3.3/core-3.3.3.pom'. Received status code 400 from server: Bad Request

   > Could not resolve com.google.zxing:core:3.3.3.
      > Could not get resource 'https://jcenter.bintray.com/com/google/zxing/cor
e/3.3.3/core-3.3.3.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/google/zxing/core/3.3.
3/core-3.3.3.pom'. Received status code 400 from server: Bad Request
> Could not resolve com.drewnoakes:metadata-extractor:2.11.0.
  Required by:
      project :app > project :react-native-camera
   > Could not resolve com.drewnoakes:metadata-extractor:2.11.0.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/drew
noakes/metadata-extractor/2.11.0/metadata-extractor-2.11.0.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/drewnoakes
/metadata-extractor/2.11.0/metadata-extractor-2.11.0.pom'. Received status code
400 from server: Bad Request
   > Could not resolve com.drewnoakes:metadata-extractor:2.11.0.
      > Could not get resource 'https://jcenter.bintray.com/com/drewnoakes/metad
ata-extractor/2.11.0/metadata-extractor-2.11.0.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/drewnoakes/metadata-ex
tractor/2.11.0/metadata-extractor-2.11.0.pom'. Received status code 400 from ser
ver: Bad Request
> Could not resolve com.google.android.gms:play-services-vision-common:[17.0.2].

  Required by:
      project :app > project :react-native-camera > com.google.android.gms:play-
services-vision:17.0.2
   > Failed to list versions for com.google.android.gms:play-services-vision-com
mon.
      > Unable to load Maven meta-data from https://dl.google.com/dl/android/mav
en2/com/google/android/gms/play-services-vision-common/maven-metadata.xml.
         > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/an
droid/gms/play-services-vision-common/maven-metadata.xml'. Received status code
400 from server: Bad Request
   > Failed to list versions for com.google.android.gms:play-services-vision-com
mon.
      > Unable to load Maven meta-data from https://jcenter.bintray.com/com/goog
le/android/gms/play-services-vision-common/maven-metadata.xml.
         > Could not get resource 'https://jcenter.bintray.com/com/google/androi
d/gms/play-services-vision-common/maven-metadata.xml'.
            > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/
play-services-vision-common/maven-metadata.xml'. Received status code 400 from s
erver: Bad Request
> Could not resolve net.minidev:json-smart:[1.3.1,2.3].
  Required by:
      project :app > project :react-native-code-push > com.nimbusds:nimbus-jose-
jwt:5.1
   > Failed to list versions for net.minidev:json-smart.
      > Unable to load Maven meta-data from https://jcenter.bintray.com/net/mini
dev/json-smart/maven-metadata.xml.
         > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/ma
ven-metadata.xml'. Received status code 400 from server: Bad Request
   > Failed to list versions for net.minidev:json-smart.
      > Unable to load Maven meta-data from https://dl.google.com/dl/android/mav
en2/net/minidev/json-smart/maven-metadata.xml.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/net/m
inidev/json-smart/maven-metadata.xml'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/net/minidev
/json-smart/maven-metadata.xml'. Received status code 400 from server: Bad Reque
st

**Expected Behaviour**
build success

**Steps to Reproduce**
1. react-native init project
2.config the android platform 
3.npm install --save react-native-camera and react-native link react-native-camera
4.cd android &&  ./gradlew assembleRelease

**Comment by muhammadridho** [comment]
i has same issue too, do you've solve it @Jeijie ?
