### ISSUE TITLE
  In Android environment, I switched on the flashlight at the same time when I scanned the code and sent the wrong message.

### ISSUE THREAD

**Issue by ymw2017** [react-native-community/react-native-camera#2219]
The error log is as follows:
camera_in_use(4):setTorchMode:1466:Torch for camera "0" is not available due to an existing camera user

How can I turn on the flashlight while sweeping the code?Thank you.

**Comment by alizorlu** [comment]
> The error log is as follows:
> camera_in_use(4):setTorchMode:1466:Torch for camera "0" is not available due to an existing camera user
> 
> How can I turn on the flashlight while sweeping the code?Thank you.

[https://github.com/react-native-community/react-native-camera/issues/2220#issuecomment-485138836](url) might help you

**Comment by ymw2017** [comment]
@alizorlu  Thank you very much for helping me solve this problem.

**Comment by Macieyou** [comment]
> @alizorlu Thank you very much for helping me solve this problem.

Hi @ymw2017 
I have the same problem. How exactly did you solve this?
