### ISSUE TITLE
Android app crashed when turn on-off camera flash light.

### ISSUE THREAD

**Issue by akashmi** [react-native-community/react-native-camera#2220]
# Bug Report

Android app is crashing when trying
![Screenshot_20190420-181715](https://user-images.githubusercontent.com/11882168/56457454-d3bbf480-6398-11e9-9e14-5d3b9268b6f2.jpg)
 to turn on-off camera flash in my one plush5 device.
It is working fine in iOS and other Android devices.

**Comment by alizorlu** [comment]
Heyy , RNCamera ,view code ? take a screen shot and add there please

**Comment by akashmi** [comment]
```
 <RNCamera
                        ref={ref => {
                            this.camera = ref;
                        }}
                        style={{
                            flex: 1,
                            backgroundColor: '#EBEBEB'
                        }}
                        type={this.state.cameraMode}
                        flashMode={this.state.flashMode}
                    />

```

**Comment by alizorlu** [comment]
> Here is RNCamera view code
> 
> ```
> <RNCamera
>                        ref={ref => {
>                            this.camera = ref;
>                        }}
>                        style={{
>                            flex: 1,
>                            backgroundColor: '#EBEBEB'
>                        }}
>                        type={this.state.cameraMode}
>                        flashMode={this.state.flashMode}
>                    />
> ```

![git](https://user-images.githubusercontent.com/24724027/56459658-2c8e8b80-639f-11e9-9aad-226940c10c26.PNG)

would you try again image suggestion @akashmi

**Comment by akashmi** [comment]
> > Here is RNCamera view code
> > ```
> > <RNCamera
> >                        ref={ref => {
> >                            this.camera = ref;
> >                        }}
> >                        style={{
> >                            flex: 1,
> >                            backgroundColor: '#EBEBEB'
> >                        }}
> >                        type={this.state.cameraMode}
> >                        flashMode={this.state.flashMode}
> >                    />
> > ```
> 
> ![git](https://user-images.githubusercontent.com/24724027/56459658-2c8e8b80-639f-11e9-9aad-226940c10c26.PNG)
> 
> would you try again image suggestion @akashmi
> 
> **Note : RNCamera <= import statement**

@alizorlu Yes. I tried it but still getting the same issue.

**Comment by MateusAndrade** [comment]
@akashmi you can give a try with the example app? Please give a look at: https://github.com/react-native-community/react-native-camera/tree/master/examples/basic

**Comment by akashmi** [comment]
@MateusAndrade I tried it. still getting the same issue in Motorola devices. it is working fine in oneplush device.

**Comment by anujraghuvanshi** [comment]
Still getting in 2022. Anybody with possible reasons ?
