### ISSUE TITLE
Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity.

### ISSUE THREAD

**Issue by icxcat** [react-native-community/react-native-camera#2224]
Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity.

**Comment by sibelius** [comment]
can you give more info? and more logs?

please use issue template

**Comment by icxcat** [comment]
Hello，Sorry, I am using a mobile phone to edit.

I am using the RN version of 0.59.4. Manually add the camera to the project according to the documentation. iOS can run normally, but Android throws an error.  I have configured permissions in Android.

**Comment by icxcat** [comment]
IOS
![734535AD-054E-4099-A19F-CBCC7AA3CBC4](https://user-images.githubusercontent.com/22029390/56502214-2980d000-6544-11e9-80bd-3714018a7b4e.png)

Android
![7C175DD9-A33B-4CEA-9969-7F405A7B3ACB](https://user-images.githubusercontent.com/22029390/56502247-474e3500-6544-11e9-8621-19fed8b427f2.jpeg)

**Comment by icxcat** [comment]
```
b914c9eb-f5ef-420a-8bc4-4fcc6895e23d:67187 Possible Unhandled Promise Rejection (id: 0):
Error: Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity.
Error: Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity.
    at createErrorFromErrorData (blob:file:///b914c9eb-f5ef-420a-8bc4-4fcc6895e23d:2108:17)
    at blob:file:///b914c9eb-f5ef-420a-8bc4-4fcc6895e23d:2060:27
    at MessageQueue.__invokeCallback (blob:file:///b914c9eb-f5ef-420a-8bc4-4fcc6895e23d:2627:18)
    at blob:file:///b914c9eb-f5ef-420a-8bc4-4fcc6895e23d:2358:18
```

**Comment by cipherGG** [comment]
do u fix this?

**Comment by mattprivman** [comment]
To fix this, implement PermissionAwareActivity in the root ReactNative.java file. 

This [Stackoverflow answer](https://stackoverflow.com/a/45879293/2209974) provides a good example of what needs to be done.

**Comment by helciofranco** [comment]
Any solution? This is happening just in Android.
