### ISSUE TITLE
Not working on react-native v-59.5

### ISSUE THREAD

**Issue by fouad1994** [react-native-community/react-native-camera#2226]
I am trying to link react-native-camera on android but I get this error when I build gradle
<img width="1657" alt="Screen Shot 2019-04-23 at 1 10 02 PM" src="https://user-images.githubusercontent.com/35866405/56573320-7f4b8b80-65c9-11e9-991e-1ef737f6cd67.png">

**Comment by vernala** [comment]
i have same problem，it’s only in android sudio3.4，

**Comment by fouad1994** [comment]
> i have same problem，it’s only in android sudio3.4，

So what we have to do I see it doesn't see the path of react-native-camera

**Comment by rphlmr** [comment]
Same problem with 0.59.4 :(

**Comment by vernala** [comment]
> Same problem with 0.59.4 :(
> 
> I try #2138 and it seems work.

yes，it works，thks
