### ISSUE TITLE
getting Frames from Camera

### ISSUE THREAD

**Issue by eranabir** [react-native-community/react-native-camera#2227]
# Feature-Request

**Describe the Feature**
is there a way to receive the frames from the camera to the client ? 

**Possible Implementations**
i tried on IOS to get it from the captureOutput function in RNCamera.m
but no luck 

would love if it will be like that :

```javascript 

handleFrame=(frame)=>{console.log(frame)}

<RNCamera
      onFrame={this.handleFrame}/>

````

**Comment by sibelius** [comment]
this would be slow

**Comment by eranabir** [comment]
i can live with it :)

**Comment by c1ngular** [comment]
how about getting the video stream ?

**Comment by hartatovich** [comment]
> this would be slow

why this would be slow if the frames coming from the native code ?

the idea here is to get the frames in native code and then just send them to the js or am i missing something here ?

from what i understand if we break the frames in the js it self then everything will become super slow..

would love to hear your thoughts @sibelius

**Comment by sibelius** [comment]
passing big chunks of data in the bridge is slow

you can implement on a PR and we can test more

**Comment by tvhieuit** [comment]
How to use RNCamera with posenet.
https://github.com/jscriptcoder/tfjs-posenet
