### ISSUE TITLE
Camera does not auto focus or manual focus FRONT FACING

### ISSUE THREAD

**Issue by mikerodham** [react-native-community/react-native-camera#2231]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

iOS

**Versions**

- Android: N/A
- iOS: 12.1.4
- react-native-camera: ^2.1.1
- react-native: 0.57.7
- react: 16.6.1
  

**Description/Current Behaviour**

I'm using the front-facing camera of an iPad Mini 2 / iPad Pro (Latest). The camera does not focus on things up close and stays focused in the distance.

I'm using [`react-native-camera`](https://github.com/react-native-community/react-native-camera) with iPads/iPhones and I use the front-facing camera to scan barcodes (Code39, Code128, QR, etc..) However when using the front-facing camera, it does not focus on the barcode (Code39) or anything I put mildly close to the camera. The rear camera works absolutely perfectly however the front camera does not. QR Codes work perfectly, this is probably cause they're bigger.

I have not been able to test android as I'm not building for android purely just iOS. I can't seem to find any information on getting the front camera to focus.

If I was to stand in the background, hold up my Code39 close to the camera but leave a small gap at the bottom, it would not try focus on the card however stay focused on me in the background.

**Expected Behaviour**

I expect the camera to see the code is taking up a lot more of the screen than I am, focus on it, read the code and proceed to run the code `onBarCodeRead`

**Steps to Reproduce**

- Create new react-native project
- `yarn add react-native-camera` / `npm install react-native-camera --save`
- set `type={RNCamera.Constants.Type.front}` to use the front camera.
- set `autoFocus={RNCamera.Constants.AutoFocus.on}` (It's on by default anyway, this just ensures it.
- set `onBarCodeRead={() => alert('barcode found')}`
- Try to scan a Code39 / Code128 - [(creatable here)](http://online-barcode-generator.net/)
- Try to scan it and you'll find the camera will not focus on it however stay focused on the background. This is also true if you cover the camera with your finger, when you pull your finger away you expect the camera to be out of focus to the background and try and re-focus. This is not the case, it will stay focused at a medium / long distance.

I do not use Expo.

**Additionals**

Front facing camera only.

[StackOverflow Question Link](https://stackoverflow.com/questions/55846066/front-facing-camera-does-not-auto-focus-or-manually-focus)

**What have I tried to fix it?**

- Disable the `autoFocus` as this was a fix for Android, no luck here.
- Manually set the `focusDepth`.
- Manually set `autoFocusPointOfInterest` to center of screen.
- Change the `zoom` to 0.2 and slowly increase to the point of where it starts to look silly.
- Set `onGoogleVisionBarcodesDetected` to just console.log something as this was another fix for android.
- Update `react-native-camera@2.6.0` 
- Update to master branch at `react-native-camera@git+https://git@github.com/react-native-community/react-native-camera.git`

**Code**

I render the camera in a [`react-native-modal`](https://github.com/react-native-community/react-native-modal) and I've put my code below.

```
<RNCamera style={styles.camera}
          type={RNCamera.Constants.Type.front}
          flashMode={RNCamera.Constants.FlashMode.off}
          autoFocus={RNCamera.Constants.AutoFocus.on}
          captureAudio={false}
          onBarCodeRead={(barcode) => {
            if (this.state.isModalVisible) {
              this.setState({
                isModalVisible : false
              }, () => this.captureQR(barcode.data));
            }
          }}>
```

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by mikerodham** [comment]
I found some code that seems relevant: (I don't know swift/obj c)
275-300
```
- (void)updateFocusDepth
{
    AVCaptureDevice *device = [self.videoCaptureDeviceInput device];
    NSError *error = nil;

    if (device == nil || self.autoFocus < 0 || device.focusMode != RNCameraAutoFocusOff || device.position == RNCameraTypeFront) {
        return;
    }

    if (![device respondsToSelector:@selector(isLockingFocusWithCustomLensPositionSupported)] || ![device isLockingFocusWithCustomLensPositionSupported]) {
        RCTLogWarn(@"%s: Setting focusDepth isn't supported for this camera device", __func__);
        return;
    }

    if (![device lockForConfiguration:&error]) {
        if (error) {
            RCTLogError(@"%s: %@", __func__, error);
        }
        return;
    }

    __weak __typeof__(device) weakDevice = device;
    [device setFocusModeLockedWithLensPosition:self.focusDepth completionHandler:^(CMTime syncTime) {
        [weakDevice unlockForConfiguration];
    }];
}
```

More specifically just this section here: 

```
    if (device == nil || self.autoFocus < 0 || device.focusMode != RNCameraAutoFocusOff || device.position == RNCameraTypeFront) {
        return;
    }
```

**Comment by fabriziobertoglio1987** [comment]
I gave the [following solution on stackoverflow](https://stackoverflow.com/a/55966437/7295772)

IOS has [three `Focus Modes`](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/AVFoundationPG/Articles/04_MediaCapture.html#//apple_ref/doc/uid/TP40010188-CH5-SW2#Focus_Modes). You need to use `AVCaptureFocusModeContinuousAutoFocus`

>[AVCaptureFocusModeContinuousAutoFocus](https://developer.apple.com/documentation/avfoundation/avcapturefocusmode/avcapturefocusmodecontinuousautofocus): The camera continuously autofocuses as needed.

>**You use the [isFocusModeSupported](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1390215-isfocusmodesupported): method to determine whether a device supports a given `focus mode`**, then set the mode using the focusMode property.

`react-native-camera` will change the focus in two different scenarios (you can set a breakpoint with `xcode` on this lines):

1. [`focusWithMode`](https://github.com/react-native-community/react-native-camera/blob/960c5b1c1687742bcadd570f676e2689339e48b0/ios/RCT/RCTCameraManager.m#L1054) method will set the focus only if your frontcamera supports `isFocusPointOfInterestSupported` and `AVCaptureFocusModeContinuousAutoFocus`

The method will change the focus mode `[device setFocusMode:focusMode];` to `AVCaptureFocusModeContinuousAutoFocus` only if the following condition is returns `true`

    [device isFocusPointOfInterestSupported] && [device isFocusModeSupported:focusMode]

If the condition returns `false`, there is no `autofocus`, **but** the picture may [be focused on](https://stackoverflow.com/a/17226418/7295772) ExposureMode [`[device setExposureMode:exposureMode];`](https://github.com/react-native-community/react-native-camera/blob/960c5b1c1687742bcadd570f676e2689339e48b0/ios/RCT/RCTCameraManager.m#L1059)

2. [`updateAutoFocusPointOfInterest`](https://github.com/react-native-community/react-native-camera/blob/1b9fb63e56368f90be2b94e32815e2837b53da41/ios/RN/RNCamera.m#L240) changes the focus when the user taps on the screen, based on the `x, y` coordinates of his touch.


As there are several posts ([post 1](https://stackoverflow.com/questions/17219049/iphone-5-front-camera-tap-to-focus), [post 2](https://stackoverflow.com/questions/18618229/autofocus-in-iphone-4s-front-camera-adjustingfocus-observer-not-being-invoked), [post 3](https://stackoverflow.com/questions/17219049/iphone-5-front-camera-tap-to-focus), [post 4](https://stackoverflow.com/questions/9729898/iphone-front-camera-tap-to-focus)) on stackoverflow stating that different iphone versions do not support all type of autofocus with the frontcamera, I suggest you to **set breakpoints** on those line of codes and check the value of [`isFocusModeSupported`](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1390215-isfocusmodesupported) and [`isFocusPointOfInterestSupported`](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1390436-isfocuspointofinterestsupported)
