### ISSUE TITLE
Error when running example for android

### ISSUE THREAD

**Issue by muhammadridho** [react-native-community/react-native-camera#2233]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**
Androdi

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:
  

**Description/Current Behaviour**
I'm trying to run example code for android. but when code is compiled i get this error from android
![Screenshot_2019-04-25-13-29-56-917_com rncameraexample](https://user-images.githubusercontent.com/16620050/56714906-632e2280-6760-11e9-9c84-d19f28358985.png)

**Expected Behaviour**
i am expected this example run

**Steps to Reproduce**
try react-native link,  and reinstall modules

**Comment by arisupriatna14** [comment]
Close your metrobundler, and try build again

**Comment by muhammadridho** [comment]
haha, i've just solved before
