### ISSUE TITLE
Build APK Android Failed

### ISSUE THREAD

**Issue by arisupriatna14** [react-native-community/react-native-camera#2234]
# Bug Report

**To Do First**

- [✔️ ] Did you try latest release?
- [ ] Did you try master?
- [ ] Did you look for existing matching issues?

**Platforms**

Android

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':react-native-camera:mlkitDebugRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-ml-common:[17.0.0].
     Required by:
         project :react-native-camera > com.google.firebase:firebase-ml-vision:19.0.3
      > Could not resolve com.google.firebase:firebase-ml-common:[17.0.0].
         > Failed to list versions for com.google.firebase:firebase-ml-common.
            > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-ml-common/maven-metadata.xml.
               > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-ml-common/maven-metadata.xml'.
                  > Connection reset
      > Could not resolve com.google.firebase:firebase-ml-common:[17.0.0].
         > Failed to list versions for com.google.firebase:firebase-ml-common.
            > Unable to load Maven meta-data from https://maven.google.com/com/google/firebase/firebase-ml-common/maven-metadata.xml.
               > Could not HEAD 'https://maven.google.com/com/google/firebase/firebase-ml-common/maven-metadata.xml'.
                  > Connection reset
      > Could not resolve com.google.firebase:firebase-ml-common:[17.0.0].
         > Failed to list versions for com.google.firebase:firebase-ml-common.
            > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-ml-common/maven-metadata.xml.
               > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-ml-common/maven-metadata.xml'.
                  > Connection reset
      > Could not resolve com.google.firebase:firebase-ml-common:[17.0.0].
         > Failed to list versions for com.google.firebase:firebase-ml-common.
            > Unable to load Maven meta-data from https://maven.google.com/com/google/firebase/firebase-ml-common/maven-metadata.xml.
               > Could not HEAD 'https://maven.google.com/com/google/firebase/firebase-ml-common/maven-metadata.xml'.
                  > Connection reset
   > Could not resolve com.google.android.gms:play-services-vision:[17.0.2].
     Required by:
         project :react-native-camera > com.google.firebase:firebase-ml-vision-face-model:17.0.2
      > Could not resolve com.google.android.gms:play-services-vision:[17.0.2].
         > Failed to list versions for com.google.android.gms:play-services-vision.
            > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-vision/maven-metadata.xml.
               > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-vision/maven-metadata.xml'.
                  > Connection reset
      > Could not resolve com.google.android.gms:play-services-vision:[17.0.2].
         > Failed to list versions for com.google.android.gms:play-services-vision.
            > Unable to load Maven meta-data from https://maven.google.com/com/google/android/gms/play-services-vision/maven-metadata.xml.
               > Could not HEAD 'https://maven.google.com/com/google/android/gms/play-services-vision/maven-metadata.xml'.
                  > Connection reset
      > Could not resolve com.google.android.gms:play-services-vision:[17.0.2].
         > Failed to list versions for com.google.android.gms:play-services-vision.
            > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-vision/maven-metadata.xml.
               > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-vision/maven-metadata.xml'.
                  > Connection reset
      > Could not resolve com.google.android.gms:play-services-vision:[17.0.2].
         > Failed to list versions for com.google.android.gms:play-services-vision.
            > Unable to load Maven meta-data from https://maven.google.com/com/google/android/gms/play-services-vision/maven-metadata.xml.
               > Could not HEAD 'https://maven.google.com/com/google/android/gms/play-services-vision/maven-metadata.xml'.
                  > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by KemikalGeneral** [comment]
@arisupriatna14 
Hi, did you ever solve this error?
I'm using this camera which works fine running on a device, but now that I'm trying to build the APK, it's throwing an error:

> Execution failed for task ':app:lintVitalRelease'.
> > Could not resolve all artifacts for configuration ':react-native-camera:mlkitDebugRuntimeClasspath'.
>    > Could not find com.google.firebase:firebase-ml-vision:12.0.1.

and

Could not find com.google.firebase:firebase-ml-vision-face-model:12.0.1.


Thanks!

**Comment by guildeassis** [comment]
I also have this problem in version 2.10.2. 
For now I'm using version 1.13.1 and works.

**Comment by aryanbhasin** [comment]
I have the same problem and haven't been able to find a solution so far

**Comment by Andriiklymiuk** [comment]
This still isn't fixed in rn 0.61.1 , 
any help?

**Comment by KemikalGeneral** [comment]
@Andriiklymiuk Due to the lack of help, I switched to this package which works better, has more features, and less setup. Never looked back since.

https://github.com/ivpusic/react-native-image-crop-picker

**Comment by Andriiklymiuk** [comment]
@KemikalGeneral Thanks, I'll try it out)

**Comment by Schabaani** [comment]
I had this issue. I changed repositories order in `android\build.gradle`

```
repositories {
        google()
        jcenter()

        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven { url 'https://jitpack.io' }
   }
```

**Comment by FansPro** [comment]
In my case,  I delete android/app/build and then rebuild will be ok

**Comment by JoseIgnacio92** [comment]
Hi, in my case, I had to delete de gradle cache folder content

C:\Users\jiperez\.gradle\caches

then rebuild

**Comment by fengandrain** [comment]
I solved my problem by [https://maven.aliyun.com/mvn/guide]。Don't thanks me,thanks alibaba
