### ISSUE TITLE
'RNCamera' not found in UIManager

### ISSUE THREAD

**Issue by mayankshah1607** [react-native-community/react-native-camera#2241]
I'm using expo to build a react native application using this library. I'm running into an error - 'RNCamera' not found in UI Manager.

**Comment by MateusAndrade** [comment]
Can you provide more info about this? Also, you followed the instructions on the README.MD about link, etc?

**Comment by sibelius** [comment]
This does not work with expo directly, check docs about how to use expo camera ou link this package in your eject expo app

**Comment by MateusAndrade** [comment]
> I'm using expo to build a react native application using this library. I'm running into an error - 'RNCamera' not found in UI Manager.

You can give a try at this: https://docs.expo.io/versions/latest/sdk/camera/

**Comment by mayankshah1607** [comment]
Thank you for your response! Will try it and get back.

**Comment by gururajphadnis** [comment]
Getting the same error message '"RNCamera" was not found in the UIManager.' in non expo environment:

"react-native": "0.57.8",
"react-native-camera": "^2.6.0",
"react-native-permissions": "^1.1.1",

**Comment by jalesingh** [comment]
I getting this problem while using react-native-qrcode-scanner and now I resolved this problem after linking react-native-camera and react-native-qrcode-scanner with react-native, like below

react-native link react-native-camera
react-native link react-native-qrcode-scanner

**Comment by MateusAndrade** [comment]
> Getting the same error message '"RNCamera" was not found in the UIManager.' in non expo environment:
> 
> "react-native": "0.57.8",
> "react-native-camera": "^2.6.0",
> "react-native-permissions": "^1.1.1",

You can check if react-native-camera is correctly linked to your project?  Following @jalesingh comment

**Comment by ravelab** [comment]
I have the same problem on android while using react-native-qrcode-scanner but @jalesingh sollution doesn't work for me. iOS works fine

**Comment by ronandowlingcullen** [comment]
Having the same problem here on android when trying to use react-native-qrcode-scanner

**Comment by brkrtp** [comment]
+1 qr-code-scanner

**Comment by robertoclavijob** [comment]
I  followed the steps to link react-native-camera **Manually**  on Android to get it working
https://react-native-community.github.io/react-native-camera/docs/installation#manual-install
