### ISSUE TITLE
Could not find method missingDimensionStrategy() for arguments [react-native-camera, general]

### ISSUE THREAD

**Issue by Qlenglet** [react-native-community/react-native-camera#2244]
Hello everybody,

I absolutely need the camera for my app. And when I try to launch the command 'react-native run-android', I have this message again and again. I followed the guide and put all the directive. And I tried everything like clear all the cache possible.

I work on Manjaro last release system with 4.10 Gradle and an android device under Android 8. I have all the software at the last stable release.

Can you help me because I don't see where is my error. Thank you a lot

 Here my android/build.gradle 
`
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        missingDimensionStrategy 'react-native-camera', 'general'
    }

    defaultConfig {
        applicationId "com.neuropalreact"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        missingDimensionStrategy 'react-native-camera', 'general'
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':react-native-camera')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
`

**Comment by nicoceledon** [comment]
I still haven't done the camera implementation, but at least with this I've solve this specific problem. I'm not an expert on android and still don't understand this solution, but here it goes.

I had the  following message:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method missingDimensionStrategy() for arguments [react-native-camera, general] on ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=16, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=26, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=1.0, applicationId=com.buscaparkingoperator, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.
```
I changed the version in `app/build.gradle`, from 2.3.3 to 3.0.0.

```
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

I have react-native 0.56.0, and i installed the react-native-camera@2.0.0 (I tried this version just because i thought the problem was related with the latest version of react-native-camera). Also I followed the manual linking.

**Comment by sibelius** [comment]
check examples

**Comment by nicoceledon** [comment]
Thanks, that's what i did and i found that the version that i had was too low ;)

**Comment by ixre** [comment]
@Qlenglet 
it should be:
```
android{
   ...
   defaultConfig {
        ...
        missingDimensionStrategy('react-native-camera','general')
    }
}
```

**Comment by sibelius** [comment]
follow docs
