### ISSUE TITLE
Face detection not working on android front camera

### ISSUE THREAD

**Issue by Chimaa123** [react-native-community/react-native-camera#2246]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

Android

**Versions**
all version after 1.8.1

- Android:
- react-native-camera:

  

**Description/Current Behaviour**
Face detection is not working on Android.

**Expected Behaviour**
Face detection should work

**Steps to Reproduce**

**Additionals**
I found that this issue raised cause of #f7fb3e3 commit (https://github.com/react-native-community/react-native-camera/commit/f7fb3e361d4f1b773ee93bea8336f276e84b692c) which is released in v1.8.1.

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
duplicated of https://github.com/react-native-community/react-native-camera/issues/2221

**Comment by Chimaa123** [comment]
#2221 is only on IOS, but this issue is on android

**Comment by RWOverdijk** [comment]
@Chimaa123 What do you mean recovering? I'm having the same issue

**Comment by RWOverdijk** [comment]
I missed the release. Verifying it works now.

**Comment by RWOverdijk** [comment]
@n1ru4l Closer, but still no. Not it's inverted horizontal causing inverted readings.
