### ISSUE TITLE
Shows "Spinner" ; camera doesn't appear

### ISSUE THREAD

**Issue by felixchan** [react-native-community/react-native-camera#2248]
- [YES ] Did you try latest release?
- [YES ] Did you try master?
- [YES ] Did you look for existing matching issues?

Deployment 8.0
React Native 0.59
Installed with the latest release (master) + `react-native link`.

When RNCamera is rendered, it shows a spinning wheel.  No camera is shown.  This occurs in both physical device and simulator.

**Comment by tuicodemobile** [comment]
Have you tried the previous version?

**Comment by MateusAndrade** [comment]
Are you trying this on ANdorid/IOS? Also, did you request the user for access to the camera?

**Comment by felixchan** [comment]
@MateusAndrade how do I request the user for access to camera? In previous versions, it would automatically request access when <RNCamera> is rendered.

(I'm testing on iOS)

**Comment by MateusAndrade** [comment]
> @MateusAndrade how do I request the user for access to camera? In previous versions, it would automatically request access when is rendered.
> 
> I also got this in XCode console (not sure if related):
> 
> ```
> 2019-05-04 12:03:08.756 [warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 0):
> TypeError: CameraManager.checkVideoAuthorizationStatus is not a function. (In 'CameraManager.checkVideoAuthorizationStatus()', 'CameraManager.checkVideoAuthorizationStatus' is undefined)
> ```
> 
> (I'm testing on iOS)

Did you link your project? IM going to give a look at the example here.

**Comment by felixchan** [comment]
@MateusAndrade Yes, `react-native link react-native-camera`

**Comment by MateusAndrade** [comment]
> @MateusAndrade Yes, `react-native link react-native-camera`

Hmmm, you can give a try at Cocoapods to ensure that you installed the deps properly? I only used pods whit this project. About the user request to the camera, i tested here and it should ask for the user when you render your component. I think it looks a link error on your case

**Comment by musti-91** [comment]
I'm having  the same with android/IOS.
I tried to change between master and release but it's the same!

**Comment by musti-91** [comment]
I solved by removing `ref` prop and passing it in child props

**Comment by jqn** [comment]
@felixchan I was having the same problem. Follow the manual linking guide and make sure everything that needs to be there is where is supposed to be. In my case I was missing libRNCamera.a from my project's build phases

**Comment by musti-91** [comment]
Does anyone have an issue with resolution of taken photo in IOS?
Device: IPhone 6 Plus, 7

**Comment by MateusAndrade** [comment]
> Does anyone have an issue with resolution of taken photo in IOS?
> Device: IPhone 6 Plus, 7

Im using rn-camera without any resolution problem on this devices. Did you set a prop for quality or something similar to It?

**Comment by musti-91** [comment]
Nope,
Configuration for save Photo: 
```javascript
const picOptions = {
      quality: 1.0,
      base64: true,
      width: 200,
      fixOrientation: true,
      pauseAfterCapture: true,
      doNotSave: false //! FOR IOS RESPONSE WILL NOT BE READ, INCLUDING (URI)
    }
```
Props: 
```javascript
captureAudio={false}
        playSoundOnCapture={true}
        autoFocus={RNCamera.Constants.AutoFocus.on}
        style={preview}
        type={cameraType}
        flashMode={RNCamera.Constants.FlashMode.auto}
```

**Comment by MateusAndrade** [comment]
@musti-91 what do you mean when you say the photo is not the same?

**Comment by musti-91** [comment]
@MateusAndrade not the same resolution,

**Comment by MateusAndrade** [comment]
@musti-91 you can give a try without setting the width and concerting It to base64? If the problem persists you can open a New issue about that. Since this isnt the problem pointed on this issue :smile:

**Comment by musti-91** [comment]
yeah, indeed.
ok, thanks

**Comment by ryanyue123** [comment]
@felixchan did you check the CameraStatus for your camera. check #1744

**Comment by gauthampait** [comment]
Still an issue in the latest version. Just shows the spinner. It doesn't ask for the permission as well.

**Comment by felixchan** [comment]
@gauthampait I installed it manually (as well as with link) ...and now it works!

**Comment by MateusAndrade** [comment]
Since the problem pointed as solved, im closing this issue. If anyone have any problem, please left a comment.

**Comment by switch13** [comment]
In my case, the permissions popup in iOS never appeared. It turns out I was adding it to the info.plist file that was in the root directory of the ios folder instead of adding to the info.plist located in my app's target folder.  Now I'm adding to both for good measure :)

You can find this info.plist file in xCode (I'm using Version 10.2.1) by clicking on your App project in the Project Navigator, clicking your app's target, clicking the info tab, then adding all of the appropriate Privacy Keys (ie. Privacy - Camera Usage Description) and their respective Values (Descriptions).

![Screen Shot 2019-06-28 at 5 40 45 AM](https://user-images.githubusercontent.com/1906710/60334128-c73fb380-9968-11e9-932e-a8e29528ddd9.png)

**Comment by MaximilianoRG** [comment]
IMPORTANT:
In ios folder, executes the command "pod install" after linking manually. It solves my problem.
