### ISSUE TITLE
[Android] Potential Vulnerability Identified by Veracode

### ISSUE THREAD

**Issue by onnij** [react-native-community/react-native-camera#2256]
# Bug Report

**To Do First**

- [ x ] Did you try latest release?
- [ x ] Did you try master?
- [ x ] Did you look for existing matching issues?

**Platforms**

Android

**Versions**

- Android: 27.0.3
- react-native-camera: 2.0.1
- react-native: 0.57.8
- react: 16.6.3

**Description/Current Behaviour**

A Veracode Scan of Application identified a potential vulnerability in FileFaceDetectionAsyncTask.java

> Description: This call to java.io.File.!operator_javanewinit() contains a path manipulation flaw. The argument to the function is a filename constructed using untrusted input. If an attacker is allowed to specify all or part of the filename, it may be possible to gain unauthorized access to files on the server, including those outside the webroot, that would be normally be inaccessible to end users. The level of exposure depends on the effectiveness of input validation routines, if any. The first argument to !operator_javanewinit() contains tainted data from the variable mPath. The tainted data originated from earlier calls to com.reactnativecommunity.webview.RNCWebViewManager$RNCWebViewClient.onReceivedError, com.reactnativecommunity.webview.RNCWebViewManager$RNCWebViewClient.onPageFinished, and com.reactnativecommunity.webview.RNCWebViewManager$RNCWebViewClient.onPageStarted.

**Expected Behaviour**

Expect that the application should compile and not have vulnerabilities detected. If this could be setup as optional like on the iOS side this would resolve our issue.

**Comment by sibelius** [comment]
Not in this package
