### ISSUE TITLE
Release build fails when ProGuard is enabled

### ISSUE THREAD

**Issue by andresmtz98** [react-native-community/react-native-camera#2258]
# Bug Report

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

Android

**Versions**

- Android: 9.0
- react-native-camera: 2.6.0 | 2.7.0
- react-native: 0.59.5
- react: 16.8.3

**Description/Current Behaviour**

When `def enableProguardInReleaseBuilds = true` the release build fails.

**Expected Behaviour**

Build succeded.

**Steps to Reproduce**
- Create any blank project
- Set up this library for Android and the release config
- Run `./gradlew assembleRelease` or `./gradlew bundleRelease`

**Aditional Information**
I tested just for 'generalRelease' for react-native-camera.

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by andresmtz98** [comment]
@sibelius Bro, can you please reopen this issue?

**Comment by andresmtz98** [comment]
@sibelius Is there any plan to adress this issue?

**Comment by mayconmesquita** [comment]
I'm getting this problem here
