### ISSUE TITLE
real-time frames processing

### ISSUE THREAD

**Issue by Manthika** [react-native-community/react-native-camera#2260]
Hi,

is there any chance to get realtime image data from camera (without save to album), do with that some processing.
I'm new to react-native ecosystem. I think about this problem like about 'canvas' and canvas like image processing, but canvas on react-native is not available... Is only chance to do image processing like this throught native code?

Thanks a lot.

**Comment by M-Ali-D** [comment]
Is this issue solved. I need help regarding live frames from camera
