### ISSUE TITLE
Compatibility with react-native-web?

### ISSUE THREAD

**Issue by shamilovtim** [react-native-community/react-native-camera#2265]
**Ask your Question**
Is there compatibility with compiling for web? Which platforms are supported? Please consider adding a list of platforms that the plugin supports since this isn't clear from the README.

**Tags**
web

**Comment by sibelius** [comment]
check expo camera, they have web support, maybe we can follow them

**Comment by sibelius** [comment]
we gonna accept a pr that bring react-native-web support

**Comment by hmheng** [comment]
this sounds awesome if we can make it!
:D
