### ISSUE TITLE
ReactNativeJS: TypeError: undefined is not an object (evaluating '_reactNativeCamera.default.constants')

### ISSUE THREAD

**Issue by liuyulin666** [react-native-community/react-native-camera#2267]
"react-native-camera": "^2.1.1",
"react-native": "^0.59.3",

Online version is right, the branch error, on the premise of not do version update, could you tell me how to solve this？？？River's lake emergency, thank you！！！

**Comment by liuyulin666** [comment]
This error is located at:
        in Index (created by SceneView)
        in SceneView (at StackViewLayout.js:786)
        in RCTView (at View.js:45)
        in View (at StackViewLayout.js:785)
        in RCTView (at View.js:45)
        in View (at StackViewLayout.js:784)
        in RCTView (at View.js:45)
        in View (at createAnimatedComponent.js:151)
        in AnimatedComponent (at StackViewCard.js:69)
        in RCTView (at View.js:45)
        in View (at createAnimatedComponent.js:151)
        in AnimatedComponent (at screens.native.js:59)
        in Screen (at StackViewCard.js:57)
        in Card (at createPointerEventsContainer.js:27)
        in Container (at StackViewLayout.js:862)
        in RCTView (at View.js:45)
        in View (at screens.native.js:83)
        in ScreenContainer (at StackViewLayout.js:313)
        in RCTView (at View.js:45)
        in View (at createAnimatedComponent.js:151)
        in AnimatedComponent (at StackViewLayout.js:309)
        in Handler (at StackViewLayout.js:302)
        in StackViewLayout (at withOrientation.js:30)
        in withOrientation (at StackView.js:79)
        in RCTView (at View.js:45)
        in View (at Transitioner.js:214)
        in Transitioner (at StackView.js:22)
        in StackView (created by Navigator)
        in Navigator (at createKeyboardAwareNavigator.js:12)
        in KeyboardAwareNavigator (at createAppContainer.js:387)
        in NavigationContainer (at App.js:160)
        in App (at renderApplication.js:35)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:98)
        in RCTView (at View.js:45)
        in View (at react-native-root-siblings/index.js:33)
        in RootSiblingsWrapper (at AppContainer.js:112)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:115)
        in AppContainer (at renderApplication.js:34)
    
    This error is located at:
        in NavigationContainer (at App.js:160)
        in App (at renderApplication.js:35)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:98)
        in RCTView (at View.js:45)
        in View (at react-native-root-siblings/index.js:33)
        in RootSiblingsWrapper (at AppContainer.js:112)
        in RCTView (at View.js:45)
        in View (at AppContainer.js:115)
        in AppContainer (at renderApplication.js:34)

**Comment by Stat1c14** [comment]
Not sure if this will help you, but I was receiving a very similar error caused by doing

`import RNCamera from 'react-native-camera';`

instead of 

`import { RNCamera } from 'react-native-camera';`

Hopefully that helps.

**Comment by MateusAndrade** [comment]
Are you importing RNCamera doing: 

```javascript
import { RNCamera, FaceDetector } from 'react-native-camera';
```

As @Stat1c14 said, you need to apply a destructing on your import, or use something like:
```javascript
   import RNCameraImport from 'react-native-camera';
```

And access it with ```RNCameraImport.RNCamera()```. Btw, i recommend using the first option, since its more clear and easy to understand.

Also, you can check if you are accessing the RNCamera constants with ```RNCamera.Constants```?

**Comment by Petrando** [comment]
I am experiencing the same issue with RN version 0.95.5, after npm install and link the RN camera library and then RN start --reset-cache. I'm trying to create a RN barcode scanner by [this tutorial](https://medium.com/@dinukadilshanfernando/implementing-a-barcode-scanner-by-using-react-native-camera-b170de4b7f51) . At first i use 

`import Camera from 'react-native-camera'`

 as suggested by said tutorial, and got error like below 

![react-native-camera-start--reset-cache](https://user-images.githubusercontent.com/32563413/61610452-6a8f9a00-ac83-11e9-83d4-812c1679de73.png)

which seems similiar to [this stackoverflow question](https://stackoverflow.com/questions/55982666/how-to-fix-typeerror-undefined-is-not-an-object-evaluating-reactnativecamer).

Then as suggested by @MateusAndrade above, i change my import into 

`import RNCameraImport from 'react-native-camera';`
`const RNCamera = RNCameraImport.RNCamera();`

And change the Camera component invocation into this :

 `<RNCamera
			style={styles.preview}
			torchMode={this.state.torchOn ? RNCamera.Constants.TorchMode.on : RNCamera.Constants.TorchMode.off}
			onBarCodeRead={this.onBarCodeRead}
			ref={cam => this.camera = cam}
			aspect={RNCamera.Constants.Aspect.fill}
		  ></RNCamera>`
(Notice above that i used capital starting letter at `RNCamera.Constants` call, as suggested by @MateusAndrade ) 
which then i got this error below : 

![react-native-camera-RNCamera](https://user-images.githubusercontent.com/32563413/61610180-8f374200-ac82-11e9-96ea-c2c5d400a808.png)

**Comment by sibelius** [comment]
use autolinking with v3

**Comment by Luis-Kendelick** [comment]
> I am experiencing the same issue with RN version 0.95.5, after npm install and link the RN camera library and then RN start --reset-cache. I'm trying to create a RN barcode scanner by [this tutorial](https://medium.com/@dinukadilshanfernando/implementing-a-barcode-scanner-by-using-react-native-camera-b170de4b7f51) . At first i use
> 
> `import Camera from 'react-native-camera'`
> 
> as suggested by said tutorial, and got error like below
> 
> ![react-native-camera-start--reset-cache](https://user-images.githubusercontent.com/32563413/61610452-6a8f9a00-ac83-11e9-83d4-812c1679de73.png)
> 
> which seems similiar to [this stackoverflow question](https://stackoverflow.com/questions/55982666/how-to-fix-typeerror-undefined-is-not-an-object-evaluating-reactnativecamer).
> 
> Then as suggested by @MateusAndrade above, i change my import into
> 
> `import RNCameraImport from 'react-native-camera';`
> `const RNCamera = RNCameraImport.RNCamera();`
> 
> And change the Camera component invocation like so :
> 
> `<RNCamera style={styles.preview} torchMode={this.state.torchOn ? RNCamera.Constants.TorchMode.on : RNCamera.Constants.TorchMode.off} onBarCodeRead={this.onBarCodeRead} ref={cam => this.camera = cam} aspect={RNCamera.Constants.Aspect.fill} ></RNCamera>`
> (Notice above that i used capital starting letter at `RNCamera.Constants` call )
> then i got this error below :
> 
> ![react-native-camera-RNCamera](https://user-images.githubusercontent.com/32563413/61610180-8f374200-ac82-11e9-96ea-c2c5d400a808.png)

man, you're using **TorchMode.on** and **TorchMode.off**?
If yes, they updated the package. You have to use FlashMode.torch and FlashMode.off instead.

**Comment by Luis-Kendelick** [comment]
guys, "constants" must be "Constants". 
TorchMode.on and TorchMode.off no more exists. There are FlashMode.torch and FlashMode.off in the documentation.
They updated the package.

**Comment by nihp** [comment]
I am also getting the same error. Any solution for this?

**Comment by aqeebimtiaz** [comment]
I'm getting this same error still, any solutions yet?

> I am experiencing the same issue with RN version 0.95.5, after npm install and link the RN camera library and then RN start --reset-cache. I'm trying to create a RN barcode scanner by [this tutorial](https://medium.com/@dinukadilshanfernando/implementing-a-barcode-scanner-by-using-react-native-camera-b170de4b7f51) . At first i use
> 
> `import Camera from 'react-native-camera'`
> 
> as suggested by said tutorial, and got error like below
> 
> ![react-native-camera-start--reset-cache](https://user-images.githubusercontent.com/32563413/61610452-6a8f9a00-ac83-11e9-83d4-812c1679de73.png)
> 
> which seems similiar to [this stackoverflow question](https://stackoverflow.com/questions/55982666/how-to-fix-typeerror-undefined-is-not-an-object-evaluating-reactnativecamer).
> 
> Then as suggested by @MateusAndrade above, i change my import into
> 
> `import RNCameraImport from 'react-native-camera';`
> `const RNCamera = RNCameraImport.RNCamera();`
> 
> And change the Camera component invocation like so :
> 
> `<RNCamera style={styles.preview} torchMode={this.state.torchOn ? RNCamera.Constants.TorchMode.on : RNCamera.Constants.TorchMode.off} onBarCodeRead={this.onBarCodeRead} ref={cam => this.camera = cam} aspect={RNCamera.Constants.Aspect.fill} ></RNCamera>`
> (Notice above that i used capital starting letter at `RNCamera.Constants` call )
> then i got this error below :
> 
> ![react-native-camera-RNCamera](https://user-images.githubusercontent.com/32563413/61610180-8f374200-ac82-11e9-96ea-c2c5d400a808.png)

**Comment by rahultectum** [comment]
![WhatsApp Image 2020-05-02 at 6 46 57 PM](https://user-images.githubusercontent.com/44963214/80865634-5bc12380-8ca8-11ea-81ab-cc28875fb8bc.jpeg)

I am also getting the same error. Any solution for this?

**Comment by YashKumarVerma** [comment]
Nothing mentioned above works. :cry:

**Comment by renatobenks** [comment]
which version are you using @YashKumarVerma?

**Comment by ayanmohsin** [comment]
Please How you resolved kindly guide me

**Comment by Aakash359** [comment]
Hello I am using React-native-camera with typescript project but in my case its giving error like tyepError : RN Camera can not be undefined , can anyone let me know what issues is there I am just using example code of react-native-camera
<img width="1440" alt="Screenshot 2022-09-12 at 11 04 24 AM" src="https://user-images.githubusercontent.com/54428958/189580610-e5454b3d-d99e-446a-94af-a8499ff0f8d0.png">

**Comment by ayanmohsin** [comment]
Dear React Native CAmera is Depresable in the favour of react native vision
camera so use react native vision camera library in react native> 6.0
