### ISSUE TITLE
How to turn off the record audio permission request

### ISSUE THREAD

**Issue by 000xuandu** [react-native-community/react-native-camera#2268]
I'm building an application that scans the qr code with the react-native-camera (RNCamera) library.
Currently, I don't have a recording-related function, so I don't want to ask my users to accept "record audio" permissions.
I have read the material in a different way, but failed.
Please help me.

**I do not want to appear dialog box asking for audio recording rights as shown in Figure 2**

![1](https://user-images.githubusercontent.com/33916400/57761658-27b3c200-7728-11e9-8067-2a6c8612956f.PNG)
![2](https://user-images.githubusercontent.com/33916400/57761657-27b3c200-7728-11e9-9d62-a70b36326e17.jpg)

Here is my code:
```
<RNCamera
          ref={ref => {
            this.camera = ref;
          }}
          style={styles.preview}
          type={RNCamera.Constants.Type.back}
          flashMode={RNCamera.Constants.FlashMode.on}
          onGoogleVisionBarcodesDetected={({ barcodes }) => {
            console.warn(barcodes[0].data);
            if (!Utils.isNull(barcodes[0].data) & this.isCan) {
              this.runAction(barcodes[0].data)
            }
          }}
        />
```

**Comment by MateusAndrade** [comment]
You can pass: `captureAudio={false}` to the RNCamera component.

**Comment by MateusAndrade** [comment]
> You can pass: `captureAudio={false}` to the RNCamera component.

```jsx
<RNCamera
          ref={ref => {
            this.camera = ref;
          }}
          style={styles.preview}
          type={RNCamera.Constants.Type.back}
          flashMode={RNCamera.Constants.FlashMode.on}
          captureAudio={false}
          onGoogleVisionBarcodesDetected={({ barcodes }) => {
            console.warn(barcodes[0].data);
            if (!Utils.isNull(barcodes[0].data) & this.isCan) {
              this.runAction(barcodes[0].data)
            }
          }}
/>
```
