### ISSUE TITLE
Investigate Monorepo Approach

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-camera#2272]
related to https://github.com/react-native-community/react-native-camera/issues/2130

The idea is to make this package more modular, we can have more than one camera module/bridge to make more features optional

My proposal:
- react-native-camera-core
- react-native-camera-barcode
- react-native-camera-face-recognition
- react-native-camera-tensor-flow

What other packages should we have?

**Comment by jgcmarins** [comment]
should we reopen?
