### ISSUE TITLE
Watermark supported?

### ISSUE THREAD

**Issue by MrHazimAli** [react-native-community/react-native-camera#2273]
# Question

**To Do First**
- [done] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [done ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [done ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Is there any ways to add watermark to video and picture after capture it?

**Comment by n1ru4l** [comment]
No there is no way to add watermarks and it is out of the scope of this library.

A quick google showed me this library: https://github.com/JimmyDaddy/react-native-image-marker

I have not used it, therefore, I can give you no guarantee.
