### ISSUE TITLE
Last Stable version??

### ISSUE THREAD

**Issue by karanpratapsingh** [react-native-community/react-native-camera#2274]
can someone tell me the last stable version??

I just need a simple camera view with qr code scanning capability, can't seem to get v2.9.0 work on android

Thanks

**Comment by karanpratapsingh** [comment]
for anyone wondering use v1.13.1 it's the most stable one if you just need this module for simple stuff like barcode scanning

**Comment by andresmtz98** [comment]
> for anyone wondering use v1.13.1 it's the most stable one if you just need this module for simple stuff like barcode scanning

Bro do you have a guide to set up that version?

**Comment by MateusAndrade** [comment]
> > for anyone wondering use v1.13.1 it's the most stable one if you just need this module for simple stuff like barcode scanning
> 
> Bro do you have a guide to set up that version?

```
yarn add react-native-camera@1.13.1
```

You can set the version you want, just changing the @1.13.1. After doing this, probably you will need to do a pod install, etc.
