### ISSUE TITLE
 Cannot choose between the following variants of project :multicontactpicker

### ISSUE THREAD

**Issue by adarshsonkar** [react-native-community/react-native-camera#2276]
ERROR: Cannot choose between the following variants of project :multicontactpicker:
  - debugRuntimeElements
  - releaseRuntimeElements
All of them match the consumer attributes:
  - Variant 'debugRuntimeElements' capability JRDOCHELP-dev:multicontactpicker:unspecified:
      - Unmatched attributes:
          - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
          - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
          - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
          - Found org.gradle.usage 'java-runtime' but wasn't required.
  - Variant 'releaseRuntimeElements' capability JRDOCHELP-dev:multicontactpicker:unspecified:
      - Unmatched attributes:
          - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
          - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
          - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
          - Found org.gradle.usage 'java-runtime' but wasn't required.

this error I found when i try to import a project. code of build.gradle is 

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.31'
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:3.1.1'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

    }
}

allprojects {

    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        google()

    }
}
ext {
    // The following are only a few examples of the types of properties you can define.
    compileSdkVersion = 28
    // You can also create properties to specify versions for dependencies.
    // Having consistent versions between modules can avoid conflicts with behavior.
    supportLibVersion = "28.0.0"
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by hazeeb** [comment]
https://github.com/react-native-community/react-native-camera/issues/2138#issuecomment-471669956
