### ISSUE TITLE
Video Size

### ISSUE THREAD

**Issue by emilemoureau** [react-native-community/react-native-camera#2278]
Hi!

First of all thanks for this great package!

My question is: How to change the quality without changing the format of the video?

In 720p with the front camera 5 seconds of videos can quickly reach 3mb size! I have tested a lot of things and I can not find anything in the doc, before redirecting me to other options like handbrakejs or https://github.com/shahen94/react-native-video-processing I would like to know if there is a solution!

**Comment by djleonskennedy** [comment]
@emilemoureau it have to be implemented by someone, faced this problem

https://github.com/react-native-community/react-native-camera/issues/1713
