### ISSUE TITLE
Interleaved2of5 with only 4 digits not recognized 

### ISSUE THREAD

**Issue by hoffmana** [react-native-community/react-native-camera#2279]
Hi,
we are having Interleaved2of5 codes with 4 and 6 digits like 1234 and 345678:
![barcode ashx](https://user-images.githubusercontent.com/31858431/58017541-c82b2d00-7b00-11e9-9205-335685fba3d4.gif)
![index](https://user-images.githubusercontent.com/31858431/58017549-c9f4f080-7b00-11e9-9f1f-26ae4fc92554.gif)

In iOS it is working totally fine, but for Android we are facing this issue:

Our scanner is having no problem to detect 6 digits code, we get the result after scanning:
{type: "ITF", data: "042826"}
But if the code contains only 4 digits, the scanner does not detect code at all.

Is anyone facing same or has some hints, why there is an issue detecting 4 dgiti code? Are there any restrictions for the scanner/barcode?

I appreciate your help, thanks a lot.

Best regards,

Thomas

**Comment by MateusAndrade** [comment]
@hoffmana you can edit your comment with the issue template?

**Comment by hoffmana** [comment]
Sorry,. I am quite new to GitHub. What do you mean exactly? I added the information, that it happens with Android. iOS is detecting correctly.

**Comment by MateusAndrade** [comment]
You can test the barcode with this app: https://play.google.com/store/apps/details?id=com.google.zxing.client.android,  and tell me if you got the same problem?

**Comment by hoffmana** [comment]
Hi, I just tested this app, but it also does not recognized the 4 digit code, but a 6 digit code.
![Screenshot_2019-05-26-21-15-46](https://user-images.githubusercontent.com/31858431/58386151-cfb86d80-7ffb-11e9-9d61-68622c9821e7.png)
![Screenshot_2019-05-26-21-16-51](https://user-images.githubusercontent.com/31858431/58386153-cfb86d80-7ffb-11e9-9ef2-7e0f9833a076.png)
If you scan it with SCANDIT (https://play.google.com/store/apps/details?id=com.scandit.demoapp), then it is recognized perfectly.
![Screenshot_2019-05-26-21-25-49](https://user-images.githubusercontent.com/31858431/58386245-ea3f1680-7ffc-11e9-93f5-86faae1bf544.png)

**Comment by MateusAndrade** [comment]
I think this is a problem with zxing, the Android library used to Scan barcodes. You tried with ML Kit?
