### ISSUE TITLE
error: expected float but got (raw string) 4:3

### ISSUE THREAD

**Issue by dedenhendrap** [react-native-community/react-native-camera#2281]
Hello i am find this error on my project, anyone have seen this error ?

![image](https://user-images.githubusercontent.com/31558217/58167584-74624480-7cb6-11e9-8aa3-372c35f6e0c2.png)

**Comment by dedenhendrap** [comment]
and i found this 
error: duplicate value for resource 'attr/aspectRatio' with config ''.

anyone can help me ?

**Comment by dedenhendrap** [comment]
solved

**Comment by samaneh-kamalian** [comment]
> solved
how do you solve it?
I have this error :+1: error: duplicate value for resource 'attr/aspectRatio' with config ''.
when install react-native-lock-screen and I have installed react-native-camera
