### ISSUE TITLE
iOS FaceDetector .It won't work

### ISSUE THREAD

**Issue by ma569322307** [react-native-community/react-native-camera#2292]
I'm using the latest version. I'm using the react native version project. My Podfile imports the following libraries:

Pod 'Firebase/Core'
Pod 'Firebase/MLVision'
Pod 'Firebase/MLVisionFaceModel'
Pod 'GoogleMobileVision/FaceDetector'
Pod 'GoogleMobileVision/MVDataOutput'

The problem now is that once the camera starts up, there's no way the face will quickly callback just once successfully. I hope it can correctly identify faces before onFacesDetected later

**Comment by sibelius** [comment]
can you provide more info?

**Comment by EskelCz** [comment]
I have the opposite situation, on ios it works (latest version), on android doesn't :-/
