### ISSUE TITLE
iOS Facedetector 

### ISSUE THREAD

**Issue by ma569322307** [react-native-community/react-native-camera#2295]
The integration of iOS platform has been completed, but the product manager asked me to remove the voice of face recognition and take photos in the future. I don't know what to do. Please tell me

**Comment by n1ru4l** [comment]
Please provide more information. Unfortunately, I am having a hard time understanding what you actually mean.

**Comment by ma569322307** [comment]
When face recognition is successful, there will be the sound of taking photos. How to remove the sound.
