### ISSUE TITLE
Coutour detection

### ISSUE THREAD

**Issue by sri-wml** [react-native-community/react-native-camera#2298]
# Feature-Request

I don't think current version fetched the face contours. Are there any plans to implement in future?

**Comment by n1ru4l** [comment]
Please provide more info. Was this previously possible?

**Comment by sri-wml** [comment]
It's not available in prior versions. It's actually a feature request. I see mlkit provides face contours along with landmarks. Right now react-native camera only shows face landmarks.

**Comment by n1ru4l** [comment]
@sri-wml Feel free to send a pull request that implements this feature!
