### ISSUE TITLE
Use either ZXing or Google Vision for Barcode Scanning, not both

### ISSUE THREAD

**Issue by heroic** [react-native-community/react-native-camera#2300]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
QR Code scanning seems to be using zxing and google vision both. Can't we just use one?

**Tags**
qr code, barcode, zxing

**Comment by n1ru4l** [comment]
related: https://github.com/react-native-community/react-native-camera/pull/1457

@heroic We can use one, however, we should first know which one works the best and remove the other one in the next major version release. Feel free to investigate and provide more info!
