### ISSUE TITLE
DexMerger androidx - program type already present

### ISSUE THREAD

**Issue by ericrprates** [react-native-community/react-native-camera#2301]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

Android

- Android: 28.0.3
- iOS:
- react-native-camera: 2.10.0
- react-native: 0.59.8
- react: 16.8.3

**Additionals**
yarn add react-native-camera
react-native link react-native-camera
react-native run-android
and i get this error
![image](https://user-images.githubusercontent.com/8013848/58997900-ebc6c680-87d4-11e9-89e5-0cf0507fef45.png)

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by n1ru4l** [comment]
@ericrprates I am sorry that you had to experience this pain. I reverted the commit that breaked the backwards compat in version https://github.com/react-native-community/react-native-camera/releases/tag/v2.10.1

The AndroidX support will be reintroduced in a major release once there is a clear and documented migration path.

For now, I am going to close this issue and I suggest you upgrading to v2.10.1.
