### ISSUE TITLE
Camera some times take a while to show the image in Android

### ISSUE THREAD

**Issue by agrass** [react-native-community/react-native-camera#231]
### Actual behaviour

Some times the camera take too much time to show the current image or just not show nothing, it show only a black background color or some times just the camera not work. someone more with this issue??
### Environment
- Android 5.0
### react-native-camera

**Version**: npm version

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
