### ISSUE TITLE
How to get a list of cameras?

### ISSUE THREAD

**Issue by rakibtg** [react-native-community/react-native-camera#2311]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Android and ios devices tends to have more than 2 or 3 cameras this days. 
Is there any way to get a list of cameras and knowing if they are in the front or back? So if the user want to select the telephoto or wide range camera they can do that?
Any idea would be great :)

**Comment by ShivaAryal** [comment]
Is there any update on this one?
