### ISSUE TITLE
Reopen: A way to read data byte from current preview, like a previewCallback?

### ISSUE THREAD

**Issue by DennisJu007** [react-native-community/react-native-camera#2315]
# Feature-Request

**Describe the Feature**
Is there a way to read the data from the current preview? My goal is to retrieve the camera preview as a Pixel Array.

A preview callback would be a good addition, passing the data byte, just like the onPreviewFrame callback when you set it up.

**Possible Implementations**

I need the byte array of onPreviewFrame(byte[], Camera) to change to rgb values.
![1201560135401_ pic_hd](https://user-images.githubusercontent.com/42829167/59398619-799d4580-8dc3-11e9-8a4c-1e5c85517c9c.jpg)

**Related Issues**

#451 

@n1ru4l Hello Sir,I reopen this issue, Hope we can fix that.

**Comment by n1ru4l** [comment]
This might be a huge performance hit, I do not think sending a whole picture via the javascript bridge is a good idea.

**Comment by DennisJu007** [comment]
I cant agree with you more.Performance is very important for us. Maybe be we can find another way to resolve it.We can support a function which needs a  screen's point x, y params and returns this point's rgb values. How does it sound like?
