### ISSUE TITLE
【iOS】压缩后上传，服务器上的大小比本地沙盒的大三倍左右

### ISSUE THREAD

**Issue by Wjy1005** [react-native-community/react-native-camera#2324]
options = {
                quality: 0.1,
                base64: false,
                exif: false,
                fixOrientation: true,
                forceUpOrientation: true
            };

本地的367Kb，服务端收到的是1.6MB

组件版本V1.9.2

**Comment by jgcmarins** [comment]
为什么这与本机相机有关？

**Comment by Wjy1005** [comment]
> 为什么这与本机相机有关？

我怀疑跟这个组件的图片处理有关，因为我用了其他的组件，同样的网络传递方式，查看是本地的跟服务器大小是一致的。而且本组件的安卓端不存在该问题

**Comment by jgcmarins** [comment]
得到它了。
所以也许它只与iOS有关

**Comment by Wjy1005** [comment]
> 得到它了。
> 所以也许它只与iOS有关

那请问要怎么改呢，或者在后续的版本中是否有修复

**Comment by jgcmarins** [comment]
我认为我们需要深入研究这个调试，并了解与Android有什么不同

除此之外，我建议确切地确定它改变图像大小的位置
