### ISSUE TITLE
Camera is not working show me white blank screen 

### ISSUE THREAD

**Issue by Asadullahbarlas** [react-native-community/react-native-camera#2340]
# Bug Report

**To Do First**

- [ ] Did you try latest release?
- [ ] Did you try master?
- [ ] Did you look for existing matching issues?

**Platforms**

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:
  

**Description/Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by MuhammadUsman786786** [comment]
Still facing this issue

**Comment by USAMABARLAS** [comment]
use react-native image picker, it's working

**Comment by MuhammadUsman786786** [comment]
Basically i am using the react native qr code scanner. Which use the react native camera inder the hood

**Comment by Asadullahbarlas** [comment]
I think react native image picker is working on qr-scanner

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
