### ISSUE TITLE
Barcode PDF417 working properly only when Remote JS Debugger is ON

### ISSUE THREAD

**Issue by marlonfrr** [react-native-community/react-native-camera#2343]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2435%20Funded-%2300A156.svg" />](https://issuehunt.io/r/react-native-community/react-native-camera/issues/2343)

# Bug Report

**To Do First**

- [x] Did you try latest release?
Yes
- [x] Did you try master?
Yes
- [x] Did you look for existing matching issues?
Yes

**Platforms**

Android API 26

IOS 12.2

**Versions**

- Android: api 26
- iOS: 12.2
- react-native-camera: ^2.11.0
- react-native: ^0.59.0
- react: 16.5.1
  

**Description/Current Behaviour**

I'm trying to read PDF417 barcode format within android emulator (but problem persists both physical device and simulator). The output on _onRead_ (TURNING ON REMOTE DEBUGGER) is the following:

<img width="1078" alt="Captura de Pantalla 2019-06-26 a la(s) 12 52 34 p  m" src="https://user-images.githubusercontent.com/30930579/60203366-1921f580-9812-11e9-824f-f4638031f540.png">

As you can see, data contains all the information that is extracted from de ID Card just fine, but the problem comes when I turn off the Remote Debugger, the output is the following:

![Screenshot_1561572040](https://user-images.githubusercontent.com/30930579/60203528-6e5e0700-9812-11e9-9a8d-fbc5685b319f.png)

NOTE that the data is just the first portion of the first log

And when I test on a real iPhone the output also contains an extra "dataRaw":

![issue iphone](https://user-images.githubusercontent.com/30930579/60203914-563ab780-9813-11e9-9491-c666b45515d7.jpeg)

**Expected Behaviour**

The data extracted should be the same on both android and iOS and without remote debugger.

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $35.00)

- [<img src='https://avatars3.githubusercontent.com/u/121981?v=4' alt='trixel' width=24 height=24> trixel](https://issuehunt.io/u/trixel) ($30.00)
- $5.00 have been anonymously funded.

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/react-native-community/react-native-camera/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by andresmtz98** [comment]
Hey bro, i'm having this issue, please help me :(

**Comment by andresmtz98** [comment]
I don't know why this happens but a workaround that i wrote after hours:
![image](https://user-images.githubusercontent.com/18200380/60632789-24a28d00-9dcd-11e9-8121-fcfd36a873fc.png)

**Comment by MateusAndrade** [comment]
This is a really strange bug. :open_mouth: 

@marlonfrr  you can tell more about how you managed to solve this?

@andresmtz98  thanks for providing your workaround. :tada:

**Comment by andresmtz98** [comment]
> This is a really strange bug. 😮
> 
> @marlonfrr you can tell more about how you managed to solve this?
> 
> @andresmtz98 thanks for providing your workaround. 🎉

Ty bro. Another critical bug is this: #794

**Comment by renatobenks** [comment]
@estevg it's probably solved in the latest, which version are you using?

**Comment by estevg** [comment]
> @estevg it's probably solved in the latest version, which version are you using?

use the version react-native-camera@3.26.0 but it presents the same problem

**Comment by renatobenks** [comment]
ok @estevg, I'll be checking this out!

**Comment by estevg** [comment]
> ok @estevg, I'll be checking this out!

any solution?

**Comment by renatobenks** [comment]
not yet @estevg, I still couldn't reproduce it, do you have a repo with such problem happening? it will be useful to fix ASAP for sure
