### ISSUE TITLE
Camera view threw an error - component could not be rendered.

### ISSUE THREAD

**Issue by AlekseyPimenov** [react-native-community/react-native-camera#2350]
# Bug Report
- [x] Did you try latest release?
- [x] Did you try master? 
- [x] Did you look for existing matching issues?

**Platforms**
Android 7.0

- Android: 7.0
- iOS: ---
- react-native-camera:2.11.0
- react-native:0.59.9
- react:16.8.3
  

**Description/Current Behaviour**
Add react-native-camera to react-native project (after init for example)
Run app on device - get error:
onMountError ->  { message: 'Camera view threw an error - component could not be rendered.' }
Get black screen and crash

Related only for Android 7.0 - 7.1
Other ones work good.

**Expected Behaviour**
react-native-camera worked on Android 7.0 -7 .1

**Steps to Reproduce**
1) Add react-native-camera to react-native project (after init for example)
2) Run app on real device with Android 7.0
3) Get black screen and crash

**Comment by MateusAndrade** [comment]
Did you asked for the permissions on Android/IOS, setting AndroidManifest.xml and Info.plist?

**Comment by JuAlexandre** [comment]
I've the same error, for me it appears when I make a video call with webrtc.
Once I come back to my scan screen the camera is in error.

**Comment by dacre-denny** [comment]
To resolve this I had to uninstall and reinstall an app that was using this library
