### ISSUE TITLE
Support for AndroidX and React Native v0.60

### ISSUE THREAD

**Issue by cassioseffrin** [react-native-community/react-native-camera#2352]
# Feature-Request

**Describe the Feature**
Compatibility with React Native v0.60. Here is some breaking changes: https://facebook.github.io/react-native/blog/2019/07/03/version-60

**Possible Implementations**
Adapt the code, here a starting point https://react-native-community.github.io/upgrade-helper/

**Related Issues**
The current version of react-native-share is not compatible with React Native v0.60

**Comment by sibelius** [comment]
comment in this pull request if everything is working

https://github.com/react-native-community/react-native-camera/pull/2306

then we can do a new release
