### ISSUE TITLE
RN 0.60 Support?

### ISSUE THREAD

**Issue by creative-git** [react-native-community/react-native-camera#2354]
any plans to add RN 0.60 Support?

**Comment by Alexispap** [comment]
It is possible to migrate it with Android Studio. Use the menu entry "Refactor -->Migrate to AndroidX". Then fix all the support lib  imports in the Java files which are not transferred by this method. If you need help, just write it here :)

**Comment by sibelius** [comment]
comment in this pull request if everything is working

https://github.com/react-native-community/react-native-camera/pull/2306

then we can do a new release
