### ISSUE TITLE
Program type already present: com.google.android.gms.vision.CameraSource$ShutterCallback

### ISSUE THREAD

**Issue by cat4total** [react-native-community/react-native-camera#2360]
# Bug Report

**To Do First**

- [x ] Did you try latest release?
- [x ] Did you try master?
- [x ] Did you look for existing matching issues?

**Platforms**

Android

**Versions**

- Android: 7.0
- react-native-camera: 2.11.0
- react-native: 0.59.2
- react: 16.8.3
- react-navigation: 2.18.3

**Description/Current Behaviour**

I migrating from version 1.x to 2.x using 
[link 1](https://github.com/react-native-community/react-native-camera/blob/master/docs/migration.md)
[link 2](https://github.com/react-native-community/react-native-camera/blob/master/docs/migrationV2.md)

then run `react-native run-android` 
the terminal gave me : 

```
 Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: com.google.android.gms.vision.CameraSource$ShutterCallback

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.google.android.gms.vision.CameraSource$ShutterCallback
```

**Comment by sibelius** [comment]
use autolinking with v3
