### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by bwor** [react-native-community/react-native-camera#2361]
![image](https://user-images.githubusercontent.com/30290674/60876838-4093ac00-a26f-11e9-839d-bca477ec2ee6.png)

**Comment by saeid85** [comment]
I guess you are using React Native **version 0.60**
The quickest solution is to downgrade to RN **version 0.59** & follow instruction to install & link `react-native-camera` package.

**Comment by sibelius** [comment]
use autolinking with v3
