### ISSUE TITLE
The barcode scanner only detect if the barcode in the center of the screen

### ISSUE THREAD

**Issue by ntk0104** [react-native-community/react-native-camera#2366]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:
  

**Description/Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by vasilestefirta** [comment]
@n1ru4l, I was just having the same problem and then after searching through the GitHub issues I found this reply: 
https://github.com/react-native-community/react-native-camera/issues/190#issuecomment-208536659

Basically, in my case, I have a PDF417  _1-dimensional barcode_ which supposedly cannot be easily detected anywhere on the digital image. Only the center of the screen can be used to properly scan this kind of barcode.

As a solution, I will simply try to add a visual mask to suggest the user to use the center of the screen for scanning the barcode. You can use a library like [react-native-barcode-mask](https://github.com/shahnawaz/react-native-barcode-mask) or code your own using the layout suggested here:
https://github.com/react-native-community/react-native-camera/issues/1394#issuecomment-375701364
