### ISSUE TITLE
Long Delay between onPress and Finished Callback

### ISSUE THREAD

**Issue by sscaff1** [react-native-community/react-native-camera#237]
There is an average of a 2 second delay on Android between pressing "Capture" and the data being returned from the promise. I used another package https://github.com/NorthFoxz/react-native-camera-android and there is an average of a 0.8 second delay for the same scenario (which is much better). Any ideas? I saw a closed issue from a while ago showing that the delay was related to a similar delay and it was associated with rotation of the image. So the current pull request (#232) by @rpopovici may fix the issue...?

**Comment by cyphire** [comment]
I'm having this issue to... My app is dependent on being able to take picture after picture quickly.  My time between capture and onPress is more like 4 seconds.  I had to change my app to select "capture", create an array of the current pictures in the default camera location,  have user go to the regular camera, shoot a bunch of pictures, then go back to my app and re-press the "capture" button, selecting all images NOT in the array for processing.  This works but is cumbersome.  My normal response in the native camera are .4-.75 seconds per press.

**Comment by java99** [comment]
+1

**Comment by Ulydev** [comment]
+1

**Comment by ArthurvS** [comment]
+1

**Comment by ZekkieB** [comment]
+1

**Comment by npomfret** [comment]
Are these all android issues?  If so, I suspect I know what's causing it.  

To test the theory, could you try my [PR](https://github.com/lwansbrough/react-native-camera/pull/716) and set the target to anything other than cameraRoll (like `Camera.constants.CaptureTarget.temp`).

Then, if the delay is noticeably less, switch to CameraRoll and see if the delay comes back.

**Comment by mnlbox** [comment]
I have same issue with Nexus 7 Tab (Android 5.1.1)

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
