### ISSUE TITLE
Not able to find the path of cached directory for recorded video

### ISSUE THREAD

**Issue by NitheeshDevadiga** [react-native-community/react-native-camera#2372]
I am able to get the cached directory path (com.xxx/0/cache/xxx.mp4) but in that cache location not able to find the video. How can I get that and How can I assign the new file path?

**Comment by shivo-ham** [comment]
you can change video path 

this.camera.recordAsync(options);

put your custom path in options

   const options = {
            path: "/storage/emulated/0/DCIM/Camera/"+"video.mp4",
            quality: '480p',
            maxDuration: 60,
            maxFileSize: 100 * 1024 * 1024
           };

like this way!
