### ISSUE TITLE
How to check if NO barcode is detected?

### ISSUE THREAD

**Issue by Esshahn** [react-native-community/react-native-camera#2374]
With 

````
onGoogleVisionBarcodesDetected={this.barcode_recognized}
````

I can check for detected barcodes, but how do I check if NO barcode is visible? The issue is that when I remove a barcode from the camera view, the barcode is not removed from the barcodes array (see example files provided here). Therefore the overlay box that displays the barcode info keeps being displayed.

Thanks for any support!

**Comment by saeid85** [comment]
Just a trick:
Add a timer, so if no barcode is detected for example in 30 seconds stop camera!

**Comment by Esshahn** [comment]
Thanks @saeid85, I considered that but decided it would be too hacky.

**Comment by Ashafix** [comment]
@Esshahn : Did you find a non-hacky solution?
