### ISSUE TITLE
If you start another recording before the previous long video file is saved, the app crashes when you stop the second recording.

### ISSUE THREAD

**Issue by realjamie** [react-native-community/react-native-camera#238]
### Steps to reproduce
1. Record a long video, like 10 minutes.
2. Before the long video file is saved (you probably need to print a log to tell), quickly start another recording.
3. Stop the second recording.
### Expected behaviour

Both of the videos should be saved. The camera should work after that.
### Actual behaviour

Both of the videos are saved. However, the app crashes. It says it cannot find the callback passed to this.refs.camera.capture(). The screenshot is attached and error messages are as follows:

```
2016-03-30 15:01:40.324 [error][tid:com.facebook.React.JavaScript] Callback with id 32: RCTCameraManager.capture() not found
2016-03-30 15:01:40.341 [fatal][tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: Callback with id 32: RCTCameraManager.capture() not found
```
### Environment
- **Node.js version**: v4.2.4
- **React Native version**: 0.20.0
- **React Native platform + platform version**: iOS 9.2.1
### react-native-camera

**Version**: master

**Note**: I noticed this crash on Nov 2015, at that time I have Node v4, the latest React native, the latest react-native-camera, and I developed on iOS 8.
![img_0560](https://cloud.githubusercontent.com/assets/5363036/14159456/d213ed0a-f68a-11e5-9ccf-6741f5077932.jpg)

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
