### ISSUE TITLE
Camera preview fixed height increase when camera display.

### ISSUE THREAD

**Issue by SA-KBJ** [react-native-community/react-native-camera#2388]
I have set RNCamera height to fixed 500. When the camera was not loaded is height is 500. But while preview show than there height increase.

I found the same behavior in library basic example: https://github.com/react-native-community/react-native-camera/tree/master/examples/basic.

Style
```
container: {
        flex: 1,
        flexDirection: 'column',
        backgroundColor: colors.profileTabSelectedColor
    },
    preview: {
        flexDirection: 'column',
        alignItems: 'center',
        width: dimen.value_100wp,
        height: 500,
        backgroundColor: colors.profileTabSelectedColor
    }
}
```
Camera rendering
```
 <RNCamera
          ref={ref => {
            this.camera = ref;
          }}
          style={createPostStyle.preview}
          type={RNCamera.Constants.Type.back}
          flashMode={this.state.flash}
          androidCameraPermissionOptions={{
            title: string.alert.CameraPÒermissionTitle,
            message: string.alert.CameraPermissionNote,
            buttonPositive: string.alert.buttonOk,
            buttonNegative: string.alert.buttonCancel,
          }}
        />
```
ScreenShoot
![CameraNotLoad](https://user-images.githubusercontent.com/47265801/61774732-2207e600-ae15-11e9-8f4a-d929ae40f5b5.png)

![Screenshot_1563950761](https://user-images.githubusercontent.com/47265801/61774770-377d1000-ae15-11e9-814b-1e2933b0ca69.png)

**Comment by kelokchan** [comment]
Try to set `overflow: 'hidden'` to your container

**Comment by SA-KBJ** [comment]
@kelokchan I have tried to set **overflow: 'hidden'** to the container but still same behavior happens.

**Comment by Obi1Kennoby** [comment]
Add `overflow: 'hidden`' not to container but to your `preview` style. it helped to me

**Comment by dca-ps** [comment]
I'm also with this problem, but @Obi1Kennoby tip helped a lot!

**Comment by sarannandhakumar** [comment]
> Try to set `overflow: 'hidden'` to your container
setting overflow : 'hidden' works fine, but the hidden portion(hide using overflow:'hidden') of camera view also reflecting in image after capture. Is there any way to stretch the camera view ?.

**Comment by Sargnec** [comment]
> > Try to set `overflow: 'hidden'` to your container
> > setting overflow : 'hidden' works fine, but the hidden portion(hide using overflow:'hidden') of camera view also reflecting in image after capture. Is there any way to stretch the camera view ?.

Have this same issue. Hidden part is visible after taken picture

**Comment by realabbas** [comment]
> overflow: 'hidden'

Yeah works for me! Thanks
