### ISSUE TITLE
defaultVideoQuality' of RNCamera with tag #119: JSON value '720p' of type NSString cannot be converted to NSNumber

### ISSUE THREAD

**Issue by RONAKDHOLARIYA** [react-native-community/react-native-camera#2392]
In ios I add  **defaultVideoQuality="720p"* this so app can crash and show  this error **defaultVideoQuality' of RNCamera with tag #119: JSON value '720p' of type NSString cannot be converted to NSNumber**
android has not issue please solve asap.

**Comment by mister09** [comment]
@RONAKDHOLARIYA Try using `defaultVideoQuality={RNCamera.Constants.VideoQuality["720p"]}`
