### ISSUE TITLE
Face detection working in iphone 6s, not working on Iphone X

### ISSUE THREAD

**Issue by TranHanHieu** [react-native-community/react-native-camera#2395]
# Bug Report

**To Do First**

- [ ] Did you try latest release?

**Platforms**

**Versions**

- ios: 12
- react-native-camera:
- react-native: 0.60.0
- react: 16.8.6
  

**Description/Current Behaviour**
iPhone 6S working (iOS 12.1.2), iphone X is currently not detecting any faces. On a component mount, facedetection callback called once with empty

{ 
  faces: []
  type: "face"
}

**Expected Behaviour**

Face detection should work on iPhone 6S

**Steps to Reproduce**

Install the package using CocoaPods and run on a device, try to detect faces.

I need help

**Comment by Esxiel** [comment]
Let me add to this.
I tried latest version so far (3.0.0), along with the latest version of react-native (0.60.4)
It works on my iPhone 6(12.2), but doesn't work on my iPhone Xs 12.3.1

**Comment by Esxiel** [comment]
I've found out that the face detection on the iPhoneX works if we switch the phone orientation to landscape mode.

**Comment by TranHanHieu** [comment]
Thanks @Esxiel, but I think the problem is not orientation to landspace, because the day before it worked with the old build on iphone X but didn't work on 6s. I think there are issues in some issues. I need help

**Comment by TranHanHieu** [comment]
FaceDetectorManagerMlkit: 

- (void)findFacesInFrame:(UIImage *)uiImage
                  scaleX:(float)scaleX
                  scaleY:(float)scaleY
               completed:(void (^)(NSArray *result))completed 
{
    self.scaleX = scaleX;
    self.scaleY = scaleY;

    FIRVisionImage *image = [[FIRVisionImage alloc] initWithImage:uiImage];
    NSMutableArray *emptyResult = [[NSMutableArray alloc] init];
    [_faceRecognizer
     processImage:image
     completion:^(NSArray<FIRVisionFace *> *faces, NSError *error) {
        RCTLog(@"faces: %@", faces);
        RCTLog(@"error: %@", error);

         if (error != nil || faces == nil) {
             completed(emptyResult);
         } else {
             completed([self processFaces:faces]);
         }
     }];
}

On iphone x log faces, error is nil.

**Comment by votanhung** [comment]
> I've found out that the face detection on the iPhoneX works if we switch the phone orientation to landscape mode.
> 
> Maybe #2221 needs to be reopened?

iPhone XS MAX has the same. It only works on landscape mode.

**Comment by kiritnim** [comment]
> > I've found out that the face detection on the iPhoneX works if we switch the phone orientation to landscape mode.
> > Maybe #2221 needs to be reopened?
> 
> iPhone XS MAX has the same. It only works on landscape mode.

@votanhung Yes it's working in landscape, you have solution of portrait.

**Comment by GH974** [comment]
Hi, i tested on the last version and it work only in landscape mode on iphone X

**Comment by sushant1333** [comment]
Hi, I am still facing the issue.

Faces are detected only in landscape mode, but not in portrait mode.
Any solution to it?

**Comment by camchis** [comment]
This seems to still be an issue for me... turning to landscape mode isn't a suitable solution
