### ISSUE TITLE
Enable MLKit face detection while recording a video

### ISSUE THREAD

**Issue by tomo25** [react-native-community/react-native-camera#2412]
# Question

Hi, mlkit face detection is great but it stops working when I start recording a video.
 Is there a way to enable mlkit face detection while recording as well?

**Comment by tomo25** [comment]
Does anyone have an idea what is causing this issue?

**Comment by MateusAndrade** [comment]
Hi @tomo25 , i dont know if we got this feature on react-native-camera at the moment. I will try giving a look at this on this week. However, prs are always welcome! :smiley:

**Comment by tomo25** [comment]
Thank you @MateusAndrade !

**Comment by tomo25** [comment]
@MateusAndrade Hi! How is it going with this?
