### ISSUE TITLE
Could not find play-services-vision Android

### ISSUE THREAD

**Issue by brayanAP** [react-native-community/react-native-camera#2414]
# Question

**To Do First**
- [ ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

When I run react-native run-android it marks the following:
![captura](https://user-images.githubusercontent.com/25075881/62509457-d9670a00-b7d0-11e9-832f-b986dae05b83.png)

**Comment by rezaarifian** [comment]
same ,  I cannot release APK but debug success

any solution about play-services-vision ?

**Comment by qimingweng** [comment]
Same issue here

**Comment by MateusAndrade** [comment]
@brayanAP you can share your `android/app/build.gradle` and your `react-native` and `react-native-camera` version?

**Comment by dlombardi** [comment]
same issue here

**Comment by badver** [comment]
According to [docs](https://react-native-community.github.io/react-native-camera/docs/installation): 
Just add `googlePlayServicesVisionVersion = "<YOUR_VERSION_HERE>"` in `android/build.gradle`

play-services-vision versions you can found here: https://mvnrepository.com/artifact/com.google.android.gms/play-services-vision 

For my app I use these values:
```
ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.1.0"
        googlePlayServicesVisionVersion = "16.2.0"
    }
```

**Comment by alexpoon2000** [comment]
I added "googlePlayServicesVisionVersion" and I can make the Android build now. However, the app crashed when I open it from Android device.
