### ISSUE TITLE
Block Phone calls & Notification alerts while recording

### ISSUE THREAD

**Issue by athondapu** [react-native-community/react-native-camera#2415]
# Question

**Ask your Question**
Hi I am very new to the react-native development. I am using this library and able to record the video and capture the photo. But I have a question is there anyway to block the phone calls and notifications while recording the video.? I searched in the web but I couldn't find any solution. Can any one please suggest or shed some light on how to block phone calls and notifications while recording the video.?

**Comment by marcosrdz** [comment]
When it comes to iOS, this is not possible. I'm not sure if Android has special flags for it but I think is unlikely.

**Comment by athondapu** [comment]
Thanks @marcosrdz for your reply. Is there anyway to block the calls & notifications in react-native.? If yes, can you please point me to the right direction.?

**Comment by marcosrdz** [comment]
There seem to be ways to detect a call, but no way to block it:

https://www.npmjs.com/package/react-native-call-detection

Perhaps you could use the notification to manually pause recording and then continue once you get a notification of a call being complete.
