### ISSUE TITLE
What critery should i use to compress an image?

### ISSUE THREAD

**Issue by felire** [react-native-community/react-native-camera#2416]
# Question

**To Do First**
- [ ] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ ] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ ] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
My doubt is the next one. My team and I build an app where the user can upload 10 photos if he want. But the problem was that the action to upload photos took a long time. So we decided to modify the quality to 0.6 and we also have implemented the library react-native-image-resizer. With this the performance grew a lot. With the library we do something like this: newWidth = originalPhotoWidth/5 and newHeight = originalPhotoHeight/5.  But my question is.. Is this the best way to compress an image? The space reduce from 5mb to 200kb in high definition photos. But really i don´t know if this is the best way, we didn´t use much critery to do it. Is there a good way to compress an image a lot only using react-native-camera? And What critery should i use to compress an image? 

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by MateusAndrade** [comment]
HI @felire , thanks for sharing your doubt with us, this is interesting topic. I worked on a application that relies on a similar behavior, and i adopted a solution similar to your. 

Doing a little research, i found that there are some libraries for Android/IOS that handle this but on the native side, like: 

https://github.com/zetbaitsu/Compressor and  https://github.com/hucool/WXImageCompress.

Please, let me know if you found a better way to achieve this. :smile:
