### ISSUE TITLE
when trying to run in device getting error

### ISSUE THREAD

**Issue by shaikhussian** [react-native-community/react-native-camera#242]
hai when i try to run this in device, I am getting an error like the below screenShot,when click on capture
![img_0204](https://cloud.githubusercontent.com/assets/11956308/14226366/ca548f46-f8fd-11e5-8ab4-b32fbf9534c9.jpg)
can you please tell me that how to solve it, And i am using this module for QR-Reader, how can i scan the generated QR  using this module

**Comment by rt2zz** [comment]
Most likely you are using an old version that haf a callback interface for capture. I would try installing master and see if that helps

**Comment by shaikhussian** [comment]
I am using these versions
react-native: 0.22.2,
react-native-camera: 0.3.8,

On Sat, Apr 2, 2016 at 10:49 PM, Zack Story <notifications@github.com>
wrote:

> Most likely you are using an old version that haf a callback interface for
> capture. I would try installing master and see if that helps
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lwansbrough/react-native-camera/issues/242#issuecomment-204760348>
>



-- 
     Thanking You,
Regards:
Hussian Shaik,
(Stellent Soft.Pvt.Ltd)

**Comment by shaikhussian** [comment]
@rt2zz just i saw saw your master and changed the node_module  according to that it show error like this in Camera.js

![simulator screen shot 04-apr-2016 12 03 22 pm](https://cloud.githubusercontent.com/assets/11956308/14240055/4e6c7962-fa5f-11e5-8799-a9157118bdbb.png)

**Comment by rt2zz** [comment]
you will need to rebuild your project since the objC source changed. Also should clear your caches just in case

**Comment by shaikhussian** [comment]
@rt2zz  i rebuild my project again,camera is working but when i move camera to generated qr code it shows some error message like this in device
![error](https://cloud.githubusercontent.com/assets/11956308/14273113/d42ea1c6-fb25-11e5-8a89-eb411089d92e.jpg)

**Comment by rt2zz** [comment]
After cursory inspection, i think there may be a bug in that onBarCodeRead is called even if it us not defined. 

1) try specifying a onBarCodeRead prop function
2) if this is the problem a PR to default onBarCodeRead prop would be much appreciated

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
