### ISSUE TITLE
Is there a way to improve the barcode reading?

### ISSUE THREAD

**Issue by andresmtz98** [react-native-community/react-native-camera#2429]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Is there a way to improve the barcode reading in cameras with low resolution (old devices) on Android using MLKit?

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
you need this https://github.com/react-native-community/react-native-camera/pull/874
