### ISSUE TITLE
RN 0.60 issue

### ISSUE THREAD

**Issue by creative-git** [react-native-community/react-native-camera#2430]
I HATE RN 0.60 :( 
any step by step tutorial to make react-native-camera work on android with RN 0.60 ?!!! i tried all ways suggested in previous issues and NOTING is working

**Comment by wellington-cunha** [comment]
I solved my problem using version 1.2.0 
 "react-native-camera": "1.2.0",

**Comment by thomassiew** [comment]
tried it.. more problems

**Comment by sibelius** [comment]
rn60 needs v3 with cocoapods

**Comment by wellington-cunha** [comment]
@thomassiew , Can you post here your package.json and Podfile? What problem came along?

**Comment by sibelius** [comment]
try to run both basic and mlkit examples from this package

**Comment by KingAmo** [comment]
just could not build success on `android` follow the docs ...  RN `0.60.5` , any solution ?
