### ISSUE TITLE
Testing Barcode Detection

### ISSUE THREAD

**Issue by JohannesWi** [react-native-community/react-native-camera#2433]
Hey Everyone,

I'm comparing some Barcode-Scanner-Librarys for a project at the university. 

For that, It would be amazing if I could test the barcode-detection feature of this react-native-camera inside a test case (such as jest). 

Is there any way how I could simulate this inside a test case?

I do appreciate every help!!

**Comment by hladf** [comment]
just use the google... https://stackoverflow.com/questions/41811477/how-to-mock-react-native-camera-with-jest

**Comment by hladf** [comment]
https://www.google.com/search?q=react+native+camera+test+with+jest&rlz=1C1GCEU_pt-BRBR821BR822&oq=react+native+camera+test+with+j&aqs=chrome.1.69i57j33l5.9647j0j7&sourceid=chrome&ie=UTF-8

enjoy

**Comment by JohannesWi** [comment]
Thank you, for your response!
I already looked up those solutions.

Of cause, its possible to Mock the Camera but I couldn't find a way, how to test the Barcode-detection feature. Do you have any ideas?
