### ISSUE TITLE
Scanning barcode is not working in android

### ISSUE THREAD

**Issue by PrathyushaKadiri** [react-native-community/react-native-camera#2440]
Scanning barcode is not working in android but for iOS, it works perfectly.

Android: 8.0 and 7 

<Camera
      ref={cam => this.camera = cam}
      style={styles.preview}
      onBarCodeRead={this.BarCodeRead.bind(this)}
 />

BarCodeRead({data}) {
    console.log(data)
    Alert.alert(data)
  }

And Used Aspect also but still no use.

**Comment by zelardiel** [comment]
I had this problem as well. This happened for me when the debugger was on. When its off it seems to be working on android for me
