### ISSUE TITLE
Camera default view is zoomed

### ISSUE THREAD

**Issue by kp2506** [react-native-community/react-native-camera#2472]
Hi All,

I am using react-native-camera with one of my android app. I have tried with 3.3.0, 3.3.1, 3.3.2 the issue is the default view of camera is zoomed, I have compared it to default camera app in the phone.

I have tried setting zoom props to 0 (zero), but the behaviour is not changed.

Please help.

**Comment by jqn** [comment]
I'm on 2.6.0 and the cameras match the view. I haven't upgraded to the latest version but I hope this helps. Also make sure you are setting the ratio properly for android

**Comment by kulek1** [comment]
I have the same problem on Android with `3.8.0` and `3.11.1` version.
iOS works like a charm.

**Comment by ksairi** [comment]
@kulek1 I'm using expo-camera, I'm having this same problem in iOS 13.2.3. Which iOS version are you on that works for you?

**Comment by alyyousuf7** [comment]
ExpoCamera has the issue on iOS 13.3.1
I came here wishing that RNCamera doesn't have the same issue as ExpoCamera. 😞

**Comment by sawndur** [comment]
Hey all, I think I found the issue. In RNCamera.m in the -initWithBridge function, 

 self.previewLayer.videoGravity = AVLayerVideoGravityResizeAspectFill; 

This is stretching out the aspect ratio giving a zoomed effect. You need to change it to AVLayerVideoGravityResizeAspect;
