### ISSUE TITLE
FaceDetection is not working in portrait mode in iphone x.

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [react-native-community/react-native-camera#2477]
Hi,

I have integrate face detection in my code. it's working fine in iPhone6, but in iPhone x in portrait mode is not working, in iPhonex landscape mode is working fine, 

Code is same as your example.

Can you help me what is problem.

Thanks.

**Comment by struct78** [comment]
I am also seeing this. Using this [solution](https://github.com/react-native-community/react-native-camera/issues/2349#issuecomment-512851436) works for me, but this is obviously a hack. 

I've tried debugging and stepping through the `convertBufferToUIImage` method, but I'm afraid I hit the limit of my talent at that point and can't see where it's going wrong.

In the meantime I've just forked react-native-camera and implemented the hack until this is fixed.
