### ISSUE TITLE
i try to reinstall many times, but when i run project in xcode, it display bug , can you help?

### ISSUE THREAD

**Issue by leuducquy** [react-native-community/react-native-camera#248]
I make step by step but it display RCTBridge.h not found in RTCamera.m  when i run project.can you help?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
