### ISSUE TITLE
TypeError: undefined is not an object ( evaluating '_reactNativeCamera.RNCamera.constants.Aspect.fill')

### ISSUE THREAD

**Issue by shreyakamoji96** [react-native-community/react-native-camera#2483]
TypeError: undefined is not an object ( evaluating '_reactNativeCamera.RNCamera.constants.Aspect.fill')

**Comment by SamiChab** [comment]
On the newest version(s) of the package, `aspect` is no more a prop you can pass.

**Comment by shreyakamoji96** [comment]
Then should it be( evaluating '_reactNativeCamera.RNCamera.constants.fill') or can you tell me the statement based on newest version

**Comment by SamiChab** [comment]
I totally removed the prop `aspect` (and the constant also). And it works the same like before

**Comment by nihp** [comment]
Any solution for this. I am facing the above error
