### ISSUE TITLE
RNCamera not focus on Galaxy Tab A6

### ISSUE THREAD

**Issue by RodrigoAngeloValentini** [react-native-community/react-native-camera#2484]
Camera focus not work in Galaxy Tab A6. So, I can't read a qrcode.

My Code:

`<RNCamera
          autoFocus={RNCamera.Constants.AutoFocus.on}
          style={styles.camera}
          onBarCodeRead={(e) => {
            console.log(e);
            this.handleBarCodeRead(e);
          }}
          type={RNCamera.Constants.Type.back}
          flashMode={RNCamera.Constants.FlashMode.auto}
          aspect={ratio}
          {...cameraProps}
        >
          {this.renderCameraMarker()}
 </RNCamera>`

![20190917_153012](https://user-images.githubusercontent.com/9674574/65069553-47baf280-d961-11e9-9fd7-1f01d1e1dac9.jpg)

Any solution?

**Comment by cristianoccazinsp** [comment]
As a work around, have you tried manually setting the focus point (with autoFocusPointOfInterest to the center of the camera screen?

**Comment by RodrigoAngeloValentini** [comment]
`autoFocusPointOfInterest={{ x: 0.5, y: 0.5 }}`

But not solve the problem.

**Comment by JCVanDam** [comment]
I have the same problem but for reading datamatrix.

Device : Galaxy Core Prime
Android Version : 5.1.1
react-native-camera version: 3.6.0

Here is my component: 
``
<RNCamera
  style={styles.preview}
  type={RNCamera.Constants.Type.back}
  flashMode={RNCamera.Constants.FlashMode.auto}
  defaultVideoQuality={RNCamera.Constants.VideoQuality['2160p']}
  androidCameraPermissionOptions={{
    title: 'Permission to use camera',
    message: 'We need your permission to use your camera',
    buttonPositive: 'Ok',
    buttonNegative: 'Cancel',
  }}
  onBarCodeRead={this.onBarCodeRead}
  barCodeTypes={[RNCamera.Constants.BarCodeType.datamatrix]}
>
``
I tried also with useCamera2api={true}, with RNCamera.Constants.AutoFocus.on and RNCamera.Constants.AutoFocus.off + focusDepth={1} but I don’t see any difference. Focus doesn’t work. (url)
Some issues existe about manual Focus and auto Focus [(#2231](https://github.com/react-native-community/react-native-camera/issues/2231) , [#1499)](https://github.com/react-native-community/react-native-camera/issues/1499) for front camera but I didn't find an answers for Android. 

Is there any solution?

**Comment by Theofilos-Chamalis** [comment]
I have noticed the same behavior on the Samsung Galaxy Tab A 7.0 2016 (T280), which runs on Android 5.1.1.

Neither of the 2 options (autoFocus, autoFocusPointOfInterest) worked when trying to scan a QR Code, so the camera view is blurry and the device cannot read the QR Code.

**Comment by xelmich** [comment]
Anyone found the solution for this problem ? using the exactly same device Samsung Galaxy Tab A 6.0 2016 (SM-T285)
