### ISSUE TITLE
capture to camera roll crashes on certain Android devices

### ISSUE THREAD

**Issue by cdimascio** [react-native-community/react-native-camera#249]
### Steps to reproduce
1. install react-native-camera on a clean samsung device e.g. galaxy tab 4
2. ensure no photos have been taken
3. use react-native-camera to capture picture and store to camera roll
4. app crashes b/c sdcar/DCIM/Camera is missing
### Expected behaviour

image is captured and saved to camera roll
### Actual behaviour

image is captured and crashes when saving to camera roll because DCIM/Camera directly is not found
### Environment
- **Node.js version**: 5.2
- **React Native version**: 0.3.8
- **React Native platform + platform version**: Android KitKat
### react-native-camera

**Version**: npm version or "master"

**Comment by dcworldwide** [comment]
This could be the issue i'm facing (Samsung S5). I'll test later this week to see if switching the photo storage method resolves the issue.

**Comment by fbacker** [comment]
Could it be that the camera is 'locked'. 

Try to open the default camera app, does it give an error? restart the device.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
