### ISSUE TITLE
Failed to list versions for org.webkit:android-jsc.

### ISSUE THREAD

**Issue by oqnunes** [react-native-community/react-native-camera#2490]
Hi everyone.

I'm trying to install react-native-camera in my project, so i follow all steps from but when i set the command react-native run-android i get this error. 

`* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.webkit:android-jsc:+.
     Required by:
         project :app
      > Failed to list versions for org.webkit:android-jsc.
         > Unable to load Maven meta-data from https://jitpack.io/org/webkit/android-jsc/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/org/webkit/android-jsc/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/org/webkit/android-jsc/maven-metadata.xml'. Received status code 522 from server: Origin Connection Time-out`

So anyone can help me? i've been two days looking for some resolution but without success.

**Comment by wouterds** [comment]
Out of nowhere (no configuration changes, no new packages) we started seeing the exact same issue since yesterday as well in our React Native 0.60.5 project. I've been trying to build for 24 hours.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRegularRelease'.
> Could not resolve all task dependencies for configuration ':app:regularReleaseRuntimeClasspath'.
   > Could not resolve org.webkit:android-jsc:+.
     Required by:
         project :app
      > Failed to list versions for org.webkit:android-jsc.
         > Unable to load Maven meta-data from https://jitpack.io/org/webkit/android-jsc/maven-metadata.xml.
            > Could not get resource 'https://jitpack.io/org/webkit/android-jsc/maven-metadata.xml'.
               > Could not GET 'https://jitpack.io/org/webkit/android-jsc/maven-metadata.xml'. Received status code 522 from server: Origin Connection Time-out
   > Could not resolve com.github.droibit.customtabslauncher:launcher:1.0.8.
     Required by:
         project :app > project :react-native-custom-tabs
      > Skipped due to earlier error
```

**Comment by yurkagon** [comment]
Got the same issue with `react-native-image-crop-picker`, fixed by

`maven { url "https://www.jitpack.io" }`
(Added `www`)

I dont know why, but it works

**Comment by oqnunes** [comment]
> Got the same issue with `react-native-image-crop-picker`, fixed by
> 
> `maven { url "https://www.jitpack.io" }`
> (Added `www`)
> 
> I dont know why, but it works

I'm trying to read barcode in my app, does react-native-image-crop-picker can do that? i dont try yet.

**Comment by oqnunes** [comment]
@yurkagon do you know if barcode work on in react-native-image-crop-picker? i'm trying to read a barcode...

**Comment by yurkagon** [comment]
> @yurkagon do you know if barcode work on in react-native-image-crop-picker? i'm trying to read a barcode...

that package is for picking images from files or from camera. I guess its not that case you need. But it got the same issue with `jitpack.io`, so I've just said how to fix the build process

**Comment by wouterds** [comment]
@yurkagon: That works, thanks!

**Comment by rockia** [comment]
I also had this problem with React Native 0.60.5. I submitted a PR to amend the official installation guide: https://github.com/react-native-community/react-native-camera/pull/2497

**Comment by juslin03** [comment]
> Got the same issue with `react-native-image-crop-picker`, fixed by
> 
> `maven { url "https://www.jitpack.io" }`
> (Added `www`)
> 
> I dont know why, but it works

Thank you  yurkagon, your method worked for me. Just add "www" to maven { url "https://jitpack.io" } in "android/build.gradle" file

**Comment by Summerian-Winter** [comment]
@yurkagon: I was " " <--- this close to giving my laptop a lethal headbutt, so I guess my laptop owes you a favour

**Comment by Armen6964** [comment]
Just turn off the internet and retry.

**Comment by RamanathanN** [comment]
I am facing this issue now. Already my "build.gradle" file has "maven { url 'https://www.jitpack.io' }" only. Is there any other solution?

**Comment by amanfcp** [comment]
> Just turn off the internet and retry.

This solution worked. Seems to be some temporary issue

**Comment by fnadj94** [comment]
> 
> 
> I am facing this issue now. Already my "build.gradle" file has "maven { url 'https://www.jitpack.io' }" only. Is there any other solution?



> 
> 
> > Just turn off the internet and retry.
> 
> This solution worked. Seems to be some temporary issue



https://status.bintray.com/incidents/ctv4bdfz08bg

JCenter is down. This seems to be causing this issue

**Comment by christhorp** [comment]
I still facing this problem, tried restarting internet and computer. Any other ideas?

**Comment by hu-qi** [comment]
The same, JCenter.
![image](https://user-images.githubusercontent.com/17986122/111247668-6035c700-8643-11eb-9caa-aef2c17ced87.png)

![image](https://user-images.githubusercontent.com/17986122/111247689-6c218900-8643-11eb-8013-1eb6ae01eccf.png)

**Comment by hu-qi** [comment]
> > Just turn off the internet and retry.
> 
> This solution worked. Seems to be some temporary issue

Hello，How did you solve it？Thanks！

**Comment by KieranCarden** [comment]
Same here, down as well. However, started working a moment ago with no change by me. Good news? But has me worried about the state of things concerning JCenter.

**Comment by jihokim2** [comment]
I found workaround. When you build, turn off wifi. It is working. I think it is temporary solution until Jcenter works fine

**Comment by hu-qi** [comment]
> I found workaround. When you build, turn off wifi. It is working. I think it is temporary solution until Jcenter works fine

Nice! When I run, turn off wifi, it works！But the build failed！

**Comment by NewtonOngko** [comment]
> I found workaround. When you build, turn off wifi. It is working. I think it is temporary solution until Jcenter works fine

after build done i turn on wifi to do login and other its work fine for me

**Comment by EvertonCosmo** [comment]
Need run in offline, Jcenter apparently is down

**Comment by mcvictormurillo** [comment]
The same problem also happens to me. thanks for your help

**Comment by FladioArmandika** [comment]
i just turn off the internet but the build failed.

**Comment by TienTungs295** [comment]
@yurkagon thank you, your solution worked for me

**Comment by unicornRainbows** [comment]
haha turning internet off and doing the build works.. but only if you didn't clean your android build before.. Got to 💌 computers some times hey.. 😉

**Comment by chengsokdara** [comment]
Just wait til Jcenter is up again. Any workaround? I already clean the build cache.
it is currently down
https://status.bintray.com/

**Comment by bblack1225** [comment]
I just turn off the wifi when building my app and its work for me!

**Comment by mcvictormurillo** [comment]
**Jcenter is working now!!!**

**Comment by ekkam04** [comment]
Facing this issue today and the app only builds by disconnecting from the internet. Is Jcenter down again?

**Comment by shaurya2612** [comment]
> Facing this issue today and the app only builds by disconnecting from the internet. Is Jcenter down again?

Came here just to say this, facing the same problem. Try running offline.

**Comment by nolife08021** [comment]
> > Facing this issue today and the app only builds by disconnecting from the internet. Is Jcenter down again?
> 
> Came here just to say this, facing the same problem. Try running offline.

did it works? I dont know why I still getting the same error

**Comment by ekkam04** [comment]
> > Facing this issue today and the app only builds by disconnecting from the internet. Is Jcenter down again?
> 
> Came here just to say this, facing the same problem. Try running offline.

Yes running offline and then once it builds switching to online works for now. So is it a worldwide issue as of now?

**Comment by shaurya2612** [comment]
> > > Facing this issue today and the app only builds by disconnecting from the internet. Is Jcenter down again?
> > 
> > 
> > Came here just to say this, facing the same problem. Try running offline.
> 
> Yes running offline and then once it builds switching to online works for now. So is it a worldwide issue as of now?

Yep

**Comment by troZee** [comment]
For targetSDK 30 it does not work at all:

Before:
```
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
    }
```

After: 
```
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        ndkVersion = "22.1.7171670"
    }
  ```

**Comment by Adeel984** [comment]
> Just turn off the internet and retry.

OMG That works!

**Comment by dipras** [comment]
How to build react native on Offline?

**Comment by denis0324** [comment]
Still same issue

**Comment by relativelyrehan** [comment]
Having the same issue, some other dependencies in my project need an internet connection. Any other solution?

**Comment by Arslan106** [comment]
still same issue

**Comment by ekkam04** [comment]
> How to build react native on Offline?

Just disconnect your computer from the internet and build

**Comment by Hemistone** [comment]
Is here TG? everybody talking this issue as live haha 🤣

**Comment by redvelvet-fan** [comment]
I Have same issue now T.T

**Comment by mohammed-sec2010** [comment]
I Have same issue now

**Comment by youngdocho** [comment]
> > Just turn off the internet and retry.
> 
> OMG That works!

It works for me 👍

**Comment by MaxJadav** [comment]
Any one have alternate option?
Bintray services will no longer be available. JCenter will no longer be available for non-Artifactory clients. This means by the end of March 2021, publishing new packages to Bintray will no longer be allowed. Existing packages can still be downloaded until February 1st 2022.
Ref: https://testfairy.com/blog/jcenter-and-bintray-is-shutting-down-what-to-do/

**Comment by ortegarenzy** [comment]
> Just turn off the internet and retry.

This definitely works right now!

**Comment by xoapit** [comment]
I meet this issue a couple of hours ago, there are no solutions for now. I cannot turn off the internet because I need to build on the server. It's very crazy when Google Service updates something.

**Comment by ThomasMcDonnell** [comment]
I have the encountered the same issue and have been stumped for the last few hours! Turning off the internet is not a solution for me either as it needs to build on a server.

**Comment by huzaifaaak** [comment]
Turning off internet isn't working for me either. Good thing I have local build installed in the emulator. Can run it from the local server.

https://jcenter.bintray.com/ is giving 403 forbidden

**Comment by huzaifaaak** [comment]
Turning off internet isn't working for me either

https://jcenter.bintray.com/ is giving 403 forbidden

**Comment by imarem** [comment]
Jcenter apparently is down https://status.jitpack.io/

**Comment by shoaib90** [comment]
I guess, Need to wait for Jcenter to start working again

**Comment by Rushikesh1212** [comment]
For me also its not working. If anyone find the solution please let us know.

**Comment by choukrus** [comment]
Oh god .. I thought I was the only one facing this problem now as the status of servers doesn't show any problem...

Feeling better now because I thought I changed something in my app ( I didn't, yesterday everything worked fine, and now it doesn't )

Can't switch internet off because it's an react native app..

**Comment by kishoreAwdar** [comment]
OMG. I did lot of things...
Thank god otherwise I will delete all of them

**Comment by maddeha** [comment]
glad that's a common problem

**Comment by LoknathPandit** [comment]
Yes also i am facing same issue

**Comment by Jscripter-pk** [comment]
@LoknathPandit  Turn your internet off and try to run your project

**Comment by khaledJabari-90** [comment]
I'm facing the same issue. 
jitpack is down. 
https://status.jitpack.io/776679744

**Comment by meliodev** [comment]
@shoaib90 Yeah it's good reason to take some rest !

**Comment by PrimulaX** [comment]
Oh it's back. 🥳

**Comment by modnarlluf** [comment]
> Oh it's back.

still down for me :disappointed:

**Comment by amolpatil15** [comment]
> Oh it's back. partying_face

Not working for me yet! Any solution?

**Comment by RukshanWithanage** [comment]
I'm also facing same issue

**Comment by kishoreAwdar** [comment]
> Oh it's back. 🥳

not working...

**Comment by khaledJabari-90** [comment]
Not working yet

**Comment by PrimulaX** [comment]
Ah crap 😄 It's down for me again.

**Comment by Rushikesh1212** [comment]
> Ah crap 😄 It's down for me again.

 😂

**Comment by modnarlluf** [comment]
Working for me, right now

**Comment by kishoreAwdar** [comment]
Its working again... Tea break is over!!!

**Comment by PrimulaX** [comment]
meh its still down
https://status.jitpack.io/776679744

**Comment by RukshanWithanage** [comment]
Still down

**Comment by ThomasMcDonnell** [comment]
Back up for me now and successfully building again 🎉

**Comment by vipin-ios** [comment]
thank GOD it's  working  now

**Comment by PrimulaX** [comment]
![image](https://user-images.githubusercontent.com/16132259/133608320-f3dc9020-5baa-44ad-aba9-669324a20e1b.png)
Still down for me 😢

**Comment by jeltehomminga** [comment]
it's working again for me after upgrade to react-native  0.65.1  https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.65.1

I guess because  jcenter() is removed

see diff here [](https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.65.1)

**Comment by PrimulaX** [comment]
@jeltehomminga upgrade isn't good option I guess for everyone.

**Comment by jeltehomminga** [comment]
> @jeltehomminga upgrade isn't good option I guess for everyone.


Yes off course, still good be good to know for who can or is already considering it

**Comment by NourAliAbdou** [comment]
Re-building offline without cleaning works for me.

**Comment by PrimulaX** [comment]
And finally Jcenter is back. 👾

**Comment by Nestoro** [comment]
jcenter seems to be down again 

[https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml](https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml)

**Comment by Philipidev** [comment]
> jcenter seems to be down again
> 
> https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml

it seens so, iam having problens here too

**Comment by rodrigogaraujo** [comment]
any solution for this?

**Comment by enigmablue** [comment]
stuck too

**Comment by avatarrrrr** [comment]
Ah shit, here we go again.

**Comment by PrimulaX** [comment]
One option is to upgrade RN, there is no jcenter dependency in newer versions, otherwise you have to wait for jcenter server's status.

**Comment by GuilhermeHelioprint** [comment]
@rodrigogaraujo i turned off the internet and built successfully

**Comment by rodrigogaraujo** [comment]
> @rodrigogaraujo i turned off the internet and i built successfully

Thanks man

**Comment by Saviourise** [comment]
> @rodrigogaraujo i turned off the internet and built successfully

tried that, it was building for hours

**Comment by rafaazvd** [comment]
é melhor um upgrade no rn

**Comment by Saviourise** [comment]
> é melhor um upgrade no rn


uma atualização resolve?

**Comment by dmitriy-komarov** [comment]
This issue prevents building Expo Android app using EAS service (cloud builds): crash on the side of Expo server, and I cannot just "turn off Wi-Fi" there.

Subscribed on this topic.

**Comment by ekediala** [comment]
> One option is to upgrade RN, there is no jcenter dependency in newer versions, otherwise you have to wait for jcenter server's status.

Hi. Good day [it is day in my corner of the world lol]. I am on 0.64 and I am still having the same issue. What version did you migrate to to solve this?

**Comment by ekediala** [comment]
> One option is to upgrade RN, there is no jcenter dependency in newer versions, otherwise you have to wait for jcenter server's status.

Hi. Good day [it is day in my corner of the world lol]. I am on 0.64 and I am still having the same issue. What version did you migrate to to solve this?

**Comment by renan-5by5** [comment]
Does anyone have information about jcenter? Will it come back or will it be mandatory to remove it and update to react-native 0.65+?

**Comment by Shruthyshanthraj** [comment]
tried every other workarounds nothing seemed to work but switching off wifi did. Waiting for jcenter up and running.

**Comment by PrimulaX** [comment]
@ekediala On version .66 it doesn't need jcenter dependency, you can check it in your `build.gradle` file.

**Comment by Shruthyshanthraj** [comment]
> tried every other workarounds nothing seemed to work but switching off wifi did. Waiting for jcenter up and running.



> @ekediala On version .66 it doesn't need jcenter dependency, you can check it in your `build.gradle` file.

thank you for the update.

**Comment by sethcwhiting** [comment]
Just started working for me again 🤷‍♂️

**Comment by toddbauermeister** [comment]
Working again for me too

**Comment by anhtuank7c** [comment]
No way, I got issue again :(
