### ISSUE TITLE
Android Camera1 - Inconsistent Aspect Ratio handling

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-camera#2500]
# Bug Report

**To Do First**

- [X] Did you try latest release?
- [X] Did you try master?
- [X] Did you look for existing matching issues?

**Platforms**

Android

**Versions**

- Android: 8, 9, 10
- iOS:
- react-native-camera: 3.4.0
- react-native: 0.60.5
- react: 16.9.0
  

**Description/Current Behaviour**
Setting an invalid aspect ratio on camera mount or if the camera is stopped will just "fail silently" and the default one will be used. However, trying to change it will crash the app if the ratio is invalid (https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/google/android/cameraview/Camera1.java#L339 and https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/google/android/cameraview/Camera1.java#L750)

Camera2 on the other hand, always fails silently. 

Any thoughts on updating that exception to make the Camera1 implementation to also fail silently? Truth is, catching exceptions on property changes is nearly impossible!

In addition, getting the list of supported ratios also requires you to have a camera already opened, so this means it cannot be set initially on camera load.

I wonder if there's any reason for that exception, if not, a PR is as simple as a 1 line change.

**Comment by kidculli** [comment]
Im also noticing that once the camera is ready, changing the aspect ratio doest affect the view or image taken. There should be a way to get the available aspect ratios before loading the Camera. Perhaps we need a custom hook useAvailableAspectRatios() that returns the supported ratios. We can then pass this to the Camera on initial load.
