### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by 1appstudio** [react-native-community/react-native-camera#2502]
I have a lockscreen to enter into the application. Here I want to capture the user photo if user enter the wrong pin. How can achieve this without camera preview?

**Comment by GH974** [comment]
Hi, I suppose it not possible. but juste define in style width and height to 0 ?

**Comment by simistern** [comment]
Taking a photo without preview is not currently supported AFAIK. @GH974's suggestion is probably the best course of action :)

**Comment by 1appstudio** [comment]
Thanks, successfully implemented. Great work
