### ISSUE TITLE
How to get live frames from a camera preview??

### ISSUE THREAD

**Issue by shreyakamoji96** [react-native-community/react-native-camera#2506]
I tried implementing this in my project to recognize fruits from camera preview in real-time using TensorFlow. Instead of grabbing the frames and converting it to jpeg format or base64 string and passing it to javascript, I grabbed the frames via TextureView.getBitmap() from CameraView and feed it to TensorFlow for image recognition and passed the results to Javascript. It's fast and could process frames in real-time. If you're going to convert the byte[] data from onFramePreview to other formats, it may take a while to pass it to javascript.

How to capture live frames in javascript

**Comment by ShaharyarMaroof** [comment]
Hey @shreyakamoji96 , can you please let me know how you achieved this? Can you please share the code to pass frames from live preview to tensorflow? Thanks.

**Comment by sibelius** [comment]
Check this https://github.com/react-native-community/react-native-camera/pull/2505

**Comment by shreyakamoji96** [comment]
> Hey @shreyakamoji96 , can you please let me know how you achieved this? Can you please share the code to pass frames from live preview to tensorflow? Thanks.

I have just implemented camera live preview, not grabbing the live frames. Actually even I wanted the live frames that was the question. If you get any solution please let me know too. Thanks

**Comment by awais-devden** [comment]
@shreyakamoji96 can you please tell me how did you implemented this camera live preview :/ ?

**Comment by rafaelcavalcante** [comment]
> @shreyakamoji96 can you please tell me how did you implemented this camera live preview :/ ?

Have you found any solution, @awaishere? I've opened an issue ( #2984 ) but still no response.

**Comment by awaishere** [comment]
Nope, i haven't found it yet.

**Comment by rafaelcavalcante** [comment]
> Nope, i haven't found it yet.

I'm using [this fork](https://github.com/react-native-community/react-native-camera/pull/2505) and taking pictures in a specific interval, then i use the taken images.

**Comment by AdarshJais** [comment]
> Nope, i haven't found it yet.

Still ?

**Comment by klayverxd** [comment]
> Nope, i haven't found it yet.

Still?

**Comment by wallride** [comment]
Still. :(

**Comment by shahnupur1901** [comment]
Still?
