### ISSUE TITLE
Camera (Shutter sound)

### ISSUE THREAD

**Issue by 1appstudio** [react-native-community/react-native-camera#2512]
How can i turn off capturing sound while taking photos in IOS?

**Comment by dingdongping** [comment]
How can i turn off capturing sound while taking photos in IOS and android?

**Comment by kkusanagi** [comment]
Till now still now way to do that. I think this is to prevent app from secretly take picture around.

**Comment by kkusanagi** [comment]
Add this.
'playSoundOnCapture={false}'

Be aware of some phone don't follow this trick.

```
<RNCamera
            ref={(cam) => {
              this.camera = cam;
            }}
            playSoundOnCapture={false}
>
</RNCamera>
```
