### ISSUE TITLE
BUG :  TCTCameraViewFinder.java  Line:77

### ISSUE THREAD

**Issue by Zachary-Leung** [react-native-community/react-native-camera#252]
Error:
RCTCamera.getInstance().setTorchMode(_cameraType, flashMode);

Right：
RCTCamera.getInstance().setFlashMode(_cameraType, flashMode);

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
