### ISSUE TITLE
crash on iphone 6+, ios 12.2

### ISSUE THREAD

**Issue by lekienhust94** [react-native-community/react-native-camera#2523]
**Platforms**
- iOS
**Versions**
- iOS 12.2
- react-native-camera 3.6.0
- iphone 6+

**Description/Current Behaviour**
Crash when take photo with takePictureAsync()

**Expected Behaviour**
I try debug in RNCamera.m then i see crash at captureStillImageAsynchronouslyFromConnection

**Comment by cristianoccazinsp** [comment]
What does the crash say exactly? 3.7.0 adds some fixes, and another PR will add even further checks to prevent crashes due to unsupported settings.
