### ISSUE TITLE
Error on catalyst

### ISSUE THREAD

**Issue by djschilling** [react-native-community/react-native-camera#2529]
# Bug Report

**Platforms**

MacOS Catalina

The library does not compile when trying to use the new build target `Mac` in XCode.

The error is:

```
node_modules/react-native-camera/ios/RN/RNCamera.m:688:31: 'setHighResolutionStillImageOutputEnabled:' is unavailable: not available on macCatalyst
```

It is not important for me that the lib works on catalyst but it should compile so that i can build the project for catalina.

Screenshot from `RNCamera.m`

<img width="1572" alt="Screenshot 2019-10-09 at 22 11 22" src="https://user-images.githubusercontent.com/3503166/66516653-d2ff5200-eae1-11e9-978e-714866f8054e.png">

**Comment by djschilling** [comment]
Also `#import <AssetsLibrary/ALAssetsLibrary.h>` in `RCTCameraManager.m` gives an error:

```
node_modules/react-native-camera/ios/RCT/RCTCameraManager.m:9:9: AssetsLibrary is deprecated and is not available when building for Mac Catalyst. Consider migrating to Photos instead, or use `#if !TARGET_OS_MACCATALYST` to conditionally import this framework, first importing TargetConditionals.h if necessary.
```

**Comment by cristianoccazinsp** [comment]
Have you tried following the instructions from here? https://developer.apple.com/documentation/xcode/creating_a_mac_version_of_your_ipad_app

Can you exclude the whole RNCamera library instead? Is this really the only library that doesn't compile for MacOS? Considering it is a camera library meant for iOS/ipad, there are probably a lot of caveats when building for MacOS.

**Comment by djschilling** [comment]
Sure when i exclude it from my build it works.
But this is not a nice build step that i want to do everytime i want to build for the mac.

I think a first fix for this library could be something like this: https://github.com/facebook/react-native/pull/25427/files

And then just showing maybe a black screen instead of the camera, telling that it is not working on Catalina.

This would be nice.

**Comment by cristianoccazinsp** [comment]
Thats a good idea. The black screen already happens for the simulator. If
you look at the code there are a bunch of macros to handle the simulator
case, so that probably can be extended to Catalina as well.

**Comment by djschilling** [comment]
still an issue

**Comment by djschilling** [comment]
still an issue

**Comment by djschilling** [comment]
i guess still nothing happened here.

**Comment by sibelius** [comment]
feel free to send a PR fixing it

**Comment by mouhsinelonly** [comment]
any solution for this

**Comment by marcosrdz** [comment]
We apply these two patches to get it to compile on Catalyst:

https://github.com/BlueWallet/BlueWallet/blob/master/scripts/maccatalystpatches/RCTCameraManager.patch
https://github.com/BlueWallet/BlueWallet/blob/master/scripts/maccatalystpatches/RNCamera.patch
