### ISSUE TITLE
App Crashed when took pictures while options contain fixOrientation: true

### ISSUE THREAD

**Issue by januarsmad** [react-native-community/react-native-camera#2540]
# Bug Report

**Platforms**
Android

**Versions**

- Android: 6.0.1
- react-native-camera: 2.11.2
- react-native: 0.59.6
- react: 16.8.3

**Description/Current Behaviour**

the app always crash when i took picture while options contain fixOrientation: true.
here's the option list that i used in my project.
`const options = {
quality: this.props.backgroundImage ? 1 : 0.8,
width: this.props.backgroundImage ? 1080 : 698,
base64: true,
forceUpOrientation: true,
orientation: 'portrait',
fixOrientation: true,
mirrorImage: !this.props.cameraTypeBack,
pauseAfterCapture: true,
};`

when using ios, it works perfectly fine. 
The device i use is Samsung J5.

**Expected Behaviour**
success taking picture

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
Can you upgrade to master?

**Comment by januarsmad** [comment]
i already use master since i installed it. i just upgraded from 2.6.0 to 2.11.2 and tested it before post this.

**Comment by chakrihacker** [comment]
Any other code changes?

Try unlink and let react-native do auto-link if you are at 0.60 or above

**Comment by januarsmad** [comment]
i just found the solution. 
after checking node_modules, i found that there's another property called writeExif that accept object. So i add this to my options config, and this is what my config looks like:
`
const options = {
          width: 1080,
          base64: true,
          orientation: 'portrait',
          forceUpOrientation: true, // IOS only
          exif: true,
          writeExif: {
            Orientation: 6,
          },
          mirrorImage: !this.props.cameraTypeBack,
          pauseAfterCapture: true,
        };
`
