### ISSUE TITLE
running basic example fails

### ISSUE THREAD

**Issue by danipralea** [react-native-community/react-native-camera#2547]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

iOS

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:
  

**Description/Current Behaviour**

Running the basic example results in error
I currently get ```[error][tid:NSOperationQueue 0x2803a9a80 (QOS: UNSPECIFIED)][RCTCxxBridge.mm:414] Failed to load bundle(http://192.168.0.112:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `/Users/praleadanut/Downloads/react-native-camera-master/src/index.js`: Module `@babel/runtime/helpers/interopRequireDefault` does not exist in the Haste module map```
**Expected Behaviour**

To run the basic example

**Steps to Reproduce**

started the project, ran the Xcode project

**Additionals**

![IMG_1030](https://user-images.githubusercontent.com/768893/67017306-3f8dd880-f102-11e9-81fd-2902241571fa.PNG)

**Comment by sibelius** [comment]
this is a problem with dependencies that does not match

**Comment by sibelius** [comment]
try to upgrade to latest react-native version: https://react-native-community.github.io/upgrade-helper/

and see if it helps

**Comment by danipralea** [comment]
> try to upgrade to latest react-native version: https://react-native-community.github.io/upgrade-helper/
> 
> and see if it helps

I tried doing that and I still get a bunch of errors
<img width="3000" alt="Screenshot 2019-10-17 17 44 58" src="https://user-images.githubusercontent.com/768893/67019814-e7f16c00-f105-11e9-9ed1-78e74edb3337.png">
![Uploading Screenshot 2019-10-17 17.45.16.png…]()

**Comment by danipralea** [comment]
I know. I saw that. but there's no `Podfile` file in my `ios` directory
<img width="755" alt="Screenshot 2019-10-17 17 50 10" src="https://user-images.githubusercontent.com/768893/67020242-91386200-f106-11e9-8680-9b6eb03337fe.png">

**Comment by sibelius** [comment]
on mlkit it has

try to copy and paste from there

**Comment by danipralea** [comment]
easy fix with the target name + this `[!] The name of the given podspec `Yoga` doesn't match the expected one `yoga`` and I removed it
and now this
<img width="1039" alt="Screenshot 2019-10-17 18 23 54" src="https://user-images.githubusercontent.com/768893/67023322-4b31cd00-f10b-11e9-9e94-8b70bcadd4fd.png">
and I'm stuck again.

**Comment by sibelius** [comment]
try to upgrade and check if pod is correct

**Comment by danipralea** [comment]
is there any way you can try on your side and see if it works @sibelius ? 
thanks

**Comment by danipralea** [comment]
The demo is unusable, so I moved to another library. going to close this.

**Comment by fabriziobertoglio1987** [comment]
I experienced [this issue][1] with the Basic Example. The Advanced Example works 100% fine and I believe there is no reason to mantain the basic example, but I can try to fix this after implementing the android side for [2711][2]. Thanks

[1]: https://github.com/facebook/react-native/issues/21310
[2]: https://github.com/react-native-community/react-native-camera/pull/2711#event-3078832678

**Comment by renatobenks** [comment]
which package did you move the examples @danipralea? I've been facing this issue https://github.com/facebook/react-native/issues/21310 to run the mlkit example, which I just got it to fix adding the @babel/runtime package as was commented at here https://github.com/facebook/react-native/issues/21310#issuecomment-586365218

anyway, I'm guessing that it seems to be related to an older version (`0.59.1`) of react-native version been used, what do you guys think about it?

**Comment by renatobenks** [comment]
@sibelius what do you think? it does make sense to upgrade the mlkit example for the latest react-native version or then, add the `@babel/runtime` as `devDependency`, in order to fix that?

**Comment by sibelius** [comment]
it is better to upgrade to latest version, and add the missing deps
