### ISSUE TITLE
RNCamera 3.7.2 -- iOS crashes unless microphone permission is given even though captureAudio=false

### ISSUE THREAD

**Issue by acoutts** [react-native-community/react-native-camera#2553]
# Bug Report

Platform affected: iOS

**Versions**
3.7.2

``` typescript
<RNCamera
  style={{flex: 1}}
  type={RNCamera.Constants.Type.back}
  flashMode={RNCamera.Constants.FlashMode.off}
  captureAudio={false}
  onGoogleVisionBarcodesDetected={this.checkBarcodes}>

  // ...
  
</RNCamera>
```

On iOS as soon as the RNCamera component is rendered the app crashes unless I add the following to Info.plist:

```
	<key>NSMicrophoneUsageDescription</key>
	<string>.......................</string>
```

Why does RNCamera need access to the microphone if audio is disabled? I only want to scan QR codes so there's no need to record video or audio.

**Comment by cristianoccazinsp** [comment]
Can you try with 3.8.0?

**Comment by acoutts** [comment]
Upgrading to 3.8.0 fixed it! Thanks.
