### ISSUE TITLE
Crash importing org.reactnative.camera.RNCameraPackage on Android 4.* 

### ISSUE THREAD

**Issue by gbalduzzi** [react-native-community/react-native-camera#2559]
# Bug Report

**Platforms**
Android

**Versions**
- Android: 4.* (seen in 4.4.2, 4.4.4, 4.3)
- react-native-camera: `3.7.0`
- react-native: `0.61.2`
- react: `16.9.0`

**Description/Current Behaviour**
I recently published an update to our app, upgrading react-native to version `0.61.2` and react-native-camera to `3.7.0`. I got on my crash reporting system (bugsnag) a lot of crash report on devices running Android 4.*

Error message:
```
java.lang.NoClassDefFoundError  PackageList.java:80
org.reactnative.camera.RNCameraPackage
```

**Expected Behaviour**

Not to crash on android 4, given that the minSdKVersion is 16

**Steps to Reproduce**
Use the package with react native 0.61.2

**Additionals**
Full stacktrace:
```
java.lang.NoClassDefFoundError - org.reactnative.camera.RNCameraPackage
PackageList.java:80 - com.facebook.react.PackageList.getPackages
MainApplication.java:38 - com.yourvoice.ccApp.MainApplication$1.getPackages
ReactNativeHost.java:76 - com.facebook.react.ReactNativeHost.createReactInstanceManager
ReactNativeHost.java:38 - com.facebook.react.ReactNativeHost.getReactInstanceManager
ReactDelegate.java:103 - com.facebook.react.ReactDelegate.loadApp
ReactActivityDelegate.java:88 - com.facebook.react.ReactActivityDelegate.loadApp
ReactActivityDelegate.java:83 - com.facebook.react.ReactActivityDelegate.onCreate
ReactActivity.java:44 - com.facebook.react.ReactActivity.onCreate
MainActivity.java:17 - com.yourvoice.ccApp.MainActivity.onCreate
Activity.java:5619 - android.app.Activity.performCreate
Instrumentation.java:1093 - android.app.Instrumentation.callActivityOnCreate
ActivityThread.java:2512 - android.app.ActivityThread.performLaunchActivity
ActivityThread.java:2607 - android.app.ActivityThread.handleLaunchActivity
ActivityThread.java:174 - android.app.ActivityThread.access$900
ActivityThread.java:1325 - android.app.ActivityThread$H.handleMessage
Handler.java:102 - android.os.Handler.dispatchMessage
Looper.java:146 - android.os.Looper.loop
ActivityThread.java:5756 - android.app.ActivityThread.main
Method.java:-2 - java.lang.reflect.Method.invokeNative
Method.java:515 - java.lang.reflect.Method.invoke
ZygoteInit.java:1291 - com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
ZygoteInit.java:1107 - com.android.internal.os.ZygoteInit.main
NativeStart.java:-2 - dalvik.system.NativeStart.main
```

**Comment by cristianoccazinsp** [comment]
Looks like a linking error to me. That's react not finding the linked native module.

**Comment by gbalduzzi** [comment]
Yeah, it looks like a linking problems but it only occurs on android 4. The same app is shipped on devices with every kind of android version from `4.0` to `10`, but only devices with android `4.*` are facing the issue.

The library is automatically linked using react-native `0.60` feature. In my builded file `com.facebook.react.PackageList` I correctly have both the import:
`import org.reactnative.camera.RNCameraPackage;`
and the package registration:
```
public ArrayList<ReactPackage> getPackages() {
    return new ArrayList<>(Arrays.<ReactPackage>asList(
      new MainReactPackage(),
      ... other packages... ,
      new RNCameraPackage(),
      ... other packages...
    ));
  }
```

Am I supposed to link it differently?

**Comment by gbalduzzi** [comment]
The issue was related to multiDex, the error message about RNCameraPackage was just a coincidence.

In case anyone ends up here: after setting `multiDexEnabled true` in your app/build.gradle file, you also need to add the dependecy

`implementation 'com.android.support:multidex:1.0.3'`

and modify your `MainApplication` to extend `MultiDexApplication` instead of just `Application`
