### ISSUE TITLE
hello,I add <Text style={styles.capture} onPress={this.takePicture.bind(this)}>[CAPTURE]</Text>, but I don't see it ?

### ISSUE THREAD

**Issue by happyEgg** [react-native-community/react-native-camera#257]
<Text style={styles.capture} onPress={this.takePicture.bind(this)}>[CAPTURE]</Text>
### Environment
- **Node.js version**:v5.6
- **React Native version**:o.22.2
- **React Native platform + platform version**: Android 5.0, etc
### react-native-camera

**Version**: npm version or "master"

**Comment by KevinHu2014** [comment]
By adding it outside the <Camera> , you'll be able to see it

`<View style={styles.container}>
        <Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          style={styles.preview}
          aspect={Camera.constants.Aspect.fill}>
        </Camera>
         <Text style={styles.capture} onPress={this.takePicture.bind(this)}>[CAPTURE]</Text>
      </View>`

**Comment by KevinHu2014** [comment]
close

**Comment by KevinHu2014** [comment]
closes #257

**Comment by happyEgg** [comment]
It's successed!!! ths，
I have a question
this.camera.capture()
      .then((data) => console.log(data))
      .catch(err => console.error(err));

data: content://media/external/images/media/512,
but I get pictures of the actual path is /storage/emulated/0/Pictures/1461061483049.jpg
why?

**Comment by happyEgg** [comment]
@KevinHu2014

**Comment by cubbuk** [comment]
@happyEgg that's relative path to camera roll, by default camera component save your images to camera roll, if you change the `captureTarget` to `disk` then you will retrieve the original path:

`Camera ref="cam" captureTarget={Camera.constants.CaptureTarget.disk}/>`

**Comment by happyEgg** [comment]
@cubbuk you're right!!!!thanks~.~

**Comment by sibelius** [comment]
styling issues
