### ISSUE TITLE
Autofocus didn't work on some device

### ISSUE THREAD

**Issue by anggaand123** [react-native-community/react-native-camera#2575]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
Autofocus didn't work on some device
My Device is Samsung Galaxy Tab A SM-T280

![photo6217240254071548171](https://user-images.githubusercontent.com/13533060/68560202-9de47780-0472-11ea-996e-decb75074d03.jpg)

**Tags**
camera, barcode, autofocus

**Comment by cristianoccazinsp** [comment]
Can you connect the device and get some logs from logcat / android studio? Make sure to filter by your application and to get logs near the time when you open the camera. If there's anything wrong with setting autofocus, it will probably show there.

**Comment by anggaand123** [comment]
> 11-14 20:30:06.579 12688-12688/? E/CAMERA_1::: true; Exposure: 0
11-14 20:30:06.579 12688-12688/? E/CAMERA_1::: -4
11-14 20:30:06.579 12688-12688/? E/CAMERA_1::: 4

I got this @cristianoccazinsp

**Comment by anggaand123** [comment]
also when i touch the screen i got this

> E/unknown:ReactNative: Got DOWN touch before receiving UP or CANCEL from last gesture

**Comment by cristianoccazinsp** [comment]
The touch event is most likely unrelated.

As for the other 3 lines of logs, are you sure there isn't more? Can you share your <RNCamera> component?

If setting the autofocus value failed for some reason, you should be seeing messages like the ones written here: https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/google/android/cameraview/Camera1.java#L484

**Comment by anggaand123** [comment]
im not installed version 3
i used 2.11
cause i got some error about manifest with version 3 
@cristianoccazinsp
