### ISSUE TITLE
Stop face detection when face is out of camera angle of view.

### ISSUE THREAD

**Issue by Quantum-35** [react-native-community/react-native-camera#2576]
# Question
Is there a way to automatically disable face detection when a user moves their face outside of the camera angle of view.
The rectangle persists when there is no face to capture.
![Screenshot_20191111-221251](https://user-images.githubusercontent.com/39088834/68624970-15ed8480-04e9-11ea-8a92-53ddc25e68d3.png)

**Comment by liguanhan** [comment]
Is there any progress on this issue？
