### ISSUE TITLE
Video Stabilization Example

### ISSUE THREAD

**Issue by ChristopherJohnson25** [react-native-community/react-native-camera#2579]
Could someone share some examples of how the video stabilization works? Are there certain standards I should be following? Currently, the video recordings from my app are very shaky.

**Comment by mauriciopf** [comment]
@ChristopherJohnson25 I have the same issue, did you were able to make it work???
 I have a prop using 
**videoStabilizationMode={RNCamera.Constants.VideoStabilization.standard}** but it seems that is not doing anything, and by default in Android the video is not shaky at all.
