### ISSUE TITLE
Flow error in RNCamera.js for View.props

### ISSUE THREAD

**Issue by James-E-Adams** [react-native-community/react-native-camera#2582]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

 N/A

**Versions**

- Android: 
- iOS:
- react-native-camera:3.9.0
- react-native:0.61.2
- react:16.9
- flow-bin: 0.105.1,
  

**Description/Current Behaviour**

![Screen Shot 2019-11-14 at 4 08 02 pm](https://user-images.githubusercontent.com/9067274/68828261-35f39280-06f9-11ea-81e5-6f9a3cd33ff4.png)

Flow error on `View.props`

Run flow on a codebase using react-native-camera

Haven't tried in a basic repo but if no one else is having this problem it might just be our flowconfig. Can post it if hard to repro.

**Comment by James-E-Adams** [comment]
Similarly: 
![Uploading Screen Shot 2019-11-14 at 4.18.53 pm.png…]()

**Comment by sibelius** [comment]
Can you send a pull request upgrading Flow to latest version and fixing this issues?

**Comment by James-E-Adams** [comment]
Sure - I'll look into it when I have better internet to clone the repo!

**Comment by NonkelDaniel** [comment]
I am also having this issue, how can we move past this?
