### ISSUE TITLE
googleVisionBarcodeType can't assign all setting

### ISSUE THREAD

**Issue by bourasseaun** [react-native-community/react-native-camera#2585]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

Huawai P8Lite
Android 8.0.0

**Versions**

- Android: 8.0.0
- iOS:
- react-native-camera: 3.8.0
- react-native: 0.61.2
- react:
  

**Description/Current Behaviour**

I can't configure my setting googleVisionBarcodeType , with the setting Code_39 OR CODE_128.
I don"t have all setting permit. 
Object.getOwnPropertyNames(RNCamera.Constants.GoogleVisionBarcodeDetection.BarcodeType) GIVE ME THIS : 
["ITF", "UPC_A", "SMS", "PRODUCT", "ISBN", "GEO", "EMAIL", "PDF417", "DRIVER_LICENSE", "TEXT", "AZTEC", "EAN_8", "DATA_MATRIX", "UPC_E", "WIFI", "None", "EAN_13", "URL", "QR_CODE", "PHONE", "CONTACT_INFO", "CALENDAR_EVENT", "ALL"]

**Expected Behaviour**

Object.getOwnPropertyNames(RNCamera.Constants.GoogleVisionBarcodeDetection.BarcodeType) :
["CODE_39","CODE_128","CODE_93","CODABAR", "ITF", "UPC_A", "SMS", "PRODUCT", "ISBN", "GEO", "EMAIL", "PDF417", "DRIVER_LICENSE", "TEXT", "AZTEC", "EAN_8", "DATA_MATRIX", "UPC_E", "WIFI", "None", "EAN_13", "URL", "QR_CODE", "PHONE", "CONTACT_INFO", "CALENDAR_EVENT", "ALL"]

**Steps to Reproduce**

**Comment by sibelius** [comment]
Can you add this?
