### ISSUE TITLE
is there a way to detect if it's pop-up camera?

### ISSUE THREAD

**Issue by carlmagumpara** [react-native-community/react-native-camera#2586]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by cristianoccazinsp** [comment]
Maybe such info would be better requested at https://github.com/react-native-community/react-native-device-info ? Is it even possible to query for that?

**Comment by carlmagumpara** [comment]
> Maybe such info would be better requested at https://github.com/react-native-community/react-native-device-info ? Is it even possible to query for that?

just post the issue in react-native-device-info thanks
