### ISSUE TITLE
[Android] Video capture from front camera results in mirroring video

### ISSUE THREAD

**Issue by tusharsarkar** [react-native-community/react-native-camera#2594]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

**Versions**

- Android: 9.0.0
- react-native-camera: 3.9.0

  

**Description/Current Behaviour**

If you capture video from the front camera of your android device then the captured video is in mirrored condition. I have tried option mirrorVideo: false but resulted video always mirrored

**Expected Behaviour**

The video should be in the actual state as it captured. 

**Steps to Reproduce**

Captured video from the android front camera.

**Comment by cristianoccazinsp** [comment]
Looking at the source code, looks like `mirrorVideo` is only implemented for iOS?

https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/org/reactnative/camera/RNCameraView.java#L267

https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/google/android/cameraview/CameraView.java

https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/google/android/cameraview/Camera1.java#L722

Doing a quick look, it doesn't seem like Android can mirror videos as easily as iOS, which would explain why it wasn't implemented: https://stackoverflow.com/questions/47197703/how-to-make-video-captured-by-front-camera-not-being-inverse-android

I think the docs have a bug where it should state this is an iOS only option.
