### ISSUE TITLE
Image not displayed after upgrading the app

### ISSUE THREAD

**Issue by ahmadallo1** [react-native-community/react-native-camera#2608]
Image in not displayed after upgrading the app, we are using react-native-camera 3.9.0 and react native v0.61. After taking the picture using takePictureAsync and saving the image path (image uri) and displaying is normally. If we trying to upgrade the app and reopen it the image path is correct but the image is not displaying.

Platform:
IOS

Any help how to fix this issue or what is the issue in this case?

**Comment by sibelius** [comment]
android or ios?

**Comment by ahmadallo1** [comment]
@sibelius the issue is on IOS

**Comment by cristianoccazinsp** [comment]
What do you mean exactly by upgrading the app?

If you are using iOS, you should NOT be storing any URI returned by any library. IOS will change part of the path after each application update or backup restore. Not really related to the camera library.

**Comment by ahmadallo1** [comment]
@cristianoccazinsp I mean updating the application. Is there a way to get those images?

**Comment by ahmadallo1** [comment]
@cristianoccazinsp I mean updating the application. Is there a way to get those images again?

**Comment by cristianoccazinsp** [comment]
The images will remain there, but you need to adjust your stored path to
the new path apple will assign to your app after an update.

I recommend you check the react native fetch blob library to work with the
file system.

**Comment by cristianoccazinsp** [comment]
If your goal is to permanently store the image on the device, you will most likely need to do two things. First, copy the image to the app's documents storage or somewhere that's not the cache folder (which is where RN stores the pictures, and this folder can be cleaned up automatically). Second, only store the relative path, and re-build it at run time when needed. That is, store only the part after `fs.dirs.DocumentDir`, and prepend it when loading it from your storage.

**Comment by ahmadallo1** [comment]
@cristianoccazinsp I want to store the images on the device in order to display them again. So first we are not able to get saved images from the cache folder?

**Comment by cristianoccazinsp** [comment]
You are, you can also use `fs.dirs.CacheDir` (from react-native-fetch-blob) to find where's the cache folder. You could do the same I described above; only store the relative path, and then prepend `fs.dirs.CacheDir` to re-build the final path. If your app is updated and Apple changes your app's location, you would still get the right path/data.

However, the cache folder can be cleaned up by the OS at any time (both android and iOS), so it is not a safe place to store permanent things.

**Comment by sibelius** [comment]
I think this should be in the docs

**Comment by cristianoccazinsp** [comment]
This is definitely not a RNCamera issue though, just file system management of each platform. For iOS, it is quite surprising apple changes the storage path so frequently.
