### ISSUE TITLE
Can i get the image data on the onFacesDetected event? [Question]

### ISSUE THREAD

**Issue by KarlHeitmann** [react-native-community/react-native-camera#2617]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
How can I get the image data once a face is detected? In order for a face to be detected, there must be an image processing of an photograph. When I use the onFacesDetected props on an arrow function, I get the following keys on the first object argument:
- faces
- target
- type

I was expecting also a _data_ object that may have the image data so I can cut the face and work on it.

I know that I can use the onFacesDetected callback and use the camera object to take a new photo using the function takePictureAsync(). However, I'll have to pause the camera, then resume, and the RNCamera element will appear with lag. In addition, since this function is async, when the new photo will arrive, the face may move and the face object may not match accurately with the new image.

It would be far more efficient if I can take the original image data on which the face was detected whenever the onFacesDetected callback is triggered. Maybe this photo is stored on RNCamera's cache?

Any different ideas or feedback about solving this issue is welcome.

Thanks.

PS: It is well written the tag of this issue? 

**Tags**
[Question]

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by liguanhan** [comment]
I need it too. Is there any solution？
