### ISSUE TITLE
Can't get full text of QR Code

### ISSUE THREAD

**Issue by dudgns0908** [react-native-community/react-native-camera#2624]
# Bug Report

**To Do First**

- [x] Did you try latest release?  Yes
- [x] Did you try master?  Yes
- [x] Did you look for existing matching issues?  Yes

**Platforms**

**Versions**
- Android: all
- iOS: all
- react-native-camera: 3.13.1
- react-native: 0.61.2
- react: 16.9.0

when read this qrcode, 
![image](https://user-images.githubusercontent.com/17000963/70050835-3f468f80-1613-11ea-8181-3945d26e7819.png)

I can not get full text that below text
> 911,,,,9先　ABC医院　0000-11-2222ください。,1」,2,錠,2,62222090

But This QR Code has this text:

> JAHISTC04
> 1,サンプル　太郎,1,19691010,,,,,,
> 2,,,9
> 3,,,,9
> 4,,,9
> 5,20170416
> 11,ABC医院,20,1,1234567,,,
> 15,サンプル　花子,0000-11-2222,1
> 51,ABC医院,20,1,123456755,石田　公孝,
> 201,1,ネキシウムカプセル２０ｍｇ,1,カプセル,2,622080801
> 281,1,,1,
> 291,1,,1,
> 301,1,朝食後,35,日分,1,1,
> 311,1,,1,
> 391,1,,1,
> 201,2,アムロジピン錠５ｍｇ「ツルハラ」,1,錠,2,620007877
> 281,2,,1,
> 291,2,グレープフルーツジュースは飲まないようにしましょう,1,
> 301,2,朝食後,35,日分,1,1,
> 311,2,,1,
> 391,2,車の運転に注意が必要です,1,
> 201,3,アトルバスタチン錠１０ｍｇ「サンド」,1,錠,2,622127001
> 281,3,,1,
> 291,3,グレープフルーツジュースは飲まないようにしましょう,1,
> 301,3,朝食後,35,日分,1,1,
> 311,3,,1,
> 391,3,,1,
> 201,4,ラックビー錠,2,錠,2,622113001
> 281,4,,1,
> 291,4,,1,
> 301,4,朝夕食後,35,日分,1,1,
> 311,4,,1,
> 391,4,,1,
> 201,5,フェキソフェナジン塩酸塩錠６０ｍｇ「ＥＥ」,2,錠,2,622220901
> 281,5,,1,
> 291,5,,1,
> 301,5,朝夕食後,35,日分,1,1,
> 311,5,,1,
> 391,5,,1,
> 401,他の薬を併用する際は、相談してください。,1
> 411,,9
> 501,連絡先　ABC医院　0000-11-2222
> 601,,
> 701,,,,9
> 911,,,

**Comment by dudgns0908** [comment]
@sibelius IOS also has this problem

**Comment by sibelius** [comment]
can you dig in native code to find the issue?

**Comment by dudgns0908** [comment]
I have no idea...
how to access native code?

**Comment by cristianoccazinsp** [comment]
Looks like a very convoluted QR Code! Have you tried other reads to see if they have the same issue?

**Comment by dudgns0908** [comment]
@cristianoccazinsp IPhone and Android's general camera's Scanner can read it. however, RNCamera's onBarCodeRead function can not read it.

**Comment by dudgns0908** [comment]
[Solved] That's QR code doesnt have  '\n', It is only has '/r'.
