### ISSUE TITLE
Auto linking / linking error when modifying the POD file for iOS

### ISSUE THREAD

**Issue by maderesponsively** [react-native-community/react-native-camera#2627]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**
iOS

**Versions**

- Android:
- iOS: 13+
- react-native-camera: 3.13.1
- react-native: 0.61.4
- react: 16.9.0

**Description/Current Behaviour**
I have followed the iOS setup for 'BarcodeDetectorMLKit' via [React native camera installation](https://react-native-community.github.io/react-native-camera/docs/installation.html#modifying-podfile ).

After I modify the pod file, I'm receiving the following error when running the cmd 'react-native run-ios' 

> error React Native CLI uses auto-linking for native dependencies, but the following modules are linked manually:  - react-native-camera (to unlink run: "react-native unlink react-native-camera")

I have not linked react-native-camera and I'm relying on auto linking. I have tried unlinking as the error message describes to no avail. This error only appears when I edit the pod file to edit the additional react-native-camera subspecs. 

What am I doing wrong? Should I just ignore the error?

**Expected Behaviour**

No error and auto link react-native-camera.

**Comment by cristianoccazinsp** [comment]
Can't fully comment on this since I haven't used those features. However, it looks like you are indeed manually linking RNCamera (when following the above instructions)

```
pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'TextDetector',
  'FaceDetectorMLKit',
  'BarcodeDetectorMLKit'
]
```

Since adding that makes rn camera "manually linked", you will need to configure your project to tell RN that that library should not be autolinked. I'm not sure if there's a better way around it.
