### ISSUE TITLE
Android Error: still running in background when component is not showing anymore

### ISSUE THREAD

**Issue by agrass** [react-native-community/react-native-camera#263]
### Expected behaviour

Camera stop running when change the route view
### Actual behaviour

Camera still running and logging this like crazy: 

```
D/QCamera2HWI(  285): bool qcamera::QCamera2HardwareInterface::TsMakeupProcess(mm_camera_buf_def_t*, qcamera::QCameraStream*, unsigned char*, TSRect&) pch_makeup_enable = null
D/mm-camera-intf(  285): mm_stream_qbuf: VIDIOC_QBUF buf_index 2,stream type 1,frame_idx 305,queued cnt 5
E/mm-camera(  326): isp_thread_proc_cmd: HW update still on going
D/mm-camera-intf(  285): mm_stream_read_msm_frame: VIDIOC_DQBUF buf_index 1, frame_idx 306, stream type 7, queued cnt 7
D/mm-camera-intf(  285): mm_stream_qbuf: VIDIOC_QBUF buf_index 1,stream type 7,frame_idx 306,queued cnt 8
```

Then when I re render the component of camera it fail and don't show nothing. 
### Environment

Android with RN 0.19 or RN 0.24 
### react-native-camera

master

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
