### ISSUE TITLE
dont work on android 4.2.2 

### ISSUE THREAD

**Issue by moh76** [react-native-community/react-native-camera#2634]
hi 
 <RNCamera
          ref={ref => {
            this.camera = ref;
          }}
          style={{
            flex: 1,
            width: '100%',
          }}
          onGoogleVisionBarcodesDetected={this.barcodeRecognized}
   > </RNCamera> 
        

this code worked on android v7 but on v4.2.2 show below error

"error while updating property 'cameraId' of a view managed by: RNCamera"

how fix it ?

**Comment by cristianoccazinsp** [comment]
Can you try without barcodes first? Can you get an error stack trace from android studio / logcat?

**Comment by moh76** [comment]
i tried #2635 and it worked 

thank you 

> Can you try without barcodes first? Can you get an error stack trace from android studio / logcat?
> 
> Related issue: #2528
> 
> Not sure why it was closed, did we ever get a PR to fix it? In short, this will crash with Android below API level 19 (Android 4.4).
> 
> Update: Can you try with this PR? #2635
