### ISSUE TITLE
Unable to Scan this EAN-13

### ISSUE THREAD

**Issue by Pczek** [react-native-community/react-native-camera#2640]
**Platforms**
iOS

**Versions**

- Android:
- iOS: 13.2.3
- react-native-camera: 3.13.1
- react-native: 0.60.5
- react: 16.9.0

**Description/Current Behaviour**
I'm using the `onBarCodeRead` API on iOS and it works great so far. However, I can't read this specific code. Can someone tell me why? I'm using the Google MLKit lib on Android and it works fine.

This is my barcode types setup. This is also a ean13 code right?
```
barCodeTypes: [RNCamera.Constants.BarCodeType.ean13],
```

<img width="244" alt="Screenshot 2019-12-12 at 16 25 48" src="https://user-images.githubusercontent.com/839848/70725808-56fdd200-1cfd-11ea-8f30-9e1654ebee33.png">

**Expected Behaviour**
I it should read the barcode.

**Steps to Reproduce**

Try to scan the barcode screenshot

**Comment by cristianoccazinsp** [comment]
I cannot seem to scan that code neither; however, I can scan EAN13 codes from google just fine. Any chance it is a bad code?

**Comment by Pczek** [comment]
When I generate a EAN-13 Code with the numbers it works fine. The generator also checks if the code is valid and otherwise throws an error that the check digit is wrong.

<img width="287" alt="Screenshot 2019-12-13 at 09 41 55" src="https://user-images.githubusercontent.com/839848/70786477-09c94100-1d8d-11ea-890e-bbd5f28275e1.png">

**Comment by cristianoccazinsp** [comment]
> When I generate a EAN-13 Code with the numbers it works fine. The generator also checks if the code is valid and otherwise throws an error that the check digit is wrong.
> 
> <img alt="Screenshot 2019-12-13 at 09 41 55" width="287" src="https://user-images.githubusercontent.com/839848/70786477-09c94100-1d8d-11ea-890e-bbd5f28275e1.png">

That code works fine for me on both platforms. The issue is the same code without the numbers?

**Comment by Pczek** [comment]
The generated code without the numbers works fine for me as well. I can't make out why the photo of the original code can't be read by the library used by RNC. Can't see any distinct issue with the photo i've posted in the opening of this issue.

**Comment by Pczek** [comment]
I've made this comparison to check if the pattern's differ. However, they are exactly the same. See below. Nevertheless, there are some parts which are not perfectly printed or photographed. Not sure what's causing the read to fail though, would be bad if the recognition fails due to such minor disturbances.

<img width="584" alt="Screenshot 2019-12-20 at 10 04 49" src="https://user-images.githubusercontent.com/839848/71243354-79e94100-2310-11ea-9c2c-4c482990de9c.png">

<img width="584" alt="Screenshot 2019-12-20 at 10 04 49" src="https://user-images.githubusercontent.com/839848/71243401-92f1f200-2310-11ea-8f50-5c0a9a50f92d.png">

**Comment by Pczek** [comment]
Using `3.15.0` as of now. I was able to read the code a few times however it was still a hassle, but better than before. Don't know why. :shrug:

**Comment by cristianoccazinsp** [comment]
Is the issue something you can consistently make it happen? Maybe it was just that one code? Or the camera you're using is not capturing properly (the one you use to take the photo of the QR, not to read it). I don't think the reading logic is even implemented by the library, that's just google/apple code.
