### ISSUE TITLE
A problem occurred evaluating project ':react-native-camera'.

### ISSUE THREAD

**Issue by Didosior** [react-native-community/react-native-camera#2644]
# Question
Hi,

`react-native-camera` I get an error when I try to run the package after installing it.

# Error
![Screenshot_2](https://user-images.githubusercontent.com/46280838/70860749-b3980180-1f36-11ea-96fa-f012e7c7808e.png)

# Versions
react-native-cli: 2.0.1
react-native: 0.61.5
Android 7
Node v12.13.0
react-native-camera 3.15.0

**Comment by OkancanCosar** [comment]
[releated](https://github.com/react-native-community/react-native-camera/issues/2641)
