### ISSUE TITLE
I can't customize the size of photos on android. Would you consider adding this feature, like ios

### ISSUE THREAD

**Issue by 17554265585** [react-native-community/react-native-camera#2648]
# Feature-Request

**Describe the Feature**

**Possible Implementations**

**Related Issues**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by cristianoccazinsp** [comment]
The `width` parameter works for both iOS and Android, doesn't it?

**Comment by 17554265585** [comment]
> 该`width`参数适用于iOS和Android，不是吗？

It's true that I can customize the width, but still have a specific ratio for the photo, such as 4:3
