### ISSUE TITLE
Image clicked is not showing in the gallery

### ISSUE THREAD

**Issue by rajeev15june** [react-native-community/react-native-camera#2652]
# Feature-Request

**Describe the Feature**
Please provide the option for the path for images like video and also the option to show in the gallery.

**Possible Implementations**

**Related Issues**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by fabriziobertoglio1987** [comment]
1) [`takePictureAsync`](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#takepictureasyncoptions-promise) has a `doNotSave` option. 

> doNotSave (boolean true or false). Use this with true if you do not want the picture to be saved as a file to cache. If no value is specified doNotSave:false is used. If you only need the base64 for the image, you can use this with base64:true and avoid having to save the file.

```javascript
async function takeImage() {
  const response = await takePictureAsync([options])
}
```

2) Use [react-native-fs](https://github.com/itinance/react-native-fs) to parse the base64 image and persist it to file system

3) Choose between the many image gallery libs
https://github.com/archriss/react-native-image-gallery
