### ISSUE TITLE
I'm curious about this file.

### ISSUE THREAD

**Issue by savetheearth2** [react-native-community/react-native-camera#2666]
# Question

**To Do First**
- [O] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [O] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [O] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

Hello! I am not good at English.

My question is about the react-native-camera file.
I followed the Installation section of the following link.
https://react-native-community.github.io/react-native-camera/docs/installation

I've read several related documents, but I'm not sure what they mean.
I would like to try the PinchGestureHandler function included in ZoomView.js.
![react native camera 질문](https://user-images.githubusercontent.com/36323955/71869314-fc696180-3154-11ea-8e8c-0a63b4122da6.PNG)

Can the examples included in "react-native-camera" be executed as an expo client?
I wonder how to implement it.
Should I run as an Android studio?

Thank you

+Perhaps it should be run as an Android studio.

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by fabriziobertoglio1987** [comment]
You should try to implement the functionality as [expo includes already `react-native-gesture-handler`](https://docs.expo.io/versions/latest/sdk/gesture-handler/), which is the library that provides the `PinchGestureHandler` and `State` Components.

For more information about [`PinchGestureHandler`](https://software-mansion.github.io/react-native-gesture-handler/docs/handler-pinch.html)

as you can see in the [expo `Camera` docs](https://docs.expo.io/versions/latest/sdk/camera/) the zoom props that you use to build this functionality is available

**Comment by savetheearth2** [comment]
> You should try to implement the functionality as [expo includes already `react-native-gesture-handler`](https://docs.expo.io/versions/latest/sdk/gesture-handler/), which is the library that provides the `PinchGestureHandler` and `State` Components.
> 
> For more information about [`PinchGestureHandler`](https://software-mansion.github.io/react-native-gesture-handler/docs/handler-pinch.html)
> 
> as you can see in the [expo `Camera` docs](https://docs.expo.io/versions/latest/sdk/camera/) the zoom props that you use to build this functionality is available

Thank you very much for your reply!
I'm curious about how to install and execute the "react-native-camera" file of "react-native-community."
https://react-native-community.github.io/react-native-camera/docs/installation.html
Which folder should I install this link in?

**Comment by fabriziobertoglio1987** [comment]
follow the instructions on the [expo docs](https://docs.expo.io/versions/latest/sdk/camera/). If you do not understand them search for an expo training

**Comment by savetheearth2** [comment]
> follow the instructions on the [expo docs](https://docs.expo.io/versions/latest/sdk/camera/). If you do not understand them search for an expo training

Thank you very much for your reply!
I first wonder if you are talking about the project on this link.
I want to run this project that includes ZoomView.js.
https://github.com/react-native-community/react-native-camera.git

**Comment by fabriziobertoglio1987** [comment]
you can test the project from the examples/advanced folder
clone the repo and `cd examples/advanced/advanced && yarn`

the app is using the ZoomView, but it is laggy and not worth it.
Just add that code in your Expo project, **read the docs**

search the issues on github **pinch to zoom**

**Comment by savetheearth2** [comment]
> you can test the project from the examples/advanced folder
> clone the repo and `cd examples/advanced/advanced && yarn`
> 
> the app is using the ZoomView, but it is not native animation.
> Just add that code in your Expo project, **read the docs**
> 
> search the issues on github **pinch to zoom**

Thank you!
I'll have to try
