### ISSUE TITLE
Could not find method compile() for arguments [com.android.support:recyclerview-v7:25.3.1]

### ISSUE THREAD

**Issue by palashmandokhot** [react-native-community/react-native-camera#2672]
hi,

In my android studio build gradle is failed i dont know how so then i check the log and i saw this error Error:Could not find method compile() for arguments [com.android.support:recyclerview-v7:25.3.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Please install the Android Support Repository from the Android SDK Manager. Open Android SDK Manager

then i check it but android support respository is already installed version 47.0.0 i restart android studio but it shows same error how i solve this error from android studio please help me to solve this problem?

**Comment by fabriziobertoglio1987** [comment]
here is a good explanation of [the difference between `compile` and `implement`](https://stackoverflow.com/a/48388463/7295772). Please show us the code where you try to compile `com.android.support:recyclerview-v7:25.3.1`. 

You will find it in the `build.gradle` files or make a search for those keywords

additionally you can read [Could not find method compile() for arguments Gradle](https://stackoverflow.com/questions/23796404/could-not-find-method-compile-for-arguments-gradle)

**Comment by palashmandokhot** [comment]
hi,
thank you for you replying,yeah i send it but i am little hesitate that its not good or great for me if i shared my project code snippets because if anyone misuse it because its a public so can i share my code snippets in private?

**Comment by palashmandokhot** [comment]
hi,
check the link everything is setup.
