### ISSUE TITLE
ios GoogleVisionBarcodeDetection.BarcodeMode.AlTERNATE doesn´t work

### ISSUE THREAD

**Issue by grean** [react-native-community/react-native-camera#2678]
When i use this parameter with RNCamera/MLkit on ios like this : 
`googleVisionBarcodeMode={RNCamera.Constants.GoogleVisionBarcodeDetection.BarcodeMode.ALTERNATE}`

i've got this error : 
`typeError: undefined is not an object (evaluating '_reactNativeCamera.RNCamera.Constants.GoogleVisionBarcodeDectection.BarcodeMode.ALTERNATE')`
or this message if i comment the line 842 in RNCamera.js (//delete newProps.googleVisionBarcodeMode;) it was a test
`typeError: Cannot read property 'ALTERNATE'of undefined`

In Android it works

This error happens on a real device iPad 7gen
With RN 0.61.5
and React-native-camera 3.15.1

But, if a remove the prop, everything works well even if i scan vertically or horizontally in android or ios.. don´t understand why..

**Comment by manishkumar03** [comment]
I am facing the same issue in iOS app. Are there any plans to add the support for inverted barcodes in iOS?

**Comment by interstates21** [comment]
Same issue

**Comment by manishkumar03** [comment]
The support for this has been added to iOS now. If it still doesn't work, please let me know.

**Comment by renatobenks** [comment]
which version are you using @interstates21? try to update to the latest one, because as @manishkumar03 told you above, he introduced that support in https://github.com/react-native-community/react-native-camera/pull/2851, so if you use the latest, or since 3.27.1 version, it should work
