### ISSUE TITLE
[iOS] TextDetector does not recognize small and thin texts

### ISSUE THREAD

**Issue by Xrequillart** [react-native-community/react-native-camera#2683]
# Bug Report

**To Do First**
- [X] Did you try latest release?
- [X] Did you try master?
- [X] Did you look for existing matching issues?

**Platforms**
Only on iOS

**Versions**
- iOS: **13.3**
- react-native-camera: **3.15.1**
- react-native: **0.59.0**
- react: **16.8.3**
- react-navigation: **3.11.1**

**Description/Current Behaviour**

The problem is only on iOS
When the text is too small or thin, the text recognition no longer detects anything. 
(rf screenshot below)
We have to zoom for it to work.

When i test on android it works very well !

**Steps to Reproduce**

 - Open ViewCamera and scan a sheet with multiple font sizes
 - Look what you return this function (`onTextRecognized`)

**Additionals**
![Image from iOS](https://user-images.githubusercontent.com/10738609/72994990-6db53f80-3df8-11ea-98dc-b84367f5b197.jpg)
<img width="1073" alt="Capture d’écran 2020-01-23 à 15 41 09" src="https://user-images.githubusercontent.com/10738609/72994995-6ee66c80-3df8-11ea-9467-8ab7c53ee154.png">

**Comment by Xrequillart** [comment]
Ok it works ! If you change the scaling parameters (file: **RNCameraUtils.m**)

```js
float scale = scale = bufferHeight>bufferWidth ? 720 / bufferWidth : 720 / bufferHeight;;
    if (position == 1) {
        scale = bufferHeight>bufferWidth ? 400 / bufferWidth : 400 / bufferHeight;
    }
```
 --- >
```js
float scale = scale = bufferHeight>bufferWidth ? 1920 / bufferWidth : 1920 / bufferHeight;;
    if (position == 1) {
        scale = bufferHeight>bufferWidth ? 1080 / bufferWidth : 1080 / bufferHeight;
    }
```
But I think it's not the most opti. What do you think ?

**Comment by arousselotvi** [comment]
Is there a specific reason for scaling down the image used by MlKit that much? Because I think a lot of issues (#1706 for example) with text detection/barcode scanning/face detection on iOS might come from this.
