### ISSUE TITLE
FPS changes without changing the code.

### ISSUE THREAD

**Issue by cinjon** [react-native-community/react-native-camera#2700]
# Bug Report

I am using iOS and have set the recording options as:

`
{ 
quality: RNCamera.Constants.VideoQuality['1080p'], 
codec: RNCamera.Constants.VideoCodec.H264
}
`

The result is that *sometimes* the videos have FPS of 15.01 as reported by running `ffmpeg -i /path/to/video`. But this doesn't always happen. In particular, in my office it's always 29.97 (as expected and which is suitable). Then, in testing at a live location, it's instead 15.01.

Is there some place where settings are being applied based on certain conditions? I'm not very familiar with native development and so I am having trouble figuring out where in the native code this issue could be happening.

**Platforms**

**Versions**

- Android:
- iOS: iPad
- react-native-camera: 3.15.1
- react-native: 0.61.5
- react: 16.9.0
  

**Description/Current Behaviour**

**Expected Behaviour**

**Steps to Reproduce**

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by cristianoccazinsp** [comment]
I don't think the camera code has anything to do. This is most likely something from iOS or the camera itself, or the device doing too much work and not being able to keep up with the processing. 

Have you tried with a lower resolution, or another codec? Does the same happen with the native camera?

**Comment by cinjon** [comment]
Thanks for the response. I have not tried another resolution or codec in the wild. And it does not happen with the native camera. How would I be able to tell if the processing is too much?

**Comment by cristianoccazinsp** [comment]
You could try with an attached debugger and XCode. You will be able to see very nice RAM and CPU numbers when doing that.

**Comment by cinjon** [comment]
Is there a way to do that in the wild (i.e. w/o attached debugger) and dump to file somewhere?

**Comment by cristianoccazinsp** [comment]
Not that I'm aware of :)

**Comment by cinjon** [comment]
Unclear what was happening here, but if I change it to HEVC, then it doesn't happen.

**Comment by cristianoccazinsp** [comment]
What device were you testing with? That definitely sounds like the phone is unable to keep up recording at such high quality. HEVC is more efficient (and apple's default), so it would make sense.

**Comment by cinjon** [comment]
I have been testing with an iPad 6th Gen (10.2 in) 13.3.1.
