### ISSUE TITLE
Trouble recording a video in react native

### ISSUE THREAD

**Issue by izzykreie** [react-native-community/react-native-camera#2712]
Question

**To Do First**
- [ X] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [ X] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [ X] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
I'm trying to get my React Native camera to record a video, but am receiving this error message:

Reference Error: can't find variable stop recording.

I am new to react native, so i have a feeling it has something to do with a misunderstood concept. Here is my code:

I included the references/permissions for completeness but you could skip down to the Record function since that is where my confusion lies.

`class DeviceCamera extends PureComponent {

  render() {
    return (
      <View style={styles.container}>
        <RNCamera
          ref={ref => {
            this.camera = ref;
          }}
          style={styles.preview}
          type={RNCamera.Constants.Type.back}
          flashMode={RNCamera.Constants.FlashMode.on}
          androidCameraPermissionOptions={{
            title: 'Permission to use camera',
            message: 'We need your permission to use your camera',
            buttonPositive: 'Ok',
            buttonNegative: 'Cancel',
          }}
          androidRecordAudioPermissionOptions={{
            title: 'Permission to use audio recording',
            message: 'We need your permission to use your audio',
            buttonPositive: 'Ok',
            buttonNegative: 'Cancel',
          }}
          onGoogleVisionBarcodesDetected={({barcodes}) => {
            console.log(barcodes);
          }}
        />
        <View style={{flex: 0, flexDirection: 'row', justifyContent: 'center'}}>
          <TouchableOpacity
            onPress={this.Record.bind(this)} //changed from onPress = {this.takePicture.bind(this)}
            style={styles.capture}>
            <Text style={{fontSize: 14}}> SNAP </Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  Record = async () => {
    if (this.camera) {
      const options = {maxDuration: 5};
      const data = await this.camera.recordAsync(options);
      console.log(data.uri);
    }
      stopRecording();
  }; 
`

Should I somehow make the button be able to call the stopRecording function and the startRecording function? I'm definitely misunderstanding a concept here

**Comment by cristianoccazinsp** [comment]
Looks like a javascript / programming error to me. You need to call `this.camera.stopRecording();`
