### ISSUE TITLE
What is the mapping between integer pictureOrientation value and "portrait", "landscape", etc?

### ISSUE THREAD

**Issue by nekapoor** [react-native-community/react-native-camera#2713]
What is the mapping between integer orientation value and "protrait", "landscape", etc?

For example, what does "1" represent? Is "1" portrait"? What about "2" and "3" and "4"? 

Are these the same for deviceOrientation?

I'm looking at the exif data passed back from the takePicture method and seeing the integer values for deviceOrientation and pictureOrientation. 

Thanks so much

**Comment by apalmer0** [comment]
> For example, what does "1" represent? Is "1" portrait"? What about "2" and "3" and "4"?

Basing this on nothing more than logging the value after turning the phone and taking a picture, and not from any insight into the code:

1 - Portrait
2 - Portrait upside down
3 - Landscape left
4 - Landsape right
