### ISSUE TITLE
Convert Fatal Exception: java.lang.RuntimeException: No camera available. to status

### ISSUE THREAD

**Issue by SvetlinStaevNewsUK** [react-native-community/react-native-camera#2715]
# Feature-Request

**Describe the Feature**
We are using the 3.13 of the package and we are sporadically getting the following error:

`Fatal Exception: java.lang.RuntimeException: No camera available.`

This creates a crash on our app which we observe in Firebase Crashlytics. It would be nice if we can handle this within our JavaScript implementation.

**Possible Implementations**
Is it possible to catch and convert this exception to a new status `CAMERA_NOT_AVAILABLE` or something similar which will allows us to show a message to the user that we have a problem with accessing their camera (if indeed available) or that they do not have a camera on their phone (which might be a rare case).

**Related Issues**
https://github.com/react-native-community/react-native-camera/issues/1350

**Comment by cristianoccazinsp** [comment]
I believe this was somehow addressed already : https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/google/android/cameraview/Camera1.java#L933

https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/com/google/android/cameraview/Camera1.java#L968

Can you try upgrading to the latest version?
