### ISSUE TITLE
recordAsync() setup time issue

### ISSUE THREAD

**Issue by LautaroMir** [react-native-community/react-native-camera#2722]
Hi!

The component I'm trying to build displays a "Ready" button. 

![WhatsApp Image 2020-03-03 at 12 14 46 (1)](https://user-images.githubusercontent.com/61150712/75790091-724f0b00-5d49-11ea-9e67-aa5838d0f2c1.jpeg)

When you press on this button a "3 2 1" countdown will appear on screen.

![WhatsApp Image 2020-03-03 at 12 14 46 (2)](https://user-images.githubusercontent.com/61150712/75790158-885ccb80-5d49-11ea-961d-700024486155.jpeg)

When that count ends it starts recording and it starts a countdown with the duration of the resulting video.

![WhatsApp Image 2020-03-03 at 12 14 46 (3)](https://user-images.githubusercontent.com/61150712/75790252-ab877b00-5d49-11ea-9321-5b0ffd9c1044.jpeg)

The problem I'm facing is that the recordAsync() method takes a few milliseconds to start recording. The countdown timer starts first and the user thinks they're already recording something when they are not. I've solved this issue using the onRecordingStart callback. However, this results in the added time between the recordAsync() call and the onRecordStart call. I need to INSTANTLY transition from the "3 2 1" countdown to start recording and the "duration" countdown.

Can someone help me achieve this?

**Comment by cristianoccazinsp** [comment]
I'm not sure why the `onRecordingStart` isn't enough? Just hold on clearing the timer until that event fires. You may even fire it a few ms before your counter reaches 0 to compensate. Sadly, the camera setup to record a video takes some time and the delay is required to avoid black screens or flickers.

The only way around it is to have the camera already set to a recording preset/quality. I believe doing so reduces the recording delay a bit.
