### ISSUE TITLE
Take photo while recording

### ISSUE THREAD

**Issue by theothersideofgod** [react-native-community/react-native-camera#2726]
# Bug Report

**To Do First**

- [ ] Did you try latest release?
- [ ] Did you try master?
- [ ] Did you look for existing matching issues?

**Platforms**

Take photo while recording on android, will get error "camera is already capturing"

work ok on ios platform

**Versions**

- Android:
- iOS:
- react-native-camera:
- react-native:
- react:
  

**Description/Current Behaviour**

Take photo while recording on android, will get error "camera is already capturing"
**Expected Behaviour**

Take photo while recording on android, will get error "camera is already capturing"
**Steps to Reproduce**

call recordAsync --> call takePicture

**Additionals**

> Love react-native-camera? Please consider supporting our collective: 👉 https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by cristianoccazinsp** [comment]
Have you tried with `useCamera2Api` ?  I believe Camera1 has a restriction and hence the error you're getting. However, I haven't tried what happens if the restriction is lifted.
