### ISSUE TITLE
components in notAuthorizedView not clickable

### ISSUE THREAD

**Issue by JijoBose** [react-native-community/react-native-camera#2729]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Button Not clickable for component added inside notAuthorizedView**

I have added a UI with Button inside of the notAuthorizedView for the user to enable the permission if denied. 
Looks like none of the button or elements are clickable within the notAuthorizedView
Let me know if there is a workaround for this

#### Update:
- The issue exists for android only

Example code below:
```
<RNCamera
     ref={ref => {
        this.camera = ref;
     }}
     style={styles.preview}
     notAuthorizedView={<CustomPermissionView />}
/>
```

**Comment by douglasjunior** [comment]
Same here, on Android I was able to fix by setting `pointerEvents="auto"` to the `View` inside `notAuthorizedView`.

But on iOS, don't works.
