### ISSUE TITLE
not working in iPhone 4s 

### ISSUE THREAD

**Issue by alenave** [react-native-community/react-native-camera#273]
### Steps to reproduce
1. install in iPhone 4s
### Expected behaviour

two button(Flip, Take) should be visible
### Actual behaviour

black screen keep coming no button is visible.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
