### ISSUE TITLE
improve basic example

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [react-native-community/react-native-camera#2736]
# Feature-Request

**Describe the Feature**

**I would like to assign this task to myself** and upgrade the Basic Example to `reactnative@0.61.5` for the following reasons:

1) The basic demo example is the main tool used to develop and test features for the react-native-camera library
2) The basic demo example is also used in Continuos Integration to run test on the device
3) Make the demo easier to install

[1]: https://github.com/react-native-community/react-native-camera/pull/2735
[2]: https://stackoverflow.com/questions/58051510/xcode-11-0-build-get-error-unknown-argument-type-attribute-in-method-r/58061998#58061998
[3]: https://github.com/react-native-community/react-native-camera/blob/master/docs/installation.md#ios---other-required-steps
[4]: https://github.com/react-native-community/react-native-camera/issues/2736#issuecomment-598802850

**Possible Implementations**

1) Fix RunTime [error][4] when recording
1) Upgrade to react native 0.61.5 (solve [bug][2])
2) Add [permissions][3]
3) Update dependencies
4) Review the `metro.config.js` and `rn-cli.config.js` configurations

**Comment by fabriziobertoglio1987** [comment]
Experienced on the master branch.
<img src="https://user-images.githubusercontent.com/24992535/76639450-700d5d80-654e-11ea-8827-445e32c7ace2.png" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="300"  />

**Comment by MateusAndrade** [comment]
> Experienced on the master branch and while working on pull [2724](https://github.com/react-native-community/react-native-camera/pull/2724)
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/24992535/76639450-700d5d80-654e-11ea-8827-445e32c7ace2.png">

Probably because of something between 3.9.0...master. Did you got any progress on that?

**Comment by fabriziobertoglio1987** [comment]
I was working on upgrading the example app to rn0.61.5 but I'm postponing it. 

https://facebook.github.io/metro/docs/configuration/
https://callstack.com/blog/adding-an-example-app-to-your-react-native-library/
