### ISSUE TITLE
How to rename or save image by custom name ?

### ISSUE THREAD

**Issue by TheRakeshPurohit** [react-native-community/react-native-camera#2741]
Love this repo.

Successfully integrated in my project.
Image is captured, saved and visible in gallery.

I am facing problem to save the image by my custom name.

Is it possible ?

I digged the ReadMe, Doc, API and all and found nothing.

**Comment by cristianoccazinsp** [comment]
Image is by default (and I believe it cannot be changed) saved in the app's cache folder. If you want to rename it, you probably want to use `rn-fetch-blob` file system module to move it to an appropriate location and rename it at the same time.
