### ISSUE TITLE
thoughts on splitting recording behavior / preview?

### ISSUE THREAD

**Issue by wolverineks** [react-native-community/react-native-camera#2742]
# Question

**To Do First**
- [X] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [X] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [X] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

any thoughts / is it possible to split the recording capabilities from the preview?
im thinking something like...

```typescript
const cameraSettings = { ... }
const Foo = () => {
  const [showPreview, setShowPreview] = React.useState(true)
  const { status, record, pause, stop } = useCamera(cameraSettings)

  return <View>
    <TouchableOpacity onPress={() => setShowpreview(showPreview => !showPreview)}>
      Toggle Preview
    </TouchableOpacity>
    {status === Camera.Status.isLoading && <ActivityIndicator />}
    {status !== Camera.Status.isRecording && <TouchableOpacity onPress={record}>Record</TouchableOpacity>}
    {status === Camera.Status.isRecording && <TouchableOpacity onPress={stop}>Stop</TouchableOpacity>}
    {status === Camera.Status.isRecording && <TouchableOpacity onPress={pause}>Pause</TouchableOpacity>}
    {status !== Camera.Status.isLoading && showPreview && <Camera.Preview style={styles.preview} />}
  </View>
}
```

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
I would love `useCamera`, can you work on some pull requests to bring this new feature, without breaking the old behavior?

**Comment by sibelius** [comment]
on hooks we have this 2 pull requests

https://github.com/react-native-community/react-native-camera/pull/2649
https://github.com/react-native-community/react-native-camera/pull/2646

not sure if this work can help you

**Comment by wolverineks** [comment]
automated tests would really help a potentially substantial change like this
how are you verifying things now? manual q/a?

**Comment by sibelius** [comment]
Manual QA for now

We could have native testing library and also detox setup

Do you wanna work on this first?

**Comment by wolverineks** [comment]
it wouldnt hurt to start a separate discussion about setting up manual/automated/semi-automated testing

**Comment by cristianoccazinsp** [comment]
As far as I know Android requires the preview layer to be running in order to take photos/videos.  Wouldn't it be a bit complicated to handle both? Looks like a good idea though!

**Comment by wolverineks** [comment]
> As far as I know Android requires the preview layer to be running in order to take photos/videos. Wouldn't it be a bit complicated to handle both? Looks like a good idea though!

thats what im seeing as well, there are some posts about sending the video to a different type of android view, but that looks like it would be a change to react-native

the best i could figure is something like:
```typescript
 <RNCamera style={{ position: "absolute", opacity: 0, height: 100, width: 100 }} />
```
that could be turned into a prop like:
```typescript
 <RNCamera hidden />
```
or something like that

and if you really wanted something like:
```typescript
const { Camera, camera } = useCamera(...CAMERA_PROPS)

const takePicture = async () => {
  const uri = await camera.takePictureAsync()
  console.log({ uri })
}

return <View>
  {Camera}
</View>
```

but anyway you slice it, there has to be a component mounted in there somewhere
maybe if react-native had portals?

**Comment by cristianoccazinsp** [comment]
What were you trying to achieve anyways? Hidden recording? You can always hide the camera behind some view just like Facebook did a while ago (can't recall the bug, but it was hilliarious). However, I don't think that's really legal :D

**Comment by wolverineks** [comment]
> What were you trying to achieve anyways? Hidden recording? You can always hide the camera behind some view just like Facebook did a while ago (can't recall the bug, but it was hilliarious). However, I don't think that's really legal :D

pretty much this, but dont worry, theres a disclaimer

**Comment by fabriziobertoglio1987** [comment]
https://github.com/react-native-community/react-native-camera/issues/2178#issuecomment-579678651
