### ISSUE TITLE
Get video duration after end record

### ISSUE THREAD

**Issue by cavator** [react-native-community/react-native-camera#2745]
how can i get the video duration after record it?

**Comment by cristianoccazinsp** [comment]
Can't you just count the time between `onRecordingStart` and `onRecordingEnd` events? It will probably be off by a few miliseconds, but should be good enough for most use cases.

**Comment by Hitesh2297** [comment]
you can use this lib
https://www.npmjs.com/package/react-native-beautiful-video-recorder
