### ISSUE TITLE
How to test with @testing-library/react-native?

### ISSUE THREAD

**Issue by prescindivel** [react-native-community/react-native-camera#2753]
How to mock test with @testing-library/react-native?

**Comment by MateusAndrade** [comment]
You tried mocking mocking the implementation on RNCamera? I was facing a similar issue on a project, and i was able to do something like:

```js
jest.mock("path-to-library", () => mockedImpl)
```

You can try looking at: https://www.reactnative.guide/7-testing/7.4-mocking-rn-modules.html.

**Comment by prescindivel** [comment]
yes, but i can't capture the takePictureAsync event

**Comment by MateusAndrade** [comment]
> yes, but i can't capture the takePictureAsync event

You can provide any sample code? I have been struggling to test apps written in react-native using  some libraries. I would be happy to help you with that. 😄

**Comment by danielholmes** [comment]
I've gotten the below working (with `expo-camera`). it works for a single test of recording a video - I don't know enough to say if it will work for multiple tests in a suite that use video recording.

`
let currentRecording: {
      resolve: (result: { uri: string }) => void;
      reject: (e: Error) => void;
    };
    jest.spyOn(Camera.prototype, 'recordAsync').mockImplementation(() => {
      return new Promise((resolve, reject) => {
        currentRecording = { resolve, reject };
      });
    });
    jest.spyOn(Camera.prototype, 'stopRecording').mockImplementation(() => {
      if (!currentRecording) {
        throw new Error('No recording');
      }
      currentRecording.resolve({ uri: '/local/video.mp4' });
    });
`
