### ISSUE TITLE
scanned result of datamatrix code differs from other barcode scanner libraries.

### ISSUE THREAD

**Issue by jonzl** [react-native-community/react-native-camera#2761]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Funded-%2300A156.svg" />](https://issuehunt.io/r/react-native-community/react-native-camera/issues/2761)

# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
I would like to use react-native-camera in order to scan datamatrix codes like the following one  of the German postal service (Deutsche Post):
https://de.wikipedia.org/wiki/DV-Freimachung#/media/Datei:DV-Freimachung_Januar_2015.png

When I use the library react-native-camera with the _general_-implementation in my project, scan the code and log the result, then I receive the following output:

```
 type: DATA_MATRIX
 data: DEA*«
 rawdata: e756059c2d9432ae6d837419996dc819ef861be144e4716a9c338fa1a89864eb7934ab43e3352060f68ee73d
```

If I scan the same datamatrix code with the well-known Android app "Barcode Scanner" ( https://play.google.com/store/apps/details?id=com.google.zxing.client.android ), then I get the following result:

`DEA   *«   > ¿   1þ  c  ÈD¶ F80V79D V   Æ‡`

![photo6035063972056641913](https://user-images.githubusercontent.com/805568/77254678-d5ee9900-6c62-11ea-9865-a7cd3c6fb37c.jpg)

The first three characters of the result are the same, but the rest of the result differs.
The result of the Android App "Barcode Scanner" is correct (it needs to be encoded into a byte array  for further processing), so my question is why does the library only recognize some parts of the datamatrix code? Any ideas?

**Tags**
Datamatrix

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars0.githubusercontent.com/u/805568?v=4' alt='jonzl' width=24 height=24> jonzl](https://issuehunt.io/u/jonzl) ($10.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/react-native-community/react-native-camera/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by trixel** [comment]
I think this is the same issue https://issuehunt.io/r/react-native-community/react-native-camera/issues/2343
