### ISSUE TITLE
What happened to Aspect Fit?

### ISSUE THREAD

**Issue by aspectgfg** [react-native-community/react-native-camera#2764]
# Question
What happened to the Aspec Fit/aspect property on RNCamera? We're getting complaints because the recording view doesn't reflect what's actually being recorded. Would like Aspect Fit so the camera preview exactly matches the Video/Photo result.

**Tags**
UX, UI

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by cristianoccazinsp** [comment]
I believe you control the camera's preview dimensions entirely with styles? As long as you set the appropriate width/height, the preview should show exactly what's going to be captured. However, it might get tricky if your goal is to cover 100% of the screen (impossible with 4:3 aspect ratio, unlikely with 16:9).

Here's some code that I've been using to render the camera view considering the device's width, height, and camera's aspect ratio. The code tries to take as much as space as possible, while also centering it.

https://github.com/react-native-community/react-native-camera/blob/master/examples/advanced/advanced/src/screens/Camera.js#L571
