### ISSUE TITLE
Crash when pass codec and bitrate

### ISSUE THREAD

**Issue by sandeepsingh91** [react-native-community/react-native-camera#2773]
# Crash in iOS 10.3.4

This is my code for record Options.

 const options = {};
        const dim = Dimensions.get('window');

        if (Platform.OS === 'ios') {
            options['videoBitrate'] = 0.8 * 1000 * 1000
            options['quality'] = RNCamera.Constants.VideoQuality['4:3']

            const majorVersionIOS = parseInt(Platform.Version, 10)

            if (majorVersionIOS >= 11) {
                if (dim.width >= 800) {
                    options['codec'] = RNCamera.Constants.VideoCodec['HVEC']
                } else {
                    options['codec'] = RNCamera.Constants.VideoCodec['H264']
                }
            } else {
                options['codec'] = RNCamera.Constants.VideoCodec['H264']
            }

        } else {
            options['quality'] = RNCamera.Constants.VideoQuality["720p"]
            options['videoBitrate'] = 3 * 1000 * 1000
        }

It work fine in Android but when I run this in iOS app got crashed.  Here are the logs from Xcode

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureMovieFileOutput setOutputSettings:forConnection:] The only supported key is AVVideoCodecKey - the following keys are illegal: {(
    AVVideoCompressionPropertiesKey
)}'
*** First throw call stack:
(0x1c0f3b3d 0x1b37b067 0x22a1d3bd 0x2f2acd 0xb75467 0xb8166f 0xb78a39 0xb8376b 0xb83471 0x1b97687d 0x1b97645c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by cristianoccazinsp** [comment]
Can you try without `videoBitrate`? I don't understand why the error happens, but it seems like your device/OS version does not support setting the bitrate.

I would suggest a PR that changes the following with a try/catch and fallsback to only setting the codec.
https://github.com/react-native-community/react-native-camera/blob/master/ios/RN/RNCamera.m#L1147

**Comment by sandeepsingh91** [comment]
@cristianoccazinsp when I tried without video bitrate it works fine. But I've to record video using custom bitrate.

**Comment by renatobenks** [comment]
@sandeepsingh91 are you still facing it?

**Comment by fonov** [comment]
I also have this issue
