### ISSUE TITLE
Unable to scan GS1 barcodes in iOS

### ISSUE THREAD

**Issue by pan23** [react-native-community/react-native-camera#2779]
# Bug Report

Testing OS: 13.3
The Latest used  RNCamera version: 3.22.0

Unable to scan GS1 barcodes in iOS but working fine in Android with the same version.  I am not getting any errors as well. The camera keeps trying to scan the barcode for a long time but nothing happens.

**Comment by sibelius** [comment]
did it worked before?

**Comment by pan23** [comment]
No, for iOS it's not worked before as well

**Comment by sibelius** [comment]
it worked before for android?

can you share the barcode?

**Comment by pan23** [comment]
Yes, it's working fine on Android. Please check the attached image of the barcode. This image is scanning properly in android but not in iOS.
<img width="510" alt="Screenshot 2020-04-09 at 11 33 13 AM" src="https://user-images.githubusercontent.com/34887932/78862870-f20d7b00-7a55-11ea-8ac2-7a86502de608.png">

**Comment by pan23** [comment]
Hi Sibelius, Have you checked the attached sample barcode? We are unable to scan these types of the barcode in iOS. Can you please suggest any solution for this?

**Comment by dhawalsonawane** [comment]
@pan23 I am facing the same issue. Did you get any work around yet?
@sibelius could you provide any help on this?

**Comment by blackgibbon** [comment]
what is the status on this?

**Comment by sandy105** [comment]
@pan23 I am facing the same issue. Did you get any work around yet?
@sibelius could you provide any help on this?

**Comment by zjw199011** [comment]
Does anyone figure out how to fix this? or maybe a work around?

**Comment by ShahidNawazEteam** [comment]
Facing the same issue, working perfectly on Android but nothing happening on iOS. QR codes and some other barcode types are working fine but GS1 barcode types are not getting scanned.

Does anyone have a fix for this issue?

**Comment by pan23** [comment]
I didn't found any solution with this library. I switched to another library which supports GS1 barcode for iOS.

**Comment by ShahidNawazEteam** [comment]
@pan23 

Can please tell the name of the library the supports GS1 barcodes for IOS.

Thanks

**Comment by sandy105** [comment]
@pan23  Could u tell me the name of the library that supports GS1 barcodes for IOS？ I used  zxingObject for iOS， but still have a issue on iPhone 12 pro.

**Comment by pan23** [comment]
@sandy105 and @ShahidNawazEteam I used @yyyyu/react-native-barcode this library. Its working properly on iPhone 12 Pro with RN version 0.63.3. This library doesn't have any updates but still its working properly.

**Comment by eteamIH** [comment]
Hi @pan23

Thanks for sharing this, can you kindly share the `formats` configuration that worked for you to scan on iPhone 12 Pro? The template is mentioned below.

```javascript
state = {
    visible: true,
    scanEnable: true,
    scannerSize: 300,
    decoder: RNLBarCode.Decoder.Auto,
    formats: RNLBarCode.Type.Common.QR_CODE,
    torch: RNLBarCode.TorchMode.Off
  };
```
Thanks!

**Comment by eteamIH** [comment]
Also @pan23 , it would be great if you could kindly share your linking process for react-native-barcode library.

I'm also using RN 0.63 and it's not scanning GS1 in default settings. But when I say
```javascript
decoder: RNLBarCode.Decoder.ZBar
```

it gives me an error "Failed to invoke, this device doesn't support this decoder".

Any help in this regard will be highly appreciated.

Thank you!

**Comment by sandy105** [comment]
@eteamIH  Zbar does not support the GS1 format of barcode， you can check it out on http://zbar.sourceforge.net
