### ISSUE TITLE
React native camera doesn't return full file path

### ISSUE THREAD

**Issue by openwell** [react-native-community/react-native-camera#2784]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**
I just installed the package an am trying to access the picture and I get a directory without the image.
``` 
    "react-native": "0.61.5",
    "react-native-camera": "^3.22.0",

takePicture = async () => {
    if (this.camera) {
      const options = {quality: 0.5, base64: true};
      const data = await this.camera.takePictureAsync(options);
      console.log(data.uri);
    }
  };
```
Output
`file:///data/user/0/*******/cache/Camera`
The path is not complete

**Tags**

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
check latest release https://github.com/react-native-community/react-native-camera/releases/tag/v3.22.1
