### ISSUE TITLE
onBarCodeRead should also send raw photo bytes

### ISSUE THREAD

**Issue by ceefour** [react-native-community/react-native-camera#2786]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Funded-%2300A156.svg" />](https://issuehunt.io/r/react-native-community/react-native-camera/issues/2786)

# Feature-Request

**Describe the Feature**

Currently `onBarCodeRead` only gives metadata, but not the image (bytes/base64) itself.
Calling `takePictureAsync()` does not give the real photo that was detected.

**Possible Implementations**

1. Save the image(s) in a bounded queue, make an optional prop to set format, i.e. `detectedImageInEvent` = `false` (default) | `true` (will be encoded as base64). (I thought of adding `binary` option but seems like [base64 is a better idea](https://stackoverflow.com/a/1443240/122441))
   * `false` is default as it adds significant additional processing
2. If barcode is detected, provide the `image` to the callback handler.

**Related Issues**

#2763, #2018.

_Bonus points:_ Support also `onGoogleVisionBarcodesDetected`, but this turns out to be a different processing pipeline.

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars1.githubusercontent.com/u/24123?v=4' alt='ceefour' width=24 height=24> ceefour](https://issuehunt.io/u/ceefour) ($10.00)

### Submitted pull Requests
- [#2923 feat: onBarCodeRead should also send raw photo bytes, fixed #2786](https://issuehunt.io/r/react-native-community/react-native-camera/pull/2923)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/react-native-community/react-native-camera/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by ceefour** [comment]
I think I know how to fix this, I'll post a PR for this.

**Comment by ceefour** [comment]
Relevant symbols:

## Barcode Scanner

## Google Cloud Vision

* `org.reactnative.camera.tasks.BarcodeDetectorAsyncTask#serializeEventData`, which should prepare the `base64` and will call:
* `org.reactnative.camera.RNCameraView#onBarcodesDetected`, which will call:
* `org.reactnative.camera.RNCameraViewHelper#emitBarcodesDetectedEvent`, which will call:
* `org.reactnative.camera.events.BarcodesDetectedEvent#obtain`

**Comment by ceefour** [comment]
Currently working on this on https://github.com/ceefour/react-native-camera/tree/hendy

**Comment by cristianoccazinsp** [comment]
I like the idea.  What about the image's quality? Base64 seems like a lot of overhead for the bridge/json if the quality is high (similar to the one from takePictureAsync). Seems like you should pass in the same options as takePictureAsync.

**Comment by ceefour** [comment]
@cristianoccazinsp Work is already done for both both BarCode and ML Kit Barcodes in this branch:
https://github.com/ceefour/react-native-camera/tree/hendy

After tidying up the commit I'll make a PR here.

**Comment by musyilmaz** [comment]
I am currently trying to make your branch work though the event object in onBarcodeRead still no returning any base64, or am I doing something wrong? @ceefour

**Comment by ceefour** [comment]
@musyilmaz make sure to set `detectedImageInEvent=true`

Thanks for reminding, I should make the PR tonight or tomorrow.

It's really encouraging to see this functionality needed by other users. :)

**Comment by musyilmaz** [comment]
Actually this didnt work also. Checked your commit and it seems it only works in android? maybe after your pr, I might work on the ios section in where I was doing the tests. 

Also one another issue I encountered, when I used your branch as a package, it wasn't showing up any of the changes :)

I will wait for your pr to test it and maybe utilize. 

Currently, thanks to the async logic on takePicture and onBarcodeRead, when device reads barcode, a base64 picture from the camera can be taken like 1 second later.

**Comment by ceefour** [comment]
@musyilmaz you are correct I only implemented on Android since that's my requirement at that time. Also I don't have access to iOS device.

> Currently, thanks to the async logic on takePicture and onBarcodeRead, when device reads barcode, a base64 picture from the camera can be taken like 1 second later.

I did try this before, and some people may be happy with this. But in my requirement it did not work, as I want to crop the exact barcode, and if there's a delay even just 1 frame the crop will be off.

**Comment by manishkumar03** [comment]
I am soon going to create a PR for this for the iOS part. My plan is to return a `uri` of the image as part of the returned barcodes object itself i.e `barcode.uri`. It will be on by default as it adds almost no overhead.

**Comment by manishkumar03** [comment]
Implemented this on iOS in [this PR](https://github.com/react-native-community/react-native-camera/pull/2864).

**Comment by ceefour** [comment]
@musyilmaz please check #2923
