### ISSUE TITLE
Wrong cast methods used in the Windows implementation

### ISSUE THREAD

**Issue by qmatteoq** [react-native-community/react-native-camera#2788]
# Bug Report

**To Do First**

- [ x ] Did you try latest release?
- [ x ] Did you try master?
- [ x ] Did you look for existing matching issues?

**Platforms**

Windows

**Versions**

- Windows: Windows 10 2004 (19041.173)
- react-native-camera: 3.22.1
- react-native: 0.61.5
- react: 16.9.0
- react-native-windows: 0.61.4

**Description/Current Behaviour**

1) Add react-native-camera to a React Native project with Windows support
2) Follow the [docs](https://react-native-community.github.io/react-native-camera/docs/installation) to link the Windows C++ module to the application
3) Open Visual Studio and deploy the React Native application
4) The solution fails to compile due to a series of errors related to the wrong method user for casting, like:

```
>C:\Users\mpagani\Source\React\CameraSample\node_modules\react-native-camera\windows\ReactNativeCameraCPP\ReactCameraView.cpp(67,67): error C4996: 'winrt::Microsoft::ReactNative::JSValue::Double': Use TryGetDouble, AsDouble, or AsJSNumber
>C:\Users\mpagani\Source\React\CameraSample\node_modules\react-native-camera\windows\ReactNativeCameraCPP\ReactCameraView.cpp(70,67): error C4996: 'winrt::Microsoft::ReactNative::JSValue::Double': Use TryGetDouble, AsDouble, or AsJSNumber
>C:\Users\mpagani\Source\React\CameraSample\node_modules\react-native-camera\windows\ReactNativeCameraCPP\ReactCameraView.cpp(73,68): error C4996: 'winrt::Microsoft::ReactNative::JSValue::Double': Use TryGetDouble, AsDouble, or AsJSNumber
>C:\Users\mpagani\Source\React\CameraSample\node_modules\react-native-camera\windows\ReactNativeCameraCPP\ReactCameraView.cpp(76,50): error C4996: 'winrt::Microsoft::ReactNative::JSValue::Boolean': Use TryGetBoolean, AsBoolean, or AsJSBoolean
>C:\Users\mpagani\Source\React\CameraSample\node_modules\react-native-camera\windows\ReactNativeCameraCPP\ReactCameraView.cpp(79,64): error C4996: 'winrt::Microsoft::ReactNative::JSValue::Double': Use TryGetDouble, AsDouble, or AsJSNumber
>C:\Users\mpagani\Source\React\CameraSample\node_modules\react-native-camera\windows\ReactNativeCameraCPP\ReactCameraView.cpp(93,46): error C4996: 'winrt::Microsoft::ReactNative::JSValue::String': Use TryGetString, AsString, or AsJSString
```
**Expected Behaviour**

The solution compiles without errors and the app is deployed

**Steps to Reproduce**

1) Add react-native-camera to a React Native project with Windows support
2) Follow the [docs](https://react-native-community.github.io/react-native-camera/docs/installation) to link the Windows C++ module to the application
3) Open Visual Studio and deploy the React Native application

**Additionals**

You can restore the project to a working state by following the suggestion included in the error message and replacing every method with the variant prefixed by As. For example, AsDouble(), AsBoolean(), AsString(), etc.

**Comment by stmoy** [comment]
cc: @Kaiguo 

This looks like an upgrade breaking change in RN to 0.61. We need to update the module.
