### ISSUE TITLE
Is there a onBarCodeRead method supported in Android ?

### ISSUE THREAD

**Issue by blacksunset** [react-native-community/react-native-camera#279]
Hi, I am building a app with QR code reading function.  It seems the OnBarCodeRead function does not work in android, is there any solution  to solve this problem?

**Comment by xiaomilii** [comment]
i have the same qustion, Will you solve it?@blacksunset

**Comment by blacksunset** [comment]
@xiaomilii i solved it by changing a component.  @see react-native-barcode-scanner-universal

**Comment by jrm2k6** [comment]
Same question here, would be nice to be able to use only one library for both platforms

**Comment by ThaJay** [comment]
+1
react-native-barcodescanner is not doing it for me at the moment

**Comment by ThaJay** [comment]
well react-native-barcodescanner kind of works but looks like it isn't maintained at the moment. So how should we go about implementing ZXing here? I'm willing to help.

**Comment by jrm2k6** [comment]
@ThaJay I used the other package mentioned and it seems to be working fine. I don't know how we could go to merge those two projects together basically.

**Comment by M1chaelTran** [comment]
there is QR code support now with the latest version 0.4.0 with PR https://github.com/lwansbrough/react-native-camera/pull/413.

consider closing this issue

**Comment by Disjes** [comment]
is BarCode supported on Android or just QR Code?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
