### ISSUE TITLE
How to save video only the last N seconds

### ISSUE THREAD

**Issue by lkspc** [react-native-community/react-native-camera#2800]
# Question

**To Do First**
- [x] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [x] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [x] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Ask your Question**

How to save video only the last N seconds? I don't need the full video. And I think clipping has bad performance.
**Tags**

`video clip`
> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this issue to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

**Comment by sibelius** [comment]
I think you need to process the video afterward using another package
