### ISSUE TITLE
Release APK Error on React-Native 0.62.0

### ISSUE THREAD

**Issue by DanishWajid** [react-native-community/react-native-camera#2804]
# Question
I have upgraded the app to react-native 0.62.0 from 0.59.10. In start app crashes, but I have added some code in android/build.gradle to resolve dependencies. Now the app works fine in development mode but gives error when I try to make APK.

I have added the following code in android/build.gradle (in all projects section)

**android/build.gradle **
![Capture](https://user-images.githubusercontent.com/34692122/80289254-eb218080-8756-11ea-95bc-88898d5a41fc.PNG)

**Build Error:**
![errror](https://user-images.githubusercontent.com/34692122/80289240-da710a80-8756-11ea-881c-b7553decf7f8.PNG)

**Comment by oussamajilal** [comment]
Having the same error with version `3.31.1` and react-native `0.59.8` and not using ML Kit (`missingDimensionStrategy 'react-native-camera', 'general'`)

Any idea how to fix this ?

**Comment by chpriyanka433** [comment]
camera is not working in android 11 version and react-native version is 0.61 and build Tool Version is 30.0.2, min SDK version  30,

can you give me any idea how to fix it
