### ISSUE TITLE
APP crashes with error “Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc in tid 11866 (AsyncTask #3), pid 11509 (***)”

### ISSUE THREAD

**Issue by linlien** [react-native-community/react-native-camera#2809]
`
   <View style={styles.Scan_wrap}>
        <RNCamera
          ref={(ref) => (this.camera = ref)}
          style={styles.preview}
          type={RNCamera.Constants.Type.back}
          flashMode={RNCamera.Constants.FlashMode.off}
          androidCameraPermissionOptions={{
            title: 'Permission to use camera',
            message: 'We need your permission to use your camera',
            buttonPositive: 'Ok',
            buttonNegative: 'Cancel',
          }}
          androidRecordAudioPermissionOptions={{
            title: 'Permission to use audio recording',
            message: 'We need your permission to use your audio',
            buttonPositive: 'Ok',
            buttonNegative: 'Cancel',
          }}
          onGoogleVisionBarcodesDetected={({barcodes}) => {
            console.log(barcodes);
          }}>
          {({camera, status, recordAudioPermissionStatus}) => {
            return (
              <View
                style={{
                  flex: 0,
                  flexDirection: 'row',
                  justifyContent: 'center',
                }}>
                <TouchableOpacity
                  style={styles.capture}
                  onPress={() => this.takePicture(camera)}>
                  <Text> SNAP </Text>
                </TouchableOpacity>
              </View>
            );
          }}
        </RNCamera>
      </View>
`

**Comment by nishit-g** [comment]
Facing the same issue here, any fixes ?
