### ISSUE TITLE
Initialize video before recording 

### ISSUE THREAD

**Issue by nica0012** [react-native-community/react-native-camera#2812]
When recording on IOS, after pressing record the camera zooms in (This is normal for video).

Is it possible to have the camera ready for video so that the camera does not zoom in anymore when they start recording?

I don't see anything in the docs related to this, cheers!

**Comment by jkerb8** [comment]
This can be resolved by setting the `pictureSize` prop (ios only) to be equivalent to the quality you're recording the video in.

**Comment by nica0012** [comment]
@jkerb8 Right on, thank you it works!
