### ISSUE TITLE
Problems with Data Matrix codes

### ISSUE THREAD

**Issue by rutvikrockers** [react-native-community/react-native-camera#2814]
Data matrix multiple scans not working at one-time scanning? Can you please give me any solution for this? it needed urgent

**Comment by fabriziobertoglio1987** [comment]
could you elaborate?

**Comment by rutvikrockers** [comment]
When I scan data matrix qr code with using react-native-camera library, it is not scanning multiple qr code. Below is the data matrix qr code which is not scanning by using library. 
![IMG-20200430-WA0019](https://user-images.githubusercontent.com/31954734/80869334-81a4f300-8cbd-11ea-8731-6eb4d373a8d6.jpg)

**Comment by rutvikrockers** [comment]
hello,
do you get my point? is there any help in it?

**Comment by manishkumar03** [comment]
Are you trying to scan multiple codes at the same time (in the same frame)?
