### ISSUE TITLE
FPS supported but not documented?

### ISSUE THREAD

**Issue by PanMan** [react-native-community/react-native-camera#2816]
# Question
It seems to me FPS is supported as a RecordingOptions: 
https://github.com/react-native-community/react-native-camera/blob/master/src/RNCamera.js#L230
but not documented? Couldn't find anything in the docs about it. 
Is there a reason for this, or should it "just work"? Then I'll do a pull req for the docs. Thanks!

**To Do First**
- [X] Take a look in the [README](https://github.com/react-native-community/react-native-camera/blob/master/README.md)
- [X] Take a look in the [docs](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md)
- [X] Take a look in the [QA](https://github.com/react-native-community/react-native-camera/blob/master/docs/QA.md)

**Tags**

camera, fps, ios

**Comment by fabriziobertoglio1987** [comment]
Work in Progress

**Comment by AkashPushkar** [comment]
Is this feature (fps) supported . If yes, I could not find it in the documentation ([https://react-native-camera.github.io/react-native-camera/docs/rncamera#recordasync-options-promise]). Is there a way to capture video at specified FPS (low value like 5fps).

**Comment by ainnotate** [comment]
Hi, I'm looking for a custom FPS as well, 

Could someone update on the status, please?

Thank you.
