### ISSUE TITLE
Barcode scanning sometimes return results even when no barcode is present in the vicinity.

### ISSUE THREAD

**Issue by AnurajDev** [react-native-community/react-native-camera#2828]
I am using RNCamera for barcode scanning. Although scanning works good, sometimes the camera returns random tag values even when there are no barcode is present in the vicinity. 

Tried both onBarCodeRead and onGoogleVisionBarcodesDetected for capturing the result, but the problem persisted. 

Any leads towards a solution is much appreciated. 

> react: 16.9.0
> react-native: 0.61.5
> react-native-camera: 3.19.1

**Comment by manishkumar03** [comment]
Did you try specifying the exact type of barcode  to be scanned using `googleVisionBarcodeType `? If you know in advance what types of barcodes you are looking for, this setting will avoid spurious results.

**Comment by tusharmutreja200** [comment]
+1, I am also facing this issue. I think **googleVisionBarcodeType** prop must have the functionality to pass an array of barcode types

**Comment by Udbhav12** [comment]
I am facing the exact same issue

**Comment by vikas-singh-fareye** [comment]
facing same issue

**Comment by sarinashish** [comment]
I am also facing this issue

**Comment by dragma** [comment]
This bug is really there and quite annoying....

**Comment by mrigo** [comment]
Hey, this bug is still in production! Anybody with a solution?

**Comment by leoamato10** [comment]
same problem! Only on Android.
