### ISSUE TITLE
Don't use RCT class prefix.

### ISSUE THREAD

**Issue by nicklockwood** [react-native-community/react-native-camera#283]
This looks like a great module, but please don't use the RCT prefix for your classes - that's reserved for first party React Native components so that we can avoid conflicts. If we ever add a camera module to React Native core, we'd probably call it RCTCamera too, and then that would break your module.

A better prefix would be something specific to your project, e.g. RNC (React Native Camera), or your name, e.g. LWAN,  which minimises the chance that someone else will accidentally use the same prefix.

(ps, That doesn't apply to the JS wrapper for your module, which we suggest you leave un-prefixed.)
(pps, And yes, it's kinda dumb that Objective-C uses a global namespace, but that's the way it is)

**Comment by rt2zz** [comment]
👍 This would make a great PR if anyone is up for it. I would vote for `RN` as a prefix since that seems to be common in the community, although the risk of collision is still non-negligible.

**Comment by nicklockwood** [comment]
@rt2zz Being common is the exact opposite of the purpose of the prefix :-)

**Comment by sibelius** [comment]
I'll try to work on this one

**Comment by sibelius** [comment]
fixed on master with new implementation

RNCamera https://github.com/react-native-community/react-native-camera#experimental
