### ISSUE TITLE
attempt to invoke virtual method 'double java.lang.double.doublevalue()' on a null object reference

### ISSUE THREAD

**Issue by anchaljain123** [react-native-community/react-native-camera#2835]
#React native camera opening issue in Android

**Ask your Question**
Getting this error when asking for record permission in device, when device has the permission,which is set after 3 to 4 times acceptance then error is gone.

**package.json**
   "react": "^16.13.0",
    "react-native": "0.61.5",
    "react-native-animatable": "^1.3.3",
    "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera.git",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^2.3.1",
    "react-native-reanimated": "^1.6.0"

#2835 
#23126

<img width="515" alt="Screenshot 2020-05-14 at 10 01 47 AM" src="https://user-images.githubusercontent.com/25630051/81896060-5c738700-95d1-11ea-8cea-708c5eacb629.png">

**Comment by jenskuhrjorgensen** [comment]
I get this error when tapping the camera view with newest version:
`"react-native-camera": "3.25.0"`
and
```
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
```
Tested on physical Android device: OnePlus 5T.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/react-native-community/react-native-camera/issues/2596

https://github.com/react-native-community/react-native-camera/issues/2047

https://github.com/react-native-community/react-native-camera/issues/1585

https://github.com/react-native-community/react-native-camera/issues/1708

I think ReadableNativeArray is used to pass data through the RN Bridge

**Comment by anchaljain123** [comment]
@fabriziobertoglio1987 : What can be done to resolve the issue, should i degrade or is it breaking because permissions are setting late

**Comment by fabriziobertoglio1987** [comment]
our codebase does not use that type ReadableNativeArray

https://github.com/react-native-community/react-native-camera/search?q=ReadableNativeArray&type=Code

you need to share your project implementation, please recreate this bug in a simple snippet

**Comment by fabriziobertoglio1987** [comment]
https://github.com/react-native-community/react-native-camera/issues/1585#issuecomment-433194726

**Comment by khattab93** [comment]
Got same error

**Comment by wxb1989** [comment]
Got same error

**Comment by khattab93** [comment]
@wxb1989 Check that your reference isn't null before calling its methods. For example: 
```
if (this.camera) {
      this.camera
        .recordAsync()
        .then()
        .catch()
}
```

**Comment by wxb1989** [comment]
@khattab93  

I want to add a monitoring method, as follows: How should I write?
 componentDidMount() {
    if (this.rnCamera) {
      this.rnCamera
        .recordAsync()
        .then()
        .catch()
    }
    
    AppState.addEventListener('change', this.handleAppStateChange);
  }

**Comment by khattab93** [comment]
@wxb1989 You need to add this event after recording a video or when?

**Comment by wxb1989** [comment]
@khattab93 
 I used this.rnCamera in this method. As you said, if you don’t judge, you will get the same error as you.  
  componentDidMount() {
    AppState.addEventListener('change', this.handleAppStateChange);
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this.handleAppStateChange);
    this.rnCamera && this.rnCamera.pausePreview();
  }

  handleAppStateChange = (currentAppState) => {
    if (this.rnCamera) {
      if (currentAppState !== 'active') {
        this.rnCamera && this.rnCamera.pausePreview();
      } else {
        this.rnCamera && this.rnCamera.resumePreview();
      }
    }
  };
 <RNCamera
        ref={this.cameraRef}
        captureAudio={false}
        onBarCodeRead={this.onScanResult} />

I think it may be related to the life cycle. If I write the life cycle after the render method can I get the ref

**Comment by wxb1989** [comment]
@khattab93  thank you!!!!!
