### ISSUE TITLE
Why only dispatch events every 500ms in iOS ? 

### ISSUE THREAD

**Issue by lumixraku** [react-native-community/react-native-camera#2844]
# Question

**Ask your Question**
Why only dispatch events every 500ms in iOS ? 

I thought iOS would have much better experience than Android. But actually it has a freq limit. 

I changed this time gap to 50ms, And face detect seems works fine.

I just do not understand why iOS would have this limit.

**Comment by sibelius** [comment]
where is the limit set?
I can we can make this lower or configurable

**Comment by lumixraku** [comment]
> where is the limit set?
> I can we can make this lower or configurable

In RNCamera.m       Line 2236

**Comment by tomsotte** [comment]
It's one of the thing I wanted to tackle on this PR #2838, because it's very useful for real-time face contours detection.

**Comment by sibelius** [comment]
I think we can change to a new better default
