### ISSUE TITLE
Plan for implement CameraView using androidx.camera.view.CameraView?

### ISSUE THREAD

**Issue by jarvisluong** [react-native-community/react-native-camera#2847]
It seems that the current Camera native view is from com.google.android.cameraview, which is quite old and deprecated, instead this new package is more up-to-date and integrate better with new Android versions (this is just my thought):

https://developer.android.com/reference/androidx/camera/view/CameraView#startRecording(java.io.File,%20java.util.concurrent.Executor,%20androidx.camera.core.VideoCapture.OnVideoSavedCallback)

Do we have any technical difficulty to implement this new CameraView or it's just nobody had time yet? Maybe I can take a look and see how this new package can be ultilized?

**Comment by sibelius** [comment]
feel free to start the implementation of the Camera from androidX

we need the old camera API to support old androids
