### ISSUE TITLE
 white barcode on a black background is not recognised

### ISSUE THREAD

**Issue by interstates21** [react-native-community/react-native-camera#2849]
# Question

if there any way to recognize a similar barcode?
![Black Barcode](https://www.carmd.com/wp-content/uploads/2019/10/VIN_Barcode.jpg)

**Comment by interstates21** [comment]
I figured it out! <RNCamera googleVisionBarcodeMode={RNCamera.Constants.GoogleVisionBarcodeDetection.BarcodeMode.ALTERNATE} />

**Comment by dev-einn** [comment]
How ?
