### ISSUE TITLE
subview doesn't work for me

### ISSUE THREAD

**Issue by rongzhou** [react-native-community/react-native-camera#286]
### Steps to reproduce
1. use the code from master.
2. copy the test code from readme.
3. test on genymotion android emulator run on mac os.
### Expected behaviour

See the capture button
### Actual behaviour

Can't see the capture button
### Environment
- **Node.js version**: 6.1.0
- **React Native version**: 0.25
- **React Native platform + platform version**: Android 5.0
### react-native-camera

**Version**: master

**Comment by stoffern** [comment]
duplicate issue..
I have added a comment on how to get the button outside camera here:
[https://github.com/lwansbrough/react-native-camera/issues/198#issuecomment-200468857](url)

**Comment by gchiocchio** [comment]
it seems an z-order problem in class RTCCameraView, i have added this code in RCTCameraView.java

```
import android.view.View;
.....
  @Override
    public void onViewAdded(View child) {
        if (this._viewFinder == child) return;
         this.removeView(this._viewFinder);
        this.addView(this._viewFinder, 0);
    }
```

and for my project sub item now work correctly

**Comment by rt2zz** [comment]
@gchiocchio good find, can you PR that change?

**Comment by gchiocchio** [comment]
yes i have sent the pr

**Comment by rt2zz** [comment]
I see [your branch](https://github.com/gchiocchio/react-native-camera/tree/patch-1) but no PR...

**Comment by cyphire** [comment]
Thank you gchiocchio! My app works now!

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
