### ISSUE TITLE
Build conflict with googlePlayServicesVersion=17.0.0

### ISSUE THREAD

**Issue by kelvin-dev** [react-native-community/react-native-camera#2870]
Latest source on the master branch gets conflicted with below react-native extension
[https://github.com/Agontuk/react-native-geolocation-service](https://github.com/Agontuk/react-native-geolocation-service)
at the must-have configuration
```
ext {
  compileSdkVersion   = 28
  buildToolsVersion   = "28.0.3"
  minSdkVersion       = 16
  targetSdkVersion    = 28

  // Below line causes the problem on project :react-native-camera
  googlePlayServicesVersion      = "17.0.0
  // playServicesVersion         = "17.0.0"
  // playServicesLocationVersion = "17.0.0"
}

```
**Build logs:**

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':react-native-camera:compileGeneralDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-camera:generalDebugCompileClasspath'.
   > Could not find com.google.android.gms:play-services-vision:17.0.0.
     Required by:
         project :react-native-camera
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
```

**Comment by Atww** [comment]
same problem

**Comment by dotdotgod** [comment]
try to set version "17.0.2"?

**Comment by leononly** [comment]
same problem to me too

**Comment by jmlavoier** [comment]
Same problem here, has anyone solved the problem, I didn't find anything in the documentation about this troubleshooting. It happens when we are using the `react-native-geolocation-service` with `react-native-camera`. That's why that geolocation library requires [googlePlayServicesVersion = "17.0.0"](https://github.com/Agontuk/react-native-geolocation-service#android) as described in documentation. And I've googled about this version and I found solutions to change the `googlePlayServicesVersion` to `17.0.2`. But it causes problems in that geolocation library.

I'm thinking this isn't about the documentation problem. It could be about compatibility.

**Comment by jmlavoier** [comment]
I solved this with this refactor in [documentation about modify buildgradle](https://github.com/react-native-community/react-native-camera/blob/master/docs/installation.md#modifying-buildgradle)

In the doc, we don't have a good explanation about that modification. When and why I should do it? 

If someone is getting the same error, changing `missingDimensionStrategy 'react-native-camera', 'general'` to `missingDimensionStrategy 'react-native-camera', 'mlkit'` worked to me.

**Comment by leoceolin** [comment]
> I solved this with this refactor in [documentation about modify buildgradle](https://github.com/react-native-community/react-native-camera/blob/master/docs/installation.md#modifying-buildgradle)
> 
> In the doc, we don't have a good explanation about that modification. When and why I should do it?
> 
> If someone is getting the same error, changing `missingDimensionStrategy 'react-native-camera', 'general'` to `missingDimensionStrategy 'react-native-camera', 'mlkit'` worked to me.

not work for me !

my android/build.gradle file:

        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = '28.0.0'
        googlePlayServicesVersion = "17.0.0"

my android/app/build.gradle

missingDimensionStrategy 'react-native-camera', 'mlkit'


need help !

**Comment by rorlf** [comment]
I'm getting the same error.

**Comment by tnghia944** [comment]
ADD in  your build.gragle
       googlePlayServicesVersion  = "17.0.0"
        googlePlayServicesVisionVersion = "17.0.2"
