### ISSUE TITLE
Error scanning QRs

### ISSUE THREAD

**Issue by mlopezfernandez** [react-native-community/react-native-camera#2875]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues? 

**Platforms**

 

**Versions**

- Android: 10, 9, 7
- react-native-camera: 3.30.0
- react-native: 0.62.2
- react: 16.11.0
  

**Description/Current Behaviour**

When the camera is opened for QR scanning an error pops up on the screen. We realized that when "onGoogleVisionBarcodesDetected" prop is removed this error doesn't appear.

![image](https://user-images.githubusercontent.com/17619458/85035925-01125700-b184-11ea-8193-0dbab84ff22d.png)

This error only happens on Android 9 and 10.

**Steps to Reproduce**
Open camera in Android 9 or 10 for scanning QR

**Comment by dotdotgod** [comment]
same here.

**Comment by gablorquet** [comment]
It was working fine on our client devices and we started getting errors since an Android update this week, maybe it has something to do with it ?

**Comment by thanhpcc96** [comment]
+1

**Comment by jbauer-sds** [comment]
Experiencing this as well when using onGoogleVisionBarcodesDetected for both QR and 128.

**Comment by brendan1809** [comment]
i tried console log onGoogleVisionBarcodesDetected it will always trigger it with unknown format even i am not scanning any qr and barcode

**Comment by adeshpandey** [comment]
Happening with me too, even onBarCodeRead returns partial qr code

**Comment by mlopezfernandez** [comment]
@adeshpandey What do you mean with partial qr code? We are trying to use this prop but the returned object is undefined.

**Comment by adeshpandey** [comment]
Hi @mlopezfernandez 
My QR Code is: https://imgur.com/AqUySJ8 . RNCamera is returning: ^8r� but full QR code content is: ^8r�G0E :v(wp$H���ك��/�b��DH\�T�F!��g�[@�����Q
��S���ȇp1�~�J�~��IEtIe�E�

I have verified with many other tools.

**Comment by adeshpandey** [comment]
Hi @mlopezfernandez 
Anybody, who has solved this ? I have even tried to look into the source code but seems nothing helpful. I have tried to base64 encode the rawBytes in the BarCodeReadEvent.java and decode in my component but still no luck.

**Comment by gablorquet** [comment]
I had to add a check for 'UNKNOWN_FORMAT' type before invoking my callback function so, more a workaround than an actual fix but it works

**Comment by jbauer-sds** [comment]
Hi @gablorquet, your post has given me a bit of hope. Could you elaborate a bit? Which file did you add the 'UNKNOWN_FORMAT' type to?

**Comment by gablorquet** [comment]
Oh I added it directly to the function I pass to onGoogleVisionBarcodesDetected

**Comment by jbauer-sds** [comment]
Here's what I have for my onGoogleBarcodesDetected: 

![Screen Shot 2020-06-24 at 9 34 01 AM](https://user-images.githubusercontent.com/39097848/85586156-e9145a80-b5fd-11ea-9b1d-921a11fae137.png)

Unfortunately, even though I have specified `barCodeTypes={[RNCamera.Constants.BarCodeType.qr]}` I am getting a TON of scans with the format of None. This seems to be degrading performance a bit but you are right, this workaround does work.

Thanks @gablorquet!

**Comment by haikov** [comment]
The same issue started happening to my app in production as well about a week ago, which made the app useless for some chunk of users. As I've found out, camera module started calling `onGoogleVisionBarcodesDeceted` with "barcodes" of types `UNKNOWN_FORMAT`, right after opening the camera.

As a hot fix, I've added the following check inside the `onGoogleVisionBarcodesDeceted` callback, which fixed errors, but the root cause is still there - the function is being called all the time:
```
if (barcodes.length > 0 && barcodes[0].type === 'UNKNOWN_FORMAT') {
  return;
}
```

Maybe someon have any idea what happened and why is it started to behave this way? I didn't update the app for a month in the Play Store, so it happened due to some over-the-air library update or maybe Android? Also, would be great to find the proper fix for that, so callback won't be fired all the time.

**Comment by jbauer-sds** [comment]
So far it only happens on Google Play Services 20.21.17 for me (040306-316502805).

**Comment by mlopezfernandez** [comment]
@adeshpandey We are using @gablorquet's workaround. @gablorquet thanks for this solution until Google fix this bug.

**Comment by zedart** [comment]
Use onBarCodeRead instead.
        onBarCodeRead={this.barcodeRecognized.bind(this)}
  barcodeRecognized = (e) => {
      console.warn(JSON.stringify(e)); // you can show only e.data 
      this._onSendBarCode('12557', e.data);
  };

**Comment by kstoykov** [comment]
@zedart 's solution works perfectly
