### ISSUE TITLE
onFacesDetected callback is not working in iOS

### ISSUE THREAD

**Issue by luvnish19** [react-native-community/react-native-camera#2885]
# In RNCamera, onFacesDetected listener is not being called in iOS.      Note: In Android it gives faces array.
Using 
Xcode: 11.3.1 
Language : Objective C
testing in iPhone 7 (13.3.1)
RNCamera library version : 3.31.0

        
    facesDetected = ({ faces }) => {
        console.log("faces length = " + faces.length)
        this.setState({ faces });
    }

   <RNCamera
                    ref={ref => { this.camera = ref; }}
                    style={{
                        width: '100%',
                        height: '100%',
                        justifyContent: 'space-between',
                    }}
                    zoom={this.state.zoom}
                    maxZoom={MAX_ZOOM}
                    type={this.state.cameraType}
                    flashMode={flash}
                    autoFocus={this.state.autoFocus}
                    whiteBalance={this.state.whiteBalance}
                    onFacesDetected={this.state.faceDetectionEnabled ? this.facesDetected : undefined}
                    onFaceDetectionError={() => console.log("this.faceDetectedError")}
                    ratio={this.state.ratio}
                    focusDepth={this.state.depth}
                    onCameraReady={() => this.setState({ faceDetectionEnabled: true })}
                    captureAudio={false}
                    androidCameraPermissionOptions={{
                        title: 'Permission to use camera',
                        message: 'We need your permission to use your camera',
                        buttonPositive: 'Ok',
                        buttonNegative: 'Cancel',
                    }} />

Please provide solution I will be very grateful.

**Comment by sibelius** [comment]
does it fail on examples/mlkit?
