### ISSUE TITLE
Barcode Scanner does not triggered on iOS

### ISSUE THREAD

**Issue by WrathChaos** [react-native-community/react-native-camera#2888]
# Bug Report

**To Do First**

- [x] Did you try latest release?
- [x] Did you try master?
- [x] Did you look for existing matching issues?

**Platforms**

Works great on **Android** but not even triggered on **iOS**

**Versions**

- iOS: 13.3.1
- react-native-camera: 3.31.0
- react-native: 0.61.5
- react: 16.12.0
- react-navigation:  4.0.10

**Description/Current Behaviour**

It does not scan the barcode or does not trigger the scanned method.

**Expected Behaviour**

It should scan the barcode without problem like Android.

## Reproducible Code:

```
<RNCamera
        ref={(ref) => {
          this.camera = ref;
        }}
        style={{ flex: 1, width: "100%" }}
        type={RNCamera.Constants.Type.back}
        onGoogleVisionBarcodesDetected={this.barcodeRecognized}
/>

barcodeRecognized = ({ barcodes }) => {
    alert("Barcodes: ", barcodes);
}
```

# Solution

Thanks to @vuongductuanktmt

Simply copy-paste this into your Podfile and `npx pod-install`, re-bundle and run. It works :)

```
pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
'TextDetector',
'FaceDetectorMLKit',
'BarcodeDetectorMLKit'
]
```

**Comment by tphuc012** [comment]
I have the same problem, please help me solve it

**Comment by interstates21** [comment]
Same issue

**Comment by vuongductuanktmt** [comment]
Same issue

**Comment by vuongductuanktmt** [comment]
I used in Podfile pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'TextDetector',
  'FaceDetectorMLKit',
  'BarcodeDetectorMLKit'
] it work

**Comment by pearson-g** [comment]
@vuongductuanktmt  My problem is a bit different, IOS is triggered occasionally, I did not use CocoaPods, How do i configure thanks

**Comment by ferasabufares** [comment]
pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
'BarcodeDetectorMLKit'
]

can you help me please after add this to pod  when i try to pod install this error happened 
![Screen Shot 2020-11-28 at 10 22 11 AM](https://user-images.githubusercontent.com/62293138/100498273-c7e60600-3169-11eb-8691-00d237d0dcd3.png)


     react": "16.9.0",
    "react-native": "^0.63.3",
    "react-native-camera": "^3.40.0",

**Comment by notjulian** [comment]
hi @ferasabufares,
In the same project I've also @react-native-firebase 

I add this on my Podfile

```
# Override Firebase SDK Version
$FirebaseSDKVersion = '6.34.0'
```

**Comment by 99uno** [comment]
Same issue: onGoogleVisionBarcodesDetected does not work on iOS, but I'm using react native 0.64, so can I add the line to the Podfile despite the react native version has autolinking?

**Comment by stanica** [comment]
Is barcode detection dead on iOS?
