### ISSUE TITLE
Crash if app can't connect to the camera

### ISSUE THREAD

**Issue by khakulov** [react-native-community/react-native-camera#293]
### Steps to reproduce
1. App has authorization to access to the camera
2. But camera is busy in hardware level for some unpredictable reason, so that CameraService connection rejected
3. App crashes
### Expected behaviour

check if camera successful connected, if not show and error.
### Actual behaviour

Crash without reason.
`adb logcat` output:

![image](https://cloud.githubusercontent.com/assets/441436/15500840/e9d5d9f8-21aa-11e6-850f-3f7c07df6a6c.png)

**Comment by dcworldwide** [comment]
@khakulov 

- Is this android specific?
- When does the crash occur? On camera load or on capture?

I have frequent crashes on Android, Samsung S5 - but only when I capture a photo.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
