### ISSUE TITLE
Scanning VIN/PIN of vehicles

### ISSUE THREAD

**Issue by AnshDubey1999** [react-native-community/react-native-camera#2961]
Hello.

I currently am using the RNCamera to scan barcodes. I want to add a new feature to the app where the users can scan the VIN/PIN code of their vehicles. However, as they're code 39 but specifically, USS Code 39 barcodes, RNCamera/ RN Qrcode scanner is unable to scan them.

I wanted to know if there is a way to scan these VIN/PIN of vehicles using RNCamera or will I have to use any 3rd party SDK for the same.

Thanks.

**Comment by rafaelcavalcante** [comment]
You'll have to use a third-party sdk like tensorflow to read the captured image and retrieve the VIN/PIN

**Comment by rafaelcavalcante** [comment]
@sibelius, i believe this can be closed
