### ISSUE TITLE
Microphone recording on iOS front camera is soft

### ISSUE THREAD

**Issue by Yaseen-Davids** [react-native-community/react-native-camera#2963]
Hi, i'm having an issue with recording on iOS.

When recording video and audio on iOS, the microphone levels are very soft, however, when recording with rear camera, the microphone levels are normal. This is not an issue on Android.

If i continue to record the front camera, the microphone is soft, but if I don't make any noise, the microphone goes loud and then soft again.

I've already tried setting:
  captureAudio={true}
  keepAudioSession={true}
  playSoundOnCapture={false}

I've tried playing with the AVAudioSession settings but no results.

Any solutions??

Thank you.

**Comment by NooruddinLakhani** [comment]
Have you resolved it?
