### ISSUE TITLE
Images are not accessible upon rebuilding ios project

### ISSUE THREAD

**Issue by israelidanny** [react-native-community/react-native-camera#321]
This could be related to:
https://github.com/lwansbrough/react-native-camera/issues/310

When I'm working on a project and save using `disk` mode, everything works fine until I rebuild the project and run it. The files are still there (if I check the actual drive folder), but they "disappear" for the app itself. 

Replicating is easy - just snap some pics via `disk` mode. Save the URI somewhere, and then try to display that URI after you rebuilt the ios project.

**Comment by ericchen0121** [comment]
Same issue. Any movement on this?

**Comment by philipheinser** [comment]
Same problem here. We also loose all the images after an app update is production...

**Comment by philipheinser** [comment]
@israelidanny @ericchen0121 @charpeni This is because iOS App are installed in a Sandbox and after each install the app is in a different directory. So we need to export the path in the document directory and not the absolute url.

**Comment by AndreasKlein** [comment]
This is a real issue for us. Are there plans to address this? @philipheinser @Iwansbrough @rt2zz

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
