### ISSUE TITLE
Could not find method... errors in Android

### ISSUE THREAD

**Issue by dudeinthemirror** [react-native-community/react-native-camera#324]
### Steps to reproduce
1. render a Camera component

```
        <Camera
          style={styles.container}
          ref="camera"
          type={this.state.cameraType}
          captureAudio={false}
        >
```

see complete code for the CameraContainer.js file here: https://gist.github.com/dudeinthemirror/e1751f0b52241690533e236f75b22a9e
2. run in Genymotion or tethered device
3. 
### Expected behaviour

Capture button (cameraButton) and flip view button (flipButton) should render on top of the camera view

![img_0488](https://cloud.githubusercontent.com/assets/981638/16165473/f5eeb57e-3498-11e6-8038-2963bd6a1471.png)
### Actual behaviour

Capture and flip buttons do not show (The exact same code works fine in iOS - see above s/shot)

![screenshot_2016-06-17-12-16-30](https://cloud.githubusercontent.com/assets/981638/16165548/6358d8ec-3499-11e6-99e7-eb005eef5ce9.png)

and these errors show up in the logcat:

https://gist.github.com/dudeinthemirror/3cba9433bcc6e274b878d04c5cf4a50a
### Environment
- **Node.js version**:

5.4.0
- **React Native version**:

react-native-cli: 1.0.0
react-native: 0.26.3
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

Android 4.4.4
### react-native-camera

**Version**: npm version or "master"

"react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",

**Comment by dudeinthemirror** [comment]
Fixed it with something that doesn't quite make sense, but it now works on both iOS and Android:
Took the `TouchableHighlight`'s (cameraButton and flipButton) out from under `<Camera>` and put them at the same level with `<Camera>` within a container `<View>`

```
      return (
        <View style={styles.container}>
         
         <Camera style={styles.camera}
            ref="camera"
            type={this.state.cameraType}
            captureAudio={false}
          >
          </Camera>
          
         <TouchableHighlight
             style={styles.cameraButton}
             onPress={this._takePicture}>
             <View style={styles.cameraButtonInner} />
          </TouchableHighlight>

          <TouchableHighlight
             style={styles.flipButton}
             onPress={this._flipCamera}>
             <Icon allowFontScaling={false}
             name='cycle'
             size={24}
             color={'#FFFFFF'}
          />
          </TouchableHighlight>
        
      </View>
```

**Comment by error-bruno** [comment]
Not sure if this will fix your errors in logcat, but there is currently a PR dealing with the Z-index for android. 

[Fix Z-Index](https://github.com/lwansbrough/react-native-camera/pull/308) That fixes [Issue #286](https://github.com/lwansbrough/react-native-camera/issues/286)

**Comment by dudeinthemirror** [comment]
thanks @error-bruno, will verify once the PR is in.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
