### ISSUE TITLE
Starting with TorchMode.On is broken

### ISSUE THREAD

**Issue by JAStanton** [react-native-community/react-native-camera#328]
### Steps to reproduce
1. `<Camera torchMode={Camera.Constants.TorchMode.On} />`
2. Observe the flash turn on, then immediately off.
### Expected behaviour

The light should stay on.
### Actual behaviour

The light flickers off.
### Environment
- **Node.js version**: v6.2.1
- **React Native version**: 27.1
- **React Native platform + platform version**: iOS 9.3.2
### react-native-camera

**Version**: npm version or "master": 0.3.8
### Related issue

similar: https://github.com/lwansbrough/react-native-camera/issues/123 and fixed here: https://github.com/lwansbrough/react-native-camera/pull/261 but it doesn't fix the light staying on.  mentioned here as well: https://github.com/lwansbrough/react-native-camera/issues/123#issuecomment-217403124

**Comment by theopolisme** [comment]
+1 encountering as well

**Comment by Shawn8585** [comment]
+1

**Comment by andrewvmail** [comment]
+1

**Comment by Guillane** [comment]
+1

**Comment by mesbahsabur** [comment]
+1

**Comment by mesbahsabur** [comment]
See my comment at #123

**Comment by wouteralberts** [comment]
I fixed this by using state for torchMode (initially `off`) and setting it to `on` after showing my camera component:

```
this.setState({showCameraComponent: true}, () => {

    this.setState({torchMode: Camera.constants.TorchMode.on})

});
```
`<Camera ... torchMode={ this.state.torchMode }/>`

**Comment by Symous** [comment]
@wouteralberts that's works, thank u!

**Comment by arberK** [comment]
+1

**Comment by imapolaris** [comment]
yes, just as @wouteralberts said. It works well for me!

**Comment by ma-pe** [comment]
Thanks for the _workaround_ @wouteralberts. 

Nevertheless this needs to be fixed.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
