### ISSUE TITLE
On IOS picture is always Portrait and on Android its always Landscape

### ISSUE THREAD

**Issue by Vani-gurnani** [react-native-community/react-native-camera#336]
We have set the Camera orientation to default and on IOS it always takes Portrait pictures and on Android it always takes Landscape.

We are in production and this is a really bad issue for our users. Any help will be appreciated.

**Comment by jakegardner** [comment]
+1

I have tried all orientation and rotation parameters to no effect.

React Native 0.27.2

**Comment by jacob-israel-turner** [comment]
+1 on this, big issue.

**Comment by dcworldwide** [comment]
Test:

- On android, simulator and galaxy s5
- Portrait mode set on RN camera
- Phone in portrait mode
- Capture photo
- Display photo in RN image. Displays in Landscape.

This would be a huge win to fix :cry:

**Comment by jasongaare** [comment]
For now my workaround is to utilize this library to rotate photos:

https://github.com/bamlab/react-native-image-resizer

**Comment by dcworldwide** [comment]
Does anyone have exif rotation logic they could kindly share to show a suggested solution?  Exif across devices can be a bit complicated

**Comment by TrekSoft** [comment]
Any update on this issue? I'm having it as well

**Comment by npomfret** [comment]
@Vani-gurnani @TrekSoft  are you able to test my PR?  It may help with this https://github.com/lwansbrough/react-native-camera/pull/682.

**Comment by vagnerSl** [comment]
+ 1

**Comment by Gigasz** [comment]
is this ever gonna be fixed?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
