### ISSUE TITLE
Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.

### ISSUE THREAD

**Issue by Shawn8585** [react-native-community/react-native-camera#339]
I can not passed Apple appStore‘s verify...

This occurred when your app was used: 
- Offline
- On Wi-Fi

We have attached detailed crash logs to help troubleshoot this issue.
### Environment
- **Node.js version 5.11.0:
- **React Native version 0.27.2:
- **React Native platform + platform version**: iOS 9.3.2, etc
### react-native-camera

**Version**: "git+https://github.com/lwansbrough/react-native-camera.git"

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
