### ISSUE TITLE
Request: Add  absolute path for Android - 

### ISSUE THREAD

**Issue by congnguyen91** [react-native-community/react-native-camera#344]
Hello,

Could you add "absolutePath" in WritableMap for android at File ? 
https://github.com/lwansbrough/react-native-camera/blob/master/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraModule.java 

for 'RCT_CAMERA_CAPTURE_TARGET_DISK', 'RCT_CAMERA_CAPTURE_TARGET_TEMP'

`response.putString("path", Uri.fromFile(pictureFile).toString());
response.putString("absolutePath", pictureFile.getAbsolutePath());`

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
