### ISSUE TITLE
what api can check phone has type=='front'||'back' ?

### ISSUE THREAD

**Issue by Timson020** [react-native-community/react-native-camera#349]
### Expected behaviour

Tell us what should happen
in china , some phone has not type =='front'
I need the api can check the phone has front camera in componentDidMount;
### Actual behaviour

Tell us what happens instead
### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
### react-native-camera

**Version**: npm version or "master"

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
