### ISSUE TITLE
Video camera is working, but the data is not being returned

### ISSUE THREAD

**Issue by hermant2** [react-native-community/react-native-camera#350]
So I have a component that takes videos, but when I try to `console.log` the data, nothing is happening.  I am sure that the camera is taking videos though because when I set the `captureTarget` to `cameraRoll`, the video is saving to my phone.

Here is the component itself, I tried to set a timeout to see if the console.log was firing off before the camera actually stopped recording, but I just got the value of null.  Before nothing else was happening.  It is not printing out in my Xcode console either.

```
class VideoCamera extends Component {


constructor() {
    super()
   this.state = {
     cameraType: Camera.constants.Type.back,
      captureMode: Camera.constants.CaptureMode.video,
     captureAudio: false,
     captureTarget: Camera.constants.CaptureTarget.cameraRoll,
      isRecording: false,
      videoData: null,
    }
  }
  render() {
   return (
     <View style={styles.container}>
       <Camera
           aspect={Camera.constants.Aspect.fill}
            captureAudio={this.state.captureAudio}
            captureMode={this.state.captureMode}
            captureTarget={this.state.captureTarget}
            ref="camera"
            style={styles.preview}
        >
        <TouchableHighlight?
            onPressIn={this.startRecord.bind(this)}
            onPressOut={this.endVideo.bind(this)}
        >
        <View style={this.state.isRecording ? styles.recordingButton : styles.recordButton}>
          <Icon
              name={'video-camera'}
              size={40}
          />
        </View>
          </TouchableHighlight>
          </Camera>
        </View>
      )
  }

  startRecord() {
    startVideo = setTimeout(this.recordVideo.bind(this), 50)
  }

  recordVideo() {
    this.setState({isRecording: true})
    this.refs.camera.capture()
      .then((data) => {
        console.log(data)
        this.setState({videoData: data})
     })
      .catch((err) => console.log(err))
  }

  endVideo() {
    this.setState({isRecording: false})
    this.refs.camera.stopCapture()
    setTimeout(() => {console.log(this.state.videoData)}, 5000)
  }
}
```
### Environment
- React version: ~15.1.0
- React Native version: 0.28.0
- React Native platform + platform version: iOS 9.0
  
  npm version

**Comment by RichLewis007** [comment]
I'm also trying to get video to work. I'm working from the Example code of the project, and have tried adding captureMode: Camera.constants.CaptureMode.video to the camera state, but haven't gotten anything but picture taking so far.

**Comment by krillov** [comment]
@RichLewis007 Any luck with the video? I got the same problems. It takes pictures only.

**Comment by bsiddiqui** [comment]
@krillov I was able to get the video working - mind positing your component and I'll try and help you out

**Comment by krillov** [comment]
@bsiddiqui Thanks. I already have a working camera app and I wanted to implement video function also. I'm using iphone simulator in Xcode. It simulates taking pictures great but I'm not sure if it can also simulate recording video.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
