### ISSUE TITLE
How to capture a picture and save to a specific album?

### ISSUE THREAD

**Issue by demobo-com** [react-native-community/react-native-camera#356]
How to capture a picture and save to a specific album? How to create an application album?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

**Comment by isnifer** [comment]
@ospfranco please reopen. This feature is not implemented, correct?
