### ISSUE TITLE
Camera.checkDeviceAuthorizationStatus is not a function

### ISSUE THREAD

**Issue by krisoul** [react-native-community/react-native-camera#361]
![](http://ww2.sinaimg.cn/large/6df1da21gw1f6nm4rz1qij20dd0lggpl.jpg)

why?

**Comment by EverChris** [comment]
help me

**Comment by markomatic** [comment]
@EverChris, are you calling it statically on imported Camera class?

import Camera from 'react-native-camera';
...
Camera.checkDeviceAuthorizationStatus()...

**Comment by realjamie** [comment]
I had the same issue. My react-native-camera was working well until I upgrade it to 0.3.8 and upgrade ReactNative to 0.32.0

[Environment]
Node.js version: 4.2.4
React Native version: 0.32.0
React Native platform + platform version: iOS

[react-native-camera]
Version: 0.3.8

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
