### ISSUE TITLE
a way to set the filename output when recording a video?

### ISSUE THREAD

**Issue by manask88** [react-native-community/react-native-camera#374]
I need to follow some naming conventions when creating a video file using the camera. Is there a way to set the name of the file that is created using this component?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
