### ISSUE TITLE
Error when import the Camera from 'react-native-camera';

### ISSUE THREAD

**Issue by Talkwondo** [react-native-community/react-native-camera#376]
When I add it I get this error
<img width="358" alt="screen shot 2016-08-22 at 9 31 17 pm" src="https://cloud.githubusercontent.com/assets/20122139/17866706/35d2ad62-68b0-11e6-94c8-9d547f628053.png">

**Comment by cavinsmith** [comment]
Identical thing happened to me:

`[error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'CameraManager.CaptureQuality.high')`

**Comment by benjick** [comment]
Getting the same error when running on Android (device)

**Comment by cavinsmith** [comment]
@Talkwondo, @benjick  I've resolved my problem by uninstalling+unlinking software and installing again via automatic install provided in description. I guess you should try to uninstall, unlink react-camera and try one-by-one all installation methods provided by author.

**Comment by Panda313** [comment]
On IOS, "Simulator > Reset Content & Settings" did the trick for me (I did auto and manual linking before but still got the error)

**Comment by VincentLaulagnet** [comment]
I have the same issue on Android.
It is working using RN0.28, but stopped working using RN0.29
@cavinsmith  I tried reinstalling and relinking but it did not help.

**Comment by VincentLaulagnet** [comment]
The issue in my set-up was related to the linking set-up. I could get it to work by manually modifying the MainApplication.java which was not correctly updated by either react-native link or rnpm link commands

**Comment by sibelius** [comment]
this is a problem with react-native link
