### ISSUE TITLE
ReactNative.createClass

### ISSUE THREAD

**Issue by benjick** [react-native-community/react-native-camera#384]
### Steps to reproduce
1. Install camera with npm and rnpm
2. 

``` js
import Camera from 'react-native-camera';
<Camera
    style={s.preview}
    aspect={Camera.constants.Aspect.fill} >
  <Text style={s.capture}>[CAPTURE]</Text>
</Camera>
```
### Expected behaviour

To render the camera
### Actual behaviour

It displays this error message:

<img width="355" alt="screen shot 2016-08-28 at 14 30 28" src="https://cloud.githubusercontent.com/assets/430872/18033703/ff2b40e6-6d2b-11e6-8da8-2f41629d41c6.png">
### Environment
- **Node.js version**: 6.3
- **React Native version**: 0.32.0
- **React Native platform + platform version**: iOS 9.3
### react-native-camera

**Version**: 0.3.8

**Comment by benjick** [comment]
Using `npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save` it works

**Comment by VincentLaulagnet** [comment]
I have the same issue on Android. 
It is working using RN0.28, but stopped working using RN0.29
@benjick I tried reinstalling and relinking but it did not help.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
