### ISSUE TITLE
Why are strings used for barcode bounds?

### ISSUE THREAD

**Issue by randycoulman** [react-native-community/react-native-camera#391]
First, let me thank you for this project.  I was able to drop it into my app and everything just worked.  So awesome!

This is more of a question than a bug, but it's something that caught me by surprise.

When I supply an `onBarCodeRead` callback, the `bounds` passed into the callback have string values instead of floats.  Is there a reason for this?

The code in question is very explicit about making them strings (from `ios/RCTCameraManager.m`):

```
        NSDictionary *event = @{
          @"type": metadata.type,
          @"data": metadata.stringValue,
          @"bounds": @{
            @"origin": @{
              @"x": [NSString stringWithFormat:@"%f", transformed.bounds.origin.x],
              @"y": [NSString stringWithFormat:@"%f", transformed.bounds.origin.y]
            },
            @"size": @{
              @"height": [NSString stringWithFormat:@"%f", transformed.bounds.size.height],
              @"width": [NSString stringWithFormat:@"%f", transformed.bounds.size.width],
            }
          }
        };
```

Are you interested in a PR that makes these into floats instead of strings?  It would be a breaking change to the public API, but since this project isn't at 1.0 yet, that might be OK.
### Steps to reproduce
1. Supply a callback for the `onBarCodeRead` property.
2. Inspect the value of the `bounds` parameter that is passed to the callback.
3. Note that the values of `origin.x`, `origin.y`, `size.width`, and `size.height` are all strings.
### Expected behaviour

The `bounds` object's sub-properties (`origin` and `size`) should contain values that are floats.
### Actual behaviour

The values in the `origin` and `size` sub-properties are strings.
### Environment
- **Node.js version**: 6.5.0
- **React Native version**: 0.32.0
- **React Native platform + platform version**: iOS 9.0
### react-native-camera

**Version**: master (as of be8b89c5)

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
