### ISSUE TITLE
camera.capture() promise never fulfilled

### ISSUE THREAD

**Issue by tslater** [react-native-community/react-native-camera#395]
### Steps to reproduce
1. Clone the example from react-native-camera
2. npm i && react-native run-android
3. Press the camera buttons
### Expected behaviour

See something in the log:

```
  takePicture() {
    if (this.camera) {
      this.camera.capture()
        .then((data) => console.log(data))
        .catch(err => console.error(err));
    }
  }
```
### Actual behaviour

Nothing shows in the log (i.e. promise is never called). I also tried adding a `finally` with no success in getting that to call. The camera object does exist, so the ref is working correctly, the promise functions just never get called.
### Environment
- **Node.js version**: 6.5.0 (upgraded after seeing there error, started on 4.4.1)
- **React Native version**: ^0.26.2 (from example)
- **React Native platform + platform version**: Android 6.0.1 (Samsung Galaxy S5)
### react-native-camera

**Version**: master

**Comment by tslater** [comment]
It works if I set the orientation: `orientation={Camera.constants.Orientation.portrait}`, but not if it is the default, which I believe is auto.

**Comment by editkid** [comment]
Confirming that this is happening also on some of my Android devices (e.g. Nexus 7) and that setting the orientation does 'fix' the issue.

**Comment by Satya5614** [comment]
Setting `orientation={Camera.constants.Orientation.portrait` doesn't fix the problem when the capture mode is Video. Is there any other way to fix this?

**Comment by editkid** [comment]
I'm using video capture mode, @Satya5614. For me the workaround works.

**Comment by Satya5614** [comment]
@editkid Have you tested that on iOS device?

**Comment by editkid** [comment]
I have no problems on iOS at all. The only platform that required the 'fix' for me was Android, and then only on some devices.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
