### ISSUE TITLE
Back camera flashes before switching to front 

### ISSUE THREAD

**Issue by bsiddiqui** [react-native-community/react-native-camera#398]
### Steps to reproduce

I have a camera set with `type={Camera.constants.Type.front}`. The first time I load the app, it will show the back camera first and then switch to the front camera.
### Expected behaviour

Camera view opens with proper camera type (front or back)
### Actual behaviour

The first time I open the camera component it will show the back camera and then switch back to the front camera
### Environment
- **Node.js version**: 6.4.0
- **React Native version**: 0.30.0
- **React Native platform + platform version**: iOS 9.3
### react-native-camera
- **Version**: master

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
