### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeCamera2.default.constants.CaptureQuality.medium')

### ISSUE THREAD

**Issue by realjamie** [react-native-community/react-native-camera#400]
### Steps to reproduce
1. I set my Camera as follows:

```
<Camera
        ref="camera"
        style={this._styles.container}
        aspect={this.props.aspect}
        captureAudio
        captureMode={Camera.constants.CaptureMode.video}
        captureQuality={Camera.constants.CaptureQuality.medium}
        captureTarget={this.props.captureTarget}
        defaultOnFocusComponent
        flashMode={Camera.constants.FlashMode.auto}
        keepAwake
        onFocusChanged={this._handleFocusChanged}
        onZoomChanged={this._handleZoomChanged}
        orientation={Camera.constants.Orientation.auto}
        type={this.props.cameraType}>
          {this.props.children}
      </Camera>
```
### Expected behaviour

It should renders the Camera without error
### Actual behaviour

I got an error: "undefined is not an object (evaluating '_reactNativeCamera2.default.constants.CaptureQuality.medium')". But if I set `captureQuality="medium"`, it renders the Camera.

![img_0028](https://cloud.githubusercontent.com/assets/5363036/18368786/b6b982b0-75d6-11e6-9e9c-68c3822965d8.jpg)
### Environment
- **Node.js version**: 4.2.4
- **React Native version**: 0.32.0
- **React Native platform + platform version**: iOS 9.2.1
### react-native-camera

**Version**: 0.3.8

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
