### ISSUE TITLE
Occasionally a captured frame and a stopped frame immediately after shutter effect are different (Android)

### ISSUE THREAD

**Issue by jaewonha** [react-native-community/react-native-camera#402]
### Steps to reproduce
1. capture a frame using camera.capture() 
### Expected behaviour

Compare what you see for a stopped frame immediately after shutter effect and captured image from file.
- Both stopped frame and captured image should be the same
### Actual behaviour
- They are occasionally different. 
- The captured image is a few frame ahead than the stopped frame immediately after shutter effect.
- Capturing image & playing shutter sound seems done in sync
- I guess stopping video process is done after playing shutter effect (maybe it should be done in reverse...?)
### Environment
- **Node.js version**: v6.3.1
- **React Native version**: 0.32.0
- **React Native platform + platform version**: Android 6.0
### react-native-camera

**Version**: 0.3.8 (maybe master, in root folder package.json dependency is set as 
"react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git", 
and at node_modules/react-native-camera/package.json version is 0.3.8)

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
