### ISSUE TITLE
Camera is "dimming" for 1 second on launch/load

### ISSUE THREAD

**Issue by larryranches** [react-native-community/react-native-camera#429]
There's about a 1 second dim initially when launching the camera, then it displays to the default brightness. It kind of makes it feel laggy. I'd like to smooth out that transition by getting rid of this "dimming" on initial component load. I'm not sure if this is the default setting in which I can change but doesn't look there is one in the api. Any help please?
### Steps to reproduce
1. Launch the react-native-camera component
2. Camera is dim for about 1 second then display default camera brightness
### Expected behaviour

Camera loads with default camera brightness without a 1 second dim. 
### Actual behaviour

Has a 1 second dim on load/launch. Makes it seems a little laggy.
### Environment
-  Node v6.6.0
- React Native 0.33
- IOS10
### react-native-camera

Master

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
