### ISSUE TITLE
Convert Preview to Buffer

### ISSUE THREAD

**Issue by ChrisCates** [react-native-community/react-native-camera#434]
Hey guys, looking to figure out how to convert the preview for the camera to a buffer...
Is there any way to do this?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

**Comment by ltung** [comment]
Does anybody have answer to this question?
