### ISSUE TITLE
Add Version Support Table

### ISSUE THREAD

**Issue by dangnelson** [react-native-community/react-native-camera#450]
I'm working on a standard for displaying version support on React-Native module README files. I would love your feedback: [react-native-version-support-table](https://github.com/dangnelson/react-native-version-support-table/)

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

**Comment by sibelius** [comment]
@dangnelson this looks good, feel free to send a PR to solve this

**Comment by ospfranco** [comment]
Looks like this last commit was 8 months ago
