### ISSUE TITLE
A way to read data byte from current preview, like a previewCallback?

### ISSUE THREAD

**Issue by kenma9123** [react-native-community/react-native-camera#451]
Is there a way to read the data from the current preview? My goal is to retrieve the camera preview as a Pixel Array.

A preview callback would be a good addition, passing the data byte, just like the onPreviewFrame callback when you set it up.

**Comment by rameshvishnoi90904** [comment]
yes, need to preview the captured images

**Comment by rameshvishnoi90904** [comment]
yes, need to preview the captured images

**Comment by MathieuMailhos** [comment]
Agreed, need a preview callback function.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

**Comment by DennisJu007** [comment]
@n1ru4l Has  this issue was fixed in new release version?How can i use it.

**Comment by n1ru4l** [comment]
@DennisJu007 Please open a new issue or even better a pull request with an implementation.
