### ISSUE TITLE
Can't use pod install with react-native-camera

### ISSUE THREAD

**Issue by ColdJuzi** [react-native-community/react-native-camera#453]
### Steps to reproduce

[!] Unable to satisfy the following requirements:
- `react-native-camera (from`/Users/PhantomDev/Documents/PhantomSmart-RN/ReactNative/node_modules/react-native-camera`)` required by `Podfile`

It seems like you've changed the constraints of dependency `react-native-camera` inside your development pod `react-native-camera`.
You should run `pod update react-native-camera` to apply changes you've made.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
### react-native-camera

**Version**: npm version or "master"

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
