### ISSUE TITLE
Render Text in video

### ISSUE THREAD

**Issue by commit-master** [react-native-community/react-native-camera#454]
Do you think it is possible to actually add a text, or an image on a video and save the video with it ?
If yes, where would you start, maybe this should be implemented ? I would be nice for example if we could add a logo on the bottom right of the video to prevent people from sharing it without credit.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
