### ISSUE TITLE
Deadlock when rotating app

### ISSUE THREAD

**Issue by johnryan** [react-native-community/react-native-camera#461]
### Steps to reproduce

Create a camera view and rotate the device several times.
### Expected behaviour

The preview should rotate with the app.
### Actual behaviour

Eventually the preview layer gets locked in RCTCamera.m -layoutSubviews and the main thread becomes locked. I've attached a screenshot of the stack trace. I was able to solve the problem by changing layoutSubviews but it seems like a hack:

```
- (void)layoutSubviews
{
  [super layoutSubviews];
    dispatch_async(dispatch_get_main_queue(), ^{
        self.manager.previewLayer.frame = self.bounds;
        [self setBackgroundColor:[UIColor blackColor]];
        [self.layer insertSublayer:self.manager.previewLayer atIndex:0];
    });

}
```

<img width="344" alt="screen shot 2016-10-22 at 4 20 16 pm" src="https://cloud.githubusercontent.com/assets/416564/19622248/70beb95a-9873-11e6-967f-5396f23a3f3d.png">
### Environment
- **Node.js version**: 6.8.0
- **React Native version**: 0.35
- **React Native platform + platform version**: iOS 9.3.5
### react-native-camera

**Version**: master

**Comment by Anuj-786** [comment]
I think you should have to use orientation i.e 
Values: `Camera.constants.Orientation.auto or "auto" (default), Camera.constants.Orientation.landscapeLeft or "landscapeLeft", Camera.constants.Orientation.landscapeRight or "landscapeRight", Camera.constants.Orientation.portrait or "portrait", Camera.constants.Orientation.portraitUpsideDown or "portraitUpsideDown"`

**Comment by johnryan** [comment]
I haven't changed any of the values so it is set on the default (auto)  and as such should rotate with the rest of the app. It works sometimes but eventually locks up and freezes the app.

**Comment by GeoffreyPlitt** [comment]
I have a stacktrace which may help:

java.lang.RuntimeException·getParameters failed (empty parameters)
Raw
Camera.java:-2android.hardware.Camera.native_getParameters	
Camera.java:1996android.hardware.Camera.getParameters	
RCTCamera.java:332com.lwansbrough.RCTCamera.RCTCamera.adjustPreviewLayout	
RCTCamera.java:169com.lwansbrough.RCTCamera.RCTCamera.setActualDeviceOrientation	
RCTCameraView.java:122com.lwansbrough.RCTCamera.RCTCameraView.setActualDeviceOrientation	
RCTCameraView.java:16com.lwansbrough.RCTCamera.RCTCameraView.access$100	
RCTCameraView.java:34com.lwansbrough.RCTCamera.RCTCameraView$1.onOrientationChanged	
OrientationEventListener.java:403android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged	
SystemSensorManager.java:583android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent	
MessageQueue.java:-2android.os.MessageQueue.nativePollOnce	
MessageQueue.java:323android.os.MessageQueue.next	
Looper.java:143android.os.Looper.loop	
ActivityThread.java:7229android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
ZygoteInit.java:1230com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	
ZygoteInit.java:1120com.android.internal.os.ZygoteInit.main

**Comment by GeoffreyPlitt** [comment]
@johnryan Should I open a 2nd issue? I didn't see "ios" in the issue title. It's the exact same thing on Android - a deadlock when orientation flips.

**Comment by johnryan** [comment]
Ah ok, could be related then, I assumed it was a native iOS issue

**Comment by skizzo** [comment]
+1, was anybody able to solve this? this bug makes the component pretty much unusable.. thanks

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

**Comment by neogermi** [comment]
Hello, this is still a common issue for us and reproducible. The fix of the forks above seems to help though. Is there a PR for this?

**Comment by neogermi** [comment]
If there is no PR, I can create one if you want.

**Comment by sibelius** [comment]
Send a pr please

**Comment by neogermi** [comment]
See https://github.com/react-native-community/react-native-camera/pull/1194 :)

**Comment by enieber** [comment]
@sibelius or @jgfidelis, this issue can it is being closed?
