### ISSUE TITLE
Q: Real time image data > image processing

### ISSUE THREAD

**Issue by slinto** [react-native-community/react-native-camera#463]
Hi, 

is there any chance to get realtime image data from camera (without save to album), do with that some processing (eg. thresholding http://stackoverflow.com/questions/37512460/thresholding-base64-string-using-javascript) and render it to 'canvas' ? 

I'm new to react-native ecosystem. I think about this problem like about 'canvas' and canvas like image processing, but canvas on react-native is not available... Is only chance to do image processing like this throught native code?

Thanks a lot.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
