### ISSUE TITLE
AVCaptureStillImageOutput is deprecated in iOS 10. 

### ISSUE THREAD

**Issue by russellpbender** [react-native-community/react-native-camera#465]
RCTCameraManager is using AVCaptureStillImageOutput. 

This is deprecated in iOS 10 https://developer.apple.com/reference/avfoundation/avcapturestillimageoutput and has been replaced by AVCapturePhotoOutput 
https://developer.apple.com/reference/avfoundation/avcapturephotooutput

**Comment by sibelius** [comment]
![image](https://user-images.githubusercontent.com/2005841/33779419-0069b000-dc34-11e7-913c-8e4dbc130c8a.png)

do u guys would accept a PR to change AVCaptureStillImageOutput to AVCapturePhotoOutput?

**Comment by ospfranco** [comment]
Moving to new package soon, closing this anyways
