### ISSUE TITLE
Can't link to camera to app

### ISSUE THREAD

**Issue by IvanProdaiko94** [react-native-community/react-native-camera#472]
I have done all the steps that are required to link camera, but when I start my app it crashes on the building phase with this error (permission are also [added](https://monosnap.com/file/KTa5vVa2T6pPYCmCRBERLjWJfq3nsa)

**Comment by leechance** [comment]
ios or android? my android demo is crashed

**Comment by IvanProdaiko94** [comment]
Ios(

**Comment by IvanProdaiko94** [comment]
react-native 0.36.1

**Comment by ngsiolei** [comment]
@IvanProdaiko94 the screen capture in your first post seems to be something about Camera Roll access, the property `captureTarget` is default to `Camera.constants.CaptureTarget.cameraRoll` in ios (more details in README), see if this is your case.

**Comment by IvanProdaiko94** [comment]
So you think that the problem in permissions?
I added one, as it was mentioned in docs, but it fails on build img phase понедельник, 14 ноября 2016г., 04:19 +02:00 от leechance  notifications@github.com :

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
