### ISSUE TITLE
crash on removeFromSuperview

### ISSUE THREAD

**Issue by mvayngrib** [react-native-community/react-native-camera#474]
love the module! Hope this err report helps someone figure out what's wrong

### Steps to reproduce
no idea, just kept opening and closing camera screen (scanning qr codes)

### Expected behaviour
not crashing

### Actual behaviour
<img width="1164" alt="screen shot 2016-11-13 at 3 30 31 pm" src="https://cloud.githubusercontent.com/assets/83948/20248644/6fb9c802-a9b6-11e6-9fd3-3c71dc811526.png">

### Environment
- **Node.js version**: 6.5
- **React Native version**: 0.34.1
- **React Native platform + platform version**: iOS 9.3.5

### react-native-camera
**Version**: npm version or "master" 0.3.8

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
