### ISSUE TITLE
It doesn't match with iphone camera's default ratio

### ISSUE THREAD

**Issue by mnkang89** [react-native-community/react-native-camera#485]
### Steps to reproduce
1. I just followed the default example in react-native-camera.

### Expected behaviour
has the same ratio(or size) with native camera app (when I ran on iphone6)

### Actual behaviour
It doesn't match with default iphone camera app's ratio. it felt like react-native-camera's view is more zommed.. so i adjusted some parameters but it's not work..

It appears that the camera zooms in by default, with no ability to fully zoom out.

Is this intended, or is there a setting that can be adjusted to initiate the camera fully zoomed out?

![appcamera](https://cloud.githubusercontent.com/assets/12220785/20549294/3fd4703c-b16e-11e6-96e4-d6d04b21b93a.jpeg)
-Default Iphone6 native camera screen

![rncamera](https://cloud.githubusercontent.com/assets/12220785/20549293/3fd0e8fe-b16e-11e6-97c3-e79deaee5686.jpeg)
-RNcamera camera screen

**Comment by umesh-magicpin** [comment]
facing the same issue.

**Comment by machadogj** [comment]
I am experiencing the same problem. Any progress on this yet?

**Comment by antonshevchenko** [comment]
Noticed this too. It looks like it defaults to the "video" setting (if you got to the default camera app and swipe to "video" mode). Also, Snapchat has the same "zoom" as on the video mode. Not sure if/how this can be changed.

**Comment by mnkang89** [comment]
thx guys!! i hope this issue will be fixed soon lol!

**Comment by ionflow** [comment]
I'm experiencing the same issue on iPhone 6 as well. 

Also noticed the picture quality does not match the native camera regardless of what quality I choose in the settings. And the camera exposure does not adjust to match the native camera when shooting the same exact target/scene.

**Comment by almost** [comment]
Did anyone find a workaround for this issue?

**Comment by VikramK** [comment]
This setting worked for me. 

this.state = {
      camera: {
                     captureQuality: Camera.constants.CaptureQuality.photo
       }

  <Camera
                ref="cam"
                style={styles.container}
                type={this.state.cameraType}
                captureQuality={this.state.camera.captureQuality} />

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
