### ISSUE TITLE
onFocusChanged and onZoomChanged on android?

### ISSUE THREAD

**Issue by Cygnus2112** [react-native-community/react-native-camera#491]
Are onFocusChanged and onZoomChanged only enabled for ios? I can't seem to get them to work on android.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
