### ISSUE TITLE
Image produced after capture has a wider viewport than that visible in the preview

### ISSUE THREAD

**Issue by soumya-banerjee** [react-native-community/react-native-camera#495]
### Steps to reproduce
1. View a frame of specific width from the preview (as in the example provided)
2. Capture the frame
3. Objects outside the specified frame comes into the image produced

### Expected behaviour
The image should have the exact frame as that visible in the preview. The viewport should not get wider.

### Actual behaviour
The image produced after capture shows object outside the intended/captured frame. The image is usually wider than expected.

### Environment
- **React Native version**: 0.38.0
- **React Native platform + platform version**: Windows + Android 5.0

**Comment by J-Priebe** [comment]
Same problem here.

**Comment by jcmandersson** [comment]
Opposite problem here, I see objects in the preview that is not visible in the actual photo. Any progress on this?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
