### ISSUE TITLE
Scan qr-code from existing image in library ?

### ISSUE THREAD

**Issue by tiempham** [react-native-community/react-native-camera#496]
Hi @lwansbrough. I want create an app it can scan qr-code from photo in library. Do you have any idea or function to do that. Thank You!

**Comment by rayshen** [comment]
i need this, too

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
