### ISSUE TITLE
Bar code types not consistent

### ISSUE THREAD

**Issue by msom** [react-native-community/react-native-camera#499]
It would be nice to be able to work with single definition of bar code types. Limiting data matrix codes using `barCodeTypes` for example work only by using `'datamatrix'`or `'DATA_MATRIX'` on Android and 'org.iso.DataMatrix' on iOS (10). On Android, the `onBarCodeRead` returns `'DATA_MATRIX'`, while iOS returns `'org.iso.DataMatrix'`.

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
