### ISSUE TITLE
Crop images based on camera view

### ISSUE THREAD

**Issue by proProbe** [react-native-community/react-native-camera#501]
Hello!

Great library! Im stumbling upon a problem regarding cropping the taken images based on the aspect ratio that I've given to the camera. Lets say that Im rendering the camera in a view that has `height: 300, width: 400`, Im still getting images that are in full size. Is it possible to crop the images based on the camera size or is not supported and should be done with some post-process?

**Comment by J-Priebe** [comment]
I too spent a lot of time trying to figure this out... after looking at a ton of cropping libraries I discovered you can do it programatically with [ImageEditor](https://facebook.github.io/react-native/docs/imageeditor.html). There is an example by Facebook [here](https://github.com/facebook/react-native/blob/1d819e9503e69737733c3a0890ae272597527083/Examples/UIExplorer/ImageEditingExample.js)



Oddly hard to find a sparsely documented, but very convenient.

**Comment by blhack** [comment]
Would love to see this as a feature as well.  It seems like the most obvious behavior.

**Comment by npomfret** [comment]
Be warned, the RN ImageEditor does everything in base64, which means it uses more memory than a native implementation would, which on android phones in particular might mean the app crashing.

**Comment by joonhocho** [comment]
I need to do this too. Is there any image processing module for react native that can do simple crop, preferably on native side as @npomfret  mentioned? I've tried `ImageEditor` module, but it does not work with disk / temp file urls. @J-Priebe Did you get `ImageEditor` working for you with `react-native-camera`?

**Comment by victorbadila** [comment]
+1 I made some workarounds with ImageEditor but it is highly unstable on Android especially. This feature should be built in, it doesn't even make sense to show a specific camera view and when you capture the picture it looks completely different, this is an actual bug and should have high priority.

**Comment by mirrorshades** [comment]
So this PR was supposed to handle this but was never merged due to conflicts apparently. #627

**Comment by sunweiyang** [comment]
Looks like this is addresed in #1057.

**Comment by sibelius** [comment]
Done

**Comment by Traviskn** [comment]
It seems in the new release we have lost the ability to use `cropToPreview`, are there any plans to get cropping to preview working on the the new RNCamera?

**Comment by dipeshkoirala21** [comment]
can somebody help me out here? I need to use cropToPreview props, just like @Traviskn said. Is there any work around ?

**Comment by azazel404** [comment]
this case already close , and how to solve this issue , i have some problem Crop images based on camera view , in the documentation react native camera , doesnt support cropping image right ?

**Comment by azazel404** [comment]
> can somebody help me out here? I need to use cropToPreview props, just like @Traviskn said. Is there any work around ?

me too , your comment is few days ago , how about now , u already solve with this problem ?
