### ISSUE TITLE
Can't reduce the quality of the video. The app crash

### ISSUE THREAD

**Issue by THPubs** [react-native-community/react-native-camera#526]
Hi, I tried to set the quality of the video like this :

`captureQuality={Camera.constants.CaptureQuality.low}`

Then everytime I try to initiate the recording, the app crash with the message `Unfortunately, MyApp has stopped`. Any idea how to fix this?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
