### ISSUE TITLE
Android orientation fix crash on Samsung phone

### ISSUE THREAD

**Issue by radko93** [react-native-community/react-native-camera#530]
### Steps to reproduce
1. Same like here #475 

### Expected behaviour
After fix in #493, it should save a correct image.

### Actual behaviour
App Crashes. Seems that there is no ExifIFD0Directory in the image, so you can't read it [here](https://github.com/lwansbrough/react-native-camera/blob/master/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraModule.java#L575). Probably the problem is that the third party library fails to read the exif: https://github.com/drewnoakes/metadata-extractor/issues/105.
@alwx you might be interested in this :)

### Environment
- **Node.js version**: `7.2`
- **React Native version**: `0.39.2`
- **React Native platform + platform version**: Galaxy S7, Android 6.0

### react-native-camera
**Version**: `master`

**Comment by wardnath** [comment]
Perhaps there could just be a check if the metadata exists, if not then just return the unaltered data

```

    private byte[] fixOrientation(byte[] data) {
        final Metadata metadata;
        try {
            metadata = ImageMetadataReader.readMetadata(
                    new BufferedInputStream(new ByteArrayInputStream(data)), data.length
            );

            final ExifIFD0Directory exifIFD0Directory = metadata.getFirstDirectoryOfType(ExifIFD0Directory.class);
            // return unaltered data if exifIFD0Directory is null 
            if (exifIFD0Directory == null) {
              return data;
            } else if (exifIFD0Directory.containsTag(ExifIFD0Directory.TAG_ORIENTATION)) {
                final int exifOrientation = exifIFD0Directory.getInt(ExifIFD0Directory.TAG_ORIENTATION);
                return rotate(data, exifOrientation);
            }
            return data;
        } catch (IOException | ImageProcessingException | MetadataException e) {
            e.printStackTrace();
            return data;
        }
    }
```

**Comment by npomfret** [comment]
@radko93 are you able to test my PR?  it may help with this https://github.com/lwansbrough/react-native-camera/pull/682

**Comment by ospfranco** [comment]
I see there is an open PR, I will close the ticket and review the PR later
