### ISSUE TITLE
Scan the qr code， How to continue to open the flash

### ISSUE THREAD

**Issue by usergyt** [react-native-community/react-native-camera#532]
### Steps to reproduce
Scan the qr code，flashMode Don't work

### Expected behaviour
Scan the qr code, open the flash

### Actual behaviour
 FlashMode doesn't work

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
