### ISSUE TITLE
Change name and storage directory

### ISSUE THREAD

**Issue by amanthegreatone** [react-native-community/react-native-camera#534]
Hi,

Is there anyway to change the name of the image and the directory where it is stored. For my app I would like to create a separate folder structure and organise images as per some naming conventions. I would also appreciate if someone can let me know how to delete these images from the phone on user input (Ideally a delete button when previewing the image).

regards
Aman Agarwal

**Comment by tobiaskiel** [comment]
This would be neat!

**Comment by xilonxiao** [comment]
Any news on this issue? I guess this is a pretty basic functionality, probably much more people would benefit of it.

**Comment by JordiGoPython** [comment]
Pleaseeee, it is basic.

**Comment by sibelius** [comment]
use https://github.com/itinance/react-native-fs to handle this
