### ISSUE TITLE
If not provide orientation prop then video record will fail

### ISSUE THREAD

**Issue by pepper** [react-native-community/react-native-camera#536]
### Steps to reproduce
1.
```
<Camera
    ref={(cam) => { this.camera = cam; }}
    captureTarget={Camera.constants.CaptureTarget.disk}
    captureMode={Camera.constants.CaptureMode.video}
    aspect={Camera.constants.Aspect.fill}
/>
```
2.
```
try {
    console.log('Start record');
    this.countdown();
    const result = await this.camera.capture({});
    console.log('Result', result);
} catch (err) {
    console.log(err);
}
```
3.
```
// Wait 5 sec and call
this.camera.stopCapture();
```

### Expected behaviour
Will save the video at disk and callback

### Actual behaviour
Both callback and file not exist...

But if I add `orientation={Camera.constants.Orientation.portrait}` to component every thing work great.

### Environment
- **Node.js version**: 6.6.0
- **React Native version**: 0.39.1
- **React Native platform + platform version**: Android 5.0

### react-native-camera
**Version**: "master"

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.
