### ISSUE TITLE
QR Code Scan is very slow in android

### ISSUE THREAD

**Issue by DVLNarayana** [react-native-community/react-native-camera#542]
bar code scanner is very slow in Android its better change the zxing lib to zbar lib.

### Expected behaviour
QR code scan should be very fast should not take more then 1 sec 

### Actual behaviour
QR code scan very slow in android

**Comment by ucfan** [comment]
+1

**Comment by xiaoleiooo** [comment]
+1

**Comment by JeroenNelen** [comment]
I have also noticed this, is there any quick fix?

**Comment by jqn** [comment]
Please view https://github.com/lwansbrough/react-native-camera/issues/664

**Comment by tmxdyf** [comment]
+1

**Comment by twelvescore** [comment]
+100

**Comment by kryst4l** [comment]
+10086

**Comment by lizhiren2016** [comment]
+1

**Comment by letitfly** [comment]
Wechat's QR code scanner is way faster. what lib does it use?

**Comment by srolija** [comment]
Given this still isn't fixed, after quite long research I finally settled for a solution to use this library for iOS and https://github.com/ekreutz/react-native-barcode-scanner-google for Android considering it is significantly faster and is based on Google Vision API.

So if someone is looking for a temporary solution I would recommend conditionally rendering each on different devices. Here is sample code how your component could look like to get the almost identical behavior.

```javascript
import Camera from 'react-native-camera';
import BarcodeScanner, { BarcodeType } from 'react-native-barcode-scanner-google';


const GenericCamera = ({ callback, torch = false }) => {
  if (Platform.OS === 'ios') {
    return (
      <Camera
        onBarCodeRead={(code) => {
          callback(code);
        }}
        barCodeTypes={[Camera.constants.BarCodeType.qr]}
        keepAwake
        style={{ flex: 1 }}
      />
    );
  }

  return (
    <BarcodeScanner
      style={{ flex: 1 }}
      barcodeType={BarcodeType.QR_CODE}
      onBarcodeRead={({ data }) => {
        callback(data);
      }}
    />
  );
};
```

**Comment by kryst4l** [comment]
thank you so much




发自网易邮箱大师
On 09/01/2017 09:22, Sergej Jakovljev wrote:

Given this still isn't fixed, after quite long research I finally settled for a solution to use this library for iOS and https://github.com/ekreutz/react-native-barcode-scanner-google for Android considering it is significantly faster and is based on Google Vision API.

So if someone is looking for a temporary solution I would recommend conditionally rendering each on different devices. Here is sample code how your component could look like to get the almost identical behavior.

importCamerafrom'react-native-camera';
importBarcodeScanner, { BarcodeType } from'react-native-barcode-scanner-google';


constGenericCamera= ({ callback, torch =false }) => {
  if (Platform.OS==='ios') {
    return (
      <Camera
        onBarCodeRead={(code) => {
          callback(code);
        }}
        barCodeTypes={[Camera.constants.BarCodeType.qr]}
        keepAwake
        style={{ flex:1 }}
      />
    );
  }

  return (
    <BarcodeScanner
      style={{ flex:1 }}
      barcodeType={BarcodeType.QR_CODE}
      onBarcodeRead={({ data }) => {
        callback(data);
      }}
    />
  );
};

**Comment by icesyc** [comment]
@srolija
it does not work for me. react-native@0.48
it cause error: 
com.ekreutz.barcodesanner.BarcodeSannerManager cannot be cast to com.facebook.react.uimanager.ViewGroupManager

**Comment by fenglu09** [comment]
@kryst4l   How did I got `react-native-barcode-scanner-google` on Chinese Mobile

**Comment by vivikenen** [comment]
+10086

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

P.S. There is a new implementation of the camera on android RNCamera, it is on the master branch, you can try it and see if it fixes your problem

**Comment by Concert0** [comment]
If anyone's still facing this problem, here's a workaround I discovered that you could use if you have the freedom to generate the Qr-codes. Try to make the codes a bit more complex until you see a small square appear the the low right corner.

**Hard to Scan**
![Hard to scan Qr](https://upload.wikimedia.org/wikipedia/commons/5/5b/Qr-1.png)

**Easy/Fast to Scan**
![Easy to scan Qr](https://upload.wikimedia.org/wikipedia/commons/2/2d/Qr-3.png)


The latter picture is not only easy/fast to scan, it also works when the scanned Qr and the scanner aren't completely parallel.

While this doesn't solve the issue on android(it works super fast on iOS), it's a workaround some people might want to use. I don't understand why it works, that's something I'll try later.

_Using master branch and RN 0.56_

**Comment by kigawas** [comment]
Hey guys, I found how to use google vision API with react-native-camera.

You can use `onGoogleVisionBarcodesDetected` like this:
```js
<RNCamera
    ref={ref => {
        this.camera = ref
    }}
    style={YOUR_STYLE_TO_SHOW_CAMERA_VIEW}
    type={RNCamera.Constants.Type.back}
    barCodeTypes={[RNCamera.Constants.BarCodeType.qr]}
    onGoogleVisionBarcodesDetected={
        (e) => {
            console.warn(e)
        }
    }
/>
```

**Comment by marlti7** [comment]
> Hey guys, I found how to use google vision API with react-native-camera.
> 
> You can set `onGoogleVisionBarcodesDetected` like this:
> 
> ```js
> <RNCamera
>     ref={ref => {
>         this.camera = ref
>     }}
>     style={YOUR_STYLE_TO_SHOW_CAMERA_VIEW}
>     type={RNCamera.Constants.Type.back}
>     barCodeTypes={[RNCamera.Constants.BarCodeType.qr]}
>     onGoogleVisionBarcodesDetected={
>         (e) => {
>             console.warn(e)
>         }
>     }
> />
> ```
> 
> Notice that `e` is different, it is like:
> 
> ```json
> {
>   "target": 127,
>   "barcodes": [
>     {
>       "type": "QR_CODE",
>       "data": "QRCODE 1"
>     },
>     {
>       "type": "QR_CODE",
>       "data": "QRCODE 2"
>     }
>   ],
>   "type": "barcode"
> }
> ```
> 
> UPDATE:
> You should not set both `onBarCodeRead` and `onGoogleVisionBarcodesDetected`, if you do this, `onGoogleVisionBarcodesDetected` will not be called and scanning cannot be fast. It is necessary to do like this inside the `constructor`:
> 
> ```js
> this.cameraAttrs = {
>     // some common attrs
> }
> if (Platform.OS === 'ios') {
>     this.cameraAttrs.onBarCodeRead = ({ data }) => {
>         this.callback(data)
>     }
> } else {
>     this.cameraAttrs.onGoogleVisionBarcodesDetected = ({ barcodes }) => {
>         this.callback(barcodes[0].data)
>     }
> }
> ```
> 
> And return something containing `<RNCamera {...this.cameraAttrs} />` in `render`.

but Android defaultConfig {
    ...
    missingDimensionStrategy 'react-native-camera', 'mlkit' // <--- replace general with mlkit
  }
