### ISSUE TITLE
Barcode Supplements

### ISSUE THREAD

**Issue by jswaldon** [react-native-community/react-native-camera#545]
I cant get the barcode scanning to recognize supplementals, e.g. EAN13 +2/3/5. Is there any additional config to get this to work or is it just not supported?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

P.S. There is a new implementation of the camera on android RNCamera, it is on the master branch, you can try it and see if it fixes your problem
