### ISSUE TITLE
Any interest in inverse barcode scanning?

### ISSUE THREAD

**Issue by robwalkerco** [react-native-community/react-native-camera#554]
Hi everyone,

I'm planning on forking and adding support for Inverse barcode scanning for us in one of our apps.

Has anyone tried this already?
Would their be any interest if I created a PR to enable an inverse scanning mode?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

P.S. There is a new implementation of the camera on android RNCamera, it is on the master branch, you can try it and see if it fixes your problem
