### ISSUE TITLE
Exception thrown from Xcode when barCodeTypes is set as an array

### ISSUE THREAD

**Issue by alexmngn** [react-native-community/react-native-camera#557]
### Steps to reproduce
1. Set the property:  `barCodeTypes={['ean13', 'ean8', 'upce']}`
2. Run the app

This is how my component looks like:
```
<Camera
	aspect={Camera.constants.Aspect.fill}
	style={styles.camera}
	torchMode={this.state.torch}
	onBarCodeRead={data => this.onBarCodeRead(data)}
	barCodeTypes={['ean13', 'ean8', 'upce']}
>
```
### Expected behaviour
Camera should launch

### Actual behaviour

Camera doesn't start, getting this exception:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureMetadataOutput setMetadataObjectTypes:] Unsupported type found - use -availableMetadataObjectTypes'
*** First throw call stack:
(0x186e211b8 0x18585855c 0x18e662a48 0x1001f9a88 0x100431258 0x100431218 0x10043eaec 0x100434ce0 0x10043f088 0x100440e2c 0x100440b78 0x185eb32a0 0x185eb2d8c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

<img width="910" alt="screen shot 2017-01-17 at 17 43 01" src="https://cloud.githubusercontent.com/assets/4203845/22017320/6e6d0df2-dcdc-11e6-9495-5127a883f00e.png">

### Environment
- **Node.js version**: v6.0.0
- **React Native version**: 0.39
- **React Native platform + platform version**: iOS 10

### react-native-camera
**Version**: 0.4.0

**Comment by jarredszabadi** [comment]
also experiencing this issue

**Comment by alexmngn** [comment]
Found out looking at the code that the type must be coming from the `Camera.constants` object.  Would be great if it was in the doc.

```
barCodeTypes={[
	Camera.constants.BarCodeType.upce,
	Camera.constants.BarCodeType.ean8,
	Camera.constants.BarCodeType.ean13,
]}
```

**Comment by grundmanise** [comment]
Same error:
iOS 10.2
iPhone 5s
`barCodeTypes={['qr']}`

**Comment by dmarcucci** [comment]
@grundmanise See @alexmngn's reply. That seems to have fixed the problem for me. Thanks @alexmngn.

+1 for this to be included in the documentation.

**Comment by grundmanise** [comment]
Thanks, that works! I overlooked his reply.

**Comment by dmarcucci** [comment]
Just FYI - For Android, it expects a `List<String>`. I just set it based on `Platform` to account for this.

Example:
`barCodeTypes={(Platform.OS === 'ios') ? [Camera.constants.BarCodeType.ean13] : ['ean13']}`

You'll need to import `Platform` from `react-native` for this solution.

**Comment by grundmanise** [comment]
@dmarcucci Thanks! I also use it like this:

`barCodeTypes={(Platform.OS === 'android') ? ['QR_CODE'] : [Camera.constants.BarCodeType.qr] }`

**Comment by dmarcucci** [comment]
@grundmanise Yes. Obviously, you can either do the check for either `ios` or `android` and then set what you need accordingly. I'm only using this for EAN-13, so that's why I have that value there.

**Comment by alexdunae** [comment]
Same as:
- https://github.com/lwansbrough/react-native-camera/issues/600
- https://github.com/lwansbrough/react-native-camera/issues/652
- https://github.com/lwansbrough/react-native-camera/issues/499
- https://github.com/lwansbrough/react-native-camera/issues/296

**Comment by iegik** [comment]
On `0.10.0` `BarCodeType.qr` will work
https://github.com/lwansbrough/react-native-camera/commit/9162879305aa801bce77a01c4469958fd50d7807

**Comment by vvakame** [comment]
I would be happy if this issue write into document. 😉 
It is a problem we can avoid if we know it.

**Comment by iegik** [comment]
@vvakame, done

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

P.S. There is a new implementation of the camera on android RNCamera, it is on the master branch, you can try it and see if it fixes your problem
