### ISSUE TITLE
Support For WebM

### ISSUE THREAD

**Issue by varun-raj** [react-native-community/react-native-camera#561]
By any chance this allows me to save videos in Google's WebM format? also is there any ways that I can use FFMPEG to have custom formatting options?

**Comment by asimolmez** [comment]
Varun Raj <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (21 Oca 2017 12:05):


By any chance this allows me to save videos in Google's WebM format? also is there any ways that I can use FFMPEG to have custom formatting options?

**Comment by ospfranco** [comment]
Hey! this repository was recently transferred to the react-native-community, as part of our ongoing cleaning process we are closing old tickets (there is just too many of them!), please feel free to try the latest versions or the master branch to see if your problem has been solved.

If you are still experiencing this problem feel free to re-open this or fill a new ticket.

P.S. There is a new implementation of the camera on android RNCamera, it is on the master branch, you can try it and see if it fixes your problem
