### ISSUE TITLE
App stops when I try to capture an image.

### ISSUE THREAD

**Issue by hudjoubert** [react-native-community/react-native-camera#566]
### Steps to reproduce
1.Open Camera App
2.Try to capture image
3.

### Expected behaviour
The app should take a picture and console log the result.

### Actual behaviour
The App stop and close when a take a picture
### Environment
- **Node.js version**:latest
- **React Native version**: latest
- **React Native platform + platform version**: Android 5.0, 6.0, 7.0

### react-native-camera
**Version**: npm version

**Comment by juanluisgv1** [comment]
Does this happen on Android or iOS or both? I'm facing a similar issue with a "Samsung Galaxy S5 Neo". I'm able to see the camera view but when I take the picture it breaks. On the other hand, it works if I use the front camera and also if I use any other phone (iphone, htc or whatever else).. any idea?

**Comment by hudjoubert** [comment]
I managed to make it work on my device (sansung S5), using the front camera, I just added the captureTarget property, but the simulator did not work. As you said now from the other camera I will test here.

**Comment by hudjoubert** [comment]
I trying here right now and a I had the same problem. So I dont Know what to do .

**Comment by juanluisgv1** [comment]
I must say that it only happens with the Samsung S5. I will research but you don't get any information at all why it breaks...

**Comment by jlyons** [comment]
Had this same problem the other day and fixed it by changing quality to 1080p, instead of the default "high".  Seems to be an issue with handing the default, which i assume is why the front camera has no problem.

**Comment by juanluisgv1** [comment]
@jlyons you were right! Changing the captureQuality attribute to 1080p or lower it solves the problem 👌🏻

**Comment by hudjoubert** [comment]
@jlyons  I was cracking my head trying to know why, thanks for the help

**Comment by zawarudo** [comment]
Can confirm this issue on my iPhone 5.

@juanluisgv1 Unfortunately playing with the captureQuality did not fix it for me. Front camera is not even accessible, it shows only black.

**Environment**
Node 7.4.0
React Native 4.0

**Comment by velozmontero** [comment]
Im having the same issue with a samsung galaxy s5. The app crashes every time I take a picture with back camera but works fine with front camera. I tried reducing the capture quality but that didn't work for me.

**Comment by MiLeung** [comment]
@zawarudo works for me! thanks!

**Comment by logileifs** [comment]
I was having the same problem and managed to fix it by adding `android:largeHeap="true"` to my AndroidManifest.xml.

```
<application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme"
      android:largeHeap="true">
```

**Comment by logileifs** [comment]
Problem seems to be in the `fixOrientation` method, when set to a high capture quality the device runs out of memory and crashes.

**Comment by npomfret** [comment]
Have you tried master?  afixOrientation` isn't applied any more (unless you explicitly specify it).  I understand that using `android:largeHeap="true"` isn't recommended (although I can't remember why).

**Comment by logileifs** [comment]
I installed the version for RN >0.40. I believe it's version 0.6 and it was still happening there. I'd rather reserve a large heap for my app (although someone does not recommend it) than have it crash

**Comment by rishimukherjee** [comment]
I am using OnePlus 3 with Android 7.1.1. None of these work for me. Works fine in Zenfone 2 and iPhone 7 plus though.

**Comment by heliocaruccio** [comment]
<key>NSPhotoLibrary**Add**UsageDescription</key>

**Comment by jifromz** [comment]
@heliocaruccio - Works for me. Many thanks!

**Comment by BonnieMilian** [comment]
I have the same issue, but just on the release apk, on the debugging works perfect, but release is the important one.

```
<Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          style={styles.preview}
          aspect={Camera.constants.Aspect.fill}
          captureQuality={Camera.constants.CaptureQuality["480p"]}
          type={Camera.constants.Type.front}>
          <TouchableOpacity
              style={styles.captureButton}
              onPress={this.takePicture.bind(this)}
          >
            {imgCamera}
          </TouchableOpacity>
        </Camera>
```

```
takePicture() {
    const options = {jpegQuality: 1};
    this.camera.capture({metadata: options})
      .then((data) => {
        //console.log(data);
        this.props.navigation.navigate('DrawRectangle',
          {
            pictureData: data
          }
        );
      })
      .catch(err => console.error(err));
  }
```
The application requires low quality picture.

**Comment by vygandas** [comment]
I'm using RNCamera like this
```
takePicture = async () => {
        const options: TakePictureOptions = {
            // quality: 0.9,
            base64: true,
            exif: false,
            // width?: number;
            // mirrorImage?: boolean;

            /** Android only */
            // skipProcessing?: boolean;
            /** Android only */
            fixOrientation: true,

            /** iOS only */
            forceUpOrientation: false
        };
        this.camera.takePictureAsync(options)
            .then(data => console.log(data.base64))
            .catch(error => console.log(error));
    };
render() {
        return (
            <View style={styles.container}>
                <RNCamera
                    ref={cam => {
                        this.camera = (cam as RNCamera);
                    }}
                    style={styles.preview}
                    type={RNCamera.Constants.Type.back}
                >
                    <TouchableHighlight onPress={this.takePicture}>
                        <Image
                            style={{ flex: 0, width: 100, height: 100 }}
                            source={require('./images/cameraButton.png')}
                        />
                    </TouchableHighlight>
                </RNCamera>
            </View>
        );
    }
```

when `type={RNCamera.Constants.Type.front}` it works. If I use `back` it fails. App closes and says "Unfortunately app has stopped....."

I've added things to manifest like exif 27+, android:largeHeap="true" and other things but it doesn't help.

**Comment by n1ru4l** [comment]
Please open a new issue with crashlogs if you still experience this issue with the newest version and `RNCamera`.
