### ISSUE TITLE
[Android] Battery drain issue 

### ISSUE THREAD

**Issue by kevinnguy** [react-native-community/react-native-camera#569]
Has anyone come across having a battery issue on their Android devices? When I'm using the camera for an extended period of time (10-30 minutes), my battery drains unexpectedly fast. I'm using the camera to scan barcodes and was wondering if there are any ways of improving camera/battery performance. Thanks!

### Environment
- **Node.js version**: 3.10.10
- **React Native version**: 0.40
- **React Native platform + platform version**: Android 5.0 >

### react-native-camera
**Version**: 0.5.1

**Comment by cfournel** [comment]
As mentionned in https://github.com/lwansbrough/react-native-camera/issues/460 , the only way is to turn off camera by not displaying the view.

**Comment by enieber** [comment]
@sibelius  this issue can it is being closed?
