### ISSUE TITLE
[Feature] Add real-time options to camera

### ISSUE THREAD

**Issue by kresic-ivan-nsoft** [react-native-community/react-native-camera#571]
Hi guys,

would it be possible to add real-time options for camera controls, triggering the flash, switch to front camera or similar?

**Comment by tobiaskiel** [comment]
It already is
` <Camera ref={(cam) => { this.camera = cam; } }
          style={styles.preview}
          type={this.state.cameraType}
          captureQuality={this.state.quality}
          torchMode={this.state.torchOn}
          aspect={Camera.constants.Aspect.fill}
          captureTarget={Camera.constants.CaptureTarget.cameraRoll }
        >`
Then just update required state for toggeling options like, type and torchMode

**Comment by kresic-ivan-nsoft** [comment]
Great, thanks for the tip! Any way to apply filters to the camera view (black & white for example)?

**Comment by hedgerh** [comment]
@kresic-ivan-nsoft: ooh, itd be awesome to be able to apply filters.  you can do it with images pretty easily, but filtering the live preview from the `<Camera>` component could be tricky.  for info about filters, check something like this out https://www.npmjs.com/package/image-filter-core

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
