### ISSUE TITLE
Autofocus does not work without onFocusChanged handler

### ISSUE THREAD

**Issue by grundmanise** [react-native-community/react-native-camera#579]
Hello,
first I want to thank for such a great component!

Issue:

Autofocus does not work without `onFocusChanged` handler. I think that `Autofocus` should not depend on `tap to focus` functionality.
Also when using `tap to focus` functionality Autofocus disables after `tap to focus` event occurs.

Plastform: iOS
Device: iPhone 5s
OS: 10.2

**Comment by ghensley** [comment]
It really doesn't make sense that it works like this.

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
