### ISSUE TITLE
Answer - save in ios album

### ISSUE THREAD

**Issue by sirgalleto** [react-native-community/react-native-camera#580]
With this library can I save the videos in a specific album? 

If this feature is not in the code please show me where is the method and maybe I can update that and make the PR

**Comment by npomfret** [comment]
You could use this https://github.com/olofd/react-native-photos-framework/tree/v1.0.4 to move the image after its saved to disk.

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
