### ISSUE TITLE
Camera randomly has incorrect orientation

### ISSUE THREAD

**Issue by RuairiOliver** [react-native-community/react-native-camera#581]
**Steps to reproduce**
Display camera in landscape mode. All displays fine.
Capture a photo and change state on the view

**Expected behaviour**
I can take another photo with the same orientation

**Actual behaviour**
At random times the image displays in portrait while I'm taking the photo. Eventually it corrects itself. Setting a fixed orientation doesn't help and using the front or back camera on the iPhone has the same problem.

Using latest version of react-native-camera(0.6) and on version 0.4 of React Native.
This was happening on the previous version of this library and react native though.

**Comment by Marthyn** [comment]
I have had reports of the same.

**Comment by kaifaust** [comment]
We're experiencing the same problem: iPad Air 2 in landscape mode. It displays the wrong orientation 30% of the time and it fixes itself in 10-12 seconds after initialization every time. Very strange behavior. We're having to implement a hack to mount — and keep mounted — the camera only once in the background during the use of the app. This is obviously problematic, but until there's an Objective-C angel out there who commits a fix, this will have to do.

**Comment by hugohow** [comment]
Ok I get the exact same problem, I will try your solution ;)

**Comment by RuairiOliver** [comment]
To solve it in the end I changed to a new view to display the picture I took. Then changed to the view that held the camera component again if I needed to take another photo. Works fine without changing state. 

Also I'm keeping it fixed on the front camera, turned off the option to flip.

**Comment by RazerTang** [comment]
Have you  solved this problem? @hugohow

**Comment by hugohow** [comment]
Yep @RazerTang the method of @kaifaust works. It's a lot of changes in the code, but it works.

**Comment by instancewoo** [comment]
in RCTCameraManager.m
- (id)init{
//.... do the following modification
  self.sessionQueue = dispatch_get_main_queue();
            //dispatch_queue_create("cameraManagerQueue", DISPATCH_QUEUE_SERIAL);
}

**Comment by craigcoles** [comment]
I have been testing the fix that @instancewoo suggested and it seems to stop issues occurring. Would this be a viable solution going forward?

**Comment by lakhman** [comment]
@instancewoo's fix works for me also, i'm on latest master of RNC. +1 Merge to help others.

**Comment by mik4el** [comment]
@instancewoo thanks, solves my problem as well

**Comment by ffiargus** [comment]
@instancewoo's fix solves the problem, but now the screen with camera component is slower to navigate too, any solutions?

**Comment by Rewieer** [comment]
The same problem also occurs in Android.

**Comment by Nauzer** [comment]
Anyone has found a fix for this issue on RNCamera?

**Comment by Progoogler** [comment]
Have you tried `takePictureAsync({forceUpOrientation: true, fixOrientation: true})`?

**Comment by eliaahadi** [comment]
@Progoogler I tried that and it still rotates incorrectly. Any other suggestions?

**Comment by mgela** [comment]
@Friendly-Robot thanks, worked for me.

**Comment by SimonErm** [comment]
Can you try if it is fixed with master?

**Comment by n1ru4l** [comment]
Closed during to missing feedback.
