### ISSUE TITLE
SubView are persisting after transition and camera disappear when going back.

### ISSUE THREAD

**Issue by Deevent** [react-native-community/react-native-camera#591]
Hello,

I'm trying to transition from a view with a camera to another also with a camera. When I push my new screen, the subviews of my first camera are showing up in my second one. And when I go back to my initial screen, there's no more camera.

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/16573898/22734095/ca31d40a-edf4-11e6-8dd5-7a8a7c1a5d15.gif)

**Comment by ptomasroos** [comment]
Can you create a repo to reproduce this and I will happily take a look at it

**Comment by Deevent** [comment]
Of course ! I created this repo containing my project : https://github.com/Deevent/curly-winner

Thanks for helping !

**Comment by jamuhl** [comment]
@Deevent you found a solution for this? we run into the same issue...

**Comment by Deevent** [comment]
@jamuhl No still not, I've tried to render null before my transition but the issue is still there. I'm planning to create my own native module (that just displays a camera background) if I don't find a solution by the end of my project.

**Comment by chillu** [comment]
Just hit this as well. The [example](https://github.com/lwansbrough/react-native-camera/blob/master/Example/Example.js#L176) doesn't nest components, but rather uses overlays

**Comment by danyflorez** [comment]
Did you find a solution for your problem?

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
