### ISSUE TITLE
React/RCTBridge.h not found

### ISSUE THREAD

**Issue by pcooper1979** [react-native-community/react-native-camera#592]
I've gone through the installation steps and when trying to compile the standard project I get this error, the header search paths are configured as per the installation instructions.

Any idea why?

**Comment by ptomasroos** [comment]
Which version of react-native are you running ?

**Comment by pcooper1979** [comment]
Version 0.38.0

**Comment by h124551753** [comment]
i also meet this problem afer running 'npm install'.
my react-native version: 0.38.0

**Comment by ptomasroos** [comment]
You need to upgrade to rn 0.40 and above in order to use packages containing the namespaces React/*.h

**Comment by cgotcu** [comment]
I am running with 0.40 (and react 15.4.0) and am just trying to get the Example going but have the same issue as above. I tried a bunch of stuff others have suggested with the same issue:
- removed node_modules and did a fresh npm
- changed the HEADER_SEARCH_PATHS setting to remove react and react-native
- tried both react-native run-ios and XCode for building/running
Any additional thoughts?

**Comment by mediavrog** [comment]
+1 running into the same issue as @cgotcu

**Comment by eqyiel** [comment]
Related #692

**Comment by DerJacques** [comment]
I'm also experiencing this issue on a freshly detached Expo app. However, installing using Pod works fine.

**Comment by harrisrobin** [comment]
Also experiencing this.

**Comment by sibelius** [comment]
fixed on master
