### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by bosung90** [react-native-community/react-native-camera#597]
### Steps to reproduce
1. clone repo
2. npm install inside Example folder
3. react-native run-android

### Expected behaviour
Example app should work

### Actual behaviour
App crashes with error

### Environment
- **Node.js version**:
7.5.0
- **React Native version**:
0.34.0 (This is what Example project comes in)
- **React Native platform + platform version**: Android 6.0.1

### react-native-camera
**Version**: master 65f7903

**Comment by matthewford** [comment]
anyone else get the example to work with the expo app?

**Comment by bkotos** [comment]
Went through the same steps, in addition to running `react-native link react-native-camera`, and it still doesn't work.  It just crashes and the app exits with no error.

**Comment by jannevickholm** [comment]
I have the same problem with Expo. Just says `undefined is not an object` and crashes.

**Comment by bkotos** [comment]
I followed this tutorial and I was able to get `react-native-camera` to work: https://www.youtube.com/watch?v=pJseuSOC8HA

**Comment by itinance** [comment]
`react-native run-ios` gives 

> Print: Entry, ":CFBundleIdentifier", Does Not Exist

although there is a bundle identifier.

**Comment by eqyiel** [comment]
@itinance does this PR fix it for you? #692

**Comment by skovhus** [comment]
Related: https://github.com/lwansbrough/react-native-camera/issues/827

**Comment by LeBlaaanc** [comment]
I'm still getting
```
.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/Example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

```

**Comment by LeBlaaanc** [comment]
I get something even more obnoxious when trying to run it in Xcode. 
![image](https://user-images.githubusercontent.com/2807897/34456341-6906b776-ed59-11e7-83cc-caa642d363de.png)

**Comment by sibelius** [comment]
This does not work with expo, does anybody want to upgrade the example to latest React native version?

**Comment by sibelius** [comment]
fixed on master
