### ISSUE TITLE
[Android] PDF417 cannot be read when barcode is parallel to the phone screen

### ISSUE THREAD

**Issue by bosung90** [react-native-community/react-native-camera#599]
### Steps to reproduce
1. react-native init AppName
2. npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save
3. react-native link react-native-camera
4. Add onBarCodeRead and barCodeTypes to Camera as props
```
onBarCodeRead={(data) => {
                alert(data.data)
              }}
              barCodeTypes={['pdf417']}
```

### Expected behaviour
PDF417 should be read successfully regardless of rather phone is parallel or perpendicular to the barcode

### Actual behaviour
PDF417 barcode is only successfully read when the barcode is perpendicular to the phone.

### Environment
- **Node.js version**: 7.5.0
- **React Native version**: 0.41.2
- **React Native platform + platform version**: Android 6.0.1

### react-native-camera
**Version**: master 65f7903

in iOS reading barcode in any direction works fine

**Comment by semiautomatix** [comment]
I'm having a similar problem where the barcode isn't being read in landscape view - only portrait.

**Comment by augusto-altman** [comment]
Facing the same issue here, any news on this?

**Comment by SimonErm** [comment]
Does this issue still occure with RNCamera?

**Comment by syadykin** [comment]
This might fix this issue: https://github.com/react-native-community/react-native-camera/pull/1994

**Comment by sibelius** [comment]
test on master
