### ISSUE TITLE
Expected barCodeTypes is different in iOS and Android

### ISSUE THREAD

**Issue by bosung90** [react-native-community/react-native-camera#600]
### Steps to reproduce
1. react-native init AppName
2. npm install react-native-camera@https://github.com/lwansbrough/react-native-camera.git --save
3. react-native link react-native-camera
4. Add onBarCodeRead and barCodeTypes to Camera as props
```
onBarCodeRead={(data) => {
                alert(data.data)
              }}
              barCodeTypes={['pdf417']}
```

### Expected behaviour
iOS App should start with camera view

### Actual behaviour
iOS App crashes
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureMetadataOutput setMetadataObjectTypes:] Unsupported type found - use -availableMetadataObjectTypes'
```

### Environment
- **Node.js version**: 7.5.0
- **React Native version**: 0.41.2
- **React Native platform + platform version**: iPhone 5S iOS 10.2.1

### react-native-camera
**Version**: master 65f7903

Note that this only happens in iOS and works fine in Android

------------------------------------------------------------
Just found out that in iOS the type must be 'org.iso.PDF417'

**Comment by Maftalion** [comment]
You cant pass it as a string, it would have to be like this:
`[Camera.constants.BarCodeType.pdf417]`

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
