### ISSUE TITLE
NSPhotoLibraryUsageDescription is required even if Photo library is not used

### ISSUE THREAD

**Issue by abcd-ca** [react-native-community/react-native-camera#602]
### Steps to reproduce
1. Configure Camera plugin to save to tmp or documents folder (not camera roll)
2. Upload app to app store

### Expected behaviour
I shouldn't need `NSPhotoLibraryUsageDescription` because I'm not storing the photos in the camera roll and don't iOS to prompt the user to explain why I need access to their photo library when I'm not even using it.

### Actual behaviour
App store sends a rejection email about missing `NSPhotoLibraryUsageDescription` in Info.plist.

### Version
Re: react-native-camera v0.6.0

**Comment by janziemba** [comment]
You need to add all permission keys to Info.plist, even if you don't use them. See: https://github.com/yonahforst/react-native-permissions#app-store-submission-disclaimer
