### ISSUE TITLE
The photo preview

### ISSUE THREAD

**Issue by wq13718048209** [react-native-community/react-native-camera#603]
Author: 
           hello, I want to click on the camera, screen display photos of images on the current interface directly, also is the effect of preview, I can now achieve is the photo of the data to the next screen, display, but not like a regular camera in the current page, could you tell me how to do?Which attributes can be achieved or is it?

**Comment by Deboracgs** [comment]
i need this.

**Comment by pr-rojan** [comment]
I think this is what you are looking for
https://github.com/spencercarli/react-native-snapchat-clone/blob/master/app/routes/Camera.js

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
