### ISSUE TITLE
Lack of Metadata returned on saving Pictures/Videos

### ISSUE THREAD

**Issue by blaziken105** [react-native-community/react-native-camera#605]
I have noticed that after taking a pic/video only the path to the saved directory is returned. It would be great if other metadata such as the URI, height, width etc.. could be returned. Something like what react-native-image-picker does. Is there any existing mechanism to get the metadata of the saved file from the path without the user explicitly clicking on it? Or would such a module have to be developed from scratch?

I am using the following versions: 
"react": "15.4.2",
"react-native": "0.41.2",
"react-native-camera": 0.6.0

**Comment by npomfret** [comment]
This PR will add a 2nd field which is the `mediaUri` of the image: https://github.com/lwansbrough/react-native-camera/pull/637

I'll look at adding more fields soon.

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
