### ISSUE TITLE
AlertIOS/Alert will not let Camera render on iOS. No errors, camera just doesn't show up

### ISSUE THREAD

**Issue by ykcai** [react-native-community/react-native-camera#606]
### Steps to reproduce
1. Create a Alert Dialog before/after/during rendering
2. Render the camera
3. Only alert shows, camera does not show

### Expected behaviour
Camera will show up behind the dialog
### Actual behaviour
only the dialog shows up
### Environment
- **Node.js version**: 7.4.0
- **React Native version**: 0.40
- **React Native platform + platform version**: iOS 10.0

### react-native-camera
**Version**: release 0.6

**Comment by manishtpatel** [comment]
It is normal react-native behaviour, will happen with any render if alert is blocking a render. You need to post render events to alert.

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
