### ISSUE TITLE
Camera Resolution vs Screen Resolution vs Ouput Resolution

### ISSUE THREAD

**Issue by RZulfikri** [react-native-community/react-native-camera#610]
Does anyone have some solution ? i have problem with the output of Video. i'm trying record video using this component but. It give me different output from record screen. 

The case is, when i record my laptop. it fit the screen. But the result it not fit the screen, the camera record more then  laptop width in record screen. 

| My Record screen | Ouput video |
| ----- | ----- |
| ![screenshot_2017-02-22-11-14-12](https://cloud.githubusercontent.com/assets/24998199/23197096/6ce042c6-f8f0-11e6-953a-2d885bb2de6d.png) |  ![screenshot_2017-02-22-11-14-37](https://cloud.githubusercontent.com/assets/24998199/23197107/7fcea6d4-f8f0-11e6-83d3-d0d5b4f85b1e.png) |

my record quality.
captureQuality : Camera.constants.CaptureQuality["720"]

i guess, it because phone dimension, so check Dimension of my screen. the output is (using Dimension.get('window') :
screen width : 360
screen height : 592

And i when i try using default camera apps, it give different output too.
Phone spec :
Android version : 6.0
Phone : Coolpad E502

Thanks

**Comment by diegocouto** [comment]
Hi, @RZulfikri!

It's probably a typo when you posted it here, but I noticed that you might be using the wrong constant name:

You seems to be using:
`Camera.constants.CaptureQuality['720']`

But the right is:
`Camera.constants.CaptureQuality['720p']`

This is a complete example:

```
<Camera
  ref='camera'
  type={this.state.captureType}
  captureQuality={Camera.constants.CaptureQuality['720p']}
  aspect={Camera.constants.Aspect.fill}>
  ...
</Camera>
```

Hope it helps! 😄

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
