### ISSUE TITLE
Barcode only scans at center of View

### ISSUE THREAD

**Issue by Maftalion** [react-native-community/react-native-camera#611]
### Steps to reproduce
1. Point camera to a code39 barcode.

### Expected behaviour
It should be able to read the barcode anywhere in the Camera's view.

### Actual behaviour
It only reads the barcode if exactly centered in the Camera view.

### Environment
- **Node.js version: 7.1**:
- **React Native version: 0.39.2,**:
- **React Native platform + platform version: iOS 10.2**: iOS 9.0, Android 5.0, etc

### react-native-camera
**Version: 0.4.1**: npm version or "master"

**Comment by melihmucuk** [comment]
any news ?

**Comment by Maftalion** [comment]
nope, not sure why it's only scanning at the center and I wasn't able to find a workaround either.

**Comment by E-P1983** [comment]
Same here. Help!

**Comment by averypfeiffer** [comment]
Anyone have any luck? Is there anyway to manually trigger a scan? The "auto-detection" detects the same barcode like twenty different times

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.

**Comment by ntk0104** [comment]
Hi guys, any news?
