### ISSUE TITLE
White screen if camera type doesn't exist

### ISSUE THREAD

**Issue by TrekSoft** [react-native-community/react-native-camera#612]
### Steps to reproduce
Run the app on an emulator or device with no rear facing camera and **type** attribute set or defaulted to Camera.constants.Type.back

### Expected behaviour
Should automatically switch to the front camera or a method should be provided to check if the back camera exists so that the proper camera can be set.

### Actual behaviour
A white screen shows and there's no way to tell if there is a back facing camera on the device until you call capture()

### Environment
Latest everything

### react-native-camera
**Version**: 0.60

**Comment by beeglebug** [comment]
Is there any way to check if the device has a camera at all?

**Comment by npomfret** [comment]
Not in this api yet, but you can do it natively (and would be a welcome PR!).  It wouldn't be required on iOS I guess.

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
