### ISSUE TITLE
question: clear exemple to store gps location in image 

### ISSUE THREAD

**Issue by smolleyes** [react-native-community/react-native-camera#616]
hi

first, thanks for this module

i spend 2 hours trying everything but i can t  get the location stored in my images (android, testing from real phone)

no way to add a clear exemple to do this (if it s possible..) ?

thanks!

**Comment by joshuapinter** [comment]
@smolleyes Would love to have this as well. Did you find out how to do it? Thanks!

**Comment by npomfret** [comment]
hi - i've submitted a PR which I think fixes this on iOS (android to follow).

The way to use it is to something like:

  async _takePicture() {
      const options = {};
      if (this.state.position) {
        // position comes from: navigator.geolocation.watchPosition((position) => this.setState({position}))
        options.location = this.state.position;
      }
      const data = await this._camera.capture(options);
  }


Then when you use RN CameraRoll to retrieve the image it has the location info attached.  I'm looking for someone to help test my PR.  If you have any time it would be appreciated.

https://github.com/lwansbrough/react-native-camera/pull/635

**Comment by koswarabilly** [comment]
@npomfret 
i have this code in my project

```
takePicture() {
    const options = {};
    options.location = this.state.location;
    this.camera.capture({ metadata: options })
      .then((data) => console.log(data))
      .catch(err => console.error(err));
  }
```
everytime i press capture the application stop working

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
