### ISSUE TITLE
onBarCodeRead "bounds"

### ISSUE THREAD

**Issue by semo94** [react-native-community/react-native-camera#621]
## Expected behaviour
onBarCodeRead event listener object should contains"bounds" property

### Actual behaviour
it's just contain "type" and "data" without "bounds"

### Environment
- **Node.js version*4.1.2*:
- **React Native version*0.42.0*:
- **React Native platform + platform version**: Android 6.0

### react-native-camera
**Version*0.6.0*: npm version or "master"

**Comment by marszall87** [comment]
I have the same problem, but running on Android 7.1.2 and Node 7.5.0 (same `react-native` and `react-native-camera`).

**Comment by MocanuMarius** [comment]
@marszall87 @semo94  Hi , please look at my solution for this and the fork . https://github.com/lwansbrough/react-native-camera/issues/683

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
