### ISSUE TITLE
Question: Camera flicker when rendering subviews?

### ISSUE THREAD

**Issue by IvyKun** [react-native-community/react-native-camera#628]
Hi,

I'm trying to have a camera button that shows a dialog to select some camera options, but showing that dialog interrupt the camera image creating a flickering. Not sure if it's a limitation on the number of subviews or I'm doing the render of the subviews wrong.

For example I have a button to select the flash mode that change the value and the icon on a subview and that render doesn't interrupt the camera image.

I have trying simplifying it to just show one subview and even that interrupts the image. The image only flickers when I open the subview, when I close it that is the same render but without the subview then everything is fine, so I'm pretty sure the problem is just rendering that one more subview.

Example of the button that interrupts the camera image:

*****
`export class TimerButton extends Component {
  
  constructor(props) {
    super(props);

    this.state = { 
      dialogOpened: false
    };

    this.openDialog = this.openDialog.bind(this);
    this.setTimer = this.setTimer.bind(this);
  }
  
  openDialog()
  {
     this.setState({
      dialogOpened: !this.state.dialogOpened
    });
  }

  setTimer(time)
    {
      this.setState({
        dialogOpened: false
      });
      
      this.props.onPress(time * 1000);
    }

  renderSubView() {
 {/**** Rendering this is what makes the image flicker *****/}
      if (this.state.dialogOpened) {
          return (
            <View >
               <TouchableOpacity onPress={() => this.setTimer(3)}>
                  <Text >3 secs</Text>
              </TouchableOpacity>
            </View>  
          );
      } else {
          return null;
      }
  }

  render() {
    return (
          <View>
            <TouchableOpacity onPress={this.openDialog} style={styles.smallTopRowButton} >
              <Image source={require('./img/timer.png')} style={styles.smallTopRowButtonImage} />
               <Text style = {styles.smallTopRowButtonText}>
                  {this.props.timer}
                </Text>
            </TouchableOpacity>
            {this.renderSubView()}
         </View>
    )
  }
}`

**********

My main view with the camera and the TimerButton component:

**********
`<View style={styles.container}>
        <Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          type={this.state.cameraUsed}
          aspect={Camera.constants.Aspect.fill}
          flashMode={this.state.flash}
          captureTarget={Camera.constants.CaptureTarget.cameraRoll} 
          style={styles.preview}>
            <View style={styles.optionsRow}>
              <FlashButton flash={this.state.flash} onPress={this.setFlashMode} />
              <TimerButton timer={this.state.timer}  onPress={this.setTimer} />
            </View>
            <View style={styles.shootRow}>
              <ShootButton onPress={this.shoot} />
            </View>
        </Camera>
      </View>`
**********

Example of the button that just change itself and doesn't interrupt the camera image:

**********
`export class FlashButton extends Component {
  
  constructor(props) {
    super(props);
  }
  
  renderFlashMode() {
      switch(this.props.flash)
      {
        case 2:
          return ('Auto');
          break;
        case 1:
           return ('On');
          break;
        case 0:
           return ('Off');
          break;
        default:
           return '';
          break;
      }
  }

  renderFlashImage() {
      switch(this.props.flash)
      {
        case 2:
          return require('./img/flash_on.png');
          break;
        case 1:
           return require('./img/flash_on.png');
          break;
        case 0:
           return require('./img/flash_off.png');
          break;
        default:
           return require('./img/flash_on.png');
          break;
      }
  }

  render() {
    return (
         <TouchableOpacity onPress={this.props.onPress} style={styles.smallTopRowButton} >
            <Image source={this.renderFlashImage()} style={styles.smallTopRowButtonImage} />
            <Text style = {styles.smallTopRowButtonText}>
               {this.renderFlashMode()}
            </Text>
         </TouchableOpacity>
    )
  }
}`

**********

I'm doing it on an android emulator but it happens on a device too.

Any ideas?

Thanks!

### Steps to reproduce
1. Create a view with react-native-camera
2. Create a subview with a button that opens a dialog or another subview on click

### Expected behaviour
Clicking the button should open the subview while camera still showing the image

### Actual behaviour
Clicking the button opens the subview but the camera image flicker while the subview is rendering and then continue and shows the image

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
