### ISSUE TITLE
There isn't bounds info for barcode reader on Android

### ISSUE THREAD

**Issue by melihmucuk** [react-native-community/react-native-camera#631]
### Steps to reproduce
1. Scan qr barcode
2. Check your onBarCodeRead logs

### Expected behaviour
Bounds info should be added to android as well.

### Actual behaviour
Now, on android, only barcode type and barcode data exist. 

### Environment
- **React Native version**: 0.41.2
- **React Native platform + platform version**: Android 7.0

### react-native-camera
**Version**: "master"

**Comment by jolinkomo-code** [comment]
Also struggling with this.

**Comment by MocanuMarius** [comment]
Hi, please read this thread i made to fix this. https://github.com/lwansbrough/react-native-camera/issues/683

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
