### ISSUE TITLE
Audio permission required on Android when specifying camera type

### ISSUE THREAD

**Issue by jimmoy** [react-native-community/react-native-camera#639]
Related to #205 

### Steps to reproduce
1. Specify `type={Camera.constants.Type.back}`
2. Build on Android
3. Install resulting .apk

### Expected behaviour
No permission for Audio required

### Actual behaviour
On Android install, the list of permissions required now includes audio

### Environment
- **Node.js version**: v6.7.0
- **React Native version**: 0.22.1, forked with some mods
- **React Native platform + platform version**: Android 5.0.2, Galaxy S6

### react-native-camera
**Version**: 0.4.1

**Comment by farrukhbashir** [comment]
helooo is there any option for audio recording???i use this react-native camera for audio recording also

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
