### ISSUE TITLE
EAN code - Does ean code detection actually work?

### ISSUE THREAD

**Issue by obykoo** [react-native-community/react-native-camera#640]
I tried different ean8 and ean13 found online or on products. 0 detected. 
I managed to detect QR code , but ean was not working for me.

Does ean8/ean13 works?

**Comment by obykoo** [comment]
Ok Found out what is the catch - it only scans if I position phone vertically

**Comment by averypfeiffer** [comment]
@obykoo is there anyway to trigger the can manually?

Example: I want to position a red-line over the optimal scan position, but I have NO idea what that is. Is there anyway to find that out?
