### ISSUE TITLE
feature request: add jpeg output quality to options 

### ISSUE THREAD

**Issue by npomfret** [react-native-community/react-native-camera#645]
(note to self!)

Being able to pass in a value for the quality of the saved jpeg would be nice.  Currently the iOS version is saved at 100%, which is probably unnecessarily high, and the android at 85, which is inconsistent.

**Comment by JasonMore** [comment]
I need this too. Curious to try to add it myself unless you guys think the effort is too low/high.

**Comment by npomfret** [comment]
Not difficult at all, almost trivial in fact for both iOS and Android.  I'll see if I can do it later today.

**Comment by npomfret** [comment]
iOS turned out not to be as obvious as i'd hoped.  But here's the android implementation:

https://github.com/lwansbrough/react-native-camera/pull/658/files

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
