### ISSUE TITLE
Error Handling "Cannot Connect to Camera"

### ISSUE THREAD

**Issue by nezcich** [react-native-community/react-native-camera#647]
If i have a camera view the app crashes if it "cannot connect to camera."

Is there any way to handle the error and instead of crashing just show a black screen (with error message if possible) ?

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.

**Comment by GospelHW** [comment]
+1
