### ISSUE TITLE
delay to open camera on android

### ISSUE THREAD

**Issue by ronaldozanoni** [react-native-community/react-native-camera#655]
The camera is delaying to open and to take the photo on android devices. In ios, it's working great.

Take a look in the screen recorded below.

### Steps to reproduce
1. Clone the repo: https://github.com/ronaldozanoni/react-native-camera-test-android
2. Click on "New" on header
3. Check the 1 second delay to open

### Environment
- ** react-native-cli: 2.0.1
- **Node.js version**: 7.0.0
- **React Native version**: 0.42.3

Tested on Motorola Moto X 1, Android 5.1

Am I doing anything wrong? 

Thanks.

Ronaldo Zanoni

![ezgif com-video-to-gif-iloveimg-compressed](https://cloud.githubusercontent.com/assets/4555903/24630703/10f3afac-1894-11e7-9fb3-c7d6e8dad4ed.gif)

**Comment by molerat619** [comment]
Similar with my Android 4.4 device.

**Comment by OmriAharon** [comment]
Delay in opening camera for me as well

**Comment by itxing666** [comment]
Delay in opening camera for me as well, i want to have a solution

**Comment by efnan34** [comment]
When i click to navigate camera it makes appx. 500 ms delay !

**Comment by Symous** [comment]
Hi,guys,I have found this issue before and modified the android native code to solve it by adding a prop called "onRecordVideoStarted" ,so that we can know when does the camera is ready for work. I make a PR but the author haven't merge it yet. see it here : #703  :)

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
