### ISSUE TITLE
Flash causes App to crash on Android 4.4

### ISSUE THREAD

**Issue by molerat619** [react-native-community/react-native-camera#659]
### Steps to reproduce
1. Take a picture with flash mode on (using Android 4.4 device)
2. App will crash

### Expected behaviour
Should start flash light and take a picture.

### Actual behaviour
App crashes.

### Environment
- **Node.js version**: 7.x
- **React Native version**: 0.42
- **React Native platform + platform version**: Android 4.4

### react-native-camera
**Version**: "master"

**Comment by skovhus** [comment]
@molerat619 any stack trace?

**Comment by molerat619** [comment]
@skovhus how can I get that when running on my phone? Sorry, I'm quite new to react native.

**Comment by skovhus** [comment]
When your phone is connected to your computer, you can run (unix or OS X):

`adb logcat '*:S ReactNative:V ReactNativeJS:V RCTCamera:V'`

On Windows, I guess you need to open Android Studio.

**Comment by molerat619** [comment]
Thanks for your help. Unfortunately, after doing so, I still get an empty log:
![image](https://cloud.githubusercontent.com/assets/3458576/25223269/3a9dc4bc-25bb-11e7-94b2-c6ef18ec6692.png)

**Comment by skovhus** [comment]
Ah yeah, I guess you need to filter by your apps name. 

`adb logcat '*:S myappname:V'` 

If this doesn't work you can always try:

`adb logcat '*:E'` (all errors)
`adb logcat '*:F'` (all fatals)

**Comment by molerat619** [comment]
I guess it's this one then:

![image](https://cloud.githubusercontent.com/assets/3458576/25225520/f20e4da0-25c1-11e7-9e98-aa742ee660ae.png)

**Comment by skovhus** [comment]
Is this only happening when using the Flash? The crash happens when the library tries to fix orientation after the image is taken. So related to #590 #638.

If you are using RN < 0.40 you can use react-native-camera@0.4.0 (which doesn't have the rotation fix for front facing camera).

**Comment by molerat619** [comment]
Thanks, I have reviewed the other issues and it seems to be the same thing. Seeing that, I cannot say that it has to do something with the flash - it seemed to me like it at the beginning.

I am on 0.43 of react native and I would not like to downgrade. Is a solution for that issue on the way?

**Comment by npomfret** [comment]
Image rotation is taking up a huge amount of memory (which is why the native camera doesn't do it).  My gut feeling is that it's not required any more because the metadata is no preserved in the output image.  I'll submit a PR that adds an option to `autorotate:true/false`, if someone could test it out that would be very helpful.

https://github.com/lwansbrough/react-native-camera/pull/682

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
