### ISSUE TITLE
UNMET PEER DEPENDENCY react@16.0.0-alpha.6

### ISSUE THREAD

**Issue by chilion** [react-native-community/react-native-camera#662]
Fresh installation;

`npm install react-native-camera@0.6`
```

── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
└── react-native-camera@0.6.0  invalid

npm WARN react-native-camera@0.6.0 requires a peer of react@>=15.4.0 but none was installed.
```

**Comment by iroshanAV** [comment]
@chilion may be you missed the steps. first run
`
npm install npm@latest -g`

this command will make sure to get the latest version

and then reinstall what you expected to install(because it is not yet installed) and no need to uninstall anything

**Comment by hudjoubert** [comment]
I had the same problema and try run this code but dont work. The problem continue.

**Comment by iroshanAV** [comment]
@hudjoubert  I think it's all about npm version :/

**Comment by jacobhenke** [comment]
I ran into the same issue, but was able to get it installed using yarn.

**Comment by codemonkey1337** [comment]
@jacobhenke Can you please be a bit more specific on how you resolved this with yarn? I'm getting this error too, and have not been able to solve it yet.

**Comment by jacobhenke** [comment]
If you have yarn installed already...

```bash
react-native init ProjectName
cd ./ProjectName
yarn add react-native-camera
npm link react-native-camera
```

When you use yarn to add react-native-camera, it DOES give you a warning about the version, but it seems to install it anyway, vs npm fails because of the version mismatch.

Hopefully this helps you!

**Comment by hudjoubert** [comment]
Yea, I try do this, Really install even with notice, but when I run, the code don't work, so the problem continue.

**Comment by prashantalhat** [comment]
I did
1) npm install npm@latest -g
2) npm prune
3) npm install react-native-camera
Worked for me!

**Comment by prachil007** [comment]
As stated you need install latest react globally. This is not react-native-camera issue.

**Comment by litingjun2015** [comment]
@prashantalhat 

`Last login: Mon May  8 14:58:50 on ttys002
DuangLink-MacBook-Pro:AwesomeProject duanglink$ react-native -v
react-native-cli: 2.0.1
react-native: 0.44.0
DuangLink-MacBook-Pro:AwesomeProject duanglink$ npm install npm@latest -g
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/lib
└── npm@4.5.0

DuangLink-MacBook-Pro:AwesomeProject duanglink$ npm prune
npm WARN react-native-camera@0.6.0 requires a peer of react@>=15.4.0 but none was installed.
DuangLink-MacBook-Pro:AwesomeProject duanglink$ npm install react-native-camera
AwesomeProject@0.0.1 /Users/duanglink/ReactNativeProjects/React-Native-Stable/AwesomeProject
└── react-native-camera@0.6.0

npm WARN react-native-camera@0.6.0 requires a peer of react@>=15.4.0 but none was installed.`

**Comment by litingjun2015** [comment]
@prachil007 

```
DuangLink-MacBook-Pro:AwesomeProject duanglink$ sudo npm install -g react@16.0.0-alpha.6
Password:
Sorry, try again.
Password:
/usr/local/lib
└── react@16.0.0-alpha.6

DuangLink-MacBook-Pro:AwesomeProject duanglink$ npm install react-native-camera
AwesomeProject@0.0.1 /Users/duanglink/ReactNativeProjects/React-Native-Stable/AwesomeProject
└── react-native-camera@0.6.0

npm WARN react-native-camera@0.6.0 requires a peer of react@>=15.4.0 but none was installed.
```

**Comment by jqn** [comment]
This worked for me:
1) npm install npm@latest -g
2) npm prune
3) npm install --save react@16.0.0-alpha.6
4) npm install react-native-camera

**Comment by jackson-sandland** [comment]
install with yarn worked in my case.

**Comment by lauracvieira** [comment]
npm install npm@latest -g
npm prune
npm install 

worked for me! thank you for the tips!

**Comment by Satish-A-Wadekar** [comment]
npm root -g
go to global packages 
open package.json
find the "peerDependencies" and add ^ on respective npm pckg 
and you are done
