### ISSUE TITLE
Able to QR-scan image from gallery?

### ISSUE THREAD

**Issue by kylanhurt** [react-native-community/react-native-camera#665]
I'm using version 0.24.1 and I am curious if it's possible to pass an image from the gallery (I'm using react-native-image-picker) to react-native-camera to be scanned as a QR-code, rather than live-scanning via the camera.  
Any help would be appreciated.  
Edit: For the record I am able to get the file path (JPEG) from react-native-image-pickers, just curious if react-native-camera is able to QRcode scan a JPEG file from the device's storage.

**Comment by yellowJhon** [comment]
Hi, bother, have you solved this problem?

**Comment by Obooman** [comment]
though "scan QRcode from local image" is not what `react-native-camera` should support, but we really can not find a library can recognize QRcode as sensitive as this library do.

split QRcode decode part to a standalone package or serve a solution would be appreciated.

**Comment by sibelius** [comment]
this should be another package

**Comment by 0xcodezero** [comment]
@kylanhurt Did you Find a way to implement Image scanning from Gallery that contains QR code?

**Comment by yellowJhon** [comment]
You May extends this library by add a @ReactMothod to recognize local image.

**Comment by 0xcodezero** [comment]
@yellowJhon Do you suggest another library to do so, Or I could pass a frame instead of using the video live feed of react-navtive-camera, or writing a method to scan the image manually?

I have also explored the repo branches & issues, there is guidance to include such functionality, so your guidance is highly appreciated 👍

**Comment by yellowJhon** [comment]
Yeah. 
For example, react-navtive-camera use the package of com.google.zxing to  scan the image.
Diving into the source code:
https://github.com/react-native-community/react-native-camera/blob/master/android/src/main/java/org/reactnative/camera/tasks/BarCodeScannerAsyncTask.java

You can see the recognize task of this library also pass a bitmap (a frame of video) as the input, and out the result.

SO, you MAY learn from his implemetion to achieve your function
