### ISSUE TITLE
Are there plans to support Windows (UWP)?

### ISSUE THREAD

**Issue by datkinson** [react-native-community/react-native-camera#669]
I'm developing a cross platform react-native application for Android, iOS and UWP (Windows) and this library is being used to interact with the camera, but more specifically the barcode scanner.

Are there any plans or any way to get this plugin working for UWP?

**Comment by Woodswu** [comment]
window? oh....

**Comment by rt2zz** [comment]
We do not have plans but always open to PRs!

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
