### ISSUE TITLE
Camera　interface white SDK: 22, the user manually shut down Camera permissions

### ISSUE THREAD

**Issue by TrustTheBoy** [react-native-community/react-native-camera#671]
Camera authority is not open, the camera interface is white, how to solve?
PermissionsAndroid only works at SDK> = 23
Will the SDK <23 how to detect whether the user manually closed by the user?

windows 10
phone: Samsung
Android ：5.0

**Comment by ptomasroos** [comment]
We're handling this out side the component in our app. I would suggest you to do the same, check for permissions and do not show the view if someone didnt grant permission

**Comment by pvanliefland** [comment]
@TrustTheBoy see my comment here: #224

**Comment by lhang** [comment]
@ptomasroos I tried to use the PermissionAndroid to check camera permission, but in some phone like meizu, oneplus, check function return permission granted result is true after I close the permission. some phone will crash if I close the camera permission.

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
