### ISSUE TITLE
How to set the Video recoding timing ????

### ISSUE THREAD

**Issue by farrukhbashir** [react-native-community/react-native-camera#686]
### Steps to reproduce
1.Open Camera 
2.start recording 
3.After this i want to set the limited time for video recording after this time video automatically save

### Expected behaviour
Video Save

### Actual behaviour
I have no code for this implementation plzz anyone help me how i implement this 

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-camera
**Version**: npm version or "master"

**Comment by Symous** [comment]
Maybe you can use setTimeout to stop and save automatically if the user doesn't stop it manually.

```js
setTimeout(()=>{
     //Stop and save video here.
},10000)
```

**Comment by Symous** [comment]
U also can add totalSeconds option when we invoke capture() in video mode , it will invoke stopCapture() after the totalSeconds. :-D

**Comment by farrukhbashir** [comment]
ok......after the video complete when i try to capture pic then app stop working???

**Comment by y00rb** [comment]
@Symous why can't get video`data` when call `camera.stopCapture()` ? I following the sample codes. but I using codes like:
```
      this.camera.capture({mode: Camera.constants.CaptureMode.video})
          .then((data) => console.log(data))
```
I can't see anything output in console log

**Comment by arapocket** [comment]
The totalSeconds option doesn't seem to do anything for me.
