### ISSUE TITLE
In the Android 4.4.2 version of the phone, rn-camera scan QR code is particularly slow, and even sometimes does not work, but in the 6.0 version of the phone soon

### ISSUE THREAD

**Issue by danna88** [react-native-community/react-native-camera#690]
### Environment
- **Node.js version**:
- **React Native version**:0.40
- **React Native platform + platform version**: Android 4.4.2

### react-native-camera
**Version**: npm version or "master"
Does anyone know the solution? Told me that I would be grateful

**Comment by vivikenen** [comment]
+1

**Comment by neonsec** [comment]
Facing the same on frontcam. Huge delay on getting the picture captured.
