### ISSUE TITLE
canOverrideExistingModule issue

### ISSUE THREAD

**Issue by navneetccna** [react-native-community/react-native-camera#714]
getting this issue to set canOverrideExistingModule=true

![screenshot_2017-05-23-11-13-37](https://cloud.githubusercontent.com/assets/210475/26339916/fbf3279a-3fa8-11e7-88d5-dffcb50bd584.png)

How to resolve this issue ?

**Comment by yangxiaoge** [comment]
have this issue too

**Comment by simpleenigma** [comment]
Check your MainApplication.java to see if you have the camera lines installed twice
