### ISSUE TITLE
App freezes for a couple of seconds when using react-native-router-flux

### ISSUE THREAD

**Issue by Gabbersaurus** [react-native-community/react-native-camera#715]
### Steps to reproduce
1. Create a home screen with a button that goes to the scene with the camera component
2. Run the app on Android (don't know how the app works on Ios)
3. Press the button to go to the camera scene.

### Expected behaviour
It should go to the scene whilst opening the camera

### Actual behaviour
The app freezes on the moment I touch the button (In my case I use a TouchableHighlight). When the app is done freezing I will see the highlight of the button I pressed and then I will move to the next scene. 

### Environment
- **Node.js version**: 7.5.0
- **React Native version**:0.44.0
- **React Native platform + platform version**: One Plus One with Cyanogen OS 12.1 (Android 5.1.1)

### react-native-camera
**Version**: master

**Comment by AkaOne** [comment]
This is probably because the camera is starting at the same as your scene (component) is mounting.
Try rendering the ```<Camera />``` component after the scene has mounted.
