### ISSUE TITLE
Support launching default camera app?

### ISSUE THREAD

**Issue by marsonmao** [react-native-community/react-native-camera#719]
Will there be any work on supporting launching the default camera app?
Like when you chat with [LINE](https://line.me/en/), you can tap the + button and choose `add photo`, which launches the default camera app for you to take the photo.

**Comment by mesbahsabur** [comment]
you can use react-native-image-picker for that

**Comment by marsonmao** [comment]
I see, tried it and it works, thanks!
But do you know why react-native-camera is not implementing this?
Any historical/logical reason?

**Comment by npomfret** [comment]
I thought the camera in react-native-image-picker was just a very basic one?  It doesn't support front camera, flash control, torch, etc .. no?

**Comment by marsonmao** [comment]
Nope, it directly opens the phone's default camera app, so you got everything that app supports.
(Unless the camera app doesn't support those things you mention but I think it's highly impossible!)

See the images:

1. Tap `Take Photo...`
![p1](https://cloud.githubusercontent.com/assets/5304782/26440887/e059124c-4160-11e7-9d98-e8e8c4ce2d34.jpg)

2. Use the default camera app.
![p2](https://cloud.githubusercontent.com/assets/5304782/26440892/e58f2ef4-4160-11e7-9002-6006fa53b556.jpg)

**Comment by npomfret** [comment]
Sorry, I meant on iOS

**Comment by marsonmao** [comment]
Then I haven't tried iOS, maybe I can comment again when I tried it!
