### ISSUE TITLE
Detecting Liveness

### ISSUE THREAD

**Issue by kevin-wolf** [react-native-community/react-native-camera#727]
Hello, I am wondering if there is a built-in functionality on this package to detect liveness and then capture a picture (eyes blink, moving head, something like that?)

Cheers.

**Comment by aditya-simplecrm** [comment]
Did you get any library for eye blink?

**Comment by Nandez89** [comment]
Any recent info on this topic? I was wondering the same Trying to capture a selfie picture after detecting the user blinked... any pointers?

**Comment by sibelius** [comment]
We could be done using RNCamera on master

**Comment by ManigandanRaamanathan** [comment]
@Nandez89 you found your solution?

**Comment by mykelaballe** [comment]
any solution on this? i got a project requiring a blink detection feature

**Comment by pramodsharma403** [comment]
is there any solution?

**Comment by 1ue** [comment]
Any solution found for this?

**Comment by el173** [comment]
Hi did any one found any solution for this?
