### ISSUE TITLE
Memory leak camera after taking a picture 

### ISSUE THREAD

**Issue by yelkamel** [react-native-community/react-native-camera#744]
Hello everyone,

When I take a picture, I got memory leak.

<img width="1001" alt="capture d ecran 2017-06-08 a 12 07 42" src="https://user-images.githubusercontent.com/10924422/26926307-76452132-4c4d-11e7-8e24-f993d8bdb5c3.png">

In my home navigation, it was at 390mb initially after a picture I got this: 

<img width="1009" alt="capture d ecran 2017-06-08 a 12 08 03" src="https://user-images.githubusercontent.com/10924422/26926315-7e68a8ca-4c4d-11e7-8cc8-988f03619743.png">

If I want to take multiple picture with the camera I can reach like 1.5GB of memory with the accumulation of this leak.

Any idea how to fix it ? 

**Environment**

Node.js version: v6.5.0
React Native version: 0.44.0
React Native platform + platform version: iOS 10.3
react-native-camera

Version: master

**Comment by adjustit** [comment]
@yelkamel, what version of this library were you on? 

I have a recursion script for replicating what our users will be doing in the field (pretty simple – take photo, commit it, wait 2000ms, repeat for n steps); after 12 steps on v0.9.4 I had my iOS simulator reading at 23GB of RAM usage. The rest of the code seems resilient through the same testing process, and this is an issue I've only seen today after upgrading from 0.9.0.

I'm going to do some more testing, hopefully this is just a testing issue and not an actual library one.

**Comment by adjustit** [comment]
So, further testing appears to indicate it was a false positive in regards to v0.9.4 leaking. I guess that's a good thing?
