### ISSUE TITLE
Sending image to server. What format is required?

### ISSUE THREAD

**Issue by tarang9211** [react-native-community/react-native-camera#745]
Hey Guys, I'm using this module to take an image and send it to my express server. At a later point, I also need to send this back to the client from the server. Do I need the base 64 format for this?

This is the snippet I am working with. The last time I used this package, it has base64 support. What's the alternative?

```javascript
takePicture = () => {
    if (this.camera) {
      this.camera.capture()
      .then((data) => {
        console.log(data)
        this.setState({ imgData: data.path })
      })
    }
  }
```

**Comment by jarredszabadi** [comment]
Not familiar with your backend and what it expects in the post request but I'll lay out what I did and hope it helps you!

I used [react-native-fs](https://github.com/itinance/react-native-fs) package to get the base64 encoded image.

1) `captureTarget={Camera.constants.CaptureTarget.disk}>`
2) Get base64 encoded image

```
takePicture() {
   this.camera.capture()
     .then((data) => {
       let base64Img = data.path;

       RNFS.readFile(Platform.OS === 'android'? base64Img.substring(7): base64Img, "base64")  //substring(7) -> to remove the file://
        .then(res => this.setState({uri: res}))
        .catch(err => console.error(err))
      })
}
```

^^^RNFS is included in react-native-fs. This sets a state variable to the encoded image string. You obviously don't have to store in the state but rather can read it the file only when you choose to upload.

3) Upload code. Keep in mind the json body of my post will be different than yours but just posting so you and anybody else can see. My backend requires a json body with the encoded image rather than a multipart/form-data.

```
storePicture(){
      if (this.state.uri) {
        var url = '<your_url>'
        fetch(url,
        {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Authorization': '<your auth>'
          },
          body: JSON.stringify({
            'equipment_image':{
              'image_encoded': `data:image/jpeg;base64,${this.state.uri}`
            }
          })
        })
         .then((responseData) => {
             console.log(responseData);
         })
         .catch(err => {
           console.log(err);
         })
    }
  }
```

Alternatively here's an example from a blog post which doesn't require getting the base64 string yourself. https://snowball.digital/Blog/Uploading-Images-in-React-Native

**Comment by kmtilwani** [comment]
@jarredszabadi - How can I upload the captured video using react-native-camera to the server (azure).

**Comment by kmtilwani** [comment]
@jarredszabadi - That's the code I've done so far `
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,Dimensions,Image,TouchableOpacity,TouchableHighlight,TextInput
} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});
import { TabNavigator, StackNavigator } from 'react-navigation';
import Icon from 'react-native-vector-icons/Ionicons';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
import Camera from 'react-native-camera';
import Video from 'react-native-video';
import IonIcon from 'react-native-vector-icons/Ionicons';

export default class VideoCapture extends Component {
	
  static navigationOptions = { 
        headerTintColor: 'white',
        headerStyle:{ position: 'absolute', backgroundColor: 'transparent', zIndex: 100, top: 0, left: 0, right: 0 } 
      };

  constructor(props) {
    super(props);
    this.state = {
      cameraType : 'back',
      mirrorMode : false,
      path: null,
    };
  }

  takeVid() {
    const option = {};
    this.camera.capture({
      mode: Camera.constants.CaptureMode.video,
      totalSeconds: 180
    })
      .then((data) => {
         console.log(data);
         this.setState({ path: data.path })
         VideoPath = data.path;
         
     })
      .catch((err) => console.error(err));
      setInterval(() => {
        this.setState((prevState) => {
          return {
            timer: prevState.timer - 1
          };
        });
      }, 1000);
  }

  stopVid(){
    this.camera.stopCapture();
  }


  changeCameraType() {
    if(this.state.cameraType === 'back') {
      this.setState({
        cameraType : 'front',
        mirrorMode : true
      })
    }
    else {
      this.setState({
        cameraType : 'back',
        mirrorMode : false
      })
    }
  }


  storeVideo(){
      console.log( VideoPath + "hooooolllllaaaaaaa");
      if (VideoPath) {
        
        var data = new FormData();
        data.append('video', {uri: VideoPath, name: 'video.mp4', type: 'video/mp4'});

        const config = {
         method: 'POST',
         headers: {
           'Accept': 'application/json',
           'Content-Type': 'multipart/form-data;',
           'Authorization': 'Bearer ' + 'SECRET_OAUTH2_TOKEN_IF_AUTH',
         },
         body: data,
        }

        fetch("https://192.168.10.142:3000/upload", config)
         .then((responseData) => {
            
             console.log(responseData);
         })
         .catch(err => {
           console.log(err);
     })
  }
}


  renderCamera() {
    return (
      <Camera
           ref={(cam) => {
             this.camera = cam;
           }}
           style={styles.preview}
           aspect={Camera.constants.Aspect.fill}
           type={this.state.cameraType}
           captureMode = {Camera.constants.CaptureMode.video}
           mirrorImage={this.state.mirrorMode}
           keepAwake={true}
           >   
           <TouchableOpacity onPress={this.stopVid.bind(this)}>                  
              <View style={{justifyContent: 'center',alignItems: 'center',height: 60, width:60,backgroundColor: '#f00039',borderRadius: 30,marginBottom:30}}>
                <Text style={styles.stopText}>Stop</Text>
              </View>                         
            </TouchableOpacity> 

           <TouchableOpacity onPress={this.takeVid.bind(this)}>                  
              <Image
                  source={require('./Capture.png')}
                  style={{height: 60, width: 60, marginBottom:30}}>
              </Image>
            </TouchableOpacity> 

            <TouchableOpacity onPress={this.changeCameraType.bind(this)}> 
              <IonIcon name="ios-reverse-camera-outline" style={{marginBottom:90}} size={35} color="#fefefe"/>      
            </TouchableOpacity>
       </Camera>
    );
  }

  renderVideo() {
    return (
      <View style={{flex:1,flexDirection:'column'}}> 
        <View style={{flex:1}}>
          <Video source={{ uri: this.state.path }}
             style={styles.preview}
             rate={1.0}
             volume={1.0}
             muted={false}
             resizeMode={"cover"}
             onEnd={() => { console.log('Done!') }}
             repeat={true} 
          /> 
        </View>               
        <Text
          style={styles.cancel}
          onPress={this.storeVideo.bind(this)}
          // onPress={() => this.setState({ path: null })}
        >Post
        </Text>
        <View style={styles.MainContainer}>
          <TextInput
            placeholder="Write Something"
            underlineColorAndroid='transparent'
            placeholderTextColor= '#36292a'
            style={styles.TextInputStyleClass}
            multiline= {true}
            maxLength={32}
          />
          <TextInput
            placeholder="Tag"
            underlineColorAndroid='transparent'
            placeholderTextColor= '#36292a'
            style={styles.TextInputStyleClass}
            editable= {false}
          />
        </View>
      </View>
    );
  }

  render() {
  	const {goBack} = this.props.navigation;
    return (
      <View style={styles.container}>
        {this.state.path ? this.renderVideo() : this.renderCamera()}
      </View>
    );
  }
};



const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000',
  },
  preview: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: Dimensions.get('window').height,
    width: Dimensions.get('window').width,
  },
  capture: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 5,
    borderColor: '#FFF',
    marginBottom: 15,
  },
  cancel: {
    position: 'absolute',
    right: 20,
    top: 20,
    backgroundColor: 'transparent',
    color: '#FFF',
    fontWeight: '600',
    fontSize: 17,
  },
  stopText: {
    color: '#fefefe',
    fontSize: 14,
    fontFamily: 'Montserrat-Regular'
  },
  MainContainer :{
    justifyContent: 'flex-end',
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderRightColor: '#e5e3e4',
    borderLeftColor: '#e5e3e4',
  },
 TextInputStyleClass:{
    height: 50,
    borderBottomWidth: 2,
    borderBottomColor: '#e5e3e4',
    backgroundColor : "#FFFFFF",
    paddingLeft: 15 
 }
});
`

**Comment by SimonErm** [comment]
RCTCamera is deprecated, use RNCamera instead. For uploading files taken by react-native-camera, take a look here: https://github.com/react-native-community/react-native-camera/blob/master/docs/Recipes.md
