### ISSUE TITLE
[iOS] CaptureQuality prop causes front camera to break

### ISSUE THREAD

**Issue by atpunk** [react-native-community/react-native-camera#753]
Device: iPhone 6
RCT: v16.0.0-alpha.3
RN: v0.44.0
react-native-camera: v0.9.0

While having a specified capture quality ("1080p"), accessing the front camera reveals a black rendered screen. Clicking the capture button crashes the app.

**Comment by ox-michaelradionov** [comment]
Same for me:

Device: iPad 2
React: 15.4.2
React Native: 0.42.3
react-native-camera: v0.9.4

Using capture quality "720p". Without setting capture quality camera works fine.

**Comment by maxschmeling** [comment]
This is related to #609
