### ISSUE TITLE
Capture delay

### ISSUE THREAD

**Issue by DavitVosk** [react-native-community/react-native-camera#755]
First of all, thanks for an awesome library. This is so helpful to work with.

I have an issue with capturing delay. It takes about 2-3sec. for it after the respective button is pressed, which is very noticeable in the eye. Please assist me in solving this issue. Thanks in advance

**Comment by DavitVosk** [comment]
Guys, is there an option to facilitate the capturing process? Please answer, this is really very important.

**Comment by Tzinov15** [comment]
I have this same issue, any feedback on how to improve this would be great

**Comment by DavitVosk** [comment]
change the captureQuality to 'low' or 'medium', this will facilitate the capturing process

**Comment by RekkyRek** [comment]
For some reason there is no real delay when taking a photo in an android emulator.

![Android Emulator](https://i.imgur.com/BsIMQmm.gif)

But when this exact same app is tested on hardware there is a 4-5 sec delay after hearing the shutter sound to when the callback is called.

**Comment by roxananistor92** [comment]
Hello guys, I wanna ask you if you found a solution for the delay sound. Also when using flash, capture sound is heard before camera takes picture. Is there any solution for this?
Thanks alot.

**Comment by Magnusad** [comment]
Replacing the Capture <Text> tag with <Button> from the readme example improved the issue for me. Hope this helps.

**Comment by jose920405** [comment]
+1

**Comment by Gatreek92** [comment]
Any one found a solution for this please ??

**Comment by n1ru4l** [comment]
It is also possible to have sync calls to the native thread: https://github.com/react-native-community/discussions-and-proposals/pull/11#discussion_r

I quickly tested it an it works much faster than using the async method.

However this can conflict with the react-native chrome debugger. If we would use this implementation under the hood we should detect if a chrome debugger instance is connected and fallback to the async code. cc @sibelius

**Comment by sibelius** [comment]
we can try that, maybe a flag or something

**Comment by n1ru4l** [comment]
@DavitVosk @Tzinov15 @jose920405 @Gatreek92 Anyone interested can try https://github.com/n1ru4l/react-native-camera/commit/da3f8ec538ffc96552a08574cac7fec14fa386a6

I added a sync mode toggle to the example app. Keep in mind this is android only. I had no time to do benchmarks, but it seems to me that sync mode is slightly faster than async mode.

**Comment by Linoa65** [comment]
We have a delay to on capturing photo and capturing video to (the record starts 1 entire second after the sound) only on android.

Please reopen.
