### ISSUE TITLE
Doesn't work with latest react and react native versions.

### ISSUE THREAD

**Issue by ashish-algorythma** [react-native-community/react-native-camera#763]
It requires 15.4.1 version of react and 0.42.0 version of react-native.
My application uses latest versions of these two. I tries rolling back to the mentioned versions but then my application started throwing weird errors. So is it possible to use this module with latest versions? Or is there an alpha version available?

**Comment by vandervidi** [comment]
i have the same problem.

**Comment by ashish-algorythma** [comment]
@vandervidi I tried https://github.com/react-community/react-native-image-picker and it works wonders.

**Comment by Ali-Ayyad** [comment]
@ashish-algorythma Try to upgrade to latest node version as well.

**Comment by victorbadila** [comment]
I am using this with react-native version 0.47.1 and react version 16.0.0-alpha and it works mostly. Can this issue be closed?
