### ISSUE TITLE
How we can we use front and back camera like as mobile tab

### ISSUE THREAD

**Issue by Kabijoy** [react-native-community/react-native-camera#772]
Hello all, I'm using react camera as barcode scanner in my app. By default, It is taking Back Camera, I want to  be able to switch between Front/Rear camera view for scanner. I'm not sure how to do this, any idea ? Any help appreciated!

**Comment by hedgerh** [comment]
@Kabijoy The `<Camera>` component takes a `type` property that can be used to choose whether you're using the front or back camera: https://github.com/lwansbrough/react-native-camera#type

The values are: `Camera.constants.Type.front` or `"front"`, `Camera.constants.Type.back` or `"back"` (default)

So:
```
<Camera
  type={Camera.constants.Type.front}/>
```

You could add a button that toggles between setting the type to front/back to switch between them.
