### ISSUE TITLE
BarcodeScan poor performance on IOS

### ISSUE THREAD

**Issue by buraky84** [react-native-community/react-native-camera#778]
I am developing a cross platform application that uses Barcode Scan feature.

Library Version installed: "react-native-camera": "1.0.0-alpha1"
React Native version: "0.44.3"

When using such online generated barcodes with clear view both Android 7 + IOS detects very fine and fast.
http://barcode.tec-it.com/en/Code128?data=818290012845

Problem starts on live use cases on IOS. 
Android still gives a very good performance on not very smooth type of barcode images.
However IOS not able to detect most and its becoming annoying on live usecases for customers. (Please see an example image attached which i am referring to
![barcode_example_ios_poor_performance](https://user-images.githubusercontent.com/26000468/27967343-524094d2-634b-11e7-9b1b-cbf63435c0c9.jpg)
)

I have checked the library documentation but could not see any fine-tuning parameter that may fix this. And no similar Issue reports or a PR. Do you think is there something this library can improve the experince or this is an issue on Native side?

Thanks for any recommendations anyway.

**Comment by buraky84** [comment]
Additional Info: When i download random Barcode Scan applications from AppStore it detects Barcodes on above attached image fast & smooth. So again my question is, how this can be improved on "react-native-camera" library?

**Comment by Failcookie** [comment]
This was a known issue as far as 2017 #78 - Unless something has changed since then, I imagine the package is still using the native scanners which is just naturally slow. I do agree though - we need to find a better alternative to avoid user frustration at some point.

**Comment by buraky84** [comment]
Ok Thanks. I had to switch to an alternative library for the moment. Hopefully this will get fixed soon.

**Comment by K-Leon** [comment]
@buraky84 which lib are you using?

**Comment by buraky84** [comment]
smart-barcode

this is based on zxing which is an alternate Native solution. IOS detection performance looks good. Android performance is similar as react-native-camera.
