### ISSUE TITLE
Problem with ios 10.3.1

### ISSUE THREAD

**Issue by hugohow** [react-native-community/react-native-camera#779]
Hello,

I have a problem with iOS 10.3.1, when I publish to Apple store. I'm using react-native 0.41.2 and I use this version of react native camera react-native-camera@https://github.com/lwansbrough/react-native-camera.git

Does someone has the same issue ?

Thread 2 name:  Dispatch queue: cameraManagerQueue
Thread 2 Crashed:
0   libsystem_kernel.dylib        	0x0000000185ccd014 0x185cae000 + 126996
1   libsystem_pthread.dylib       	0x0000000185d97264 0x185d92000 + 21092
2   libsystem_c.dylib             	0x0000000185c41a60 0x185be0000 + 399968
3   libsystem_c.dylib             	0x0000000185c419d0 0x185be0000 + 399824
4   libc++abi.dylib               	0x000000018570d1b0 0x18570c000 + 4528
5   libc++abi.dylib               	0x0000000185726c04 0x18570c000 + 109572
6   libobjc.A.dylib               	0x0000000185734820 0x18572c000 + 34848
7   gifprojectv3                  	0x000000010008c8f8 0x100070000 + 116984
8   libc++abi.dylib               	0x00000001857235d4 0x18570c000 + 95700
9   libc++abi.dylib               	0x0000000185722ef8 0x18570c000 + 93944
10  libobjc.A.dylib               	0x000000018573466c 0x18572c000 + 34412
11  AVFoundation                  	0x000000018e713f44 0x18e644000 + 851780
12  gifprojectv3                  	0x0000000100176c50 0x100070000 + 1076304
13  libdispatch.dylib             	0x0000000185b8a9e0 0x185b89000 + 6624
14  libdispatch.dylib             	0x0000000185b8a9a0 0x185b89000 + 6560
15  libdispatch.dylib             	0x0000000185b98ad4 0x185b89000 + 64212
16  libdispatch.dylib             	0x0000000185b8e2cc 0x185b89000 + 21196
17  libdispatch.dylib             	0x0000000185b98fa8 0x185b89000 + 65448
18  libdispatch.dylib             	0x0000000185b9aa50 0x185b89000 + 72272
19  libdispatch.dylib             	0x0000000185b9a7d0 0x185b89000 + 71632
20  libsystem_pthread.dylib       	0x0000000185d93100 0x185d92000 + 4352
21  libsystem_pthread.dylib       	0x0000000185d92cac 0x185d92000 + 3244

**Comment by n1ru4l** [comment]
Please use the current version or master and give feedback whether this crash is still occuring.

I am closing this issue, if your problem is still not solved, please open a new issue.
