### ISSUE TITLE
Android captureQuality of "preview" didn't work

### ISSUE THREAD

**Issue by huyvohcmc** [react-native-community/react-native-camera#782]
In Android 7.0 (Sony Xperia XA), the `captureQuality` of video recording didn't work with the value `Camera.constants.CaptureQuality.preview`. It does start the recording but didn't save the video and show an error like this in the console: `CamcorderProfile not found in prepareMediaRecorder`.

Right now it looks like `Camera.constants.CaptureQuality.high` or `Camera.constants.CaptureQuality.medium` stretch the screen wider a little bit while recording and make it unnatural with the preview screen so I want to change it but there is no way.

Pull request #479 may be the solution (I'm not sure since I don't understand the code yet).

**Comment by n1ru4l** [comment]
Please use the current version or master and give feedback whether this crash is still occuring.

I am closing this issue, if your problem is still not solved, please open a new issue.
