### ISSUE TITLE
Typescript Definition File?

### ISSUE THREAD

**Issue by MartinWebDev** [react-native-community/react-native-camera#785]
Hi there? Anybody have, or any plans to add, a d.ts file?
For now I have just added the whole thing as "any" for now, but would rather not, and I'm not great at writing my own typescript definition files. 

Thanks :)

**Comment by Fconstant** [comment]
@MartinWebDev I'm working on it.
Maybe I'll try to publish at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so you can install as:
```
npm i @types/react-native-camera
```

*PS:* I'm not in any way related to this project. I just like to type things :smile:

**Comment by sibelius** [comment]
Feel free to send a pr here as well
