### ISSUE TITLE
Android scan qrcode  very slow even unrecognized

### ISSUE THREAD

**Issue by isszz** [react-native-community/react-native-camera#788]
Version:
> android: 6.0
> react-native: 0.46.3
> react-native-camera: 0.9.4

**Comment by nmfzone** [comment]
Same here..

**Comment by Liuthx** [comment]
same,  what can replace it on Android?

**Comment by nmfzone** [comment]
@Liuthx https://github.com/react-native-component/react-native-smart-barcode

**Comment by diegobfernandez** [comment]
I think Google Mobile Vision API that is included in Android SDK would fit better.

**Comment by isszz** [comment]
@nmfzone 
This problem does not seem to be the component.
ZXing should be the problem, the old version of ZXing is no problem, but the new version will be very slow
I'm curious why I do not use ZBar

**Comment by marlti7** [comment]
same problem
