### ISSUE TITLE
Modal inside camera freezes the app when its closed

### ISSUE THREAD

**Issue by srameshr** [react-native-community/react-native-camera#791]
**Originally reported here**
[https://github.com/facebook/react-native/issues/15057](https://github.com/facebook/react-native/issues/15057)

**Comment by hedgerh** [comment]
@srameshr I took a look and, yeah, it crashes my app whenever I even try and close the modal.

Instead of nesting the Modal within the `<Camera>`, just put it below it and it should still work how you want:

```
<View>
  <Camera/>
  <Modal>...</Modal>
</View>
```

**Comment by n1ru4l** [comment]
Does this still occur with RNCamera?
