### ISSUE TITLE
Is there any way to measure human height using camera

### ISSUE THREAD

**Issue by thomaspower8** [react-native-community/react-native-camera#793]
I am developing a mobile app in react native that uses this camera package. I need to measure height of human body using camera. 
Is there any way of doing this? Suggestions are highly appreciated.
Thansk

**Comment by victorbadila** [comment]
This would be better suited as a Stackoverflow question, the issues section of this github page is for actual library issues and improvements.

**Comment by n1ru4l** [comment]
I am going to close this due to the facts @victorbadila  mentioned.
