### ISSUE TITLE
Barcode PDF417 in IOS is not working

### ISSUE THREAD

**Issue by rcanessa89** [react-native-community/react-native-camera#794]
Hello!

I was trying to read a pdf417 but is not working how is expected, data is coming like an empty string and should return something like:

78?¡+r®FS'0  Ñ3àÐß'uWðIAÜHáÑ3àÐß'0  Ña¯GLO'0  Ñ3àÐß'0 Þ#é
Ð0á1í040; Ñ3àÐ1é	0\øÿI²}¶eÀ[«ó{¬ÊwwnL§:±±Qú|bËü¬-f¾UY[?{­÷Jyu:SÅ[» æb¥7·jA¬`LYZª²1¨«N¢Qÿy°\Ý°8nÑàÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'2! \Xl g« tm4xôÇU`®u¤G¬gjÚszýníPojenv|î­ÊÃ¬Ùs_jAYa[I¦EqÓhtûmò±_y}ÞRò¸ýôfwûgÎàÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0  Ñ3àÐß'0

In android version is working fine. Somebody knows how fix the problem or what is happening? (I'm not sure but is something related to 'UTF-8' and 'ASCII')

Thanks

**Comment by jcgonzave** [comment]
Hi

I am having the same problem when scanning pdf417 codes on iOS. 

On android it works as expected giving me the whole data I need.
I actually can get information that is between the null characters (\u0000)

![7eb59589fac0b7c66e97182653c5f32cf38b455f](https://user-images.githubusercontent.com/1459799/43734030-185ad1e8-997c-11e8-8211-fb0d0168c898.jpg)

But when scanning on iOS the data breaks just before the first null character.
¿Is probably the null character (\u0000) used to identify the end of the string?

I am testing it on real devices: iphone 7 and Motorola g5s plus with 7.1.1 android version.

**Comment by andresmtz98** [comment]
On Android with v2.0 also :/

**Comment by andresmtz98** [comment]
This problem still persists on ios. It looks like never will be fixed :(.

**Comment by renatobenks** [comment]
@rcanessa89 @jcgonzave @andresmtz98 can you guys give an update on this? is this still happening?
