### ISSUE TITLE
captureQuality not working

### ISSUE THREAD

**Issue by irokhes** [react-native-community/react-native-camera#804]
I'm trying to change the video quality but is not working (or I missing something).
I'm following the example code, bellow are my settings:

```
this.state = {
      camera: {
        aspect: Camera.constants.Aspect.fill,
        captureTarget: Camera.constants.CaptureTarget.disk,
        captureQuality: Camera.constants.CaptureQuality["480p"],
        type: Camera.constants.Type.back,
        orientation: Camera.constants.Orientation.auto,
        flashMode: Camera.constants.FlashMode.auto,
      },
      isRecording: false
    };
  }
```
The video is still 1920x1080 no matter what value I set in captureQuality

do you see anything wrong there?
Thanks!

**Comment by khendraw** [comment]
on the example code there is no captureQuality property

`<Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          style={styles.preview}
          aspect={this.state.camera.aspect}
          captureTarget={this.state.camera.captureTarget}
          type={this.state.camera.type}
          flashMode={this.state.camera.flashMode}
          onFocusChanged={() => {}}
          onZoomChanged={() => {}}
          defaultTouchToFocus
          mirrorImage={false}
        />` 

I fell for this one also. Yet I still have force close on Android when the captureQuality property is stated.

**Comment by irokhes** [comment]
Anyone has been able to record with different quality?

**Comment by yomybaby** [comment]
I have a same problem. Always 1920x1080.. 😢

**Comment by han4wluc** [comment]
I have the same problems. looks like captureQuality is not working for iOS video capture.

**Comment by han4wluc** [comment]
I can confirm that captureQuality is working on iOS, video.

**Comment by io-pan** [comment]
Neither on Android7.0 (galaxy S6) RN 0.44.2
Photos size is still 5312x2988 whatever the choosen captureQuality

**Comment by alameddince** [comment]
how can you it ? @han4wluc

**Comment by jordangrant** [comment]
@irokhes @alameddince  Try setting the captureQuality in the component. Not in the state or elsewhere.
```
<Camera
          ref={(cam) => {
            this.camera = cam;
          }}
          style={styles.preview}
          aspect={this.state.camera.aspect}
          captureTarget={this.state.camera.captureTarget}
          **captureQuality={'480p'}**
/>
```

**Comment by n1ru4l** [comment]
RCTCamera is deprecated, please use RNCamera.
