### ISSUE TITLE
permission not setting for camera auto, after install app.

### ISSUE THREAD

**Issue by tundak** [react-native-community/react-native-camera#814]
permission not setting for camera auto, after install app.

working with moto G5  android 7.0

**Comment by iegik** [comment]
I use https://github.com/iegik/redux-saga-native-permissions based on https://github.com/yonahforst/react-native-permissions

**Comment by xenu256** [comment]
See [this working example](https://github.com/react-native-community/react-native-camera/issues/1708#issuecomment-429547891)
