### ISSUE TITLE
Android preview is dark solution

### ISSUE THREAD

**Issue by hellomaya** [react-native-community/react-native-camera#822]
My Android Nexus 5, version 5.0.1,  device had a problem to open the preview with react-native-camera, when it opened, the scene is much more dark than the system Camera app, so I checked the open source Camera app code, it appears to have those code when initialize the camera:

```java

        // Reset preview frame rate to the maximum because it may be lowered by
        // video camera application.
        List<Integer> frameRates = parameters.getSupportedPreviewFrameRates();
        if (frameRates != null) {
            Integer max = Collections.max(frameRates);
            parameters.setPreviewFrameRate(max);
        }
```

https://android.googlesource.com/platform/packages/apps/Camera.git/+/lollipop-release

And it solved the problem. I think it might be good to add this one in current codebase too.

**Comment by pribeh** [comment]
@hellomaya where did you add the above too?
