### ISSUE TITLE
Android: crash on touch when camera not yet initialized

### ISSUE THREAD

**Issue by krizka** [react-native-community/react-native-camera#825]
```
Fatal Exception: java.lang.NullPointerException
       at com.lwansbrough.RCTCamera.RCTCameraViewFinder.onTouchEvent(RCTCameraViewFinder.java:349)
       at android.view.View.dispatchTouchEvent(View.java:7782)
```
After reinitialization of camera (reopening camera window). Think its because of _camera is null there and not yet initialized.

**Comment by Amurmurmur** [comment]
+1

**Comment by jrchew88** [comment]
I am also experiencing this.

**Comment by Amurmurmur** [comment]
@jrchew88 
Fixed it by adding 
```
android:launchMode="singleTask"
```

To the .MainActivity

Hopefully works for you! 👍 
The problem is that many instances of react-native-camera are instantiated, well for me at least.

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
