### ISSUE TITLE
Camera white when being overlayed

### ISSUE THREAD

**Issue by michelalbers** [react-native-community/react-native-camera#830]
I use react-community/react-navigation for navigating around my app, which is structured like this:

- WrapperNavigator (StackNavigator / Modalmode)
  - AppNavigator (TabNavigator)
    - Camera
    - Gallery
  - LoginAndRegistrationNavigator (StackNavigator)
    - Login
    - Registration
      - Step 1
      - Step 2
      - ....

When the user opens the app and is not logged in, the app will redirect to LoginAndRegistrationNavigator/Login. The Camera is the initial view of AppNavigator and will therefore be rendered and visible until the login overlay appears.

The issue: After the user is done with logging in or registration, the camera will not be working / be white. It will work again, after the user taps the switch camera button once.

Is there a way to tell the camera to reinit? Hiding and showing the view does kinda work but is very bad performancewise.

**Comment by michelalbers** [comment]
I tried multiple approaches in force resetting the camera but all failed. Any help?

**Comment by ArwaLh** [comment]
I have encountered this same problem. Anyone that could help me?

**Comment by SimonErm** [comment]
RCTCamera is deprecated, use RNCamera instead. If this issue still occures, open a new issue please.
