### ISSUE TITLE
how make the flash always lighting？？？

### ISSUE THREAD

**Issue by yunyouboy** [react-native-community/react-native-camera#832]

**Comment by adjustit** [comment]
Set `flashMode` to `Camera.constants.FlashMode.on` when you initialise the camera's options in your component's `state`.

**Comment by adjustit** [comment]
Or if you mean so the light is always illuminated, `Camera.constants.torchMode.on` is what you need.

**Comment by christophby** [comment]
In my case the prop
`flashMode={isTorchOn ? Camera.Constants.FlashMode.torch : Camera.Constants.FlashMode.off}`
did it

**Comment by n1ru4l** [comment]
@anniewey which platform are you using?

**Comment by anniewey** [comment]
@christophby Tried with your props but still same result.
@n1ru4l I'm using it on Android.

**Comment by filippoitaliano** [comment]
Same issue here:

``
import Camera, { RNCamera } from 'react-native-camera';
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';

export default class Photo extends React.Component {
  onBarCodeRead = e => {
    this.props.barcodeCallback(e);
  };

  render() {
    return (
      <View style={styles.container}>
        <Camera
          flashMode={RNCamera.Constants.FlashMode.torch}
          onBarCodeRead={this.onBarCodeRead}
          barCodeTypes={[
            RNCamera.Constants.BarCodeType.qr,
            RNCamera.Constants.BarCodeType.datamatrix,
          ]}
          style={styles.preview}
        />
      </View>
    );
  }
}
``

Flash always off.

**Comment by xjing97** [comment]
> In my case the prop
> `flashMode={isTorchOn ? Camera.Constants.FlashMode.torch : Camera.Constants.FlashMode.off}`
> did it
> 
> _flashMode_ is the propname & _Camera.Constants.FlashMode.torch_ is the correct key

Thx, Camera.Constants.FlashMode.torch is the correct key, and it works!!!



> Same issue here:
> 
> ```
> import Camera, { RNCamera } from 'react-native-camera';
> import React from 'react';
> import { StyleSheet, Text, View, Button } from 'react-native';
> 
> export default class Photo extends React.Component {
>   onBarCodeRead = e => {
>     this.props.barcodeCallback(e);
>   };
> 
>   render() {
>     return (
>       <View style={styles.container}>
>         <Camera
>           flashMode={RNCamera.Constants.FlashMode.torch}
>           onBarCodeRead={this.onBarCodeRead}
>           barCodeTypes={[
>             RNCamera.Constants.BarCodeType.qr,
>             RNCamera.Constants.BarCodeType.datamatrix,
>           ]}
>           style={styles.preview}
>         />
>       </View>
>     );
>   }
> }
> ```
> Flash always off.

I think you should change your RNCamera to Camera, and it will work

**Comment by n1ru4l** [comment]
`Camera` is deprecated and will be removed in the next major release. Please use `RNCamera`, if you experience any issues with `RNCamera` I encourage you to open a new issue/or fix the issue with a pull request.
