### ISSUE TITLE
code=EXC_I386_INVOP

### ISSUE THREAD

**Issue by skyweaver213** [react-native-community/react-native-camera#835]
xcode build and run the project ,it will auto breakpoint at
0x109e0637a <+145>: ud2    
info: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

 How should i do,please?
![wechatimg14](https://user-images.githubusercontent.com/5363176/29259020-57a136fc-80f1-11e7-8526-d801069e9ebe.jpeg)

**Comment by ziyaddin** [comment]
@skyweaver213 were you able to fix this error?
