### ISSUE TITLE
Squats fps when switching screens with react navigation

### ISSUE THREAD

**Issue by shanematte** [react-native-community/react-native-camera#848]
Hello. I have a problem with switching screens with drawer react navigation. For example, I photographed, switch to another screen, FPS crouches. Animation looks terrible. How to solve this problem? Thanks

**Comment by MackayBravo** [comment]
support. I'm still here

**Comment by banli17** [comment]
+1

**Comment by n1ru4l** [comment]
Closed due to missing activity. Please open a new issue if you still experience this with the newest version of `RNCamera`.
