### ISSUE TITLE
Default Zoom Factor

### ISSUE THREAD

**Issue by JoschaP** [react-native-community/react-native-camera#850]
Hey Folks, 
is it possible to set a default zoom factor?

Thanks 4 help

**Comment by n1ru4l** [comment]
@JoschaP Feel free to send a pull request that implements that feature.

**Comment by beaurushton** [comment]
@JoschaP isn't that what https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#zoom does?

**Comment by n1ru4l** [comment]
@beaurushton Have you tested it? I think @JoschaP means the zoom is not applied when the camera is initialized for the first time.
