### ISSUE TITLE
SIGABRT on ios when barCodeTypes specified

### ISSUE THREAD

**Issue by deedoc** [react-native-community/react-native-camera#854]
Hi guys!

I'm using "react-native-camera": "0.10.0" and specified barCodeTypes like this
`barCodeTypes={["qr"]}`

It works nice on android, but i began to get SIGABRT on ios.

In XCode debug i see that when i leave barCodeTypes blank it passed into
`[metadataOutput setMetadataObjectTypes:self.barCodeTypes];`
as array of AVFoundation qualifier strings ["org.iso.QRCode", ...]

But if i do specify barCodeTypes it passes as is - ["qr", ...] - this is reason of SIGABRT

I avoided this SIGABRT with following code
```
const BAR_CODE_TYPES = [
  Platform.select({android: "qr", ios: "org.iso.QRCode"})
];
```

**Comment by srolija** [comment]
Had the same issue, you should use constant rather than string, try like this
`barCodeTypes={[Camera.constants.BarCodeType.qr]}`.

**Comment by norberdo** [comment]
Correct, this fixed my problem, thank you!
