### ISSUE TITLE
onBarCodeRead when read Code128 in android 4.4,it doesn‘ work 

### ISSUE THREAD

**Issue by wenwen1995** [react-native-community/react-native-camera#855]
When I use the camera to scan the code128,it works good in android 5+,but when I use it in android ,it only can scan qr,but don't read the code128 data,what's wrong ??

**Comment by wenwen1995** [comment]
Okay,I find the problem,it's not the code problem,it may be the code128.....When I use android 4.4 phone to scan the pc code128 photos,like this,
![tt](https://user-images.githubusercontent.com/12100065/29757162-5f3a4c1e-8bdc-11e7-9872-26f3eceb4f93.jpg)

and I scan many of these photos,it works well,and the datas also appear....I think it may be not  sensitive..

**Comment by rajeshkos** [comment]
Hi @wenwen1995 

Can you please send me sample code for barcode reader for android and ios ?

**Comment by iegik** [comment]
It is ean13
