### ISSUE TITLE
 How can I increase the speed of the render to react native camera?

### ISSUE THREAD

**Issue by shanematte** [react-native-community/react-native-camera#860]
I use the react navigation module for routing, when I go to screen of module react native camera fps drops to 2, but when the module is loaded, fps 60. How to solve this problem?
THANKS
IT IS VERY IMPORTANT !!

**Comment by adjustit** [comment]
The only real ways to somewhat solve it that I know of are to either, a) preload the component you're switching to and then show the camera with a `state` toggle, or b) get faster hardware. 

Initialising the camera (whether it's the native camera built into the OS or through an abstracted layer like RN with this library) is inherently expensive and will consume a lot of your resources.

Also, sidenote: ALL-CAPS and exclamation marks make it much less likely for people to want to help you. Especially when you already have an existing issue for the problem mentioned on the repo you're asking on.

**Comment by p-ugulino** [comment]
@adjustit hey, could you elaborate more on how to preload a component?

**Comment by n1ru4l** [comment]
Please open a new issue if you are still experiencing these issues with the newest version of `RNCamera`.
