### ISSUE TITLE
orientation doesnt work.

### ISSUE THREAD

**Issue by Gigasz** [react-native-community/react-native-camera#866]
tried literally everything
(ios)

**Comment by adjustit** [comment]
When you say 'literally everything' – what exactly does that mean?

**Comment by Gigasz** [comment]
every possible combination on the orientation prop inside camera tag

**Comment by Gigasz** [comment]
looked into RCTCamenraManager.m to check if the string received matches

**Comment by samanthacampisi** [comment]
I can confirm this, has anyone found a solution?

**Comment by iamweilee** [comment]
orientation不起效果，我们希望idcard平放在桌子上，手机横着拍idcard，但拍出来的效果却是倾斜-90度的，尽管我设置了orientation为landscapeRight依然不起作用。

**Comment by SimonErm** [comment]
This issue is closed because of inactivity.
Furthermore RCTCamera is deprecated now, use RNCamera instead. If this issue is also related to RNCamera, please open a new one.
