### ISSUE TITLE
Does react-native-camera support returning the thumbnail for captured JPEG?

### ISSUE THREAD

**Issue by nburger** [react-native-community/react-native-camera#868]
Hi our RN app is hitting OOM issues displaying images captured using this module.  At the same time, we have a requirement to keep captured image quality above the lowest levels.  What support, if any, does this module have for returning the EXIF thumbnail which a camera may already generate?

https://developer.android.com/training/camera/photobasics.html#TaskPhotoView

**Comment by SimonErm** [comment]
Take a look here https://github.com/phuochau/react-native-thumbnail
