### ISSUE TITLE
Execution failed for task ':app:transformClassesWithDexForDebug'

### ISSUE THREAD

**Issue by Naveen-ICARUS** [react-native-community/react-native-camera#885]
I try to use the react-native-camera by following both automatic and manual installation. 
but always shows this error please help me in .
![image](https://user-images.githubusercontent.com/31643287/30311382-8ebb54c4-97b2-11e7-8f3f-5ed87f6ea242.png)

**Comment by jozekcore** [comment]
i have the same issue

**Comment by ashishrokr** [comment]
same issue while installing app

**Comment by irsyadmhdilham** [comment]
@ashishrokr I did tweak multiDexEnabled to true and add in the dependencies. Still doesn't solve the issue

**Comment by n1ru4l** [comment]
This seems to be solved.

@irsyadmhdilham If you still experience this issue after using the newest npm release and/or the master branch and RNCamera I encourage you to open a new issue.

**Comment by kapil708** [comment]
hi @irsyadmhdilham did you find any solution.
