### ISSUE TITLE
How to set metadata correctly and how to retrieve it?

### ISSUE THREAD

**Issue by Stophface** [react-native-community/react-native-camera#891]
I am not sure if I understand the docs properly.
`capture([options]): Promise` allows to set `metadata` like `location`.

However, how do I set the `metadata` correctly?! That way?

```
    _takePhoto() {
        const options = { location };
        this.camera.capture({ metadata: options })
            .then((data) => {
                console.log("photodata", data, data.path)
            })
            .catch(err => console.error(err))
    }
```

And, how would I read the `location` information out again? When I log `console.log("photo data", data, data.path)` there is no `location` information in it.

**Comment by koswarabilly** [comment]
i got the same problem , mine even crash when i try to take photo

**Comment by zahid-dapperapps** [comment]
+1 same issue no metadata being saved
