### ISSUE TITLE
Camera crashes when I try to open it again

### ISSUE THREAD

**Issue by nachovg** [react-native-community/react-native-camera#895]
Hi, thanks for your attention! I'm developing an app to scan qr codes and I have a little problem, when I scan a Qr I go to a success or fail screen, when is fail I can try it again but the app crashes when the scan screen render the camera the second time. I think it happens cause the camera is running in background, there is any way to close it completely?

**Comment by satishsynnov** [comment]
Can you please share your crash report?

**Comment by nachovg** [comment]
There is no crash report, it just close it

**Comment by satishsynnov** [comment]
Can you share your code how are you using?

**Comment by qamoonsite** [comment]
happens to me also, please help

**Comment by n1ru4l** [comment]
Please open a new issue if you are still experiencing this problem with the newest version of `RNCamera`.
