### ISSUE TITLE
Could not connect to development Server

### ISSUE THREAD

**Issue by AAGSICON** [react-native-community/react-native-camera#897]
![screenshot_2017-09-19-08-45-05-22](https://user-images.githubusercontent.com/31310379/30574695-503f195e-9ceb-11e7-8099-f57829460a98.png)

**Comment by nachovg** [comment]
Did you run react-native start? Are you trying to run it from your physical device? Because when I try to run it in my phone I need to run "adb reverse tcp:8081 tcp:8081" in adb folder to connect it.
