### ISSUE TITLE
undefined is not an object (evaluvating '_reactNative.NativeModules.RNPinch.fetch')

### ISSUE THREAD

**Issue by AAGSICON** [react-native-community/react-native-camera#902]
![screenshot_2017-09-22-16-30-32-70](https://user-images.githubusercontent.com/31310379/30741962-9f3bd1c6-9f86-11e7-8e94-0286c11020e9.png)

import React, { Component } from 'react';
import { NativeModules } from 'react-native';
import DatePicker from 'react-native-datepicker';
import ValidationComponent, {Form, FormInput, Validate} from 'react-native-form-validator';
import {  Text, TextInput, Picker, View, Button, StyleSheet, NativeAppEventEmitter, Camera, Alert } from 'react-native';
import * as EmailValidator from 'email-validator';
import pinch from 'react-native-pinch';

export default class Registration extends Component {

constructor(props) {
    super(props);
    this.state = {text: '',
    date:'',
    firstName:'',
    lastName:'',
    email:'',
    username:'',
    password:'',
    passwordConfirmation:''
      };
    }

  _handlePress(event) {
console.log('Pressed!');

var tester = /^[-!#$%&'*+\/0-9=?A-Z^_a-z{|}~](\.?[-!#$%&'*+\/0-9=?A-Z^_a-z`{|}~])*@[a-zA-Z0-9](-?\.?[a-zA-Z0-9])*\.[a-zA-Z](-?[a-zA-Z0-9])+$/;
// Thanks to:
// http://fightingforalostcause.net/misc/2006/compare-email-regex.php
// http://thedailywtf.com/Articles/Validating_Email_Addresses.aspx
// http://stackoverflow.com/questions/201323/what-is-the-best-regular-expression-for-validating-email-addresses/201378#201378
var firstName = this.state.firstName;
var lastName = this.state.lastName;
var date = this.state.date;
var email = this.state.email;
var username = this.state.username;
var password = this.state.password;
var passwordConfirmation = this.state.passwordConfirmation;

var atpos = email.indexOf("@");
   var dotpos = email.lastIndexOf(".");

    if (firstName=="") {
       title = 'Fail';
       msg = '1. firstName is required'; // get all fields' validation error message

     }else if (lastName=="") {

          title = 'Fail';
          msg = '2. lastName is required'; // get all fields' validation error message
        }
        else if (date=="") {
          title = 'Fail';
          msg = '3. date is required';

        }

        else if (atpos<1 || dotpos<atpos+2 || dotpos+2>=email.length) {
          title = 'Fail';
          msg = '4. email is required';

        }

        else if (username=="") {
          title = 'Fail';
          msg = '5. Username is required';

        }
        else if (password=="") {
          title = 'Fail';
          msg = '6. password is required';

        }
        else if (passwordConfirmation=="") {
          title = 'Fail';
          msg = '7. confirmpassword is required';

        }
        else if (password != passwordConfirmation) {
          title = 'Fail';
          msg = '8. password and confirm password does not match';

        }
        else {

          title = 'Sucess';
          msg = 'user Registration is Sucess';
          pinch.fetch('https://192.168.0.80/Registration/user_registration.php', {
            method: 'POST',
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({

              name: username,

              email: email,

              password: password

            }),
            sslPinning: {
                cert: 'my-cool-cert'

              }
          }).then((response) => response.json())
                .then((responseJson) => {

          // Showing response message coming from server after inserting records.
                  Alert.alert(responseJson);

                }).catch((error) => {
                  console.error(error);
                });
        }

    Alert.alert(
           title,
           msg,
           [
             {text:'ok'},
           ]
         );

}

render() {
        return (
          <View style={{padding: 30}}>
          <Text style={{textallign: "Center"}}>SignUp</Text>

            <TextInput

            Name="firstName"
             style={{height: 40}}
              autoFocus={true}
              autoCapitalize="none"
              autoCorrect={false}
              placeholder="First Name"
              onChangeText={(firstName) => this.setState({firstName: firstName})}

            />

          <TextInput
          Name="lastName"
           style={{height: 40}}
            autoFocus={false}
            autoCapitalize="none"
            autoCorrect={false}
            placeholder="Last Name"
            onChangeText={(lastName) => this.setState({lastName: lastName})}
          />
          <Picker
            selectedValue={this.state.language}
            placeholder="Select Gender"
            onValueChange={(itemValue, itemIndex) => this.setState({language: itemValue})}>
            <Picker.Item label="Male" value="Male" />
            <Picker.Item label="Female" value="Female" />
          </Picker>
          <DatePicker
            style={{width: 295}}
            date={this.state.date}
            mode="date"
            placeholder="Select Date of Birth"
            format="YYYY-MM-DD"
            confirmBtnText="Confirm"
            cancelBtnText="Cancel"
            customStyles={{
              dateIcon: {
                position: 'absolute',
                left: 0,
                top: 4,
                marginLeft: 0
              },
              dateInput: {
                marginLeft: 36
              }
          // ... You can check the source to find the other keys.
        }}
        onDateChange={(date) => {this.setState({date: date})}}
      />
          <TextInput
          Name="email"
           style={{height: 40}}
           autoFocus={false}
           autoCapitalize="none"
           autoCorrect={false}
           placeholder="Email"
           onChangeText={(email) => this.setState({email: email})}
         />

          <TextInput
          Name="username"
          style={{height: 40}}
          placeholder="Username"
          onChangeText={(username) => this.setState({username: username})}
        />

	       <TextInput
         Name="password"
          style={{height: 40}}
          placeholder="password!"
          secureTextEntry={true}
          autoCapitalize="none"
          autoCorrect={false}
          onChangeText={(password) => this.setState({password: password})}
        />

          <TextInput
          Name="passwordConfirmation"
           style={{height: 40}}
            secureTextEntry={true}
            autoCapitalize="none"
            autoCorrect={false}
            placeholder="Password Confirmation"
            onChangeText={(passwordConfirmation) => this.setState({passwordConfirmation: passwordConfirmation})}
          />

       <Button
    onPress={this._handlePress.bind(this)}
     title="Press Me"
 />
      </View>

        );
    }
  }

**Comment by DaBs** [comment]
That's from pinch and not camera. This should be closed and moved to the pinch repo.
