### ISSUE TITLE
Android compiling error

### ISSUE THREAD

**Issue by fenicento** [react-native-community/react-native-camera#905]
I have various errors when i run react-native run-android, mostly referring to non existing libraries:

error: package com.drew.imaging does not exist
error: package com.drew.metadata does not exist
error: package com.google.zxing does not exist

should I install them on my own? should they be included in google APIs?

**Comment by fenicento** [comment]
nevermind, I didn't update build.gradle. I have another error now:

Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple de
x files define Lcom/lwansbrough/RCTCamera/RCTCamera$CameraInfoWrapper;


any clues?

**Comment by samhunta** [comment]
Try removing specific versions from your build.gradle

Source: https://github.com/tolu360/react-native-google-places/issues/31

**Comment by n1ru4l** [comment]
Dpulicate of #885
