### ISSUE TITLE
App Crash when taking a picture 

### ISSUE THREAD

**Issue by sandropoluan** [react-native-community/react-native-camera#918]
App get crashed/unexpected closed when taking a picture, And no image was saved.
This problem only happen with real device. Everything is fine on emulator. 

Everything was fine when i was using RN 0.44.0, but the problem appear after upgrading to  RN 0.48.4.

react-native-camera@0.10.0
React Native@0.48.4

Device
Xiaomi Redmi Note 2 (Android 5.0.2)

**Comment by CalebRoyer** [comment]
+1

**Comment by eiribro** [comment]
+1

**Comment by goel135** [comment]
+10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by goel135** [comment]
Any update on this because many people are facing this issue.
If there is any update do reply asap.
I have tried it on react-native-camera@0.6 as well as on react-native-camera@0.10
With react native version 0.46.4
and react navigation version ^1.0.0-beta.11
Do reply if there is any solution.

**Comment by koswarabilly** [comment]
i am facing the same issue but only when i try to add location metadata to it

**Comment by ducpt2** [comment]
+1

**Comment by seanelias** [comment]
Same issue app crashes when taking a photo. I tested this on Pixel, Pixel 2 XL running oreo.

**Comment by sibelius** [comment]
Use master and RNCamera 

Also provide stacktrace of the error
