### ISSUE TITLE
Scanning QR code crashes app iOS only

### ISSUE THREAD

**Issue by justynspooner** [react-native-community/react-native-camera#926]
This QR code causes a crash on iOS only.

![screen shot 2017-10-03 at 11 57 44](https://user-images.githubusercontent.com/1853660/31121993-2a062dfc-a832-11e7-8ad9-36f8f3403c26.png)

in `RCTCameraManager.m`

in the method `- (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputMetadataObjects:(NSArray *)metadataObjects fromConnection:(AVCaptureConnection *)connection`

```
@"data": metadata.stringValue,
```

calling stringValue causes the crash.

**Comment by fokoz** [comment]
Mine crashes only when specify `barCodeTypes` to qr but if not specify, it is fine.

**Comment by prajnarobo** [comment]
Any solution for the above issue? App is crashing even after removing barCodeTypes

**Comment by hariDasu** [comment]
this works with the above merged PR, this issue can be closed now @prajnarobo @justynspooner

**Comment by sibelius** [comment]
use RNCamera instead of RCTCamera
