### ISSUE TITLE
barcodeCodes search results adds zero with result 

### ISSUE THREAD

**Issue by ghost** [react-native-community/react-native-camera#929]
```onBarCodeRead(scanResult) {
      if (scanResult.data != null) {
        if (!this.barcodeCodes.includes(scanResult.data)) {
          this.barcodeCodes.push(scanResult.data);
          console.log(scanResult.data);
        }
      }
      return;
    }```

why does it adds zero with result ?

**Comment by casperbakker** [comment]
Without any information about the used barcode and the exact result, nobody can help you...

But maybe you are scanning a 12-character UPC-A code. Then it will be converted to a EAN-13 code with a leading zero. As mentioned in the docs at https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#onbarcoderead

**Comment by simistern** [comment]
Closed for inactivity. Please reopen if this issue is persisting
