### ISSUE TITLE
Location isnt added to data on IOS 11.01

### ISSUE THREAD

**Issue by AnnyA95** [react-native-community/react-native-camera#939]
I want to add the location of the photo so but it isnt added to the data object
<img width="388" alt="schermafbeelding 2017-10-09 om 10 46 23" src="https://user-images.githubusercontent.com/7666541/31330660-926b573a-acdf-11e7-89ff-69a1e256fc0c.png">
<img width="927" alt="schermafbeelding 2017-10-09 om 10 47 58" src="https://user-images.githubusercontent.com/7666541/31330670-97e08d7a-acdf-11e7-8cbe-f484733f59ea.png">

**Comment by taiki-t** [comment]
Yeah, It's happening to me as well. Still looking for a solution.

**Comment by koswarabilly** [comment]
Android also got the same issue
in my project the app crash immediately when trying to capture because of metadata

**Comment by wbyoung** [comment]
It looks like you need to set `location` on the `metadata` rather than on options directly. I just opened #1437 to try to make that more clear.

**Comment by taiki-t** [comment]
> it looks like you need to set location on the metadata rather than on options directly.

That's true. I wasn't looking at the code in the issue description well. But the problem still remains. Even though you set `location` in `metadata`, in iOS 11.x (now 11.2.6) doesn't save photo with location.
