### ISSUE TITLE
Capture image with specific height, width and borderRadius?

### ISSUE THREAD

**Issue by bvv218** [react-native-community/react-native-camera#941]
Is there a way to set up width and height for an image to be captured? For example, if I need a picture with width: 100 and height: 100, and borderRadius of 50, is there a way to capture and save it as a rounded image?

**Comment by josenaves** [comment]
Take a look at this https://github.com/lwansbrough/react-native-camera#capturequality

**Comment by bvv218** [comment]
@josenaves It only allows to change picture quality, not width/height/shape of the image to make it rounded.

**Comment by nakulkundaliya** [comment]
@bvv218  Did you find any solutions of it?

**Comment by allaire** [comment]
For border radius, you must add RNCamera to a view, and use `overflow: hidden`, exemple:

```
<View style={styles.cameraView}>
  <RNCamera
    ref={(ref) => {
      this.camera = ref;
    }}
    style={styles.camera}
    type={RNCamera.Constants.Type.front}
    permissionDialogTitle="Permission to use camera"
    permissionDialogMessage="We need your permission to use your camera phone"
  />
</View>
```

```
...
  cameraView: {
    alignSelf: 'center',
    width: scale(100),
    height: scale(100),
    marginBottom: scale(20),
    borderRadius: scale(100) / 2,
    backgroundColor: colors.grayLight,
    overflow: 'hidden',
  },
  camera: {
    flex: 1,
  },
...
```
