### ISSUE TITLE
Square video capture

### ISSUE THREAD

**Issue by winfysoftware** [react-native-community/react-native-camera#943]
Is there any way to capture square videos using this component?

**Comment by rutger** [comment]
Why not just use `aspectRatio: 1,` on the component?
https://facebook.github.io/react-native/docs/layout-props.html#aspectratio

**Comment by redaben** [comment]
@Rutger When aspectRatio:1 is used, it affects only the camera. The video recorded doesn't have an apsectRatio:1.

**Comment by roycclu** [comment]
@winfysoftware try this video-processor for react native, looks promising. 
https://github.com/shahen94/react-native-video-processing

**Comment by cenaHara** [comment]
hi @redaben  any solution ?
