### ISSUE TITLE
Error: Redefinition of RCTMethodInfo after installing the plugin

### ISSUE THREAD

**Issue by adirzoari** [react-native-community/react-native-camera#944]
Hello,
I opened a new react-native project (latest version V0.49) and after installing the plugin react-native-camera, 
I'm trying to run on ios with XCode (simulator:IPHONE 6 IOS 11) it failed with error:

> Error: Redefinition of RCTMethodInfo

![screen shot 2017-10-11 at 13 07 27](https://user-images.githubusercontent.com/20258998/31434970-ade863a6-ae86-11e7-8e20-d6fec8d1df00.png)

when I run on android it works fine.

**Comment by sibelius** [comment]
fixed on RNCamera
