### ISSUE TITLE
Camera keeps working until the new screen appears

### ISSUE THREAD

**Issue by sharifhh** [react-native-community/react-native-camera#953]
Capture an image and send it to new screen to preview
the camera keeps working

expected, taken picture keeps on until the new screen appears with the preview

how can i make it work like this

**Comment by paynd** [comment]
Me too.

**Comment by afonsodelgado** [comment]
+1

**Comment by alexey-kuznetsov** [comment]
Confirm this bug. On real device with logcat enabled you can see that camera works even if device is blocked.
