### ISSUE TITLE
Snapchat esque functionality

### ISSUE THREAD

**Issue by joecaraccio** [react-native-community/react-native-camera#954]
I was noticing how when taking a picture with the react-native-camera it seems to automatically save to payroll. Is there a way to avoid that?
My goal was to implement it to be snapchat esque where it only really lives in the app, and you wouldn't be able to find it in the camera roll

**Comment by gr33k01** [comment]
Hey @joecaraccio , you can save to temp directory by setting the `captureTarget` prop and retrieve the file path post capture.

So for video:

```js
// render()
<Camera
   ref={ref => this.camera = ref }
   captureMode={Camera.constants.CaptureMode.video}
   captureTarget={Camera.constants.CaptureTarget.temp}
/>

// somewhere else
this.camera
      .capture()
      .then(videoObject => {
          console.log(videoObject); // file path will be in here for you to handle however
      })
```

Read more [here](https://github.com/lwansbrough/react-native-camera#capturetarget).
