### ISSUE TITLE
How can I scan barcode with specific bound ?

### ISSUE THREAD

**Issue by tayathorn** [react-native-community/react-native-camera#962]
I want camera detect only barcode inside specific area. 

something like this picture that scan QRCode only in rectangle frame

![unnamed](https://user-images.githubusercontent.com/31066087/32220860-dcfb192e-be65-11e7-9dc1-a1203584b8cf.png)

Is there possible way to do that ?

**Comment by fogg4444** [comment]
Subscribed

**Comment by fbacker** [comment]
No feature today, I've a pull request on this that you can try out https://github.com/lwansbrough/react-native-camera/pull/874
