### ISSUE TITLE
Requires main queue setup

### ISSUE THREAD

**Issue by tfsjohan** [react-native-community/react-native-camera#971]
I'm getting a warning when running React Native Camera. 

`Module RCTCameraManager requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
`

Is this something that will be fixed soon?

**Comment by ptomasroos** [comment]
Feel free to send a pull request @tfsjohan its because a change in react-native which we haven't implemented yet.

**Comment by stefalda** [comment]
Thanks @ptomasroos
