### ISSUE TITLE
react-native-camera crashes 

### ISSUE THREAD

**Issue by AshokICreate** [react-native-community/react-native-camera#975]
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.5.0
  Yarn: Not Found
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

Package.json
"react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",

0Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000050 Raw Text
--
0 | libdispatch.dylib | dispatch_async + 132
1 | libdispatch.dylib | dispatch_async + 64
2 | _mobile | RCTCamera.m line 184-[RCTCamera changePreviewOrientation:]
3 | _mobile | RCTCamera.m line 114-[RCTCamera orientationChanged:]
4 | CoreFoundation | __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
14 | UIKit | -[UIApplication sendEvent:] + 100
15 | _mobile | UIApplication+interceptEvents.m line 46-[UIApplication(GFInterceptEvents) GFlookback_sendEvent:]
16 | UIKit | _UIApplicationHandleEvent + 404
24 | UIKit | UIApplicationMain + 208
25 |_mobile | main.m line 16main
26 | libdyld.dylib | start + 4

**Comment by sibelius** [comment]
try the new RNCamera on master

https://github.com/react-native-community/react-native-camera#experimental
