### ISSUE TITLE
method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by jslok** [react-native-community/react-native-camera#976]
RN 0.49.5
RN-camera 0.12.0

During build:
\node_modules\react-native-camera\android\src\main\java\com\lwansbrough\RCTCamera\RCTCameraPackage.java:20: error: method does not override or implement a method from a supertype
    @Override
    ^

To solve the issue I removed the entire createJSModules method and it works for me. Not sure how to do a pull request, or if doing this will inadvertently remove compatibility with RN < 0.47 either.

**Comment by koswarabilly** [comment]
just delete the @override line as the compiler error

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
