### ISSUE TITLE
Android perfomance?

### ISSUE THREAD

**Issue by tomislavHonig** [react-native-community/react-native-camera#977]
Any plans to improve Android perfomance. It's still little bit janky and on some phones has a delay of even few seconds when taking picture and opening the camera.

Will the new  android.hardware.camera2 help with the perfomance on devices with api lvl 21 or more? https://developer.android.com/reference/android/hardware/camera2/package-summary.html

**Comment by Cygnus2112** [comment]
+1

**Comment by shubhangi-asgola** [comment]
+1

**Comment by niom** [comment]
+1

**Comment by koswarabilly** [comment]
location metadata maybe?

**Comment by ospfranco** [comment]
Please try the new implementation RNCamera, it is on master and see if it solves your problems
