### ISSUE TITLE
What if there is no info.plist in React-Native project?

### ISSUE THREAD

**Issue by Hiroki111** [react-native-community/react-native-camera#979]
For iOS 10+, it's  one of the requirements to put the "Privacy - Camera Usage Description" key into info.plist.

However, there is no such a file in my project file, maybe because I made this project with `create-react-native-app` command.
In which file should I put this key?

I'll apologise if this question is too basic. I've just started to use React-Native.
Any advice will be appreciated.

**Comment by jgcmarins** [comment]
Hello @Hiroki1116. In your case, as you're using CRNA, you should use Expo API Components. You can find an example here: https://github.com/expo/native-component-list/blob/master/screens/ExpoApisScreen.js#L143

**Comment by Hiroki1116** [comment]
@jgcmarins 
Thank you for your reply.
Could you elaborate on how Expo API can be a substitution of info.plist?
(Does that mean that there is an equivalent of info.plist among Expo API components?)
I've been reading Expo's documentation, but I'm still clueless.

**Comment by giovannipds** [comment]
Still clueless. Did you learn it, @Hiroki111?
