### ISSUE TITLE
runtime permission for camera in android

### ISSUE THREAD

**Issue by milon87** [react-native-community/react-native-camera#986]
Please add runtime permission to access camera for Android

**Comment by jgcmarins** [comment]
Hello, @milon87.
These [permissions](https://github.com/lwansbrough/react-native-camera#permissions) aren't good enough?

**Comment by milon87** [comment]
@jgcmarins  yeah but if I use SDK 26 then it shows a white screen instead of the camera. If permission provided manually then it works again as expected.

**Comment by pavanmehta91** [comment]
Same issue here. It does not ask for permission and the app crashes due to it but If provided manually by going to the settings it works.

**Comment by axsann** [comment]
Use PermissionsAndroid.request() or [react-native-permissions](https://github.com/yonahforst/react-native-permissions).

**Comment by pavanmehta91** [comment]
in IOS i don't have to explicitly ask for permission, Do I've to ask for permissions for android explicitly?

**Comment by milon87** [comment]
@pavanmehta91  yes

**Comment by pavanmehta91** [comment]
Thanks. I implemented the permissions using react-native-permissions module

**Comment by tungbt-2-3-1994** [comment]
Hello Mr. Pavanmehta91, 
Could you share your code to implement react-native-permissions? 
I follow sample code in this component, but request function occurs wrong.
Thanks!
