### ISSUE TITLE
No error and nothing happen when capture image and pass metadata, no metadata in the image

### ISSUE THREAD

**Issue by koswarabilly** [react-native-community/react-native-camera#987]
THIS IS SO FRUSTRATING 
METADATA can not be pass it crash everytime i do that
is there any way to fix that?

@npomfret
i have this code in my project
```

takePicture() {
    const options = {};
    options.location = this.state.location;
    this.camera.capture({ metadata: options })
      .then((data) => console.log(data))
      .catch(err => console.error(err));
  }
```

everytime i press capture the application stop working on android

if this is a duplicate issue please ref me to the solved one

**Comment by zahid-dapperapps** [comment]
+1 having same issue, metadata not being saved

**Comment by zahid-dapperapps** [comment]
@koswarabilly did you find solution?

**Comment by koswarabilly** [comment]
Nope i dont @zahid-dapperapps

**Comment by zahid313** [comment]
@koswarabilly  this file https://github.com/npomfret/react-native-camera/blob/c6aede1c092e9d41b4e47b29f80b69f68de0b1c9/ios/RCTCameraManager.m is supposed to be in master but donot why its not, but If you manually replace the existing one with this it should solve your issue
https://github.com/lwansbrough/react-native-camera/pull/635
