### ISSUE TITLE
Doesn't seem to be picking up qr codes

### ISSUE THREAD

**Issue by IljaDaderko** [react-native-community/react-native-camera#991]
I implemented component to scan qr codes:

```
  // -- methods -- //
  onBarcode = event => {
    console.log(event);
    AlertIOS.alert("Barcode Found!", "Type: " + event.type + "\nData: " + event.data);
  };

  // --- render --- //
  <Camera
    onBarCodeRead={this.onBarcode}
    barCodeTypes={["qr"]}
    aspect={Camera.constants.Aspect.fill}
  />
```

`this.onBarcode` doesn't seem to be triggered, despite me trying camera on 10 different qr codes. (Bitcoin address, post tracking website etc...). Did I implement this correctly and is there a known issue? Possibly related to #989 but in my case downgrading to v0.10.0 didn't help 

**Device:** iPhoneX
**react-native:** 0.50.3
**react-native-camera:** 0.12.0

**Comment by koswarabilly** [comment]
@IljaDaderko if your application do not specified just to scan qr code you do not have to declare barcodeTypes

**Comment by IljaDaderko** [comment]
@koswarabilly it indeed needs to only work with qr type, I removed ` barCodeTypes={["qr"]}` and it started to work 👍 however I would like to add it back after the fix, to ensure only qr codes are being scanned for.

**Comment by koswarabilly** [comment]
@IljaDaderko i think you can use validation instead of declaring barcode type, let the barcodetype as default then make validation in your onBarcode and check event.type , if it is qr then do the action you want if not return null, anyway have you successfully insert location metadata to image capture?

**Comment by IljaDaderko** [comment]
@koswarabilly I wasn't able to insert any metadata I'm afraid, as this is not a part of my app. As for qr specific stuff, yeh thats the approach I took, but will leave this open as this feature was documented in docs and appears to be broken

**Comment by fmsouza** [comment]
@IljaDaderko I was having the same problem after updating to the latest `react-native-camera` release. Then when I tried to do some logs I realized that the qrcode id changed from `qr` to `org.iso.QRCode`.

What solved the issue for me was using the constants provided by the module itself:

```javascript
import { RNCamera } from 'react-native-camera';

const { BarCodeType } = RNCamera.Constants;

// ...

<RNCamera
  style={styles.camera}
  barCodeTypes={[BarCodeType.qr]}
  onBarCodeRead={this.onBarCodeRead} />

// ...

onBarCodeRead({ type, data }) {
  if (type === BarCodeType.qr) {
    // do something
  }
}
```
