### ISSUE TITLE
Tried to register two views with the same name RCTCamera

### ISSUE THREAD

**Issue by PsArvin** [react-native-community/react-native-camera#997]
Device: Android 7.0
react-native: 0.50.3
react-native-camera: 0.12.0

![screenshot_20171121-191432](https://user-images.githubusercontent.com/11503449/33070008-748c9f1a-cef1-11e7-9ebe-d68431ce3d2a.png)

**Comment by krizpoon** [comment]
I met the same problem. In my case, there is another library that declares `react-native-camera` as dependency. I fixed it by deleting the `node_modules/react-native-camera` folder inside that library.

**Comment by sibelius** [comment]
is this an issue?

**Comment by kuailetuoluoren** [comment]
i meet the same problem,
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-camera": "^1.1.2",

**Comment by ducanhmai205** [comment]
how can i fix this issue

**Comment by JulianKingman** [comment]
@krizpoon my hero. I found a few instances of the package in question (in my case `react-native-svg`) installed in other dependencies. Removing those solved the problem. I'd imaging that version mismatches between them contribute to the issue, as I was attempting to change the version number..

**Comment by sibelius** [comment]
RCTCamera is removed https://github.com/react-native-community/react-native-camera/issues/1890

Migrate to latest version of RNCamera
