### ISSUE TITLE
Destroy camera between screens

### ISSUE THREAD

**Issue by oricoh** [react-native-community/react-native-camera#999]
Hi,

I have encountered two problems when using the camera in different screens in the same app.

1. In my app, I load the camera in forced Portrait screen, and later in a different screen I load it in a forced landscape. However the first screen sets the size of the camera and in the second screen it comes up squished and narrow in the center of the screen with the width of the first camera.
2. In another case, I load the camera with a different set of GUI/buttons in 2 different screens, but the result is that in the second screen I see both the GUI one on the top of each other.

How can I stop/reset/destroy the camera so when I load it in a different screen, it comes up as new?

Thanks!

**Comment by harrisrobin** [comment]
If you are using react-navigation, you need to dispatch a reset action so that the camera is unmounted. 

See https://github.com/lwansbrough/react-native-camera/issues/701 for more details.

**Comment by jslok** [comment]
I showed an example of how I unmount the camera between screens using redux here #878

**Comment by diegoool** [comment]
Ive used withNavigationFocus with HOC and this helped me!

import { withNavigationFocus } from 'react-navigation';

class MyWrapComponent extends React.Component {
render() {
return this.props.isFocused ? < CameraComponent /> : <></>;
}
}

export default withNavigationFocus(MyWrapComponent );

**Comment by michael-harley** [comment]
> Ive used withNavigationFocus with HOC and this helped me!
> 
> import { withNavigationFocus } from 'react-navigation';
> 
> class MyWrapComponent extends React.Component {
> render() {
> return this.props.isFocused ? < CameraComponent /> : <></>;
> }
> }
> 
> export default withNavigationFocus(MyWrapComponent );

@diegoool This doesn't work! :(
What version of react, react-native, react-native-camera, react-navigation did you use?
You have another solution maybe? I already tried the Navigation Stack reset too. Still get stuck on react native camera (Happening sometimes, but quite a lot)

**Comment by iDevo** [comment]
Hi @michael-harley! Did you find a solution? I am updated the code to the new react navigation 5 and also tried to use old APIs but unfortunately without success. Switching the camera from one screen to the other leads to a black RNCamera screen.

**Comment by CorentinHeroux** [comment]
Same issue.
